### ISSUE TITLE
[Bug]: when the content overflows the designated borders of the widgets like (checkbox(and groups),select(and groups)it introduces an extra scroll, and the next widget placed below it overlaps

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19598] opened 2023-01-09 16:04 UTC
https://www.loom.com/share/84fd1fa6d7fc4f5faaaafa83bf648c97

**Comment by Sripriya93** [comment] 2023-03-21 14:39
Even though we are not able to reproduce the first half of the issue, second half of the issue is still reproducible, Please check loom 

https://user-images.githubusercontent.com/104895602/226640984-57cb6e66-4328-4dfa-ba69-4adc93b8a9c5.mp4

**Comment by marks0351** [comment] 2023-05-15 05:20
Cannot reproduce this now based on steps mentioned in the loom video. closing the issue.

**Closed by marks0351** 2023-05-15 05:20 UTC
Labels: Bug, Mobile Pod, Responsive Widget
