### ISSUE TITLE
[Feature]: SSH plugin

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#10205] opened 2022-01-06 11:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a user I would like to run few commands or trigger an action on servers. This is possible with ssh

### Why should this be worked on?

SSH plugin will help users build apps to connect to servers

**Comment by Nikhil-Nandagopal** [comment] 2022-01-06 11:14
@yatinappsmith this is a duplicate of #2404 please upvote that issue :D

**Closed by Nikhil-Nandagopal** 2022-01-06 11:14 UTC
Labels: Enhancement, New Datasource
