### ISSUE TITLE
[Bug]: index.lock file issues with Git

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32483] opened 2024-04-08 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I merge branches, I see the git lock error

### Steps To Reproduce

1. Create a git connected application with a few branches.
2. On the last branch, make a few changes and then try to commit the changes. 
3. Commit was taking for ever and did not complete
4. Do a refresh.
5. Now the modal shows no commits. 
6. Assuming that commits have gone through, Try to merge the branch with another.
7. Note an error pops up as below

<img width="1058" alt="Screenshot 2024-04-08 at 12 29 31 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/11f221cd-14e6-4c18-a304-9321af0296b4">

This has been seen by a customer as well. Here is the [frontapp](https://app.frontapp.com/inboxes/teammates/12984076/inbox/open/98277932748)  thread for the same. 

Slack [thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1709921656361529). 

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud v1.18

**Comment by brayn003** [comment] 2024-04-19 09:12
This issue is reproducible, however I am not sure how to solve this. We do have a background task that removes the stale lockfile after a certain amount of time - https://github.com/appsmithorg/appsmith/issues/24854

Need to figure out a better way to solve this

**Comment by btsgh** [comment] 2024-04-30 10:43
Also attaching the slack [thread](https://theappsmith.slack.com/archives/C04HERDNZPA/p1714473570160929) here which deals with handling the UI aspect of this error.

**Comment by nidhi-nair** [comment] 2024-05-14 06:34
@btsgh we have recently merged in a clean up around the locking mechanism, can you check if this issue is still reproducible? If it is, it would then mean that we're attempting parallel operations and need to take a look at the exact API call that is triggering this for you.

**Comment by Shirisha-Manthoju** [comment] 2024-06-06 04:08
Hi @nidhi-nair 

I am not able to reproduce this issue , I was able to commit and merge the branches without any error messages 

I have followed the below steps : 

1. Created a git connected application with a two branches.
2. On the last branch, made few changes and then tried to commit the changes.
3. Commit message have not taken much time 
4. As there are no merge conflicts , I was able to merge the branches successfully. 

Below are the Screenshots 

![merge_loading_from_official_appsmith](https://github.com/appsmithorg/appsmith/assets/119922471/6253e22f-e06b-43e5-8527-89c57305a38c)

![merge_cmplt_from_official_appsmith](https://github.com/appsmithorg/appsmith/assets/119922471/22ec9178-7c5d-41fb-a1e8-55501768c5ad)

Thank you

**Comment by brayn003** [comment] 2024-06-17 07:53
Possible duplicate of https://github.com/appsmithorg/appsmith/issues/32858

**Comment by brayn003** [comment] 2024-06-17 07:59
Additional context on the issue #32858

**Comment by infinitetrooper** [comment] 2024-07-22 10:50
Closing in favour of https://github.com/appsmithorg/appsmith/issues/32858

**Closed by infinitetrooper** 2024-07-22 10:50 UTC
Labels: Bug, High, Production, High effort, Git Version Control, Git Pod
