### ISSUE TITLE
[Bug] Unable to run/connect to app-smith using docker.

### ISSUE THREAD

**Issue by vaibhav-falconx** [appsmithorg/appsmith#3952] opened 2021-04-09 16:48 UTC
## Description

Trying to deploy appsmith using the install.sh script mentioned for self-hosting using docker.  Had to make a few changes to the docker-compose.yaml file (reduced version to 3.3 for docker-compose version and changed the ports for nginx).

[What happened]

After doing the above changes and starting the containers, appsmith internal server fails to start with the following error : 
```
^[[31mappsmith-internal-server_1  |^[[0m  - Opened connection [connectionId{localValue:1, serverValue:1}] to mongo:27017
   97 ^[[31mappsmith-internal-server_1  |^[[0m  - Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true,        version=ServerVersion{versionList=[4, 4, 5]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=16221041}
   98 ^[[31mappsmith-internal-server_1  |^[[0m  - Enabled plugins: []
   99 ^[[31mappsmith-internal-server_1  |^[[0m  - Disabled plugins: []
  100 ^[[31mappsmith-internal-server_1  |^[[0m  - PF4J version 3.5.0 in 'deployment' mode
  101 ^[[31mappsmith-internal-server_1  |^[[0m  - Field 'id' cannot be empty
  102 ^[[31mappsmith-internal-server_1  |^[[0m org.pf4j.PluginRuntimeException: Field 'id' cannot be empty
  103 ^[[31mappsmith-internal-server_1  |^[[0m    at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:918)
  104 ^[[31mappsmith-internal-server_1  |^[[0m    at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:840)
  105 ^[[31mappsmith-internal-server_1  |^[[0m    at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139)
  106 ^[[31mappsmith-internal-server_1  |^[[0m    at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:240)
  107 ^[[31mappsmith-internal-server_1  |^[[0m    at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:61)
  108 ^[[31mappsmith-internal-server_1  |^[[0m    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  109 ^[[31mappsmith-internal-server_1  |^[[0m    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  110 ^[[31mappsmith-internal-server_1  |^[[0m    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  111 ^[[31mappsmith-internal-server_1  |^[[0m    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  112 ^[[31mappsmith-internal-server_1  |^[[0m    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.                                                  invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
  113 ^[[31mappsmith-internal-server_1  |^[[0m    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.                                                 invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
  114 ^[[31mappsmith-internal-server_1  |^[[0m    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.                                                                   postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
  115 ^[[31mappsmith-internal-server_1  |^[[0m    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.                                                                          applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)

```
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Run install.sh
2. Had to reduce the docker-compose version to 3.3 for local docker compose.
3. Changed the ports in nginx to 180 and 1443.
4. Run sudo docker-compose up

The logs for the internal-appsmith-server show the above error.

### Important Details
 - Version: Ubuntu 18.04.1 hosted by AWS
 - Browser : Chrome

**Comment by sharat87** [comment] 2021-04-10 05:44
Hey @vaibhav-falconx, the error message you are seeing is actually harmless. We have an issue open where we intend to get to the bottom of this, but it shouldn't affect the functionality of the server. Can you share more logs from the server container so we can see if there's any other error message perhaps?

Additionally, if it's okay with you, can you share your current `docker-compose.yml` file as well?

**Comment by sharat87** [comment] 2021-04-10 05:44
Issue about the harmless error: https://github.com/appsmithorg/appsmith/issues/3616

**Comment by sharat87** [comment] 2021-04-15 05:37
Downgrading to High from Cititcal, since the error message posted in the description is harmless for the core functionality. We can reevaluate the criticality once we have more information of what the problem is. Thanks!

**Comment by vaibhav-falconx** [comment] 2021-04-15 17:50
I realized later that this was benign. The actual problem was that I was trying to run app-smith on a different port and that was not working. Once I reverted to using the default port, AppSmith started. I think the main thing here is to make the documentation for changing ports more easier to follow. This can be closed as not a bug since there is already a duplicate.

**Comment by sharat87** [comment] 2021-04-16 03:56
Thank you for confirming and providing the details @vaibhav-falconx!

Closing.

**Closed by sharat87** 2021-04-16 03:56 UTC
Labels: Bug, Deployment, High, Platform
