### ISSUE TITLE
[Bug] UX : On creating a space the suggestion are displayed to user and it becomes a little annoying 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6816] opened 2021-08-24 07:54 UTC
Steps to reproduce:
1) Add a JS function
2) Click on the code section
3) Click on space 
and observe suggestions appear

Observation:
It is observed that the suggestion are displayed to user when he wants to create a simple space this would become very annoying to user

Expectation:
the suggestion must be displayed to the user when the slash is typed 
![Screenshot 2021-08-24 at 1 23 02 PM](https://user-images.githubusercontent.com/71753653/130578675-91196de6-7b2f-46c2-b194-815c82d7e261.png)

**Comment by ajinkyakulkarni** [comment] 2021-08-25 10:21
This is duplicate of https://github.com/appsmithorg/appsmith/issues/6243

**Closed by ajinkyakulkarni** 2021-08-25 10:21 UTC
Labels: Bug, Actions Pod, JS, Low, Needs Triaging, Deploy Preview
