### ISSUE TITLE
[Bug]-[33]:Onclick action throws error for table widget with column type Image.

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#13496] opened 2022-05-02 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Onclick action throws error for table widget with column type Image for a new column
![image](https://user-images.githubusercontent.com/92293815/166217624-4122e905-0837-4a2a-86dd-0e74f07b43e7.png)

### Steps To Reproduce

1. Drag and drop table widget
2. Create new column
3. Change column type to Image > Add a computed value
4. Onclick event > Open a modal > observe the error

### Version

cloud

**Comment by dilippitchika** [comment] 2022-05-04 08:57
@shwetha-ramesh just confirming, the only error here is the debugger error right? Because we are able to open the modal with clicking on the image.

**Comment by shwetha-ramesh** [comment] 2022-05-04 10:18
Yes correct @dilippitchika

**Comment by dilippitchika** [comment] 2022-05-05 06:30
112 people configured image in a custom column, assuming 30% configure on click 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 33 |
| Effort (months)  | 0.5 |

**Comment by souma-ghosh** [comment] 2022-08-17 08:59
@shwetha-ramesh @dilippitchika @sbalaji1192 Tested this out, seems to be no longer reproducible in Table Widget V2.

**Comment by souma-ghosh** [comment] 2022-08-17 10:14
@dilippitchika No there is not error in the debugger on clicking on image cell

**Comment by dilippitchika** [comment] 2022-08-17 10:22
Ok, cool we can close it then

**Closed** 2022-08-17 10:50 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low, Production, regression
