### ISSUE TITLE
[BUG] No option to remove an organization

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#613] opened 2020-09-20 09:38 UTC
## Description

I created a new organization. Now I don't need it anymore. I do not see any option to remove this.

### Steps to reproduce the behavior:

1. Create a new organization
2. How to remove that?
![image](https://user-images.githubusercontent.com/13042781/93708367-29c73580-fb53-11ea-92e4-0b9ea049ae0c.png)

### Important Details
 - Version: Cloud
 - OS: MacOSX
 - Browser: chrome

**Comment by Nikhil-Nandagopal** [comment] 2021-02-10 12:17
Duplicate of #2502

**Closed by Nikhil-Nandagopal** 2021-02-10 12:17 UTC
Labels: Needs Design, UX Improvement
