### ISSUE TITLE
[Bug] Inappropriate tool tip in File picker widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5073] opened 2021-06-11 12:15 UTC
Steps to reproduce:
1) Add a file picker
2) Click on the file picker
3) Observe the pop up close option

Observation:
It  is observed that the tooltip for the close option  says "Close Modal"

Expectation:
The tooltip for the close option  must say "Close"
![Screenshot 2021-06-11 at 5 34 42 PM](https://user-images.githubusercontent.com/71753653/121684707-aed8ed00-cadc-11eb-9bf1-a738116f4e46.png)

**Comment by pcastro3** [comment] 2021-06-16 00:50
Hi, I think I found the solution to changing the text from "Close Modal" to simply "Close". However, I can't know if the change actually works because I cannot get the application to run with Heroku. I followed the instructions in the Heroku README, and I have successfully deployed and connected it with MongoDB , but the application will not not display. Instead, it gives me an H10 error, which essentially tells me to upgrade the Heroku plan to get more dynos. Is there a workaround for this, or should I try again with AWS instead? Thanks!

**Comment by somangshu** [comment] 2021-06-16 05:02
Hi @pcastro3 👋, Thanks for showing interest and taking the time to understand more about this. I could not understand why you are trying to deploy to Heroku. Though @sharat87 from my team will be able to help you out with any questions related to that. Otherwise, you can [contribute to Appsmith](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md) with the local environment and then submit a new Pull Request on the release branch (which also creates a deploy preview automatically) to let us know that you wish to submit a Fix/Change related to a listed issue. You can also know more about our code contribution guideline [here](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md).

Regarding this issue, Our team had already taken this up and fixed it. There are many other issues you could look into [here](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+no%3Aassignee), One issue which is an easy fix is [this](https://github.com/appsmithorg/appsmith/issues/4662), please drop in a comment and we will assign it to you 😃.

**Comment by sharat87** [comment] 2021-06-16 05:53
Hey @pcastro3, Heroku's free and hobby dynos are a little inadequate for running Appsmith, but it should only be slow as a result. It shouldn't be throwing up errors, unless the load is super high (which I'm guessing is not the case for you). Can you open a separate GitHub issue and share what Heroku plan you are using and full error message you see. We can continue this discussion there to keep this one on-topic 😄. Thanks!

**Comment by pcastro3** [comment] 2021-06-16 22:34
Hi @somangshu, I was trying to deploy the app so I'd be able to see the changes I made to the local files. That was overkill. I failed to read the doc on how to reproduce the environment locally. My mistake! That being said, yes, it would be great if you could assign the other issue you mentioned to me. Much appreciated!

**Comment by pcastro3** [comment] 2021-06-16 22:34
Hey @sharat87, I opened a new issue like you asked. I'll link it directly to you for the sake of simplicity.

https://github.com/appsmithorg/appsmith/issues/5185

**Closed** 2021-06-22 11:22 UTC
Labels: Bug, File Picker Widget, Good First Issue, Low, Release, UI Building Pod, Widgets
