### ISSUE TITLE
[Bug]: Footer expands and UI distort when Menu button has lot of menu item

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12286] opened 2022-03-28 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1782" alt="Screenshot 2022-03-28 at 2 49 51 PM" src="https://user-images.githubusercontent.com/83569920/160367737-e328230b-1306-4b55-8f12-f6a086e38ab5.png">
<img width="1783" alt="Screenshot 2022-03-28 at 2 48 46 PM" src="https://user-images.githubusercontent.com/83569920/160367757-50ae60a5-b3a3-4b0b-94ac-1fd2f4e7a67d.png">

### Steps To Reproduce

1. Drag and drop a Menu button widget
2. Add around 20 menu item
3. Click on Menu widget
4. Observe that the footer expands and UI do not look good

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-06-15 08:06
Also, on deploy, the menu dropdown functionality is improper on click to close- focus goes to the menu items, instead of the menu getting closed.
https://www.loom.com/share/40d22812c22b4532af0c60730308f84d

Please check #14518 when fixing this

**Comment by VividhPandey003** [comment] 2022-09-26 13:28
Hello Sir, I am a beginner looking forward to contribute to appsmith. 
Could you please explain what tech stack is required and where can I find the code in the repository where I need to fix it.

**Comment by Naveen-Nair** [comment] 2022-10-08 09:57
@dilippitchika Can i work on this issue?

**Comment by dilippitchika** [comment] 2022-10-10 05:36
Hello to fix this issue, we have to limit the number of items and show a scrollbar. We can show a total of 6 items post which we can show a scrollbar. 

Greetings @VividhPandey003 @Naveen-Nair thanks for showing interest 🎉 , This is all yours. Assigning this to both of you for now. Based on the PRs received we will figure out whose code to merge.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Tallon66** [comment] 2022-10-22 02:16
Hi @dilippitchika @dhruvikn. Could I please work on this issue?

**Comment by dhruvikn** [comment] 2022-10-23 10:48
Sure @Tallon66, please take a shot at it. Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. Let us know here.

**Comment by iSatVeerSingh** [comment] 2023-04-04 14:30
Can't reproduce this issue anymore. I think this issue has been fixed.

**Closed** 2023-04-06 10:22 UTC
Labels: Bug, Good First Issue, hacktoberfest, App Viewers Pod, Low, Production, Menu Button Widget, Papercut
