### ISSUE TITLE
[Bug]: create an event for accessing templates tab

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#21012] opened 2023-02-27 19:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the month of January, Mixpanel stopped recording the ROUTE_CHANGE event. 

<img width="1430" alt="Screenshot 2023-02-28 at 01 09 57" src="https://user-images.githubusercontent.com/32227135/221665956-e70a9868-f4a4-48b5-9367-6ca3614deb25.png">

### Steps To Reproduce

Check this Mixpanel dashboard - https://mixpanel.com/s/2NvN6q

### Environment

Production

### Version

V 1.9.9

**Comment by kocharrahul7** [comment] 2023-02-28 03:38
Since this is not a bug, closing this in favour of [this](https://github.com/appsmithorg/appsmith/issues/21024)

**Closed by kocharrahul7** 2023-02-28 03:38 UTC
Labels: Bug, Needs Triaging
