### ISSUE TITLE
[Bug]: Page ordering is incorrect on forking an app

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31538] opened 2024-03-06 07:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page ordering is incorrect on forking an app

### Steps To Reproduce

1. Create an app with multiple pages
2. Fork the app onto the same/different workspace
3. Notice that the page ordering of the forked app is different from the original app

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/924d992ebde9411b855c786acd6f695e?sid=84294046-2306-4cba-8bd4-812de8115cff

### Version

Production v1.16.0

**Comment by laveena-en** [comment] 2024-03-06 07:30
@rohan-arthur I'm assuming this regressed due to IDE changes. Please reassign if it doesn’t come under the purview of the IDE pod

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 07:48
@laveena-en please add the correct product tags when creating an issue

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 07:54
Also looks like a duplicate of #9016

**Closed by Nikhil-Nandagopal** 2024-03-06 07:54 UTC
Labels: Bug, Pages, Production, Regressed, Needs Triaging, Medium, IDE Pod
