### ISSUE TITLE
[Feature] Import Api from a Swagger file

### ISSUE THREAD

**Issue by rmvids** [appsmithorg/appsmith#8114] opened 2021-10-02 11:58 UTC
## Summary

Import Api from a Swagger file

## Motivation

Much easier to do a batch import already, and it is also more natural since swagger(Open Api) is practically standard in the api documentation.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-03 11:10
@rmvids , thank you for the wonderful feature request!

**Comment by kaprinsoftware** [comment] 2023-05-29 11:11
Hello! 
We have built a utility that can import a swagger / openapi spec or a postman collection export into Appsmith by defining Datasources and add all the endpoints defined.
If you are interested in using it, please share your information and we will connect with you https://forms.gle/ia15HNsCtoYHpScaA

**Comment by yozlet** [comment] 2023-08-13 15:16
Please mark this a duplicate of #3920.

**Closed** 2024-05-13 08:00 UTC
Labels: Enhancement, New Datasource, Integrations Pod
