### ISSUE TITLE
[Bug]: The Mongo Mock datasource query fails with Json error 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#32316] opened 2024-04-02 04:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Mongo Mock datasource query fails with Json error 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/7455d9db-19d8-4313-a27b-f80c34e58afa">

### Steps To Reproduce

1. go to release.app.appsmith.com
2. Go to edit mode go to datasource section
3. now add the new datasource i.e Mongo sample datasource 
4. Now before the table loads click on new query button on the right top corner
5. The query is auto filled 
6. Just run the query 
7. The json error is displayed
Note:if the "New query" button is clicked before the datasource structure is ready the query is displayed empty

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.19

**Comment by RakshaKShetty** [comment] 2024-04-02 08:08
couldn't consistently repro the issue would like more debugging on this so reducing the priority here

**Comment by NilanshBansal** [comment] 2024-08-21 07:52
Closing this as couldn't reproduce the issue.

**Closed by NilanshBansal** 2024-08-21 07:52 UTC
Labels: Bug, Low, Production, DevOps Pod, Mock Data
