### ISSUE TITLE
[Bug] Renaming a MongoDB datasource that uses SRV URL breaks all actions until the SRV URL is set again

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#5007] opened 2021-06-10 04:58 UTC
## Description

Noticed that renaming a datasource (I've added MongoDB with URI) temporarily breaks the queries till the URI is edited and re-added.

### Steps to reproduce the behaviour:

1. Create a MongoDB datasource using a URL.
2. Create a simple query to get a document out of this datasource.
3. Verify that this query works.
4. Now rename the datasource.
5. Try the query again, it fails.
6. Now edit the datasource to set the same URL again and save it.
7. Try the query again, it works.

https://user-images.githubusercontent.com/120119/121467143-34be4080-c9d6-11eb-98b0-b3f4027b02b2.mov

### Important Details

- Version: Cloud
- OS: macOS
- Browser: Firefox
- Environment: Production, <https://app.appsmith.com>.

**Comment by ajinkyakulkarni** [comment] 2021-08-24 12:13
@trishaanand Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5007?planning-poker)

**Comment by ajinkyakulkarni** [comment] 2021-08-24 12:14
@trishaanand @ohansFavour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5007?planning-poker)

**Comment by sumitsum** [comment] 2021-11-12 09:17
Re-assigning myself due to pod re-arragnement. @trishaanand please mention if you have already started working on it.

**Comment by sumitsum** [comment] 2022-02-07 02:08
Closing since the issue is no longer seen. I can see a fix handling this case that was added a while ago.

**Closed by sumitsum** 2022-02-07 02:08 UTC
Labels: Bug, Backend, Datasources, Actions Pod, High, community, Needs Triaging, Mongo, BE Coders Pod
