### ISSUE TITLE
[Bug]-[250]:Cmd+click of an entity doesn't scroll the editor to the correct location

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#22001] opened 2023-04-03 04:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The JS object pane should support basic keyboard shortcuts that help developers write code faster and more effectively

Cmd+click of an entity doesn't scroll the editor to the correct location. The cursor is put correctly but the editor doesn't scroll. This is confusing to the user.

### Steps To Reproduce

Open the JS editor and perform any/all of the actions defined above to see behaviour

### Environment

Production

### Version

1.6.6

**Comment by bharath31** [comment] 2023-04-03 10:23
@rimildeyjsr let me know if this [loom video](https://www.loom.com/share/03c172786a9746d9bf80492ffc2d846d) helps :)

**Comment by bharath31** [comment] 2023-04-03 13:55
Assuming 0.25% of users who perform ROUTE_CHANGE face this issue 
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 250 |
| Effort (months)  | 0.5 |

**Comment by rohan-arthur** [comment] 2024-05-22 10:06
duplicate of #33420

**Closed by rohan-arthur** 2024-05-22 10:06 UTC
Labels: Bug, Low, Production, FE Coders Pod, JS Usability, IDE Navigation
