### ISSUE TITLE
[Bug]: shows schema not available until its loaded 

### ISSUE THREAD

**Issue by ganganimaulik** [appsmithorg/appsmith#13584] opened 2022-05-05 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**No information available/shows schema not available** displayed until real error message/data appears. 

should display **Loading..** message

https://user-images.githubusercontent.com/10296400/166870595-dbb60443-6a67-48da-8d9c-bcc222450fa5.mp4

### Steps To Reproduce

1. add sample users datasource (its same for any/most datasources)
2. try to expand it as shown in video

### Version

cloud

**Comment by ginilpg** [comment] 2022-10-04 04:57
@somangshu Can we close this ticket? Is this done?

**Comment by somangshu** [comment] 2022-10-04 05:37
@ginilpg I am not sure about this. Looks like the issue is related to datasource in entityexplorer.

**Comment by AmanAgarwal041** [comment] 2023-07-12 06:48
Closing as the featured branch is merged

**Closed by AmanAgarwal041** 2023-07-12 06:48 UTC
Labels: Bug, Datasources, Entity Explorer, Low, Needs Triaging, BE Coders Pod, New Developers Pod, Integrations Pod
