### ISSUE TITLE
[Bug]: Phoneinput drop down opens away from the widget 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#20215] opened 2023-01-30 10:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When phoneinput widget is dropped on the canvas below the viewport and `Change Country Code` is toggled on, the dropdown opens up away from the widget at the start of the canvas. Refer [video](https://loom.com/share/6cfdcdbcdf374b7494339179fe8cebe0)

### Steps To Reproduce

1. Drag and drop phone input widget at the very bottom of the canvas
2. Toggle on `Change Country Code`
3. Click on the drop down on the widget

### Issue video log

https://loom.com/share/6cfdcdbcdf374b7494339179fe8cebe0

### Version

Cloud

**Comment by dilippitchika** [comment] 2023-03-13 10:01
Closing as duplicate of #18561

**Closed as not planned by dilippitchika** 2023-03-13 10:01 UTC
Labels: Bug, UI Improvement, Widgets Product, Low, Production, Needs Triaging, Phone Input Widget, Widgets & Accelerators Pod
