### ISSUE TITLE
[Feature]: Code editor widget

### ISSUE THREAD

**Issue by iwesselk** [appsmithorg/appsmith#16703] opened 2022-09-12 21:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a code editor widget with syntax highlighting. I suggest rendering ACE in place. 

Needs the following options on the widget:
* Choose the syntax highlight mode. IE Javascript, SQL, etc.
* The contents of the code editor
* Auto completion suggestions? (TODO: Look into if this is practical to feed in)
* OnChange listener
* OnSave listener?

### Why should this be worked on?

This feature would allow appsmith to be used to create tools that can be more developer focused. Things like SQL generators, code configuration, yaml, and raw json. 

Currently my workaround is to use an IFrame. Every code update causes the full IFrame to re render, rather than just the code changes.

**Comment by iwesselk** [comment] 2022-09-12 21:38
I am willing to take a look at this @Nikhil-Nandagopal I'm not sure why it auto assigned to you, or if I can assign it to myself to look at. I also spoke with @AS-Laguna in discord.

**Comment by AS-Laguna** [comment] 2022-09-12 21:53
@iwesselk No worries! It auto assigns to him as he's both a user and a bot 😋

**Comment by AS-Laguna** [comment] 2022-09-12 21:55
Thanks for requesting and looking at this @iwesselk!

**Comment by dilippitchika** [comment] 2023-04-13 12:34
Closing as duplicate of #19429

**Closed by dilippitchika** 2023-04-13 12:34 UTC
Labels: Enhancement, App Viewers Pod, New Widget
