### ISSUE TITLE
[BUG] Docker setup issues/improvements

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#688] opened 2020-09-23 07:32 UTC
## Description

When someone wants to set up appsmith's front-end using docker and Nginx configuration, it has a port issue.

AppSmith template config uses `port 80` as default for listening the browser requests. Most of Linux/macOs versions have default port 80 used by their apache2. Since same port is already bind with another request, it can't listen to new service that is being started by AppSmith Docker setup.

![image](https://user-images.githubusercontent.com/13042781/93980947-ee1fac00-fd9c-11ea-8e92-f728b0eab219.png)

**Solutions:**
1. Change default port of nginx template
2. Or give a way to modify it with ease and explain in the documentation for the contributors.

### Important Details
 - Version: Self-Hosted
 - OS: MacOSX

**Comment by Nikhil-Nandagopal** [comment] 2020-09-30 08:55
Duplicate of #762

**Closed by Nikhil-Nandagopal** 2020-09-30 08:55 UTC
Labels: Deployment, Enhancement
