### ISSUE TITLE
Users don’t test their datasources before saving it, leading to saving invalid connections

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32182] opened 2024-03-28 07:22 UTC
https://www.notion.so/Users-don-t-test-their-datasources-before-saving-it-leading-to-saving-invalid-connections-190c46337bce45faa0e33a97a4d0982c

**Comment by sribalajig** [comment] 2024-03-28 11:57
Duplicate of - https://app.zenhub.com/workspaces/activation-6604f423cc09d10016792707/issues/gh/appsmithorg/appsmith/32151

**Closed** 2024-03-28 11:57 UTC
Labels: Task, Activation Pod, Activation
