### ISSUE TITLE
[Feature] Easier deployment through docker compose

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3853] opened 2021-04-03 20:27 UTC
## Summary
An easier deployment method with `docker compose`

## Motivation
`docker compose` is easier to handle than bash scripts for devOps

**Comment by Nikhil-Nandagopal** [comment] 2021-04-05 06:00
@riodeuno duplicate of #2402

**Closed by Nikhil-Nandagopal** 2021-04-05 06:00 UTC
Labels: Deployment, Platform, community
