### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3882] opened 2021-04-06 10:35 UTC
Description 
Copy widget functionality is not working in safari version - 

Expected Result:
User should be able to Copy widget either by Command+C or clicking on Copy icon from the Property pane and paste using Command+V

Actual Result:
User is not able to create copy of an existing widget

### Steps to reproduce the behaviour:
1.Launch Appsmith in Deploy environment
2.Drag and Drop list widget or any other widget 
3. Copy widget by either clicking on Copy icon from property pane or select and press Command+C
4.  Press Command+V and observe

**Video Link:**
https://www.loom.com/share/65175b19c9a840f3b921b3122151ef4e

### Important Details
 - Version: Version 12.1.2 (14607.3.9)
 - OS: Mac
 - Browser: Safari

**Comment by hetunandu** [comment] 2021-04-06 10:37
Duplicate of #3881

**Closed by hetunandu** 2021-04-06 10:37 UTC
Labels: Bug, Needs Triaging
