### ISSUE TITLE
[Bug]: MultiSelect widget decreases in height when more options are selected

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13970] opened 2022-05-19 16:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The different types of select widget have different box heights if the selected options width exceeds the box width.

![image](https://user-images.githubusercontent.com/101155659/169347864-21294c07-9b85-485c-93c0-7bc24a9977bb.png)

### Steps To Reproduce

1. Open a new app.
2. Drag one of each select-style widget and place them side by side.
3. Select multiple things in the multi select widgets.
4. Resize the multi-select widget to a smaller width than the options selected.
5. Observe that the height of the box decreases.

### Version

Cloud 1.7

**Comment by dilippitchika** [comment] 2022-05-20 07:17
Happens in multi select widget 

Loom video - `https://www.loom.com/share/ad94ee328d7d4725bd274d320a54f305`

**Comment by dilippitchika** [comment] 2022-05-20 07:18
@souma-ghosh assigning this to you to understand why this is happening, only then we will work on the fix.

**Comment by souma-ghosh** [comment] 2022-05-26 11:46
@dilippitchika 
So far it seems like a problem with the parent container size of the Multiselect. The one with lesser height has the unusual behaviour (Multiselect2). When we change the label position from left to top the initial height of the parent container does not change. As a result the inside contents overflow. When this overflow happens the Select component tries to adjust its height to fit into the parent container when there is a disturbance in the inner content i.e. Green, Red, +1 more.
I am still investigating into this to find a solid cause.
One work around that fixes the issue is setting "flex-shrink: 0" to the select component which is shrinking in height.

**Comment by dilippitchika** [comment] 2022-05-27 10:39
Also needs to be fixed in JSON form #13777

**Comment by souma-ghosh** [comment] 2022-07-13 06:04
@dilippitchika On further investigation this issue seems like it might get fixed with dynamic height. This is because when the container height is adjusted manually according to the content inside, the Multiselect input no longer changes height as mentioned in the issue. Should we hold this off?

**Closed** 2022-07-20 08:56 UTC
Labels: Bug, App Viewers Pod, Low, MultiSelect Widget
