### ISSUE TITLE
[Bug]: In a git connected application,  omnibar shows entities of other branches which do not exist on current branch, on clicking these gives resource not found error.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#19240] opened 2022-12-27 06:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app is connected to git, and there are certain entities e.g. page1 that exist on master and not on child branch, on switching to child branch and using Navigate to option in omnibar, the page1 option is displayed, clicking on it gives resource not found error.Also the CTAs for adding queries/ widget disappear, and on clicking show all datasources show queries in disabled state

https://user-images.githubusercontent.com/80334441/209622007-a1183644-9014-4024-a7c8-a221d51be0af.mov

### Steps To Reproduce

1. In a git connected app, have multiple pages with datasource.
2. Create a new branch branch1 from master
3. Switch to master and delete one Page, commit and push changes
4. Switch to branch1 and open Omnibar , click on Navigate
5. Observe deleted page shows up in omnibar , click on it.
6. Resource not found error is thrown along with that + icon for queries and widget disappear

### Version

Release

**Comment by infinitetrooper** [comment] 2023-11-24 12:02
Duplicate of #17493

**Closed by infinitetrooper** 2023-11-24 12:02 UTC
Labels: Bug, High, Git Version Control, Git Pod
