### ISSUE TITLE
[Bug]: Sorting by a column and then removing it results in a blank table

### ISSUE THREAD

**Issue by anupamck** [appsmithorg/appsmith#18178] opened 2022-11-15 18:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Database blanks out when table is first sorted by a column, and then the column is removed from the database query. 

### Steps To Reproduce

1. Link a table to a database 
2. Write a query to display data e.g. `SELECT * FROM contacts LIMIT 10;`

![image](https://user-images.githubusercontent.com/34277143/201995929-15de0cef-51e5-4765-9cf9-e3ece7257eb6.png)

3. Sort that table by a particular column (say the `ID` column)
4. Remove that column from the database query ` SELECT name, frequency FROM contacts LIMIT 10;`

The table is now blank.

![image](https://user-images.githubusercontent.com/34277143/201995818-ef420181-7269-4d6c-bf27-27174955e817.png)

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-12-21 04:39
Approach: If the column sorted by is not found in the data, please reset the table

**Comment by dilippitchika** [comment] 2022-12-21 05:04
Duplicate of #15238

**Closed by dilippitchika** 2022-12-21 05:04 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low, Needs Triaging
