### ISSUE TITLE
[Feature] UI list of page names in NavigateTo action selector

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2343] opened 2020-12-24 03:32 UTC
## Summary
A UI mechanism to select a page when using the `navigateTo` action.

## Motivation
Some applications have a lot of pages, and it can be difficult to keep track of the page names. Having a UI list, will help users not lose context of the action selector and still browse through the page names.

**Comment by Nikhil-Nandagopal** [comment] 2021-11-10 12:20
Duplicate of #1033

**Closed by Nikhil-Nandagopal** 2021-11-10 12:20 UTC
Labels: Enhancement, Actions Pod, JS, community, FE Coders Pod
