### ISSUE TITLE
[Bug]when creating a new table in Snowflakes in the response tab the text is not displayed fully in the table

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6056] opened 2021-07-21 14:18 UTC
## Description when creating a new table in Snowflakes in the response tab the text is not displayed fully in the table

[What happened]

### Steps to reproduce the behaviour:

https://loom.com/share/b5439c4b8eff49b8bda787cb26dcc579

### Important Details

- Version: [Cloud ]
- OS: [Mac]
- Browser [Safari]
- Environment [release frozen]

**Comment by Nikhil-Nandagopal** [comment] 2021-08-23 10:01
Duplicate of #4263

**Closed by Nikhil-Nandagopal** 2021-08-23 10:01 UTC
Labels: Bug, Datasources, Actions Pod, Low, Needs Triaging
