### ISSUE TITLE
[Bug]: Table row height doesn't always align with the canvas grid and cuts the last row short

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#22104] opened 2023-04-05 01:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I expand a table vertically, I expect to be able to snap the height in such a way that all rows are fully visible.

Instead, sometimes the last row gets cut off due to a mismatch in the table dimensions and the canvas grid.

### Steps To Reproduce

1. Drag a table widget to the canvas.
2. Try to line it up with each row.
3. Observe that it's impossible to line it up perfectly with all rows.

### Environment

Production

### Version

Cloud v1.9.14-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_93m6k)

**Comment by Gabriel-Azevedo** [comment] 2023-04-05 15:55
I completely agree with this issue. As a user, I also expect to be able to fully see all rows in a table when expanding its height vertically. It can be frustrating when the last row gets cut off due to a mismatch in the table dimensions and the canvas grid.

Thanks for bringing this up and I give a 👍 for fixing this issue.

**Comment by Nikhil-Nandagopal** [comment] 2023-04-08 09:57
This is a duplicate of #20831 we'll fix this soon

**Closed by Nikhil-Nandagopal** 2023-04-08 09:57 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low, Needs Triaging
