### ISSUE TITLE
[Task]: Export app with module definition and reference

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#24637] opened 2023-06-19 18:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

[Discussion on Slack](https://theappsmith.slack.com/archives/C054KQSN6M8/p1685965236090949)

_No response_

**Comment by subrata71** [comment] 2023-06-22 06:21
We should include the definition of packages, modules, and module instances as part of the exported JSON of an application. If we don't include all the details then the import might fail when the exported file is imported in a different workspace given that the prerequisite packages and modules don't exist in the destination workspace. In that way, we will lose the portability of the exported file.

cc: @dilippitchika

**Comment by dilippitchika** [comment] 2023-06-22 07:23
@subrata71 i agree, because without it the app will be in a broken state.

**Comment by subrata71** [comment] 2023-06-22 07:34
@dilippitchika That means we will also need to include the definition of the nested packages (package inside another package).

**Comment by dilippitchika** [comment] 2023-06-22 08:45
Yes, i was aware of it.

**Comment by subrata71** [comment] 2023-06-22 14:21
If the exported JSON (with modules and packages inside it) is imported into a different workspace, then a new instance of the packages and associated modules will be created. 

In this case, these newly created packages will be detached from the original packages. These newly created packages can be treated as forked packages. Thus any future updates made to the original packages will not propagate to these forked packages. 

cc: @dilippitchika

**Comment by subrata71** [comment] 2023-06-26 12:36
As discussed with @dilippitchika , we are not going to include the definition (aka code) of packages and modules in exported app JSON. We will only include the information related to module instances used in pages. Module instance will have the required information of the package and module it belongs to. 

**Caveat**
If an app is exported given that the app uses modules inside it, the exported file only works in the same workspace that the package belongs to. It won't work if it's imported in a different workspace. 

**How to solve that?**
Once we implement the import/export of the package, then we will be in a condition to tackle such a problem either by importing the package first and then the app or introducing a new export/import flow keeping everything (app JSON, package JSON, module JSON, order of import instruction, etc.) required in a zip file.

**Comment by subrata71** [comment] 2023-06-30 10:33
### Why Package import/export should be under the scope of Phase 1?

There's a use case where companies manage their **staging** and **production** environments through two different workspaces. 

**Staging workspace**
App1

**Production workspace**
App1

If the new changed introduced in **App1** under the staging environment works well, then they push the changes to the remote repository (The app is Git connected). And in the production workspace, they pull the latest changes in **App1**.

Please note that **Staging.App1** and **Proudction.App1** are connected to the same remote repository.

**Comment by subrata71** [comment] 2023-06-30 11:01
### What's the problem if we include the definition aka code of packages and modules in the App JSON file?

This is the current directory structure of Git in Appsmith. Any changes made in any file of this hierarchy will result in uncommitted changes.
#### Git Directory Structure (Current)
![Git Direcotry structure-current](https://github.com/appsmithorg/appsmith/assets/3524599/22463d16-f294-4076-a80c-9c56dd823196)


Now, if we decide to include the definition (code) of all the used packages and modules in the app JSON file (exported JSON file of an application) then the Git directory structure would look like below

#### Git Directory Structure (With packages and modules)
![Git Directory structure-with packages](https://github.com/appsmithorg/appsmith/assets/3524599/c1a0b6b4-8448-4eb6-a8bd-c49711634a04)

Let's say the package owner makes some changes in the existing modules and publishes the package. Please note that a package can have only one published version and upon publishing new version overrides the previously published version. Now users will see uncommitted changes in their applications even though they haven't made any changes in their applications. This is because we included the definition of packages and modules in the app JSON file. This is a really bad UX and we should not walk through this path.

**Comment by infinitetrooper** [comment] 2023-07-03 17:40
> ### Why Package import/export should be under the scope of Phase 1?
> #### Use case
> There's a use case where companies manage their **staging** and **production** environments through two different workspaces.
> 
> **Staging workspace** App1
> 
> **Production workspace** App1
> 
> If the new changed introduced in **App1** under the staging environment works well, then they push the changes to the remote repository (The app is Git connected). And in the production workspace, they pull the latest changes in **App1**.
> 
> Please note that **Staging.App1** and **Proudction.App1** are connected to the same remote repository.
> 
> Assuming that in the staging environment, some modules of a package have been used in App1. While pushing the changes to the remote repository the change will only include the module instances information.
> 
> Staging (PackageA is available at this workspace)
> 
> * Go to App1
> * Install PackageA {moduleX, moduleY} in App1
> * Use moduleX and moduleY in Page1
> * Push changes to remote repository
> 
> Production (PackageA is not available at this workspace)
> 
> * Go to App1
> * Pull changes
> * Found that the app is broken because it has dependency on moduleX and moduleY and transitive dependency on PackageA
> 
> ### Solution
> * Export PackageA
> * Go to the production workspace
> * Import PackageA
> * Open App1
> * Now pull changes from remote repository of App1
> * App1 will work as the required package is now installed
> 
> ### Alternative solution
> Allowing the user to copy a package to another workspace will also solve the issue.
> 
> ### **Blocker**
> We need an identifier for a package. We cannot rely on the name of a package to be the identifier since the package name is supposed to be unique in the workspace it belongs to. Again, we cannot rely on the UUID of a package because the same package will have a different UUID if it's copied/imported in a new workspace.

**A couple of points on the flow**

1. The workspaces might be across instances in some cases as customers use git with multiple instances for physical isolation between environments. This setup is more likely with power users of modules as well as they cater to the same customers.
2. We're gonna introduce continuous delivery to make the process of pulling changes in production automatic. We need to take this into consideration and the git solution for modules we arrive at needs to lend itself to that kind of automation.

**Comment by infinitetrooper** [comment] 2023-07-03 17:47
> Let's say the package owner makes some changes in the existing modules and publishes the package. Please note that a package can have only one published version and upon publishing new version overrides the previously published version. Now users will see uncommitted changes in their applications even though they haven't made any changes in their applications. This is because we included the definition of packages and modules in the app JSON file. This is a really bad UX and we should not walk through this path.

@subrata71 - I don't necessarily think this is a problem, publishing a new version of the module does update the design/functionality of an app. IMO, that change should show up for users. 

One open question I have is - what is the expected behavior when a new module version is published? Does the change automatically reflect to end users (or) does the developer need to publish the app again? asking because this has implications on git flow as well.

**Comment by subrata71** [comment] 2023-07-05 06:23
@infinitetrooper 
> @subrata71 - I don't necessarily think this is a problem, publishing a new version of the module does update the design/functionality of an app. IMO, that change should show up for users.

Not all the updates mean to be bringing changes in the design/functionality of an app. For example, the module editor can add some comments to the query and publish it. That doesn't change the functionality of the app but it will result in uncommitted changes in the app if we decide to include the definition aka code of the modules and packages in exported app JSON file. 
 
> One open question I have is - what is the expected behavior when a new module version is published? Does the change automatically reflect to end users (or) does the developer need to publish the app again? asking because this has implications on git flow as well.

When a new version is published it overrides the previously published version since a package can have only one published version in phase 1. The change will propagate to all the applications where this particular package is used automatically.

**Comment by subrata71** [comment] 2023-07-05 06:25
@infinitetrooper 
> **A couple of points on the flow**
> 
> 1. The workspaces might be across instances in some cases as customers use git with multiple instances for physical isolation between environments. This setup is more likely with power users of modules as well as they cater to the same customers.
> 2. We're gonna introduce continuous delivery to make the process of pulling changes in production automatic. We need to take this into consideration and the git solution for modules we arrive at needs to lend itself to that kind of automation.

We are planning to implement Git version control for packages in phase 2. Once we have that, we can achieve what you just mentioned here. 

cc: @dilippitchika

**Comment by infinitetrooper** [comment] 2023-07-05 08:10
> We are planning to implement Git version control for packages in phase 2. Once we have that, we can achieve what you just mentioned here.

On this, it doesn't have anything to do with package versioning. When customers use the same app across instances and those apps contain packages, the app should be self-sufficient when it's synced across instances. Manual importing and updation of packages is poor UX and an avenue for manual errors. We should avoid it at all costs.

**Comment by subrata71** [comment] 2023-07-07 07:36
We need a direction to go with from the Git team. We will have a meeting early next week on this. We need to decide what solution is the most suitable considering the following traits of it

1. Better user experience
2. Less implementation complexity
3. Extensibility
4. Minimized risks
5. Easily reversible
6. Compatible w.r.t. the speed breakers


As we discussed, we will keep this in the blocked state and spill over the next sprint.

cc: @dilippitchika @somangshu

**Comment by subrata71** [comment] 2023-07-22 10:27
### Outcome
We have decided not to include the module and package definition in the exported app JSON file. We will only include the module instances used on different pages.

Structure of **Application.json** file with module instances

```
{
  "clientSchemaVersion": 1.0,
  "serverSchemaVersion": 6.0,
  "exportedApplication": {
    "name": "Untitled application 2",
    "isPublic": false,
    "pages": [No change],
    "publishedPages": [No change],
    "viewMode": false,
    "appIsExample": false,
    "unreadCommentThreads": 0.0,
    "color": "#D6D1F2",
    "icon": "system",
    "slug": "untitled-application-2",
    "unpublishedCustomJSLibs": [],
    "publishedCustomJSLibs": [],
    "unpublishedPackages": [
      {
        "id": "<Package UUID>"
      }
    ],
    "publishedPackages": [
      {
        "id": "<Package UUID>"
      }
    ],
    "evaluationVersion": 2.0,
    "applicationVersion": 2.0,
    "collapseInvisibleWidgets": true,
    "isManualUpdate": false,
    "deleted": false
  },
  "datasourceList": [No change],
  "customJSLibList": [No change],
  "installedPackageList": [
    {
      "id": "<Package UUID>"
    }
  ],
  "pageList": [No change],
  "moduleInstanceList": [
    {
      "id": "Page1_ModuleX1",
      "packageId": "UUID",
      "moduleId": "<Module Name>",
      "type": "QUERY",
      "pageId": "Page1",
      "unpublishedModuleInstance": {
        "name": "ModuleX1",
        "publicActionId": "<Will come from the module by module id>",
        "inputs": [],
        "configMap": {
          "childActionId1": {
            "confirmBeforeExecute": true,
            "executeOnLoad": false
          }
        },
        "dynamicBindingPathList": {
          "key": "body"
        },
        "jsonPathKeys": {}
      },
      "publishedModuleInstance": {
         ...
      }
    }
  ],
  "actionList": [No change],
  "actionCollectionList": [No change],
  "updatedResources": {
    "customJSLibList": [No change],
    "actionList": [No change],
    "moduleInstanceList": [
      "ModuleX1##ENTITY_SEPARATOR##Page1"
    ],
    "pageList": [No change],
    "actionCollectionList": [No change]
  },
  "editModeTheme": {No change},
  "publishedTheme": {No change}
}
```


### [View on Miro](https://miro.com/app/board/uXjVPniSQ7U=/?moveToWidget=3458764559758153713&cot=14)

**Comment by subrata71** [comment] 2023-07-22 10:32
Reopening this issue as closing it in between two sprints doesn't get reflected in the Burndown report.

**Closed** 2023-07-24 06:25 UTC
Labels: Backend, Task, Modules pod
