### ISSUE TITLE
[Bug]  Appsmith server is unavailable after installing with Kubernetes install script

### ISSUE THREAD

**Issue by koolay** [appsmithorg/appsmith#4201] opened 2021-04-29 02:31 UTC
## Description
The home page dose not work after installing using k8s.install.sh.

[What happened]
It can not display the editor page.

### Steps to reproduce the behaviour:
1. install using k8s.install.sh
2. `kubectl port-forward service/appsmith-editor 80:80`
3.  open the page: `http://localhost`
4.  Allways a error page with "Appsmith server is unavailable"

All pods are ok.
```
redis-statefulset-0                         1/1     Running   0          17m
mongo-statefulset-0                         1/1     Running   0          17m
appsmith-internal-server-79c999fbb6-jf8jn   1/1     Running   0          10m
appsmith-editor-559b988c66-hnm5h            1/1     Running   0          10m

```

**Comment by zdb999** [comment] 2021-04-29 04:18
I had this issue. The problem is that the front end expects to talk to the back end service through from the browser on certain routes. This means that Appsmith doesn't work on Kubernetes through port forwarding, you have to set up an ingress controller.

If you want to protect it from the outside world, you can disable account sign ups and/or use your reverse proxy to add another auth layer (I used basic auth, with TLS enabled.) If you have access to the actual machines in the Kubernetes cluster, you could also probably access it through a VPN that sits outside Kubernetes.

I have a Helm chart with my configuration. It's not fit for public consumption right now, but I could probably clean it up and release it if people are interested.

**Comment by Nikhil-Nandagopal** [comment] 2021-04-29 06:12
@zdb999 thank you for another great bug report! 
@sharat87 @mohanarpit can you please have a a look?

**Comment by sharat87** [comment] 2021-05-20 07:25
Hey @koolay, sorry for the delay in responding on this. Can you confirm the Kubernetes version you are working with? The script has been tested to work with v1.18.0 only.

**Comment by optit-shraddhansu** [comment] 2021-05-25 20:16
Hi @Koolay, We recommend you to check if Nginx Ingress controllers is configured, as our application doesn't run on port forwarding.
You can make use of this command to get this installed, if it is not.


--> kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/aws/deploy.yaml


--> kubectl get ingress
NAME               CLASS    HOSTS   ADDRESS          PORTS   AGE
appsmith-ingress   <none>   *       XXX.XXX.XX.XXX   80      2m

you can see the application live on link Under  ADDRESS column.

**Comment by koolay** [comment] 2021-05-26 05:20
@sharat87 @optit-shraddhansu 
Thanks, I will check it.

**Comment by Nikhil-Nandagopal** [comment] 2021-06-04 06:13
@koolay I'm closing this issue. If you're still facing trouble please feel free to re-open it :)

**Closed by Nikhil-Nandagopal** 2021-06-04 06:13 UTC
Labels: Bug, Critical, Deployment, Needs Triaging, Platform

**Comment by Hokwang** [comment] 2021-06-18 09:46
@zdb999 please look at https://github.com/appsmithorg/appsmith/pull/2558 and you can provide helm chart first version.
