### ISSUE TITLE
[Bug]: The hand icon should not be displayed when the workspace context menu is not clickable

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18804] opened 2022-12-09 05:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The hand icon should not be displayed when the workspace context menu is not clickable
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206632514-e2632a93-7af5-44ce-9e94-9c254aa1ee3a.png">

### Steps To Reproduce

1. Login as admin
2. create. new role with only view access for app
3.  assign it to user 1
4. Login as user 1
5. hover on the context menu of the workspace 
6. the hand icon is displayed but when we click its not clickable

### Version

localhost

**Comment by ankitakinger** [comment] 2022-12-09 05:45
Duplicate of [#18743](https://github.com/appsmithorg/appsmith/issues/18743

**Closed by ankitakinger** 2022-12-09 05:45 UTC
Labels: Bug, Needs Triaging, Deploy Preview, Team Managers Pod, RBAC
