### ISSUE TITLE
[Bug]: Munbyn barcode scanner is unable to scan into our Input widget

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#24165] opened 2023-06-06 19:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Nothing happens when I scan a FedEx barcode with my Munbyn scanner using the Scanwedge mobile app, and the browser is focused on an Appsmith input.

I expect the value to be read into the input. This works with other text inputs like the browser address bar. This also works with a Honeywell scanner.

I will update this issue with the model number of the scanner when this info is shared with us.

### Steps To Reproduce

1. Drag an input onto the canvas.
2. Start the ScanWedge app on the Munbyn scanner.
3. Focus the cursor on the input in Appsmith.
4. Attempt to scan a FedEx barcode into the input.

### Environment

Production

### Version

Cloud v1.9.20.4

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b2v4c)

**Comment by somangshu** [comment] 2023-09-20 06:38
Works for me. Closing because its non reproducible. 
https://github.com/appsmithorg/appsmith/assets/11089579/92f583ff-2267-4b81-ab31-b99fd1c6f08c

Steps to resolve:
- Code scanner `onCodeDetected`, call a JS function, that sets the value in the the input widget using the `setValue` internal prop
- Scan the code and see that the input widget has the test from QA scanner.

**Closed** 2023-09-20 06:38 UTC
Labels: Bug, Input Widget, App Viewers Pod, Low, Needs Triaging
