### ISSUE TITLE
[Bug]: Cursor is hidden in Table inline edit mode

### ISSUE THREAD

**Issue by hunter-xue** [appsmithorg/appsmith#32237] opened 2024-03-29 03:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

edit data in table, there is no cursor displayed in the cell. 

### Steps To Reproduce

create a simple app and put a table component on the page. 
bind data source to this table. 
CRUD functions working well, but no cursor displayed in editing cell. 

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

self hosted the lastest version with docker

**Comment by Nikhil-Nandagopal** [comment] 2024-03-29 08:30
@sbalaji1192 we're seeing the same issue while adding a new row

**Comment by Nikhil-Nandagopal** [comment] 2024-04-01 16:36
@hunter-xue I'm not fully able to reproduce this. Can you share a video?

**Comment by hunter-xue** [comment] 2024-04-02 15:12
> @hunter-xue I'm not fully able to reproduce this. Can you share a video?

np, but I need few days to re-deploy my test env.

**Comment by hunter-xue** [comment] 2024-04-05 05:39
> @hunter-xue I'm not fully able to reproduce this. Can you share a video?

![image](https://github.com/appsmithorg/appsmith/assets/4905312/c384d961-ba07-45aa-adcc-96e7f04f601b)

let's have a look, and there is no curosr displayed in highlight line col 2. 

BTW: I have updated to version 1.19

**Comment by Nikhil-Nandagopal** [comment] 2024-04-05 07:52
@hunter-xue which browser are you on? As you can see, I really cannot reproduce this

https://github.com/appsmithorg/appsmith/assets/3897254/5891b927-f7e7-4161-8d53-4703ee001ad5

**Comment by hunter-xue** [comment] 2024-04-05 10:05
> @hunter-xue which browser are you on? As you can see, I really cannot reproduce this
> 
>  Screen.Recording.2024-04-05.at.1.21.32.PM.mov

yes, you are right, I use edge browser latest version on MacBook. Let me try this in other browsers.

**Comment by hunter-xue** [comment] 2024-04-05 10:25
> @hunter-xue which browser are you on? As you can see, I really cannot reproduce this
> 
>  Screen.Recording.2024-04-05.at.1.21.32.PM.mov

I guess we ran into a browser compatible issue, this working well in Safari & Firefox, but not work in Edge and Chrome. All browsers and MacOS are the latest version. 
![截屏2024-04-05 18 19 55](https://github.com/appsmithorg/appsmith/assets/4905312/1ebef921-b95d-45f1-a57a-e23b5c54ce0a)

**Comment by rahulbarwal** [comment] 2024-08-28 12:15
@hunter-xue I am getting the cursor in edge and chrome as well. 
Closing this issue, please re-open if you still face this issue.

**Closed by rahulbarwal** 2024-08-28 12:15 UTC
Labels: Bug, Table Widget, Widgets Product, Production, Community Reported, Needs Triaging, Medium, Ballpark: S, Widgets & Accelerators Pod

**Comment by eedwardsSGS** [comment] 2024-08-28 13:02
> @hunter-xue I am getting the cursor in edge and chrome as well. Closing this issue, please re-open if you still face this issue.

Fixed as of which version?  I'm on 1.36.1 and the bug is still there.

**Comment by rahulbarwal** [comment] 2024-08-28 13:21
@eedwardsSGS I tried on both edge and chrome, sharing a video. 

https://github.com/user-attachments/assets/f2a4a4be-ab47-4a29-ad53-bdf28feb5db6

If you still face this, please share the browser versions? Here are mine.
Edge: 128.0.2739.42 (Official build) (arm64) 
Chrome: 128.0.6613.85 (Official Build) (arm64)

**Comment by eedwardsSGS** [comment] 2024-08-28 13:29
@rahulbarwal
That is correct, I do get a cursor now when editing a row.

I still do not get a cursor when adding a new row.

**Comment by rahulbarwal** [comment] 2024-08-29 04:34
Thats a legit bug. Tracking it here: https://github.com/appsmithorg/appsmith/issues/35963

We will pick it up soon.
