### ISSUE TITLE
[Bug]: Unable to delete old datasource after updating dependent queries with a new datasource

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11690] opened 2022-03-07 13:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing datasource to a new datasource and then trying to delete the old datasouce fails to happen and instead displays an error stating there are dependent quries.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8b21104f62674fbeaf440a2c478b2746-00001.gif)](https://www.loom.com/share/8b21104f62674fbeaf440a2c478b2746)

### Steps To Reproduce

1. Use templates to create a new app
2. Create a new datasource that's the same type as your queries and update queries with this new datasource
3. After changing datasource for all dependent queries, try to delete the old datasource and observe the error as seen in the video

### Environment

Production

### Version

Cloud

**Comment by nidhi-nair** [comment] 2022-03-08 17:14
Quick check on this bug report, had the app been published after switching the queries' datasources? If the published version of apps are referring to datasources, they'd still prevent deletion.

**Comment by ramsaptami** [comment] 2022-03-09 06:34
This is on a new template so deploy has happened yet.. Only initial changes

**Comment by Nikhil-Nandagopal** [comment] 2022-04-04 06:14
Duplicate of #10358

**Closed by Nikhil-Nandagopal** 2022-04-04 06:14 UTC
Labels: Bug, Datasources, Actions Pod, Production, error, High impact, BE Coders Pod
