### ISSUE TITLE
[Bug]: Unable to reset password after recent update v1.8.5

### ISSUE THREAD

**Issue by wkethman** [appsmithorg/appsmith#17637] opened 2022-10-18 02:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After recent update to v1.8.5 I am unable to login under my default admin email address. When I request to reset the password it does not send the email to reset.

To test this functionality, I created a second user and was able to request and reset the password successfully so it is configured correctly. 

At the end of the day, this may not be a bug or perhaps the user account was corrupted but I have lost access to an Application that I would like to get back. Any suggestions?

I have attempted going back to 1.8.4 without success

### Steps To Reproduce

1. Go to: https://appsmith.kethman.dev/user/login
2. Attempt to login 
3. "It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below."
4. Attempt password reset does not send email 

### Version

Self-hosted, v1.8.4

**Comment by sharat87** [comment] 2022-10-19 13:59
Hey @wkethman, that is not a pleasant experience and this is not what we aspire to. Really sorry you have to deal with this.

To help investigate this, can you provide the following data please?

1. Is Appsmith v1.8.4 the first version you are running? Or did you arrive at this version after upgrading from a previous one?
1. Please attempt to login with that admin user, see it fail, then attempt the forgot-password flow, see that fail too. Then get the logs from the `stacks/logs/backend` folder and share them with us. Please feel free to email the logs to support@appsmith.com if you aren't comfortable sharing them publicly here.
2. Do you have disk backups of your server running Appsmith? If you use an external MongoDB, do you have backups of your data in there?
3. If you attempt to **sign up** with that old admin email, does it report an error saying that user already exists, or does it go through?

Sorry for the barrage of questions. This information will help me get a picture of what might be happening here and help you faster. Thanks!

**Comment by wkethman** [comment] 2022-10-19 23:55
@sharat87 thank you - we are using this for a hospital (clinical) based application and unfortunately I am concerned about the reliability of keeping the app online - thank you for helping

1. I was running 1.8.4 as the first version and had no issues - the docker container automatically updated to 1.8.5 and that is when I noticed the issue. I attempted to go back to 1.8.4 and it still occurred. I created a new user in v1.8.5 and it hasn't failed yet.
2. I was able to request Forgot password on Safari and it worked - then was able to go back to Chrome - I can't reproduce the issue now in v1.8.5
3. I have disk backups and was able to export the app as backup
4. It did report that the user existed

For now, I was able to recover the app and login but it doesn't give me a lot of faith in the app - do you know what might have caused this to happen?

**Comment by sharat87** [comment] 2022-10-20 14:52
Hey @wkethman, thanks for the responses. Can you also share the logs from the `stacks/logs/backend` folder as well please? Feel free to email them to support@appsmith.com, and refer this issue link in the email. I'll pick it up and investigate.

I'm really sorry for the experience you have here. We'll figure out what's going on here.

Thank you for your patience.

**Comment by sharat87** [comment] 2022-10-27 07:45
Hey @wkethman, just following up here. Can you share the logs from when you faced the error? Or if you can reproduce, logs from now please? This will help us investigate and get to the root cause. Thanks!

**Comment by Nikhil-Nandagopal** [comment] 2022-11-01 14:25
Closing this since we haven't gotten a response

**Closed by Nikhil-Nandagopal** 2022-11-01 14:25 UTC
Labels: Bug, High, DevOps Pod, Email Config
