### ISSUE TITLE
[Bug] onPageLoad not working for queries

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1848] opened 2020-11-23 07:45 UTC
## Description
After adding a query and binding it to a widget, the query is not run on page load

**Comment by hetunandu** [comment] 2020-11-23 07:46
Need a way to reproduce consistently to see if it is a server or a client issue

**Comment by Nikhil-Nandagopal** [comment] 2020-11-23 07:47
How did this not get caught in automation?

**Comment by hetunandu** [comment] 2020-11-23 08:12
Not happening all the time. I am yet to be able to reproduce this issue

**Comment by nidhi-nair** [comment] 2020-11-24 04:56
@hetunandu Have you been able to replicate this since then? We should downgrade this bug if not.

**Comment by hetunandu** [comment] 2020-11-24 06:43
Yes. Since this bug was seen before your changes were pushed to self hosted, we can wait a while till we see this again

**Comment by Nikhil-Nandagopal** [comment] 2020-11-24 09:08
Closing untill we're able to reproduce this

**Closed** 2020-11-24 09:07 UTC
Labels: Backend, Bug, Frontend, Needs More Info
