### ISSUE TITLE
[Bug]: Update thru file import for packages is throwing error 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31553] opened 2024-03-06 10:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Update thru file import for packages is throwing error 

### Steps To Reproduce

<img width="1434" alt="Screenshot 2024-03-06 at 3 25 59 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/ecc5e393-1c5f-4714-83b5-8e4386ed9588">
<img width="1434" alt="Screenshot 2024-03-06 at 3 25 59 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/162f2c2c-6623-44de-8fc5-f494320b318f">

### Environment

Release

### Severity

High (Blocker to building)

### Version

Cloud/Release

**Comment by nidhi-nair** [comment] 2024-03-12 03:00
Closing as duplicate of #31528

**Comment by nidhi-nair** [comment] 2024-03-12 04:13
Reopening to separate the client side issue from the core story.

**Closed** 2024-03-13 05:08 UTC
Labels: Bug, High, Release, Needs Triaging, Modules pod, Module creator
