### ISSUE TITLE
[Bug]Safari - The screen gets Blue highlighted by dragging and dropping most of the widgets

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3965] opened 2021-04-12 07:58 UTC
## Description
It is observed that by dragging and dropping most of the widgets the screen is highlighted in blue. Blue highlight is not occurring by dragging and dropping the following widgets (DatePicker, FilePicker, RichTextEditor and Video)

**Expected Result:**
Blue Highlight should not occur by dragging and dropping widgets

**Actual Results:**
Blue Highlight occurs by dragging and dropping most of the widgets

### Steps to reproduce the behaviour:
1. Launch Appsmith in Release Environment
2. Drag and Drop table widget and observe

**Note:**
Blue highlight doesn't occur by dragging and dropping Datepicker, Filepciker, RichTextEditor and Video widgets

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c831139abebd460e8126dce83cb2dc76-00001.gif)](https://www.loom.com/share/c831139abebd460e8126dce83cb2dc76)

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [e.g.MacOS Big Sur 11.2.X]
 - Browser [safari]

**Comment by somangshu** [comment] 2021-04-12 08:36
I can drag and drop all widgets normally on the safari browser. Not able to reproduce!

**Comment by riodeuno** [comment] 2021-09-09 11:07
@YogeshJayaseelan Please close this issue if this is verified to be a non-issue.

**Comment by Rishabh-Rathod** [comment] 2021-10-03 09:28
Unable to reproduce this issue in safari @YogeshJayaseelan, can you check again was it for a special case ?

https://user-images.githubusercontent.com/23132741/135747820-6520b6a2-0255-4a9c-ae64-a92855485ef7.mov

**Closed** 2022-01-25 15:30 UTC
Labels: Bug, Low, Release, regression
