### ISSUE TITLE
[Bug]-[86]:The disconnect from git-flow is broken in the release

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12094] opened 2022-03-22 08:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The disconnect from git-flow is broken in the release
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/159444072-1561255f-7739-450b-afce-1ccc3b1ee341.png">

### Steps To Reproduce

1. connect the application to git 
2.Now click on setting icon on the bottom bar 
3. click on the delete icon
4. the disconnect modal is changed and when the user try to revoke the access the access is not revoked

### Version

release

**Comment by IAmAnubhavSaini** [comment] 2022-03-23 03:15
I am not able to reproduce the issue.

https://user-images.githubusercontent.com/1573771/159616709-c5f9a82f-a39e-440e-87d8-05121acd6f16.mov

**Comment by IAmAnubhavSaini** [comment] 2022-03-23 04:46
@RakshaKShetty Design is new. @Debsourabh has provided newer designs for Revoke and RepoLimitReached.

Checkout this task: https://github.com/appsmithorg/appsmith/issues/11750

Here are images of new design:

![](https://user-images.githubusercontent.com/1573771/157738662-a624fd91-eed3-4d6f-bf76-6b95c99bfa83.png)

![](https://user-images.githubusercontent.com/1573771/157738668-6ed67369-2343-450c-b5ac-fe02d936f052.png)

**Comment by IAmAnubhavSaini** [comment] 2022-03-23 05:19
Reopening because old apps cannot revoke.

**Comment by abhvsn** [comment] 2022-03-23 09:14
Able to replicate this issue with the following steps on release but not on my local:

1. Create an empty app
2. Connect app to empty repo
3. Revoke access
4. Delete all the files on remote except for the .md or only keep the supported files like LICENSE, yml etc
5. Connect the app again to the same repo
6. Try to revoke the access now, this fails with 504 Gateway Timeout

I think steps 4 and 5 are very unlikely can we please make this critical and remove the `Release Blocker` for now?
@hiteshjoshi

**Comment by abhvsn** [comment] 2022-03-23 11:50
Errors which we are seeing on logDNA:

> Mar 22 16:10:52 55c6f85cbc96 appsmith-internal-server Caused by: java.io.IOException: Creating directory /data/git-storage/62388603c76e7b651d6bc835/6239966ba1037840b6dc1628/fluffy-eureka/.git/refs failed
> 
> Mar 23 11:13:07 55c6f85cbc96 appsmith-internal-server org.eclipse.jgit.api.errors.JGitInternalException: Creating directory /data/git-storage/62395480c76e7b651d6bcbf7/6239572bc76e7b651d6bcc7b/api_import/.git/refs failed

**Comment by abhvsn** [comment] 2022-03-23 12:33
Next set of actions to be performed on an immediate basis:

- [ ] Disable all the git related APIs till the list branches return the valid response @IAmAnubhavSaini 
- [ ] Don't throw an exception if the local repo and DB are not in sync, currently if the repo has the local branch and the same is not available in DB this throws the `Resource Not Found` exception @abhvsn 
- [ ] Triage the issue related to directory creation is throwing the exception @abhvsn 
- [ ] Check the possibility within the codebase for local repo getting deleted @abhvsn 
- [ ] Implement the file locks so as to avoid multiple clones in the same directory location if multiple folks try from separate browsers @AnaghHegde

**Comment by IAmAnubhavSaini** [comment] 2022-03-24 06:07
> Disable all the git related APIs till the list branches return the valid response

Please return proper response to a request, if service is not expecting other, certain service requests. Introducing an artificial blocking of other service calls will make code brittle and prone to errors. Also, I don't understand the `till the list branches return the valid response`, do you mean that frontend should keep retrying until it gets proper response from backend? Retries should happen in backend, without FE firing multiple requests.

In case you still think FE should not fire other requests, could you please provide reasoning behind that? Please explain what is the problem with the current implementation and how suggested solution will resolve it.

---

The problem that we were facing was related to server not returning proper response and throwing `504 gateway timeout`. The suggested solution will not take care of this problem, as there would be no way to know if list branches service call finished properly or not; as you can notice from the image that server response is in html instead of in json.

<img width="993" alt="Screenshot 2022-03-24 at 11 27 14 AM" src="https://user-images.githubusercontent.com/1573771/159852082-74c15d9a-5a0b-46b0-a43f-ed4dc7af4701.png">

**Comment by abhvsn** [comment] 2022-03-24 08:13
`In case you still think FE should not fire other requests, could you please provide reasoning behind that? Please explain what is the problem with the current implementation and how suggested solution will resolve it.`

For on page load we are doing couple of requests which is trying to utilise the same file path:
1. List branch
2. Get status

In case if the local repo is not present we will clone the repo from remote which takes somewhere between 5-15 sec depending upon the files etc. Also for the status API we are dehydrating the DB and saving the resources in the file system, this creates the file conflicts as we are trying to copy the same files in the same directory (through status API) where cloning is in process(list branch API). We have placed the cloning only for the list branch API as only this is supposed to run for page load and not the other git APIs. Also without the local repo all the git APIs will result in exception. Once we have the locks we will have a better control over the files but until then we will have to be dependent on the native git locks.  

When I said `till the list branches return the valid response`, I was not referring to any retry etc. but just wait till list branch is successful before making any git call like `get status`. Also if the get status fails other git APIs are going to fail. Having said this we will improve the error messages in the backend but I still feel that as we are already aware of the errors in the client side can't we put a check here as well?

I will be resolving the issue for server not returning the proper response as well. This should be json as you suggested and I need to triage this why nginx returning this error and not the server.

**Comment by IAmAnubhavSaini** [comment] 2022-03-31 04:28
>  if the get status fails other git APIs are going to fail.

Why is this? If the params to a service call are correct, there should be no reason for another API to fail.

---

The reason for not removing git status call on load.

As soon as the application loads, user can still click `+` commit button, and fire git status call. If it is going to fail on load, it will fail in this scenario too. My reluctance stems from this being a patchwork.

There is another possibility, same app being open in two places at the same time. Maybe two users are working on it, maybe only one.

There is yet another possibility, a malicious user firing all the requests at once. 

Thus I am pushing for robust service that can handle requests and return appropriate response.

---

Let's have a call on this after the standup.

**Comment by Nikhil-Nandagopal** [comment] 2022-04-04 06:54
Not critical since it does not break a user's app

**Comment by vuiets** [comment] 2022-04-26 08:00
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 43 |
| Effort (months)  | 0.25 |

Dropping a rough estimate for effort for this. Feel free to change it here.

**Comment by abhvsn** [comment] 2022-05-16 12:39
@RakshaKShetty is this still reproduceable?

**Comment by IAmAnubhavSaini** [comment] 2022-05-18 00:56
@RakshaKShetty Please test against an old application and let us know if this bug still persists.

**Comment by RakshaKShetty** [comment] 2022-05-20 05:26
Still able to repro this issue i am facing 504 gateway error
![image](https://user-images.githubusercontent.com/45958978/169456076-c2edf642-42de-457f-9067-ab6c1cc2cab1.png)
App Link https://release.app.appsmith.com/applications/625685fce4f28636dd152d08/pages/62568603e4f28636dd152d17?branch=master
Github link: https://github.com/RakshaKShetty/datasource_import

**Comment by IAmAnubhavSaini** [comment] 2022-05-20 06:47
I have been able to reproduce this issue with Revoke API as @abhvsn has mentioned above. This looks like a backend cleanup issue. I am getting 500 and 504 errors. Lets have a call on backend implementation. From FE we are sending proper data in request, but not getting proper response. The responses I am getting are 500 or 504.

**Comment by IAmAnubhavSaini** [comment] 2022-05-20 08:05
After app gets into a weird state when revoke is failing:

# revoke response

```json
{
    "responseMeta": {
        "status": 500,
        "success": false,
        "error": {
            "code": 5000,
            "message": "Internal server error while processing request"
        }
    }
}
```

And subsequent commit response:

```json
{
    "responseMeta": {
        "status": 404,
        "success": false,
        "error": {
            "code": 4051,
            "message": "Unable to find the repository for application 62872d61db0f9c6e620d564c, please refresh the page to auto-sync with the remote. This might take couple of minutes",
            "errorType": "REPOSITORY_NOT_FOUND"
        }
    }
}
```

**Comment by IAmAnubhavSaini** [comment] 2022-05-20 08:41
@abhvsn It looks like revoke API is not returning proper response, but commit one does. This happens after steps mentioned in https://github.com/appsmithorg/appsmith/issues/12094#issuecomment-1076129711 

Revoke succeeds but leaves the application in weird state. Here, git-status API returns a proper response, and as if the git is connected properly. But, only commit command shows that it is not connected. 

(speculation:) On revoke, we somehow keep local repo, but disconnect from remote, and when commit-push happens, we get to know that the connection doesn't exist.

Could you please take a look at it and see if this is the case?

**Closed** 2022-06-15 09:37 UTC
Labels: Bug, Low, Cannot Reproduce Issue, Needs Triaging, Git Version Control, Team Managers Pod, Platform Pod
