### ISSUE TITLE
[Bug]: Tab widget CTA on entity explorer does not switch to specific tab or load property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9442] opened 2021-11-29 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on tab widget on entity explorer does not open up it's property pane. Also clicking on a specific tab from the entity explorer does not navigate to the chosen tab.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/280c66926c3c41f6b9536a5eaadb0a22-00001.gif)](https://www.loom.com/share/280c66926c3c41f6b9536a5eaadb0a22)

### Steps To Reproduce

1. Add a tab widget to the canvas with multiple tabs
2. Navigate away from the canvas
3. Select `tab2` from entity explorer and observe that user is navigated to canvas but property pane of this widget does not load and does not navigate to the specific tab that was selected from entity explorer.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-01-12 13:20
Duplicate of #4748

**Closed by dilippitchika** 2022-01-12 13:20 UTC
Labels: Bug, UX Improvement, Tab Widget, App Viewers Pod, Low, Production, UI Building Pod
