### ISSUE TITLE
[Bug]: JS object name is displayed as a lint error on binding when app/page is cloned

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11645] opened 2022-03-04 15:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS object name is displayed as a lint error when app/page is cloned

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/33bcd074854d4e40801427dfad1e443f-00001.gif)](https://www.loom.com/share/33bcd074854d4e40801427dfad1e443f)

### Steps To Reproduce

1. Create a JS object and bind it to a widget
2. Clone the page or app (fork, duplicate, or fork) and observe this object name displayed as a lint error

### Environment

Production

### Version

Cloud

**Comment by eco-monk** [comment] 2022-03-21 07:05
Duplicate of #11943.

**Closed by eco-monk** 2022-03-21 07:05 UTC
Labels: Bug, UX Improvement, Actions Pod, Production, Needs Triaging, High impact, JS Linting & Errors, FE Coders Pod
