### ISSUE TITLE
[Enhancement] UX:  As we populate API and header the api_key must also be populated dynamically

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5472] opened 2021-06-29 11:06 UTC
Steps to reproduce
1) Add an API with api_key
2) Now click on save as datsource 
and observe

Observation:
it is observed that the Auth does not get populated however, the API data gets populated

Expectation:
Since the API data contains the Auth Type and considered key we can populate the data like we populate the API and the header

**Comment by Nikhil-Nandagopal** [comment] 2021-08-23 09:34
@prapullac can you add more details. Not able to understand this exactly

**Comment by prapullac** [comment] 2021-08-23 13:16
@Nikhil-Nandagopal 
Please find the video :
https://www.loom.com/share/07fd248ac134476a985e20eedf3c2722

The API_Key is attached inside the cURL / API yet we ask the user to add it explicitly when it is converted to API data source

**Comment by Nikhil-Nandagopal** [comment] 2021-08-23 13:21
Got it. This is actually a duplicate of #4568
It doesn't show because we don't have a query params section.
We also can't detect the apikey because it can be added as any field

**Closed by Nikhil-Nandagopal** 2021-08-23 13:21 UTC
Labels: Enhancement, API pane, Actions Pod, Low, Release, Needs Triaging
