### ISSUE TITLE
[Bug] onSubmit gets triggered before evaluation

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#7507] opened 2021-09-16 07:50 UTC
## Description

A user reported that hitting enter in an input widget was submitting only part of the input

### Steps to reproduce the behavior:

1. Drag an input widget
2. configure onSubmit as
`{{navigateTo('Page 1',{name: Input1.text})}}`
3. Type text quickly and hit enter
4. only part of the text is present in the query param

**Comment by Nikhil-Nandagopal** [comment] 2021-10-11 09:20
@AsianCat54x this is not a good first issue. Please have a look at our good first issue label

**Comment by Nikhil-Nandagopal** [comment] 2021-11-10 13:17
@somangshu The onSubmit is being triggered before the meta is updated and thus the navigate Eval is getting the older value

**Comment by somangshu** [comment] 2022-01-20 09:27
@sbalaji1192 can you check this once?

**Comment by sbalaji1192** [comment] 2022-01-20 10:24
@somangshu We have a 200 ms debounce when updating the widget's meta property since we don't wanna choke the worker thread as the user types in an input widget. In the scenario mentioned in the description, the onSubmit action gets triggered before the debounce expires.

**Comment by wjurij** [comment] 2022-01-20 10:34
In the application I am developing it is quite an important issue. We're using a barcode scanner, which inserts a newline character after the code. The accepted input contains only the first character of the code. Due to this issue, we had to disable the endline character postfix on barcode scanner and so users accept every single code by pressing enter on keyboard. 

The problem is also sometimes triggered on manual input, when users type and accept the input very quickly.

**Comment by sbalaji1192** [comment] 2022-01-20 10:48
@wjurij Agreed, this is an important issue. we will provide a fix for this.

**Comment by sbalaji1192** [comment] 2022-01-20 12:35
@SatishGandham @riodeuno Any ideas on how we can solve this? (please refer to this comment - https://github.com/appsmithorg/appsmith/issues/7507#issuecomment-1017326748)

**Comment by DeanMann** [comment] 2022-02-20 09:32
> In the application I am developing it is quite an important issue. We're using a barcode scanner, which inserts a newline character after the code. The accepted input contains only the first character of the code. Due to this issue, we had to disable the endline character postfix on barcode scanner and so users accept every single code by pressing enter on keyboard.
> 
> The problem is also sometimes triggered on manual input, when users type and accept the input very quickly.

I am also using a barcode scanner in the same way and experiencing the same problem. I can confirm that rapid typing using a manual keyboard input can reproduce this issue

**Comment by sbalaji1192** [comment] 2022-02-23 08:06
We have arrived at a two-step solution: 
1. Fix the current issue by changing how we're triggering the submit action from the input widget, By using `updateWidgetMetaProperty` instead of `executeAction`.
2. Make platform-level changes to flush out the current metaHOC state before triggering an action.

cc: @riodeuno @Rishabh-Rathod @hetunandu

**Closed** 2022-03-16 14:45 UTC
Labels: Bug, Input Widget, App Viewers Pod, High, UI Building Pod
