### ISSUE TITLE
[Docs]: Add docs for validation support within inline editing 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16776] opened 2022-09-15 05:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Within tables, we now support validations in edited columns, so devs can define rules which users adhere to.

### Describe the improvement

https://www.notion.so/appsmith/Table-inline-editing-validations-447aa9d882ee4d1dba7bdbcb2214fbd7

Here's the doc.

**Comment by dilippitchika** [comment] 2022-09-15 05:17
POC @sbalaji1192

**Comment by dilippitchika** [comment] 2022-09-15 05:18
Expected release version - 1.8.2

**Comment by Pranay105** [comment] 2022-09-21 09:56
@dilippitchika is this a duplicate of #15955

**Comment by dilippitchika** [comment] 2022-09-21 11:47
Yes, closing the other one

**Closed** 2022-10-07 08:19 UTC
Labels: Documentation, User Education Pod, Ready for Doc Team
