### ISSUE TITLE
[Feature] Move widgets on the canvas with the help of arrow keys

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4076] opened 2021-04-20 15:07 UTC
## Summary

As a user, I want to be able to move the widgets in all directions on the canvas with the help of arrow keys.

## Motivation

This is a good UX that can help users to make the minor movement of widgets to get the overall look and feel of the final app.

## Additional Context

The behavior exists on draw.io

**Comment by Nikhil-Nandagopal** [comment] 2021-08-19 06:56
Duplicate of #3264

**Closed by Nikhil-Nandagopal** 2021-08-19 06:56 UTC
Labels: Enhancement, Widgets, UI Building Pod, UI Building

**Comment by szalapski** [comment] 2025-06-04 15:27
I'm guessing https://github.com/appsmithorg/appsmith/issues/3264 was mistakenly thought unnecessary in light of auto-layout, but auto-layout is now dead, so I have created a new one, https://github.com/appsmithorg/appsmith/issues/40863.
