### ISSUE TITLE
[Bug]-[2120.8]:Connect PostGreSql query to a Select widget -> Default Value field is populated incorrectly

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16931] opened 2022-09-21 06:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I connect a PostGreSql query to a Select widget (choosing from the Add New Widget section), the Default Value field is populated incorrectly. 

### Steps To Reproduce

1. Create a connection to PostGreSql Datasource (details [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e)) 
2. Create a query on this data source. (Say - SELECT DISTINCT name FROM users;)
3. From the Add New Widget section, connect the query to a select widget
4. On the Page, check the Default Value section .. The binding appearing here is incorrect but there is no error seen. 

<img width="666" alt="Connect_Binding_DefaultValue" src="https://user-images.githubusercontent.com/101863839/191428668-20874f1d-0f25-48c6-8114-0149fa36425b.png">

Expected binding is - 
{{Select1.options[0].label}}

### Version

Production

**Comment by Nikhil-Nandagopal** [comment] 2022-09-26 09:32
@kocharrahul7 it seems the suggested widgets logic has broken

**Comment by Tooluloope** [comment] 2023-03-31 12:20
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 530.2 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment] 2023-04-07 10:32
@sribalajig I dont see how this is related to the select widget, Can you shed some light on why is this assigned the `select widget` label?

**Comment by sneha122** [comment] 2024-05-01 09:42
@rohan-arthur I am not able to reproduce this issue anymore on production, hence closing this issue, please feel free to reopen it if reproduced again.

**Closed by sneha122** 2024-05-01 09:42 UTC
Labels: Bug, High, Production, Needs Triaging, Low effort, BE Coders Pod, Integrations Pod, Suggested Widgets
