### ISSUE TITLE
[Bug]: Switching branch fails with error : Remote does not have refs/heads/<branchName> available for fetch

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24666] opened 2023-06-20 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/80334441/b50c1a5f-1073-4fc4-82b1-ea2d3787b45d

### Steps To Reproduce

1. Go to this [app](https://release.app.appsmith.com/app/test-dp/page1-6491742543745f7d202d4c71/edit?branch=test%252Fbranch01)
2. Create new branch or switch to test/branch01
3. Observe following error is thrown `git status failed. Details: Remote does not have refs/heads/test/branch01 available for fetch.`
Note: This is not reproducible always

### Public Sample App

https://release.app.appsmith.com/app/test-dp/page1-6491742543745f7d202d4c71/edit?branch=test%252Fbranch01

### Environment

Release

### Version

Release

**Comment by infinitetrooper** [comment] 2023-07-03 05:57
From this [conversation](https://theappsmith.slack.com/archives/C04HERDNZPA/p1688363149223559), this [sentry issue](https://appsmith.sentry.io/issues/4080486708/?query=is:unresolved+git&statsPeriod=14d&stream_index=1) looks to be linked. Please triage this and fix it while closing this issue.

**Comment by nayan-rafiq** [comment] 2023-07-27 07:40
Closing this as we were not able to reproduce this. Will open again if there is any occurrence in future.

**Closed by nayan-rafiq** 2023-07-27 07:40 UTC
Labels: Bug, High, Production, Needs Triaging, Git Version Control, Git Pod
