### ISSUE TITLE
[Bug]: Query entered in a GSheet field is retained for a new query in the same/new page

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#21396] opened 2023-03-14 10:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we enter a query/value in a field e.g. `Pagination Offset` of a GSheet query in one page, the query/value gets retained for a new query in the same page or a new query in a new page.

### Steps To Reproduce

1. Add a GSheet query.
2. Select the desired `Spreadsheet` & `Sheet Name`.
3. Scroll down & enter a value/query in the `Pagination Offset` field & click on `Run`.
4. Now create a new query for the same datasource & repeat step 2.
5. Scroll down to the `Pagination Offset` field.

**Expected:** The `Pagination Offset` field for the new query should be blank.
**Actual:** Value/Query of the 1st GSheet query is retained.

### Environment

Production

### Issue video log

https://www.loom.com/share/8547e5630c9f45d2b4b1e0fd6314f470

### Version

Cloud

**Comment by sumitsum** [comment] 2023-05-05 09:03
Marking the issue as `High` priority because it may indicate a larger problem with the query config flow ie. the same problem occurring across all integration query forms.

**Comment by sneha122** [comment] 2024-04-02 07:55
Closing this issue @shadabbuchh please reopen it in case you are able to reproduce it

**Closed by sneha122** 2024-04-02 07:55 UTC
Labels: Bug, Frontend, UX Improvement, High, Production, Low effort, Google Sheets, BE Coders Pod, Integrations Pod
