### ISSUE TITLE
[Enhancement]: Don't create the modal when it is not shown thus avoiding errors it may have on page load

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#10341] opened 2022-01-12 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Edit mode: the modal throws error on page load. Even though it's closed.

Conditions:
1. When the modal has certain fields that are bound to a widget on page.
2. And when the widget depends on some dynamic data (that gets populated on certain action, which is not performed yet).

### Steps To Reproduce

[App export](https://drive.google.com/file/d/1EUp-RhaH96kPfTbvxDOZRzPx_EVBG986/view?usp=sharing) for reference.

1. Create an `API` that returns an array of objects.
2. Create a button that triggers the `API` -> `onClick`. 
3. Bind `API.data` to a `table`.
4. Create a `modal` and inside that, create an `input field` that binds `defaultText` to `Table.selectedRow.columnName`.
5. Make sure `Run API on Page load` is disabled.
6. Refresh the page and notice an error in appsmith console from modal.
![image](https://user-images.githubusercontent.com/66776129/149099106-6e17535b-1874-4313-a110-4710edfb916d.png)

Yes, we could add a null check to solve this. 
But, a question arises. Should modal contents be evaluated even when it's not open?

Notice the error gets resolved, the moment we click on the button.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-01-13 06:34
@eco-monk I think this is more an enhancement than a bug. The widgets are always created and only hidden / shown since they are part of the DSL. This can be an optimization

**Comment by dilippitchika** [comment] 2022-01-13 12:29
@somangshu can you check if this is technically feasible?

**Comment by somangshu** [comment] 2022-01-13 12:42
Will need to traige this. Not sure what is causing this. As pointed out maybe the evaluation must not happen when the widget is not ready. 

@hetunandu @SatishGandham can you guys help understand what the best aplroch here

**Comment by dilippitchika** [comment] 2022-01-13 13:10
Parking this for now

**Comment by areyabhishek** [comment] 2022-01-21 19:49
We got a Discord message where a user is quite annoyed and says that the error messages thrown by the modal is causing problems. I've pinged to find out more, but here's his current message.

<img width="675" alt="Screen Shot 2022-01-22 at 1 16 31 AM" src="https://user-images.githubusercontent.com/30255708/150590832-8fd2bb1b-4fe8-47f8-98a1-169bda222b50.png">

**Comment by billyrudi** [comment] 2022-01-21 20:08
Consider to have an the modal also list view or date picker. The errors are many.. And if you have two or three modal forms than the page spent also 10 15 seconds to load or refresh.

**Comment by ohansFavour** [comment] 2022-01-22 06:43
My thoughts

1.  We have introduced the concept of a `logBlacklist` (https://github.com/appsmithorg/appsmith/pull/4854). So we can conditionally populate the `logBlacklist` field with all the children of the modal. `The caveat here is that evaluations actually happen but errors don't get logged`.

2. We can also have an evaluationBlacklist. The problem however is that if the children of the modal are to be considered public, in the sense that all other entities can refer to them (bind to them), those entities will always have the unevaluated value till the Modal is open.

**Comment by billyrudi** [comment] 2022-01-25 21:45
Hi, some news?

**Comment by dilippitchika** [comment] 2022-01-26 10:34
Hi @billyrudi the end user cannot see the errors right? Can you please confirm?

Plus, the load time which you are referring to is it the page load or the load time for a specific widget like a table widget?

**Comment by billyrudi** [comment] 2022-01-26 11:30
no, the end yeser does not see errors.
the load time is for the entire page.

**Comment by dilippitchika** [comment] 2022-01-27 05:43
Thanks for the confirmation @billyrudi. 

I second what @ohansFavour has suggested by introducing an evaluation blacklist. 

@somangshu not sure if this will also have some changes on our end, can you help me out? Also not sure if having the eval blacklist will improve performance.

**Comment by somangshu** [comment] 2022-01-27 06:09
@dilippitchika @ohansFavour With `evaluationBlacklist` an issue from before might resurface, that is in the editor mode the dev is binding the value between the modal child widget and api pane, while navigating between them they will not see the updates happen, which is a very poor experience. 

I am not sure of the implication of the 1. point

@SatishGandham @rahulramesha need your feedback on this

**Comment by Nikhil-Nandagopal** [comment] 2022-01-28 09:39
@billyrudi the modal should not affect the load time for the entire page unless those queries are being run on page load. Can you try marking run on page to false and triggering them only when the modal is opened?

**Comment by billyrudi** [comment] 2022-01-28 10:18
no, it is not so: the problem is indipendent of API. I load only the ones need to populate the main page.
I have give you all server username and password to see yourself the BIG time that mainpage spent to load itself. I cannot know where is the problem but there is another iussue that can be correlated with this: https://discord.com/channels/@me/935028682848874537/935054553248858112
maybe searching in both directions can help you to find the problem.  

Satish Gandham — 25/01/2022 wrote to me:
It seems to be happening on some systems, we were able to reproduce it yesterday. Looking into it.

**Comment by billyrudi** [comment] 2022-01-28 11:05
I have deleted all modal forms in a test enviroment and loading is better....

**Comment by billyrudi** [comment] 2022-02-01 06:17
Hi, news on this? Ifyou dont resolve this problem i must leave appsmith ide to use other solutions

**Comment by ApekshaBhosale** [comment] 2022-02-02 10:32
Hello @billyrudi, I am so sorry this is happening with your app. We are actively working on it and found a few improvements to be done. 
One of the libraries used in our code was taking most of the time but we have found an alternative that improves performance by 40%. 
As you said deleting modal forms improved because it automatically reduces widget numbers hence the evaluation and loading time improved. Building on the last point, will you be able to split the app into multiple pages? This gives lesser data to work with on the page load and boosts performance.
Meanwhile, we are looking into improving performance with at most priority.

**Comment by billyrudi** [comment] 2022-02-02 11:52
hi, i can try but it is not so simple. modal forms loads data from tables. how i can do it with separete forms?

**Comment by dilippitchika** [comment] 2022-02-02 12:22
Hey you can share data across pages using the parameters in the navigateTo(). Ideally the table's selectedRow on Click opens a new page with the selectedRow's properties passed as parameters.

More info here - https://docs.appsmith.com/framework-reference/navigateto

**Comment by Nikhil-Nandagopal** [comment] 2022-03-09 17:28
@billyrudi the performance fixes for this have been shipped. Is your application working fine now?
I'm closing this issue. Do let us know if you're still having trouble with it

**Closed by Nikhil-Nandagopal** 2022-03-09 17:28 UTC
Labels: Enhancement, Actions Pod, Modal Widget, App Viewers Pod, Low, UI Building Pod, community, FE Coders Pod
