### ISSUE TITLE
[Bug]: Text overlaps in property fields for some of the widgets 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10165] opened 2022-01-05 07:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the text overlaps in the property field outline for some of the widget 

<img width="1680" alt="Screenshot 2022-01-05 at 12 29 39 PM" src="https://user-images.githubusercontent.com/35128442/148175302-4ecd4315-9c88-4450-8a64-2c726f6de791.png">

<img width="301" alt="Screenshot 2022-01-05 at 10 51 01 AM" src="https://user-images.githubusercontent.com/35128442/148175436-4899ce90-896a-4bbf-aa3a-27b1f33382fe.png">

**Widgets :**

Input Widget - Regex field and Tool tip field 
Select Widget - Options field (When options are removed)
MultiSelect Widget - Options field (When options are removed)

### Steps To Reproduce

1.Launch appmsith app in release environment 
2.Drag and drop input widget 
3.Open property pane and check regex and tool tip field 
4.drag and drop Select widget - Remove options value and observe text overlap
5.drag and drop MultiSelect Widget - Remove options value and observe text overlap

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2024-04-30 09:44
Duplicate of #8973

**Closed by Nikhil-Nandagopal** 2024-04-30 09:44 UTC
Labels: Bug, Property Pane, Low, Production, Needs Triaging, UI Builders Pod
