### ISSUE TITLE
[Bug]: SSL protocol error using caddy

### ISSUE THREAD

**Issue by accesstechnology-mike** [appsmithorg/appsmith#19958] opened 2023-01-20 18:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

reference: #13783

using https://github.com/lucaslorentz/caddy-docker-proxy

appsmith can't start using SSL with caddy

_using http://app.domain.co.uk:8443 it runs fine, so the installation is ok_ 

### Steps To Reproduce

docker-compose.yml:

```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8043:80"
      - "44343:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      caddy: app.domain.co.uk
      caddy.reverse_proxy: "{{upstreams 8043}}"
    networks:
      - caddy
    
  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
    depends_on:
      - appsmith
    environment:
     - WATCHTOWER_LIFECYCLE_HOOKS=true

networks:
  caddy:
    external: true
```

### Version

self-hosted latest

**Comment by accesstechnology-mike** [comment] 2023-01-20 19:00
Is there an environment value to prevent appsmith generating it's own SSL cert?

**Comment by sharat87** [comment] 2023-01-24 01:16
Hey, thank you for reaching out.

> Is there an environment value to prevent appsmith generating it's own SSL cert?
If you have the `APPSMITH_CUSTOM_DOMAIN` env variable set, please remove it, or comment it out. This will disable the automatic provisioning of SSL certificate.

If that doesn't resolve the problem, can you share how you are running Caddy as well please? I don't see it in the `docker-compose.yml`, and I'm not sure I understand the whole setup.

Thanks.

**Comment by sharat87** [comment] 2023-01-31 02:55
Hey, thanks for confirming. But since Appsmith is accessible if accessed directly on the exposed port (8443/8043), I suspect Caddy's `reverse_proxy` configuration might be the problem.

I just noticed that I don't have a detail on what's the problem you are seeing. Can you elaborate please? You confirm that Appsmith works on http://app.domain.co.uk:8443/, but what do you see when you open <https://app.domain.co.uk>? Is there a gateway error? Does it load Appsmith with error page? Note that Caddy usually won't show error details in the browser, so in that case, please try `curl -v https://app.domain.co.uk` and share the output as well. Thanks!

That said, having worked with Caddy in the past, but not with `caddy-docker-proxy`, I _think_ you should use `upstreams 80` instead of `upstreams 8043` in the value for `reverse_proxy`. Can you try this once please?

**Comment by sharat87** [comment] 2023-03-22 01:57
I'm guessing the above suggestions helped to resolve this. So closing. Please reopen if the issue is still there after the above suggestions. Thanks.

**Closed by sharat87** 2023-03-22 01:57 UTC
Labels: Bug, Needs More Info, Needs Triaging, Docker, DevOps Pod
