### ISSUE TITLE
[Bug] Ctrl + C / Command + C does not work on data source ip whitelist

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2246] opened 2020-12-17 07:37 UTC
## Description

Tried copying ip to whitelist, ended up triggering widget copy.

PS: copy pasting works within inputs.

### Steps to reproduce the behaviour:

The gif is at 0.5x speed for some reason, sorry.
![Copy triggers wigdet](https://user-images.githubusercontent.com/292174/102457356-a3929080-4068-11eb-9b64-e042404bd354.gif)

**Comment by rishabhsaxena** [comment] 2020-12-17 07:58
I think we should have the hotkeys mounted at the widgets page to fix this instead of the editor root

**Comment by Nikhil-Nandagopal** [comment] 2020-12-17 08:47
@ofpiyush this is a duplicate of #1937 
Ctrl+c doesn't work pretty much anywhere in the app. Closing this in favor of the older issue

**Closed by Nikhil-Nandagopal** 2020-12-17 08:47 UTC
Labels: Bug, Frontend, Low
