### ISSUE TITLE
[Enhancement]: Keyboard shortcut for entity explorer to be supported

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9411] opened 2021-11-26 17:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Entity explorer should support renaming via keyboard shortcut

### Why should this be worked on?

Provides easy navigation and supports existing behavior user may expect out of habit.

**Comment by Nikhil-Nandagopal** [comment] 2022-04-25 09:46
Duplicate of #11134

**Closed by Nikhil-Nandagopal** 2022-04-25 09:46 UTC
Labels: Enhancement, Entity Explorer, Platform Pod, keyboard shortcut, New Developers Pod
