### ISSUE TITLE
Groups/Roles should be shown alphabetically in their respective pages, this order should be followed while assigning to users also.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18818] opened 2022-12-09 07:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recently added groups/roles should be shown at the top in Groups/Roles page for easy access.

### Steps To Reproduce

1. Login as super admin
2. Create new Role/Group.
3. Come back to listing page and observe the newly added Role/Group is added at the end.

### Version

http://65.0.99.89/

**Comment by trishaanand** [comment] 2023-02-03 07:22
Duplicate of https://github.com/appsmithorg/appsmith/issues/20242

**Closed by trishaanand** 2023-02-03 07:22 UTC
Labels: Enhancement, Low, Team Managers Pod, RBAC
