### ISSUE TITLE
[Bug] Error on table : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this"

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6760] opened 2021-08-20 08:38 UTC
` Error: {  "widgetType" : "TABLE_WIDGET",  "bindingPath" : "primaryColumns.Sr_No..computedValue",  "message" : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.",  "widgetName" : "Table7",  "widgetId" : "v78pamwmft",  "pageId" : "610cdc95f00abe4fc53d8bef",  "layoutId" : "610cdc95f00abe4fc53d8bee",  "dynamicBinding" : null}`

<img width="1904" alt="Screenshot 2021-08-20 at 12 58 13 PM" src="https://user-images.githubusercontent.com/83569920/130196689-750af303-ee9f-4e20-93e6-ec6a9eb3896f.png">

Observation: Data is not showing on table sr_no column.
### Important Details

- Version: Cloud 
- OS: MacOSX
- Environment production

**Comment by somangshu** [comment] 2021-08-20 08:51
@vivekverma2312 please add steps to reproduce

**Comment by aswathkk** [comment] 2021-11-29 10:59
I also faced a similar issue today. Steps to reproduce:
1. Add a table widget
2. Convert one column type to "Icon Button"
3. Enable JS editable on Button Variant and type `{{"PRIMARY"}}`
4. Disable JS editable and see the console for the error

This doesn't have to be Button Variant. For other properties also the same thing happens.

**Comment by jsartisan** [comment] 2022-06-07 12:45
@sbalaji1192 I was able to reproduce this for the table widget.

Here are the steps to reproduce this on new apps:

1. Drop table widget
2. Drop any other widget. Let's say we drop the button widget.
3. Rename button widget to `action` ( action is a column name in the default table widget )
4. Now rename the same button widget to something else. Notice the binding path error.

For the time being, I have asked the user not to name any widget the same as primary columns.

**Comment by pratikbgit** [comment] 2022-06-07 12:50
Above bug open since 2021 and after that many person had put comment on it but still that issue is not resolved🥲 😭

Can you please make resolve it in priority.

**Comment by sbalaji1192** [comment] 2022-06-08 05:31
@jsartisan The Table widget does not actually cause this issue. When changing a widget name, we make `/layouts/refactor`. The said URL throws the above issue.
@somangshu Whom should I tag to take a look at this from BE side.

**Comment by sbalaji1192** [comment] 2022-06-08 05:35
@pratikbgit Sorry about that. We were not able to consistently reproduce this issue. That's why the delay in closing this issue.
Could you please post the steps to repro this?

**Comment by jsartisan** [comment] 2022-06-08 12:50
@sbalaji1192 Actually @pratikbgit is the guy who gave us the steps to repro it. The steps I gave in my comment came from @pratikbgit only.

**Comment by sbalaji1192** [comment] 2022-06-08 16:41
@jsartisan @pratikbgit sounds good. This seems like a BE issue. we will have someone take a look at this .

**Closed** 2022-10-26 14:53 UTC
Labels: Bug, High, BE Coders Pod, Entity Refactor, Data Platform Pod
