### ISSUE TITLE
[Bug] Error evaluating trigger: `selectedRowIndices.map` is not a function

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4772] opened 2021-05-28 11:16 UTC
Reported by @alexBotteri, 

> When selecting a line on my user table, I sometimes get this message.

<img width="277" src="https://user-images.githubusercontent.com/120119/119969238-f1be9f00-bfcb-11eb-968b-ad619cf29dd9.png">

I tried with a few scenarios with the table widget with multiple row selection and not selecting anything, and then using the binding in another widget. I couldn't reproduce the problem though. @alexBotteri, can you share some additional details on where the `selectedRowIndices.map` is being used and details on the table as well to help us reproduce the problem?

Thanks!

**Comment by vivekverma2312** [comment] 2021-08-18 09:27
@riodeuno I tried but not able to repro the issue.

**Comment by riodeuno** [comment] 2021-08-31 06:07
@sharat87 @vivekverma2312 Closing this issue for now, as we're not able to reproduce this.

**Closed by riodeuno** 2021-08-31 06:07 UTC
Labels: Bug, UI Building Pod, Needs Triaging, UI Building
