### ISSUE TITLE
[Bug]: [Regression] No redirect on clicking the app link

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14371] opened 2022-06-08 04:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on a link to an app, and I've not signed in. Upon signing in I'm taken to the apps home([app.appsmith.com](http://app.appsmith.com/)). Then I have to come back and click the link again to open the app that I originally wanted to.
Do we know this, and shouldn't there be a redirect upon authentication to the original intended link?

### Steps To Reproduce

1. Log out of app.appsmith.com
2. click this link: https://app.appsmith.com/app/appsmith-standup/standup-form-5fb67116322ddc249377f5eb?branch=master
3. you are prompted to login, so enter credentials and login
--> Expected result: upon successful authentication, you should see the stand up app
--> actual result: upon successful authentication, you see the apps home (https://app.appsmith.com/applications)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-06-08 06:08
Duplicate of #14268

**Closed by Nikhil-Nandagopal** 2022-06-08 06:08 UTC
Labels: Bug, Login / Signup, Needs Triaging, Team Managers Pod, medium, Platform Pod
