### ISSUE TITLE
[Epic]: JS Framework Stability

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9087] opened 2021-11-10 12:06 UTC
### Objective

Improve the JS experience by making it consistent and bug free

### Success Metrics

Reduction in High / Critical Issues

### RACI matrix

| ------------- | ------------- |
| Responsible   | @hetunandu @ApekshaBhosale @ohansFavour @eco-monk @Rishabh-Rathod  |
| Accountable   | @ohansFavour  |
| Consulted     | @Nikhil-Nandagopal @ajinkyakulkarni  |
| Informed      | @mohanarpit  |

**Comment by ohansFavour** [comment] 2021-11-19 16:25
As per the project meeting on the 17th of November;

We were able to do the following,

- Remove issues that were wrongly tagged as part of this epic and add a few issues corresponding to this epic.

-  Discuss the solvability of certain issues and unanimously agree on if these issues should be solved as part of this epic.

- Add estimates to several issues.


### Resolutions

- Considering the total number of estimated points remaining (41) and the number of team members working on this epic, we should be able to make the JavaScript Framework absolutely stable and bug-free in about 3+ weeks.

- Issues with smaller story points are to be worked on first since almost all of these issues are of high priority.



### Pending actions

-  These issues are yet to be estimated

      #9096 
      #9181 
      #7576 
      #8595
      
      
In the next meeting slated for the 24th of November, team members are expected to

- Discuss the progress made so far on achieving the goal of this epic.

- From progress made so far, come up with actionable items required to ensure that we meet the goal and timeline set for the completion of this epic.

**Comment by ohansFavour** [comment] 2021-12-01 12:55
As per the project meeting on the 1st of December;

Each team needs to perform a root cause analysis on the issues assigned to them.

Team 1: @hetunandu , @rohan-arthur and @eco-monk 

Team 2: @ApekshaBhosale , @Rishabh-Rathod and @ohansFavour 


### List of issues for Team1

#8651 
#3027 
#1004
#9181
#6923


### List of issues for Team 2

#3559 
#8943
#7484
#5408 
#7558

**Comment by ajinkyakulkarni** [comment] 2022-01-05 12:30
Meeting notes:
* No significant progress has been made in the last 2 weeks on this epic
* @eco-monk to finish #4789
* @eco-monk to start working #9692
* @ApekshaBhosale to add JSObject metrics to Mixpanel 
* @eco-monk to look at #9391
* Decision to not include Autocomplete Evaluated Value feature (https://www.figma.com/file/X03G0OsEtvH9JHDhU8XREy/JS-Editor?node-id=39%3A10023) as part of this epic

**Comment by ohansFavour** [comment] 2022-01-13 08:29
As per the project meeting on the 12th of January;

We were able to do the following,

- Make recommendations that will help speed up the completion/ closing of this Epic.
- Discuss progress so far on several issues currently being worked on.

#### Resolutions

- More time should be allocated for Sprint planning - @ajinkyakulkarni 
- Issues on this epic should be reviewed and properly prioritized - @rohan-arthur 
- Comments on progress/ blockers should be added to Issues recurring in several sprints  - All Engineers

#### New Project Timeline Estimate

Mid-February

**Comment by ohansFavour** [comment] 2022-01-19 23:54
As per the project meeting on the 19th of January;

### Action Items

- @ohansFavour to look into #9181 
- @ohansFavour to confirm the status of #2862 and @Rishabh-Rathod to look into it if no one is currently working on it
- @rohan-arthur to reschedule sprint planning date

**Closed** 2022-11-15 13:39 UTC
Labels: JS Evaluation, Autocomplete, Epic, FE Coders Pod, Evaluated Value
