### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by hillyzhu** [appsmithorg/appsmith#18171] opened 2022-11-15 08:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Mysql plugin does not use the connection pool, unlike Postgres Plugin using the HikariPool

### Why should this be worked on?

For better performance, it is suggested that the Mysql Plugin can use the connection pool

**Comment by Nikhil-Nandagopal** [comment] 2022-11-21 10:56
Duplicate of #17481 and #8419

**Closed by Nikhil-Nandagopal** 2022-11-21 10:56 UTC
Labels: Enhancement
