### ISSUE TITLE
[Bug]: JSON Form Behaving Weird With Source Data

### ISSUE THREAD

**Issue by utkarshDunzo** [appsmithorg/appsmith#16955] opened 2022-09-21 11:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a JSON Form where I am getting source data from another page and setting the value. When I open the page it's giving error "Something went wrong", but if I open the page again then the error is gone and data is also prefilled.

### Steps To Reproduce

Refer the below video:
https://www.loom.com/share/8dd3dae0bfd94dcd92d52db9af5ac62c

`TypeError: t.trim is not a function
    at main.bcfb3e56.js:2:3518056
    at je (main.bcfb3e56.js:2:3518064)
    at Ja (main.bcfb3e56.js:2:8043165)
    at Bo (main.bcfb3e56.js:2:8052057)
    at Cs (main.bcfb3e56.js:2:8090507)
    at vc (main.bcfb3e56.js:2:8082031)
    at mc (main.bcfb3e56.js:2:8081956)
    at sc (main.bcfb3e56.js:2:8078965)
    at main.bcfb3e56.js:2:8030443
    at t.unstable_runWithPriority (main.bcfb3e56.js:2:8686275)`

### Version

Self Hosted 1.7.8

**Comment by dilippitchika** [comment] 2022-09-22 17:18
@utkarshDunzo we need some help in debugging this, will you be open for a call next week or give us a sample app export where we can reproduce this? 

Here's a calendly link if you are ok with a call - https://calendly.com/dilip_pitchika/30min

**Comment by dilippitchika** [comment] 2023-02-16 07:00
Closing this as we are unable to reproduce

**Closed by dilippitchika** 2023-02-16 07:00 UTC
Labels: Bug, App Viewers Pod, High, Needs Triaging, JSON Form
