### ISSUE TITLE
[Feature]: Scroll To Widget Function

### ISSUE THREAD

**Issue by tiger360** [appsmithorg/appsmith#10057] opened 2021-12-29 14:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello,
I'd like to have a Scroll To Top button or specific section.
Thanks

### Why should this be worked on?

Especially on mobile when the list is very long  instead of scrolling .

**Comment by Nikhil-Nandagopal** [comment] 2021-12-30 06:24
@tiger360 thank you for the feature request. A good way to solve this would be to allow users to call a function that scrolls to any widget on a page.

**Comment by oskarannas** [comment] 2022-01-10 10:26
This one is similar to #8314, maybe the could be combined :)

**Comment by Nikhil-Nandagopal** [comment] 2022-01-11 12:06
@oskarannas great catch! It is a duplicate of #8314

**Closed by Nikhil-Nandagopal** 2022-01-11 12:06 UTC
Labels: Enhancement, Actions Pod, FE Coders Pod, New JS Function
