### ISSUE TITLE
[Feature]: Apache Cassandra datasource support

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17028] opened 2022-09-23 12:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith should look to provide support for Cassandra datasource

### Why should this be worked on?

Given the current usage and popularity of this datasource it would be good for appsmith to have an option for the users to connect to this datasource. 
Refer article- 
1. https://techcrunch.com/sponsor/datastax/how-the-world-caught-up-with-apache-cassandra/ 
2. Companies like Facebook, [Instagram](https://instagram-engineering.com/tagged/cassandra) and [Netflix](https://netflixtechblog.com/tagged/cassandra) use Apache Cassandra for mission-critical features.
3. Cassandra is the most popular wide column store database system on the market - https://logz.io/blog/nosql-database-comparison/#:~:text=Cassandra%20is%20the%20most%20popular,database%20system%20on%20the%20market.

**Comment by Nikhil-Nandagopal** [comment] 2022-09-26 09:25
Duplicate of #4063

**Closed by Nikhil-Nandagopal** 2022-09-26 09:25 UTC
Labels: Enhancement, New Datasource, Integrations Pod
