### ISSUE TITLE
[Bug]: Reset widget not working properly 

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#11965] opened 2022-03-18 07:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a form with multiple fields and while selecting a dropdown value some data will be fetched from db and shown to other widgets . when deselecting the option the widgets filled with data should be changed to default value state. I tried by calling resetwidget() for each and every field but did not work.

1. Before selecting fee term

![Screenshot (42)](https://user-images.githubusercontent.com/94359116/158954520-b931ebf8-b516-4e7f-837a-bfabc9b3d1d3.png)

2.Here while select fee term the data are populating to the fields

![Screenshot (43)](https://user-images.githubusercontent.com/94359116/158954528-83fa77c5-06f0-44c1-ae86-a2623409d4a8.png)

3.After deselecting the fee term some widget like number field only are got reset.

![Screenshot (44)](https://user-images.githubusercontent.com/94359116/158954529-4eae12bd-20d7-46c4-b2e5-a8e6de5d83cd.png)

### Steps To Reproduce

1.Include a for with multiple  type widgets.
2. Populate some data to the widgets on change event of  select dropdown.
3. Reset widgets by calling resetWidget() in a js function on change event before executing the query to show data  and check.

### Version

Self hosted v1.6.15

**Comment by Nikhil-Nandagopal** [comment] 2022-03-21 10:11
@ginjojohny can you share the code for the reset widget? You just need to call resetWidget('Container1', true) to reset all widgets inside a container

**Comment by ginjojohny** [comment] 2022-03-21 11:40
I  have tried  this by reset individual widget like this 
	resetWidget("fee_term"); 
	resetWidget("industry_category");
	resetWidget("amount"); 
and so on .

Also tried with the method you mentioned   as  resetWidget("fee_details",true);   where  'fee_details'   is my container name.

While inspecting errors showing as shown in the image.
![Screenshot (48)](https://user-images.githubusercontent.com/94359116/159254042-92d79a6d-d7fe-4287-be23-79447dd53630.png)

**Comment by Nikhil-Nandagopal** [comment] 2022-03-21 13:36
@ginjojohny this seems like it needs deeper investigation by us. Can you share your app with support@appsmith.com?

**Comment by ginjojohny** [comment] 2022-03-30 10:08
@Nikhil-Nandagopal  shared the app to the above mentioned mail id

**Comment by pranavkanade** [comment] 2022-04-12 07:24
I could not reproduce the problem. I am closing this issue for now.

**Closed by pranavkanade** 2022-04-12 07:24 UTC
Labels: Bug, Needs More Info, Needs Triaging

**Comment by ginjojohny** [comment] 2022-04-13 09:01
Hi, @pranavkanade  shared loom video  which shows the issue to pranav@appsmith.com .

**Comment by pranavkanade** [comment] 2022-04-14 07:21
@ginjojohny just confirmed this is not the `resetWidget` issue. I am replying to your email with a detailed resolution.
RCA - The default values are bound to a query response that is not cleared when the option changes; hence, as expected, input fields show the values even after widget reset.

**Comment by ginjojohny** [comment] 2022-04-19 07:06
@pranavkanade  issue fixed as per your solution. Thank you.

**Comment by prajyotPatilpp** [comment] 2023-10-29 11:06
@ginjojohny can you please forward the solution to prajyot.jio008@gmail.com. Thank you.
