### ISSUE TITLE
[Bug]: Dynamic menu buttons in tables break if there are more than 10 rows

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#24504] opened 2023-06-15 19:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a table, and one of the columns is a menu button. This menu button is dynamic. In this menu button, I have hard-coded a single option. The options will be the same for each row. This works fine for up to ten table rows. When I add the eleventh table row, the menu buttons no longer open. We get this error in the table:

<img width="589" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101155659/cde78946-d618-494c-817b-bba250773c9d">

I expect it only to allow 10 menu options per row instead of 10 sets of menu options in the table. Here it appears to be checking the length of the wrong arrray. Each button only has one option, but there are more than 10 buttons.

### Steps To Reproduce

1. Open the public sample app of this issue.
2. Click a menu button in the table.
3. Observe that the menu appears.
4. Click the `Add One Row` button.
5. Click a menu button in the table again.
6. Observe that nothing happens.

### Public Sample App

https://app.appsmith.com/app/table-menu-button-issue/example-648b30f7e923f357ae1e8ec1

### Environment

Production

### Version

Cloud v1.9.22-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fafrg)

**Comment by dilippitchika** [comment] 2023-07-05 05:25
@dhruvikn looks like a regression to me, can you look at it once next sprint?

**Comment by dhruvikn** [comment] 2023-07-05 05:33
Sure. Have added it to the next sprint. @dilippitchika

**Comment by dhruvikn** [comment] 2023-07-26 09:17
I was triaging this. I think this can be fixed with a small change. Have raised [a PR for the same here](https://github.com/appsmithorg/appsmith/pull/25724). @sbalaji1192, can you please take a look once you get a chance?

**Comment by sbalaji1192** [comment] 2023-07-27 07:54
@dhruvikn Let's write a new validation config for this property in the table. since it can be an array or an array of arrays. Check out the UNION validation.

**Closed** 2023-08-24 03:50 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, Regressed, Needs Triaging
