### ISSUE TITLE
[Bug] When an onPageLoad action fails, the editor breaks

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1203] opened 2020-10-14 18:09 UTC
## Description

If an onPageLoad API times out, the application goes into a bad state

### Steps to reproduce the behaviour:
1. Create an app
2. add a query
3. add a low timeout for the query
4. mark the query to run onPageLoad
5. Bind the query to a table
6. Refresh the page
7. The query can no longer be run from the query pane and no error is mentioned.
8. All other APIs are also suddenly timing out with the timeout that the query failed with.

**Comment by prapullac** [comment] 2020-10-21 10:07
Reopening the issue as the issue still exists on Release

**Comment by hetunandu** [comment] 2020-10-21 15:11
@prapullac Can you help me with an error case? Is there an error message shown?

**Comment by prapullac** [comment] 2020-10-22 12:34
@hetunandu Adding the screenshot for the above issue
![Screen Shot 2020-10-22 at 6 03 09 PM](https://user-images.githubusercontent.com/71753653/96872233-fc8edf80-1490-11eb-80aa-fff334c4b3d5.png)

**Comment by hetunandu** [comment] 2020-10-22 12:52
@prapullac This is the expected behaviour. onPageLoad actions can break but the editor should still be functional. You should still be able to create/edit/run actions which used to break before. Please test if that still works. The error is shown to tell the user that the page load actions may have some issues

**Comment by mohanarpit** [comment] 2020-10-22 13:29
@hetunandu Wouldn't it be better to inform the user specifically which actions aren't working properly? Is that possible?

**Comment by hetunandu** [comment] 2020-10-22 14:13
Should be possible @mohanarpit. Can we open a new issue for this?

**Comment by mohanarpit** [comment] 2020-10-23 06:28
Opened #1357 to fix the error message being displayed to the user.

**Comment by hetunandu** [comment] 2020-10-23 09:38
Closing this since it is working as expected

**Closed** 2020-10-23 09:38 UTC
Labels: Actions, Bug, Critical, Frontend, High
