### ISSUE TITLE
[Bug] Seeing a lot of items in autocomplete even though they are not on the screen

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1027] opened 2020-10-06 12:13 UTC
https://www.notion.so/Seeing-a-lot-of-items-in-autocomplete-even-though-they-are-not-on-the-screen-3bafa6d2ad334aea9f9fe4f4bfc1fc83

**Comment by hetunandu** [comment] 2020-10-06 12:16
Hey @prapullac can you test this in our current release? I think it should be solved with the immutable widgets change

**Comment by Nikhil-Nandagopal** [comment] 2020-10-06 14:08
duplicate of #951

**Closed by Nikhil-Nandagopal** 2020-10-06 14:08 UTC
Labels: Bug, Low, Release

**Comment by prapullac** [comment] 2020-10-08 04:44
We can close the issue as it is working as expected
