### ISSUE TITLE
Excel sheet download not working in table widget

### ISSUE THREAD

**Issue by anshika-optum-rrt** [appsmithorg/appsmith#35120] opened 2024-07-23 13:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi Team,
 
We are trying to download Excel sheet from a table widget (as shown in the below screenshot) but on opening it states as file corrupted with 0 records in it.
Please let us know is there any restriction we have with the counts of the records to be downloaded or exported into excel , as I see on other pages where counts are lesser we are able to download in excel 

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/27ace2fd-7215-4595-821d-40682325f3c3)

Issue we are facing in excel is :
![image](https://github.com/user-attachments/assets/07760b47-45cb-4425-a9f5-bd943eac7e51)
On click Yes , getting this.
![image](https://github.com/user-attachments/assets/7e09c313-0eb8-479f-9985-8121b6e4446d)
On click ‘Close’. Getting all blank file.

Please let me know if you have further concerns.
Thanks,
Anshika Singh

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Appsmith v1.27

**Comment by Nikhil-Nandagopal** [comment] 2024-07-29 10:40
@anshika-optum-rrt it seems to be working for us, can you share a sample of the table data which you can get from the evaluated value?

**Comment by saicharan-zemoso** [comment] 2024-08-13 07:28
Hello @anshika-optum-rrt ,
I have tried reproducing the issue with 119 cloumns and 5613 rows and it is working fine for me. 
and this is the video :

https://github.com/user-attachments/assets/10287cd0-e4d1-44ce-985f-63e0817cf1ff

I wan't able to upload the data but here is a screen shot of it:
![image](https://github.com/user-attachments/assets/66223a18-b360-4d7f-afe2-4ce39b1a138f)

can you provide the steps followed to reproduce??

can you also check if the data contains "," or any special characters which can be used to separate the data

**Comment by Nikhil-Nandagopal** [comment] 2024-08-13 07:33
@akhabibulin-casecreate can you please share the evaluated value of the data you are trying to download?

**Comment by akhabibulin-casecreate** [comment] 2024-08-13 09:30
[table3.json](https://github.com/user-attachments/files/16597219/table3.json)
[table3_data.json](https://github.com/user-attachments/files/16597221/table3_data.json)


> @akhabibulin-casecreate can you please share the evaluated value of the data you are trying to download?

Here's table.json and its data. There are Cyrillic symbols but this is not the case. If you will change "Расход новых <30 дней" column to plain text, it will be downloaded normally. When this or other similar columns have "number" type, it won't work.

**Comment by akhabibulin-casecreate** [comment] 2024-08-20 13:52
Hi! @Nikhil-Nandagopal have you seen it?

**Comment by saicharan-zemoso** [comment] 2024-08-22 08:29
This problem is due to applying number type to the column name. This can be fixed with a small change.

**Comment by saicharan-zemoso** [comment] 2024-08-22 08:39
Hello @akhabibulin-casecreate , can you conform  if this is your expected excel output file.
[output.xlsx](https://github.com/user-attachments/files/16707767/output.xlsx)

screen shot of the data in the table:
![image](https://github.com/user-attachments/assets/32d0d8b9-76fd-4505-af11-4524187d2a0a)

screenshot of output file:
![image](https://github.com/user-attachments/assets/6d0a9c30-1043-4a54-b0dd-748823ed63cb)

**Comment by akhabibulin-casecreate** [comment] 2024-08-22 15:27
> This problem is due to applying number type to the column name. This can be fixed with a small change.

Yes, it is. And your output is correct. But I want this column to be number type, so I fixed this issue with changing number type to text which cause mistyping this column by Excel. So it's not a good solution for me
![image](https://github.com/user-attachments/assets/0c88cc48-8d3a-4dae-8cd1-367ff0fa0a2d)

**Comment by saicharan-zemoso** [comment] 2024-08-23 08:28
No we don't need to change the type of the whole column just for the column name ie here:
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/TableWidgetV2/component/header/actions/Download.tsx#L148-L160

we are getting this issue because it is trying to assign number type to that column name text.

**Comment by akhabibulin-casecreate** [comment] 2024-08-26 09:26
![image](https://github.com/user-attachments/assets/6df4643d-fd96-4646-975e-01435818abe3)
I can't change type of the column name, only the whole "Column type".

**Comment by Nikhil-Nandagopal** [comment] 2024-08-26 09:28
@akhabibulin-casecreate you can change the column name by clicking it's name at the top of the property pane.

**Comment by akhabibulin-casecreate** [comment] 2024-08-26 09:43
Emm, ok. It seems that the issue with the special character "<" is resolved. When it was removed from the column name, the Excel file compiled successfully. So you can combine numbers and text inside the column name but do not include at lest this special character.

**Comment by Nikhil-Nandagopal** [comment] 2024-08-26 09:45
Glad it's working now. @anshika-optum-rrt feel free to re-open this if it's still not working for you

**Closed by Nikhil-Nandagopal** 2024-08-26 09:45 UTC
Labels: Bug, Table Widget, Widgets Product, High, Production, Community Reported, Needs Triaging, Inviting Contribution, Widgets & Accelerators Pod

**Comment by saicharan-zemoso** [comment] 2024-08-26 15:29
Hello @Nikhil-Nandagopal ,
The problem was for the columns which are of type number it was trying to convert the column name to number as well and for some reason when the name contained "<" symbol it corrupted the file. 

If we change the type of column names to string in here:
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/TableWidgetV2/component/header/actions/Download.tsx#L148-L160

the issue will be resolved and will work even if the column name contains the "<" symbol in them.
So, can I fix this and raise a PR for this. Or is it not required.

**Comment by Nikhil-Nandagopal** [comment] 2024-08-26 15:32
@saicharan-zemoso let's wait for more instances of this to holistically fix this because there might be other cases where this is breaking
