### ISSUE TITLE
[Bug]Editor Window->The table widget name display the red color warning for a split second even when the data is correct

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4762] opened 2021-05-28 06:54 UTC
## Description

[What happened] 
table widget Editor window->When the user refresh the page which has a table widget with the API or DB data binding, The table widget name display the red color warning for a split second

Steps to reproduce the behaviour:
1.Drag and drop a table widget
2.add a New api
3.Bind the table with the API
4.Refresh the page
5.Verify the display name of the  table widget

expected result:
table widget Editor window->When the user refresh the page which has a table widget with the API or DB data binding, The table widget name should not display the red color warning for a split second when there is no error
Actual Result:
table widget Editor window->When the user refresh the page which has a table widget with the API or DB data binding, The table widget name display the red color warning for a split second even when there is no error
![image](https://user-images.githubusercontent.com/45958978/119942308-4a337380-bfaf-11eb-9186-20a4bcef520d.png)

### Important Details

- Version: Cloud 
- OS: Windows
- Browser: Chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment] 2021-06-03 07:16
Duplicate of #4298

**Closed by Nikhil-Nandagopal** 2021-06-03 07:16 UTC
Labels: Bug, Needs Triaging, Platform, error
