### ISSUE TITLE
[Bug] 502 in save layout is abruptly taking me to an error screen

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2452] opened 2021-01-05 14:08 UTC
## Description

A 502 for this request PUT 
 https://app.appsmith.com/api/v1/layouts/5fe08b3e8b57d44aea1af0e7/pages/5fe08b3e8b57d44aea1af0e8
took me abruptly to an error screen while I was editing my app

<img width="1680" alt="Screenshot 2021-01-05 at 6 56 05 PM" src="https://user-images.githubusercontent.com/3897254/103655628-8a0ca680-4f8d-11eb-82a5-5f6c980c269a.png">

**Comment by jsartisan** [comment] 2021-01-06 05:10
@Nikhil-Nandagopal Can you help me reproduce this?

**Comment by Nikhil-Nandagopal** [comment] 2021-01-06 06:27
@jsartisan you'll have to mock a 502 on the frontend. Maybe removing internet might also work

**Comment by mohanarpit** [comment] 2021-01-06 09:16
@jsartisan You can reproduce this by using Cypress's [network stubbing feature](https://docs.cypress.io/guides/guides/network-requests.html#Stubbing). 

Disconnecting your internet will not work because that'll just show no connectivity. HTTP status 502 is returned by the load balancer when the backend API service is not available.

**Comment by jsartisan** [comment] 2021-01-11 06:00
Closed in #2475

**Closed by jsartisan** 2021-01-11 06:00 UTC
Labels: Bug, Critical, Editor, Frontend, Platform
