### ISSUE TITLE
[Bug] If user logs off a profile user must be navigated to login page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1439] opened 2020-10-28 07:17 UTC
Steps to reproduce :
1) Log into to an account 1
2) Open the same account in another tab of the same browser
3) Now log out of the account from one tab 
4) Navigate to another tab and refresh
and observe

Observation:
It is observed that on refresh the user is navigated to 404 error page 

Expectation:
user must be able navigated to Login page if the user is logged off

**Comment by mohanarpit** [comment] 2020-10-28 11:48
@prapullac This is expected behaviour. Instead of redirecting the user directly to the login page, we show the user that the page either doesn't exist or that they don't have permissions to access it. This is because the flow is equivalent to coming to the page with an invalid pageId. If we expose to the user which pageId is invalid & which one the user doesn't have access to, that's a security leak.

Closing this issue.

**Closed by mohanarpit** 2020-10-28 11:48 UTC
Labels: Bug, Login / Signup, Low, Release
