### ISSUE TITLE
[Feature]: Deploy without committing to git repo everytime

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#11361] opened 2022-02-22 23:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I remember seeing a discussion about this on Figma, but I couldn't find the issue for it. 
1. Today users need to commit every change to their repo 
2. It adds an extra step to someone who is building and testing their app in rapid succession
3. Can we add a way to deploy to the URL without needing to use Git sync?
Original comment here: https://community.appsmith.com/t/deploy-without-being-forced-to-commit-with-git/664

### Why should this be worked on?

It reduces the steps required to deploy to a URL

**Comment by hiteshjoshi** [comment] 2022-03-17 13:21
@areyabhishek any application connected to git have a default branch. The concept of default branch is similar to having default (display) branch on GitHub.com 
Will it be okay if we let users deploy just default branch without committing. Doing it on every branch is also not a technical challenge. But would like users to understand a bit about privacy here. The problem is git based urls today are just a query parameter away. 
Now this can go wrong if someone knows your git branch names and you want to keep some branches private and only one public.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-18 11:51
I don't think we should solve this problem right now. This user's problem was that they could not test things out properly in our preview mode because there were bugs there. Lets solve that first

**Comment by hiteshjoshi** [comment] 2022-03-19 07:24
Closing this.

**Closed** 2022-03-19 07:24 UTC
Labels: Enhancement, UX Improvement, community, Platform Pod, Git Version Control, Team Managers Pod
