### ISSUE TITLE
[Bug] Dropdown jumps if there is no space inside modal when it opens

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#995] opened 2020-10-05 15:44 UTC
https://www.notion.so/Dropdown-jumps-if-there-is-no-space-inside-modal-when-it-opens-005b3df5f34143e5a30b341517b6b2af

**Comment by riodeuno** [comment] 2021-06-07 10:46
@prapullac @vivekverma2312  Please verify if this is still an issue.

**Comment by vivekverma2312** [comment] 2021-06-07 13:11
@riodeuno This issue still exist.
## Steps to reproduce
1. Create an alert modal
2. Drag a dropdown into modal
3. Add a large list in the dropdown
4. Open the dropdown

<img width="576" alt="Screenshot 2021-06-07 at 6 12 40 PM" src="https://user-images.githubusercontent.com/83569920/121022160-b8521480-c7bf-11eb-82d4-20708be2d006.png">

**Comment by somangshu** [comment] 2021-06-08 09:17
@vivekverma2312 what is the issue here, If the list is too long and crosses over the modal boundary I think that's the intended behaviour!

**Comment by vivekverma2312** [comment] 2021-06-08 09:29
@somangshu The dropdown options should come below the select widget and should not open from top.

**Comment by somangshu** [comment] 2021-06-08 11:04
@techbhavin do you have an idea why this is happening?

**Comment by techbhavin** [comment] 2021-06-08 15:03
> I observe when we have a large list of dropdown options and we are trying to search ,so list item will be decreased and options popover will change this position top to bottom.

![sample](https://user-images.githubusercontent.com/58818598/121209760-c031b780-c898-11eb-8fe8-cd4f9f02994c.gif)


> In issue #4290 (same issue with date picker widget). so here it was fixed by applying min-height in pop-over.

can we apply the same solutions here?

**Comment by somangshu** [comment] 2021-06-10 06:19
@techbhavin does this mean that the popper will always remain fixed at the bottom? Also, will there be a lot of unnecessary white space?

**Comment by techbhavin** [comment] 2021-06-10 09:22
@somangshu  agree with your point this will be not a good UX, we need to think of other solutions instead.

> @techbhavin does this mean that the popper will always remain fixed at the bottom? Also, will there be a lot of unnecessary white space?

**Comment by riodeuno** [comment] 2021-06-11 10:56
@techbhavin I believe, the core issue here is the jumping of the dropdown. So, making sure that the dropdown is fixed in a certain direction, we will make sure that it doesn't cause UX issues for our users. So, let us try to solve it in this manner, all the while making sure that this approach doesn't cause other issues to show up.

**Comment by somangshu** [comment] 2021-06-22 10:13
This is fixed for the multiselect.

@Tooluloope will be fixing this for the select widget as well;

**Comment by riodeuno** [comment] 2021-06-25 12:04
Fixed in #5069

**Comment by somangshu** [comment] 2021-06-28 11:36
@vivekverma2312 we need to see if this is fixed for both select and multi-select. We can close it in the same PR then

**Comment by vivekverma2312** [comment] 2021-06-28 12:17
@somangshu https://github.com/appsmithorg/appsmith/pull/5228#issuecomment-869516254
This issue is working for multi select but not for select. 
@Tooluloope Can you please mention the separate PR for this issue and link.

**Comment by somangshu** [comment] 2021-06-28 13:27
@vivekverma2312 we will take this up separately, Lets push back all such issue to product backlog where the fix is present in multi-select but not select.

**Comment by Tooluloope** [comment] 2021-06-29 16:56
@vivekverma2312 @somangshu Made a fix for select as well on The Multiselect PR.
@vivekverma2312 You can test it now.

**Comment by somangshu** [comment] 2021-06-30 10:29
@Tooluloope please link the PR.

@vivekverma2312 Please push to the required pipeline After you have tested this out

**Comment by vivekverma2312** [comment] 2021-06-30 11:42
@Tooluloope This is tested on deploy preview of PR #5228 and working fine.

**Closed** 2021-08-03 06:38 UTC
Labels: Bug, Low, Modal Widget, Release, Select Widget, UI Building Pod, Widgets
