### ISSUE TITLE
[Bug]: App works on build mode but got API 404 and timeout error on both production/deployed mode

### ISSUE THREAD

**Issue by yitecdeveloper** [appsmithorg/appsmith#24805] opened 2023-06-24 02:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Application keep showing all the query has failed, got this error when open console log
Refused to set unsafe header "Expect"
GET https://appsmithdomain/api/v1/applications/snapshot/6495f2ed93e91c1592cfd8a2... 404

### Steps To Reproduce

1. Create an app with 2 page, page 1 has a list view and each list item when you click in will redirect to an item view page with passed ID param
2. Deploy the app and go to the app's URL
3. Click on an item to navigate to view item detail page

### Public Sample App

https://app.appsmith.com/app/tiktok-builder/trang-chinh-6495f3c19135f82ab51b9084

### Environment

Production

### Version

Cloud

**Comment by AS-Laguna** [comment] 2023-06-26 20:36
On the first page we get this error in the console: `Refused to set unsafe header "Expect"` and a 404 for this url: https://app.appsmith.com/api/v1/applications/snapshot/6495f3c19135f82ab51b9080

<img width="513" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101155659/d7c1489b-da4d-4ed8-97f7-b34e1418b6dd">


On the second page, we get the same as well as the queries failing:

<img width="497" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101155659/a42b21d0-6123-4f90-bd14-5c36ef49953f">


@yitecdeveloper Can you please add support@appsmith.com as a developer to your example app so we can take a closer look?

**Comment by yitecdeveloper** [comment] 2023-07-03 02:40
Invited, the API is 404 but in build mode it works fine. I think it must be a bug.

**Comment by LagunaElectric** [comment] 2023-09-13 19:17
I've confirmed this now. It seems to happen any time I call a query. My query returns fine, but it always displays this error in the console.

**Comment by AlexiaAcevedo** [comment] 2023-09-13 21:24
This happens to me whenever I make an API or DB query. Does not affect the functionality of my application but clogs up the console.

**Comment by LagunaElectric** [comment] 2023-11-20 16:03
Looking closer in the sample app I see `JSON reader expects a string but found 'null'.` in the query failure message:

<img width="576" alt="image" src="https://github.com/appsmithorg/appsmith/assets/6085143/4e49722f-9fd7-4f22-b2d8-1b5ae847ca42">

This comes after clicking one of the buttons on the list in the landing page. One of the queries is reading from the query params and failing with the above error. This only happens in deployed mode.

**Comment by Nikhil-Nandagopal** [comment] 2023-11-22 17:20
@Too-Smart @yitecdeveloper I think the issue is that the navigate function is not adding the query param in the deployed mode. You can get around this by storing the value using {{storeValue('key', value)}} and referencing it as {{appsmith.store.key}} in the new page and that should work

**Comment by bharath31** [comment] 2023-11-23 04:54
@Nikhil-Nandagopal this does not seem like an issue with the `navigateTo` function. Here's a sample app that works fine- https://app.appsmith.com/app/navigateto-params/overview-655ed565b6b8894bd68a29a2

@AlexiaAcevedo @yitecdeveloper could you share how you are reading the query params and passing it to your API or DB query?

**Comment by arunvjn** [comment] 2023-11-23 10:43
@yitecdeveloper The usage of params in navigate button is incorrect. Could you please try passing it like this
```
{{{
"id": currentView.scriptID.text
}}}
```
Please go through https://docs.appsmith.com/reference/widgets/list#access-list-items for more info.

**Comment by arunvjn** [comment] 2023-11-27 05:27
Closing this issue since the originally affected application works fine by tweaking the code as per the comment above

**Closed by arunvjn** 2023-11-27 05:27 UTC
Labels: Bug, High, FE Coders Pod, Framework Functions
