### ISSUE TITLE
[Bug]: Table Widget unable to show data for new JSON form based CRUD page

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13242] opened 2022-04-24 10:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reported by @abhvsn 

When we create a new CRUD page (JSONForm-based), it was noticed that the TableWidget wasn't showing data. 
OnRowChange did work as expected though.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/08cdf3f56e264470a0aed893cd7c7dca-00001.gif)](https://www.loom.com/share/08cdf3f56e264470a0aed893cd7c7dca)

### Steps To Reproduce

1. Go to the ec2 instance where new backend changes are deployed for the CRUD page
http://ec2-3-108-64-217.ap-south-1.compute.amazonaws.com/app/
2. Create a new page using Generate page feature
3. Check the table widget. 

### Public Sample App

http://ec2-3-108-64-217.ap-south-1.compute.amazonaws.com/app/my-first-application/page3-62652b7853c44339b0aa0241/edit

### Version

https://github.com/appsmithorg/appsmith/pull/12662

**Comment by dilippitchika** [comment] 2022-04-25 07:26
@abhvsn i believe we will need a call for this for the changes you have done in the backend to support this with @sbalaji1192 once. 

The reason i am asking is because the column names are also not updated by default to the correct column names. 

I am assigning this to @sbalaji1192 and you for the time being to discuss and come back with a root cause. Hope that works. 

Can you also link this issue to the main crud generation improvement issue, if any?

**Comment by abhvsn** [comment] 2022-04-26 06:52
@dilippitchika can you elaborate on  `The reason I am asking is because the column names are also not updated by default to the correct column names.`

We haven't made any updates for table binding in the current CRUD template, you can check the binding by generating a CRUD page on the provided instance. Also, if I am not mistaken we are seeing the table columns getting updated correctly as per Rishabh's screen recording also if we select different rows we can see the data is modifying in the JSON form, we can jump on a call to triage this further though.

**Closed** 2022-05-06 05:42 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, UI Building Pod, Needs Triaging, Generate Page, New Developers Pod, Platform Pod
