### ISSUE TITLE
[Bug]: The Default value is not displayed when user click on JS for toggle 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8647] opened 2021-10-20 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Check, box widget click on js for Inline toggle  the data is displayed empty for the first time 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9c99e59540f44f67972dcb7781382780-00001.gif)](https://www.loom.com/share/9c99e59540f44f67972dcb7781382780)

### Steps To Reproduce

```markdown
1. Got to canvas
2. Drag and drop the check box group widget
3. Inside the property pane Click on JS for Inline toggle 
4. The Data is displayed blank
```

### Environment

Release

### Version

Cloud

**Comment by aswathkk** [comment] 2021-11-29 04:47
@somangshu This happens not due to the issue with JS Convertible functionality.
This happens since the default value for `isInline` is not provided [here](https://github.com/appsmithorg/appsmith/blob/2a3089383ae59508a65288b97ef0e6c98b6346e3/app/client/src/widgets/CheckboxGroupWidget/index.ts)

**Comment by tauantcamargo** [comment] 2022-10-07 18:34
can i get it? @somangshu

**Comment by aswathkk** [comment] 2022-10-07 18:47
Hi @tauantcamargo,
When I checked this, I'm unable to reproduce this issue. So, I'm closing this.
Thanks for showing interest Please check out other open issues.

**Closed by aswathkk** 2022-10-07 18:47 UTC
Labels: Bug, Good First Issue, App Viewers Pod, Low, Release, Checkbox Widget
