### ISSUE TITLE
[Bug]: Unable to use TED oauth

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#15541] opened 2022-07-29 10:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to use TED oauth rest api with appsmith

### Steps To Reproduce

Steps 
1) docker run  --name appsmithted-oauth -d  -p 6001:6001  appsmith/test-event-driver:nightly
2) signup http://localhost:6001/ 
3) create client 
![image](https://user-images.githubusercontent.com/84702014/181735256-5c346bc4-dfa1-4e7c-904e-ef8ff98e7949.png)
4) click save & authorize
5) try using api http://localhost:6001/api/echo/get?ASDSA=ASDSA
This works in post man
![image](https://user-images.githubusercontent.com/84702014/181735386-55449230-13b2-498f-b786-f19dd7001d5f.png)
 
![image](https://user-images.githubusercontent.com/84702014/181735441-0f842c39-7ba0-45e9-b5b5-a8d274f0302a.png)

### Version

self hosted

**Comment by yatinappsmith** [comment] 2022-07-29 10:02
Marking this issue as high as it will unblock test automation

**Comment by nidhi-nair** [comment] 2022-08-18 09:04
This works for locally hosted Appsmith. The issue seems to be with using ngrok along with TED's authorization server, closing the issue for now since Yatin confirmed that locally hosted server suffices for automation.

**Closed by nidhi-nair** 2022-08-18 09:04 UTC
Labels: Bug, High, BE Coders Pod, REST API plugin
