### ISSUE TITLE
[Bug]: Unable to find environmentid error

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#26301] opened 2023-08-11 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some users reported that the `Unable to find environment id <id>` error occurs in various scenarios: when an application page is reloaded, when a Postgres query is executed, when an Airtable API is tried to be created, among others.

![1](https://github.com/appsmithorg/appsmith/assets/114161539/09fa3626-8f9b-404c-8a8d-e26bf2dbe6c0)

### Steps To Reproduce

Since I was not able to replicate the error, I am attaching the conversations with each of the users:

1. https://app.frontapp.com/open/cnv_12yvuy4s?key=IpJCxACoAjSfgeMpBUjbjTk8IzEMVZmU

2. https://app.frontapp.com/open/cnv_12qfbqto?key=c2bYHKzKc8cSe-1Z7mkqptFSoyah_kW7

3. https://app.frontapp.com/open/cnv_12qb90p8?key=P_wCtYDh9XmnmM-6mecQ8_4kDZsKUEI5

4. https://app.frontapp.com/open/cnv_11uog83w?key=OM9D_n8csBEWw70iNBSdD9UmctBlzYev

### Environment

Production

### Version

Cloud

**Comment by ayushpahwa** [comment] 2023-08-26 07:23
This is going to be resolved with the changes made under this issue https://github.com/appsmithorg/appsmith-ee/issues/2164

**Comment by riteshkew** [comment] 2024-07-22 10:23
Not reproducible in the latest version and the underlying issue could be due to permissions or resource not found

**Closed by riteshkew** 2024-07-22 10:23 UTC
Labels: Bug, High, Production, Community Reported, Needs Triaging, BE Coders Pod, Datasource Environments, Git Pod, Custom environments
