### ISSUE TITLE
[Bug] Unable to connect to MySQL after upgrade to version 1.5

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4462] opened 2021-05-13 01:22 UTC
A MySQL datasource on a self-hosted instance that was working before the upgrade to v1.5, was reported to fail repeatedly with no details of the error and no workaround. Following is the stacktrace:

```
  - [id: 0xcdbc3f5c, L:/10.10.108.204:50378 ! R:test.xxxxxxxxxxx.us-west-2.rds.amazonaws.com/10.10.10.10:3306] Error was received while reading the incoming data. The connection will be closed.           │
│ reactor.core.Exceptions$BubblingException: dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection unexpectedly closed                                                                            │
│     at reactor.core.Exceptions.bubble(Exceptions.java:170)                                                                                                                                                       │https://codeshare.io/
│     at reactor.core.publisher.Operators.onErrorDropped(Operators.java:521)                                                                                                                                       │
│     at reactor.core.publisher.EmitterProcessor.onError(EmitterProcessor.java:275)                                                                                                                                │
│     at dev.miku.r2dbc.mysql.client.ReactorNettyClient.drainError(ReactorNettyClient.java:254)                                                                                                                    │
│     at dev.miku.r2dbc.mysql.client.ReactorNettyClient.handleClose(ReactorNettyClient.java:260)                                                                                                                   │
│     at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:257)                                                                                                                              │
│     at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1871)                                                                                                              │
│     at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:359)                                                                                                                     │
│     at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:268)                                                                                                                │
│     at reactor.core.publisher.EmitterProcessor.checkTerminated(EmitterProcessor.java:489)                                                                                                                        │
│     at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:350)                                                                                                                                  │
│     at reactor.core.publisher.EmitterProcessor.onComplete(EmitterProcessor.java:293)                                                                                                                             │
│     at dev.miku.r2dbc.mysql.client.ReactorNettyClient.resumeError(ReactorNettyClient.java:215)                                                                                                                   │
│     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)                                                                                                              │
│     at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214)                                                                                                                                 │
│     at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:424)                                                                                                                                 │
│     at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:210)                                                                                                                                     │
│     at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:353)                                                                                                                                     │
│     at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:353)                                                                                                                         │
│     at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)                                                                                                              │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                                                                                                    │
│     at dev.miku.r2dbc.mysql.client.MessageDuplexCodec.handleDecoded(MessageDuplexCodec.java:187)                                                                                                                 │
│     at dev.miku.r2dbc.mysql.client.MessageDuplexCodec.channelRead(MessageDuplexCodec.java:95)                                                                                                                    │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                                                                                                    │
│     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)                                                                                                                │
│     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)                                                                                                                    │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                                                                                                    │
│     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)                                                                                                         │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                                                                                                  │
│     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                                                                                                  │
│     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)                                                                                                                  │
│     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)                                                                                     │
│     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)                                                                                                                               │
│     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)                                                                                                                                        │
│     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)                                                                                                              │
│     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                                                 │
│     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                     │
│     at java.base/java.lang.Thread.run(Unknown Source)                                                                                                                                                            │
│ Caused by: dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection unexpectedly closed                                                                                                            │
│     at dev.miku.r2dbc.mysql.client.ClientExceptions.unexpectedClosed(ClientExceptions.java:32)                                                                                                                   │
│     ... 40 common frames omitted                                                                                                                                                                                 │
                                                                                             
```

**Marking as Critical since this is blocking users from using their MySQL datasources and queries without any workaround.**

**Comment by sumitsum** [comment] 2021-05-13 06:43
Issue resolved by setting `SSL` to `Disabled`. The error had been documented here as well: https://docs.appsmith.com/troubleshooting-guide/action-errors#mysql-plugin-errors

Verified by user on Discord:
`It worked.. by editing SSL field in the data source configuration form and setting it to Disabled. Thanks @Sumit`

**Closed by sumitsum** 2021-05-13 06:43 UTC
Labels: Bug, MySQL, Needs Triaging, community

**Comment by sumitsum** [comment] 2021-05-14 08:31
Looks like the issue is with the Java version we use with our docker container. It uses v11.0.11 which has TLSv1 protocol disabled. I checked via enabling the protocol again that we don't see this issue. Also, with v11.0.10 installed on my local we don't see this issue.

```
JDK-8256490: Disable TLS 1.0 and 1.1
====================================
TLS 1.0 and 1.1 are versions of the TLS protocol that are no longer
considered secure and have been superseded by more secure and modern
versions (TLS 1.2 and 1.3).
These versions have now been disabled by default. If you encounter
issues, you can, at your own risk, re-enable the versions by removing
"TLSv1" and/or "TLSv1.1" from the `jdk.tls.disabledAlgorithms`
security property in the `java.security` configuration file.
https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2021-April/005860.html
```
