### ISSUE TITLE
[Bug] Table doesn't load/display data consistently on page load

### ISSUE THREAD

**Issue by akshayrangasaid** [appsmithorg/appsmith#2575] opened 2021-01-14 06:12 UTC
## Description

Table widget that displays data based on a few inputs doesn't load when a page is entered. When I reset the inputs or change them, the widget loads normally.

[What happened]

When I enter a new page, some of the table widgets do not load/display data, when I change inputs on the page, which the table is linked, the table displays the data consistently. 

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to Jarvis - App Stats Page
2. Click on Date Dropdown and change the date
3. Change the date back to the default date
4. See dead apps update, which hadn't during initial load

Link to video: https://share.vidyard.com/watch/edN7ENPNymrDCtaRjxk36p

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser:  Edge

**Comment by Nikhil-Nandagopal** [comment] 2021-01-14 06:19
@akshay11298 thanks for reporting this. This is a duplicate of the issue mentioned here #2562 so I'm closing it in favor of that

**Closed by Nikhil-Nandagopal** 2021-01-14 06:19 UTC
Labels: Bug, Needs Triaging
