### ISSUE TITLE
[Bug]: Focus state visible upon checking/unchecking the box

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#27921] opened 2023-10-10 11:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/6636360/a56d6da0-e75f-4f38-9a0b-f4c8a527e66b)

Focus styles are visible upon checking/unchecking the checkbox.

### Steps To Reproduce

1. Drop the new wds checkbox widget.
2. Click on the checkbox 2-3 times. You will see the focus stylesWDS

### Environment

Production

### Version

latest

**Comment by KelvinOm** [comment] 2024-03-27 09:45
Duplicate of #27677

**Closed by KelvinOm** 2024-03-27 09:45 UTC
Labels: Bug, Low, Production, Needs Triaging, Anvil POD, WDS team
