### ISSUE TITLE
[Epic] Improved Deployments

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4430] opened 2021-05-11 11:27 UTC
# Objective
Simplify the following modes of deployment
- Docker
- K8s
- Heroku
- AWS

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| ------------- | ------------- |
| Improved Installation Funnel | 95% | 
| Better Telemetry Capture Rate | 50% |

# Requirements
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Docker | The user should be able to deploy appsmith with a single docker command on any OS. The container is rebuilt whenever a change to the frontend or backend occurs | High |  |
| Docker | The user should be able to bring up appsmith with a docker-compose file/run command | High |  |
| K8s | The user should be able to deploy on Kubernetes with a helm chart. We should have a public chart repo for appsmith with the default release | High | |
| AWS | The user should be able to deploy on AWS with a single click using the AWS stack | High | |
| Heroku | The user should be able to deploy on Heroku with a single click after setting up mongo with no additional configuration required | High | |
| UI Config | The user can configure all environment variables via a UI. | High | |
| SSL | The user should be able to install SSL via a single CLI command for all modes of deployment | Medium | |
| Logs | The user should be able to view the logs of the container with a simple docker logs command | Medium | |
| Export | The user should be able to easily take a dump of the instance and restore it | Medium | |

## Inspiration
[Metabase](https://www.metabase.com/docs/latest/operations-guide/installing-metabase.html)

# User Story
Users self-hosting appsmith should be welcomed first instead of being thrown onto a login screen. They should proceed to fill in the details of the administrator of the instance.
- Name
- Email
- Password
The Intended Use of appsmith
- Personal / Company
- Company Name
They can choose whether they are deploying appsmith locally or on a cloud server.
Agree to anonymous share usage statistics of their instance.
Subscribe to our newsletter for updates about appsmith
The user is instantly logged in

The user can now update the instance settings from the administrative section.
This section allows users to configure their appsmith instance
- General
  - Instance Name
  - Admin Email
  - Generate Docker Compose File
  - Option to enable / disable anonymous tracking
  - Option to connect a custom domain & SSL
- Email
  - SMTP Host
  - Port
  - SMTP Security - None | SSL | TLS | START TLS 
  - Username
  - Password
  - From Address
  - Links to guides on integrating with Sendgrid / SES
- Version
  - The current version of appsmith
  - The release notes 
- Authentication
  - Form Signup
    - Enable / Disable (default)
  - Google Signup
    -  Client ID
    - Allowed Domains
    - Link to guide to configure
  - Github Signup 
    - Client ID 
    - Link to guide to configure
- Google Maps
  - Google Maps API Key
  - Link to guide to generate API Key

# Developer Handoff Document in Figma
Link to the developer Handoff Document:

**Comment by sharat87** [comment] 2021-06-03 12:11
Can we add monitoring to this? The self-hosted setup could come with an initial monitoring system as well (optionally), that will monitor the server, frontend, mongo etc. in one single place.

**Comment by Debsourabh** [comment] 2021-07-29 05:40
WIP Figma File

https://www.figma.com/file/lqtUfzJO50RpEhxKttYeOg/Local-Dev?node-id=1%3A70

**Comment by Nikhil-Nandagopal** [comment] 2021-08-03 05:42
## New Comment by a user 
embedded mongo db password in docker-compose.yml poor choice.  Should go in an environment file that can be given stricter permissions

**Comment by sharat87** [comment] 2021-08-03 06:13
Opened #6345 for issue from above comment.

**Comment by sharat87** [comment] 2021-08-06 11:34
## Admin Configuration Fields

| Display Name                  | Type          | Internal Name                   | Detail                                                                                                                                          |
| ----------------------------- | ------------- | ------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| MongoDB URI                   | Text          | APPSMITH_MONGODB_URI            | The URI to a MongoDB server, that will be used as the database.                                                                                 |
| Redis URI                     | Text          | APPSMITH_REDIS_URL              | The URI to a Redis server, that will be used for storing sessions and other ephemeral information.                                              |
| Enable Email                  | Boolean       | APPSMITH_MAIL_ENABLED           | If true, email is enabled, and needs to be configured, using the other fields here. If false, Appsmith server won't be able to send any emails. |
| Email: From Address           | Email Address | APPSMITH_MAIL_FROM              | The email address to use as the from address when sending emails.                                                                               |
| Email: Reply To               | Email Address | APPSMITH_REPLY_TO               | The email address to use for the Reply-To header for emails sent by Appsmith.                                                                   |
| Email: SMTP Host              | Text          | APPSMITH_MAIL_HOST              | The host address of the SMTP server to use.                                                                                                     |
| Email: SMTP Port              | Number        | APPSMITH_MAIL_PORT              | The port of the SMTP server to use.                                                                                                             |
| Email: SMTP Authentication    | Boolean       | APPSMITH_MAIL_SMTP_AUTH         | Enable authentication, when talking to the SMTP server.                                                                                         |
| Email: SMTP Username          | Text          | APPSMITH_MAIL_USERNAME          | Username to use for authenticating with the SMTP server, if authentication is enabled.                                                          |
| Email: SMTP Password          | Text          | APPSMITH_MAIL_PASSWORD          | Password to use for authenticating with SMTP server.                                                                                            |
| Email: Enable TLS for SMTP    | Boolean       | APPSMITH_MAIL_SMTP_TLS_ENABLED  | Whether to use TLS when authenticating with SMTP server, if authentication is enabled.                                                          |
| Signup: Disable               | Boolean       | APPSMITH_SIGNUP_DISABLED        | If true, signing up on this Appsmith instance will not be allowed.                                                                              |
| Signup: Allowed Email Domains | Boolean       | APPSMITH_SIGNUP_ALLOWED_DOMAINS | When set to a comma separated list of domains, only emails with these domains will be allowed to signup.                                        |
| Google ReCaptcha Site Key     | Text          | APPSMITH_RECAPTCHA_SITE_KEY     | Provide ReCaptcha Site key here, if you wish to use it for the signup page.                                                                     |
| Google ReCaptcha Secret       | Text          | APPSMITH_RECAPTCHA_SECRET_KEY   | Provide ReCaptcha Secret key here, if you wish to use it for the signup page.                                                                   |

**Comment by sharat87** [comment] 2021-09-06 06:50
@Nikhil-Nandagopal, regarding the item **Generate Docker Compose File**, instead of generating just a docker-compose.yml file and having that download, should we give a zip with the docker-compose.yml file and the docker.env file, with the current env variables? The docker-compose.yml file would have a reference to this `docker.env` file, so I'm guessing just the yml file wouldn't be of much use.

Additionally, if the idea of providing this is to be able to export the whole environment in one click, to reproduce elsewhere, shouldn't it include the database dumps as well?

**Comment by sharat87** [comment] 2021-09-06 06:52
> Currently when deploying using k8s, there is no health probe. Sometimes connection to mongo or redis may end, but since no health route exists, there is no way for the pod to be restarted.

Hey @heroic, you mean a health endpoint on the backend server, right? One option is to use `/api/v1/users/me`, and confirm it responds with 200 status code, and perhaps that the JSON body contains `anonymousUser`.

Let me know if I misunderstood your question.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-06 06:58
@sharat87 the zip sounds good. The idea for this was quick replication for the DB admin. I think with git sync the need for a DB dump will go away. Only the users will need to be re-added which should be fine once we create domain wide sign ups & invite links

**Comment by heroic** [comment] 2021-09-06 13:45
> > Currently when deploying using k8s, there is no health probe. Sometimes connection to mongo or redis may end, but since no health route exists, there is no way for the pod to be restarted.
> 
> Hey @heroic, you mean a health endpoint on the backend server, right? One option is to use `/api/v1/users/me`, and confirm it responds with 200 status code, and perhaps that the JSON body contains `anonymousUser`.
> 
> Let me know if I misunderstood your question.

Yes. I ended up using /applications

**Comment by sharat87** [comment] 2021-09-07 14:16
@sbalaji1192, here's the variable names for some of the configs:

- Authentication
  - Form Signup
    - Enable / Disable (default) (`APPSMITH_SIGNUP_DISABLED`)
  - Google Signup
    -  Client ID (`APPSMITH_OAUTH2_GOOGLE_CLIENT_ID`)
    - Allowed Domains (`APPSMITH_SIGNUP_ALLOWED_DOMAINS`)
    - Client Secret (`APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET`) 🆕
    - Link to guide to configure
  - Github Signup 
    - Client ID (`APPSMITH_OAUTH2_GITHUB_CLIENT_ID`)
    - Link to guide to configure (`APPSMITH_OAUTH2_GITHUB_CLIENT_SECRET`)
- Google Maps
  - Google Maps API Key (`APPSMITH_GOOGLE_MAPS_API_KEY`)
  - Link to guide to generate API Key

**Comment by DiptoChakrabarty** [comment] 2021-09-26 19:13
> > Currently when deploying using k8s, there is no health probe. Sometimes connection to mongo or redis may end, but since no health route exists, there is no way for the pod to be restarted.
> 
> Hey @heroic, you mean a health endpoint on the backend server, right? One option is to use `/api/v1/users/me`, and confirm it responds with 200 status code, and perhaps that the JSON body contains `anonymousUser`.
> 
> Let me know if I misunderstood your question.

Can I add this liveness probe in the backend deployment file. My plan is to setup a http request probe to the /api/v1/users/me path with a period of 5 seconds.

**Comment by mohanarpit** [comment] 2021-09-27 04:11
> > > Currently when deploying using k8s, there is no health probe. Sometimes connection to mongo or redis may end, but since no health route exists, there is no way for the pod to be restarted.
> > 
> > 
> > Hey @heroic, you mean a health endpoint on the backend server, right? One option is to use `/api/v1/users/me`, and confirm it responds with 200 status code, and perhaps that the JSON body contains `anonymousUser`.
> > Let me know if I misunderstood your question.
> 
> Hey ,can I send a PR to add this liveness probe in the backend deployment file. My plan is to setup a http request probe to the /api/v1/users/me path with a period of 5 seconds.

@DiptoChakrabarty Sure. Please go ahead.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-27 06:49
@sharat87 are the same events being fired for when telemetry is opted in / out?

**Comment by jalberto** [comment] 2021-11-08 11:58
Hi, in the latest blog post Helm support has been announced, but I cannot find the docs for it

**Comment by sharat87** [comment] 2021-11-08 12:10
Hey @jalberto, you can checkout https://github.com/appsmithorg/appsmith/tree/release/deploy/helm where we have some documentation for this. We are working on including this in our official docs.appsmith.com soon. Thanks!

**Comment by sharat87** [comment] 2021-11-26 02:45
Action Items:
@sharat87 -- Review and merge helm charts, infra compliance changes.
@sub1983 -- Work with GeekUP for IaC changes.

**Comment by hiteshjoshi** [comment] 2022-03-10 05:26
Closing this.

**Closed by hiteshjoshi** 2022-03-10 05:26 UTC
Labels: Enhancement, Deployment, Platform Pod, Epic, New Developers Pod

**Comment by Nikhil-Nandagopal** [comment] 2022-03-10 06:07
@hiteshjoshi I still see 10 open issues in the epic. What are we doing about those?

**Comment by hiteshjoshi** [comment] 2022-03-10 06:13
@Nikhil-Nandagopal They will still be open, the problem is DevOps is being tracked on Notion + EE repo due to a lot of restrictions. We will close them but the priority have changed a bit for some of the open issues.
