### ISSUE TITLE
[Bug]-[450]:Table header UI issues

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#12239] opened 2022-03-24 20:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When I remove all the Heading options and the table's toolbar is removed, the table header text is not vertically center-aligned anymore.
2. When I right or center-align text in the table, the text inside the table's header doesn't follow that and is always left-aligned.
3. Multi-row selection is also not aligned (the one in heading) - https://github.com/appsmithorg/appsmith/issues/12615

![Screenshot 2022-03-24 at 21 33 07](https://user-images.githubusercontent.com/81744497/160005768-df5fb86b-39e9-4134-b1aa-e414a30949a2.png)
![Screenshot 2022-03-30 at 15 54 38](https://user-images.githubusercontent.com/81744497/160851442-64358dd2-754e-4399-9c6d-316e7e5699e9.png)

### Steps To Reproduce

1. Remove all the header options from the toolbar (pagination, search, download and filter)
2. Right align the text in the table.,
3. Enable multi-row selection

### Version

Cloud

**Comment by somangshu** [comment] 2022-04-01 11:19
@momcilo-appsmith thanks, that seems to be a regression. We might need to treat them separately, One is an enhancement while another is a bug

**Comment by dilippitchika** [comment] 2022-04-28 05:06
Last one being tracked here - https://github.com/appsmithorg/appsmith/issues/12615

**Comment by dilippitchika** [comment] 2022-04-28 05:10
Reach : People who have set the header to be center or right. 
Considering only for 2nd issue in this list.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 450 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment] 2022-05-17 12:17
@sbalaji1192 to check this once

**Comment by dilippitchika** [comment] 2022-08-18 07:16
Closing this as it's not reproducible anymore in v2

**Closed by dilippitchika** 2022-08-18 07:16 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low
