### ISSUE TITLE
[Bug]: Table Row Frontend Desync with other Components

### ISSUE THREAD

**Issue by mw-risRX** [appsmithorg/appsmith#35641] opened 2024-08-12 17:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Users click a row, the information that populates forms/other components on the same page displays information from a different row. The users sometimes do not recognize this until they submit the 'forms' and realize the incorrect row has been updated with the desync'd information. Users essentially end up updating the wrong row , their "Selected Row" is not always accurate.
We tried fixing code-wise/putting safety nets and found that when calling [tableComponent].selectedRow it would be reflecting the information that is shown on the forms, and no record of the 'selectedRow' thats visually highlighted when onClick. So code wouldn't see what user was seeing.

### Steps To Reproduce

1. Navigate to our home 'page'
2. spam click between a few rows
3. the forms/components below are supposed to sync with the rows

// we had a video demonstrating but let us know if you can reach out we can provide a secure video

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Appsmith Community v1.28

**Comment by dc-risrx** [comment] 2024-08-12 18:00
Hello,

We've been talking with appsmith support (jimmy@appsmith.com) about this issue and were told to create a bug report as they were unable to reproduce the error on their side. 

For additional detail, this issue has persisted across multiple versions for us so we're not sure if just updating our version will help

Looking forward to hearing back, thank you!

**Comment by rishabhrathod01** [comment] 2024-08-13 16:26
@dc-risrx we would like to have a debugging session for this. Could you schedule a call according to your availability using https://calendly.com/rishabh-rathod

**Comment by dc-risrx** [comment] 2024-08-13 16:39
Hello @rishabhrathod01 sounds good just scheduled for this Friday at 8AM PST, looking forward to meeting thank you very much!

**Comment by rishabhrathod01** [comment] 2024-08-13 19:45
Hey @dc-risrx, Pardon for a miss from my side. Friday was supposed to be marked as OOO on my calendar but wasn’t updated, i have done that now. I request you to reschedule the meeting using [https://calendly.com/reschedulings/0ef5c3de-185a-424f-8d1e-2862321c1526](https://www.google.com/url?q=https://calendly.com/reschedulings/0ef5c3de-185a-424f-8d1e-2862321c1526&sa=D&source=calendar&ust=1724010306500717&usg=AOvVaw2hQtivZdAAmh8BfBhnLJ81), Thanks.

**Comment by dc-risrx** [comment] 2024-08-13 19:57
no worries @rishabhrathod01 just rescheduled!

**Comment by dc-risrx** [comment] 2024-08-21 17:54
hello @rishabhrathod01 apologies, not sure if you saw my email this morning and I just saw the calendly options to reschedule or cancel but I'm unable to access those links for some reason

we were having some emergencies with one of our systems this morning so so sorry again that we had to miss, would you be able to resend a calendly invitation please so that we can reschedule

**Comment by rishabhrathod01** [comment] 2024-08-21 20:04
@dc-risrx No worries, you could schedule a new call using [calendly.com/rishabh-rathod](https://calendly.com/rishabh-rathod)

**Comment by dc-risrx** [comment] 2024-08-21 20:32
thank you so much, just sent it

apologies again!

**Comment by rishabhrathod01** [comment] 2024-08-26 10:35
@dc-risrx we expected to receive an email with the details but haven't yet received one. Also, do add rishabh.rathod@appsmith.com to the email with support@appsmith.com. Thanks

**Comment by dc-risrx** [comment] 2024-08-26 15:48
hello @rishabhrathod01, apologies took us longer to get this out than we wanted but just sent it over! please let us know if there's any issues, thank you!

**Comment by rishabhrathod01** [comment] 2024-08-29 10:24
@dc-risrx The application JSON and the data schema didn't help us reproduce the issue. We will need to analyze the application further and would request to schedule a call for the same. Could you please use this link to schedule a call again [calendly.com/rishabh-rathod](https://calendly.com/rishabh-rathod)

**Comment by rohan-arthur** [comment] 2024-09-09 09:23
this should still be treated as a critical issue - we are working on another critical issue( #35523 ) before coming to this

**Comment by rishabhrathod01** [comment] 2024-09-13 01:09
@dc-risrx We created the query to trigger onRowSelection but unfortunately, this issue is not yet reproducible on our side. We noticed an `await` used in the binding of `onRowSelection`. That `await` could be skipped. We will keep updating here with more information.

**Comment by rishabhrathod01** [comment] 2024-09-13 11:30
@dc-risrx After further analysis, we confirmed that it is an old bug that got fixed with this PR https://github.com/appsmithorg/appsmith/pull/34106 and is available in version 1.29. We would suggest you to please upgrade to get the fix. I will be closing the issue for now. Please reopen if it is still reproducible. Thanks for your patience.

**Closed by rishabhrathod01** 2024-09-13 11:30 UTC
Labels: Bug, JS Evaluation, Critical, Production, Community Reported, Needs Triaging, Javascript Product, Query & JS Pod
