### ISSUE TITLE
[Bug]: The table displays one more row than the amount needed to fill the space

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#24770] opened 2023-06-23 03:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table displays one more additional row when the table is sized to the exact number of rows.

Observe the below video at 0:11 second:
https://www.loom.com/share/4f724ddd239040a7ae30498e2623553b?sid=0997eb83-e4f8-43c2-8d2a-4f81d1ad2318

### Steps To Reproduce

1. Dnd a table widget
2. Adjust the height of the table such that it contains exact number of rows.
3. Observe that we still have additional row once scrolled down

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2023-06-23 03:43
Duplicate of https://github.com/appsmithorg/appsmith/issues/17857

**Closed by dilippitchika** 2023-06-23 03:43 UTC
Labels: Bug, Table Widget, App Viewers Pod, Needs Triaging
