### ISSUE TITLE
[Bug]: getIdToken returns null

### ISSUE THREAD

**Issue by fungiboletus** [appsmithorg/appsmith#15040] opened 2022-07-06 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`getIdToken` returns null.

See https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java#L136-L139

### Steps To Reproduce

1. Install AppSmith and configure it with Google Authentication
2. Try to load `{{appsmith.user.idToken}}`
3: It's empty

### Version

latest on github

**Comment by Nikhil-Nandagopal** [comment] 2022-07-18 12:14
@fungiboletus it seems to be working for me. Could you share a video with this issue?

**Comment by fungiboletus** [comment] 2022-07-18 12:36
I could if necessary, but are you sure you tested on the version from this repository?

**Comment by Nikhil-Nandagopal** [comment] 2022-07-18 12:49
I tested it on our cloud and release environments which are the latest code deployments from the main appsmith repo. Are you able to reproduce this on https://app.appsmith.com?

**Comment by trishaanand** [comment] 2023-03-03 07:16
Not reproducible. Closing this.

**Closed by trishaanand** 2023-03-03 07:16 UTC
Labels: Bug, Cannot Reproduce Issue, Needs Triaging, Team Managers Pod, SSO
