### ISSUE TITLE
[Bug]: Dragging table column cards doesn't scroll up/down the property pane

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10561] opened 2022-01-22 09:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have a lot of columns, I can't scroll up/down the property pane while dragging the table column cards.

### Steps To Reproduce

1. Drag a table on your canvas
2. Create 10 columns
3. Try to scroll up while dragging one of the cards.

Loom recording:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/56e8895420214b01a7620614420a7ed0-00001.gif)](https://www.loom.com/share/56e8895420214b01a7620614420a7ed0)

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment] 2022-01-22 11:20
Related to #8623

**Comment by somangshu** [comment] 2022-01-25 06:31
This is duplicate of #4266

**Closed by somangshu** 2022-01-25 06:31 UTC
Labels: Bug, Table Widget, Property Pane, App Viewers Pod, UI Building Pod, Needs Triaging, UI Builders Pod
