### ISSUE TITLE
[Bug]: Evaluation loop when facing cyclic dependency issue

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9181] opened 2021-11-16 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2b40f90ba9b742278e3445cdaf670a27-00001.gif)](https://www.loom.com/share/2b40f90ba9b742278e3445cdaf670a27)

### Steps To Reproduce

No steps to reproduce yet.
### Environment

Release

### Version

Cloud

**Comment by hetunandu** [comment] 2021-12-07 08:33
Not able to reproduce this issue

**Comment by rohan-arthur** [comment] 2021-12-10 06:31
got one - open my org "Rohan - For Issues", and duplicate then edit "Spotify Recommendations"
1. Select list widget "SearchResults", cmd+C
2. Scroll down to empty area, cmd+v
3. see the cyclic dependency error

https://user-images.githubusercontent.com/94514895/145528133-9500753b-d802-4756-a049-e2d2986add41.mov

**Comment by ohansFavour** [comment] 2022-02-16 10:40
Hey @rohan-arthur , kindly check this out

**Comment by rohan-arthur** [comment] 2022-02-16 11:00
@ohansFavour I don't get the flickering anymore, but still get the cyclic dependency error - request you to make a copy of [my app](https://app.appsmith.com/applications/61b2f3a5d3e4214454c26996/pages/61b2f3a5d3e4214454c2699a/edit) and try out the steps again.

1. enter something in the search that will get positive results, e.g., "Michael Jackson"
2. Select the list and copy
3. scroll down to some empty area and paste
---> you'll see the cyclic dependency error

**Comment by ohansFavour** [comment] 2022-04-10 20:38
Hey @rohan-arthur , tried these exact same steps and did not get any cyclic dependency. Closing this for now.

**Closed by ohansFavour** 2022-04-10 20:38 UTC
Labels: Bug, Actions Pod, JS, High, Needs Triaging, FE Coders Pod
