### ISSUE TITLE
[Bug] JS Editor Selection and Line Wrapping Problems

### ISSUE THREAD

**Issue by daemons2000** [appsmithorg/appsmith#7558] opened 2021-09-17 04:47 UTC
From Discord:
A bit strange selection behavior. See the gif. I'm on Windows. First I press Ctrl+A 3 time. See how the selection does not cover the entire text. Then I double click a word. See how not the word is selected but some unrelated text fragment.
![bugJsEditorSelection](https://user-images.githubusercontent.com/1758467/133725788-36cd7704-7755-461a-9b6a-66139b7ddd5b.gif)

Somangshu suggested: #6043 

I replied:
It's only a symptom. The core reason is I think is how you do line wrapping. See how the same code snippet looks like when in a regular text editor
![notepad](https://media.discordapp.net/attachments/760761686549463060/887764972799680562/unknown.png?width=400&height=168)

And then I continued:
Yeah, confirmed my hypothesis. See the gif. I removed all indent. Now the previous test is running perfectly fine. So it's not a matter of some "limit", it's how the selection range coordinates are calculated.
![bugJsEditorSelectionOk](https://user-images.githubusercontent.com/1758467/133725968-dbf6442f-3cb2-4882-8fe9-d8f1c95b7612.gif)

Somangshu
Can you please drop thia finding on the issue

**Comment by Nikhil-Nandagopal** [comment] 2021-09-17 06:10
@daemons2000 thank you for the detailed issue report!

**Comment by Nikhil-Nandagopal** [comment] 2021-09-17 06:10
@ApekshaBhosale @hetunandu could you'll look into why code mirror is behaving this way?

**Comment by Rishabh-Rathod** [comment] 2021-11-12 06:42
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/7558?planning-poker) with ZenHub @ajinkyakulkarni @ApekshaBhosale @hetunandu @ohansFavour

**Comment by Rishabh-Rathod** [comment] 2021-12-15 12:31
Duplicate of https://github.com/appsmithorg/appsmith/issues/6043

**Comment by Rishabh-Rathod** [comment] 2021-12-15 16:06
@ajinkyakulkarni @somangshu Shall we close this issue as it is the same as #6043 and is not related to JS evaluation?

**Comment by somangshu** [comment] 2021-12-16 06:12
Ideally we could close it, The solution for #6043 should solve this

**Closed** 2021-12-16 09:52 UTC
Labels: Bug, Actions Pod, High, JS Editor, FE Coders Pod
