### ISSUE TITLE
[Bug] Unable to change the tab name from the Entity explorer

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2822] opened 2021-02-02 10:15 UTC
Steps to reproduce :
1) Add Tab Widget into the canvas
2) Add other widget into the Tab widget
3) Now navigate to Entity explorer
4) Change the name of the "Tab" from the Entity explorer
and observer

Observation:
It is observed that the user Name of the tab does not get updated when changed from the entity explorer

Expectation:
It is expected that the entity explorer name must get updated to the widget

![Screenshot 2021-02-02 at 3 39 30 PM](https://user-images.githubusercontent.com/71753653/106585620-86a91280-656d-11eb-83f4-bb429a79b5bf.png)

**Comment by hetunandu** [comment] 2021-02-02 10:43
Duplicate of #2774

**Closed by hetunandu** 2021-02-02 10:43 UTC
Labels: Bug, High, Needs Triaging, Release, Tab Widget, UI Building Pod, Widgets
