### ISSUE TITLE
[Bug]: Refresh token is not being processed correctly 

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10493] opened 2022-01-20 05:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user is reporting that the refresh token is not being processed correctly and therefore they must re-authorize the application on a daily basis.  The application (Infusionsoft Max Classic) doesn't use the offline_access method of OAuth2, so needs some investigation.  

### Steps To Reproduce

Need to get on a call with the user to investigate this issue.

### Environment

Production

### Version

Self-Hosted

**Comment by sumitsum** [comment] 2022-01-26 09:58
I spent some time going through the overall flow and had a discussion with @Nidhi  regarding this earlier today. Our current assessment is that the issue is with the oauth2 refresh token authorization mechanism - our implementation is slightly different from what the authorization server of the user application expects. We send the client credentials in the body of the API request whereas the user's authorization server expects it via header and base64 encoded : https://developer.keap.com/getting-started-oauth-keys/

**Comment by rohan-arthur** [comment] 2022-02-07 11:40
fix is in progress - awaiting review

**Closed** 2022-02-09 04:08 UTC
Labels: Bug, Actions Pod, Critical, community, Needs Triaging, BE Coders Pod
