### ISSUE TITLE
[Bug]: License status shows up as expired, though it has not expired.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28176] opened 2023-10-18 06:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the release-ee instance, the license status shows up as expired, though the license has not expired.

### Steps To Reproduce

1. Login to release-ee instance as an instance admin, and remove the license. 
2. When we relog back in to admin settings, and open up the network console, the **current** response value shows plan as Expired, though the plan has not expired. This is intermittently seen

### Environment

Release

### Version

Cloud

**Comment by abhvsn** [comment] 2023-10-23 16:38
Further reducing the priority as we have added more logs and we are still not able to reproduce the issue.

**Comment by abhvsn** [comment] 2023-10-27 12:34
If we don't observe this in next regression cycle let's close this.

cc: @btsgh @RakshaKShetty

**Comment by abhvsn** [comment] 2023-11-24 10:41
Closing this as we haven't seen for last month.

**Closed by abhvsn** 2023-11-24 10:41 UTC
Labels: Bug, Release, Cannot Reproduce Issue, Needs Triaging, Medium, Billing & Usage Pod, 1-click upgrade
