### ISSUE TITLE
[Bug]: Error deploying appsmith on heroku (Appsmith server is unavailable)

### ISSUE THREAD

**Issue by rodrigo-mahamud** [appsmithorg/appsmith#14802] opened 2022-06-25 00:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have followed all the steps that are indicated in the documentation,
but when i finish the process this message. I have also checked the mongodb data source and i think is all ok. I don't know how to solve this problem.
![Captura de pantalla 2022-06-25 023847](https://user-images.githubusercontent.com/76396937/175751434-1d58ff21-1611-4ff2-98ca-c8d6c3dc6e5b.jpg)
![Captura de pantalla 2022-06-25 024045](https://user-images.githubusercontent.com/76396937/175751438-5653da4e-e3fd-4322-8d5a-550bf3cd8d40.jpg)
![Captura de pantalla 2022-06-25 024303](https://user-images.githubusercontent.com/76396937/175751497-7f451827-602c-445a-b8c4-c38ee1244374.jpg)

### Steps To Reproduce

1. Go to Heroku setup in de documentation.
2. Setup Appsmith in Heroku.
3. Open the app.

### Public Sample App

https://rwh-2022.herokuapp.com/

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-06-27 09:44
Hello, this seems to be a duplicate of #14808

**Closed by Nikhil-Nandagopal** 2022-06-27 09:44 UTC
Labels: Bug, Needs Triaging
