### ISSUE TITLE
[Bug] Enhancement: Deleting the application user must be displayed with confirmation message

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1048] opened 2020-10-06 17:30 UTC
https://www.notion.so/Enhancement-Deleting-the-application-user-must-be-displayed-with-confirmation-message-4b8ba7a1b1b14e7cb00065dcaa883c05

**Comment by mohanarpit** [comment] 2020-10-06 18:29
Duplicate of #961

**Closed** 2020-10-15 09:48 UTC
Labels: Enhancement, Low, QA, Release

**Comment by prapullac** [comment] 2020-10-22 07:05
Verified the issue and confirmation message is added into the action icon
