### ISSUE TITLE
[Bug]: Chart widget doesn't load when data is undefined or in some special cases

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15467] opened 2022-07-26 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When data is undefined OR when using custom charts and changing pages, the charts don't load.

Based on a client call:

- When chart widget goes to undefined state and there are linked charts. If no default data is provided the all the charts stop working.
- When we encounter this state we see the "node" undefined error, which is essentially stopping fusion charts in some way.

Based on another client discussion Amelia had 
https://theappsmith.slack.com/archives/C0341RERY4R/p1658851581396239?thread_ts=1658846793.951819&cid=C0341RERY4R

### Steps To Reproduce

Check the slack thread -https://theappsmith.slack.com/archives/C0341RERY4R/p1658846793951819

We are still trying to find the best way to reproduce

### Version

Production (self-hosted)

**Comment by unknown1337** [comment] 2022-07-26 20:34
Thanks for filing!

**Comment by dilippitchika** [comment] 2022-07-27 05:08
@unknown1337 is this happening for you as well? Can you please give us steps to reproduce?

**Comment by dilippitchika** [comment] 2022-07-27 05:36
Notes from @Rishabh-Rathod -

Action item here would be that whenever a fusion chart component crashes

- In our widget error handler for chart widget we need to show error related to unexpected data format was not received and also throw that error in console.
- re-initialise the chart component on crash so that chart widget in other places still works.
This issue is mostly around data supplied to chart and not related to evaluation as far as i understand it.

**Comment by Rishabh-Rathod** [comment] 2022-07-27 08:40
As this issue is mainly related to chart widget and what config data is provided to it. 
I am removing my assignment to avoid confusion here.

cc: @somangshu @jsartisan

**Comment by jsartisan** [comment] 2022-07-27 10:19
Closing this one as it is a duplicate of #12905.

**Closed by jsartisan** 2022-07-27 10:19 UTC
Labels: Bug, Chart Widget, App Viewers Pod, Critical

**Comment by unknown1337** [comment] 2022-07-28 07:08
Yes, please check the chat attached to the opening post (crated after a conversation with me).

**Comment by somangshu** [comment] 2022-07-28 12:29
@unknown1337 we are tracking this in #12905, please subscribe to get the updates
