### ISSUE TITLE
[Bug]: Postgres migration: An internal server error comes up on trying to login with google sso

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35223] opened 2024-07-26 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On setting up SSO with google authentication, I get an internal server error on trying to login with google sso

### Steps To Reproduce

https://jam.dev/c/da8faa8e-f450-4a8c-be6c-145b440e5202

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted

**Comment by RakshaKShetty** [comment] 2024-07-26 14:45
Same issue with OIDC login
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f9fdb00f-f809-410b-84aa-5ab172660f32">

**Comment by abhvsn** [comment] 2024-08-08 08:15
@RakshaKShetty @btsgh this has been fixed with the updated DP can we verify once.

**Comment by RakshaKShetty** [comment] 2024-08-09 06:41
The issue is fixed

**Closed by RakshaKShetty** 2024-08-09 06:41 UTC
Labels: Bug, QA, High, Needs Triaging, Deploy Preview, PR blocker, QA Pod, Move to Postgres, DB Infrastructure Pod

**Comment by RakshaKShetty** [comment] 2024-08-09 07:01
@abhvsn , @btsgh currently only SAML has a issue with Local and we are not able to login, lets try this scenario in DP. Same issue exists in release .
[backend-58dcc31ac393.log](https://github.com/user-attachments/files/16557287/backend-58dcc31ac393.log)
