### ISSUE TITLE
[Bug]-[688]: JS code on text style does not clear when user turns off the JS mode on text widget causing unexpected behaviour

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6797] opened 2021-08-23 14:05 UTC
## Description
When JS code on text style is input with an incorrect code and JS toggle is turned off, then the error still stays on debugger and turning on text style via buttons (**bold, italics**) only adds to the existing JS incorrect JS code.

### Steps to reproduce the behaviour:
1. Add text widget on to canvas and turn on JS code for text colour
2. Input a code such that an error appears on the debugger
3. Now turn off the JS code and use bold/italics buttons to define text style - observe the JS error still present on the debugger and any bold/italics value being added to the invalid JS code
4. toggle back on to JS code and observe that the code was not cleared and selected bold/italics are added to the code

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9e173c960b3d4f01a65a38ffbcb93503-00001.gif)](https://www.loom.com/share/9e173c960b3d4f01a65a38ffbcb93503)

**Comment by somangshu** [comment] 2021-08-23 14:13
Here, the JS evaluated value is trying to persist between modes. I think this is intended.

@hetunandu can you clarify?

**Comment by ramsaptami** [comment] 2021-08-23 14:40
Another thing that's observed is that once JS code is added with keywords **bold/italics**, then clicking on either Bold or Italics buttons changes text style but does not alter selected buttons. (even though the video is recorded on DP, the behaviour observed on release as well)

https://www.loom.com/share/871584c8d0984eebaee1f8117f795ea1

**Comment by hetunandu** [comment] 2021-11-19 06:32
> Here, the JS evaluated value is trying to persist between modes. I think this is intended.
> 
> @hetunandu can you clarify?

@somangshu When switching back from 'js' mode, the value should reset and no longer be dynamic.

https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/WidgetOperationSagas.tsx#L274-L283

Looks like the validation does not parse this value correctly.

**Comment by vuiets** [comment] 2022-04-25 05:32
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 86 |
| Effort (months)  | 0.25 |

**Comment by aswathkk** [comment] 2022-06-17 03:21
We've disabled the JS toggle button unless a proper value is passed to the code. (merged to release)
This issue can't be reproduced anymore.

**Closed by aswathkk** 2022-06-17 03:21 UTC
Labels: Bug, Property Pane, App Viewers Pod, High, UI Building Pod, UI Builders Pod, Widget Property
