### ISSUE TITLE
[Docs]: Custom Authentication Rehaul

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#20748] opened 2023-02-17 12:20 UTC
https://docs.appsmith.com/advanced-concepts/how-to-implement-custom-authentication-on-appsmith

**Comment by danciaclara** [comment] 2023-02-17 12:52
Duplicate of https://github.com/appsmithorg/appsmith-docs/issues/879

**Closed by danciaclara** 2023-02-17 12:52 UTC
Labels: Documentation, User Education Pod
