### ISSUE TITLE
[Bug]: Creating a new query from an API datasourcee crashes the app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12556] opened 2022-04-04 13:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new query from an API datasource causes the app to crash

### Steps To Reproduce

1. Create an API query from either datasources page or from omnibar and observe the app crash

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/95173840f9b74148a43795c2b2928709-00001.gif)](https://www.loom.com/share/95173840f9b74148a43795c2b2928709)

### Version

Cloud

**Comment by sumitsum** [comment] 2022-04-06 02:31
(1) The issue with creating a new REST API query is not reproducible any more. Checked with Saptami with this as well. 
(2) The issue with creating a new REST API query from imported datasources is because of datasource config being missing. 
Re-assigning this to @AmanAgarwal041 for further investigation.

**Closed** 2022-04-07 07:15 UTC
Labels: Bug, Datasources, Actions Pod, Critical, Release, Query Editor, Needs Triaging, Release Blocker, BE Coders Pod
