### ISSUE TITLE
[Bug]When the user switches between the MySql query pane to Mongo Query Pane the previously selected query pane is retained in the new query pane 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5684] opened 2021-07-08 02:13 UTC
## Description

[What happened] When the user switches between the Mysql query pane to Mongo Query Pane the previously selected query pane is retained in the new query pane

### Steps to reproduce the behaviour:

https://drive.google.com/file/d/1dEtFbOf9_awBRAXWhVSk2Z4eC4PTgibb/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by pranavkanade** [comment] 2021-07-08 04:49
duplicate of #5676

**Closed by pranavkanade** 2021-07-08 04:49 UTC
Labels: Actions Pod, Bug, Needs Triaging, Query Editor
