### ISSUE TITLE
[Bug]: Erratic behaviour with missing pluginId for the actions created by JSObjects

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#11927] opened 2022-03-17 06:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some users have reported that their app is crashing, after investigating this resulted in the missing `pluginType` and `pluginId` for the actions connected to the JSObejct. This happens with all the actions attached to the JSObject which is at fault but if we look into the DB, JSObject looks fine with `pluginType` and `pluginId` is also available.

### Steps To Reproduce

-

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-03-17 07:01
@abhvsn this should be critical since we're broken existing apps right?

**Comment by abhvsn** [comment] 2022-03-23 12:02
Discussion with the user who faced this issue: https://discord.com/channels/725602949748752515/953870548868431872

**Comment by abhvsn** [comment] 2022-04-05 12:41
@ajinkyakulkarni this is not related to `Git Version Control` feature, we have seen this happening to the applications which are not connected to git as well. 
@Rishabh-Rathod this is not reproducible but we have seen this happening

**Comment by Rishabh-Rathod** [comment] 2022-04-06 06:42
@abhvsn Can you add more details to the issue? 

#### 1. What did we notice?
#### 2. Where could the problem be?
#### 3. Which pod might be responsible for this?

Initially, it was tagged to FE coders pod which for now handles only the frontend side of JS Editor, but it seems the issue lies in the backend.

**Comment by rohan-arthur** [comment] 2022-04-06 14:13
Pranav helped with an example app where this is reproducible.
1. notice that there are duplicate named JS Objects
2. try to edit one of the js objects --> see internal server error

[app link](https://app.appsmith.com/applications/620dafe36b4b1e154a3c4946/pages/620dafe36b4b1e154a3c494b/edit/jsObjects/620dafe36b4b1e154a3c49a2?branch=revamp)

**Comment by abhvsn** [comment] 2022-04-06 15:54
@rohan-arthur that was a different issue we are tracking this in #12000, but for the current issue we saw the application was crashing. @ApekshaBhosale and @AnaghHegde have observed this issue in their apps previously

**Comment by eco-monk** [comment] 2022-04-11 05:30
We don't have any active apps to reproduce this issue.
Nor any steps to bring an app to the state where this error occurs.

We can manipulate the DB manually to reproduce this though.
`Create a JS Object and remove the plugin Info from DB manually, then notice that when you load the app, client makes a PUT call and the call fails with internal server error`

**Comment by Rishabh-Rathod** [comment] 2022-04-11 07:10
> We don't have any active apps to reproduce this issue. Nor any steps to bring an app to the state where this error occurs.
> 
> It's discussed that we can manipulate the DB manually to reproduce this though. Trying this now. `Create a JS Object and remove the plugin Info from DB manually, then notice that when you load the app, client makes a PUT call and the call fails with internal server error`

Does it mean issue got created due to bug in backend which is now resolved? 
If that is the case then ideally shouldn't that be the root cause and we should close this issue with backend bug fix?
cc: @abhvsn  @eco-monk

**Comment by Rishabh-Rathod** [comment] 2022-04-11 11:15
Frontend needs to gracefully handle this error and should not crash users app and ideally, this should never happen from backend.

**Comment by abhvsn** [comment] 2022-04-12 05:35
This needs to be handled from the backend which we are not able to reproduce at the moment. @ApekshaBhosale mentioned we are seeing more and more instances of this not sure if this is reproducible though. 

cc: @nidhi-nair @sumitsum

**Comment by Rishabh-Rathod** [comment] 2022-04-12 10:02
Today, i was able to reproduced issue of JSObject duplication in my application without git feature.

App link - https://release.app.appsmith.com/applications/62444de2c48ad30cd5b5eb23/pages/62444de2c48ad30cd5b5eb2a 

What i noticed was, first i lost my JS object named `JSobject1` and then to fix the function i created new `JSObject1` and that resulted in 2 `JSObject1` entity in the application. 

To reproduce the duplication, I opened release and dev site both pointing to release server. 
Now modified `JSobject1` name to `JSObject2` on release and did same for other JS object but it didn't crash my application when i tried to rename it and get out of duplicate condition.

For user, maybe when multiple user worked on same application we could have faced this.

**Closed** 2022-04-26 11:21 UTC
Labels: Bug, Backend, Critical, Cannot Reproduce Issue, Needs Triaging, BE Coders Pod, Actions Pod
