### ISSUE TITLE
[Bug] Like Header the Params must be made inactive when added from cURL

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5475] opened 2021-06-29 12:35 UTC
Steps to reproduce:
1) Add a cURL cmd
2) Ensure it contains Params
3) Covert it to API
4) Observe params are added 
5) now click on Params Tab
6) observe delete option is displayed to the user

Observation:
Clicking on the delete option it is observed that the params get deleted however when the header is added via curl the headers can not be deleted 

Expectation:
Like Header the Params must be made inactive when added from cURL

**Comment by mohanarpit** [comment] 2021-06-29 13:47
@prapullac I'm unable to reproduce this. Can you share a video? 

I'm asking because I can delete headers & params for APIs that I import via CURL

**Comment by prapullac** [comment] 2021-06-30 04:36
@mohanarpit: Please find the video below
https://www.loom.com/share/6e0f5ac8aa5145e7acc7eee5176fab3d

**Comment by mohanarpit** [comment] 2021-06-30 16:34
@prapullac This is intended behaviour. In the video I can see that you created a datasource from the API. This ends up copying all the headers from the API into the datasource. Since the header is now part of the datasource, you can no longer tamper with it from within the API. This is to ensure that users are able to set headers like Authorization etc safely without worrying about other users changing it or modifying it in any way. 

Closing this issue.

**Closed by mohanarpit** 2021-06-30 16:34 UTC
Labels: API pane, Actions Pod, Bug, Low, Needs Triaging, Release
