### ISSUE TITLE
[Bug]: navigateTo()'s promise resolving before queryParams are updated

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#32348] opened 2024-04-02 16:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

navigateTo() appears to be the only way to update the queryParams on a page.  And if you navigateTo() the current page you are on, the page does not reload it just updates the queryParams.  However, even if you await the navigateTo() the queryParams are not updated when the promise resolves.

Additionally, parameters that are usually responsive to changes (such as default tabs) are unresponsive to changes in queryParams.

### Steps To Reproduce

1. Create a JSObject
2. Create a function:
`test (page, option) {
	console.log("1", appsmith.URL.queryParams.week);
	await navigateTo(page, {week: option});
	console.log("2", appsmith.URL.queryParams.week);
	await some async query that depends on that queryParam;
	console.log("3", appsmith.URL.queryParams.week);
}`
3. Create an async query that depends on the query param
4. Create a button that triggers the test function, with the page parameter bound to the name of the page you are on and the option parameter bound "week 1".
5. Create another button that triggers the test function, with the page parameter bound to the name of the page you are on and the option parameter bound "week 2".
6. Press button 1 and look at the console, press button 2 and look at the console
7. You will see that console log 1 is correctly the old queryParam
8. You will see that console log 3 is correctly the new queryParam
9. You will see that console log 2 is incorrectly still the old queryParam even though navigateTo is awaited

Bonus:
1. Create a tabs widget.
2. Set the default tap to appsmith.URL.queryParams.week
3. Create a tab named week 1, a tab named week 2, and a tab named week 3.
4. Press select the week 3 tab.
5. Press the button that triggers week 1 or week 2, notice the tab does not change.
6. Refresh the page and notice the tab does change.
7. This is not normal behavior for changes to the default tab.  Normally changes to the default tab (such as if it was bound to a jsobject tabs.defaultTab) instantly change the selected tab.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self Hosted - 1.13

**Comment by Nikhil-Nandagopal** [comment] 2024-04-03 12:01
@eedwardsSGS I believe the problem is that the query params should update reactively. This is a duplicate of #26831
console.log will execute after an await because it's a sync statement and will not wait for the promise to resolve unless it's directly using the response of the promise. Closing this in favor of #26831

**Closed by Nikhil-Nandagopal** 2024-04-03 12:01 UTC
Labels: Bug, Production, Community Reported, Needs Triaging, Medium

**Comment by Nikhil-Nandagopal** [comment] 2024-04-09 10:59
@eedwardsSGS this is now fixed in the upcoming release
