### ISSUE TITLE
[Bug] Appsmith cookies don't have an expiration date. 

### ISSUE THREAD

**Issue by vnodecg** [appsmithorg/appsmith#5872] opened 2021-07-15 06:38 UTC
## Description

Appsmith cookies don't have an expiration date. This makes user logout once he ends the browsing session ends.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

<img width="1260" alt="Screen Shot 2021-07-15 at 12 59 58 AM" src="https://user-images.githubusercontent.com/4994565/125740573-a6cd335e-733d-4442-bd87-35ff599f7bdd.png">

### Important Details

- Version: Both self-hosted and cloud
- OS: Mac OSX
- Browser: Chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment] 2021-07-15 06:55
@sharat87 can we pick this up?

**Comment by sharat87** [comment] 2021-07-15 07:20
@Nikhil-Nandagopal I'm not sure this qualifies as a _bug_, unless it doesn't align with how we want our sessions to behave. What is the life of the session cookie we want to be? Personally, I prefer current case of the cookie expiring on closing the browser. This is the default on most webapps IIRC, unless a `Remember Me` checkbox is turned on.

So, is the solution here to add support for a `Remember Me` checkbox on the login page? Do we really want to make the session cookie live indefinitely _by default_?

/cc @mohanarpit

**Comment by Nikhil-Nandagopal** [comment] 2021-07-15 08:11
@sharat87 I think remember me is a different use case to remember the password. But I can't remember the last time I was logged out of an app and had to re-login. Since in the backend we're saying that session is valid for 30 days since last usage, can't we propagate this forward?

**Comment by sharat87** [comment] 2021-07-15 10:21
@Nikhil-Nandagopal I believe it's a little different. The `Remember Me` checkbox that shows up on websites is not about remember the _password_, but to keep the session alive even after closing the browser. Remembering passwords is done by the browser and the app has no control over that.

If we are setting the session life to 30days, I _think_ it shouldn't be deleted on browser close. I'm not sure what's happening there. If this is true, it sounds like a bug then.

Lots of websites I use ask for login every day for me, exceptions I can recall are Google, Twitter etc. Either way, if that's the behavior we want by default, it needs to be implemented then.

**Comment by Nikhil-Nandagopal** [comment] 2021-07-15 12:53
@sharat87 this seems to only be happening to a few people for some reason. Ex. I don't have to login to appsmith everyday on my desktop but on my mobile I do.
@mohanarpit @vnodecg can you shed more light on this?

**Comment by nidhi-nair** [comment] 2021-07-28 04:23
@sharat87 This is indeed reproducible on session close. That's the lifespan associated to the Cookie on the browser, also the default that Spring session assigns. We will need to specify `max-age` in our set up to override this.

**Closed** 2021-07-29 12:43 UTC
Labels: Backend, Bug, Login / Signup, Low, Platform
