### ISSUE TITLE
[Task]: make table name searchable in one click binding

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#28935] opened 2023-11-17 10:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=44a37bbc2e51478284f0e3a63846d0ef&pm=s

**Comment by AmanAgarwal041** [comment] 2023-11-23 10:53
Closing this issue as the issue is already resolved on production. 
Attaching the video : https://www.loom.com/share/d82c3739cb7b47839942417c266d39e8?sid=2d187fbd-d93d-44d6-87ab-9bac4229a78d

**Closed by AmanAgarwal041** 2023-11-23 10:53 UTC
Labels: Task, Integrations Pod, Activation - datasources
