### ISSUE TITLE
[Bug]: All the pages of the templates are not displayed on page selection page of the template

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#17382] opened 2022-10-07 08:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to add any page from the template then on page selection screen all the pages from the templates are not displayed.

https://www.loom.com/share/8574699257f940b0b80b1cfb04fae008

### Steps To Reproduce

1. Click on + on left pane of Pages
2. Select Add Page from Template option
3. Select Customer Support Dashboard template
4. On Templates page listing page see the total no of pages displayed
5. Now click on **BACK TO TEMPLATES** button and navigate back to all the templates page
6. Again select **Customer Support Dashboard** template and fork it
Note : Happening for **Customer Support Dashboard** , **Maintenance Order Management**, 
**Vehicle Maintenance App**, **Applicant Tracker**, **Employee Feedback Form Builder**
7. Observe the total no of pages added now 

### Version

Release

**Comment by akash-codemonk** [comment] 2022-10-17 05:24
Duplicate of https://github.com/appsmithorg/appsmith/issues/15920. Hidden pages are not visible as of now.

**Closed by akash-codemonk** 2022-10-17 05:24 UTC
Labels: Bug, Backend, Low, Needs Triaging, New Developers Pod, Templates
