### ISSUE TITLE
[Bug]: The test email is failing in Admin setting page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9698] opened 2021-12-10 09:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The test email is failing in the Admin setting page 
![image](https://user-images.githubusercontent.com/45958978/145553017-2ae1ccb9-cad9-476e-bda2-30673a7b9b52.png)

### Steps To Reproduce

1. Go to the admin setting page
2. Click on the email tab
3. Add all the related details 
4. Click on send a test email
5. The Test email failed toast bar is displayed 

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by sharat87** [comment] 2021-12-16 18:23
@RakshaKShetty Is this still an issue?

**Comment by sharat87** [comment] 2022-06-30 09:29
@RakshaKShetty, can't reproduce this, so closing. Please reopen if otherwise.

**Closed by sharat87** 2022-06-30 09:29 UTC
Labels: Bug, High, Needs Triaging, Deploy Preview, Super Admin, DevOps Pod
