### ISSUE TITLE
[Bug]: Refactoring widget name when it's the same as a column of a table causes renaming issues

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9018] opened 2021-11-05 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a table column and a widget have the same name then trying to rename widget causes issue with table widget

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ba9c3fde0ee94a0992cd8e8f90483bd9-00001.gif)](https://www.loom.com/share/ba9c3fde0ee94a0992cd8e8f90483bd9)

### Steps To Reproduce

1. Have a widget that has the same name as a table widget
2. Try to rename the widget and observe the error.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment] 2021-11-10 10:37
@hetunandu will need some help here

**Comment by sbalaji1192** [comment] 2022-04-19 13:17
This looks like not related to the Table widget. Most likely caused by the code that changes bindings across all the widgets when a widget gets renamed. Removing the table widget label

**Comment by dilippitchika** [comment] 2022-05-11 11:32
@sbalaji1192 why do you think this is related to property pane?

**Comment by sbalaji1192** [comment] 2022-05-11 11:35
@dilippitchika This issue happens when we change the name from the property Pane on Table widget and button group widget.

**Comment by dilippitchika** [comment] 2022-05-11 11:38
Ok, is there a code that auto updates the bindings? Do you know who looks at that?

**Comment by sbalaji1192** [comment] 2022-05-11 11:59
@dilippitchika Let me have a look and assign it to the appropriate pod.

**Comment by sbalaji1192** [comment] 2022-05-12 05:54
@dilippitchika Looks like the error was thrown from the BE on `api/v1/layouts/refactor`. Not sure who is responsible for this.
@nayan-rafiq Could you have look at this issue?

**Comment by kamakshibhat-appsmith** [comment] 2023-09-14 13:13
cannot reproduce anymore.

**Closed by kamakshibhat-appsmith** 2023-09-14 13:13 UTC
Labels: Bug, Property Pane, High, Production, UI Builders Pod
