### ISSUE TITLE
[Bug]: The searched text background color is white on dropdown of 'change currency/country code'

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#16368] opened 2022-08-29 09:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/e973ceb2855c4b9e905c2041ef72460e

### Steps To Reproduce

1. Drag & Drop Phone/Currency Input widget
2. Enable 'Allow Currency/country change' option from property pane
3. Search for any currency/country in the dropdown
4. Observe that the search text is on clearly visible and background color is white
5. Same issue can be observed in JSON Form currency/Phone type field

### Version

Cloud/ Production

**Comment by dilippitchika** [comment] 2022-09-01 10:40
Duplicate of #16374

**Closed by dilippitchika** 2022-09-01 10:40 UTC
Labels: Bug, App Viewers Pod, High, Needs Triaging, Currency Input Widget, Phone Input Widget
