### ISSUE TITLE
[Feature]: Input page number and go straight there

### ISSUE THREAD

**Issue by wansadi** [appsmithorg/appsmith#33001] opened 2024-04-28 03:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It's frustrating to click 'next-page' for countless times when I need to go to page 100

### Why should this be worked on?

Table's pagination UI won't let me manually input a page number I want to go to. It's frustrating to click 'next-page' for countless times when I need to go to page 100. Is there a feature already available that I'm not aware of? I'm on latest ce btw.

**Comment by wansadi** [comment] 2024-04-28 03:28
My bad, I was referring to the table widget :)

**Comment by Nikhil-Nandagopal** [comment] 2024-04-29 09:02
This is a duplicate of #24973

**Closed by Nikhil-Nandagopal** 2024-04-29 09:02 UTC
Labels: Enhancement
