### ISSUE TITLE
[Bug]: URLs ( containing binding value  ) doesn't work in the "Image field", rather works in the "Default Image field" 

### ISSUE THREAD

**Issue by RoopKrrish9696** [appsmithorg/appsmith#11768] opened 2022-03-10 12:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to use an Image URL that contain binding values for ex `https://images.unsplash.com/photo-{{table.selectedRow.value}}e72b0397e57bixlib=rb1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80` in the Image field section it doesnt work. When I empty that field and use it in the Default image then it works.

### Steps To Reproduce

1. Go to "Image field" section of Image widget
2. Enter the URL with binding value in it `https://images.unsplash.com/photo-{{table.selectedRow.value}}-e72b0397e57b?ixlib=rb1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80g`
3. Image doesnt show up
4. Now remove that URL from that section , empty it
5. Paste that URL in the "Default Image" section
6. It works in this way

### Public Sample App

https://app.appsmith.com/applications/62051a456b4b1e154a398053/pages/62051a456b4b1e154a398056

### Version

Cloud - Appsmith v1.6.14-SNAPSHOT

**Comment by dilippitchika** [comment] 2022-03-11 04:54
@techbhavin can you take a look if this issue is also resolved with the fix you are doing for #11494

**Comment by techbhavin** [comment] 2022-03-11 05:41
Yes, @dilippitchika  this issue is resolved By [#11494](https://github.com/appsmithorg/appsmith/issues/11494)

**Comment by somangshu** [comment] 2022-03-11 12:57
@techbhavin please link the issue

**Closed** 2022-03-16 06:10 UTC
Labels: Bug, Image Widget, App Viewers Pod, High, UI Building Pod

**Comment by btsgh** [comment] 2022-03-23 14:09
Tested and unable to reproduce. Issue is fixed.
<img width="825" alt="Bug11768_Fixed" src="https://user-images.githubusercontent.com/101863839/159718684-0b9d738d-4e23-4c71-af3a-659b3792741a.png">
