### ISSUE TITLE
[Bug]: Getting a 401 error once we refresh or navigate between pages

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19654] opened 2023-01-10 07:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On refreshing any page or visiting a new page, we are getting the below error in release.
<img width="1440" alt="Screenshot 2023-01-10 at 12 16 24 PM" src="https://user-images.githubusercontent.com/39921438/211488087-55472ae2-2320-4729-b4bc-7d7fc3e14d05.png">

**Note:** This also happens when we switch between git branches, load the templates page etc. 

### Steps To Reproduce

1. In release open any app.
2. Refresh the page/navigate to any other page.

### Version

Cloud

**Comment by vivonk** [comment] 2023-01-10 08:25
This issue was caused by a newly introduced web configuration on cloud services. Fix has been applied on release and that should fix it.
Closing this blocker.

**Closed by vivonk** 2023-01-10 08:25 UTC
Labels: Bug, Release, Needs Triaging, Release Blocker
