### ISSUE TITLE
[Bug]: Importing a git app returns an error for incorrect private key

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15091] opened 2022-07-08 12:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After importing an app through git, the initial 2 attempts resulted in seeing the attached error on the org home page. On the third attempt, app was loaded successfully but saw the same error appear after 'application imported successfully' toast was displayed.

This is an intermediate error that pops up maybe 3 out of 5 times.

### Steps To Reproduce

1. Import an app via git a couple of times to observe incorrect private key error (clear cache and try)

https://files.slack.com/files-pri/TGA9SH07N-F03NLQJ2KTQ/image.png
![image](https://user-images.githubusercontent.com/79509062/177989579-a4824ecd-5194-4970-a882-7bdd6f11f460.png)
![image](https://user-images.githubusercontent.com/79509062/177989609-231a8e4c-f642-4b4d-bfd1-2a57d9d2af3c.png)

### Version

Cloud

**Comment by AnaghHegde** [comment] 2023-03-26 17:06
Closing this issue. Feel free to reopen this if you are able to reproduce the issue.

**Closed by AnaghHegde** 2023-03-26 17:06 UTC
Labels: Bug, Release, Needs Triaging, Git Version Control, Import-Export-App, Git Pod

**Comment by ramsaptami** [comment] 2023-03-27 15:00
@AnaghHegde why are we closing this issue? I don't see a PR attached

**Comment by AnaghHegde** [comment] 2023-03-27 16:13
@ramsaptami I am unable to reproduce this error. If this was 3 out of 5 times, we would have noticed this error on CI (cypress tests). Hence closing this. Feel free to reopen the issue if you can reproduce the issue.
