### ISSUE TITLE
[Bug]: Field for input parameters not showing up for JS objects in the property pane

### ISSUE THREAD

**Issue by ayushi-appsmith** [appsmithorg/appsmith#19417] opened 2023-01-02 06:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add parameters to a function in a JS object, I no longer see input fields for the same in the property pane when configuring an action using this function. The syntax has commas to show that params can go there, but this not clear enough. 
We previously had these param fields with labels that can no longer be seen. 

### Steps To Reproduce

1. Create a function with two or more parameters inside a JS object. 
2. Run this function on any event for any widget - example, onClick for Button

### Issue video log

https://www.loom.com/share/caf38857bbdb412aad1ed6b758857fcb

### Version

Cloud v1.8.16

**Comment by ravikp7** [comment] 2023-05-29 07:01
I can't reproduce this issue anymore. @ramsaptami Can you please verify and close this issue?

![Screenshot 2023-05-29 at 12.30.29 PM.png](https://images.zenhubusercontent.com/634fa41f0ccac9aa40f755c2/38206e28-08d6-4b72-8faa-f506ef82df22)

**Closed** 2023-05-31 05:33 UTC
Labels: Bug, FE Coders Pod, JS Usability
