### ISSUE TITLE
[Bug]: Columns disappear from a table if the corresponding fields are not in the source data. That causes the column labels to get forgotten

### ISSUE THREAD

**Issue by m-ocean-it** [appsmithorg/appsmith#21102] opened 2023-03-02 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Create a table
2. Add a JS function as a source of data
3. Set labels for the columns
4. Make the function return rows without a single row containing a specific field
5. See how table deletes the corresponding column
6. Fix the function back, so that it returns the field in question
7. See how the table recreates that column, but doesn't assign the label that I set to it

### Environment

Production

### Version

Cloud

**Comment by m-ocean-it** [comment] 2023-03-02 09:36
I wonder why there isn't an option to prevent this from happening like there is in the JSONForm widget

**Comment by pranavkanade** [comment] 2023-03-02 10:18
@m-ocean-it can you share a public app that can show this behavior? Or share a loom recording for better understanding.

**Comment by m-ocean-it** [comment] 2023-03-02 13:23
Sure! [Here](https://www.loom.com/share/48d46ba0c5dd4457978479ad68350ffd) it is.

I figured, it doesn't have to be a JS function but just any source of data, including manually typed in JSON.

**Comment by dilippitchika** [comment] 2023-03-02 20:07
Duplicate of https://github.com/appsmithorg/appsmith/issues/17152

**Closed** 2023-03-02 20:07 UTC
Labels: Bug, App Viewers Pod, community, Needs Triaging, Table Widget V2
