### ISSUE TITLE
[Feature]: Accordion Widget

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#10516] opened 2022-01-20 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user on discord requested for Accordion widget.

What is the Accordion component? 
an example can be seen here - https://jqueryui.com/accordion/

### Why should this be worked on?

This needs to be triaged

**Comment by Nikhil-Nandagopal** [comment] 2022-01-24 10:17
Duplicate of #2888

**Closed by Nikhil-Nandagopal** 2022-01-24 10:17 UTC
Labels: Enhancement
