### ISSUE TITLE
[Bug]: Vertical border getting misaligned when there is no table data

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#20021] opened 2023-01-24 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I search the table and no search results are found, then re-sizing the column widths causes misalignment in the vertical borders. This also happens when no data is present in the table.

![Screenshot 2023-01-24 at 09 30 44](https://user-images.githubusercontent.com/14138515/214259335-7d76fb07-d1ce-498a-87ba-fb15e58b7c3a.png)

### Steps To Reproduce

1. DnD Table widget
2. Search for something in the search box that is not relevant to the table data.
3. Try to resize the column width
4. Observe

### Version

Cloud

**Comment by somangshu** [comment] 2023-01-24 10:49
@keyurparalkar does this bring any change to the UX?

Also, do you know why this is happening?

**Comment by kamakshibhat-appsmith** [comment] 2023-01-24 11:16
this seems to be duplicate of #18115

**Comment by somangshu** [comment] 2023-01-25 09:41
Closing this issue as its tracked above

**Closed by somangshu** 2023-01-25 09:41 UTC
Labels: Bug, App Viewers Pod, Needs Triaging, Table Widget V2
