### ISSUE TITLE
[Bug] Arango DB : A grey spacing is added on selecting an SSL certificate 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5719] opened 2021-07-08 09:29 UTC
Steps to reproduce:
1) Navigate to datsources
2) Select Aarango DB 
3) Add necessary details
4) Navigate to SSL expand
5) Click on the dropdown 
and observe 

Observation:
It is observed that the grey spacing is added when a user tries to add data from the dropdown

Expectation:
It is expected that the grey spacing must not be displayed  and page must be expanded 
![Screenshot 2021-07-08 at 2 47 09 PM](https://user-images.githubusercontent.com/71753653/124898635-00ea3100-dffd-11eb-93da-3f96773c1cad.png)

**Comment by bfrodsham** [comment] 2021-07-16 23:28
Hello!
I'm new to open source contributions and I'd like to take on this issue. Any tips or recommendations for where to start would be appreciated. Thanks!

**Comment by rishu1601** [comment] 2021-07-19 16:19
Hi,
I would love to contribute to this project and help solve this issue, please assign this to me and let me know on how to get started. Thanks!

**Comment by sumitsum** [comment] 2021-07-20 11:34
@bfrodsham Many thanks for deciding to contribute to Appsmith. I have assigned this issue to you. One of our engineers will help you along the way to design the solution or understand the code or anything else that you might need. I would also suggest you to join the `contributors` channel on our [discord](https://discord.com/invite/rBTTVJp) page for faster communication, as we monitor the discord channels very actively.

**Comment by sumitsum** [comment] 2021-07-20 11:43
> Hi,
> I would love to contribute to this project and help solve this issue, please assign this to me and let me know on how to get started. Thanks!

Hi @rishu1601, I am very grateful that you want to contribute to Appsmith. Since we follow first come first serve policy we had to assign this issue to @bfrodsham for now. In case we don't have any response / activity by the assigned user, we can re-assign the issue to you. However, in the meantime there is plenty of other interesting [issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) that  you may pick from. In case you are still not able to find something, please respond back here or on our [discord](https://discord.com/invite/rBTTVJp) page and we will make sure to find you an interesting issue to crack. Happy hunting :D

**Comment by bfrodsham** [comment] 2021-07-26 19:41
Hey @sumitsum,

I've unassigned myself from the issue because I've been unable to free up time for the issue (I was trying to juggle two issues at once). Apologies for the inconvenience! If @rishu1601 still would like to work on the issue, feel free to pass it on to him. Again, sorry for not passing this on sooner. I hope to contribute to the project soon!

**Comment by sumitsum** [comment] 2021-08-06 11:14
Hi @rishu1601 , would you be interested in picking this issue ?

**Comment by sumitsum** [comment] 2021-08-06 11:15
Hi @rishu1601 , would you be interested in picking this issue ?

**Comment by sumitsum** [comment] 2021-08-06 11:19
> Hey @sumitsum,
> 
> I've unassigned myself from the issue because I've been unable to free up time for the issue (I was trying to juggle two issues at once). Apologies for the inconvenience! If @rishu1601 still would like to work on the issue, feel free to pass it on to him. Again, sorry for not passing this on sooner. I hope to contribute to the project soon!

@bfrodsham no problem at all. Looking forward to your future contributions.

**Comment by rishu1601** [comment] 2021-08-06 12:59
Yes sure

**Comment by sumitsum** [comment] 2021-08-06 13:38
@rishu1601 Great! I am assigning this to you. If possible, please join the contributor's section on our [discord](https://discord.com/invite/rBTTVJp) channel for faster communication, as we monitor the discord channels very actively. It will also allow you to ask questions and get a faster response. You may also post your queries directly on this page as well. Please do reach out to us for any kind of help, whether it is to understand the code or to expedite code review or anything else.

**Comment by sumitsum** [comment] 2021-08-17 15:24
@rishu1601 Were you able to work on this ? Do you require any help on this ?

**Comment by sumitsum** [comment] 2021-08-23 07:56
Hi @rishu1601 , request you to respond to this comment, in case you are still working on this.

**Comment by sumitsum** [comment] 2021-08-30 07:52
Marking this issue as un-assigned since @rishu1601 has not responded back. @rishu1601 please comment here in case you are working on this.

**Comment by hetunandu** [comment] 2021-09-29 10:21
Not able to reproduce anymore 

https://user-images.githubusercontent.com/12022471/135250815-879df3c5-e448-4992-bc88-ea4618bfebbc.mov

**Closed by hetunandu** 2021-09-29 10:21 UTC
Labels: Bug, Good First Issue, Actions Pod, Low, Release, Query Editor, Needs Triaging

**Comment by prapullac** [comment] 2021-09-29 10:25
@hetunandu Can not reproduce the issue as dropdown now opens upwards.Hence closing the issue
