### ISSUE TITLE
[Bug]: Template apps aren't publicly accessible on first deploy. Needs an additional step to toggle public app setting for it to work

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12659] opened 2022-04-07 07:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Template apps aren't automatically public even when the toggle has been set. We need to toggle public setting to off and then back on for the app to be recognized as public.

### Steps To Reproduce

1. Go to templates and fork any app to your organization
2. Deploy app and make sure the app has been marked `public`
3. Copy share link and access it on incognito/another browser and observer a message pop-up saying `Resouce not found` and redirecting user to login page

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e1b00ee38f8b44ae8afea8a4e65fea08-00001.gif)](https://www.loom.com/share/e1b00ee38f8b44ae8afea8a4e65fea08)

### Public Sample App

https://release.app.appsmith.com/applications/624e8ab26aefb866285ad13d/pages/624e8ab26aefb866285ad13f

### Version

Cloud

**Comment by akash-codemonk** [comment] 2022-08-08 06:49
I thinks apps are not public by default. The share modal does show that it is public but it is incorrect. I think it is picking up from the exported json of the template app where the application is marked as public.
@kocharrahul7  Not sure how the templates are uploaded but is there a way to set the public field to false for the template app.  If there isn't a way then I think it is a bug in the backend where the field is to be set as false when imported as it is a new application altogether.

**Comment by GreenFlux** [comment] 2022-08-10 18:12
@akash-codemonk , yes, we can set the public field to false before exporting the app JSON that is used when forking. That should avoid the mismatched state of the public switch in the share modal. 

I think the default should be that the new forked app is not public when first forked, even if the source app is public. This is what the platform is currently doing, but the share modal is not properly reflecting the new app's state. 

This seems like a bug in the forking process. We could avoid it by toggling the public flag before exporting the app, but I think we should fix the forking process so the toggle reflects the current state of the new app, instead of showing the source app's share setting.

**Comment by NilanshBansal** [comment] 2022-12-08 06:59
Cannot Reproduce the issue, discussed with @kocharrahul7 
CC: @GreenFlux

**Closed** 2022-12-08 06:59 UTC
Labels: Bug, Backend, High, Release, Cannot Reproduce Issue, New Developers Pod, Templates

**Comment by ramsaptami** [comment] 2022-12-16 06:36
Public app setting is not appropriately set as per expected behaviour
