### ISSUE TITLE
[Feature] Logged out user doesn't get redirected to the app they were trying to access

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2636] opened 2021-01-20 07:04 UTC
## Summary

1. Try to access an app when logged out
2. Appsmith redirects you to the login page
3. Once you login, you are taken to the applications page

Ideal behavior: Redirect the user to the original application/page that they were trying to access.
All redirects because you were logged out should take you back to the original page you were trying to access.

**Comment by jsartisan** [comment] 2021-01-20 09:32
@areyabhishek This is already fixed in #2423.

**Comment by mohanarpit** [comment] 2021-01-20 15:05
@jsartisan It doesn't seem to be working on either Appsmith Cloud or self-hosted instances. Hence re-opening this issue.

**Comment by jsartisan** [comment] 2021-01-21 06:11
@mohanarpit I exactly followed the steps written by abhishek and it was redirecting for me. Can you share the steps to reproduce the issue?

**Comment by mohanarpit** [comment] 2021-01-21 09:20
For some reason, I can't reproduce it any more. Closing this issue. Will re-open again if I see this issue re-surface.

**Closed by mohanarpit** 2021-01-21 09:20 UTC
Labels: Login / Signup, Low, Low effort, Platform
