### ISSUE TITLE
[Bug]: Canada is not the USA

### ISSUE THREAD

**Issue by bamboowonder** [appsmithorg/appsmith#19562] opened 2023-01-06 23:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is sort of like saying Africa is a country.  Or Germany is like France because it is in Europe.   In the phone widget, it is USA/Canada +1 with an American flag.  And no way to disable that flag.   We are a Canadian company that only deals with Canada.

Please kindly give Canada its own flag and listing.

Thanks,

### Steps To Reproduce

create a phone widget.

### Version

self hosted 1.9.2

**Comment by dilippitchika** [comment] 2023-01-07 14:13
Thanks for bringing this up @bamboowonder, my apologies as this is not foolproof yet. We need a method to differentiate between canadian numbers and USA numbers on our end which our developers can also pass. 

The problem is developers can only pass default data in number with country code today and we can't automatically understand if it's USA or Canada due to the shared country code. Ideally we will need all such data to also contain the country code going forward.

**Comment by somangshu** [comment] 2023-01-17 06:10
duplicate of #18136, Closing this for better tracking the issue

**Closed** 2023-01-17 06:10 UTC
Labels: Bug, App Viewers Pod, Needs Triaging, Phone Input Widget
