### ISSUE TITLE
[Task]: Add new relic config to self hosted images that can be enabled for debugging when required

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28857] opened 2023-11-15 02:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We at appsmith can share our new relic license key with the user and should start receiving their monitoring data on our new relic setup.

We need to find a way to specify a unique new relic application name for every self hosted instance. The application name can be specified in the docker env variables.

Sample new relic file is attached: 
[newrelic.yml.zip](https://github.com/appsmithorg/appsmith/files/13359413/newrelic.yml.zip)

**Comment by sumitsum** [comment] 2024-02-02 06:52
Closing because it is a duplicate of #29892

**Closed by sumitsum** 2024-02-02 06:52 UTC
Labels: Performance Pod, Task, Docker, DevOps Pod, Performance infra
