### ISSUE TITLE
[Task]: Remove parse JS Actions from View mode

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#18291] opened 2022-11-21 03:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by somangshu** [comment] 2022-12-21 05:39
This was re-opened due to regression #19089 

We will re-prioritiize this once #18471 is merged since that brings good improvement to the parseJSActions, this might not be required any more

**Closed** 2023-01-23 05:01 UTC
Labels: Performance, JS Evaluation, QA, Low, Task, FE Coders Pod

**Comment by ramsaptami** [comment] 2023-01-23 08:23
PR had to be reverted since actual performance did not improve
