### ISSUE TITLE
[Bug] Orgs should be ordered in the order in a user was invited to them on the home page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1036] opened 2020-10-06 17:02 UTC
## Steps
1. Create 2 accounts
2. Create an organization in the second account with a name starting with A
3. Invite the user from the first account
4. The organization that the user was invited to should show up at the bottom of the list but instead shows up at a random location

**Comment by shinnlok** [comment] 2020-10-10 23:35
@Nikhil-Nandagopal Can I take a look?

**Comment by manchicken** [comment] 2020-10-11 00:50
I have the environment up and running, could I take this issue?

**Comment by manchicken** [comment] 2020-10-11 00:56
OK; I've reproduced the issue. This is _soooo_ much easier to spot with a second org. At first it was hard to see the problematic sorting, but I think I see it now. Please confirm attached screenshot.

(Please note, I'm not waiting for confirmation, I'm just hoping you can yell at me if I've misidentified.)
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/1848743/95667947-13514000-0b3b-11eb-9eed-14c4534e5597.png">

**Comment by manchicken** [comment] 2020-10-11 03:31
OK, I have a code change that I think will work, but I can't figure out how to get the React to run in conjunction with the docker-compose.yml really quick. Is there a trick to running the local server? I don't see anything in any of the README.md's.

**Comment by Nikhil-Nandagopal** [comment] 2020-10-12 06:10
Hi guys, thank you for your participation, I'm assigning this to @shinnlok since he claimed for it first.

@manchicken we have quite a few other issues open. You can have a look at our [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md) to get the code running

**Comment by manchicken** [comment] 2020-10-12 15:28
@Nikhil-Nandagopal Oh, man, I'm sorry @shinnlok, I didn't see that.

I'll take a peek elsewhere, many thanks.

**Closed** 2021-03-02 10:45 UTC
Labels: Backend, Bug, Home Page, Low, Platform, Release
