### ISSUE TITLE
[Bug]-[68]:Errors When Deleting a Project or Using Git Import on Windows

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13423] opened 2022-04-28 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user is getting errors when trying to delete a project. They also get a 504 Gateway Time-out error when doing a git import.
These issues are present only on a Windows machine, as it works fine on a Linux machine, although the browser versions used are the same (Chrome).

Screenshots with the issue:
![image](https://user-images.githubusercontent.com/101268423/165786062-0d34e10e-0be0-450a-b5db-d42952b8d4bb.png)
![image](https://user-images.githubusercontent.com/101268423/165786114-70180421-2ea9-44d5-9037-0aefde45220f.png)
![image](https://user-images.githubusercontent.com/101268423/165786150-c7693e56-feae-4dfe-aeec-ec4fda3d6647.png)
![image](https://user-images.githubusercontent.com/101268423/165786169-264044b0-591d-41b5-b3e4-4bdd0056615a.png)

Discord thread: https://discord.com/channels/725602949748752515/760761686549463060/968909378583425045

### Steps To Reproduce

1. Try to delete a project on Windows.
2. Try to do a git-import on Windows.

### Version

Environment: Windows, Chrome browser

**Comment by vuiets** [comment] 2022-04-29 05:11
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 34 |
| Effort (months)  | 0.25 |

**Comment by abhvsn** [comment] 2022-05-16 12:36
As per user comments it happend once and we are not able to reproduce this so closing for now.

**Closed by abhvsn** 2022-05-16 12:36 UTC
Labels: Bug, Needs Triaging, Git Version Control, Team Managers Pod, medium, Platform Pod

**Comment by hiteshjoshi** [comment] 2022-05-19 01:50
@abhvsn for future proofing ourself, can we add some analytics on time outs or error stages due to git?

**Comment by abhvsn** [comment] 2022-05-19 02:07
@hiteshjoshi we already have the analytics in place for error events as well. Let me check if the above scenario is covered, if not I'll add the datapoint 👍
