### ISSUE TITLE
Add error in evaluated value pane when functions are used in read value fields within the property pane

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3052] opened 2021-02-16 04:42 UTC
At times, users end up using functions in the read fields for a property pane. When it doesn't work, it causes confusion. We can eliminate this confusion by showing an error in the evaluated pane informing the user that this tact won't work.

**Comment by hetunandu** [comment] 2021-07-14 12:20
Duplicate of #2560

**Closed by hetunandu** 2021-07-14 12:20 UTC
Labels: Actions Pod, Enhancement, JS, error
