### ISSUE TITLE
[Bug]: Table header alignement issue

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#22743] opened 2023-04-26 03:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The positioning of the Center and Right aligned table headings isn't centered and isn't all the way to the right.

Discord: https://app.frontapp.com/inboxes/teams/folders/15690316/archived/76661528588

### Steps To Reproduce

1. Drag and drop the table widget
2. Go to the style properties of any column
3. Select the text-align property to right or center.
4. Observe that the header is not completely right-aligned or centered

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment] 2023-04-26 06:32
Duplicate of #21790

**Closed by somangshu** 2023-04-26 06:32 UTC
Labels: Bug, Table Widget, App Viewers Pod, Community Reported, Needs Triaging, medium

**Comment by somangshu** [comment] 2023-04-26 17:18
@AS-Laguna it indeed the same issue. Please check the pr attached, it's the same problem where column header has a offset and not properly centred
