### ISSUE TITLE
[Bug]: After setting the custom URI for MongoDB and Redis corresponding containers should not be created 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#9977] opened 2021-12-24 04:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we provide the custom URI for MongoDB and Redis still we can see corresponding containers are up, which is not the expected behavior as users have deliberately opted for this option to not run containers in their self-hosted setup.

### Steps To Reproduce

1. Update the env vars for MongoDB and Redis as described [here](https://docs.appsmith.com/setup/instance-configuration/custom-mongodb-redis)
2. Run appsmith using docker-compose
3. Check the running containers

### Environment

Production

### Version

Self-Hosted

**Comment by sharat87** [comment] 2021-12-24 12:47
Was this seen on an ECS setup or anywhere?

**Comment by abhvsn** [comment] 2021-12-24 13:50
This is for ECS setup.

**Comment by grinono** [comment] 2022-01-12 12:36
@abhvsn i tried to set the ECS environmental variables but they are not picked up by appSmith. Did it work for you?
same issue on local environmental variables. is there a known issue?

"environment": [
        {
          "name": "APPSMITH_CUSTOM_DOMAIN",
          "value": "internal.sevi.io"
        },
        {
          "name": "APPSMITH_MONGODB_URI",
          "value": "mongodb+srv://u:p@production.2ssea.mongodb.net/appsmith"
        }
      ],

**Comment by abhvsn** [comment] 2022-01-12 12:41
@sharat87 do we have any resolution on this?

**Comment by sharat87** [comment] 2022-01-12 13:53
Hey, we are currently working on this problem with Helm charts. Once it's fixed for Helm charts, it'll apply for ECS as well. The PR is going through review currently and should be out soon. 😃

**Comment by imanmzoe** [comment] 2022-01-14 15:48
We are also facing the same problem, and it would appear to be that the issue is that it cannot reliably connect to the Redis service.

**Comment by sharat87** [comment] 2022-02-09 14:22
This should be fixed as part of https://github.com/appsmithorg/appsmith/pull/10157.

**Closed by sharat87** 2022-02-09 14:22 UTC
Labels: Bug, Deployment, High, Needs Triaging, Platform Pod, New Developers Pod
