### ISSUE TITLE
[Bug]: The column flicks when the mouse focus is on the mid of the top or bottom outline on any of the column field and clicking on it

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#11033] opened 2022-02-09 08:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that on the table property pane when the mouse focus is on the column tile(Top or bottom) and clicking on it the focused state flicks slightly 

https://loom.com/share/aa2e41a2b3c746bc8e16ce2e3bada802

### Steps To Reproduce

1. Launch appsmith app in release environment 
2. Drag and drop table widget 
3. Open property pane 
4. Choose any of the column and keep the mouse focus on the column tile outline(top or bottom)
5.  Click and observe the focused state flicks/jumps slightly 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-02-10 14:12
@vicky-primathon  can you check this? Looks like an after effect of #10046 

CC @somangshu @shwetha-ramesh

**Comment by somangshu** [comment] 2022-02-16 07:05
I think this cant be solved easily given the implementation right now. @Tooluloope if this high effort, We can push this into icebox and take it up later. Lets not spend energy on this right now

**Comment by dilippitchika** [comment] 2022-02-25 05:27
@somangshu could you also add a few lines on why this can't be solved easily. Will help us retain context for this when we actually pick it up.

**Comment by somangshu** [comment] 2022-02-28 11:05
@dilippitchika its because of how the draggable logic works, The flicker is actually because of the recent algo to drag tiles for reordering, Its basically an assumption and hence I will need inputs from @Tooluloope as well

**Comment by somangshu** [comment] 2022-02-28 11:06
An easy fix could be to reduce the touchable area for dragging, But that might bring in other issue where the users are not able to drag easilty

**Comment by carinanfonseca** [comment] 2024-08-26 14:42
I am closing this issue because it is not reproducible in production right now.

**Comment by carinanfonseca** [comment] 2024-08-26 14:43
I am closing this issue because it is not reproducible in production right now.

**Closed by carinanfonseca** 2024-08-26 14:42 UTC
Labels: Bug, Table Widget, Widgets Product, Low, Production, Widgets & Accelerators Pod
