### ISSUE TITLE
[Bug]: Enterprise docker conainer fails to start

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#14406] opened 2022-06-09 07:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Enterprise fat container fails to start

```
ubuntu@ip-172-31-7-39:~/appsmith-ee-fat-localmongo$ uname -a
Linux ip-172-31-7-39 5.15.0-1005-aws #7-Ubuntu SMP Wed Apr 20 03:44:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-7-39:~/appsmith-ee-fat-localmongo$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
[eefatcontainernotworking.txt](https://github.com/appsmithorg/appsmith/files/8868023/eefatcontainernotworking.txt)
.
```

### Steps To Reproduce

```
sudo docker pull  appsmith/appsmith-ee:release
sudo docker run -d --name appsmith-eeprodoidc -p 80:80 -p 443:443 -v "$PWD/stacks:/appsmith-stacks" -e APPSMITH_LICENSE_KEY=#################  appsmith/appsmith-ee:release
```

### Version

Slef-Hosted release

**Comment by sharat87** [comment] 2022-06-09 09:30
@sum35h, this is the same thing you faced with the unescaped `$host`, right? Can you open a PR and push the fix please? Thanks!

**Comment by sharat87** [comment] 2022-06-30 08:42
@yatinappsmith Is this still an issue? Unless the license key is incorrect, I can't reproduce the problem with the steps given in the description. Can we close this if it's no longer an issue?

**Closed** 2022-08-08 11:51 UTC
Labels: Bug, Needs Triaging, Release Blocker, Docker, DevOps Pod
