### ISSUE TITLE
[Bug]: Text is duplicated when ':()' appears in trigger field and does not clear when text is removed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9669] opened 2021-12-09 05:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text is duplicated when `:()` is typed and does not clear when the text from property pane field is cleared.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/fe73622fa94c402bb41e8beafce897ab-00001.gif)](https://www.loom.com/share/fe73622fa94c402bb41e8beafce897ab)

### Steps To Reproduce

1. Try and type out `:(` and observe the behaviour using it and after removing the text and triggering the field

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment] 2022-04-08 08:56
reach 484

**Comment by rohan-arthur** [comment] 2022-04-28 08:45
this seems to have been fixed with some other PR, because not reproducible anymore:
https://images.zenhubusercontent.com/275993885/2d2b76fa-aca2-4f03-915e-c3b2ad061e0a/screen_recording_2022_04_28_at_14_14_26.mov

**Closed by rohan-arthur** 2022-04-28 08:45 UTC
Labels: Bug, JS, High, Release, Needs Triaging, FE Coders Pod, Actions Pod
