### ISSUE TITLE
[Bug]: If there are any unsaved data sources in the app, reconnect modal pop-up will appear every time prompting them to reconnect. when the user tries to import a new app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22829] opened 2023-04-28 10:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there are any unsaved data sources in the app, reconnect modal pop-up will appear every time prompting them to reconnect. when the user tries to import a new app

When user import a App with datasource and then doesnt add a reconnect detailes just skip it and then in the same app import the other app which doesnt have a datasource the reconnect datasource modal will be displayed
https://www.loom.com/share/a8e192e75762429693a1ad8e18f52135

### Steps To Reproduce

1. login o https://appsmith-huxvaxjvc-get-appsmith.vercel.app/applications
2. first import app which is built with multiple datasources 
3. when reconnect modal opens don't fill any details in the data source just skip it
4. now import an another app which has API and other datasources connected
5. The reconnect modal will be displayed with both app1 +app 2 datasources

### Environment

Deploy Preview

### Version

deploy preview

**Comment by abhvsn** [comment] 2023-04-28 10:46
@RakshaKShetty this is the expected behaviour as in legacy import flow we expect all the datasources which are part of app import to be saved.

**Comment by abhvsn** [comment] 2023-05-01 11:07
@RakshaKShetty any reason we are tryiong to update the application with completely different application?
  
  Correct me if I'm wrong but this is what I got from above description:
  1. Create new `app1_ws1` in workspace 1 (WS1) with datasource DS1
  2. Import the same `app1_ws2` in worspace 2 (WS2) and skip datasource config so that DS1 will not have correct configuration in WS2
  3. Now create `app2_ws1` in workspace other than WS2 with datasource DS2
  4. Update the app `app1_ws2` from 2nd step with the `app2_ws1` which will ask to configure both `DS1` and `DS2`
  
  If this is the scenario then isn't this expected considering DS1 is still connected to `app1_ws2`, considering there will be queries present in published mode?

**Comment by abhvsn** [comment] 2023-05-02 14:41
Lowering the priority as this is a side-effect the root cause is user's can update the existing application with any JSON file as we are not placing any checks currently.

**Comment by infinitetrooper** [comment] 2023-11-24 11:22
Closing this, expected behavior. The feature is meant for updating existing app.

**Closed by infinitetrooper** 2023-11-24 11:22 UTC
Labels: Bug, Needs Triaging, Import-Export-App, Deploy Preview, Team Managers Pod, Medium, Git Pod, Airgap
