### ISSUE TITLE
[Feature]: Autocomplete widget

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#9976] opened 2021-12-24 03:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Autocomplete widget allows users to quickly find values from a list by providing suggestions as you type.

When typing in the autocomplete widget, it starts searching for entries that match and displays a list of values to choose from. By entering more characters, the user can filter down the list to get better matches.

### Why should this be worked on?

In the select widget, you need to scroll down the whole list to find items. This becomes cumbersome when you have dropdown lists with a large number of items. It would be nice to have an option to type a word and have it filter a list of options from which the user is able to select.

**Comment by dilippitchika** [comment] 2021-12-27 19:15
Duplicate of #6928 (https://github.com/appsmithorg/appsmith/issues/6928)

**Closed by dilippitchika** 2021-12-27 19:15 UTC
Labels: Enhancement
