### ISSUE TITLE
[Feature] Import and Export a project/app on cloud/local and vice versa

### ISSUE THREAD

**Issue by s2agrahari** [appsmithorg/appsmith#2006] opened 2020-12-03 04:42 UTC
## Summary

Let's say I have developed a project using docker on a local machine. I want to export this project to the appsmith cloud or different cloud and vice-versa

## Motivation

Currently, It's difficult to share/ship a project built to a local machine to production on a cloud

**Comment by mohanarpit** [comment] 2020-12-03 04:58
Closing as duplicate of #488. 

@s2agrahari Please feel free to add your thoughts and use-case on the other issue.

**Closed by mohanarpit** 2020-12-03 04:58 UTC
