### ISSUE TITLE
[Feature]: Multil select in a table

### ISSUE THREAD

**Issue by anhsao104** [appsmithorg/appsmith#30379] opened 2024-01-17 07:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

My database table had a column that contained multiple selects, like a category that can have multiple subcategories. But in the table, there is no column type like multiple select. I think we need to develop this new feature

### Why should this be worked on?

it will be very helpful in development.

**Comment by Nikhil-Nandagopal** [comment] 2024-02-02 07:00
Duplicate of #16026

**Closed by Nikhil-Nandagopal** 2024-02-02 07:00 UTC
Labels: Enhancement, App Viewers Pod, Community Reported, Table Widget V2
