### ISSUE TITLE
[Bug]-[Infinity]:Query Fails When Prepared Statement Is Turned On and Value Contains Only Numbers and Commas

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13620] opened 2022-05-05 17:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When running a **query** with **Prepared Statement** turned **on**, in which one of the values contains only **numbers** and **commas** (and optionally, **one single dot**),  it returns the error: 

> Query preparation failed while inserting value: 12,23.4, for binding: {{Input3.text}}. Please check the query again.
> Error: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

**Notes**: 
- This happens for all queries (Select, Insert, etc.)
- The issue is reproducible for **PostgreSQL** and **MySQL** databases.

![image](https://user-images.githubusercontent.com/101268423/166979829-23c5389c-a175-4b00-abdd-9f7408812e0e.png)
![image](https://user-images.githubusercontent.com/101268423/166981463-3cbf7f51-85ee-408d-9efb-3aba066acf53.png)

Sample app that reproduces the issue: https://app.appsmith.com/app/prepared-statement-with-comma/prepared-statement-with-comma-6273fdb75984be5f57847aad

### Steps To Reproduce

1. Create a **Select** or **Insert** query and bind it to an **Input** or **Text** widget.
2. Ensure **Prepared Statement** is turned **on**.
![image](https://user-images.githubusercontent.com/101268423/166981047-d752fab2-f2f4-402b-8ce3-d123d70f9807.png)
3. Enter a **value** that contains only **numbers** and **commas** (and optionally, **one single dot**) in the **widget**. E.g., `12,34` or `12,03,456,7.89`.
![image](https://user-images.githubusercontent.com/101268423/166981284-e6598f65-4c2c-4183-b192-7bdba9d49139.png)
4. Run the **query**.
![image](https://user-images.githubusercontent.com/101268423/166981463-3cbf7f51-85ee-408d-9efb-3aba066acf53.png)

### Public Sample App

https://app.appsmith.com/app/prepared-statement-with-comma/prepared-statement-with-comma-6273fdb75984be5f57847aad

### Version

Appsmith v1.6.24-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment] 2022-05-10 09:34
@ame-appsmith in this case latitude is a number in the database and it does not accept commas

**Comment by Nikhil-Nandagopal** [comment] 2022-05-10 10:04
@ame-appsmith that is a great point!

**Comment by subrata71** [comment] 2022-08-16 05:07
Hi @ame-appsmith 
Can you please share the DDL of the table?

**Comment by ame-appsmith** [comment] 2022-08-16 07:47
@subrata71 I have used the `users` database.
![image](https://user-images.githubusercontent.com/101268423/184826168-d75103c5-c4ac-489a-a9fa-9b54359399a7.png)

**Comment by subrata71** [comment] 2022-08-16 11:33
## Root Cause
I have figured out the actual problem behind this issue.
According to our current data type identification implementation, the server guesses the data type from the value. If a string value contains comma(s), the server replaces the commas with an empty string and later tries to parse it as `integer -> long -> float -> double -> ...`. 

For a value like “`134,33.53`” the server identifies this as `FLOAT` and later provides the value with commas to the plugin and the plugin converts this to `BigDecimal` like below:

`preparedStatement.setBigDecimal(index, new BigDecimal(String.valueOf(value))); //value = "134,33.53"`
And this line generates error like:

`Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark`

**Comment by subrata71** [comment] 2022-08-16 11:48
## Good News
IMO, We don’t need to introduce any special type for that. This concern is on the user who knows the data type of the target column very well and the responsibility is upon the user to provide the correctly formatted data to that column. In any way, if we had to take this then there are a lot of other cases that should be taken care of as well.

And I think a concern like comma-separated numerics should be confined to the presentation layer.

We believe that this should get fixed by **Datatype Handling V1**.

**Comment by obafemiolorungbon** [comment] 2022-08-18 04:30
I can also confirm that when passing data to queries through the query.run() method, if any of the properties of the objects passed as params contains comma. the resulting query is the first number of the property value,

e.g UserQuery.run({paginate:"10,0"})

what is passed to UserQuery at run time is 10. 

which causes problems for us.

**Comment by rohan-arthur** [comment] 2022-08-25 09:50
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 67 |
| Effort (months)  | <<number>> |

**Comment by obafemiolorungbon** [comment] 2022-08-25 20:14
> I can also confirm that when passing data to queries through the query.run() method, if any of the properties of the objects passed as params contains comma. the resulting query is the first number of the property value,
> 
> e.g UserQuery.run({paginate:"10,0"})
> 
> what is passed to UserQuery at run time is 10.
> 
> which causes problems for us.

I can also confirm that turning off smart substitutions removed this behavior. This works for us.

**Closed** 2022-10-18 05:32 UTC
Labels: Bug, High, MySQL, BE Coders Pod, Postgres, Prepared statements, needs estimate, Datatype issue, Data Platform Pod, Integrations Pod
