### ISSUE TITLE
Enhancement : Allow image upload in image widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1623] opened 2020-11-06 13:08 UTC
Add an image widget on canvas and giving an option into image widget to upload a an image of any format would reduce the binding

**Comment by Nikhil-Nandagopal** [comment] 2020-11-07 06:37
@prapullac thank you for this. This has been recorded so I'm marking this as a duplicate of #1089

**Closed by Nikhil-Nandagopal** 2020-11-07 06:37 UTC
Labels: Bug, Low, Needs Design, Release
