### ISSUE TITLE
[Bug] Adding a new property to the map function does not add a new column on the table

### ISSUE THREAD

**Issue by gordervanhel** [appsmithorg/appsmith#1719] opened 2020-11-13 00:31 UTC
## Description

[What happened]

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to a table widget
2. Add a new property to the transform map function
3. New column does not reflect on the table

### Important Details
 - Version: [Self-Hosted vx.x]
 - OS: [e.g.MacOSX]
 - Browser [firefox

**Comment by mohanarpit** [comment] 2020-11-13 01:44
@gordervanhel I'm unable to reproduce this bug. Can you give an example of the map function that you used? The one I used to create a new column is:

```
{{Api1.data.map((row) => { return {...row, foo: row.name}})}}
```

**Comment by Nikhil-Nandagopal** [comment] 2020-11-18 06:53
@gordervanhel We're unable to reproduce this and hence closing this issue. Feel free to re-open this with more details, preferably with a video if it's still happening for you

**Closed by Nikhil-Nandagopal** 2020-11-18 06:53 UTC
Labels: Bug, High, Needs More Info, Table Widget, Widgets
