### ISSUE TITLE
[Bug] Input Widget Regex validation not working as expected 

### ISSUE THREAD

**Issue by pric-appsmith** [appsmithorg/appsmith#1877] opened 2020-11-24 07:32 UTC
## Description

I wanted to create an input widget that allows numeric values greater that 0, and upto 2 places of decimal. I chose `Data Type` as `Number`, and set `Regex` to `^\s*(?=.*[1-9])\d*(?:\.\d{1,2})?\s*$` . On my local machine's terminal, I verified that the regex returns no match for input value `1.222` . But when I set the value of the input widget on Appsmith to `1.222`, no error is shown.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add a new Page
2. Drag drop input widget on it
3. Choose Data Type as Number
4. Set Regex to `^\s*(?=.*[1-9])\d*(?:\.\d{1,2})?\s*$`
5. Deploy application
6. In the live app, set the value of input as `1.222`
7. Regex validation doesn't fail, and input 1.222 is accepted

### Expected behavior
Regex validation should fail

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Chrome

**Comment by prapullac** [comment] 2020-12-15 07:49
The issue still persist.hence reopening the issue

**Comment by Nikhil-Nandagopal** [comment] 2021-01-06 09:27
@jsartisan this issue seems to have reopened.

**Comment by jsartisan** [comment] 2021-01-06 09:40
@Nikhil-Nandagopal I just checked. I can see the error tooltip whenever the above regex is failing. Tried with the form widget also. - https://app.appsmith.com/applications/5ff584aa53b64c03e83001c4/pages/5ff584aa53b64c03e83001c6

1.22 is passing and 1.222 is failing.

**Comment by mohanarpit** [comment] 2021-01-06 09:42
This was a build problem when it got reopened. This is not an issue.

@prapullac Please verify this and close the issue if it looks good to you.

**Comment by prapullac** [comment] 2021-01-06 11:15
The issue is fixed and working as expected

**Closed by prapullac** 2021-01-06 11:15 UTC
Labels: Bug, Frontend, Input Widget, Low, QA, UI Building Pod, Verified, Widgets
