### ISSUE TITLE
[Bug]: Postgresql connections are left idle.

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#14117] opened 2022-05-26 09:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After running a query postgres connections are left idel

### Steps To Reproduce

1. Create Postgress data source.
2. Create multiple onload select queries.
3. Create multiple pages.
4. traverse multiple all the pages few times.
5. Check idle connections

### Public Sample App

https://release.app.appsmith.com/app/habitasaurus/page1-628f4177dfdca56c4283eb2a/edit/queries/628f4182dfdca56c4283eb2c

### Version

cloud

## Update:
- A large part of the issue is supposed to be resolved by this [fix](https://github.com/appsmithorg/appsmith/pull/14348). 
- Unsolved part is described [here](https://www.notion.so/appsmith/Postgres-multiple-idle-connections-issue-72cc080691c64385ab3efab5d573c630).

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5sozw)

**Comment by sumitsum** [comment] 2022-05-30 14:07
@yatinappsmith I could not reproduce the increasing idle connections scenario using the steps mentioned in the PR. I used the following command to check the state of connections to the db: `SELECT usename, state FROM pg_stat_activity where datname='mydb'`; Please let me know if I should use some other way or if you used any specific way to test it.

**Comment by prapullac** [comment] 2022-06-16 08:16
Hi @sumitsum 
Please find the test cases attached[ here](https://github.com/appsmithorg/TestSmith/issues/1891)

**Comment by sumitsum** [comment] 2022-07-18 09:26
Partly addressed by https://github.com/appsmithorg/appsmith/pull/14348

**Comment by sumitsum** [comment] 2022-07-20 18:05
Lowering the priority to `High` since we expect the issue to be resolved to a large extent via https://github.com/appsmithorg/appsmith/pull/14348

**Comment by sumitsum** [comment] 2022-11-14 10:55
Another case was reported : https://theappsmith.slack.com/archives/C040LHZN03V/p1668423093195909

**Comment by saran-ravi** [comment] 2022-11-15 07:52
I was facing this issue recenlty during this week, Too many idle connections were opened by single page of appsmith so If multiple users are using it then database quickly reaches maximum connection limit and appsmith pages becomes unresponsive.

The same issue was obeserved during the end of september 2022 and when I tried to reduce the idle_session_timeout it helped then but this time it did not help.  Idle connections are closing automatically even if the session timeout was set with low value like 50 seconds.

The idle connections persisit for longer time even after the users closes appsmith pages.

I use **postgres 14** database. I have attached the screen shot of **pg_stat_activity** for reference.

I was using appsmith in my company for the past few months but this issue for faced frequently.

Thanks 
![Screenshot_2022-11-11_002500](https://user-images.githubusercontent.com/30770108/201859992-c451837e-3071-4d07-aae6-1b9af84f2f2c.png)

**Comment by sarojsarab** [comment] 2022-11-23 05:47
My app has multiple pages and links to a Supabase database, hence I am experiencing this problem whenever the app is reloaded once or twice. The Appsmith pages are unresponsive because there are too many idle connections that have been opened by the Appsmith.

**Comment by sumitsum** [comment] 2022-11-23 11:03
@saran-ravi @sarojsarab can you please mention which version of Appsmith you were using when you faced this problem ?

**Comment by sarojsarab** [comment] 2022-11-23 12:18
@sumitsum I am using https://app.appsmith.com/ to build my app, and I think the version was v1.8.9 when I got this issue

**Comment by learnbasicsfun** [comment] 2022-11-23 18:26
@sumitsum I am using the appsmith cloud, Appsmith v1.8.10-SNAPSHOT - Hope it is the latest

**Comment by saran-ravi** [comment] 2022-11-23 18:27
@sumitsum I am using the appsmith cloud, Appsmith v1.8.10-SNAPSHOT - Hope it is the latest

**Comment by rohan-arthur** [comment] 2023-02-28 19:17
Today I saw some behaviour that can give a clue. Here are the steps I followed:

1. Supabase setup
    a. create a project in supabase
    b. create a dummy table with some dummy data
    
  
![Screenshot 2023-03-01 at 00 37 14](https://user-images.githubusercontent.com/94514895/221956265-ec255032-85fb-4608-a4a8-02b2d9a80b05.png)
    
    c.   get connection params
    
2. Appsmith setup
    1. create an app with datasource that connects to this postgres db
    2. create two queries:
        1. `select * from test` bind this to a table and also trigger the query with a button
        2. `SELECT COUNT(*) FROM pg_stat_activity WHERE application_name='PostgreSQL JDBC Driver';` bind this to another table and also trigger the query with a button

This is what the app looks like.

![Screenshot 2023-03-01 at 00 40 52](https://user-images.githubusercontent.com/94514895/221956347-282311c9-d7dd-4525-b18e-38b534761cb0.png)


Things to note:

1. when I first created the app and ran the query, the number of connections was already 5 - too high, shouldn’t this have been 1? 
2. keep going back to this app and clicking both the buttons after some intervals (5 minutes, 30 minutes, a few hours etc) - the number of connections only keeps growing. In the screenshot above, it has reached 27.

******************************************************************************************************Why I am not sharing the app or the db credentials?******************************************************************************************************

this is easy to setup, and if I share the credentials here, then our assumption that there’s only one external consumer of this db becomes moot, and we won’t know truly how many connections should be there.

**Comment by felix-appsmith** [comment] 2023-03-07 14:16
This issue seems to be the same or similar to this problem: #21203

**Closed** 2023-04-03 04:18 UTC
Labels: Bug, Backend, Critical, Core Query Execution, BE Coders Pod, Postgres, Data Platform Pod, Integrations Pod, Connection pool
