### ISSUE TITLE
[Bug] Header names should be adjusted for lengthy column headers under 'Update row index'

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6864] opened 2021-08-25 07:11 UTC
Scroll on long column names does not look good hence need to replace this with the new **input widget** that accommodates labeling

![image](https://user-images.githubusercontent.com/79509062/130743244-c04ee5b6-c29b-4764-82c5-d99f1c28a6df.png)

**Comment by Nikhil-Nandagopal** [comment] 2021-09-02 08:48
Seems like a bug with the text widget. Horizontal scrollbars should not show

**Comment by somangshu** [comment] 2021-09-22 06:27
The behaviour is default here, the scrollbar shows up because the text inside is one string (without spaces), Break word style here will introduce the vertical scroll. 

Another thing I have noticed is that this depends on the screen size. For bigger screens this does not tend to happen

**Comment by ramsaptami** [comment] 2021-09-22 06:33
Can the scroll styling for Windows be the slimmer ones like on MacBook instead of the bulky one as seen on the screenshot above?

**Comment by Nikhil-Nandagopal** [comment] 2021-09-22 07:47
@somangshu this is how it works for a single string on my laptop. Why is the behavior different here?
<img width="451" alt="Screenshot 2021-09-22 at 1 16 28 PM" src="https://user-images.githubusercontent.com/3897254/134303368-e4104a66-5901-46b2-be17-23fb80670198.png">

**Comment by somangshu** [comment] 2021-10-01 06:57
@ramsaptami what browser and OS is this, I cant seem to reproduce this!

**Comment by SandipPalit** [comment] 2021-10-01 10:53
I would Like to work on this. Please assign it to me.

**Comment by ramsaptami** [comment] 2021-10-01 13:19
The issue with a horizontal scroll appearing seems to have been fixed @SandipPalit. 

Could I point you to a few [other issues ](https://github.com/appsmithorg/appsmith/labels/hacktoberfest) that might interest you?

**Comment by SandipPalit** [comment] 2021-10-01 13:26
No problem. I will search for other issues and resolve them.

**Comment by dilippitchika** [comment] 2022-04-25 05:12
Cannot see a scroll today on the text widget in the horizontal mode. @ramsaptami can we close this?

**Closed** 2022-04-25 05:39 UTC
Labels: Bug, App Viewers Pod, Low, UI Building Pod, Text Widget
