### ISSUE TITLE
[Bug] Date picker shows time field for formats that don't require time

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1341] opened 2020-10-21 21:20 UTC
## Description

The date picker widget shows the time field even when the date format chosen doesn't require it.
<img width="450" alt="Screen Shot 2020-10-22 at 2 45 18 AM" src="https://user-images.githubusercontent.com/30255708/96788179-ac703880-1410-11eb-928e-73cf301ce169.png">

The time field should be hidden from the widget if the date format doesn't require it.

Loom video: https://www.loom.com/share/6109c4c4a62f453eb502d3ff996dfe5f

**Comment by Nikhil-Nandagopal** [comment] 2020-10-24 05:07
Duplicate of #773

**Closed by Nikhil-Nandagopal** 2020-10-24 05:07 UTC
Labels: Bug, Date Picker Widget, Low
