### ISSUE TITLE
[Bug]: Fetch File

### ISSUE THREAD

**Issue by JhouXerox** [appsmithorg/appsmith#18861] opened 2022-12-12 04:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. I try to upload file directly like the pic. But it send string"[object Object]" in file field.
[image](https://user-images.githubusercontent.com/24403596/206958312-6c157893-51d1-4f94-9722-7eefcb1be2ce.png)
It should be a File object.

2. I try to convert file to File type, but I found that file size is changed.
[image](https://user-images.githubusercontent.com/24403596/206958451-1fe5dd42-766b-4014-b388-226c6468a5b8.png)
[image](https://user-images.githubusercontent.com/24403596/206958650-7fc67543-33ce-4541-9a4a-d973467c04cd.png)

It should be same.I tried type of base64,binary,text ,these are all different.

### Steps To Reproduce

1. file picker,select file
2. upload file use fetch
3. convert filepicker.files[0].data to File object

### Version

1.8.12

**Comment by Nikhil-Nandagopal** [comment] 2022-12-12 05:57
Closing as duplicate of #17045

**Closed by Nikhil-Nandagopal** 2022-12-12 05:57 UTC
Labels: Bug, Needs Triaging
