### ISSUE TITLE
[Bug]: Configured custom environment is visible with Business license for the same user

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#33091] opened 2024-05-01 06:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a user has created a custom environment while being on Enterprise License, the same custom environment should not be visible once they downgrade to a Business License.

### Steps To Reproduce

1. Create a custom env when user is on Enterprise License.
2. Now downgrade to Business license.

**Expected:** The custom environment created should not be visible in the environment dropdown list or anywhere else in the app.
**Actual:** We are able to see the custom environment in the environment dropdown list as well as the datasource configuration screen.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/d38df4a1f372481abab8040b996cc4af

### Version

Cloud

**Comment by riteshkew** [comment] 2024-07-22 10:56
Duplicate of #28073, so closing this off

**Closed by riteshkew** 2024-07-22 10:56 UTC
Labels: Bug, High, Production, Needs Triaging, Git Pod, Custom environments
