### ISSUE TITLE
[Bug]: Upon upgrading instance from lower version to latest version

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#31364] opened 2024-02-28 12:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, when we upgrade appsmith from lower version to latest version. 

We see a refresh button even after refresh .

Upon doing a command+shift+r or hard refresh the refresh dialog is gone 

### Steps To Reproduce

1. Currently, when we upgrade appsmith from lower version to latest version. 
2. We see a refresh button on the appsmith home page.
3. Upon clicking refresh we still see the message

### Environment

Production

### Version

selfhosted

**Comment by Nikhil-Nandagopal** [comment] 2024-04-25 09:10
@pratapaprasanna is this still valid?

**Comment by sharat87** [comment] 2024-11-07 10:57
Closing. Let's reopen or open anew if the issue is still there.

**Closed by sharat87** 2024-11-07 10:57 UTC
Labels: Bug, Production, Needs Triaging, Docker, DevOps Pod, Medium
