### ISSUE TITLE
[Bug]: Wrong evaluated value after binding checkbox group widget with query

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#24620] opened 2023-06-19 11:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we bind a checkbox group widget with a query, the default options seem to be retained in the evaluation.

### Steps To Reproduce

1. D&D checkbox group & text widgets.
2. In the Text property for the text widget enter: `{{CheckboxGroup1.selectedValues}}`.
3. Now select all values in the checkbox group widget. All selected values should reflect in text widget.
4. Now, remove all the options & bind the checkbox query with any datasource.

**Expected:** All default options should disappear & only the options selected from the datasource should reflect in the text widget.
**Actual:** We are able to see old options as well.

### Environment

Production

### Issue video log

https://www.loom.com/share/bc63bae4935442d98f690326d35c7a6e

### Version

Cloud
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/25849
```

**Comment by bharath31** [comment] 2023-06-20 04:09
@arunvjn could you please investigate this issue?

**Comment by srix** [comment] 2023-07-31 11:26
This issue was assigned to https://github.com/orgs/appsmithorg/teams/fe-coders-pod . I was working on it. The RCA points to bug inside the ChecckboxGroupw Widget. So reassigning to https://github.com/orgs/appsmithorg/teams/app-viewers .

Capturing the RCA details here:

The problem and symptoms are clearly mentioned in the above issue. so skipping it.

**Possible root causes:**

Eval flow retains the default values in the this.props.selectedValues 
Widget's this.props.selectedValues is not cleaned up on options update.

**Actual root cause:**
The exact root cause is not ascertained. But the following observation may help. 

The CheckBoxGroup widget allows the user to set a default value which does not exist in the options list. Ideally, the widget selectedValues should be an empty array if the default value is not present in the options dictionary.

Try adding this unit testcase in `app/client/src/widgets/CheckboxGroupWidget/widget/index.test.tsx` . This should pass. Now it fails.
```

 test("should return empty array when default value is not in options", async () => {
    const result = defaultSelectedValuesValidation(`["blue"]`, {
      options: [
        {
          label: "Apple",
          value: "1",
        },
        {
          label: "Orange",
          value: "2",
        },
      ],
    });

    expect(result).toStrictEqual({ isValid: true, parsed: [""] });
  });

```

**Suggested solution:**
An implementation of `app/client/src/widgets/MultiSelectWidgetV2/widget/derived.js ` similar to the MultiSelectWidgetV2 can be implemented to check for missing default values in options and ignore the default value itself.

**Comment by Shivam-z** [comment] 2024-06-03 04:13
Hi @keyurparalkar @shadabbuchh , I have raised a PR for this issue. Could you please assign a reviewer for this.
Thank You

**Comment by Shivam-z** [comment] 2024-06-04 06:53
@keyurparalkar  @shadabbuchh  This is the PR link : https://github.com/appsmithorg/appsmith/pull/33906

**Comment by Shivam-z** [comment] 2024-06-11 00:05
@ramsaptami @Nikhil-Nandagopal @keyurparalkar @shadabbuchh 
please any one assign a review for this [PR](https://github.com/appsmithorg/appsmith/pull/33906) else it will auto close in some days.

**Closed** 2024-07-17 05:24 UTC
Labels: Bug, App Viewers Pod, High, Production, Checkbox Group widget
