### ISSUE TITLE
[Bug]: Move to Postgres :The datasources order seems to be broken in Datasources section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35610] opened 2024-08-12 07:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The databases order seems to be broken in Datasources section
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3ec3f7e7-5e1a-4d48-83d0-e962df392987">

### Steps To Reproduce

1. Pull postgres abhijeetappsmith/appsmith:ee-pg locally
2. login as admin and go to admin setting advance section
3. add the custom postgres uri
4. once save and restart
5. now create a new app and go to datasource section
6. the datasource order seems to be broken

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

deploy preview

**Comment by AnaghHegde** [comment] 2024-08-20 13:00
@RakshaKShetty I see the correct order in local. Can you confirm if the issue is still reproducible. 
![image](https://github.com/user-attachments/assets/c3ac53f2-b7b7-42c2-a158-f3c08d342226)

**Comment by RakshaKShetty** [comment] 2024-08-21 03:43
@AnaghHegde the attached screenshot in your comment check the datasource section the order is different also attaching my screenshot 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a629e4e0-aeda-4a28-b6a1-e8a4027ce3f4">

**Comment by RakshaKShetty** [comment] 2024-08-21 04:49
@AnaghHegde the screenshot you have attached has a wrong order this is the correct order
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/8034f6ab-bf03-4563-825f-53af3fadbc5f">

**Comment by abhvsn** [comment] 2024-08-22 08:00
### Release ordering:
<img width="1723" alt="Screenshot 2024-08-22 at 1 23 27 PM" src="https://github.com/user-attachments/assets/c9939cf9-773d-498c-badd-e3959029290f">

### Prod ordering:
<img width="1719" alt="Screenshot 2024-08-22 at 1 24 10 PM" src="https://github.com/user-attachments/assets/1076795f-4b75-4a0d-8041-32b3f8181e2a">

### DP ordering:
<img width="1725" alt="Screenshot 2024-08-22 at 1 24 28 PM" src="https://github.com/user-attachments/assets/4bb0bd8e-45d3-49b2-98d1-53585a9cbe0f">


@RakshaKShetty I don't think we are following any specific ordering for databases.

**Comment by abhvsn** [comment] 2024-08-22 10:20
Closing this as per the discussion from https://theappsmith.slack.com/archives/C040LHZN03V/p1724313605988879

**Closed by abhvsn** 2024-08-22 10:20 UTC
Labels: Bug, Needs Triaging, Deploy Preview, Medium, DP, Move to Postgres, DB Infrastructure Pod
