### ISSUE TITLE
[Enhancement] Application Themes + Custom Class for custom CSS for widgets

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3183] opened 2021-02-24 07:30 UTC
Sometimes user wants to have application-level styling ( background colors, fonts, etc ). An option for setting application styles would be great.

**Comment by segfall** [comment] 2021-09-14 23:41
Strong agree here. A well-developed internal tool needs custom styling to distinguish it from less used tools.

**Comment by fcatanzaro** [comment] 2021-09-27 20:42
Huge game changer. Agree with commenter above.

**Comment by sbalaji1192** [comment] 2021-11-16 11:18
Closing this as
- Application Themes are being worked on https://github.com/appsmithorg/appsmith/issues/3369.
- duplicate of https://github.com/appsmithorg/appsmith/issues/3095

**Closed by sbalaji1192** 2021-11-16 11:18 UTC
Labels: Enhancement, Needs Design, App Viewers Pod, UI Building Pod, Widget Styling

**Comment by ichik** [comment] 2024-01-09 11:09
@fcatanzaro @segfall Hi. We've been working on a revamp of our layout and theming engines that should facilitate faster, more predictable, and more consistent styling of the widgets. While that is still work-in-progress the team wants to properly evaluate a common request for custom CSS, that has been asked by the community.
To that end I'd be interested in talking with you, to see what kind of ideas you have.
You can schedule [a call with me](https://www.getclockwise.com/c/vadim-appsmith-com/quick-meeting) if you're willing to talk or [drop me an email](mailto:vadim@appsmith.com).
