### ISSUE TITLE
[Bug]-[385]:Actions on RTE is repeated

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14949] opened 2022-07-01 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="761" alt="Screenshot 2022-07-01 at 2 28 58 PM" src="https://user-images.githubusercontent.com/83569920/176862557-2e3623c7-4978-4bb4-97ba-ea2f6419ac96.png">

### Steps To Reproduce

1. Drag and drop a RTE widget
2. Click on 3 dots in toolbar
3. Check the actions are repeated

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-07-04 06:36
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 385 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment] 2022-07-04 06:36
Remove the other color and highlight color

**Comment by victor-echo-delta** [comment] 2023-04-02 17:25
This issue seems to be resolved, is there anything more that needs to be done here?
<img width="483" alt="image" src="https://user-images.githubusercontent.com/34849403/229368866-8b015669-4ac7-42fe-8eb8-1fed156cc29b.png">

**Comment by nikhil-babar** [comment] 2023-05-03 17:18
@dilippitchika I would like to work on this issue, plz can you assign me this issue

**Comment by dilippitchika** [comment] 2023-05-04 03:46
Closing this, as the issue is now resolved

**Closed by dilippitchika** 2023-05-04 03:46 UTC
Labels: Bug, Good First Issue, Rich Text Editor Widget, App Viewers Pod, Low, Production
