### ISSUE TITLE
[Task]:  Move app settings to the left

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#27949] opened 2023-10-11 09:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Figma: https://www.figma.com/proto/GTOUFv2RYxDjmxfbGYoWpn/IA-changes?type=design&node-id=408-39046&t=tjYviuVkHVLgh2NQ-0&scaling=min-zoom&page-id=408%3A23992

**Comment by rohan-arthur** [comment] 2023-10-13 05:52
duplicate of #27955

**Closed by rohan-arthur** 2023-10-13 05:52 UTC
Labels: IDE, Task, New Developers Pod
