### ISSUE TITLE
[Bug]: Preview mode has a close sidebar button that doesn't do anything

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#14511] opened 2022-06-14 05:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user is in preview mode, the sidebar (aka the Explorer) is hidden by default, but the hamburger icon on the navbar is still visible.
The hamburger icon in this context has no functionality, and should not be visible to a user. (Screenshot below).
<img width="699" alt="Screenshot 2022-06-14 at 11 20 54 AM" src="https://user-images.githubusercontent.com/65771350/173503250-468bdecc-f0a3-40e4-8fec-3b888e07e93a.png">
<img width="604" alt="Screenshot 2022-06-14 at 11 21 00 AM" src="https://user-images.githubusercontent.com/65771350/173503258-fdf5579f-6ff7-44b8-bf00-c463511e6e91.png">

**Expected behavior**: Hide the Hamburger icon (close sidebar button) when in preview mode.

### Steps To Reproduce

1. Open any app on Appsmith Editor
2. Switch to preview mode
3. Try clicking on the Hamburger menu icon, it's the left-most icon on the navbar
4. The button doesn't do anything

### Version

Cloud

**Comment by akash-codemonk** [comment] 2022-06-14 06:38
Duplicate of https://github.com/appsmithorg/appsmith/issues/13869

**Closed by akash-codemonk** 2022-06-14 06:38 UTC
Labels: Bug, Duplicate, Needs Triaging
