### ISSUE TITLE
[Docs]:  #11982 [Feature] HubSpot CRM API Saas Integration 

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#17818] opened 2022-10-21 19:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

> TODO 

 - [ ] Evaluate if this task is needed. If not add the "Skip Docs" label on the parent ticket 
- [ ] Fill these fields 
- [ ] Prepare first draft 
- [ ] Add label: "Ready for Docs Team" 

Field | Details 
-----|----- 
**POD** | BE Coders Pod 
**Parent Ticket** | #11982 
Engineer | 
Release Date | 
Live Date | 
First Draft | 
Auto Assign | 
Priority | 
Environment |

**Comment by felix-appsmith** [comment] 2022-10-25 18:05
As discussed with @jnikhila, the HubSpot Docs could become huge (~40 commands). So, we decided to segregate the work on different issues.

My proposal is to have an issue that serves as an introduction (what's HubSpot, how to get a token, how to create a data source), and other issues for the different scopes of the HubSpot Integration (CMS stuff, CRM stuff, Settings, Domains, etc).

## Proposed Structure / Organization of Issues/Drafts

1. [13466 - [Docs] #11404 [Feature] HubSpot Integration](https://github.com/appsmithorg/appsmith/issues/13466)
    1. What's HubSpot?
    2. Creating a Private App and getting a Token
    3. Creating a Datasource
    4. Making a basic Query.
2. [13267 - [Docs] #13026 [Feature] HubSpot CMS Domains API Saas Integration](https://github.com/appsmithorg/appsmith/issues/13267)
    1. Everything related to the CMS Domains commands.
3. [13266 - [Docs] #13028 [Feature] HubSpot CMS URL Redirects API Saas Integration](https://github.com/appsmithorg/appsmith/issues/13266)
    1. Everything related to the CMS URL Redirects commands.
4. [13021 - [Docs] #12151 [Feature] HubSpot Settings API Saas Integration](https://github.com/appsmithorg/appsmith/issues/13021)
    1. Everything related to the CMS URL Redirects commands.
5. [17817 - [Docs]: #11983 [Feature] HubSpot Files API Saas Integration](https://github.com/appsmithorg/appsmith/issues/17817)
    1. Everything related to the Files commands.
6. [17818 - [Docs]: #11982 [Feature] HubSpot CRM API Saas Integration](https://github.com/appsmithorg/appsmith/issues/17818)
    1. Everything related to the CRM commands.
7. [17819 - [Docs]: #11984 [Feature] HubSpot CMS HubDB API Saas Integration](https://github.com/appsmithorg/appsmith/issues/17819)
    1. Everything related to the CMS HubDB commands.

**Comment by danciaclara** [comment] 2023-06-07 05:42
Duplicate of [1280](https://github.com/appsmithorg/appsmith-docs/issues/1280)

**Closed** 2023-09-13 06:00 UTC
Labels: Documentation, potential-duplicate, User Education Pod
