### ISSUE TITLE
[Enhancement] [Api] Option to omit a get param if the value if not defined

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5375] opened 2021-06-24 05:03 UTC
## Summary
For a get api, add an option to omit get param if the value if not defined

## Additional Context
Quoting from discord:
```
on the api create form, if we add a param, it automatically appends = sign to the key. Can we have a workaround if no value is defined then no = sign is added
```

**Comment by Nikhil-Nandagopal** [comment] 2021-08-23 09:49
Duplicate of #5756

**Closed by Nikhil-Nandagopal** 2021-08-23 09:49 UTC
Labels: Enhancement, API pane, Actions Pod, Low
