### ISSUE TITLE
[Bug]: Trying to leave an organization throws an internal server error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17987] opened 2022-10-31 09:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

leaveWorkspaces endpoint returns a 500 when user tries to leave a workspace. Unable to repro this on prod since exact steps is unknown.

### Steps To Reproduce

1. Unable to leave a few shared workspaces and get an internal server error from the `users` API `leaveWorkspace` endpoint `PUT` call

![image](https://user-images.githubusercontent.com/79509062/198969552-da7de47d-a31b-4f67-b9da-f1048b692f73.png)

### Version

Cloud

**Comment by trishaanand** [comment] 2022-10-31 15:20
This is a duplicate of https://github.com/appsmithorg/appsmith/issues/17235. Closing this.

**Closed by trishaanand** 2022-10-31 15:20 UTC
Labels: Bug, Duplicate, High, Release, Needs Triaging, Release Blocker, Organization
