### ISSUE TITLE
[Bug] Unnecessary scroll bars in Table Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3249] opened 2021-02-26 16:50 UTC
On chrome and Firefox, I always get scrolbars in tables, on Firefox even horizontal ones, although there is no scroll needed since the table has pages. 

![image](https://user-images.githubusercontent.com/48994518/109291933-ea9bbf80-7829-11eb-8f00-d54bdf089a65.png)

This is even happening if the table has only 1 line for example. 
I would be nicer to not have these scrollbars.

_Originally posted by @hawisizu in https://github.com/appsmithorg/appsmith/issues/3248#issuecomment-786575010_

**Comment by Nikhil-Nandagopal** [comment] 2021-03-03 07:04
Another User raised this issue today on email

**Comment by riodeuno** [comment] 2021-03-22 10:50
Duplicate of #2895. Closing this, as this issue will be fixed in the PR for #2895

**Closed by riodeuno** 2021-03-22 10:50 UTC
Labels: Bug, Low, Low effort, Table Widget, UI Building Pod, Widgets

**Comment by arjunsriva-woven** [comment] 2022-04-01 07:41
hey
We've encountered this issue while creating table with buttons, steps to reproduce: 

1. create a new empty app
2. add table widget
3. make it wider than necessary
4. deploy 
5. table scroll sideways even though the table is wide enough

Observed on : Chrome-Mac
