### ISSUE TITLE
[Bug]: Importing from Git Repository shows uncommitted changes randomly in Master

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18776] opened 2022-12-08 08:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in GitImport_spec cypress test, when an app is imported from git, on creating new branch from it and making changes and committing those changes gives following error: 
<img width="1434" alt="Screenshot 2022-12-08 at 1 54 46 PM" src="https://user-images.githubusercontent.com/80334441/206396288-42c85df1-090e-4b45-902f-a3c3760d97f9.png">

### Steps To Reproduce

1. Import an app from GIt.
2. Create a new branch ChildBranch
3. Add some actions, and commit and push changes.
4. Merge the changes to master.
5. Observe the error.

### Version

https://release.app.appsmith.com

**Comment by Aishwarya-U-R** [comment] 2022-12-08 10:53
We are skipping these cases from CI runs since its costing more to re-run these cases every PR - minimum twice or thrice before passing.
Cc: @yatinappsmith @AnaghHegde

**Comment by AnaghHegde** [comment] 2022-12-09 05:00
Is this reproducible locally? Or is this only on CI?

**Comment by Aishwarya-U-R** [comment] 2022-12-09 05:11
Only in CI - we have tried to give a script fix - will monitor few more runs & update here1

**Comment by Aishwarya-U-R** [comment] 2022-12-12 05:57
@AnaghHegde - Script fix (adding wait time after import) did not help & this still happens & can be seen between 1:42 to 1:55 seconds in attached video where - it shows pending changes on master in 2nd case & hence 4th case failing to merge!
Cc: @yatinappsmith 

https://user-images.githubusercontent.com/91450662/206970690-810ecd1f-6ea5-4c11-982e-e7119bf8ce0b.mp4

**Comment by ramsaptami** [comment] 2023-01-06 07:31
I have seen this happen on an app but not reproducible every time. Will capture logs and share when I do see it though

**Comment by AnaghHegde** [comment] 2023-01-09 05:49
@ramsaptami @Parthvi12 Is there any specific scenario you know that will help me in reproducing this error?

**Comment by ramsaptami** [comment] 2023-01-09 06:35
Have multiple branches and try to switch between branches while making changes and committing those changes.
What I've seen is that after committing and navigating to `merge` tab, it shows there's an uncommitted change, and then when we toggle to `Commit` tab, then all of a sudden there's a pending change with no change log on that tab

**Comment by Aishwarya-U-R** [comment] 2023-01-09 06:46
Can also try with importing an app from Git with datasources. Thats the scenario CI throws this error.

**Comment by AnaghHegde** [comment] 2023-01-09 10:06
@ramsaptami Do you have any repo where i can see this change? If not next time you face this, could you commit the changes with a unique commit message and share it with me?

**Comment by ramsaptami** [comment] 2023-01-09 12:27
It's not consistent but I'll try to grab logs the next time. It happens quite often on new git repo committing to master

**Comment by AnaghHegde** [comment] 2023-06-23 10:36
Closing this issue. Feel free to reopen if this is reproducible.

**Closed by AnaghHegde** 2023-06-23 10:36 UTC
Labels: Bug, Needs Triaging, Git Version Control, medium, Git Pod
