### ISSUE TITLE
[Bug]: When the origin module name gets changed all the references to that module don’t get refactored

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#34492] opened 2024-06-26 10:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the origin module name gets changed all the references to that module don’t get refactored

### Steps To Reproduce

.

### Severity

Medium (Frustrating UX)

### Version

Cloud/Selfhosted

**Comment by subrata71** [comment] 2024-06-27 06:26
Duplicate of https://github.com/appsmithorg/appsmith/issues/33465

**Closed** 2024-07-10 05:30 UTC
Labels: Bug, Needs Triaging, Deploy Preview, Medium, Packages pod, Module creator
