### ISSUE TITLE
[Bug]: 400 error is returned on a newly defined JS function name

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14755] opened 2022-06-23 05:55 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

A newly defined function displays a message stating object and function name combination already exists when it does not.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/scratch-pad/automation-test-cases-62987963c43c3d0bd6572185/edit/jsObjects/62b3f8abdd56222d3f8039b0?editName=false) location and observe the toast message and the browser logs display error for a newly defined function

![image](https://user-images.githubusercontent.com/79509062/175225518-b05e4d79-d4b3-423e-ae68-c18f5cd4c228.png)

### Version

Cloud

## Test Plan
- [ ] [[Test Case]: verify that there is no 400 error appear on defining a new JS function name](https://github.com/appsmithorg/TestSmith/issues/1925)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5rtvw)

**Comment by ohansFavour** [comment] 2022-06-27 07:47
This seems like a BE issue. When we fetch JS Collections for the application, the affected JS Object, **TC4**  returned from the server has only 1 action (**TC4.dog**), whereas there are multiple actions in the JS Object.
When we then try to update the js collection with new actions (detected after we `evaluateTree`), an error is thrown with the message  "`TC4.cat` is already exists."

The question is "if it is already present, why aren't we getting it when we fetch the js collection?"

cc: @nidhi-nair

**Comment by subrata71** [comment] 2022-06-28 04:56
Can you please share the app with me? @ramsaptami

**Comment by ramsaptami** [comment] 2022-06-28 06:09
I'm not able to repro this consistently. Only random. But the app attached to the issue shows the issue. I've also shared the app with you @subrata71

**Comment by subrata71** [comment] 2022-06-28 11:04
## What I tried

- Tried to reproduce by creating JS object in different environments {local, release, prod} but I wasn't able to reproduce

- Forked the application that Saptami shared and found that the issue exists in that forked app too.

- Exported that application and imported in local environment. The issue also exists in local after being imported.

- Saptami confirmed that the issue is not easily reproducible and it seems to appear intermittently.

- There's a PUT request taking place every time I click on the page which has usage to that JS object. Is it expected to trigger a PUT request when a page is clicked in edit mode?

  Request URL: https://release.app.appsmith.com/api/v1/collections/actions/62ba8d7eca2698047034f59c
  Request Method: PUT
  Status Code: 400 Bad Request


- Whenever the following method returns true an error message like {} already exists. Please use a different name is thrown.

`LayoutActionServiceCEImpl.isNameAllowed`

It returns true in the following cases

1. If any unpublished action under this page contains the fully qualified name of the given JS object
2. If any widget under this page contains the fully qualified name of the given JS object
3. If any action collection under this page contains the fully qualified name of the given JS object


### Current workaround

1. Rename the JS object to something else which doesn't conflict with any of the existing {action names, widget names, collection names} which creates this issue
2. Now revert back to the previous name of the JS object
3. You should see the issue doesn't seem to prevail


### Next course of action
We need to figure out on which instances the following API is triggered from FE
`/api/v1/collections/actions/{actionId}`

**Comment by Nikhil-Nandagopal** [comment] 2022-06-28 16:32
@subrata71 But ideally this should not matter since the function name should be scoped by the name of the JSObject and hence does not need to be unique across widgets and other queries right?

**Comment by Privatecoder** [comment] 2022-08-26 21:21
Any updates on this?

I am experiencing the same issue in an app I use in production. I can also confirm @subrata71's [steps](https://github.com/appsmithorg/appsmith/issues/14755#issuecomment-1168576393) (fork, export/re-import) don't fix this and the issue seems to occur randomly after a while.

However: I did experience a much larger latency between my Browser and the Server – between the last updates that I deployed without editing any App so I just realized it some days ago – which sometimes results in "the server took too long to respond" and seems to favorably trigger this.

**Comment by rlnorthcutt** [comment] 2022-10-07 14:27
I've also run into this a few times while building the Hacktoberfest app. I assumed it was related to some type of caching of the JS object, so I ignored the first one for a few days. Finally, I renamed the method and updated my code to get the error to go away.

Now its happening on a different method in a different page. I've confirmed that there isn't a duplicate method name both in my code AND in the export. There are no errors running the JS object or in the IDE, but this error message pops up over an over (it seems to be when the JS object is updated/saved).

I could ignore the warning, BUT it is now not showing my new methods when I try to bind them to a button. The list of methods on an object doesn't show the new ones. I can manually add them, and it works... but super annoying.

![image](https://user-images.githubusercontent.com/673633/194577320-227f4a28-e650-46aa-ae36-bf69149db2d6.png)

![image](https://user-images.githubusercontent.com/673633/194577499-92c3e83e-d56b-4000-8ae8-a673466e08e2.png)

**Comment by rlnorthcutt** [comment] 2022-10-07 14:29
It must be related to some type of cache somewhere. I believe it happens when I _move_ a method inside my object during refactoring.

**Comment by ramsaptami** [comment] 2022-10-07 19:41
Thanks for adding in your observations @rlnorthcutt.
I also see a "cannot reproduce" label here and wanted to add that trying to copy paste an existing function and then trying to rename the function throws this error for the renamed function

**Comment by ramsaptami** [comment] 2022-10-19 16:57
Don't think this has been resolved. I still see this error show up on the sample app attached in the description hence reopening it

**Comment by subrata71** [comment] 2022-10-19 18:05
I found it happening in a few other apps too.

**Comment by subrata71** [comment] 2022-10-27 09:13
(WIP)
The following query returns a few documents which shouldn't return any document ideally.

`{"pluginType": "JS", "unpublishedAction.collectionId" : {$exists: false}, "unpublishedAction.deletedAt" : {$exists:false}}`

It's expected that the actions inside a JS collection should always have a `collectionId` if it's not deleted. (But even if it's deleted the`collectionId` should persist).

**Comment by ramsaptami** [comment] 2022-11-23 09:08
Verification blocked since there's another area of code that's triggering this error
[Slack thread ](https://theappsmith.slack.com/archives/CPQNLFHTN/p1669142481685559)for more context

**Comment by subrata71** [comment] 2022-12-23 05:37
I am closing this issue as it solves one reason which causes this issue. And I will create a new one addressing the other reason.
cc: @ramsaptami

**Closed by subrata71** 2022-12-23 05:37 UTC
Labels: Bug, QA, High, Production, Cannot Reproduce Issue, Core Query Execution, JS Objects, FE Coders Pod, BE Coders Pod, QAVerificationBlocked, Data Platform Pod
