### ISSUE TITLE
[BUG] MySQL Connection doesn't work

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#589] opened 2020-09-19 10:38 UTC
## Description

Unable to connect my MySQL database on a shared hosting server. Enabled remote access to the IP as specified in the data source page. 

### Steps to reproduce the behavior:
1. Click on + to add a data source
2. Select "MySQL"
3. Enter the host address, database name, authentication information (username and password)
4. Click test and the error throws up 
![Screenshot_2](https://user-images.githubusercontent.com/4999463/93665179-0ee0bc80-fa92-11ea-965e-4a58bb1f8ca2.png)

PluginExecution failed with error Error connecting to MySQL: The server time zone value 'PDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser Google Chrome (v. 85.0.4183.102)

#### Server Information

- Apache Version | 2.4.46
- PHP Version | 7.2.33
- MySQL Version | 10.2.33-MariaDB
- Architecture | x86_64
- Operating System | linux
- Perl Version | 5.16.3
- Kernel Version | 3.10.0-962.3.2.lve1.5.24.9.el7.x86_64

**Comment by sharat87** [comment] 2020-09-23 11:13
Hello @harishkotra, a way to address to problem has been released into Appsmith cloud and should be available to self-hosted instances as a release is created soon.

The problem is that the timezone set on the MySQL server is something that the JVM (Appsmith server) doesn't recognize unambiguously. So, the solution is the override the server timezone. We've added a new field in the MySQL datasource configuration UI at the bottom, in a section called "MySQL Specific Parameters" where you can set this override.

In your particular case, `PDT` is an ambiguous timezone and if the override field I mentioned above is set to something like `PST` or `UTC`, the connection should go through.

Let us know if you face further problems on this.

**Closed by sharat87** 2020-09-23 11:13 UTC
Labels: above-them, bug
