### ISSUE TITLE
[Bug]: Modal widget with expanded borders, on deploy, overlaps with the application page tabs

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15031] opened 2022-07-05 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On increasing the size of a modal widget, and deploying the app which has a number of pages, the UI of modal widget seems to overlap with the Pages. 

### Steps To Reproduce

1. Drag and drop a modal widget on one of the pages of an application, with about 7 / 8 pages already
2. Increase its height such that it reaches its max height to the top of the canvas. 
3. Add a button to the canvas, and ensure that on click of this button the modal widget is invoked.
4. Deploy the application

You can see that the modal widget overlaps the Pages tabs on top of the screen. 
The behavior on Prod is different. 
<img width="1412" alt="Modal_Prod" src="https://user-images.githubusercontent.com/101863839/177370208-ad71d0a5-3ea0-4daa-833d-6d2d31599073.png">
<img width="1045" alt="Modal_Release" src="https://user-images.githubusercontent.com/101863839/177370229-746c3bf1-ac1e-4690-bd3a-12e6dfd0634c.png">

### Version

Release

**Comment by Nikhil-Nandagopal** [comment] 2022-07-06 07:23
Duplicate of #14849

**Closed by Nikhil-Nandagopal** 2022-07-06 07:23 UTC
Labels: Bug, Modal Widget, App Viewers Pod, Needs Triaging, medium
