### ISSUE TITLE
[Feature]: props not passed to children of table. 'currentRow' not available on children of 'Menu button'

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#31598] opened 2024-03-08 02:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

on a table if a cell is marked as a 'menu button' the menu option buttons do not have access to 'currentRow'
![Screenshot 2024-03-07 at 8 36 38 PM](https://github.com/appsmithorg/appsmith/assets/1387859/a3fe8480-36ee-43eb-bba4-77d8441b489d)

### Why should this be worked on?

It is extremely likely that an operation on the menu button needs to be performed on the currentRow.

yes, we can access the selectedRow but that is not always the same as the currentRow which results in the incorrect row being selected.

**Comment by Nikhil-Nandagopal** [comment] 2024-03-08 07:03
This is a duplicate of #26052

**Closed by Nikhil-Nandagopal** 2024-03-08 07:03 UTC
Labels: Enhancement, Community Reported
