### ISSUE TITLE
[Bug]: Issue When copying a listWidget from modal to another

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#11013] opened 2022-02-09 03:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Issues related to modal
(1) When we copy a listwidget from a modal to another the currentItem property will be undefined.
(2) in a modal form the select widget have problems with manual configurations of items. it reports incorrect line break.

Issue reported by a discord user.
https://discordapp.com/channels/725602949748752515/940626765636861953

### Steps To Reproduce

When we copy a listwidget from a modal to another the currentItem property will be undefined

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment] 2022-02-18 10:56
@leotom2000 Could you drop a video to help us understand how to reproduce this issue.

Thank you.

cc @wmdev0808

**Comment by leotom2000** [comment] 2022-02-18 12:06
![image.png](https://images.zenhubusercontent.com/61a0a7dfb7ec239be6d85573/39d442c3-5b82-4f67-b92d-04c741cd7b65)

This was an issue raised by a discord user, he has shared this image,
Please let know if this info is okay for us to test.
Else we need to ask for more info

**Comment by leotom2000** [comment] 2022-02-22 05:06
![image.png](https://images.zenhubusercontent.com/61a0a7dfb7ec239be6d85573/7a0d1e85-a094-4c07-871e-373fcfa9ce36)

**Comment by leotom2000** [comment] 2022-02-24 06:58
The above is screenshot from the users system
I tried a simple component, but was working fine.
For list widget, I have not tried to reproduce, 
I can check and update.

**Comment by Tooluloope** [comment] 2022-02-24 09:06
Closing this off.
Couldn't reproduce

@vivekverma2312 Could you help verify

**Closed by Tooluloope** 2022-02-24 09:06 UTC
Labels: Bug, App Viewers Pod, High, UI Building Pod, List Widget

**Comment by btsgh** [comment] 2022-03-24 05:29
Created Two Modals. (Modal1 and Modal4)
Added a list widget (List2) in Modal1
Copied this list widget into Modal2
Was able to copy without any errors, with the List2Copy and its corresponding widgets getting created successfully under it.
