### ISSUE TITLE
[Bug] the auto height property of the container fails to kick-in in mobile viewport when you copy paste widgets inside it

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22725] opened 2023-04-25 12:23 UTC
https://www.loom.com/share/3725cb5b4d324830a80c26b3b9f0f3bd

**Comment by aswathkk** [comment] 2023-04-27 06:00
Seems like this is getting fixed in #22716

**Comment by aswathkk** [comment] 2023-05-11 09:35
Unable to reproduce this in release

**Closed** 2023-05-15 10:47 UTC
Labels: Mobile Pod, Responsive Widget
