### ISSUE TITLE
[Bug]: confirmation pop doesn't appear in old application but works in new org

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14626] opened 2022-06-17 07:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user adds an API and navigates to the setting page to select the confirmation pop but on RUN in the API pane the pop-up is displayed to the user when binded to the Table on the canvas it is observed that COnfirmation Pop up does not appear.

### Steps To Reproduce

1) Add an API
2) Navigate to the Setting page
3) Tick on the "Request confirmation before running API"
4) RUN the API in the pane and observe that the Pop up appears
5) Bind the API to the table 
6) Now refresh the page and
 observe the confirmation pop-up is not displayed and the table does not get populated 

Note : WHen done on the new organization and new application the confirmation pop-up is displayed 

### Version

Release

**Comment by AmanAgarwal041** [comment] 2022-06-17 12:58
Unable to reproduce this issue. So removing the `Release Blocker` label for now and waiting for the progress of reproducing this issue.

**Comment by sumitsum** [comment] 2023-07-26 07:51
As mentioned [here](https://github.com/appsmithorg/appsmith/issues/14626#issuecomment-1158846865), the issue was not replicable earlier, and no new instance has been reported so far. Hence closing it.

**Closed by sumitsum** 2023-07-26 07:51 UTC
Labels: Bug, Low, BE Coders Pod, REST API plugin, Integrations Pod
