### ISSUE TITLE
[Bug] Link for a resolved comment thread notification does not show the comment

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5811] opened 2021-07-13 05:25 UTC
## Description
Link for a resolved comment thread notification does not show the comment. Since the `show resolved comments` filter is not set

1. Create an app
2. Invite a new user
3. Add a comment and tag the new user
4. Resolve the comment
5. Login as the invited user and click on the comment notification
6. The thread is not shown since the resolved filter is not set

**Comment by nayan-rafiq** [comment] 2021-08-17 04:50
@Nikhil-Nandagopal Need some idea on what we can do in this case. IMO, showing a toast message "Comment not found. It might be deleted or hidden due to resolved"

**Comment by Nikhil-Nandagopal** [comment] 2021-08-17 05:38
We should take the user to the editor with the resolved filter auto applied

**Comment by RakshaKShetty** [comment] 2021-09-06 13:54
reopening the issue one scenario is missed in this Attaching the video for reference
https://www.loom.com/share/281acc419d004b3a91e6b189f9bd0d5c

**Comment by pranavkanade** [comment] 2021-09-09 10:27
@RakshaKShetty tested above scenario on local and release envs working fine for me. Could you please confirm once again if the bug is still there.

https://user-images.githubusercontent.com/13262095/132669705-690a4f4c-3b8c-4995-a6a9-c0d039440a95.mov



https://user-images.githubusercontent.com/13262095/132669633-0e0f9cb5-fa28-4b9c-af25-a3f94c062ddc.mov

**Comment by RakshaKShetty** [comment] 2021-09-10 07:17
The issue is fixed closing it

**Closed** 2021-09-10 07:17 UTC
Labels: Bug, Needs Triaging, Platform, Collaboration
