### ISSUE TITLE
[Bug]: The close icon on the Page Settings box in Page Properties UI looks disabled for Home Page.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18306] opened 2022-11-21 08:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Page Properties UI, when we click on the settings icon for the Home Page,  The Close icon seems to be disabled, though it is actually clickable. 

### Steps To Reproduce

1. On the Page Properties page, for a Page that is set as Home Page (say Page1), click on the Settings icon
2. The Close icon seems to be disabled, though it is actually clickable. 

<img width="401" alt="Screenshot 2022-11-21 at 1 32 28 PM" src="https://user-images.githubusercontent.com/101863839/202997414-c35335b8-bc4c-48d8-90bc-028311c610b6.png">

### Version

Production

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 07:51
Duplicate of #18310

**Closed by Nikhil-Nandagopal** 2024-03-06 07:51 UTC
Labels: Bug, Pages, Low, Production, Needs Triaging, IDE Pod
