### ISSUE TITLE
[Bug]: [intermittent ]The G sheet Authorisation fails when user tries to authorise  

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#23449] opened 2023-05-17 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1.Gsheet breaks on user tries to authorize the data source

### Steps To Reproduce

1. Import a json app that has gsheet datasource
2. now try to authorize the app the Users are navigated to "https://cs.appsmith.com/api/v1/integrations/oauth/authorize?appsmithToken=eyJhbGciOiJIUzUxMiJ9.eyJwbHVnaW4iOiJnb29nbGUtc2hlZXRzLXBsdWdpbiIsImlhdCI6MTY4NDMyMTEwNCwiZXhwIjoxNjg0MzIxNDA0LCJzdWIiOiIyY2YzNGFkZi1lZTg4LTRlOWEtOTcxMi03NDhlM2JlZDJkNWUifQ.ONHRjiohpsrCF9juo_6zqjLQ-L7KuKfsXQWIMdcXBcpHL488-PGxtOntJNzHk-KdoXZrteSXGTGh95M4CzLGcA"
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/098caf26-aaf1-4e0c-b898-0f1494d64552">
3. the authorization fails

### Environment

https://ee-1483.dp.appsmith.com

### Version

v1.9.20

**Comment by RakshaKShetty** [comment] 2023-05-17 11:57
As per discussion changing the priority to high, as it exits in the prod

**Comment by sneha122** [comment] 2023-05-17 12:52
@prapullac @btsgh This issue is intermittently occurring as the DP is intermittently pointing to production cloud-services url. And issue seems to be with how DP was generated. Right now I am not able to reproduce it even on DP

**Comment by prapullc** [comment] 2023-05-17 12:56
@sneha122: Closing the above issue as per the above comment and accepting the issue occurance is intermittent

**Closed** 2023-05-17 12:57 UTC
Labels: Bug, High, Needs Triaging, Google Sheets, BE Coders Pod, Integrations Pod
