### ISSUE TITLE
[Feature] Define google sheet access on the user who launch the app. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4589] opened 2021-05-20 06:35 UTC
## Summary
Requested by community: 
```
Hi, is there a way to define Google sheet Access on the user who launch the app, maybe by passing his mail ?
```

**Comment by Nikhil-Nandagopal** [comment] 2021-08-16 08:44
Duplicate of #3313

**Closed by Nikhil-Nandagopal** 2021-08-16 08:44 UTC
Labels: Enhancement, Actions Pod, community, Actions, Google Sheets
