### ISSUE TITLE
[Bug]: "Reset on submit" is not working in Input Widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11330] opened 2022-02-22 05:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After adding some input and submit (press enter), the old text is not getting removed even if Reset on Submit option is Enabled
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bb306428e45341b3a7900bcd522b9353-00001.gif)](https://www.loom.com/share/bb306428e45341b3a7900bcd522b9353)

### Steps To Reproduce

1. Add input widget to canvas
2. Enable Reset on Submit option from property pane
3. Add some text and hit enter
4. Observe that older text is still present in the widget

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-02-23 05:09
Hey @sbalaji1192 this is not working for me in production as well. It's working for currency widget but not for the input widget, can you check this?

Also can we add this in our regression cases if it's not there.

**Comment by sbalaji1192** [comment] 2022-02-23 05:43
@chandannkumar @dilippitchika Not able to repro on release and prod - https://www.loom.com/share/88866ea7055a485ebfeba8cd1ae156c0

**Comment by chandannkumar** [comment] 2022-02-23 06:23
It is now observed that Text gets reset on submit if **onSubmit** action is handled and if onSubmit is not handled then text is unable to reset on Pressing Enter, though Reset on submit is enabled

@dilippitchika  is this a expected behavior? Does Reset on Submit have any limitations or dependent on any other actions?

**Comment by dilippitchika** [comment] 2022-02-25 05:09
This is the expected behavior, the problem was weirdly even that was not working for me, when I was demoing. 

Closing this issue for now as it's not reproducible anymore.

**Closed by dilippitchika** 2022-02-25 05:09 UTC
Labels: Bug, Input Widget, App Viewers Pod, High, UI Building Pod, Needs Triaging, UI Builders Pod
