### ISSUE TITLE
[Bug]: Application is randomly throwing Error toasts on navigating between Deploy & Edit pages

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#24174] opened 2023-06-07 06:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in CI , where on navigating from deploy page to edit page and vice versa, application is throwing `Cannot read properties of undefined (reading 'responseMeta')` error toast:
And sometimes - There was an unexpected error toast :

![Screenshot 2023-06-07 at 10 29 29 AM](https://github.com/appsmithorg/appsmith/assets/91450662/cf7b8f45-6f16-4eb9-8d27-53054e9d4cca)
<img width="1488" alt="Screenshot 2023-07-07 at 3 53 18 PM" src="https://github.com/appsmithorg/appsmith/assets/91450662/bcb105dc-cd5e-4f57-9f66-a91dafde333f">

### Steps To Reproduce

1. Login to Appsmith
2. Create an app
3. Publish the app
4. Navigate back to edit page

### Environment

Release

### Issue video log

https://github.com/appsmithorg/appsmith/assets/119562824/eb64a836-9ade-4e2f-8632-40d9248d5e80

### Version

Self hosted

**Comment by Vijetha-Kaja** [comment] 2023-06-07 06:23
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/35724/test-results/ff01198e-f822-4bb8-9bdc-73550caa4fe6) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11673199/28_ci-test-limited.ci-test-limited.27.txt)

**Comment by Vijetha-Kaja** [comment] 2023-06-12 06:42
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7584/test-results/f719beee-ec9c-4a6a-984a-b24297cb6cf0) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11718828/4_ci-test-limited.ci-test-limited.3.txt)

**Comment by Vijetha-Kaja** [comment] 2023-06-22 08:20
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7854/test-results/1f3fbf6d-d9ff-4d06-8a1d-15f1c0cff459) with above failure

**Comment by Vijetha-Kaja** [comment] 2023-06-30 08:59
@somangshu we don't know the root cause yet, Please feel free to re-assign this to relevant folks

**Comment by Aishwarya-U-R** [comment] 2023-07-04 18:19
[Recent run logs](https://cloud.cypress.io/projects/eyxvp8/runs/37088/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression%2FServerSide%2FGenerateCRUD%2FMySQL2_Spec.ts%22%2C%22value%22%3A%22%5B%5C%2299246b6f-9e85-4d51-b84c-63bd73367af7%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D)

**Comment by Aishwarya-U-R** [comment] 2023-07-04 18:20
@somangshu - We are seeing this when navigating from View Mode to Edit page. So we thought it was App viewers. Can you please let know whom should we re-assign this to instead?

**Comment by somangshu** [comment] 2023-07-05 07:33
@Aishwarya-U-R @Vijetha-Kaja to debug the problem better can you help me understand the reproducible steps from the cypress test that is failing. 
I tried doing it, but did not succeed.
My understanding is that the application crashes, cause I dont see any of the elements load on the canvas. Maybe something to with the canvas in that case. 

cc @marks0351 any idea?

**Comment by Aishwarya-U-R** [comment] 2023-07-07 10:25
Recent run [error logs reference](https://cloud.cypress.io/projects/n14p1y/runs/8104/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_campaign=view%20spec&utm_medium=failed&utm_source=slack) - for There was an unexpected error toast.

**Comment by Vijetha-Kaja** [comment] 2023-07-25 14:24
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/37766/test-results/930ba230-7a0a-4452-81ad-600890a2ece1) with above failure

**Comment by Aishwarya-U-R** [comment] 2023-08-02 06:47
[Recent run](https://cloud.cypress.io/projects/n14p1y/runs/8750/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D) - There was an unexpected error - when navigating from Edit to Deploy page:

<img width="1502" alt="Screenshot 2023-08-02 at 12 17 12 PM" src="https://github.com/appsmithorg/appsmith/assets/91450662/1575ba53-e0cc-4c8c-a518-83f89e29371e">

**Comment by akash-codemonk** [comment] 2023-09-08 08:35
This seems to be happening on CI only. If there are reproducible steps this can be picked up. To debug these failures on CI we will need more info like network logs and console logs. https://github.com/appsmithorg/appsmith/issues/26006

**Comment by Vijetha-Kaja** [comment] 2023-09-13 13:46
Recent [run](https://internal.appsmith.com/app/cypressdashboard/specdetails-64ec3df0c632e24c00764939?branch=master&specID=682139&testsstatus=failed) with above failure

**Comment by Aishwarya-U-R** [comment] 2023-09-18 07:53
Adding logs from [recent run](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6202210849&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)
[dockerlogs (2).zip](https://github.com/appsmithorg/appsmith/files/12645609/dockerlogs.2.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-18 08:03
Another [run failure](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6218820368&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs 
[dockerlogs (2).zip](https://github.com/appsmithorg/appsmith/files/12645685/dockerlogs.2.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-18 08:05
Another [run failure](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6217932804&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs
[dockerlogs (2).zip](https://github.com/appsmithorg/appsmith/files/12645714/dockerlogs.2.zip)

**Comment by Vijetha-Kaja** [comment] 2023-09-18 12:41
Another failure [run](https://internal.appsmith.com/app/cypressdashboard/specdetails-64ec3df0c632e24c00764939?specID=878154&testsstatus=failed) 
[docker_logs.zip](https://github.com/appsmithorg/appsmith/files/12647802/logs_522626.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-19 05:08
Another [failure run](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6226707476&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/12656068/dockerlogs.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-19 08:27
Another[ latest failing run](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6231931753&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs 
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/12657543/dockerlogs.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-19 12:03
Multiple specs failing with sidebar not visible & app not loading with empty toast - [Run1](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6233387793&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)
[Run2](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6233711768&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)  with logs  
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/12659506/dockerlogs.zip)

**Comment by Aishwarya-U-R** [comment] 2023-09-19 12:30
[Side bar not loaded run ](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6234375618&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)issue with emtpy toast & logs 
[dockerlogs (1).zip](https://github.com/appsmithorg/appsmith/files/12659870/dockerlogs.1.zip)

**Comment by Aishwarya-U-R** [comment] 2023-10-06 08:19
[Recent run with this fialure after logs added](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6428382607&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)
[cypress-console-logs (1).zip](https://github.com/appsmithorg/appsmith/files/12828639/cypress-console-logs.1.zip)

**Comment by akash-codemonk** [comment] 2023-10-06 09:13
@Aishwarya-U-R As mentioned earlier I think it's better close this issue, the loading issue is tracked in https://github.com/appsmithorg/appsmith/issues/27489 for clarity.

Closing this let me know if you have any concerns.

**Comment by Aishwarya-U-R** [comment] 2023-10-06 09:58
@akash-codemonk - what you have created is a task that will account for fixing this. This bug cannot be closed - until the bug itself is addressed.

**Comment by Aishwarya-U-R** [comment] 2023-10-09 07:38
[One more recent Internal server error run & logs](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6451033088&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail) & logs attached.
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/12843557/dockerlogs.zip)

**Comment by Aishwarya-U-R** [comment] 2023-10-13 07:48
[Recent run](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?workflowId=6504709400&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs 
[cypress-console-logs (2).zip](https://github.com/appsmithorg/appsmith/files/12890850/cypress-console-logs.2.zip)

**Comment by Aishwarya-U-R** [comment] 2023-10-13 12:30
[Anothe run](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6507148430&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with logs attached. 
[cypress-console-logs (3).zip](https://github.com/appsmithorg/appsmith/files/12893487/cypress-console-logs.3.zip)

**Comment by Aishwarya-U-R** [comment] 2023-10-16 11:30
[Latest](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6531428325&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) with instance failures at [22](https://github.com/appsmithorg/appsmith/actions/runs/6531428325/job/17733850853) & [42](https://github.com/appsmithorg/appsmith/actions/runs/6531428325/job/17733856218#step:26:1)

**Comment by Aishwarya-U-R** [comment] 2023-10-17 05:23
[Latest](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6537306234&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) at instance [33](https://github.com/appsmithorg/appsmith/actions/runs/6537306234/job/17751925311) tests CheckBoxGroupTest.ts, TableV1/Table_spec.js, TableV2/TableV2_Switch_spec.js, Text/Text_truncate_spec.js

**Comment by Aishwarya-U-R** [comment] 2023-10-20 08:15
This PR is fixed now, any other error toasts in Applications will be tracked separately.

**Closed by Aishwarya-U-R** 2023-10-20 08:15 UTC
Labels: Bug, Needs More Info, High, Needs Triaging, UI Builders Pod, Generate Page, New Developers Pod, Canvas / Grid, CI impacted
