### ISSUE TITLE
[Feature]: Move away from environment variables and rely on db changes

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#31128] opened 2024-02-14 14:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when a user makes changes in admin settings those changes go into docker.env which inturn goes in as an environment variable. 

Rather, it will be great if we can add required entries into the database and avoid restarts and relying on environment variabls

### Why should this be worked on?

This will help in increased user experience and avoid UN-necessary hassle of maintaining environment variables

**Comment by sharat87** [comment] 2024-02-15 01:49
Duplicate of https://github.com/appsmithorg/appsmith/issues/11855.

**Closed by sharat87** 2024-02-15 01:49 UTC
Labels: Enhancement, Backend, Customer Success
