### ISSUE TITLE
[Bug]-[12]:Cypress Test - Reconnect modal doesn't show all the datasources on importing app from JSON/Git

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#14283] opened 2022-06-03 12:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is being observed in cypress tests , sometimes the reconnect modal doesn't show all the datasources when an app is imported from JSON and sometimes from git too. Causing gitimport tests to fail.

Here ideally there should be 3 datasources
<img width="1434" alt="Screenshot 2022-06-03 at 5 34 31 PM" src="https://user-images.githubusercontent.com/80334441/171850778-275ffe8d-af0f-4998-9ada-d517afd9f907.png">

### Steps To Reproduce

1. Import the application with multiple datasources
2. Reconnect modal should appear
 
Note: This doesn't happens always.

### Version

Release

**Comment by AnaghHegde** [comment] 2022-06-07 06:32
Since we are unable to reproduce the issue locally and the reconnect do not show only one of the datasources in the response, we have decided to log the response for git import API. PR for the same can be tracked here - https://github.com/appsmithorg/appsmith/pull/14325/files#diff-6391484e33a37f063691140dc77c4686d0fcbc344b6ab836cab60ebddc2ce2ddR32

**Comment by vuiets** [comment] 2022-06-10 07:04
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6 |
| Effort (months)  | 0.5 |

**Comment by Parthvi12** [comment] 2022-06-21 06:45
@AnaghHegde 
<img width="1434" alt="Screenshot 2022-06-21 at 12 14 43 PM" src="https://user-images.githubusercontent.com/80334441/174734055-ad9797ce-5519-4aed-9bf5-6773cd2ae6e2.png">

**Comment by AnaghHegde** [comment] 2022-06-22 06:05
This looks like FE issue, server is sending the correct response. Screenshot attached. We can try adding a delay and see if that solves the issue. 
<img width="1352" alt="Screenshot 2022-06-21 at 4 49 16 PM" src="https://user-images.githubusercontent.com/12005551/174955164-0c875c2d-fd55-4448-aa43-95b72e5a2d12.png">

**Comment by AnaghHegde** [comment] 2022-07-18 05:06
@Parthvi12 Adding delay has fixed this and Delete branch tests right? Can we close this issue?

**Comment by Parthvi12** [comment] 2022-07-18 05:12
@AnaghHegde  Yes, its failure rate has gone down. Closing it.

**Comment by AnaghHegde** [comment] 2022-10-12 09:03
@Parthvi12 Can we close this?

**Comment by Parthvi12** [comment] 2023-01-16 04:06
We are seeing this issue again in CI, hence reopening.

**Comment by AnaghHegde** [comment] 2023-03-26 17:08
Since we do not know how to reproduce this, can we close this issue? I guess we are not observing this error on CI anymore.

**Comment by infinitetrooper** [comment] 2023-11-24 10:55
Stale

**Closed by infinitetrooper** 2023-11-24 10:55 UTC
Labels: Bug, Needs Triaging, Git Version Control, Medium, Git Pod
