### ISSUE TITLE
[Feature] A JSON Diff Editor to resolve merge conflicts

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#5649] opened 2021-07-06 14:19 UTC
## Summary

JSON Diff Editor will aim to help users resolve merge conflicts when merging branches using the git sync feature.

## Motivation

Github Diff editor compares line by line which is not an ideal case for comparing JSON files and hence makes it difficult to resolve conflicts.
Even a comma and/or braces position will lead to an unnecessary difference in this kind of editor.

### Information about implementing a JSON Editor.

1. Arrange keys alphabetically for both JSON with standard spacing. (Also following this while saving JSON file)
2. Now, we have 2 substeps 
    1. Find the difference and 
    2. Show it in a diff editor.
    
Ideally, the same key from both JSON should be in the same line in the editor, irrespective of the values or other keys not being present.  ( Compare only keys 1st )
For example:-
```
1. {
2.   "a": "1",
3.   "b": {
4.           "a": "wa", 
5.           "name" : "qq"
6.         }
7.   "c": "hello",
8. }
```

```
1. {
2.   "a": "1",
3.   
4.
5.
6.
7.   "c": "hello"
8. }
```

https://jsoncompare.org/ also handles this.
Also, it is better to hide the values of the objects by default which are at LEVEL 2 depth, and on user click only show the difference of those objects.

3. Compare the values and show the difference if the value differs.

To find the JSON difference there are options like https://www.npmjs.com/package/json-diff which gives the complete difference in its own format that can be manually handled to control how to render it. This is an ideal way of doing it.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6b0ng)

**Comment by Rishabh-Rathod** [comment] 2021-07-06 14:25
Sharing my experience below while building DiffyCURL's JSON diffEditor.

In [DiffyCURL](https://rishabh-rathod.github.io/DiffyCurl/), I used `react-ace`'s DiffEditor component ([DEMO](https://securingsincity.github.io/react-ace/diff.html)) which does both finding differences (but like GitHub line by line compare) and rendering it.

It had many issues for comparing JSON.
Even basic rearranging according to the key was not handled, so I wrote logic to do that. Even then there were many issues that I didn't resolve at that time.

For example, Even now in DiffyCURL, it is comparing line by line which leads to confusion as shown in the below image.

<img width="1376" alt="Screenshot 2021-07-06 at 6 13 56 PM" src="https://user-images.githubusercontent.com/23132741/124616692-ecd6f000-de93-11eb-8a43-6abfd46f955b.png">

**Comment by somangshu** [comment] 2021-07-06 14:32
@Rishabh-Rathod does #3360 fall under the same category

**Comment by Rishabh-Rathod** [comment] 2021-07-06 14:45
> @Rishabh-Rathod does #3360 fall under the same category

No, I don't think both these issues are related. #3360 is about having a JSON Widget for the user to visualize data inside their appsmith application, which they can drag and drop to canvas and connect data to.

Whereas this issue/feature to add JSON Diff editor is related to #3199 Git sync feature where on merge conflicts, the user might need to compare JSON files and for that, a JSON diff Editor will be helpful.

@Nikhil-Nandagopal correct me if I am wrong.

**Comment by somangshu** [comment] 2021-07-06 14:53
Great stuff @Rishabh-Rathod 😄, This sounds really helpful the the git sync feature.

**Comment by Nikhil-Nandagopal** [comment] 2024-01-04 11:55
Duplicate of #10250

**Closed by Nikhil-Nandagopal** 2024-01-04 11:55 UTC
Labels: Enhancement, Frontend, Git Version Control, Git Pod
