### ISSUE TITLE
[Bug] Cloned an app and the original one isn't available.

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1707] opened 2020-11-12 07:44 UTC
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]

**Comment by Nikhil-Nandagopal** [comment] 2020-11-12 12:47
@trishaanand this is related to the issue uolo faced

**Comment by trishaanand** [comment] 2020-11-17 08:35
@Nikhil-Nandagopal : Yes. But unfortunately haven't been able to reproduce this.

**Comment by Nikhil-Nandagopal** [comment] 2020-11-17 09:31
@trishaanand closing for now. Can we add some logs for self-hosted instances? Maybe we can just write our console logs to a file?
@mohanarpit

**Comment by trishaanand** [comment] 2020-11-19 08:44
Reopening this issue because it was reproduced on the cloud deployment of Appsmith.

**Closed** 2020-11-20 05:26 UTC
Labels: ACL, Backend, Bug, Cannot Reproduce, High
