### ISSUE TITLE
[Bug]: github repo not being cloned after restart or deployment

### ISSUE THREAD

**Issue by gurudatta-carbon** [appsmithorg/appsmith#29047] opened 2023-11-22 20:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Issue**
github repo not being cloned after restart or deployment

getting errors like below, 
```
com.appsmith.server.exceptions.AppsmithException: Git command execution error: repository not found: <<masked repo path>>
	at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$getStatus$137(GitServiceCEImpl.java:1847)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#getStatus(String, String, Boolean) [DispatcherHandler]
Original Stack Trace:
		at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$getStatus$137(GitServiceCEImpl.java:1847)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
```

**Expected behavior**
- clone to happen after restart of service, as that path/files are flushed
- as per docs https://docs.appsmith.com/advanced-concepts/version-control-with-git/updating-local-file-path
```
INFO
If the file path isn't present, Git repositories are cloned, but this isn't persistent, and Appsmith would try to clone the repositories in case they got deleted by docker restart, etc.

```
### Steps To Reproduce

- import a app from github
- Restart service or deploy a new version
- open app in appsmith
**Note:**
- git directory is pointed to docker file system, so it's ephemeral

### Environment

Production

### Version

Self Hosted - 1.9.46

**Comment by andreoav** [comment] 2023-12-11 16:58
I have the same error also using a deployment using ephemeral storage. Using version 1.9.38 the error happens but the repository is cloned. After upgrading to latest version (tested with 1.9.52) the error still occur, but the repository is not cloned.

I don't know which version between 1.9.38 and 1.9.52 introduced the error.

**Comment by riteshkew** [comment] 2023-12-12 08:14
Thank you @andreoav @gurudatta-carbon for bringing this to our attention. We are already working on improving the Git experience with server restart. We'll keep you updated on the progress, and thank you again for your patience and continued support.

**Comment by riteshkew** [comment] 2023-12-20 05:54
Post our triaging, the issue is with ephemeral storage being used.
@gurudatta-carbon @andreoav Would you folks be able to get on a call with us to help us better understand the use case for ephemeral storage and why can’t we use persistent storage instead?

**Comment by gurudatta-carbon** [comment] 2023-12-20 16:52
@riteshkew , it's more of we use only 1 instance of appsmith backend running, very few deployments to appsmith server, and moreover older version of appsmith worked with ephemeral storage and kind of stateless.

if it requires persistent storage,  we can do persistent storage to make it work.

Note: only for "Edit" mode we are facing this issue.

If that's the case, can we update appsmith docs to reflect that as well ? it would need persistent storage ?
<img width="962" alt="image" src="https://github.com/appsmithorg/appsmith/assets/81990237/9895d721-a018-49e1-ba90-adac2112ecb0">

**Comment by andreoav** [comment] 2023-12-21 13:25
> Post our triaging, the issue is with ephemeral storage being used. @gurudatta-carbon @andreoav Would you folks be able to get on a call with us to help us better understand the use case for ephemeral storage and why can’t we use persistent storage instead? Please use [this link](https://calendly.com/ritesh-catchup-15/30min) to schedule.

Same here... ephemeral storage works well for us, and we had no problem with the current version we are running (v1.9.38). Also the docs don't mention that persistent storage is required. (see @gurudatta-carbon screenshot).

We are running on EKS and we can configure persistent storage, but is something that we never needed for Appsmith, and we are using Appsmith for quite some time now...

**Comment by tmedford-zuora** [comment] 2023-12-21 17:42
Persistent storage on disk is not great. If you need to scale out, you must worry about syncing the files across instances or using something like EFS to attach a networked synced drive to all instances.

**Comment by Nikhil-Nandagopal** [comment] 2023-12-22 07:03
@andreoav @tmedford-zuora thanks for bringing this to our notice, we think we may have identified the issue to solve it. Persistent storage will solve the problem and is recommended but we'll also add a fix for this soon

**Closed** 2023-12-25 05:23 UTC
Labels: Bug, Community Reported, Needs Triaging, Git Version Control, Git Pod

**Comment by riteshkew** [comment] 2024-01-22 12:27
@andreoav @gurudatta-carbon @tmedford-zuora I hope you folks are doing well. Just checking in here, if this issue concerning non-persistent storage is resolved for you folks.
