### ISSUE TITLE
[Bug]: On enabling `Confirm before calling`, function runs before confirmation is given

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31416] opened 2024-03-01 11:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When both `Run on page load` & `Confirm before calling` are enabled we can see that the function runs even before providing the confirmation.

### Steps To Reproduce

1. Create a JS Object.
2. Write a function returning a value.
3. Now enable both `Run on page load` & `Confirm before calling` for that function.
4. Now reload the page. -> You should see the confirmation modal.
5. Click on `Yes` in that modal.
6. Now explicitly click on `Run` (without loading the page).

**Expected:** Once `Yes` is clicked on the confirmation modal, the function should run displaying the response.
**Actual:** We see the response before clicking on `Yes`.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/04af7590918d425d9ce74baea2a83854

### Version

Cloud

**Comment by rishabhrathod01** [comment] 2024-04-12 12:58
Unable to reproduce this issue. 

Also, Confirm before calling is deprecated with this change https://github.com/appsmithorg/appsmith/pull/32527. Hence, closing this.

**Closed by rishabhrathod01** 2024-04-12 12:58 UTC
Labels: Bug, Production, Needs Triaging, JS Objects, FE Coders Pod, Medium
