### ISSUE TITLE
[Bug]: Using bound data inside a comment line causes embedded text to not be commented

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10802] opened 2022-02-01 12:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When bound data is present inside a comment line, text inside double mustache is not recognized as a comment. Since JSON doesn't support comment lines, the error is right but we need to handle UI on our end.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/23930e19fa9f4ffab90b6f93921bf78a-00001.gif)](https://www.loom.com/share/23930e19fa9f4ffab90b6f93921bf78a)

### Steps To Reproduce

1. Use a double mustache inside a double mustache.
2. Comment this line out and observe the nested mustache not recognized as a comment text

### Environment

Production

### Version

Cloud

**Comment by subrata71** [comment] 2023-02-15 15:47
Hey @ramsaptami 
Can you please give a concrete example to help reproduce this issue?

**Comment by subrata71** [comment] 2023-02-17 07:39
@ramsaptami 
You mentioned three issues in the [Loom video](https://www.loom.com/share/4737dfed98574fa0b91fb1b7aedf5fb9). Please check the **remarks** column for each of those and let me know your thought on this.

|SL| Issue | Remarks |
|---| --- | --- |
|1| When the value of a binding contains a binding-like syntax it gets replaced by `null`| This [PR](https://github.com/appsmithorg/appsmith/pull/20679) is supposed to fix this |
|2| Adding a comment in JSON results in an error like `Plugin failed to parse JSON...` | This is because JSON doesn't support comment. Quoting from the Wikipedia page of JSON =>**Comments were intentionally excluded from JSON. In 2012, Douglas Crockford described his design decision thus: "I removed comments from JSON because I saw people were using them to hold parsing directives, a practice which would have destroyed interoperability.**<= [Reference](https://en.wikipedia.org/wiki/JSON#:~:text=Comments%20were%20intentionally%20excluded%20from%20JSON.%20In%202012%2C%20Douglas%20Crockford%20described%20his%20design%20decision%20thus%3A%20%22I%20removed%20comments%20from%20JSON%20because%20I%20saw%20people%20were%20using%20them%20to%20hold%20parsing%20directives%2C%20a%20practice%20which%20would%20have%20destroyed%20interoperability.) |
|3|`{{{{someBinding}}}}` evaluates to `null` or `undefined`| In Appsmith world this is definitely an invalid binding. You have to use double curly braces to make it a valid dynamic binding e.g. `{{someBinding}}`|

**Comment by ramsaptami** [comment] 2023-02-17 08:49
Wrt #2, while it's a valid error as mentioned in the original post, the error on our end isn't informative/lacks clarity around what exactly is wrong with the JSON file. The issue was mainly created to handle the error messaging. So can we reopen the issue and track that here?

Wrt #3, since it is an invalid binding, but we show the evaluated value with twin set mustaches, could we add a warning? 
This is primarily because the data inserted to Google Sheets seen in the video is empty cells on all columns except the column where we're sending `{{{{}}}}` where it shows up as `null`

**Comment by subrata71** [comment] 2023-02-17 10:03
[2]
It's not possible to pinpoint the error in the provided JSON object because the underlying library doesn't provide that kind of specific error message. 

[3]
What you are asking seems like an enhancement in the front-end evaluation logic and error messages.

I think the original issue you opened is neither relevant to point[2] nor relevant to point[3. Hence I think you can open different issues for those and close this one.
@ramsaptami

**Closed** 2023-02-20 09:30 UTC
Labels: Bug, UI Improvement, UX Improvement, JS Evaluation, Low, Needs Triaging, error, FE Coders Pod, Data Platform Pod, Error Handling
