### ISSUE TITLE
[Bug]-[2064]:Cannot sort table columns which have custom javascript logic

### ISSUE THREAD

**Issue by danielazheleva** [appsmithorg/appsmith#19928] opened 2023-01-19 16:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a table widget which has some basic columns and some complex columns which use custom javascript to extract data. I.e.:

basic column: `{{currentRow["country_code"]}}`
complex column:
```
{{
	(function() {
		let all_created_at = currentRow.items.map(item => new Date(item.created_at));
		const min = new Date(Math.min.apply(null, all_created_at));
      return min;
	})()
}}
```

I am then unable to sort the columns which have this complex javascript. I have tried setting these columns to both `Number` and `Plain Text` type, and neither work. The other column which have the 'basic logic' are able to sort just fine.

https://user-images.githubusercontent.com/88207801/213492986-9a0bef08-05e6-47cc-a3e5-3e852250c0f5.mov

### Steps To Reproduce

1. Create a table widget
2. Add a JS function to one of the columns to manipulate the data
3. Try to sort the table by that column

### Version

self-hosted - v1.9.3.1

**Comment by somangshu** [comment] 2023-01-23 07:38
We need to test this and find out what is going wrong here

**Comment by somangshu** [comment] 2023-01-23 08:47
@danielazheleva thanks for raising the issue; We will be looking into the problem

I however have not been able to reproduce this issue with the steps shown above. 
can you please check if there any any errors on the debugger or evaluated popup on the table property pane?

**Comment by Privatecoder** [comment] 2023-02-15 11:28
Same issue here. Custom column set as `Number`, checked type with `typeof` which also returns `Number`. AS v 1.9.7. Sorting of this custom column does not work.

**Comment by dilippitchika** [comment] 2023-02-16 06:24
Thanks for adding more information @Privatecoder, we have been able to figure out the exact fix for this issue and will prioritise it.

This is happening because we are not updating an internal property when the custom column is updated making it hard to sort.

**Comment by dilippitchika** [comment] 2023-02-16 06:30
Assuming 30% custom columns use this complex logic

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 516 |
| Effort (months)  | 0.5 |

**Comment by keyurparalkar** [comment] 2023-02-16 09:05
@danielazheleva and @Privatecoder we would like to understand a bit more about the issue you guys are facing. Can you tell us if this is happening in the custom column? If yes, have you renamed this custom column?

**Comment by Privatecoder** [comment] 2023-02-16 16:08
> We noticed this happens when you rename the custom column, are you also doing it?

yes.

**Closed** 2023-04-20 06:41 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, Needs Triaging
