### ISSUE TITLE
[Bug]: Text cursor is not seen in chrome browsers for editing tables in specific cases

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#18352] opened 2022-11-22 10:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text cursor (input caret) is not seen when trying to edit a row in a table widget that has a google sheets datasource.

https://ivp6ez0ljb.vmaker.com/record/EOrbctl6UEMejuuY

### Steps To Reproduce

1. D&D a table widget
2. Connect a datasource to the widget
3. Make some columns editable 
4. Notice that the text cursor does not appear while trying to edit a cell

### Public Sample App

https://app.appsmith.com/app/test12-1/page1-637ca3ef73eefb0845620b98

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7hamk)

**Comment by ame-appsmith** [comment] 2023-02-15 15:08
[Another user](https://app.frontapp.com/open/msg_1mzcint8?key=F4cu9PqUyoUPOhJ3Lrws2b2tcTWThAPJ) reported this issue.

**Comment by Nikhil-Nandagopal** [comment] 2024-04-29 10:13
Duplicate of #32237

**Closed by Nikhil-Nandagopal** 2024-04-29 10:13 UTC
Labels: Bug, Table Widget, App Viewers Pod, Production, Needs Triaging, Medium, Table Widget V2
