### ISSUE TITLE
[Bug] Cannot subscribe to Appsmith AWS AMI 

### ISSUE THREAD

**Issue by datanator** [appsmithorg/appsmith#5745] opened 2021-07-08 19:22 UTC
## Description

When I follow steps to launch AMI launching fails
The error says 
  Launch Failed
  In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3qibdzpltpdqpyu8q24bpgth0

On marketplace I cannot find appsmith AMI and there is no way to subscribe

### Steps to reproduce the behaviour:

See above

**Comment by Nikhil-Nandagopal** [comment] 2021-07-09 05:54
@datanator we're currently having some trouble with Amazon for our AMI. In the meantime, I suggest installing using docker
https://docs.appsmith.com/setup/docker

**Comment by Nikhil-Nandagopal** [comment] 2021-07-12 09:21
Duplicate of $5456

**Closed by Nikhil-Nandagopal** 2021-07-12 09:21 UTC
Labels: Bug, Deployment, Platform
