### ISSUE TITLE
[Bug] Table actions get the wrong value for currentRow when any filter is applied

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#5102] opened 2021-06-14 05:50 UTC
We have a table widget that displays rows of data, along with button for each row. This button is intended to open a Modal with a form used for editing the data from the _current row_.

The way this was implemented is that on clicking the button, we save the `currentRow` object into Appsmith store and then open the Modal. The input widgets in the modal have their default value set to load from the Appsmith store and pick the appropriate field.

This works for the most part, but sometimes, the input widgets in the form don't load the values they should've. They load sometimes, so the logic is likely working, but they don't load sometimes, so we're missing something.

The following video shows the problem as well as the bindings used for the button as well as the bindings in the Modal form.

https://cdn.discordapp.com/attachments/760761686549463060/853566610353422336/vokoscreen-2021-06-13_16-18-17.mp4

**Comment by Nikhil-Nandagopal** [comment] 2021-06-14 06:38
@sharat87 the user can directly reference the selectedRow instead of storing it in these cases.
@hetunandu could this be because of the async nature of actions?

**Comment by sharat87** [comment] 2021-06-14 06:40
I see. I didn't realize clicking on a button in a row will select the row as well. 👍

**Comment by brianestadimas** [comment] 2021-06-14 07:42
Hi @Nikhil-Nandagopal @sharat87 thank you for this, I just want to add something, this behavior only happens when applying filter or search box, for pagination it works well. For example going into page 120, the bug won't occurs. So there must be something with on selection that make value of stored data undefined/null.

I have tried selectedRow to store value and it doesn't work when applying filter/search.

Update : I have tried using text (label) to store temporary data, but become undefined when applying filter/search then store value.

**Comment by brianestadimas** [comment] 2021-06-16 01:39
Hi all, @hetunandu @sharat87 I found the cause of this problem, in short, when filter/search is active and then storing data within currentRow will cause appsmith store to be null

**Comment by hetunandu** [comment] 2021-06-16 16:16
This is caused because the `currentRow` value passed in Table actions is incorrect when any kind of filter is applied. Here is a video with the reproduction

https://user-images.githubusercontent.com/12022471/122255786-17183c00-ceec-11eb-9016-9e7243d7a9fb.mov

**Comment by riodeuno** [comment] 2021-09-09 10:32
@somangshu This has been triaged by @hetunandu . Please re-assign this issue.

**Comment by ashit-rath** [comment] 2021-09-14 05:18
@somangshu @riodeuno I think [this](https://github.com/appsmithorg/appsmith/pull/7244/files) PR might fix this issue as well

**Comment by somangshu** [comment] 2021-10-05 09:57
@vivekverma2312 based on the above please check if this issue is fixed. 

Close this if done

**Comment by vivekverma2312** [comment] 2021-10-06 11:49
@somangshu Tested on prod and it's working fine so closing the issue.

**Closed by vivekverma2312** 2021-10-06 11:49 UTC
Labels: Bug, Table Widget, Widgets Pod, High, UI Building Pod
