### ISSUE TITLE
[Bug] When any of the widgets is placed at the bottom of the canvas the property pane of that widget goes out the canvas/page

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6830] opened 2021-08-24 12:35 UTC
## Description
Release - It is observed that when any of the widgets are placed at the bottom of the canvas that particular widgets property pane goes out of the page 

Expected result:
The page should get expanded when the property pane of any of the widget which are placed at the bottom of the page is opened. The page should get expanded similarly when the widget is placed at the bottom of the canvas

### Steps to reproduce the behaviour:
1.Launch Appmsith app in the release environment 
2.Drag and drop few widgets to the canvas
3.Drag few more at the bottom so that page gets expanded 
4.Click on the widget name of any of the widget which are at the bottom and observe

VideoLink:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/087f7dbfb1034452abc892092924fcb6-00001.gif)](https://www.loom.com/share/087f7dbfb1034452abc892092924fcb6)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [Release]

**Comment by somangshu** [comment] 2021-08-30 10:03
Duplicate of #6040

**Closed by somangshu** 2021-08-30 10:03 UTC
Labels: Bug, Property Pane, Low, Release, UI Building Pod, Needs Triaging
