### ISSUE TITLE
[Feature]: Add feature to reorder available actions in a SaaS Integration through the SaaS Manager App

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#9358] opened 2021-11-24 14:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, all actions are sorted by creation date and that is how they appear in the editor to the end user. We should let the contributor re-arrange these actions to make it more user-friendly, irrespective of the order in which these actions were created.

### Why should this be worked on?

This allows integrations to have the ability to show more relevant actions first as well.

**Comment by felixsuarez0727** [comment] 2022-08-10 19:46
@nidhi-nair, do we have properties that can be controlled from the SaaS App to control this? Will this require BE/FE changes?

**Comment by nidhi-nair** [comment] 2022-08-12 08:25
@felixsuarez0727 this would require us to change the index of the actions in the array they are stored in in the database. We won't need FE/BE changes for this, we can use the SaaS Manager itself to perform this manipulation.

**Comment by felixsuarez0727** [comment] 2022-08-17 02:07
A new branch "feature/order-dropdown" has been created where the functionality to edit the order of actions has been added.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/7eb3bb0b-b97c-40a8-935b-93e0921a3fbe)

There is a problem when saving an ID, the Save button is not deactivated afterwards. So it does not allow to edit another action. 
I think the problem occurs because when the save button is pressed the row is not selected.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/82b50af5-7756-4bf2-9228-08e5fc6dbac1)

**Comment by felixsuarez0727** [comment] 2022-08-17 23:44
Added the new functionality for reordering dropdown actions in master

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/c76699b9-1b4e-47d2-9057-9e32d49c3372)

**Comment by nidhi-nair** [comment] 2022-08-18 08:53
@felixsuarez0727 can we use another variable name instead of id for storing the order of actions? The conflict with `_id` might cause problems in the future.

**Comment by btsgh** [comment] 2022-08-18 10:39
In discussion with @felixsuarez0727 as I am unable to find the id column in the Saas Manager App.

**Comment by felixsuarez0727** [comment] 2022-08-19 11:00
The column is not coming up because it is empty. I am looking for a way to make appear.

**Comment by felixsuarez0727** [comment] 2022-08-26 12:11
This issue was blocked by above these two errors:

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/1a9218ba-51e1-43d7-b8a7-0bd0d77c8432)

But, after looking at this, I realized that the fixes made this week overwrite this enhacement, so, I will be moving this back to the backlog.

**Comment by felixsuarez0727** [comment] 2022-08-27 03:00
I changed the id field to index. Now when a new action is added the index is created by default in 1

Steps to reproduce it 
1. Create a test datasource
2. Add some actions
3. Click on the edit order button
4. The index column will appear for editing

https://images.zenhubusercontent.com/275993885/c8748cd9-4681-4a11-9fcb-5c1998ebe238/video1275890571.mp4

**Note:** As the Index field does not exist in previous datasource it is not recommended to use this function because this columns does not appear, you must first add an index manually.

**Comment by felixsuarez0727** [comment] 2022-08-30 12:39
Fixed when the column was not coming up for existing integrations.

**Comment by prapullac** [comment] 2022-09-01 07:03
@felixsuarez0727 
Page has failures of the Queries Hence moving back to Blocked PR 
 ![Screenshot 2022-09-01 at 12.11.10 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/ad6c0c95-9576-443b-a07b-cb8cad2602ff)

**Comment by felixsuarez0727** [comment] 2022-09-01 12:38
I think this is a general error that was impacting all internal apps, including SaaS App. Can you check again?

**Comment by prapullac** [comment] 2022-09-05 05:50
Verified on the SAAS manager App and works as expected

**Closed** 2022-09-06 17:23 UTC
Labels: Enhancement, QA, BE Coders Pod, SAAS Manager App
