### ISSUE TITLE
[Bug] Firestore pagination query does not work properly

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7333] opened 2021-09-10 07:45 UTC
## Description

User reported:
When I try to implement paging in firestore it behaves in a very strange way, the first 2 pages behave well but if I try to go to the third and then return it shows me the results of the first in the second and there the madness begins, I attach a small video, maybe I am doing the wrong things and if not, I would love to be able to help solve the problem. I'm fascinated by Appsmith.

https://drive.google.com/file/d/1OGG6EzWl4GAC49wJWkj-BXY3ogVA924z/view?usp=sharing

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by ajinkyakulkarni** [comment] 2021-09-10 10:49
Duplicate of #7111

**Closed** 2021-09-10 10:51 UTC
Labels: Bug, Actions Pod, High, Production, Needs Triaging, Actions, firestore
