### ISSUE TITLE
[Bug]: datasource allows binding to JS objects, but they might not exist on a different page 

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#14902] opened 2022-06-29 10:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. datasources are app wide
2. if I create a datasource with some binding to a JSObj on page X then this will work as long as I'm on page X, e.g. 
![image](https://user-images.githubusercontent.com/5968968/176415068-40d18f29-13b6-4c11-8666-79ba39e52d76.png)
3. if I now move to a different page, and create an api under the same datasource then the API calls will fail as the JSobj is non existent on that page. Thinking about it somewhat logical, though the user is not warned for this. I think this should be taken along with the appwide roadmap items :)

related to? https://github.com/appsmithorg/appsmith/issues/9438 and/ or https://github.com/appsmithorg/appsmith/issues/1911 

### Steps To Reproduce

see above

### Version

cloud @ 29/06/2022

**Comment by Nikhil-Nandagopal** [comment] 2022-06-29 11:02
Hi @unknown1337 this isn't necessarily an issue because you can bind to the data on the current page but yes ideally with the introduction of global actions, it will be easier to achieve this. I'm closing this right now because this is the expected behavior

**Closed by Nikhil-Nandagopal** 2022-06-29 11:02 UTC
Labels: Bug, Needs Triaging
