### ISSUE TITLE
[Bug]: Not able to fork Github manager app - timeout error

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#10145] opened 2022-01-04 10:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in production, I want to fork the app [GitHub Manager](https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/60d72903ee9aa1792c5bf16a/edit) into my own organisation. but when I try to do this, I see error: 
![Screenshot 2022-01-04 at 15 49 00](https://user-images.githubusercontent.com/94514895/148044538-8bf0b464-e2b3-4643-bbed-ef3830e70b29.png)

### Steps To Reproduce

1. Go to app.appsmith.com
2. Look for "GitHub Manager" under the organisation "Appsmith internal apps"
3. Click the three dots (...) under the app thumbnail and select "fork"
4. In the modal, select some other organisation that you have access to

**Expected Result**
The app is forked into my org

**Actual Result**
1. There is a long wait where I see the "busy" animation
2. Finally, there is the timeout error as you can see in the screenshot above

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment] 2022-01-04 10:25
I tried forking a couple of other apps, and it worked. Unless this issue is because of something very peculiar in the GitHub Manager app, IMO the priority for this should be High.

**Comment by abhvsn** [comment] 2022-02-09 10:01
Closing this as this is a duplicate of https://github.com/appsmithorg/appsmith/issues/10184

**Closed by abhvsn** 2022-02-09 10:01 UTC
Labels: Bug, Needs Triaging, Platform Pod, Fork App, New Developers Pod
