### ISSUE TITLE
[Bug] Dropdown : Dropdown option gets overlapped on the Modal

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1000] opened 2020-10-05 15:53 UTC
## Steps to reproduce

1. Place a dropdown. In the property pane, make it a multi-select dropdown.
2. In the property pane, configure `onOptionChange` to open a modal. 
3. Change an option in the multi-select dropdown

## Observation

Dropdown options get overlapped on the Modal

## Expected behaviour

Dropdown option must not get overlapped on the Modal. The multi-select dropdown must close itself.

## Video reproducing this bug:
[https://www.loom.com/share/eba7375d05c645508cd21b631db1d14d](https://www.loom.com/share/eba7375d05c645508cd21b631db1d14d)

**Comment by reachtokish** [comment] 2020-10-06 10:04
Can I work on this?

**Comment by spielers** [comment] 2020-10-06 10:04
Hey @Nikhil-Nandagopal @prapullac I would like to work if found any bug please add me there

**Comment by mohanarpit** [comment] 2020-10-06 10:10
@reachtokish It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by mohanarpit** [comment] 2020-10-06 10:11
@spielers Sorry, this is assigned to @reachtokish because he's claimed this first. There are a lot of other issues in the repo that you could solve.

Happy hacking!

**Comment by reachtokish** [comment] 2020-10-06 10:16
Thanks @mohanarpit

**Comment by reachtokish** [comment] 2020-10-06 13:24
@mohanarpit the reproduction instruction is not very clear to me. Could you pls elaborate more and kindly share a screenshot if possible?

**Comment by reachtokish** [comment] 2020-10-06 13:44
I think I got the direction but unable to reproduce the issue

**Comment by mohanarpit** [comment] 2020-10-06 13:56
@reachtokish I've added a video reproducing the issue in the description. Also added some more details to the issue. Please check that out.

**Comment by reachtokish** [comment] 2020-10-06 13:58
Got it. Thnx @mohanarpit

**Comment by reachtokish** [comment] 2020-10-06 15:38
I was checking [@blueprintjs/select](https://blueprintjs.com/docs/#select/multi-select). And what I have come up with is that blueprintjs select component does not allow to hide dropdown panel explicitly. Kindly refer [this link](https://github.com/palantir/blueprint/issues/3850).

I have to do a hack to hide the dropdown panel like triggering a blur event on `StyledMultiDropDown` input using ref like below. Also refer [this PR](https://github.com/palantir/blueprint/commit/b884410f669fb8f390e0043df8bb662334656c2c)

```javascript
<StyledMultiDropDown
  ref={this.ref}
  onItemSelect={this.onItemSelect}
/>
```
```javascript
onItemSelect = (item: DropdownOption): void => {
  this.ref.current.input.blur();
  this.props.onOptionSelected(item);
};
```

The above way works perfectly and hides the dropdown on every change

@mohanarpit kindly provide a better solution if you have any, otherwise I'm going with the above approach.

**Comment by mohanarpit** [comment] 2020-10-06 17:03
@satbir121 Can you please comment on the proposed solution above?

**Comment by Nikhil-Nandagopal** [comment] 2020-10-08 10:22
@reachtokish we don't necessarily need to close the dropdown, can we just modify the z-index of the open state so that it's under the modal?

**Comment by reachtokish** [comment] 2020-10-08 10:27
@Nikhil-Nandagopal thnx. Will do the needful and raise a PR in sometime.

**Closed** 2021-06-22 10:07 UTC
Labels: Bug, Dropdown Widget, Frontend, Good First Issue, Low, Modal Widget, Release, UI Building Pod, Widgets, hacktoberfest
