### ISSUE TITLE
[Bug] Enhancement : User readable error messages for @NotNull validation annotations

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1006] opened 2020-10-05 15:59 UTC
Reference: [https://www.baeldung.com/spring-validation-message-interpolation](https://www.baeldung.com/spring-validation-message-interpolation)

This ensures that all validation annotations have human readable messages being returned to the client.

**Comment by mohanarpit** [comment] 2020-11-16 04:28
Closing this as a duplicate of #604

**Closed by mohanarpit** 2020-11-16 04:28 UTC
Labels: Bug, Low, Release, Widgets, hacktoberfest
