### ISSUE TITLE
[Bug]: Keycloak signup page form shows up for an existing user, if their prior login attempt failed

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#23423] opened 2023-05-17 01:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We've noticed this with one of our users, where the Keycloak signup form with `username`, `email`, `first name` and `last name` shows up even for existing users, if their prior login attempt failed. But this itself is not the problem, if they attempt to fill the form and move on, Keycloak complains that a user already exists with this email, and then proceeds to a link loop. No matter what option we choose there, we end up at the Keycloak signup form again.

### Steps To Reproduce

Little unsure on this.

[Slack thread for reference](https://theappsmith.slack.com/archives/C0341RERY4R/p1684171155416289?thread_ts=1680545916.892459&cid=C0341RERY4R).

### Environment

Production

### Version

1.9.18

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 09:52
Duplicate of #30520

**Closed by Nikhil-Nandagopal** 2024-03-06 09:52 UTC
Labels: Bug, High, Production, Needs Triaging
