### ISSUE TITLE
[Bug]: Redis is not persisting data on container restart

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#19889] opened 2023-01-19 04:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Redis is not persisting data on container restart, this is causing user sessions to terminate on updating/restarting the Appsmith container.
The ideal way this should be working is that Redis works as an in-memory system. Storing all its data in it's memory. But we configure Redis to dump all this data to an RDB file, every so often. On restart or update, Redis is supposed to pick up from that RDB file, and continue. 

### Steps To Reproduce

1. Launch an Appsmith container
2. Use a browser to log in
3. Restart the container
4. Use the same browser to access the app, and observe the users gets logged out.

### Version

1.9.3.1

**Comment by sharat87** [comment] 2023-01-20 05:01
Duplicate of #19768.

**Closed by sharat87** 2023-01-20 05:01 UTC
Labels: Bug, Deployment, High, Docker, DevOps Pod
