### ISSUE TITLE
[Bug]:  Apps with gsheet as datasource are broken.

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#10431] opened 2022-01-17 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Build appsmith locally using build slim container https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md   https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md

gsheet reauthorization fails 
apps with gsheet cannot be imported

### Steps To Reproduce

Unable to import apps with gsheet
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/aaa4a4e7c49c4c0a862882cbe93bc902-00001.gif)](https://www.loom.com/share/aaa4a4e7c49c4c0a862882cbe93bc902)
Unable to authenticate gsheet
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d63b3b287436438bab8a87e2bc4a2a3e-00001.gif)](https://www.loom.com/share/d63b3b287436438bab8a87e2bc4a2a3e)

### Environment

Release

### Version

Self-Hosted

**Comment by yatinappsmith** [comment] 2022-01-17 08:57
Issue is only present on slim container.

**Comment by rohan-arthur** [comment] 2022-01-17 11:40
tested this in prod cloud, not reproducible.
Also @prapullac tested in fat container and release - not reproducible

Looks like this issue exists only in slim container

cc @sharat87 @mohanarpit

**Comment by sumitsum** [comment] 2022-01-20 08:10
@yatinappsmith @prapullac can you please invite me to the org where the test application used in the video is present ? I could not reproduce it on my local. I am hoping the test application could help.

**Comment by sumitsum** [comment] 2022-01-20 08:58
Closing since this issue was resolved as mentioned here: https://theappsmith.slack.com/archives/CTHN8GX5Y/p1642402286005700

**Closed by sumitsum** 2022-01-20 08:58 UTC
Labels: Bug, Actions Pod, Needs Triaging, Google Sheets, BE Coders Pod
