### ISSUE TITLE
[DOCS] - Add docs for Clear store

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#18224] opened 2022-11-17 09:39 UTC

**Comment by Pranay105** [comment] 2022-12-07 10:41
Can you please give us the first draft? @rimildeyjsr

**Comment by jnikhila** [comment] 2023-01-12 09:55
Duplicate of [#692](https://app.zenhub.com/workspaces/user-education-pod-61c01739f309a80011b48267/issues/gh/appsmithorg/appsmith-docs/692)

**Closed by jnikhila** 2023-01-12 09:55 UTC
Labels: Documentation, FE Coders Pod, User Education Pod, Ready for Doc Team, Framework Functions
