### ISSUE TITLE
[Bug]: Disable clicking on Next page button when Table record reached to last page

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#22477] opened 2023-04-17 09:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Table widget, when pagination reach to it's last page the icon seems disabled but we can still Click on it and see rendering of data.

### Steps To Reproduce

1. Drag & drop a Table widget
2. Run a server side pagination query `SELECT * FROM users ORDER BY id LIMIT {{Table2.pageSize}} offset {{Table2.pageOffset}}`
3. Enable server side pagination and configure onPageChange & Total records
4. Reach to last page of the table records
5. Observe that Next page button is disabled but clickable

### Environment

Production

### Issue video log

https://www.loom.com/share/bad8d690647c4583b7e82d6092a1ccbe

### Version

Cloud / Production

**Comment by avijeetpandey** [comment] 2023-04-19 11:51
@chandannkumar @keyurparalkar @dilippitchika i wanted to contribute and work on this issue can you please assign this issue to me ?

**Comment by dilippitchika** [comment] 2023-04-19 11:59
Greetings @avijeetpandey thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by avijeetpandey** [comment] 2023-04-19 12:04
Thanks @dilippitchika , will try my best to do that

**Comment by Ashmash100** [comment] 2023-04-19 19:42
Hi @dilippitchika @chandannkumar 
In case the PR isn't raised, I would like to work on this issue.

**Comment by avijeetpandey** [comment] 2023-04-20 14:49
@dilippitchika the client  is taking so much time to compile, anything that can be done to speed this up , have setup the client and server as per the docs , but upon running ```yarn start``` its taking so much to complile .

System Info
```
Ubuntu 22.10
8GB RAM
```

**Comment by avijeetpandey** [comment] 2023-04-20 17:18
@dilippitchika @chandannkumar After following the docs and setting up the server successfully got the following error on the client, need little help in making the client a successful connection to a staging/local environment.

Attaching the screenshot for a better understanding of the issue.

Thanks
![Screenshot from 2023-04-20 22-35-57](https://user-images.githubusercontent.com/40532869/233440546-5285b83d-17a0-497e-bbee-670f1dc8d21e.png)

![Screenshot from 2023-04-20 22-41-26](https://user-images.githubusercontent.com/40532869/233440706-9eeaca0e-2b22-488a-921a-d564274bbf4b.png)

**Comment by sharat87** [comment] 2023-04-21 04:47
Hey @avijeetpandey, I think you're opening http://dev.appsmith.com:3000 in your browser. Can you try https://dev.appsmith.com instead please? If that also shows the _same_ error, please share the exact full command you've used to run the `start-https.sh` script for us to debug further. Thanks!

**Comment by avijeetpandey** [comment] 2023-04-21 12:36
@sharat87 here are the set of commands i am running after setting up the repo as per the docs

```
// for backend
cd appsmith/app/server
docker-compose up -d

cd appsmith/app/client
./start-https.sh
yarn start
```


on accessing ```http://dev.appsmith.com``` I am getting the following
![Screenshot from 2023-04-21 18-06-08](https://user-images.githubusercontent.com/40532869/233637746-6464ccd3-117f-468f-a877-38a1d11693f6.png)
![Screenshot from 2023-04-21 18-06-01](https://user-images.githubusercontent.com/40532869/233637752-0dd30287-eaaf-4288-9f48-59c595d027ea.png)

**Comment by Ashmash100** [comment] 2023-04-23 17:23
Hi
I know the solution for this. If the issue is still open can I work on it?

**Comment by sharat87** [comment] 2023-04-24 13:45
@avijeetpandey, that looks odd. Can you share the output of the `start-https.sh` command, as well as the generated NGINX configuration located at `app/client/nginx/nginx.dev.conf` here please?

**Comment by harrybasra95** [comment] 2023-04-30 06:48
@chandannkumar @keyurparalkar @dilippitchika I was going through this issue and I have found the buggy code.

### Code Location

The below image is from /app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx 

<img width="1037" alt="Screenshot 2023-04-30 at 11 55 18 AM" src="https://user-images.githubusercontent.com/20265606/235339118-6e59e47b-fec9-419e-822d-a6cb0405cf21.png">

### What the issue
 
We are adding `pointerEvents: none` to the child elements of `PaginationItemWrapper`. But the onClick code is working on the `PaginationItemWrapper` element itself. Because of this on hover the button looks like disabled but still the onClick works.

### Proposed solution
With CSS - We can add `pointerEvents: none` to the parent element but it will disable the `cursor: not-allowed` property. Thus it will start showing the move icon when hovered on the disabled button.

With JS - We can directly add the disable condition on the onClick event.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/20265606/235339768-78344c6b-f4be-4ff2-939f-5d08a9df32f3.png">

Please suggest to me how to proceed.

**Comment by keyurparalkar** [comment] 2023-05-02 09:43
Greetings @harrybasra95 thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by keyurparalkar** [comment] 2023-05-02 13:30
@harrybasra95 can you proceed with the JS solution where we add a disable condition to the onClick event

**Comment by harshitpandey0426** [comment] 2023-05-14 13:51
@keyurparalkar Is this resolved?

**Comment by keyurparalkar** [comment] 2023-05-15 06:09
@harshitpandey0426 thanks for showing interest but the PR has already been raised for it.

**Comment by Dvinod1** [comment] 2023-06-15 04:43
Hi, is this issue still open, and it is client-side only?, I want to contribute

**Closed** 2023-07-07 06:46 UTC
Labels: Bug, Good First Issue, Table Widget, App Viewers Pod, Needs Triaging, medium
