### ISSUE TITLE
[Bug]: Forking a template into an existing app which is connected to git makes the application go into a bad state

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17002] opened 2022-09-23 05:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/67054171/191893840-a48f385c-a859-4ef8-a4c3-a2b6384463dd.mov

Public app: https://release.app.appsmith.com/app/untitled-application-2/page1-632d3b6688c13228e9a61fa8?branch=master

https://release.app.appsmith.com/api/v1/actions?pageId=632d3c4388c13228e9a62015 GET returns a 404.

```
{
  "status": 404,
  "success": false,
  "error": {
    "code": 4027,
    "message": "Unable to find page 632d3c4388c13228e9a62015, master",
    "errorType": "INTERNAL_ERROR"
  }
}
```
Here `632d3c4388c13228e9a62015` is the new page added post forking the template.

### Steps To Reproduce

1. Create a new app.
2. Connect the application to a git repo.
3. Fork a template(Customer Support Dashboard) as shown in the screen recording.
4. 404 page is shown. This page is shown because it failed to get the actions of the page, as the api failed for the same.

### Public Sample App

https://release.app.appsmith.com/app/untitled-application-2/page1-632d3b6688c13228e9a61fa8?branch=master

### Version

Cloud / Release: v1.8.2

**Comment by mohanarpit** [comment] 2022-09-23 06:01
@akash-codemonk Is this an intermittent issue or 100% reproducible for you?

**Comment by akash-codemonk** [comment] 2022-09-23 06:01
It is 100% reproducible.

**Comment by hiteshjoshi** [comment] 2022-09-30 07:51
Closing this since this seems merged. Also, removing the Git labels.

**Closed by hiteshjoshi** 2022-09-30 07:51 UTC
Labels: Bug, Backend, High, Release, Needs Triaging, Git Version Control, Team Managers Pod, New Developers Pod, Templates
