### ISSUE TITLE
[Feature]: Dynamic client ID and client secret for custom logins.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#22685] opened 2023-04-24 21:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user wants to create a simple login where their users can authenticate to their API by only passing their Client ID and Client Secret. This would allow hundreds of users to connect with different privileges to their API from a single data source.
![image](https://user-images.githubusercontent.com/114161539/234119512-3f3e3e06-14b6-449a-bc0f-b262ed55df2b.png)
![image](https://user-images.githubusercontent.com/114161539/234122332-705b6fd6-ba0e-45c2-9c7c-1eae317d75ef.png)

### Why should this be worked on?

   
1. Simplified user authentication: With dynamic client ID and client secret for custom logins, users can authenticate to the API by only passing their credentials, which is a much simpler process than traditional authentication methods.

2. Scalability: This solution allows for hundreds of users to connect to the API with different privileges from a single data source, which makes it much more scalable than traditional methods.

3. Improved security: Using dynamic client ID and client secret for custom logins improves security as users don't have to share their personal credentials and can only access the parts of the API that they are authorized to.

4. Cost-effective: With this solution, the cost of user authentication is significantly reduced as we eliminate the need for expensive authentication systems and complex user management.

Overall, implementing dynamic client ID and client secret for custom logins would simplify the authentication process, improve security, increase scalability, and reduce costs.

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 11:22
A better way to achieve this is to use our SSO option. This is a duplicate of #3313

**Closed by Nikhil-Nandagopal** 2024-03-06 11:22 UTC
Labels: Enhancement
