### ISSUE TITLE
[Task] Using request DTOs instead of domain objects in APIs

### ISSUE THREAD

**Issue by pc9795** [appsmithorg/appsmith#1015] opened 2020-10-06 00:35 UTC
## Summary
While going through the codebase I observed that in controllers, at many places, we are using domain objects instead of a separate DTOs for handling API requests. 

For example https://github.com/appsmithorg/appsmith/blob/c1b498f6b81dd67d707fd45c7dd40d6990486438/app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java#L54

Moreover, there are no validations in the object. (Ideally, they should not be present on domain objects)

## Motivation

* The first thing is using DTOs for requests separate the resource/controller layer from the service layer. DTO and domain objects can change independently from each other.
* We can avoid littering our domain objects with Jackson and Java bean validation annotations.
* Having a request DTO will help a backend engineer or a contributor to quickly understand what this API needs instead of understanding the domain object (In most of the cases domain objects contain some extra fields populated in the service layer).

## Additional Context

For example, I wanted to explore the backend system locally (without digging into/running the frontend) so to access many of the APIs I had to create a `User `through the `UserController `APIs. But when I went to the create method I had to understand by looking into the `User `domain object that what fields to set, what is ignored etc. DTOs make this thing simple.

**Comment by mohanarpit** [comment] 2020-10-06 01:28
@pc9795 Thanks for opening this issue. You do make a good point. 

I have 1 question though: Does creating a request DTO for each API mean that now we'll have to perform a deep copy of the object from the DTO to the domain object on each request? Vice-versa, will we have to perform a deep copy from domain object to DTO ( for GET API calls )? Is there a way to avoid all this copying? 
Also, by any chance is there a reference code base you can point me to

**Comment by pc9795** [comment] 2020-10-06 01:29
@mohanarpit No need for manual copying. You can look into https://mapstruct.org/

**Comment by pc9795** [comment] 2020-10-06 01:30
Some code reference where I have used it: https://github.com/pc9795/portfolio/blob/master/src/main/java/com/prashantchaubey/dto/mappers/ContactMapper.java

**Comment by mohanarpit** [comment] 2020-10-06 01:54
@pc9795 Thanks for the pointer to mapstruct. #TIL

On reading a little more about it, in the [generated code section](https://mapstruct.org/documentation/dev/reference/html/#basic-mappings), I can see that MapStruct implicitly creates the implementation class to copy data from the domain class to the DTO. This is the copy that I'm trying to avoid. It creates unnecessary garbage in the JVM and slows things down. A lot of this doesn't show up in the early days, but with a little load on the machine, the cost of these copies become apparent very quickly. 

By design, the Appsmith backend server should be as light and performant as possible. Hence, if there's a better way to implement the "separation of concerns" principle that you suggested, I'd be more than willing to do that.

**Comment by pc9795** [comment] 2020-10-09 01:33
hmmmm, I have not thought in this way. I only used Map struct or wrote mappers by scratch.  For the starters there is this excellent [article](https://www.baeldung.com/java-performance-mapping-frameworks). I can dig in more but not sure as of now. But yeah using DTOs is debatable but IMO keeping things separate has its own benefits.

**Comment by mohanarpit** [comment] 2020-10-22 13:48
Closing this issue for now since we are not prioritizing this code change.

**Closed by mohanarpit** 2020-10-22 13:48 UTC
Labels: Backend
