### ISSUE TITLE
[Bug]Replacing image url directly without binding in the list widget is not working as expected

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3924] opened 2021-04-08 08:04 UTC
## It is observed that by the binding image with API the list widget is showing the binder image. But, when the user directly replaces the image url in the property pane the new image is not displayed.

**Expected Result:**
User should be able to change the List Widget image by replacing the image url from the image property pane

**Actual Result:**
Replacing the image url from the image property pane new image is not displayed

### Steps to reproduce the behaviour:
1.Launch Appsmith app in the Deploy environemt
2. Drag and drop list widget 
3. Click edit on the Image1 and replace the image url 
4. Replace the image url in the List array for image 1 and observe

**Video link:**
https://www.loom.com/share/844d405484ac4aa3a02567a6d6caf6f2

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [e.g.MacOS Big Sur 11.2.3]
 - Browser [ safari]

**Comment by areyabhishek** [comment] 2021-04-24 08:42
@YogeshJayaseelan This will not work because the image widget has been bound to a URL already. In the video you are replacing the default image, but not the actual binding. The default image works only when there is no binding.

**Comment by jsartisan** [comment] 2021-06-14 09:34
Closing this as the issue reported is the expected behavior.

**Closed** 2021-06-14 09:34 UTC
Labels: Bug, List Widget, Medium effort, Release, UI Building Pod, Widgets
