### ISSUE TITLE
[Bug]: The filepicker widgets selects multiple files and then removes one of them, causing the final content of all file.data to be abnormal.

### ISSUE THREAD

**Issue by gzlinzihong** [appsmithorg/appsmith#31411] opened 2024-03-01 10:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When using filepicker widgets to select multiple files and then remove one of them, all file.data contents are abnormal in the end.
![image](https://github.com/appsmithorg/appsmith/assets/56068188/4d85f693-8ce1-4b7f-b786-94e4535f22ea)
![image](https://github.com/appsmithorg/appsmith/assets/56068188/fdb6d995-5440-44a9-8aba-97e2d7abc444)

### Steps To Reproduce

1. Select multiple files
2. Delete one of the files
3. View filePicker1.data

### Environment

Production

### Version

Cloud And self hosted,latest version

**Comment by Nikhil-Nandagopal** [comment] 2024-03-01 14:47
@gzlinzihong this is a duplicate of #29605 so I'll close it in favor of that

**Comment by gzlinzihong** [comment] 2024-03-01 15:18
@Nikhil-Nandagopal  And the second point。The MULTIPART_FORM_DATA type in the body of the restapi plugin, when passing text type parameters, including Chinese, Japanese, etc., is garbled

Based on the above two questions, I have solved them on self hosted. I'm not sure if it's possible to raise a PR to see if it works

**Closed** 2024-03-12 07:16 UTC
Labels: Bug, File Picker Widget, App Viewers Pod, Community Reported, Needs Triaging, REST API plugin, Integrations Pod, Integrations Pod General
