### ISSUE TITLE
[Bug]: 'Close on selection' is not working on changing the month from calendar in Date Picker widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#16131] opened 2022-08-18 10:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/620b105c244841cb9b13b37d163cd848

### Steps To Reproduce

1. Drag & Drop Date Picker widget
2. Enable 'Close on Selection' property from property pane
3. Click on Date picker widget to open calendar
4. Change the month of the calendar via dropdown or arrow ( <  > )
5. Now select the date from calendar
6. Observe that calendar is not getting closed on date selection

### Version

Cloud/Production

**Comment by dilippitchika** [comment] 2023-03-02 13:42
Duplicate of #13566

**Closed by dilippitchika** 2023-03-02 13:42 UTC
Labels: Bug, Date Picker Widget, App Viewers Pod, Production, Needs Triaging, medium
