### ISSUE TITLE
[Bug] the Table widgets pageSize property cannot be updated in mobile viewport

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22911] opened 2023-05-02 11:03 UTC
https://www.loom.com/share/64a52913d2254122af468b2a5f58ff11

**Comment by aswathkk** [comment] 2023-05-11 09:39
We need to take into account of mobileBottomRow property for the pageSize calculation within TableWidget

**Comment by andreevanatasha** [comment] 2023-05-12 13:13
Duplicate of https://github.com/appsmithorg/appsmith/issues/22907

**Closed by andreevanatasha** 2023-05-12 13:13 UTC
Labels: Mobile Pod, Responsive Widget
