### ISSUE TITLE
[Bug]: Git import of attached repo throws bad request error on first time opening, and switiching to branches

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33967] opened 2024-06-04 11:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I git import the attached repo, I get a bad request error, after which a git lock error is thrown

### Steps To Reproduce

Git import app from attached repo
Note that as soon as app opens on master, we get a bad request error 
This error appears when we checkout any branch
Post that we also get a git lock error

Repo: git@github.com:btsgh/perfinfraapp.git

https://github.com/appsmithorg/appsmith/assets/101863839/acd210af-b858-4428-8dba-79cf5e27c7a5

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud DP

**Comment by btsgh** [comment] 2024-06-07 10:40
[performance-infra-app_CANBEUSED.json](https://github.com/user-attachments/files/15737805/performance-infra-app_CANBEUSED.json)
@sondermanish

**Comment by VigneswarV** [comment] 2024-06-20 05:30
Hi,

I was not able to reproduce the issue,
**Steps tried to reproduce,** 
1. Created a new repo
2. Try to import the newly created repo ( no issues occured yet )
3. Add some components in the main branch  
4. Then created branch in it
5. And try do branch switch also (haven't get any error)
6. It was able to load the whole application.

As this issue is  specific git repo, Can you provide access to it
Or can i fork it and test 
repo: **perfinfraapp**
owner: **btsgh**

**Comment by btsgh** [comment] 2024-06-21 10:08
This happens on release as well, for the particular app, when we try to git import it. Hence moving it out of auto-commit, but retaining it as a git issue.

**Comment by VigneswarV** [comment] 2024-06-27 08:41
I have tried forked the specific repo and try to do import to replicate this issue.
But I have block with **Missing Datasource Credentials** page.

![image](https://github.com/appsmithorg/appsmith/assets/165656044/a11be9cd-6a4f-4ecf-a5fa-c047177018c9)

Can you please share the details.
repo: **perfinfraapp**
owner: **btsgh**

**Comment by riteshkew** [comment] 2024-09-25 18:02
Lock file errors are now resolved. Specific to this app only, hence closing this for now.

**Closed by riteshkew** 2024-09-25 18:02 UTC
Labels: Bug, Production, Needs Triaging, Import-Export-App, Medium, Git Platform Pod, Artifact Platform Product
