### ISSUE TITLE
[Feature] S3: provide a way to allow bulk upload of files

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6553] opened 2021-08-12 08:55 UTC
## Summary
```
I am using a file picker widget to upload image and store on S3
i have written a query on s3 to upload 1 image for now
how do I configure the query to upload multiple images, for now I have set the filepicker widget to a max of 5 images
```

**Comment by SatishGandham** [comment] 2021-08-18 07:03
@Nikhil-Nandagopal , Do we need any changes in the file picker widget for this?

**Comment by SatishGandham** [comment] 2021-08-18 07:11
Duplicate #3338

**Comment by sumitsum** [comment] 2021-08-18 07:17
@SatishGandham These two issues are slightly different - issue 3338 talks about uploading a folder hence the Filepicker would have to allow for adding a folder instead of files and the s3 plugin would have to create a separate folder in the designated path as well. However, for this issue, a folder is not a requirement, files are individually added and when uploading to s3 they need to be present as such at the designated path and not inside a folder.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-06 09:04
Duplicate of #6737

**Closed by Nikhil-Nandagopal** 2021-10-06 09:04 UTC
Labels: Enhancement, Actions Pod, community, Query Executions, S3, BE Coders Pod
