### ISSUE TITLE
[Bug] improper alingment of the table rows with there header

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1528] opened 2020-11-03 07:29 UTC
Please refer the screenshot for the same
Environment :
Windows 7 > Chrome 

![table](https://user-images.githubusercontent.com/71753653/97958909-34bce900-1dd4-11eb-890e-56fac727f655.png)

**Comment by Nikhil-Nandagopal** [comment] 2020-11-03 08:51
Duplicate of #982

**Closed by Nikhil-Nandagopal** 2020-11-03 08:51 UTC
Labels: Bug, Low, Production, Release, Table Widget
