### ISSUE TITLE
[Feature]: Grouping pages for navigation

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#17768] opened 2022-10-20 11:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

[Creating a group](https://www.figma.com/proto/Ah9UdeCmvk4PXeDIcPBIRq/EUE%3A-Grouping-Controls?page-id=621%3A253961&node-id=919%3A419946&viewport=245%2C-4383%2C0.2&scaling=min-zoom&starting-point-node-id=919%3A419946&show-proto-sidebar=1)
[Deleting a group](https://www.figma.com/proto/Ah9UdeCmvk4PXeDIcPBIRq/EUE%3A-Grouping-Controls?page-id=621%3A253961&node-id=919%3A443802&viewport=245%2C-4383%2C0.2&scaling=min-zoom&starting-point-node-id=919%3A443802&show-proto-sidebar=1)
[Ungrouping](https://www.figma.com/proto/Ah9UdeCmvk4PXeDIcPBIRq/EUE%3A-Grouping-Controls?page-id=621%3A253961&node-id=919%3A448749&viewport=245%2C-4383%2C0.2&scaling=min-zoom&starting-point-node-id=919%3A448749&show-proto-sidebar=1)
[Adding homepage to group](https://www.figma.com/proto/Ah9UdeCmvk4PXeDIcPBIRq/EUE%3A-Grouping-Controls?page-id=621%3A253961&node-id=984%3A456880&viewport=245%2C-4383%2C0.2&scaling=min-zoom&starting-point-node-id=984%3A456880&show-proto-sidebar=1)

### Related
https://github.com/appsmithorg/appsmith/issues/17766

**Comment by Nikhil-Nandagopal** [comment] 2024-06-15 07:51
Duplicate of #2282

**Closed by Nikhil-Nandagopal** 2024-06-15 07:51 UTC
Labels: Enhancement, App Viewers Pod, App Navigation
