### ISSUE TITLE
[Bug]: Signing up as a new user from a public app does not work

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15103] opened 2022-07-11 05:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App returns a 400 when a new user signs up using a shared public app URL

### Steps To Reproduce

1. Make an app public
2. Copy share link to an incognito tab
3. Launch the application and try to sign-in from the top right corner
4. Create new user credentials and press enter - observe a 400 page as seen below displayed to the user

![image](https://user-images.githubusercontent.com/79509062/178197028-da251bd0-4a88-4268-9085-68dd70965779.png)

### Version

Cloud

**Comment by akash-codemonk** [comment] 2022-07-11 06:13
This is a duplicate of https://github.com/appsmithorg/appsmith/issues/12926 and is not related to clean url.

**Closed** 2022-07-11 06:14 UTC
Labels: Bug, Critical, Needs Triaging, Release Blocker, Clean URLs
