### ISSUE TITLE
[Feature]: Horizontal Scrolling for List widget

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13622] opened 2022-05-05 18:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be nice to have the option for List widgets to scroll horizontally. What if we are displaying tall data or using the list items as info cards?

### Why should this be worked on?

Suppose you have many panes of tall data to display, or you have smaller cards, and prefer to display them horizontally instead of vertically.

**Comment by rohan-arthur** [comment] 2022-05-24 07:51
another request for this feature: https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100095411

**Comment by dilippitchika** [comment] 2022-05-27 10:57
Duplicate of #7256

**Closed by dilippitchika** 2022-05-27 10:57 UTC
Labels: Enhancement, Needs More Info, App Viewers Pod, UI Building Pod, community, List Widget

**Comment by codefromrvk** [comment] 2022-09-20 07:09
Add an option to list vertically or horizontally
