### ISSUE TITLE
[Bug] Multi-select dropdown widget doesn't show selected options count

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4018] opened 2021-04-15 14:28 UTC
The multi-select dropdown widget is supposed to show the names of a few selected options and then truncate the rest to show a count when there's not enough space.
1. This is how it looks today.
<img width="246" alt="Screen Shot 2021-04-15 at 7 53 56 PM" src="https://user-images.githubusercontent.com/30255708/114886059-dab15c80-9e24-11eb-9d45-ddf7cd069962.png">
2. This is how it is supposed to look
<img width="398" alt="Screen Shot 2021-04-15 at 7 55 32 PM" src="https://user-images.githubusercontent.com/30255708/114886064-dbe28980-9e24-11eb-8277-aee3143035bb.png">
Link to Figma: https://www.figma.com/file/moGQyQffFfyUhHUMO9xqn3/Appsmith-v1.0-Final?node-id=8229%3A6383

**Comment by Nikhil-Nandagopal** [comment] 2021-04-16 07:07
Duplicate of #772 
I've also shared a component which we can use to achieve this in that issue

**Closed by Nikhil-Nandagopal** 2021-04-16 07:07 UTC
Labels: Bug, Dropdown Widget, Low, Low effort, UI Building Pod, Widgets
