### ISSUE TITLE
[Bug] Changing tab name in property pane does not reflect in entity explorer properly

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3540] opened 2021-03-13 13:53 UTC
When we change the tab name in the property pane, it does not reflect in entity explorer and it results in the error "already exists" error when changing in the entity explorer

**Comment by Nikhil-Nandagopal** [comment] 2021-03-15 07:10
Duplicate of #2037

**Closed by Nikhil-Nandagopal** 2021-03-15 07:10 UTC
Labels: Bug, Needs Triaging, Tab Widget, UI Building Pod, Widgets, community
