### ISSUE TITLE
[Bug]:  Label text goes missing on edit mode when reducing width on radio group widget

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#26549] opened 2023-08-22 07:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attached screen shot : 

![image](https://github.com/appsmithorg/appsmith/assets/134914630/f5cadde4-901f-401d-b845-3d63e08767ec)

### Steps To Reproduce

1. Drag and drop radio group widget
2. Add tool tip to the label text
3. Set label text in bold style 
4. Now reduce the width and observe label text goes missing
5. Now deploy the app or preview the app label text displays

### Environment

Production

### Version

Appsmith v1.9.34-SNAPSHOT

**Comment by Naveen-Goud** [comment] 2024-07-18 15:54
Hii @ghost @pranavkanade , I would like to work on this ticket , can you assign this to me !!

**Comment by msivakumars2712** [comment] 2024-07-19 15:55
@Nikhil-Nandagopal is this available for contribution? If available our team can work on this. Please confirm.

**Closed** 2024-08-12 07:16 UTC
Labels: Bug, Widgets Product, Low, Production, Needs Triaging, Radio Group Widget, Widgets & Accelerators Pod

**Comment by Naveen-Goud** [comment] 2024-08-12 07:30
Hii @Nikhil-Nandagopal  , I have can see that the issue is still reproduceable.
![image](https://github.com/user-attachments/assets/96e4d55e-9d57-4e88-bddc-6bd86ef5cbbf)

thank you.

**Comment by Nikhil-Nandagopal** [comment] 2024-08-12 09:14
@Naveen-Goud this is a non issue so I closed it. I don't want to invest time fixing this
