### ISSUE TITLE
[Bug][High][Release] Form is resetting on error

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#820] opened 2020-09-30 11:44 UTC
action response has `isExecutionSuccess: false`

**Comment by jsartisan** [comment] 2020-12-08 07:25
@Nikhil-Nandagopal Seems to be working on my end. Can you reproduce it?

![1](https://user-images.githubusercontent.com/6636360/101452951-91bc3980-3954-11eb-9e9e-fdd3bcf07996.gif)

**Comment by Nikhil-Nandagopal** [comment] 2020-12-09 07:08
@jsartisan I am able to repro it.
1. Drag a form
2. Drag an input into the form
3. Select the submit button
4. Bind the onClick to a new Query
5. Enter random text in the query
6. Enter some value in the input of the form
7. Click submit
8. The form value gets reset and an error is showing.

This is happening on app.appsmith.com

**Comment by jsartisan** [comment] 2020-12-09 09:49
@Nikhil-Nandagopal Can you invite me to the app where it is happening? I am unable to reproduce it.

**Comment by Nikhil-Nandagopal** [comment] 2020-12-09 13:01
@jsartisan strangely it's not happening now. @hetunandu did anything change here?

**Comment by hetunandu** [comment] 2020-12-09 13:05
Nope @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment] 2020-12-09 13:29
ok lets close this for now

**Closed by Nikhil-Nandagopal** 2020-12-09 13:29 UTC
Labels: Bug, Form Widget, Frontend, High, Release
