### ISSUE TITLE
[Bug]: 'source data exceeds 50-fields' and the page freezes

### ISSUE THREAD

**Issue by developer-honoru** [appsmithorg/appsmith#17162] opened 2022-09-29 00:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

'source data exceeds 50-fields' and the page freezes

Discord thread : https://discord.com/channels/725602949748752515/1024863192935051394/1024996651842154507

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/33475816/192911351-af295d5d-70e7-4cd0-9d5e-97dd8f5e4d60.png)
![image](https://user-images.githubusercontent.com/33475816/192911369-fed94606-3528-4be6-a868-38d3e94aeaf0.png)

### Version

cloud/ v1.8.3

**Comment by pranavkanade** [comment] 2022-09-29 06:18
@developer-honoru, could you please list down the steps to reproduce the issue? Or Share a loom video of the issue in action.

**Comment by billyrudi** [comment] 2022-09-29 08:23
i can share mi screen to show this problem!!!
there are many many tasks also on discord about this!
contact me and make a zoom so i can show you!

**Comment by Nikhil-Nandagopal** [comment] 2022-10-03 08:45
@billyrudi @developer-honoru we're working on this issue. Till then, we recommend not loading all the columns into the table unless they absolutely need to be displayed.

**Comment by johnezell** [comment] 2022-12-06 22:54
could we please have the MAX_ALLOWED_FIELDS as an .env variable for the on premise users?
source: https://github.com/appsmithorg/appsmith/blob/ab5eb0e325d1594ddb3679ddf0b30bdbd7a9eaa2/app/client/src/widgets/JSONFormWidget/constants.ts

I have several use cases where we need this to be many fields internally.

**Comment by dilippitchika** [comment] 2022-12-07 06:55
Hi @johnezell i would like to understand what the UX is you are optimising for here, because more than 50 fields on a form would be really hard for your users to use. Would you be willing to get on a call and discuss further? If yes, please find a slot here which works for you - https://calendly.com/dilip_pitchika/30min?month=2022-12

**Comment by saicharan-zemoso** [comment] 2024-05-28 08:59
Hi! I would like to know if this problem still exists. I have tried to reproduce this issue with 51 fields and 889 rows. The application did not freeze for me. I am still able to use the application. can any one provide the steps to reproduce this issue if the problem still exists. 
Thank you.

**Comment by saicharan-zemoso** [comment] 2024-05-31 08:48
Hello!
I was unable to replicate this issue and i have tested with 119 columns and 5600 records and found that this was resolved in v1.8.4

**Comment by akshayvijayjain** [comment] 2024-05-31 09:05
@saicharan-zemoso , please also add reference link, specifying issue was fixed in v.1.8.4

**Comment by saicharan-zemoso** [comment] 2024-05-31 10:11
Here the discord link for the issue: https://discord.com/channels/725602949748752515/1024863192935051394

**Comment by Nikhil-Nandagopal** [comment] 2024-05-31 10:41
Closing this since the user seems to say that the issue went away on discord itself

**Closed by Nikhil-Nandagopal** 2024-05-31 10:41 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, Production, Needs Triaging
