### ISSUE TITLE
[Bug]: Filling welcome form with keyboard navigation doesn't enable the Next button

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#14441] opened 2022-06-10 06:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fill up the welcome form with just keyboard navigation, no mouse interaction, then the Next button doesn't get enabled. I have to make selections in the dropdowns with the mouse go get the Next button to work.

### Steps To Reproduce

Recorded:

https://user-images.githubusercontent.com/120119/173003868-f1439c40-bdb1-4314-ad16-0b4bd990f215.mov

### Version

Self Hosted

**Comment by akash-codemonk** [comment] 2022-06-10 06:48
@sharat87 Is this on mac? It seemed to work there. Duplicate of https://github.com/appsmithorg/appsmith/issues/10634

**Comment by akash-codemonk** [comment] 2022-06-10 06:50
Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/10634

**Closed by akash-codemonk** 2022-06-10 06:50 UTC
Labels: Bug, Needs Triaging, Welcome Screen

**Comment by sharat87** [comment] 2022-06-10 13:06
@akash-codemonk, yeah, looks to be the same, but a point not noted there, is that the Next button is actually _disabled_ if I don't use the mouse. So, even if I fill everything with the keyboard, and try to click the just Next button with the mouse, even that is not possible. Hopefully, that's just another symptom of the same problem so, will be fixed. ✌️
