### ISSUE TITLE
[Feature]: Programmatically configure datasources

### ISSUE THREAD

**Issue by taylorbrosnan** [appsmithorg/appsmith#20886] opened 2023-02-22 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want a way to programmatically configure datasources like through an AppSmith API or at least some REST calls. 

### Why should this be worked on?

We have 50+ tenants that we would like to connect to our appserver. This is generating a massive number of datasources since we have prod and beta GQL API connections for each tenant coming in. I want to programmatically configure datasources so I don't have to make 100+ of them.

Link to Discord request: https://discord.com/channels/725602949748752515/1077717581022105670/1077718880702713866

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 11:30
Seems like a duplicate of your previous request

**Closed by Nikhil-Nandagopal** 2024-03-06 11:30 UTC
Labels: Enhancement
