### ISSUE TITLE
[Bug]: List | Reset | Does not work as expected

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#16578] opened 2022-09-06 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/188599298-c5045471-133e-4cfa-bdbb-647dfe77b791.mov

### Steps To Reproduce

1. D&D List widget & Button widget
2. Update onClick of Button widget to reset the List widget `{{resetWidget("List1",true)}}`
3. Deploy the app & Click on button
4. Observe: The 3 items in List are split to accommodate the list's page number
5. **Expected: Initially when 3 items are accommodated fine, moving items upon reset is confusing user**
6. Observe: Move to 2nd page & click reset button & see that nothing happens
7. **Expected: User should be moved to Page1 as a part of Reset action on List**

### Version

Prod/Release v1.7.15

**Comment by Nikhil-Nandagopal** [comment] 2022-09-06 14:59
Duplicate of #14727

**Closed by Nikhil-Nandagopal** 2022-09-06 14:59 UTC
Labels: Bug, App Viewers Pod, Needs Triaging, List Widget
