### ISSUE TITLE
[Feature] Add Appsmith watermark when Appsmith is embedded in other pages

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1790] opened 2020-11-18 20:42 UTC
## Summary
Create a watermark with Appsmith logo+link to Appsmith website when an Appsmith app is embedded it other pages.

## Motivation

This will help users understand that an app was built on Appsmith and help our branding.

**Comment by Nikhil-Nandagopal** [comment] 2021-02-10 11:28
Closing as duplicate of #1979

**Closed by Nikhil-Nandagopal** 2021-02-10 11:28 UTC
Labels: Enhancement, Frontend, Needs Design
