### ISSUE TITLE
[Bug]: Page tabs showing ellipsis even for small names

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#11480] opened 2022-02-28 09:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On windows, Page tabs are being shown at all times even for small names.

![image](https://user-images.githubusercontent.com/6636360/155960710-16f85206-8c37-4622-8aa7-9a8075cba162.png)

### Steps To Reproduce

Open any app on windows with at least 2 pages.

### Environment

Production

### Version

Cloud

**Comment by prsidhu** [comment] 2022-03-08 09:04
@jsartisan I'm unable to reproduce this bug. Could you help me with this?

<img width="1680" alt="Screen Shot 2022-03-08 at 2 33 27 PM" src="https://user-images.githubusercontent.com/5424788/157203753-930c4ebf-4580-4f15-8609-ed76acd39f96.png">

**Comment by jsartisan** [comment] 2022-03-08 11:19
@prsidhu this was happening for me on windows chrome

**Comment by prsidhu** [comment] 2022-03-09 03:05
@jsartisan Could you confirm if this is still happening?

**Comment by prsidhu** [comment] 2022-03-28 05:23
this issue is resolved in https://github.com/appsmithorg/appsmith/pull/12032

**Closed by prsidhu** 2022-03-28 05:23 UTC
Labels: Bug, Pages, Low, UI Building Pod, firefox, UI Builders Pod, Windows
