### ISSUE TITLE
[Bug]: Country selector in phone input shows incorrect flag

### ISSUE THREAD

**Issue by zhirzh** [appsmithorg/appsmith#17397] opened 2022-10-08 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dropdown shows incorrect flag (in some cases) when selecting a country which shares dial code with another country

Example: select UK (dial code `+44`) but flag shown if of Guernsey

Once any such country is selected, other countries with same country code are also shown as selected

<img width="400" alt="Screenshot 2022-10-09 at 12 10 54 AM" src="https://user-images.githubusercontent.com/8132723/194722728-7741d7f3-6184-496d-be41-094ad8a91a0e.png">

---

List of duplicates in [`ISDCodeOptions` list][1]

```
 +44 : Guernsey, Isle of Man, Jersey, United Kingdom
 +47 : Norway, Svalbard and Jan Mayen
 +61 : Australia, Christmas Island, Cocos (Keeling) Islands
+262 : Mayotte, Reunion
+358 : Aland Islands, Finland
+500 : Falkland Islands (Malvinas), South Georgia and the South Sandwich Islands, 
+590 : Guadeloupe, Saint Barthelemy, Saint Martin
+595 : Guyana, Paraguay
+672 : Antarctica, Norfolk Island
```

[1]: https://github.com/appsmithorg/appsmith/blob/ab106455f2906f1a4e7a512c7e3d31f3d0d4695d/app/client/src/constants/ISDCodes_v2.tsx#L7

### Steps To Reproduce

- select any country with shared country code
- check if flag emoji matches that country's flag

### Version

cloud

**Comment by dilippitchika** [comment] 2022-10-17 16:06
Duplicate of #11101

**Closed by dilippitchika** 2022-10-17 16:06 UTC
Labels: Bug, App Viewers Pod, Low, Needs Triaging, Phone Input Widget
