### ISSUE TITLE
Add automatic focus on input name after adding an input to a query module

### ISSUE THREAD

**Issue by pedro-santos-rodrigues** [appsmithorg/appsmith#31967] opened 2024-03-20 22:51 UTC
- [Loom solution overview](https://www.loom.com/share/6269096b17dd4dfb974402da66c13091?sid=9d544198-34cf-439d-b9d7-595b027264cf)

Summary:
- Having the focus on input name automatically right after creating the input
- When the input is focused and the user presses “Tab” it should focus on the corresponding default value input

[More information about the problem](https://www.notion.so/appsmith/Users-struggle-to-find-how-to-rename-an-input-7ad46d1a28e94646a4bd03e83a017c3f?pvs=4)

**Comment by ashit-rath** [comment] 2024-03-26 11:21
@pedro-santos-rodrigues Is this duplicate of https://github.com/appsmithorg/appsmith/issues/32067?

**Comment by pedro-santos-rodrigues** [comment] 2024-03-26 11:23
Yes it is. Sorry didn't notice that this already exists. I'll delete #32067

**Comment by kamakshibhat-appsmith** [comment] 2024-03-29 07:03
https://github.com/appsmithorg/appsmith/issues/31967#issuecomment-2025755579

This is working already. Please ignore @ashit-rath

**Comment by kamakshibhat-appsmith** [comment] 2024-03-29 07:04
https://github.com/appsmithorg/appsmith/issues/31967#issuecomment-2025755579

This is working already. Please ignore @ashit-rath

**Closed** 2024-03-29 07:07 UTC
Labels: Task, Medium, Packages pod, Module creator, Query module
