### ISSUE TITLE
[Bug] Clicking on the Browser back navigation button the user navigated out off the application without sign out

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1060] opened 2020-10-06 17:46 UTC
## Steps to reproduce
1. LogIn to the application
2. Add some widgets 
3. add  some page 
4. Now click on the back navigation button of the browser
and observe that the user is taken back to login page of the application
5.  Now click on the forward navigation button of the browser
and observe that the user is taken to the different pages or into the application

**Comment by gagandeepp** [comment] 2020-10-11 09:46
please assign it to me

**Comment by mohanarpit** [comment] 2020-10-12 05:02
@gagandeepp It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by gagandeepp** [comment] 2020-10-16 17:41
@mohanarpit please share the steps to reproduce video and I am unable to do npm install on win 10 because of sentry,please help!

**Comment by Nikhil-Nandagopal** [comment] 2021-02-10 07:59
Closing this as it seems like an expected behaviour

**Closed by Nikhil-Nandagopal** 2021-02-10 07:59 UTC
Labels: Bug, Frontend, Login / Signup, Low, Platform, Release, hacktoberfest
