### ISSUE TITLE
[Docs]: Update Troubleshooting - Datasource

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16053] opened 2022-08-16 10:17 UTC
<p>User Query - <a href="https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100051921">https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100051921</a></p>
<p>Connecting to local database: Error - Connection refused</p>
<p>User sees errors like - io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /172.17.0.1:3306</p>
<p> </p>
<p> </p>

**Comment by Pranay105** [comment] 2022-12-07 09:43
Duplicate of [#568](https://app.zenhub.com/workspaces/user-education-pod-61c01739f309a80011b48267/issues/appsmithorg/appsmith-docs/568)

**Closed by Pranay105** 2022-12-07 09:43 UTC
Labels: Documentation, User Education Pod, Ready for Doc Team, A-Force, Doc Rehaul

**Comment by notacouch** [comment] 2023-01-05 19:48
Getting a 502 bad gateway error, looking into logs we see this:

> Application start up encountered an error: finishConnect(..) failed: Connection refused: /127.0.0.1:8091; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:8091\n

**Comment by notacouch** [comment] 2023-01-05 21:23
We rebuilt containers, and now get 503 error in browser. Going through logs MongoDB is restarting constantly, it has a versioning compatibility issue. I guess it automatically updated to v6 and failed or something?

**Comment by notacouch** [comment] 2023-01-05 22:47
Saw the 1.9.0 and 1.9.1 release notes, still trying to figure out what to do.
