### ISSUE TITLE
[Bug]: Can't go to next widget using single Tab.

### ISSUE THREAD

**Issue by utkarshDunzo** [appsmithorg/appsmith#15061] opened 2022-07-07 05:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When going to next widget single Tab doesn't seem to work, I have to press Tab twice to go to the next widget. Also it doesn't skip over the disabled widget, I need to press tab so many times to skip the disabled widgets. Is there any setting which needs to be changed for this?

### Steps To Reproduce

Take two input widgets and try to switch between them using a single tab.

### Version

Self Hosted 1.7.5

**Comment by dilippitchika** [comment] 2022-07-07 10:46
Thanks, for reporting this. This is indeed an issue, I will get this investigated.

**Comment by dilippitchika** [comment] 2022-07-07 10:47
@rahulramesha this looks like it's happening across all input type widgets at-least. Can you take a look once?

**Comment by dilippitchika** [comment] 2022-07-07 16:00
Thanks for triaging this Rahul, yes I will ask someone to take this up internally

**Comment by dilippitchika** [comment] 2022-07-13 06:57
Need to triage this better. For all labels within widgets, tabIndex="-1" should be present

**Comment by souma-ghosh** [comment] 2022-09-29 11:01
As discussed above, the labels within widgets should have tabIndex="-1".
Expanding on this further
Taking Currency Input Widget as an example:
1. First tab press focuses on the label - unnecessary, needs to be skipped
2. second tab press focuses on the currency sign, which is basically a disabled button with no onClick functionality - unnecessary, needs to be skipped
3. third tab focuses on the actual input area
4. fourth tab focuses on the up arrow button but this is not clearly communicated to the user since the highlight is still on the input box itself - should have highlighted the up arrow button (this can be done through code)
5. fifth tab focuses on the down arrow button - same problem as 4, necessary but not communicated to the user properly

So we need to work on this issue in 2 ways
1. Skip the elements that do not need to be in the tab order, e.g. - label, disabled button, any disabled widget
2. The element that gets the focus on pressing tab should get highlighted properly so user does not think that pressing tab is not working

This explanation can be extended to all other widgets
e.g. - Audio widget first tab focuses on the whole widget but there is no highlight at all. So user will feel pressing tab did not work. Second tab focuses on the play button and it gets highlighted correctly as well so this is fine. Subsequent tab presses work perfectly.
@dilippitchika

**Comment by roycegerikchua** [comment] 2023-02-20 17:52
hi how do i set tab index to -1?

**Comment by dilippitchika** [comment] 2023-02-21 05:38
Hello @roycegerikchua we have fixed this issue in v1.9.3 and above, are you using our cloud version or self hosting it?

**Comment by dilippitchika** [comment] 2023-02-21 05:38
Closing as duplicate of #7757

**Closed by dilippitchika** 2023-02-21 05:38 UTC
Labels: Bug, App Viewers Pod, community, Needs Triaging, Keyboard Shortcuts

**Comment by roycegerikchua** [comment] 2023-02-21 06:58
Hi Appsmithorg/Appsmith,

I am using Appsmith Community v1.8.13.

I will check on how to update.

Thanks!

Gerik
