### ISSUE TITLE
[Bug] Need a better way to indicate to the user that a bracket is present/missing the other pair (not closed/open/extra bracket present in the code) No error is displayed currently.

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7158] opened 2021-09-06 11:27 UTC
## Description
Need a better way to indicate to the user that a bracket is present/missing the other pair (not closed/open/extra bracket present in the code). No error is displayed currently.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f017e127ab93449ba1818a7de0c277ea-00001.gif)](https://www.loom.com/share/f017e127ab93449ba1818a7de0c277ea)

**Comment by Nikhil-Nandagopal** [comment] 2021-11-10 13:08
Duplicate of #6923

**Closed by Nikhil-Nandagopal** 2021-11-10 13:08 UTC
Labels: UX Improvement, Actions Pod, Low, JS Linting & Errors, FE Coders Pod
