### ISSUE TITLE
[Enhancement] Mongo Atlas is returning limited records

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2290] opened 2020-12-21 05:47 UTC
## Description

The user reported that their query is returning only 101 records when there are multiple records in the DB

**Comment by sumitsum** [comment] 2020-12-21 07:01
Hi @NandanAnantharamu @mohanarpit, reproducing the slack discussion here for record purpose: 

find() and aggregate() operations have an initial batch size of 101 documents by default. Subsequent getMore operations issued against the resulting cursor have no default batch size, so they are limited only by the 16 megabyte message size.
https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/

![Screenshot 2020-12-21 at 12 16 29 PM](https://user-images.githubusercontent.com/1757421/102748556-655ae100-4388-11eb-84ac-0ff52adeb568.png)

**Comment by Nikhil-Nandagopal** [comment] 2020-12-23 06:18
Changing this to a feature request to improve the mongo db experience since this is not a bug and part of the mongo documentation

**Comment by mohanarpit** [comment] 2021-03-03 13:51
Closing as this is expected behaviour.

**Comment by areyabhishek** [comment] 2021-03-25 08:58
Can we add this on the MongoDB query page? This seems to be a common query.

**Comment by areyabhishek** [comment] 2021-04-24 22:39
Can we add this instruction on the Mongo query page? I just spent 20mins helping a user because they didn't know about batchsize.some sort of instruction on the page would be awesome.

Also can we show the total number of records fetched in the query response?

**Comment by vasani-arpit** [comment] 2021-05-22 17:21
For me simple solution was to use `batchSize` field/property in the query and set to it higher number. by default it is 101.

**Comment by areyabhishek** [comment] 2021-05-22 19:03
@vasani-arpit Did you figure this out on your own? We are improving the Mongo query experience to eliminate the need to think about batch sizes

**Comment by vasani-arpit** [comment] 2021-05-23 04:38
You can enable server side paging and use skip and limit to get the only records you need. 

In my case, I only worry about UX not about performance nor about how things work. Updating a batchSize is the only feasible solution I see for my case. I found about it from here https://docs.mongodb.com/manual/reference/command/find/

**Comment by Nikhil-Nandagopal** [comment] 2021-07-12 12:20
Our limit field now updates the batchsize as well

**Comment by awanishraj** [comment] 2021-09-15 07:47
The Find query now gives more results thanks to the limit field, but the aggregate query still returns 101 records, and there is not limit field setting.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-15 08:27
@awanishraj thanks for pointing this out. Re-opening this issue.
@trishaanand @nidhi-nair @sumitsum

**Comment by awanishraj** [comment] 2021-11-08 07:06
@Nikhil-Nandagopal, I understand that the team must be busy with a lot of features. For the time being, is there any workaround for the "aggregation 101 record limit" issue?

**Comment by Nikhil-Nandagopal** [comment] 2021-11-08 07:13
@awanishraj you can do this by increasing the batchSize value in the cursor
cursor: { batchSize: <num> }

**Comment by awanishraj** [comment] 2021-11-08 07:46
Sorry, I couldn't find an option to provide cursor options. PFA screenshots:

### Query Page:
![Screenshot 2021-11-08 at 1 13 24 PM](https://user-images.githubusercontent.com/6928709/140702842-7b17a4f3-71f1-4225-8de7-b40e77b268fd.png)

### Settings Page:
![Screenshot 2021-11-08 at 1 13 33 PM](https://user-images.githubusercontent.com/6928709/140702900-18cf2c2d-0907-4c22-8e17-0f7dbc95d9c6.png)

**Comment by awanishraj** [comment] 2021-11-08 07:59
Understood, I should be using the RAW command instead of aggregate. Thanks.

**Comment by Nikhil-Nandagopal** [comment] 2021-11-08 08:28
@awanishraj  yes! sorry I didn't explain that very well :)

**Comment by trialsin** [comment] 2021-12-17 17:45
To clarify follow a example in MongoDB 3.6:

```
{
  "aggregate": "coolecion_name",
  "cursor": { "batchSize": 1000 },
  "pipeline": [
    {$match: {}},
    {$lookup: {}},
    {$project: {}}
    {...}
  ]
}
```

**Closed** 2022-01-10 16:42 UTC
Labels: Enhancement, Backend, Datasources, Actions Pod, High, BE Coders Pod
