### ISSUE TITLE
"Cannot find page with id" error

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#35575] opened 2024-08-09 10:37 UTC
[More info](https://www.notion.so/appsmith/A-force-Critical-Issue-with-Appsmith-Application-Cannot-find-page-with-id-error-impacting-usab-441e9312f3eb4fef98e5c7b74207d28c?pvs=4)
The APIs fail with error: Hex-encoded string must have an even number of characters
https://theappsmith.slack.com/archives/C0341RERY4R/p1723357416990659?thread_ts=1723144994.825399&cid=C0341RERY4R

**Comment by NilanshBansal** [comment] 2024-08-14 08:05
The issue is only occurring for one workspace, the other workspace works fine. The user is unblocked.
As per the logs error seen is: Hex-encoded string must have an even number of characters
This error occurred in the past when `gitApplicationMetdata` field in the database could not be encrypted due to some issue. Also the application is git connected.
Assigning to @sondermanish and @nidhi-nair to take this forward.
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1723357416990659?thread_ts=1723144994.825399&cid=C0341RERY4R

**Comment by riteshkew** [comment] 2024-09-25 17:51
Very specific to this scenario and workspace. Closing this for now and considering this to be resolved as part of move to Git native integration. Would reconsider on newer occurence.

**Closed by riteshkew** 2024-09-25 17:51 UTC
Labels: Git Product, Task, Git Platform Pod, Git performance
