### ISSUE TITLE
[Bug] Delete method for Google Sheets row does not delete rowIndex value

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6145] opened 2021-07-26 15:17 UTC
## Description
Trying to delete a Google Sheet row from 'Delete row' method does not delete the row indicated in rowIndex

### Steps to reproduce the behaviour:
1. Add Google Sheets datasource
2. Select method as 'Delete row'
3. Select sheet name and row header
4. Indicate row deletion on 'Row Index'

In the video, there are 2 rows that contain the word 'nice' and after deletion there's only 1 row left.

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

Sheet before deletion: ![image](https://user-images.githubusercontent.com/79509062/127013633-231cdb26-82ea-4d03-b803-0bea567c9a7a.png)

https://www.loom.com/share/baac0f51b9fa4c468c14b22932fa9e87

**Comment by nidhi-nair** [comment] 2021-07-27 05:44
@ramsaptami The reference for row indices starts from 0, relative to the table heading. This means that as in your case the table header is at Google Sheet Row 1, the row_index: 0 refers to Google Sheet Row 2, and so on. I am closing this issue since this is by design.

**Closed by nidhi-nair** 2021-07-27 05:44 UTC
Labels: Actions Pod, Bug, Critical, Google Sheets
