### ISSUE TITLE
[Feature] Enable populating forms using JSON objects

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4038] opened 2021-04-16 16:02 UTC
The use case for forms is generally a `POST` or `PUT` request that works with existing data structures in a user's backend. Given that this data structure is easily available for the user, we should allow creating default versions of forms with the help of these data structures, so that users don't have to drag and drop 20 labels and 20 inputs fields to get their first version of form running.

**Comment by Nikhil-Nandagopal** [comment] 2021-04-19 05:04
Duplicate of #1724

**Closed by Nikhil-Nandagopal** 2021-04-19 05:04 UTC
