### ISSUE TITLE
[Bug]: Moved JS obj can still be seen on the source page 

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#27654] opened 2023-09-27 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Stale data still remains on the page even afetr successfully moving it to the next page

Video can be found here 

[screen-capture.webm](https://github.com/appsmithorg/appsmith/assets/134914630/cf6eadbd-5cc9-4aed-b39d-b72d4cee96ff)

### Steps To Reproduce

Steps : 
1. Create a JS oBJ
2. Copy it to the same page
3. Move it to different page
4. Go back to previous page from where js obj was moved 
5. Observe moved JS obj still shown 

### Environment

Production

### Version

Appsmith v1.9.39-SNAPSHOT

**Comment by bharath31** [comment] 2023-10-12 13:43
@kavitasmoolya this is a duplicate of #27516. Closing this in favour of the original ticket.

**Closed by bharath31** 2023-10-12 13:43 UTC
Labels: Bug, Production, Needs Triaging, JS Objects, FE Coders Pod, Medium
