### ISSUE TITLE
[Bug] Fit Appsmith editor for smaller resolution screens

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2317] opened 2020-12-22 20:14 UTC
## Description

Appsmith editor resolution doesn't fit well on smaller screens. Need a way to reduce horizontal scroll on such screens.
https://www.loom.com/share/5297384d90da455ca43ce22fba941df8
The below video is on a Macbook Pro 13inch 1440*900 resolution.

**Comment by Nikhil-Nandagopal** [comment] 2021-02-10 10:32
Closing as duplicate of #2577

**Closed by Nikhil-Nandagopal** 2021-02-10 10:32 UTC
Labels: Bug, Editor, Low, Platform, UI Building, UI Building Pod
