### ISSUE TITLE
[Bug]: Parametred qry do not correctly load on load page due  on bad incoming entities response

### ISSUE THREAD

**Issue by cdoudet** [appsmithorg/appsmith#10970] opened 2022-02-08 11:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My main qry is like this:
```
select  {{Qry_centrale6_somme.data.find(el => el.centrale6==="MAXEDA").sum}} as value
from dim_date b
where ......
```
run qry on page load is setted for both qry

on refresh page or app start the main qry return blank lines 

the problem is that this main qry is launched before the result of {{Qry_centrale6_somme.data.find(el => el.centrale6==="MAXEDA").sum}} 
so the result is undefined and i get the correct line number but not the correct data

I recently migrated to1.6.8 and this pbm does not exist in the previous version 1.5.9

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d9a9bab6a3734f978a56849e72d33fe2-00001.gif)](https://www.loom.com/share/d9a9bab6a3734f978a56849e72d33fe2)

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment] 2022-02-14 06:16
@cdoudet I'm not able to reproduce this on our end. Could you share a an example application where you can reproduce this behavior?

**Comment by Nikhil-Nandagopal** [comment] 2022-02-18 09:36
@cdoudet we're closing this as we're not able to reproduce it. Do let us know if you can help us with the steps

**Closed by Nikhil-Nandagopal** 2022-02-18 09:36 UTC
Labels: Bug, Actions Pod, Critical, community, FE Coders Pod, OnPageLoad
