### ISSUE TITLE
[Bug]The widget size reduces when there are drag and dropped in the container widgets 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7557] opened 2021-09-17 04:22 UTC
## DescriptionThe widget size reduces when there are drag and dropped in the container widgets 

[What happened]The widget size reduces when there are drag and dropped in the container widgets 

### Steps to reproduce the behaviour:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9f72f343550047d0b47510e4b74feb8b-00001.gif)](https://www.loom.com/share/9f72f343550047d0b47510e4b74feb8b)
### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser  chrome
- Environment production

**Comment by mohanarpit** [comment] 2021-09-17 04:38
Closing as this is expected behaviour. This happens because we want to ensure that you can move the widgets from the container to the canvas and back without having to re-size them.

**Closed by mohanarpit** 2021-09-17 04:38 UTC
Labels: Bug, Widgets, Low, Production, UI Building Pod, Needs Triaging
