### ISSUE TITLE
[Feature]: Expandable rows in Table Widget

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#11478] opened 2022-02-28 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a widget to create expandable rows or add an option to make rows expandable in table widget.
![U3n7t](https://user-images.githubusercontent.com/89374972/155954898-f7f638bb-ff8c-4cbd-bc4f-1e4ce14d1bbf.png)

### Why should this be worked on?

Feature request on discord

https://discord.com/channels/725602949748752515/760761686549463060/947310444610215957

**Comment by dilippitchika** [comment] 2022-03-03 18:15
@rashmi-rai this is a duplicate of tree widget #5415. Tracking this there already.

**Closed by dilippitchika** 2022-03-03 18:15 UTC
Labels: Enhancement, Table Widget, App Viewers Pod, UI Building Pod
