### ISSUE TITLE
[Bug]Delete form widget fails intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#7737] opened 2021-09-22 15:40 UTC
Steps:

1. As a part of the form widget spec we see tests related to delete widget failing intermittently.
2. Delete from properties / Delete from the keyboard is failing intermittently, this is after we optimized the test

**Comment by somangshu** [comment] 2021-09-29 08:36
@NandanAnantharamu what is expected here, Looks like this should be assigned to the owner of the test optimization

**Comment by NandanAnantharamu** [comment] 2021-09-29 08:45
@somangshu as discussed, this is an intermittent issue, not a cypress issue.

**Comment by somangshu** [comment] 2021-09-29 08:53
@vivekverma2312 @YogeshJayaseelan can you verify this, if possible we will need some reproducible steps. 

@NandanAnantharamu in case you know how to better debug this, Please let us know, Right now on cypress the only error i see is `CypressError: Timed out retrying`, I suspect something to do with eval here

**Comment by NandanAnantharamu** [comment] 2021-09-29 08:58
@somangshu CypressError: Timed out retrying, this is seen because after delete the @updateLayout call happens. Since the Delete action hasn't worked the call hasn't happened and the test failed.

**Comment by dilippitchika** [comment] 2022-01-12 10:48
Is this still happening @NandanAnantharamu?

**Closed** 2023-04-20 09:00 UTC
Labels: Bug, App Viewers Pod, Low, Form Widget, UI Builders Pod, Automation
