### ISSUE TITLE
[Bug]: The appsmith name is displayed with the dotted lines in github commit message

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30629] opened 2024-01-25 10:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The appsmith names is displayed with the dotted lines in github commit message
![image](https://github.com/appsmithorg/appsmith/assets/45958978/d76bc108-0d03-402b-ace6-13e12d123406)

### Steps To Reproduce

1. take a local pull with " docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.35"
2. Now import any bigger app
3. Now upgrade the instance keeping the old stack
4. docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:release
5. now open the git connected app te auto commit bar is displayed
6. go to the git repro where the app is commited 
7. Click on commit check for the appsmith text

### Environment
Release

### Version

v.1.10

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 10:17
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by brayn003** [comment] 2024-04-23 13:59
The line is getting wrapped. This is an expected behaviour. Closing it for now

**Closed by brayn003** 2024-04-23 13:59 UTC
Labels: Bug, High, Production, Needs Triaging, Git Version Control, Git Pod, Git Auto-commit
