### ISSUE TITLE
[Bug]: The sample datasource Movies throws timeout error when user tried to fetch the data

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9799] opened 2021-12-15 11:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sample movies Datasource throws timeout error user tried to fetch the data
![image](https://user-images.githubusercontent.com/45958978/146178133-aa037c5e-4609-4f9c-a0ef-31b532fb92c3.png)

### Steps To Reproduce

1. Go to Create new data source tab
2. click on Movies sample data source
3. Create a new query 
4. Try to fetch the data 
5. the timeout error is displayed

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment] 2021-12-20 05:43
@RakshaKShetty I tried these steps a few times, and didn't encounter a time-out. Would you please check again?
If it is still happening, maybe a good idea to do this on a call because I might be missing some crucial step in the reproduction.

**Comment by rohan-arthur** [comment] 2021-12-20 09:04
@sharat87 fixed the project settings and this is working again. Closing the issue.

**Closed by rohan-arthur** 2021-12-20 09:04 UTC
Labels: Bug, Datasources, Actions Pod, Critical, Release, Needs Triaging, Mongo, BE Coders Pod
