### ISSUE TITLE
[Bug]: Refactor of API, widget name or function name on an idle app does not happen

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8968] opened 2021-11-02 07:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Refactoring of widget name or function works as expected for apps that are not in idle state (being picked up after a long time) but for apps where widgets/function names are present in JS object or API names - refactor does not happen all the time.

### Steps To Reproduce

1. Use widget names in JS object and make a JS call from any widget. Leave the app be on the tab and come back the next day or so and try to refactor any name and observe that some refactor does not work

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment] 2021-11-08 11:52
@ramsaptami is this same case for APIs and widgets too?

**Comment by ramsaptami** [comment] 2021-11-15 16:43
@ApekshaBhosale that's right, this applies to widgets and API

**Comment by ApekshaBhosale** [comment] 2021-11-25 08:14
@ramsaptami can we make this issue more generic to take care of all scenarios please?

**Comment by ramsaptami** [comment] 2021-12-08 12:44
A consistent way to repro this - use autocomplete to change function names 

https://www.loom.com/share/474c207440d34ee694b6867472f51038

**Comment by Nikhil-Nandagopal** [comment] 2022-01-06 10:19
@ramsaptami @ApekshaBhosale is this still an issue?

**Comment by ramsaptami** [comment] 2022-01-06 10:31
This still happens on release today @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 08:03
Closing because I don't think we can reproduce it properly

**Closed by Nikhil-Nandagopal** 2024-03-07 08:03 UTC
Labels: Bug, Low, Production, BE Coders Pod, Entity Refactor, Data Platform Pod
