### ISSUE TITLE
[Bug]: Unable to view pdf document on Document viewer widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10756] opened 2022-01-31 10:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we map a filepicker widget to document viewer widget to display the .pdf document, it says "The content is blocked.Contact the site owner to fix the issue."

Sharing video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7ac19196d6fb4507a0381cb58ee2c6bd-00001.gif)](https://www.loom.com/share/7ac19196d6fb4507a0381cb58ee2c6bd)

### Steps To Reproduce

1. Add Document viewer widget
2. Add File Picker widget and bind it with Document viewer {{FilePicker1.files[0].data}}
3. Upload .pdf file using file picker to display file on Document viewer
4. Observe the error on Document viewer widget

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment] 2022-01-31 10:56
@techbhavin did we support base 64. What has possibly changed that its not working anymore. Please check on an urgent basis.

**Comment by chandannkumar** [comment] 2022-02-03 06:03
@techbhavin Issue still exists on release

**Comment by techbhavin** [comment] 2022-02-04 07:41
@chandannkumar  as we discuss yesterday  
here something is wrong in only the release version. it is working fine in PROD and the local version.

cc: @somangshu

**Comment by somangshu** [comment] 2022-02-04 08:27
It probably would make sense to verify this after the release. There are no changes here, we fail to understand how it fails on release env only

**Comment by somangshu** [comment] 2022-02-16 06:02
@techbhavin is this fixed, Why are we closing this?

cc @vivekverma2312 @YogeshJayaseelan

**Comment by techbhavin** [comment] 2022-02-16 06:17
Here status is done so I moved it to closed. can we reOpen this? 

cc: @somangshu  @vivekverma2312  @YogeshJayaseelan

**Comment by somangshu** [comment] 2022-02-16 06:21
I dont see this fixed, Please test and take a call further @techbhavin

**Comment by chandannkumar** [comment] 2022-02-16 06:33
![image](https://user-images.githubusercontent.com/95341241/154209193-2404c49a-6608-4905-b156-5ca9bf01de29.png)
Error in console @techbhavin 

cc: @sharat87

**Comment by somangshu** [comment] 2022-02-16 06:40
Keeping it deprioritised because the issue is persistent to the release environment. @chandannkumar please verify if possible

**Comment by chandannkumar** [comment] 2022-02-16 06:53
This issue only occurs in release environment as of now and works normal on production

**Comment by sharat87** [comment] 2022-02-16 09:12
Fixed CSP. Added `data:` to `frame-src` and now this works.

**Comment by chandannkumar** [comment] 2022-02-16 09:49
Tested and working fine on release

**Closed** 2022-02-16 10:06 UTC
Labels: Bug, QA, App Viewers Pod, Low, UI Building Pod, Document Viewer Widget
