### ISSUE TITLE
[Bug] List widget doesn't show text items in deploy mode

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4624] opened 2021-05-21 21:56 UTC
## Description
Video of the bug:
https://www.loom.com/share/e0bc34839303433386d307024c2c96ed

**Comment by jsartisan** [comment] 2021-06-14 09:41
Closing this as I was not able to reproduce this. I will revisit if this happens again.

**Closed by jsartisan** 2021-06-14 09:41 UTC
Labels: Bug, High, High impact, List Widget, UI Building, UI Building Pod, Widgets
