### ISSUE TITLE
[Bug]: Tabs in the API page overlap with corresponding metrics

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29673] opened 2023-12-18 05:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The tabs in the API query page overlap with the metrics such as `Status`.
<img width="1440" alt="Screenshot 2023-12-18 at 11 00 01 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/4f7de296-797a-435b-880a-e8df50ce3935">

**P.S:** we see the `Size` metric on in https://release-ee.appsmith.com/. Tried the same query on https://release.app.appsmith.com/ & https://app.appsmith.com/ and was not able to see `Size` (below are the screenshots from release & prod)

Release:
<img width="1440" alt="Screenshot 2023-12-18 at 11 21 28 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/3f6fd7bb-70f2-4368-be50-bb536db59892">

Prod:
<img width="1440" alt="Screenshot 2023-12-18 at 11 21 34 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/fe8d4fc2-2416-4946-a9b7-7028b32715c9">

### Steps To Reproduce

1. Go to https://release-ee.appsmith.com/ and open an app.
2. Create an API query & enter https://restcountries.com/v3.1/all as the URL.

### Environment

Release

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 10:17
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by rohan-arthur** [comment] 2024-03-26 09:01
not reproducible anymore, closing this

**Closed by rohan-arthur** 2024-03-26 09:01 UTC
Labels: Bug, UI Improvement, Low, Production, Needs Triaging, Query Forms, BE Coders Pod, Integrations Pod
