### ISSUE TITLE
[Bug]: CI failure: Randomly Super user api does not respond within 30000ms

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#22147] opened 2023-04-06 05:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in CI, where on creating a user in welcome page and when we click on **Make your first app** button super user api (/api/v1/users/super) is not responding and new page doesn't load

![cypress-screenshot (18)](https://user-images.githubusercontent.com/119562824/230282121-2ef20082-e5c0-4699-9f9a-7cc29d7ce2de.png)
![cypress-screenshot (19)](https://user-images.githubusercontent.com/119562824/230302128-8be03cd0-092a-4330-b257-f6f44a409a52.png)

### Steps To Reproduce

1. Navigate to welcome page
2. Create a user
3. Set usage data preference
4. Click on **Make your first app** button

### Environment

Release

### Issue video log
https://user-images.githubusercontent.com/119562824/230301995-058e5323-0c0a-4330-bea9-2ebdf7b8e49e.mp4
https://user-images.githubusercontent.com/119562824/230302797-5d389773-bd15-477f-8b4a-95c48098504b.mp4
### Version

Release

**Comment by Aishwarya-U-R** [comment] 2023-04-06 06:45
Error snap from Cypress:
<img width="571" alt="Screenshot 2023-04-06 at 12 14 02 PM" src="https://user-images.githubusercontent.com/91450662/230293233-f9205bc0-4138-4eec-b91e-5c4b32d0da2d.png">

**Comment by Aishwarya-U-R** [comment] 2023-04-06 07:19
Another Recent failure -[ /QueryPane/Mongo_Spec.ts](https://cloud.cypress.io/projects/eyxvp8/runs/32098/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression_TestSuite%2FServerSideTests%2FQueryPane%2FMongo_Spec.ts%22%2C%22value%22%3A%22%5B%5C%226fe12736-bd53-48f3-8bc2-5595ef80985c%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D)

**Comment by Vijetha-Kaja** [comment] 2023-04-12 04:58
Recent runs with above failure:
https://cloud.cypress.io/projects/n14p1y/runs/6088/test-results
https://cloud.cypress.io/projects/n14p1y/runs/6081/test-results/220d1d72-03e2-4b89-af20-c9ddee43829b

**Comment by Vijetha-Kaja** [comment] 2023-04-19 04:59
Recent run with above [run](https://cloud.cypress.io/projects/n14p1y/runs/6173/test-results)

**Comment by Vijetha-Kaja** [comment] 2023-04-21 05:19
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/6223/test-results/789703f3-c8cc-4fe7-9aec-41a16a0c4c5d) with above failure

**Comment by Vijetha-Kaja** [comment] 2023-05-10 12:04
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/33871/test-results/eaab305d-fd43-49df-8b0d-f5e89c53c15d) with above failure - [logs](https://github.com/appsmithorg/appsmith/files/11441589/1_ci-test.ci-test.0.txt) , [logs2](https://github.com/appsmithorg/appsmith/files/11441631/17_ci-test.ci-test.16.txt)

**Comment by Aishwarya-U-R** [comment] 2023-05-10 16:21
Reopening this bug - since the attached PR only adds additional log to debug this issue further & not exactly solving the issue with said api.

**Comment by nsarupr** [comment] 2023-05-12 06:55
Debugged the issue with the CI, but was not able to get a proper resolution on the same. 
Have merged a PR into release: https://github.com/appsmithorg/appsmith/pull/23140 which will capture the duration logs. I will be looking at the observations and then take it from there.

**Comment by Aishwarya-U-R** [comment] 2023-05-15 12:40
Reopening this bug - since the attached PR only adds additional log to debug this issue further & not exactly solving the issue with said api.

**Comment by Aishwarya-U-R** [comment] 2023-05-25 01:49
Do not observe this issue in recent CI runs, hence closing this in favor of fix applied for same.

**Closed by Aishwarya-U-R** 2023-05-25 01:49 UTC
Labels: Bug, Performance Pod, QA, High, Needs Triaging, Team Managers Pod, Super Admin, DevOps Pod, RBAC, CI impacted, Performance
