### ISSUE TITLE
[Bug] Deploy Preview - List widget breaks on an error in the text widget inside the list widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5242] opened 2021-06-18 04:42 UTC
## Description
Deploy Preview : It is observed that List widget breaks on an error in the text widget inside the list widget 

**Expected Result:**
If there are any errors the list widget should not break

**Actual Error:**
Error on text widget breaks list widget 

### Steps to reproduce the behaviour:

1.1.Launch Appmsith app in the Deploy preview - https://deploy-preview-4189--appsmith-editor-ce.netlify.app/
2.Drag and Drop list widget
3.Place text widget inside any of the item container 
4.Open property pane of text widget 
5.Click on visible JS
6.Pass the following query - {{currentItem.name === “Bulbasaur”}}
7.Click on visible JS again and observe

**videoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0847770baabc4cd5a1e9e7812ce61b3a-00001.gif)](https://www.loom.com/share/0847770baabc4cd5a1e9e7812ce61b3a)

### Important Details

Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [Safari]
Environment [Deploy Preview]

**Comment by SatishGandham** [comment] 2021-09-17 08:59
@YogeshJayaseelan  The code you pasted includes these quotes ”””””””””
Not sure how text input accepted that, but they should """""".

Please confirm and close this issue. If you are double quotes are posted as apostrophe, please raise another issue.

**Comment by YogeshJayaseelan** [comment] 2021-09-22 05:48
@SatishGandham This is to confirm you that the quotes are in regular formats """ and not used italic formats ”””””””””. Hence keeping this issue open

**Comment by Tooluloope** [comment] 2022-07-03 22:12
Cant reproduce

**Closed by Tooluloope** 2022-07-03 22:12 UTC
Labels: Bug, App Viewers Pod, Low, List Widget, Deploy Preview
