### ISSUE TITLE
[Bug]: IP address URL not valid in the Document Viewer widget

### ISSUE THREAD

**Issue by guilhermep** [appsmithorg/appsmith#9704] opened 2021-12-10 15:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting the URL pointing to an IP address in a Document Viewer widget, a validation error occurs:
![image](https://user-images.githubusercontent.com/3932327/145601679-679e1d08-2a15-45b8-b824-30352f8791e7.png)

### Steps To Reproduce

1. Insert a Document Viewer widget.
2. Set the document link as a URL with an IP address as host.

### Environment

Production

### Version

Self-Hosted

**Comment by dilippitchika** [comment] 2021-12-15 14:08
Hi, @guilhermep I am unable to replicate the issue. Please see my screenshot.
![IP address PDF url](https://user-images.githubusercontent.com/19730984/146200317-b1d61b9a-9b92-46ea-9dc8-8f9ab51eb531.png)

I can see that the url you pasted does not end with a .pdf or any valid file formats. Could you please check and let me know if you are facing this issue only when the url doesn't end with a valid file type? or you are still facing it for IP addresses with a valid file extension?

Please see the supported file types listed below
![File types](https://user-images.githubusercontent.com/19730984/146200977-bf043053-b010-4301-a218-ea7fecff619c.png)

**Comment by guilhermep** [comment] 2021-12-15 15:21
Indeed, it works with an IP address + file extension. But I would expect a URL to be valid even without the extension. It is not uncommon for REST APIs to serve files like this. 

A named host works:
![image](https://user-images.githubusercontent.com/3932327/146211454-c51cdc75-631c-434e-a431-cd221ae886cc.png)

IP host works only with extension:
![image](https://user-images.githubusercontent.com/3932327/146211733-47040724-cce4-4626-9c3b-0cb10cbbee05.png)
![image](https://user-images.githubusercontent.com/3932327/146211915-3cb6df0b-64e6-47e4-a781-8043f513dee8.png)

**Comment by somangshu** [comment] 2021-12-16 06:39
@guilhermep we depend on the extension to understand how to load the files (with the appropriate viewer), Since we manage the complexity under the hood, We need the extension

**Comment by somangshu** [comment] 2021-12-16 06:40
@techbhavin again, Can we check the URL headers to understand the file extension? This will be convenient for the user!

**Comment by techbhavin** [comment] 2021-12-16 10:46
@somangshu looks like we can fix this issue to improve our URL checking validation. the library is already checking the URL header for understanding file type. checking header is might be a complex part from our side.

**Comment by somangshu** [comment] 2021-12-17 08:57
@techbhavin I still don't understand, Can we access the ext even if its from within the package. Would not checking this on our end cause problems.

**Comment by techbhavin** [comment] 2021-12-17 11:05
@somangshu  here the issue is we are adding validation to check URL is valid or not. so we can improve our validation checking function. so this issue is resloved

**Comment by Nikhil-Nandagopal** [comment] 2021-12-20 05:49
@techbhavin so can we fix the validation and raise a PR to close this?

**Comment by somangshu** [comment] 2022-01-04 13:22
@guilhermep the first url from google load because the component at this point understands it needs to use the google viewer to display the doc. Otherwise the file extension is required to identify the doc viewer to be used since we cannot access the headers on the frontend (to identify the file type from content-type) unless exposed. Check [this answer](https://stackoverflow.com/a/66291644/5826265) out to find more. My stand here is that the file type is stored in the backend and identified through the URL on frontend (since we also accept all file types).

@dilippitchika @techbhavin on that note, Do we still need this change if the IP + EXT worked from before, What are we really changing here?

cc @vivekverma2312 @Nikhil-Nandagopal

**Comment by techbhavin** [comment] 2022-01-05 12:14
@somangshu  @dilippitchika  
we can decline related PR.  Here we only added validation to allow  IP without EXT URL.

**Comment by dilippitchika** [comment] 2022-01-05 12:30
@somangshu @techbhavin no other change. We can decline the PR.

**Comment by somangshu** [comment] 2022-01-05 12:37
In that case we can close both the pr and issue @techbhavin

**Closed** 2022-01-05 13:43 UTC
Labels: Bug, App Viewers Pod, High, UI Building Pod, community, Document Viewer Widget
