### ISSUE TITLE
[Bug]: List V2 onItemClick Event Not Run When Clicking on Widgets Placed Inside The List Item

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#21409] opened 2023-03-14 22:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a user clicks on a list item that contains other widgets such as images or text, the onItemClick event does not get fired. It only gets fired when clicking on the container/blank space.

### Steps To Reproduce

1. Add a List widget (List v2).
2. Add some images and text inside the list items.
3. Add an onItemClick event.
4. Click on the images or text and note that the onItemClick event does not run.

### Environment

Production

### Issue video log

https://cdn.discordapp.com/attachments/1082691051929735179/1082696640504287363/vokoscreenNG-2023-03-07_16-03-30.webm

### Version

v1.9.12

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_83tjg)

**Comment by somangshu** [comment] 2023-03-15 10:34
@Tooluloope lets traige the priority and impact. We should take this up basis that

**Comment by kamakshibhat-appsmith** [comment] 2023-03-15 10:43
I remember this was a product decision to run the onItemClick events only when we click on the empty area as the child widgets can have their own click events @dilippitchika Shouldn't this be more of a feature and not a bug ?

**Comment by Tooluloope** [comment] 2023-03-15 10:47
@kamakshibhat-appsmith, yeah, it was a product decision, but we might need to improve it to cater to both people that want 
1. Child widget selection should trigger List Item Event
2. Only clicking the container should trigger the List item Event

**Comment by somangshu** [comment] 2023-03-15 11:04
This is just [event bubbling](https://www.freecodecamp.org/news/event-bubbling-in-javascript/#:~:text=What%20is%20Event%20Bubbling%3F,gets%20to%20the%20root%20element.), Similar to container widget having a [onClick action](https://github.com/appsmithorg/appsmith/issues/8330), the nested onClick action should still work separately. I disagree to user having to configure something like this again, its just an option for no reason

**Comment by dncpax** [comment] 2023-03-15 12:34
Hi there. Just my 2cents... that's a change from V1 that implies a rewrite when replacing with a v2 list. we could depend on onitemclick to react to clicking on an item. now we have to depend on having clickable widgets in items on the list and duplicate onclick code in all of them. also text boxes are not clickable so any content we show using text boxes will not react to clicks... IMHO this was not an improvement and feels very strange to the user, it feels the app somehow does not react sometimes. there's no one to explain you have to click on certain clickable areas...

**Comment by Tooluloope** [comment] 2023-03-15 12:59
The given text outlines two ways to address the issue of conflicting onClick events in a container widget with child widgets that have onClick events:

1. Only fire an onClick event on the container widget if the clicked child widget does not have its own onClick event configured. In other words, if both a button widget and the List widget have onClick events configured, only the button widget's event will be captured. However, only the list item will be triggered if only the List widget configures an onClick event.

2. For widgets that do not have an onClick event, such as an input widget, but which may still be clicked, the list's onClick event will not be triggered. Instead, a list of allowable and not allowable widgets will be kept. For instance, since the Text widget does not have an onClick event configured, the list's onClick event will be triggered by default.

By implementing these two approaches, the conflicting onClick events issue can be resolved in a container widget with child widgets with their own onClick events.

This would be handled in https://github.com/appsmithorg/appsmith/issues/8330

cc @kamakshibhat-appsmith @dilippitchika @somangshu

**Comment by Nikhil-Nandagopal** [comment] 2023-03-18 09:04
@Tooluloope that's a good solution and I think it works this way in list widgets generally

**Comment by Nikhil-Nandagopal** [comment] 2023-03-18 09:05
@dilippitchika @Tooluloope can we fix this now instead of creating a dependency? This seems like a basic expectation of this widget

**Comment by dilippitchika** [comment] 2023-03-20 09:28
We will start working on it this sprint. @Tooluloope please add it to your sprint

**Comment by somangshu** [comment] 2023-03-23 09:58
Are we making this functionality work in the container widget and transitively that automatically works for the container widget as well? Or our solution will be specific to list only. @Tooluloope

**Closed** 2023-04-14 13:55 UTC
Labels: Bug, App Viewers Pod, High, Community Reported, List Widget
