### ISSUE TITLE
[Type]-[12000]:Add Keyboard Shortcut for Run Action

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13331] opened 2022-04-26 14:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Add Keyboard Shortcut for Run Action

**Comment by rohan-arthur** [comment] 2022-05-02 13:58
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6000 |
| Effort (months)  | <> |

**Comment by rohan-arthur** [comment] 2022-05-02 14:00
to consider:
1. I should be able to run the query by using a hotkey that is familiar and intuitable
2. Even so, I should be able to learn this shortcut easily when I am on the query editor

**Comment by mohanarpit** [comment] 2022-05-10 07:24
This is a regression. The Ctrl+Enter / Cmd+Enter shortcut existed to run the API & DB queries. Currently this shortcut is enabled in the query panes but is broken in the API pane. Possible for us to fix this quickly? Only asking because it's a regression.

**Comment by AmanAgarwal041** [comment] 2022-05-27 05:14
This feature already exists on the API pane as well. This is working for me. @rohan-arthur  can you also verify so that we can close this issue ?

**Closed** 2022-05-28 01:38 UTC
Labels: Needs More Info, Low, regression, Low effort, Task, BE Coders Pod, Ready for design, Actions Pod
