### ISSUE TITLE
[Task]: Redis password falsely used as username when no username is set

### ISSUE THREAD

**Issue by Phylu** [appsmithorg/appsmith#27900] opened 2023-10-09 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

I am using an AWS powered Redis instance with Authentication enforced. AWS is using only a password without username for its Redis instances. See: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth.html

This means, that a correct URL to connect to an AWS managed Redis instance looks as:

```
rediss://PASSWORD@master.REDIS-NAME.euc1.cache.amazonaws.com:6379
```

When appsmith is building up the redis connection in https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/RedisConfig.java#L146, the following code is run:

```
            final String[] parts = userInfo.split(":", 2);
            config.setUsername(parts[0]);
            config.setPassword(RedisPassword.of(parts.length > 1 ? parts[1] : null));
```

Therefore, the Redis password from the URL is set as username instead of password. I can run Appsmith in version 1.9.38 when setting the Redis connection string to the following value. Notice the `:` before the password, denoting an empty username:

```
rediss://:PASSWORD@master.REDIS-NAME.euc1.cache.amazonaws.com:6379
```

Is this intended behaviour? Should we start Appsmith with this "strange" connection string, or is this something that should/will be adjusted?

This was not an issue before https://github.com/appsmithorg/appsmith/pull/24924.

**Comment by sharat87** [comment] 2024-01-31 09:54
Hey @Phylu, sorry for getting to this late. Yes, for cases like this, we'll need the `:` to explicitly differentiate cases where username is needed without a password, and the case where password is needed without username.

I'm closing this issue since this is expected behaviour.

**Closed by sharat87** 2024-01-31 09:54 UTC
Labels: Task

**Comment by Phylu** [comment] 2024-01-31 13:35
Hi @sharat87,

thanks a lot for your response. Just making sure: You write "We'll need..." and then "closing this issue since this is expected behaviour". So I don't understand whether the current behaviour is expected and will stay like this, or if there is any change that should be done in the future.

Cheers, Phylu

**Comment by sharat87** [comment] 2024-02-13 12:43
Hey, sorry if that was confusing. I meant that we _need_ the `:` to be there in the URL, if the username is empty, but password should be present. The current behavior is expected and intended.
