### ISSUE TITLE
[Bug]: Complete filter card not visible if Table widget is placed at the extreme top in the canvas

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17984] opened 2022-10-31 08:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The complete Filter card is not visible to the developer when the table widget is placed on the extreme top of the canvas. 

Also noticed that when the filter card is open and we click outside of it (somewhere in the table), the card does not close. You either have to click outside the table widget or the `x` button in order to close the filter card. Should we enable the user to close it if they click anywhere outside the card, on the table?

https://www.loom.com/share/75bb845628464fde84360eca014896de

### Steps To Reproduce

1. D&D a table widget.
2. Place it at the extreme top of the canvas.
3. Click on `Filters`.

### Version

Cloud

**Comment by Shivam-z** [comment] 2024-08-28 10:50
@shadabbuchh we can able to see the filter card even if table widget is placed at the extreme top in the canvas .
[Screencast from 28-08-24 04:15:26 PM IST.webm](https://github.com/user-attachments/assets/4356bf3a-3e05-409b-8563-9ec2d159f2f8)
can you check this.

**Comment by carinanfonseca** [comment] 2024-08-28 14:49
Thank you, @Shivam-z. I can't reproduce this issue either. It seems it was fixed in the meantime, so I'm closing it.

**Closed by carinanfonseca** 2024-08-28 14:49 UTC
Labels: Bug, Table Widget, UX Improvement, Widgets Product, Low, Production, Table Widget V2, Inviting Contribution, Widgets & Accelerators Pod
