### ISSUE TITLE
[Feature]: Badge Widget

### ISSUE THREAD

**Issue by danguilherme** [appsmithorg/appsmith#28630] opened 2023-11-03 15:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A new Badge widget and table column, to show the status or progress of a certain entity or action.

![image-20231020-184523](https://github.com/appsmithorg/appsmith/assets/1488378/6b5c6509-4fbe-493f-9c0c-0d93bcf6262d)

### Why should this be worked on?

A Badge is a small, visual element used to highlight important information or status updates within products. It features colors, and a short text label, and is often displayed in a corner or alongside other content. The badge can be used to indicate new or unread messages, notifications, or other important information. It can also be used to highlight the status of a task or project, such as "completed" or "in progress."

![image](https://github.com/appsmithorg/appsmith/assets/1488378/5debd183-6f74-4507-a501-8c3d6877d074)

**Comment by Nikhil-Nandagopal** [comment] 2023-11-06 06:15
Thanks for the feature request! This seems to be duplicate of #4333 so I'll close this in favor of that

**Closed by Nikhil-Nandagopal** 2023-11-06 06:15 UTC
Labels: Enhancement, App Viewers Pod, Community Reported, Table Widget V2

**Comment by danguilherme** [comment] 2023-11-06 11:35
Hey there @Nikhil-Nandagopal, thanks for the update! I see that that request is specifically about adding a "Tags" column to the table. Besides the usage in the Table, I also have the need of a standalone Badge widget.

Furthermore, one can argue that Badge and Tags are different UI elements.

**Comment by ricardoxtrindade** [comment] 2023-11-06 11:40
Hey there, I agree with @danguilherme here are some key differences between a Badge and a Tag/Chip IMO:
 
**Badge**

- Purpose: Badges are typically used to highlight specific pieces of information, such as status indicators, notifications, or counts. They often represent some form of dynamic or contextual information.
- Appearance: Badges are usually small, often circular or rounded rectangles, with concise text or simple icons to convey the associated message. They can have various colors to indicate different states or types of information.
- Usage: They are commonly applied to indicate new items, alerts, notifications, or the status of an element, such as "New," "Sale," "Hot," or displaying a numerical count.
- Interaction: Badges are generally not interactive elements and are primarily used for display purposes.

**Tag/Chip**

- Purpose: Tags or chips are used to categorize, filter, or organize content. They are often applied to represent keywords, categories, or attributes associated with an item.
- Appearance: Tags/chips are typically rectangular or pill-shaped elements with text that describe the content or context they represent. They may have a background color to differentiate various categories or types.
- Usage: They are frequently used for filtering content, creating a visual hierarchy, or enabling users to search or identify items based on specific criteria.
- Interaction: Tags or chips can be interactive, allowing users to remove or add filters, navigate to related content, or trigger specific actions associated with the tagged item.

In summary, badges primarily emphasize status or dynamic information, while tags/chips are more often used for categorization and content organization purposes.
