### ISSUE TITLE
[Bug] JSON substitution for REST API breaking with surrounding single and double quotes

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3868] opened 2021-04-05 15:25 UTC
With JSON substitution turned on, if the dynamic binding is not explicitly surrounded by quotes, the parsing is successful. But if we include quotes during usage, the parsing breaks.

Example Body:
```
{
  "key": "{{Input1.text}}"
}
```

**Comment by trishaanand** [comment] 2021-04-19 07:06
Can't reproduce. Closing for now.

**Closed by trishaanand** 2021-04-19 07:06 UTC
Labels: API pane, Actions, Actions Pod, Backend, Bug, community
