### ISSUE TITLE
[Bug]: occasional cyclic dependency on user's app (potentially due to array bindings)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#13308] opened 2022-04-26 07:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Happens randomly when changing select widget option.
Data sensitive app, so not sharing screenshots.

[cyclic-dependency-error-object.txt](https://github.com/appsmithorg/appsmith/files/8560971/cyclic-dependency-error-object.txt)

Update: (steps to repro)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/044a520a6a9e4bbdb9b63c35f508d2e9-00001.gif)](https://www.loom.com/share/044a520a6a9e4bbdb9b63c35f508d2e9)

---

Suggested to use promise chaining for consequent async actions.

---

Suggested changes to bindings
```
{{ 
function() {
    const data = get_client_info.data;
    return appsmith.store.cust_id === "" ? "" : data[0]["id"];
}()
}}
```

instead of 
```
{{ 
    appsmith.store.cust_id === "" ? "" : get_client_info.data[0]["id"];
}}
```

---

### Steps To Reproduce

Happens randomly when changing select widget option.

### Version

Self hosted - v1.6.20

**Comment by eco-monk** [comment] 2022-04-26 07:54
We have an internal app that behaves somewhat similar to this
https://app.appsmith.com/applications/6179aa44b2db5a27f21af8c8/pages/617a5154b2db5a27f21afaee

**Comment by eco-monk** [comment] 2022-04-29 04:02
Looking at why `dependencyMap` doesn't include array accessors for certain cases.
e.g.`Api1.data` instead of `Api1.data[0]`

**Comment by eco-monk** [comment] 2022-05-19 05:21
The Api seems to throw this error consistently. (Thanks @ApekshaBhosale for pointing this out)
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/66776129/169214365-1a33a1ec-b3ea-40f8-bfeb-d03384433bc7.png">

Was unable to repro this with query, which is the user's case.
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/66776129/169214468-3466348a-2ccf-4d99-8cc1-c823c58efc41.png">

Noticed body being a string, hence `Query.data[0]` will be a valid accessor.

---

Fixing the dependencyMap problem on the API's case should solve it for the Query too.
But will be investigating what kind of errors will make the `body` undefined / {} for query.

**Comment by ramsaptami** [comment] 2022-06-17 08:01
The issue is back on release now and needs to be looked at

**Comment by eco-monk** [comment] 2022-06-23 05:02
@ramsaptami, this is not reproducible on prod or on release.

https://github.com/appsmithorg/TestSmith/issues/1737

https://www.loom.com/share/4cbbb24a3ad44f35868fa291b7530590

https://www.loom.com/share/c260845d58cf43bca071d42826522d7e

**Comment by ramsaptami** [comment] 2022-06-23 05:20
Closing it since this has been fixed

**Closed by ramsaptami** 2022-06-23 05:20 UTC
Labels: Bug, High, Reopen, FE Coders Pod, Skip Docs, Actions Pod
