### ISSUE TITLE
[Bug]: Promise.then is not working

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10285] opened 2022-01-10 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using promises, running a query onSuccess of an update function does not work

### Steps To Reproduce

1. Go to the A force app https://app.appsmith.com/applications/61cd5be2a4437918c01f87af/pages/61d7f69a6bd5757f166cb01e/edit?branch=master
2. Click the signup option
3. The fields do not refresh till the page is refreshed but the fetch_hero_roster query is run in the then part of the assign function in the JSObject

### Environment

Production

### Version

Cloud

**Comment by Rishabh-Rathod** [comment] 2022-01-13 11:16
According to the discussion [here](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1641913149043600 ) , This is duplicate of #9782

**Closed by Rishabh-Rathod** 2022-01-13 11:16 UTC
Labels: Bug, Actions Pod, JS, High, FE Coders Pod
