### ISSUE TITLE
[Task]: Fix flakiness of cypress/e2e/Smoke/Apps/ReconnectDatasource_spec.js

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#35138] opened 2024-07-24 08:32 UTC
### SubTasks

This test failed on first run but passed on the second.
Ref: https://github.com/appsmithorg/appsmith/actions/runs/8732019146/attempts/1

**Comment by NilanshBansal** [comment] 2024-07-24 09:33
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Integration-Pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/35138?planning-poker) with Zenhub @AmanAgarwal041 @carinanfonseca @rishabhrathod01 @rohan-arthur @sneha122

**Comment by rishabhrathod01** [comment] 2024-07-26 08:13
Estimate this task as 2 SP for
- Usage of xPath
- Uncertainty for the root cause

**Comment by rishabhrathod01** [comment] 2024-08-12 10:17
Closing the issue as the cypress test passed every time and hence will be considered not flaky.
CE PR -  https://github.com/appsmithorg/appsmith/pull/35586
EE PR -  https://github.com/appsmithorg/appsmith-ee/pull/4863

**Closed by rishabhrathod01** 2024-08-12 10:17 UTC
Labels: Task, Query & JS Pod, Integrations Product, Integrations Pod General, cypress-flaky-fix, Stability Pod
