### ISSUE TITLE
[Bug]: System generated commit drops a widget

### ISSUE THREAD

**Issue by phantom943** [appsmithorg/appsmith#28446] opened 2023-10-27 19:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I pull my project from git remote, Appsmith generates a commit dropping one of my widgets. This happens only to selected widgets, after I do some changes to them. 
The commit reads "System generated commit, for syncing changes with remote after git pull" and the changes from that commit are "drop file data_table.json".
What's weird is that on the source branch I develop with (dev), the widget is present in both "Edit" and "Launch" views, but the repo does NOT contain the widget JSON file.
When I manually revert this commit from git, and then pull the changes into Appsmith, it again generates the commit that's dropping the widget file.
When I import this project from Git on a different Appsmith instance (on my local machine) - the widget is gone.
What seems to solve the issue is copying the widget, deleting the old one, and renaming the new to something like data_table2. If I rename it to data_table - it once again goes missing.
So it seems the widget is somehow cached in Appsmith, and it would not let me return the widget file into git.

### Steps To Reproduce

No idea how to trigger this, it's intermittent.

### Environment

Production

### Version

Self Hosted v1.9.42

**Comment by riteshkew** [comment] 2023-10-30 07:46
@phantom943 Since you have figured out a workaround and this is not consistently reproducible, we would appreciate it if you could get on a call and we can triage this together. You can schedule a call using this [link](https://calendly.com/ritesh-catchup-15/30min?month=2023-10).

**Comment by Nikhil-Nandagopal** [comment] 2024-01-25 06:25
@phantom943 we're closing this issue for now. Please let us know if this resurfaces.

**Closed** 2024-01-25 06:25 UTC
Labels: Bug, High, Community Reported, Needs Triaging, Git Version Control, Git Pod
