### ISSUE TITLE
[Feature]: Improve select column

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#26194] opened 2023-08-09 05:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The select column functions differently than the select widget.  They both use label and value, but when setting it, only the value is visible under the table and not named normally (for example table1.triggeredRow.sku instead of table1.triggeredRow.sku.selectedValue).

Either the documentation of this column should be updated so it is clear how it is different from the widget, or the functionality of the column should be updated to match the widget (preferably the latter, but the former is a good stopgap).

### Why should this be worked on?

It is confusing for users when a widget performs differently than expected and is not clearly documented.

**Comment by dilippitchika** [comment] 2023-08-10 06:42
Duplicate of #21993, @eedwardsSGS we have started planning this, will fix it soon

**Closed by dilippitchika** 2023-08-10 06:42 UTC
Labels: Enhancement, App Viewers Pod, Community Reported, Table Widget V2
