### ISSUE TITLE
[Bug]: Column name on property pane changes on changing the order 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9188] opened 2021-11-17 05:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/54029a63fe7143f6a86a5ccddf04993d-00001.gif)](https://www.loom.com/share/54029a63fe7143f6a86a5ccddf04993d)

### Steps To Reproduce

1. Drag and drop a table widget
2. Open the property pane
3. Click on any column name in property pane and drag to change the order
4. Observe that previous column name on property pane changes to same name

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment] 2021-11-17 10:56
Good find, But since on blur the issue is rectified ill keep this on low priority

**Comment by somangshu** [comment] 2021-12-15 05:49
- [ ] Research the solution
- [ ] Implement the solution
- [ ] test cases
- [ ] resolving QA comments
- [ ] reserved points

**Closed** 2021-12-24 09:31 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low, Production, UI Building Pod
