### ISSUE TITLE
[Bug]: The auto commit and push happens When user tries to commit some of his changes 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19166] opened 2022-12-23 06:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto commit and push happens When user tries to commit some of his changes 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/209285321-8fe4b601-846c-44c7-b43e-a5973b619b6f.png">
https://www.loom.com/share/f1c2bfd3164e4f64a291325dacd74fa8

### Steps To Reproduce

1. login as admin
2. go to admin setting page
3. Create a custom role
4. Give crud access for only few pages
5. assign it to user 1
6. Now login as user 1
7. Create a new branch from master branch 
8. do some edits in the app 
9. try to commit and push
10. Now do a first commit
11. Now again do some changes
12. Click on + icon 
13. The commit Operation Starts on its own 

### Version

release

**Comment by AnaghHegde** [comment] 2022-12-23 10:16
Duplicate of the issue - https://github.com/appsmithorg/appsmith/issues/15102

**Closed by AnaghHegde** 2022-12-23 10:16 UTC
Labels: Bug, Needs Triaging, Git Version Control, Team Managers Pod, Release Blocker
