### ISSUE TITLE
[Bug]: Preview mode does not work unless clicked on from the canvas page

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16276] opened 2022-08-24 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we are on any page other than the canvas and click on the Preview mode icon, instead of getting the preview of the application we get to see that particular page.

https://www.loom.com/share/b6ccc5584806405098e1221ed01f1c78

### Steps To Reproduce

1. Go to any application.
2. Click on the "Page Properties" icon in the Entity explorer.
3. Now click on the Preview mode.

**Expected:** The preview of the application should be displayed rather than any of the Edit mode contents.

**Note:** This can be replicated from Queries/Datasources pages as well.

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-08-29 10:38
@rohitagarwal88 can you please take a look at this?

**Comment by rohitagarwal88** [comment] 2022-08-29 10:52
@dilippitchika/ @shadabbuchh  it does not happen only page setting, it happen in all view eg, JSObjects, API, Queries, Datasources etc. 
@rahulramesha : Look at this. This is an interesting bug. Preview & edit icon hide all the left side, search bar and  right sidebar. We have to redirect user to edit url with preview mode enabled.

**Comment by rahulramesha** [comment] 2022-08-29 15:41
@rohitagarwal88 @dilippitchika, looks like we are only removing the panes from left and right. What should be the expected behaviour when user selects preview mode on Page Settings page or any other Page. Or should we fix this by just showing preview mode option only on canvas page and removing that option from other pages?

**Comment by dilippitchika** [comment] 2022-08-30 05:13
In my head, preview can be done from any page. While in most cases it's an immediate feedback on what is happening in canvas hence, our users haven't reported this.

Either when preview is clicked, we take the user to canvas and hide the prop pane and entity explorer or remove it from other pages other than canvas. I prefer the first as it's much more comprehensive @rahulramesha

**Comment by rohitagarwal88** [comment] 2022-08-30 14:36
> Either when preview is clicked, we take the user to canvas and hide the prop pane and entity explorer or remove it from other pages other than canvas. I prefer the first as it's much more comprehensive @rahulramesha 
I would vote for the first approach.

**Comment by rohitagarwal88** [comment] 2023-06-05 13:12
Marking it closed as Page properties has moved to property pane. This issue is not reproducible now

**Closed by rohitagarwal88** 2023-06-05 13:12 UTC
Labels: Bug, App Viewers Pod, Low, Production, Needs Triaging, View Mode, UI Builders Pod, Canvas / Grid
