### ISSUE TITLE
[Bug]: "Null" application in workspace

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24614] opened 2023-06-19 09:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A null application was created in my workspace. The application literally shows "null" as the name, but I didn't create it. However, the audit logs say It was created by my account. 

### Steps To Reproduce

...

### Environment

Production

### Version

Cloud & Self - Hosted > 1.9.19

**Comment by ginilpg** [comment] 2023-06-23 11:03
duplicate of #24773

**Comment by nayan-rafiq** [comment] 2023-09-07 18:14
I was able to reproduce this. Here are the steps:

1. Connect the application to git
2. Create another branch from the default branch. For example, assume that application has two branches now - `develop` and `main`. `main` is the default branch.
3. Change the default branch to `develop` in the remote e.g. at github
4. Click on the sync icon in the list of branch dropdown. This should sync the default branch from remote. So, now `develop` branch will be the default branch in appsmith as well.
5. Checkout to develop branch
6. Delete the `main` branch from appsmith
7. Try to checkout to `remote/main` branch. It'll show an error. Go back to dashboard and you'll see a new app created with name `null`.

**Closed** 2023-09-12 05:39 UTC
Labels: Bug, Community Reported, Needs Triaging, Git Version Control, Git Pod
