### ISSUE TITLE
[Feature] Reusable Components

### ISSUE THREAD

**Issue by KirtiChug** [appsmithorg/appsmith#4157] opened 2021-04-26 10:23 UTC
## Summary

Reusable components - widgets, APIs or DB Queries. There is often a use case while we code in React we create one component and use it across different pages. 

## Motivation

Currently, it is possible by copying the component and use it on a different page so that we don't have to create one again and again. But this itself does not solve the purpose of reusablity. As if one component changes we need to go across changing all components on different pages.
Consider a use case:
We have a page with multiple widgets with a particular CSS styling. We copy all the widgets and use them on different pages. Now at someday, we realize the CSS styling has to be changed in all widgets of the page. We have to go across changing in a lot of places.

Usually, while we code, we keep reusable components in some common directory so that we can use it across easily and when the component changes it is reflected on every page required.

**Comment by Nikhil-Nandagopal** [comment] 2021-04-26 10:24
@KirtiChug thanks for the details!

**Comment by segfall** [comment] 2021-09-14 05:05
++ to this. 

retool calls it ["modules"](https://docs.retool.com/docs/modules). Oracle Apex calls it ["shared components"](https://docs.oracle.com/cd/E11882_01/appdev.112/e11947/bldr_sc.htm#HTMDB04009).

The ability to drag a component from page-scope to app-scope, and then back down to another page is a feature I'll be looking for in appsmith's future.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-14 05:59
@segfall thank you for the upvote! We're really excited about this feature as well. Stay tuned for a product note on it. We'd love your input

**Comment by Nikhil-Nandagopal** [comment] 2021-12-07 06:24
Closing this as a duplicate of #5229

**Closed by Nikhil-Nandagopal** 2021-12-07 06:24 UTC
Labels: Enhancement, UI Building Pod, community, UI Builders Pod
