### ISSUE TITLE
[Bug]: JSON Form icon dropdown is not working as expected on first time click

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13633] opened 2022-05-06 06:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user clicks on the icon dropdown in the Submit Button Styles dropdown, the dropdown is not working .. it is empty, incorrectly placed and small.

### Steps To Reproduce

1. Drag and drop the JSON form widget to the canvas.
2. Expand the Submit button styles section
3. Click the Icon dropdown. 

The dropdown is not working.

Workaround - Open the icon dropdown of the Reset button styles section, and then come back and try to open the icon dropdown of Submit button styles. It works now. 

<img width="781" alt="Jsonform_Icondropdown" src="https://user-images.githubusercontent.com/101863839/167075802-e47be592-9a0a-442a-85ee-926c9832850b.png">

### Version

Release

**Comment by dilippitchika** [comment] 2022-05-27 10:47
@btsgh this looks fixed probably as part of theming, can you please recheck and let me know?
![Screenshot 2022-05-27 at 4 17 24 PM](https://user-images.githubusercontent.com/19730984/170685335-78564650-b7e2-4549-b628-df1c63df046f.png)

**Comment by dilippitchika** [comment] 2022-05-27 12:11
Happening on release - https://release.app.appsmith.com/applications/61cbf39a8f45a85fae9ab0ee/pages/6283da485869d765189f9b30/edit

**Comment by dilippitchika** [comment] 2022-05-27 12:11
check with demo@appsmith.com account

**Comment by ashit-rath** [comment] 2022-06-06 06:50
@dilippitchika @btsgh I am unable to reproduce it, can we verify this again?
Ideally it should have got fixed in [#13881](https://github.com/appsmithorg/appsmith/pull/13881)

**Comment by dilippitchika** [comment] 2022-07-22 07:23
Closing as it's not happening, @btsgh let me know if it needs to be reopened

**Closed by dilippitchika** 2022-07-22 07:23 UTC
Labels: Bug, App Viewers Pod, High, JSON Form

**Comment by btsgh** [comment] 2022-07-25 14:58
@dilippitchika - works fine now.
