### ISSUE TITLE
[Bug]: Mongodb collections are not in sorted order in schemas.

### ISSUE THREAD

**Issue by Naveen-Goud** [appsmithorg/appsmith#35842] opened 2024-08-22 09:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when we connect with mongodb database and execute any query the collections after getting from db are not in sorted order in schemas.

### Steps To Reproduce

1.login into the appsmith application.

2.open the data tab in app and add mongodb data source.

3.add some collections in mongodb, ignore if present.

4.try to execute any query .

5.after that when we open the schemas , we observe that the collections  are in not sorted manner.

![Screenshot from 2024-08-05 16-07-18](https://github.com/user-attachments/assets/03490850-7b13-4f49-bab0-e7302153abea)

 

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

release

**Comment by rohan-arthur** [comment] 2024-08-22 12:32
sure, @raushan3737 
In future, please pick one from this list: https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Inviting+Contribution%22

For now, I've added the tag `Inviting contribution` to this issue as well.

**Comment by raushan3737** [comment] 2024-08-22 12:41
Sure @rohan-arthur,  Thank you. 
I have a small request for you and the team. If possible, could you please proceed with the other issue PRs that have been in an open state for weeks?
PR Link: 
https://github.com/appsmithorg/appsmith/pull/35363
https://github.com/appsmithorg/appsmith/pull/35099
https://github.com/appsmithorg/appsmith/pull/34977
https://github.com/appsmithorg/appsmith/pull/35391

**Comment by NilanshBansal** [comment] 2024-08-23 04:45
@Naveen-Goud I assume you have already raised a fix for this issue in this PR -https://github.com/appsmithorg/appsmith/pull/35413 
Also this issue is a duplicate of https://github.com/appsmithorg/appsmith/issues/28190

**Comment by NilanshBansal** [comment] 2024-08-23 04:45
@raushan3737 please don't work on this as the fix has already been raised in this PR -https://github.com/appsmithorg/appsmith/pull/35413

**Comment by NilanshBansal** [comment] 2024-08-23 05:44
Thanks @Naveen-Goud I have reopened this issue and updated the original filtering issue. 

@raushan3737 apologies for the confusion, you can go ahead working on this issue.

**Closed** 2024-09-25 14:16 UTC
Labels: Bug, Low, Needs Triaging, Mongo, Query & JS Pod, Integrations Product, Inviting Contribution
