### ISSUE TITLE
[Bug]-[1200]:Widget property pane is not accessible when horizontally/vertically placed widgets are grouped together

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8415] opened 2021-10-11 11:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Group widgets that are horizontally/vertically next to each other and try to access the property pane - not possible since widget label is hidden under the container widget as seen in the screenshot. Widgets need to be ungrouped to access property pane

![image](https://user-images.githubusercontent.com/79509062/136783797-d0dcf7ef-9ee4-4ff7-829e-d36b832bddaf.png)

### Steps To Reproduce

```markdown
1. Place widgets of same height next to  or below each other - like text, input, switch
2. Group these widgets and try to access the property pane by clicking on the widget label - not possible. Widgets need to be ungrouped to access property pane
```

### Environment

Production

### Version

Cloud

**Comment by marks0351** [comment] 2022-01-19 14:10
closing this coz the issue is reproducible but property pane opens up on click again after docked property pane changes.

**Comment by ramsaptami** [comment] 2022-01-25 18:43
When there's a widget like the modal, it's not possible to navigate between widgets without triggering the modal when the intension is only to navigate to the property pane. Having the label visible is a standard across the app and so having it accessible is necessary for consistent UX.
https://www.loom.com/share/f395d21cf8534cb1a8b9cc4009d14721

**Comment by vuiets** [comment] 2022-04-25 04:29
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 0.5 |

Adding a rough estimate for effort. We can change it if you guys feel different about it.

**Comment by kamakshibhat-appsmith** [comment] 2023-09-14 12:59
doesn't occur anymore . Closing this

**Closed by kamakshibhat-appsmith** 2023-09-14 12:59 UTC
Labels: Bug, UX Improvement, Property Pane, High, Production, Community Reported, Needs Triaging, UI Builders Pod, High effort
