### ISSUE TITLE
[Bug]: Unable to delete the API datasource

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#30071] opened 2024-01-05 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://theappsmith.slack.com/archives/C040LHZN03V/p1704429009634409

### Steps To Reproduce

https://theappsmith.slack.com/archives/C040LHZN03V/p1704429009634409

### Environment

Production

### Version

v1.9.58-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 09:16
Duplicate of #16866

**Closed by Nikhil-Nandagopal** 2024-03-07 09:16 UTC
Labels: Bug, Production, Needs Triaging, BE Coders Pod, Medium, Integrations Pod, Integrations Pod General
