### ISSUE TITLE
[Bug]: In a table, a menu button item does not recognize the currentRow property.

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#31625] opened 2024-03-08 18:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on a menu button, then click on a menu item I want to store an ID value from this currentRow.  However,  Appsmith is not recognizing this property in the onClick event. 

### Steps To Reproduce

Create a table. 
Create a custom column as a MenuButton.
add a couple of memu items.
Navigate to a menu Item and look at the properties.
in the onClick event property add {{console.log(currentRow)}}.  For me it says get in the hover text "currentRow is not defined"

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/4c275aca54ef401a8358726e6a311984?sid=aaa89780-1e33-4832-b3dd-f89acb47dfd7

### Version

Appsmith Community v1.13 self-hosted.

**Comment by pchambless** [comment] 2024-03-08 18:45
You can notice in the Loom video that I reference currentRow below in the Visible and Disabled properties.  (Kinda redundant, but you get the message)

**Comment by Nikhil-Nandagopal** [comment] 2024-03-11 08:01
Thanks for reporting! This is a duplicate of the issue #26052

**Closed by Nikhil-Nandagopal** 2024-03-11 08:01 UTC
Labels: Bug, Table Widget, App Viewers Pod, Production, Community Reported, Needs Triaging, Medium
