### ISSUE TITLE
[Task]: Check launching instance with cloud-run on gcp

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#18800] opened 2022-12-09 05:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by yan-hic** [comment] 2023-03-16 09:40
@pratapaprasanna what was the outcome of this ? Wanted some feedback before we are heading to cloud run for the same.
Ideally an official guide on the pitfalls, limitations when deploying on CR. A VM does not scale to zero.

**Comment by sharat87** [comment] 2023-05-30 12:35
Closing this as duplicate of #23522, since there's more description there.

@yan-hic, update, we're working on this already and will very likely have docs for setting up Appsmith on CloudRun soon. Thanks! 🙏

**Closed by sharat87** 2023-05-30 12:35 UTC
Labels: Task
