### ISSUE TITLE
[Bug]The Evaluated value pop up hides at the top most area when the user scrolls the query section

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4575] opened 2021-05-19 09:16 UTC
## Description
Release Environment - MongoDB - It is observed that connecting mongo DB via URI connection and creating new query and clicking on any of the fields and by scrolling thr query section the evaluated values moves top most area and truncates. 

**Expected Result:**
Evaluated value should be clearly visible by scrolling query section 

**Actual Result:**
Evaluated value truncates when the user scrolls the query section

### Steps to reproduce the behaviour:
1. Launch app smith app in the release Environment 
2. Click on Database 
3. Add new Datasource
4. Select Mongo DB
5. Change the connection as Yes for URI 
6. Pass the following url - mongodb+srv://fortest:123testing@mock.0rat3.mongodb.net/heroku_bcmprc4k
7. Click on Save button 
8. Click onNew Query 
9. Click on any of the fields collection name, query, sort or Protection and check Evaluated value pop up will be displayed
10. Scroll down and observe

Video Link:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d88bfab3d5fb4ed3b93a1fb1203eedf3-00001.gif)](https://www.loom.com/share/d88bfab3d5fb4ed3b93a1fb1203eedf3)

### Important Details
 - Version: [Safari - 14.1 (16611.1.21.161.3), Chrome - 90.0.4430.212]**
 - OS: [MacOS Big sur 11.3]
 - Browser [Chrome, Safari ]

**Comment by Nikhil-Nandagopal** [comment] 2021-08-23 09:54
Duplicate of #5687

**Closed by Nikhil-Nandagopal** 2021-08-23 09:54 UTC
Labels: Bug, Actions Pod, Low, Release, Query Editor, Needs Triaging
