### ISSUE TITLE
[EPIC] Improve copy-paste experience

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5150] opened 2021-06-15 20:53 UTC
1. Today copy paste for widgets is unpredictable and doesn't paste the widget where it needs to be pasted.
2. Sometimes the paste occurs at a location that's so far below that it's difficult to notice it's location
This is especially important for group actions where it's difficult to love large groups of widgets if they've been pasted at the wrong location.

Potential solutions:
1. On clicking copy, the widget can be magnetically attached to the cursor
2. Paste always occurs at the closest empty space beside the cursor

**Comment by somangshu** [comment] 2021-06-16 05:43
One more suggestion here, Follow what happens on an OS or text editor,

- Copy the widget
- Right-click to find the paste option on the canvas.
- Paste always occurs at the closest empty space beside the cursor

**Comment by riodeuno** [comment] 2021-09-09 10:43
This is to be taken up as a part of the issue #2308 cc @somangshu

**Comment by rahulramesha** [comment] 2022-02-09 09:32
Update from the Feb 9th Meeting,

We agreed to go with this approach and build 1 POC only for now. Then test it internally and externally if needed and decide what needs to be done next:

1. If the mouse pointer is on a layout widget,

- and the layout widget is selected, paste with reflow inside the layout widget
- and the layout widget is not selected, paste below the layout widget

2. If the mouse pointer is on a non-layout widget,

- and the non-layout widget is selected, paste below the widget
- and the non-layout widget is not selected, paste below the widget

3. If the mouse pointer is on the empty canvas, paste with reflow

A layout widget is any widget that can house other widgets. Looking at the position of the mouse over selected vs. non-selected here.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-09 13:49
@rahulramesha If the mouse is over the widget name handle that users generally use to click the widget, will that also count as hover over widget?

**Comment by rahulramesha** [comment] 2022-03-09 14:05
> @rahulramesha If the mouse is over the widget name handle that users generally use to click the widget, will that also count as hover over widget?

Currently, I'm thinking No, My Rationalisation for that is because of two scenarios where in,
- Widget name is displayed on top of the widget - If we consider that as hover over the widget then by the above logic, we will have to paste it below the widget, while the mouse pointer will be above it. This might feel a bit odd to the user. So, the solution here would be to paste it at that point reflow the widget down.
- Widget name is displayed below the widget - if we consider or not consider it as hover over that widget, In either situation by the above logic we will be pasting below it.

But changing the logic to include that can be done as well if it solves any useCase.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-09 14:18
@rahulramesha I think in this case it should still be considered a part of the widget when the widget is selected. Because of the main user story: 
As a user, when I select an Input in a form and copy + paste it, I expect a new input to show up below the current input.
This is the base expectation here for any user

Also wanted some clarity around the positioning, when we say it is pasted below a widget, does that mean it will be horizontally aligned with the widget or below and centered around the mouse position? I think it should be horizontally aligned so I just want to be clear

**Comment by rahulramesha** [comment] 2022-03-09 14:49
@Nikhil-Nandagopal , Yes it makes sense when a widget is selected.

For positioning, When the widget or group of widgets are selected, then the pasted widgets will be aligned horizontally.

But for when, no widgets are selected, I feel it would make sense to align top-left of the pasting widget with the mouse pointer, as it will help in aligning the pasted widgets in the grid. In this scenario, centring it around the pointer, might complicate it to the user, as they might not remember how tall or wide the pasting widgets will be in reference to the pointer.

Once we have a POC to get a feel of the UX, tweaks such as this should be a minor change.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-09 15:02
@rahulramesha the problem is that the success of pasting will almost always be a very low number because the user can't visualise where the object will be pasted so the user will most of the time need to move the widget after pasting so it makes sense to optimise for the user grabbing the widget as soon as it's pasted

**Comment by rahulramesha** [comment] 2022-03-10 11:34
From the 10th March Kickoff Discussion,

Update on the UX for positioning of the Widget,

- When a widget is selected, widget will be pasted below the selected widget and is horizontally aligned with widget that is selected.
- While mouse pointed is on plain canvas, the pasted widgets will be added around the mouse pointer, i.e., centred both vertically and horizontally with respect the mouse pointer.

**Comment by vuiets** [comment] 2022-03-23 04:20
@rahulramesha could you ensure that we tackle [#9646 | Grouping widget causes newly formed container to shift to the bottom of the page](https://github.com/appsmithorg/appsmith/issues/9646) as a part of this project.

**Comment by rahulramesha** [comment] 2022-03-24 13:57
Update on 24th March,

As next steps for the Project, we will have to make two decisions,

1. Paste below the selected widget always , if none is selected place near the mouse pointer V/S Paste on the mouse pointer Always ignoring the selected Widgets and paste below a reference widget when the mouse pointer is on the reference widget
2. While pasting near the mouse Pointer, align the pasted widget's Top-Left corner with the mouse Pointer V/S align the centre of the widget or group of widgets with the mouse position.

In order to conclude with these decisions, we are planning to schedule a call with some users for the feedback on this and also try to get more internal feedback by requesting team members to build a layout that involves lot of copy/paste, with both the POC

**Closed** 2022-05-31 13:12 UTC
Labels: Enhancement, High, UI Building Pod, community, UI Builders Pod, Epic, Copy Paste
