### ISSUE TITLE
[Bug]: Button widget throws an e is an undefined error when the user runs the email query 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9663] opened 2021-12-08 13:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button widget throws an e is an undefined error when the user runs the email query 

### Steps To Reproduce

1. go to SMTP Datasource
2. Configure the Port no with 587
3. Now create a new query
4. Add the same email Ids in TO, CC, BCC email input box
5. Bind this query to button widget
5. CLick on button
6. E is undefined error is dsplayed

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-03-18 09:59
@RakshaKShetty not able to reproduce in release and production, i used mailjet to test with the same 587 port. Closing this for now.

**Closed by dilippitchika** 2022-03-18 09:59 UTC
Labels: Bug, App Viewers Pod, Release, Button Widget, UI Building Pod, Needs Triaging
