### ISSUE TITLE
[Feature] Resize the property editor pane

### ISSUE THREAD

**Issue by daemons2000** [appsmithorg/appsmith#7319] opened 2021-09-09 16:42 UTC
We need this because anything a bit more serious than a Javascript one liner gets wrapped wrapped wrapped so it becomes a mess to edit. Alternatively, a popup JS editor for each field would be nice too.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-10 06:40
@daemons2000 thank you for the feature request. We have a full fledged JS Editor right now being tested. You can track the issue here #1751

**Comment by Nikhil-Nandagopal** [comment] 2021-11-08 10:21
Duplicate of #4435

**Closed by Nikhil-Nandagopal** 2021-11-08 10:21 UTC
Labels: Enhancement, UI Improvement, Property Pane, UI Building Pod, community, UI Builders Pod
