### ISSUE TITLE
[Feature] Provide a connector / plugin for Google drive 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#5117] opened 2021-06-14 14:22 UTC
## Summary
Requested by community: 
```
Is there any documentation on (or has anyone tried) saving a file to Google Drive from a file picker widget? 

Do we have to create a new Project in the Cloud Console and enable the drive API, define scopes, etc? Or is there an easier way?
```

**Comment by Nikhil-Nandagopal** [comment] 2021-08-16 08:43
Duplicate of #4304

**Closed by Nikhil-Nandagopal** 2021-08-16 08:43 UTC
Labels: Enhancement, Datasources, Actions Pod, community, Actions
