### ISSUE TITLE
[Bug] Child widget tooltips are hidden behind parents

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3826] opened 2021-04-01 08:11 UTC
## Description

Widget name and other tooltips in a child widget get hidden behind the parent and do not overflow to be completely visible.

This needs a re structure of the stacking contexts of particular elements of child widgets to make them visible.

**Comment by areyabhishek** [comment] 2021-09-17 19:54
Got this on Discord from Joseph today. https://www.awesomescreenshot.com/video/5274881?key=3653ec9c5719e628e80150ee2026adf1

**Comment by vuiets** [comment] 2022-03-23 04:10
Closing this as it is a duplicate of [#8415](https://github.com/appsmithorg/appsmith/issues/8415).

**Closed by vuiets** 2022-03-23 04:10 UTC
Labels: Bug, High, UI Building Pod, community, UI Builders Pod, High effort
