### ISSUE TITLE
chore: POC on CSS Modules 

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#26019] opened 2023-08-04 07:58 UTC
Currently, for every new CSS feature, we have to wait for its support in styled-components. We want to try CSS modules with post-css plugins and check if we can work with CSS modules so that we don't have to wait for every CSS feature in the styled component.

**Comment by KelvinOm** [comment] 2023-08-04 08:07
Duplicate of https://github.com/appsmithorg/appsmith/issues/25536

**Comment by KelvinOm** [comment] 2023-08-04 11:12
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/26019?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm

**Closed** 2023-09-15 07:17 UTC
Labels: App Viewers Pod, Widget design system, WDS team
