### ISSUE TITLE
[Bug]: User Invited as Developer to Organization Has Only App Viewer Access

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#16160] opened 2022-08-19 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user that previously had only App Viewer access to an organization gets an invite to join as a Developer. After receiving the invitation email, the user went to the workspace but still did not get edit access and is listed as App Viewer.
![2022-08-03 15_03_01-Window](https://user-images.githubusercontent.com/101268423/185574345-35fe4303-2869-433d-b7ef-bc55cde8c5b0.png)
![2022-08-03 15_21_13-Window](https://user-images.githubusercontent.com/101268423/185574370-e1d4965b-9e56-47ab-840b-190f41b10622.png)

**Workaround**:
1. Remove the user that has only App Viewer access from the organization.
2. Add the user again as **Developer**.

### Steps To Reproduce

1. Invite the user that previously had **App Viewer** access to an organization as **Developer**.
2. Click the **Share** button and note that the user still has the App Viewer role, even after refreshing or hard reloading the page.

### Version

Cloud v1.7.13-SNAPSHOT

**Comment by vuiets** [comment] 2022-09-02 04:15
Unable to calculate the RICE score for this, we have to add analytic events to for user role updates.

**Comment by hiteshjoshi** [comment] 2022-09-02 06:46
This belongs to the old infrastructure for ACL, and now, since we are working on RBAC/ABAC, we will need to revisit this once we launch.
CC: @vuiets

**Comment by vuiets** [comment] 2022-09-13 05:42
Hey @RakshaKShetty! Could you check if this is fixed in `v1.8.0` with the new RBAC infra and close this?

**Comment by nsarupr** [comment] 2023-04-28 06:58
Closing this. Please re-open if the issue is seen again.

**Closed by nsarupr** 2023-04-28 06:58 UTC
Labels: Bug, Wont Fix, High, Needs Triaging, Team Managers Pod, RBAC
