### ISSUE TITLE
[Enhancement]: Add 'Allow Clearing Value' property to Select widget

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#15804] opened 2022-08-08 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The new Select widget allows users to clear the selection. We should allow developers an option to prevent the users from clearing this selection in case there is a query that is dependent on the default value in the select widget. We have this property on the Treeselect widget as shown in the screenshot below. 
<img width="611" alt="Screenshot 2022-08-08 at 11 34 42" src="https://user-images.githubusercontent.com/32227135/183350120-c29b5afb-5fef-4417-9e74-8534a5324edd.png">

### Why should this be worked on?

A user on discord reached out with an issue where the queries were failing when the user deletes the default value in the select widget. https://discord.com/channels/725602949748752515/760761686549463060/1005198690450952343

**Comment by dilippitchika** [comment] 2022-08-08 06:45
Closing this as duplicate of https://github.com/appsmithorg/appsmith/issues/6780

**Closed by dilippitchika** 2022-08-08 06:45 UTC
Labels: Enhancement, Select Widget, App Viewers Pod
