### ISSUE TITLE
[Bug]-[268]:Suggested Widgets Table gives a 'buttonColor is invalid' debug error

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14527] opened 2022-06-14 11:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/173571024-ccfcc2ce-da25-44e3-83df-492e4446975a.mov

### Steps To Reproduce

1. Create a new app & apply some theme
2. Run a query or an api - which gives result in table format
3. Select the Table from the Suggested widgets section
4. **Observe: Table is added to canvas but a debug error which never goes away & which is misleading of a presence of an error in the widget**
5. Map the query result to table widget manually & observe there is no error
6. **Expected: Mapping Table from Suggested widgets section should also give no error to user**

### Version

Prod/Release v1.7.2

**Comment by dilippitchika** [comment] 2022-08-18 11:27
@sbalaji1192 @jsartisan i don't know who needs to fix this, but this is an important issue because a lot of people bind data from table using this method and most of them are first time users.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 268 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment] 2022-08-18 11:28
Not adding this in epics for now

**Comment by sbalaji1192** [comment] 2022-08-19 05:41
@dilippitchika This issue looks like related to theming. @jsartisan could you take a look at this?

**Comment by jsartisan** [comment] 2022-09-28 05:55
@marks0351 @rahulramesha Hey guys assigning this to you guys as the issue is happening in the suggested widget flow. Let me know if you guys need any help from me or balaji.

**Comment by dilippitchika** [comment] 2023-06-20 12:21
Closing because it's fixed now

**Closed by dilippitchika** 2023-06-20 12:21 UTC
Labels: Bug, Table Widget, App Viewers Pod, Production, Needs Triaging, App Theming, medium, Data Platform Pod, Suggested Widgets
