### ISSUE TITLE
[Bug]The Red dot icon is displayed on the comment icon even when there are no new comments

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5432] opened 2021-06-28 03:06 UTC
## Description

[What happened]The Red dot icon is displayed on the comment icon even when there are no new comments

After the onboarding tour for comment
click on comment icon 
add the first comment
resolve the comment 
now verify the display of comment icon

https://drive.google.com/file/d/1mqK8642RCwAQTFQppaLEUI0A3pqe4DL0/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment Release

**Comment by rishabhsaxena** [comment] 2021-07-05 05:20
Duplicate of #5098

**Closed by rishabhsaxena** 2021-07-05 05:20 UTC
Labels: Bug, Needs Triaging, Release, collaboration
