### ISSUE TITLE
[Bug] Clicking on organization names does nothing

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#840] opened 2020-09-30 17:38 UTC
## Description

Upon clicking on the name of the organization, nothing happens except for a few times. Looks like there needs to be a name for the scroll to work. 

Also, adding a smooth scroll may be more user friendly.

### Steps to reproduce the behavior:

Screencast: https://recordit.co/FS56YQfC80

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge

**Comment by Nikhil-Nandagopal** [comment] 2020-10-01 06:21
Duplicate of #807  different result but the root cause is the same

**Closed by Nikhil-Nandagopal** 2020-10-01 06:21 UTC
Labels: Bug, High
