### ISSUE TITLE
[Bug]: The application breaks when user tries to Launch duplicated app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8697] opened 2021-10-21 11:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user duplicate the app and Launch it the Resource not found error is displayed
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/44dd292430a841178bd3a22d5016d720-00001.gif)](https://www.loom.com/share/44dd292430a841178bd3a22d5016d720)

### Steps To Reproduce

```markdown
1. Go to home page
2. click on meatball icon below the application name 
3. Click on the duplicate menu 
4. after the new duplicated application opened up 
5. come back to home page 
6. now click on launch the application breaks
```

### Environment

Release

### Version

Cloud

**Comment by hiteshjoshi** [comment] 2022-03-19 08:41
@abhvsn can we close this?

**Comment by abhvsn** [comment] 2022-03-21 09:43
Duplicate of #7799

**Closed by abhvsn** 2022-03-21 09:43 UTC
Labels: Bug, Home Page, High, Needs Triaging, Platform Pod, Team Managers Pod
