### ISSUE TITLE
[Bug] Video : When autoplay is toggled  from JS to regular the option becomes "True"

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#985] opened 2020-10-05 15:25 UTC
https://www.notion.so/Video-When-autoplay-is-toggled-from-JS-to-regular-the-option-becomes-True-3bca508913f241bd958aafdd5e2b3925

**Comment by Nikhil-Nandagopal** [comment] 2020-10-19 12:16
Duplicate of #1254

**Closed by Nikhil-Nandagopal** 2020-10-19 12:16 UTC
Labels: Bug, Low, Release, Widgets
