### ISSUE TITLE
[Bug] Column name on table widget is not updated on autocomplete after name change

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7565] opened 2021-09-17 07:02 UTC
## Description
When column name of a table is changed and any attempt to use this new column name through autocomplete shows a "No suggestions" tooltip

### Steps to reproduce the behaviour:
1. Go to data bound table widget with columns
2. change column name and go to settings of the column name and try to change the query using autocomplete dropdown and observe that the new column name does not appear on autocomplete

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ef9eaf20dd034f569782b21c55ab1667-00001.gif)](https://www.loom.com/share/ef9eaf20dd034f569782b21c55ab1667)

**Comment by somangshu** [comment] 2021-09-29 07:00
Duplicate of #4757

**Closed by somangshu** 2021-09-29 07:00 UTC
Labels: Bug, Table Widget, Widgets Pod, High, Autocomplete, UI Building Pod
