### ISSUE TITLE
[Feature] Disable signup / login on Appsmith when hosted privately.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2411] opened 2021-01-01 06:10 UTC
## Summary
1. User has hosted Appsmith on their AWS instance and want to rely on AWS login to authenticate user. Once the user has logged in to AWS, they should be able to access Appsmith freely.

## Additional Context
Discord discussion: 
`We have deployed our appsmith in aws. how to access appsmith with out appsmith credential. Right now we have already gmail credential, we don't need appsmith login credential. how to remove appsmith credential.
`

**Comment by Nikhil-Nandagopal** [comment] 2021-01-04 06:38
@sumitsum closing this as a duplicate of #2350

**Closed by Nikhil-Nandagopal** 2021-01-04 06:38 UTC
