### ISSUE TITLE
[Feature]: Add ssl disable for Rest API queries

### ISSUE THREAD

**Issue by arshia-rgh** [appsmithorg/appsmith#38044] opened 2024-12-09 10:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I cant disable ssl verification in appsmith like postman and I think this is a important feature

### Why should this be worked on?

I have self-signed ssl and wiht appsmith I cant send request to it, and appsmith doesn't have disable SSL like the postman

**Comment by ame-appsmith** [comment] 2024-12-09 13:55
Duplicate of https://github.com/appsmithorg/appsmith/issues/16889

**Closed by ame-appsmith** 2024-12-09 13:55 UTC
Labels: Enhancement, Query & JS Pod, REST API plugin, Integrations Product
