### ISSUE TITLE
[Bug]: Deleted binding path does not show up as an error by the linter

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15989] opened 2022-08-12 11:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a widget's binding path has been deleted, for instance, a table widgets column or a button group widget's button, we don't display an error for incorrect path

### Steps To Reproduce

1. Add a button group widget and bind the first button to a text widget
2. Delete this button and observe there are no errors displayed for this missing path

### Version

Cloud

**Comment by bharath31** [comment] 2022-08-15 05:34
@ramsaptami looks like a duplicate of https://github.com/appsmithorg/appsmith/issues/15905

**Closed by bharath31** 2022-08-15 05:34 UTC
Labels: Bug, High, Production, Needs Triaging, JS Linting & Errors, FE Coders Pod
