### ISSUE TITLE
[Bug]: Bracket matching does not work with comma

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14292] opened 2022-06-05 05:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/94514895/172036916-09892883-cdd4-4c52-b920-a3dedaef3f0a.mov

### Steps To Reproduce

1. I have a google sheet datasource, and have added a select query to this
2. Now I want to add an insert query, but I don't want to be bothered to construct the required row structure, so I copy it from the select query
3. In the copied content, I want to replace the literals with dynamic binding to widgets from my canvas
4. check the video, when I remove the string and add `{{`, the matching `}}` is not added because there is a comma at the end of the line. If I remove the comma and add `{{`, then the matching closing counterparts are added properly

### Version

Cloud

**Comment by bharath31** [comment] 2022-10-11 05:18
Duplicate of #11642

**Closed by bharath31** 2022-10-11 05:18 UTC
Labels: Bug, Low, Needs Triaging, FE Coders Pod, Code Editor
