### ISSUE TITLE
[Bug]: The text  inside the Restart server pop up is broken in Admin setting page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9828] opened 2021-12-16 14:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text  inside the Restart server pop up is broken in Admin setting page

### Steps To Reproduce

1. go to the admin setting page
2. in advance tab 
3. add the custom domain name
4. click on the save and restart server button
5. Inside the Restart server pop up the text is broken 

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by sharat87** [comment] 2022-06-30 09:36
Closing as can't reproduce.

**Closed by sharat87** 2022-06-30 09:36 UTC
Labels: Bug, Low, Needs Triaging, Deploy Preview, Super Admin, DevOps Pod
