### ISSUE TITLE
[Bug]: Write query breaks Google Sheets integration.

### ISSUE THREAD

**Issue by rfseancavanaugh** [appsmithorg/appsmith#9063] opened 2021-11-10 00:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am in edit mode all of my pages that have write queries for google sheets, I get this error. This behavior started today.

```Cyclic dependency found while evaluating. Node was: Api1.config.pluginSpecifiedTemplates```

In deployed mode, my previously made pages still work properly, but the page I made today stops functioning as soon as a write query exists in either the production or deployed enviroment .

Discord #Support advised that I post this here. Please let me know if I am missing information as it's my first time contributing to a Github project.

### Steps To Reproduce

1. Create table with Google Sheets Read query.
2. Add Menu button column. 
2. Create a Google Sheets write query.
3. Create Modal with input fields.
4. Create a new api to write to the same google sheet.

### Environment

Production

### Version

Cloud

**Comment by rfseancavanaugh** [comment] 2021-11-10 00:44
<img width="821" alt="Screen Shot 2021-11-09 at 7 44 18 PM" src="https://user-images.githubusercontent.com/89208875/141028812-7d67092a-7dd4-4126-a9c9-b89c3ae41ab3.png">

**Comment by prapullac** [comment] 2021-11-10 10:04
@ajinkyakulkarni This issue is reproducible on Master

**Comment by zzgvh** [comment] 2021-11-10 13:32
I commented in the Discord chat, but I'll add it here too. I'm seeing this issue too, I haven't determined exactly which types of goole queries that trigger this, but I'm seeing it on almost all my pages. I use a lot of goog queries...

An interesting observation is that my app still works in deployed mode. But in edit mode I have this constant flickering from some kind of error feedback loop. Se editing is impossible :stuck_out_tongue:

Hope you find a resolution to this soon, as it's a complete stopper. 

https://user-images.githubusercontent.com/142613/141122091-019f9589-52be-4255-8ceb-3e4af71addb9.mp4

**Comment by nidhi-nair** [comment] 2021-11-11 05:40
This should be fixed in [v1.5.30](https://github.com/appsmithorg/appsmith/releases/tag/v1.5.30). Closing this issue since users on Discord have confirmed that the fix works as well.

**Closed by nidhi-nair** 2021-11-11 05:40 UTC
Labels: Bug, Actions Pod, JS, Critical, Google Sheets, FE Coders Pod, BE Coders Pod
