### ISSUE TITLE
[Bug]: Data Source Reauthorization Required to Authenticate API After Update

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#24767] opened 2023-06-22 18:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After one of the updates, some users are experiencing the need to reauthorize their data sources in the AHutenticate API after a certain period of time. I have investigated and successfully replicated this issue.

![image](https://github.com/appsmithorg/appsmith/assets/114161539/23d92688-02d1-4e3f-a7ea-f91b5c3577cc)

### Steps To Reproduce

1. Create a new data source for Authenticate API.

2. Configure it for Google Drive as shown in these images.
![image](https://github.com/appsmithorg/appsmith/assets/114161539/7975b122-0829-4b4c-b3a2-570a5a60279e)
![image](https://github.com/appsmithorg/appsmith/assets/114161539/fa57d2a3-e4e5-4880-a8ff-74fad0988574)
![image](https://github.com/appsmithorg/appsmith/assets/114161539/b8677a16-9a2c-41e9-bfd5-688b945e71b3)
![image](https://github.com/appsmithorg/appsmith/assets/114161539/01244ce0-4ec4-4742-9873-fbd781a35d60)

3. Execute the GET request, and you will receive a `200` response. However, after 3 hours, the token will expire, and despite having the parameters to refresh the token, it will not be refreshed.

### Environment

Production

### Version

Appsmith v1.9.23-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lt898)

**Comment by VladTabacariu** [comment] 2023-07-04 06:10
is anybody looking into this?

**Comment by rohan-arthur** [comment] 2023-07-17 10:53
hello! we are looking into this, and will reach out to you in case we need some help with investigating the issue

**Comment by sbalaji1192** [comment] 2023-07-28 05:23
@tkAppsmith I noticed that the fix was only pushed to the CE promotion branch. But not to EE. Was this intentional?

**Comment by sbalaji1192** [comment] 2023-09-05 07:34
@tkAppsmith Yeah. The sync workflow must have synced it.

**Comment by felix-appsmith** [comment] 2023-09-05 16:35
Due to two other users ([1](https://app.frontapp.com/open/cnv_13c9zqa4?key=z0mwErCKCM1_Ogo_fYZPUAuTSh0TJ0lt), [2](https://app.frontapp.com/open/cnv_13o9edcc?key=TBLzHzVhGKfbwWKuGTTa_JEFqg-xTWQe)) recently reported that they have a similar problem with Big Query (they both need to reauthorize their data source at least once a day), I reopened this Bug Report to address the issue again.

**Comment by sumitsum** [comment] 2023-09-06 07:11
Removing `critical` tag for now because it is not clear if the issue is due to wrong config or bug in the code.

**Comment by sumitsum** [comment] 2023-09-12 03:25
Closing in favour of https://github.com/appsmithorg/appsmith/issues/27175

**Closed by sumitsum** 2023-09-12 03:25 UTC
Labels: Bug, Backend, High, Verified, Regressed, Needs Triaging, Core Query Execution, BE Coders Pod, OAuth, Data Platform Pod, Integrations Pod
