### ISSUE TITLE
[Bug] Sorting Numeric Fields doesn't work

### ISSUE THREAD

**Issue by tlawrence-TAG** [appsmithorg/appsmith#7598] opened 2021-09-20 03:51 UTC
## Description

Sorting doesn't appear to function on decimal types.

### Steps to reproduce the behavior:

1. Set a number type column - pull from a database table.
2. Set the type to number
3. Sort
4. Note: The images show "$" signs, etc. These are done post. If you remove any formating by Intl.Number, the issue still persists.

![image](https://user-images.githubusercontent.com/82402173/133955348-fab9f8bf-b854-4a49-970b-12983d02e5b0.png)
![image](https://user-images.githubusercontent.com/82402173/133955431-5beb18e0-5db6-4efb-9fe4-bb97556964b5.png)

### Important Details

- Version: Self-Hosted - Release v1.5.21 
- OS: Windows 10
- Browser: MS Edge - Version 93.0.961.52 (Official build) (64-bit)
- Environment: Development/Production

**Comment by vicky-primathon** [comment] 2021-09-23 10:30
@somangshu  not able to reproduce this issue. Sorting works fine for numbers but if the input itself is not number but formatted strings than the sorting work like sorting strings.

**Comment by tlawrence-TAG** [comment] 2021-09-23 14:16
Add some blank/null values to the data set.

Here's an animated GIF....
![numeric_sort_bug](https://user-images.githubusercontent.com/82402173/134524004-8819185a-ab69-401e-bdb0-a10fb365e27a.gif)

**Comment by somangshu** [comment] 2021-09-25 06:50
Thanks for the additional information here @tlawrence-TAG 💯, We are looking into the issue to identify the problem, We will keep this thread updated.

**Comment by sbalaji1192** [comment] 2021-11-02 11:03
@somangshu What should be the expected behaviour.
1. All null values should be treated as 0  in number type columns or
2. should be pushed to bottom of the table regardless of sorting order (like google sheets).

**Comment by somangshu** [comment] 2021-11-02 12:11
@sbalaji1192 option 2 sounds better to me, Undefined should be treated separately, not to mix with 0, We should show them at the end regardless of order type. let me know if I am not getting this right

**Comment by sbalaji1192** [comment] 2021-11-02 12:13
@somangshu Sounds good. let me push a fix for this.

**Closed** 2021-11-18 12:57 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, UI Building Pod, community
