### ISSUE TITLE
[Feature]-[68]:Unable to connect to visual studio (azure devOps) git repo

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17628] opened 2022-10-17 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current git-sync functionality expects repos with `.git`, a community user was not able to connect to their repo.
REF - https://community.appsmith.com/t/unable-to-connect-to-visual-studio-azure-devops-git-repo/1536

### Steps To Reproduce

The user shared this git repo URL - `blahblah@vs-ssh.visualstudio.com:v3/blahorg/Appsmith-TEST/Appsmith-TEST`

### Version

v1.8.4

**Comment by vuiets** [comment] 2022-10-28 06:38
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 68 |
| Effort (months)  | 0.5 |

Estimating the reach for this to be about 5% of our users will use Azure DevOps for git hosting (this number is negligible in our analytics): 68

**Comment by hiteshjoshi** [comment] 2022-10-28 07:35
The requested behaviour is actually not a bug and a sound behaviour for `git` 
Right now we have Regex to check `.git` at the end of a Git repo URL. If we receive more such requests from users we should take a look but right now the obvious solve is for the user to enable the current URL formats for git.

**Comment by NicksonYap** [comment] 2023-03-24 10:35
We've moved from GitHub to using Azure DevOps Repo and the format for Git url cannot be configured.

The format is:
`https://dev.azure.com/{account}/{project}/_git/{repo}`

using regex to check for `.git` is not the best practice

Reference: https://github.com/dotnet/docfx/issues/4493

There is no workaround to this and it seems like users are forced to just use Gitlab or GitHub

**Comment by riteshkew** [comment] 2024-07-22 10:12
this is resolved in v1.31

**Closed by riteshkew** 2024-07-22 10:12 UTC
Labels: Enhancement, Low, Low effort, Git Version Control, Git Pod
