### ISSUE TITLE
[Bug] Did not receive Forget password link on mail — asking to configure email service

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4368] opened 2021-05-07 08:50 UTC
## Description - Email is not received and "Configure email service" message is shown on Reset password screen.

Imp : If user signup from google account and then try to login using email/password -- This flow is not possible due to this issue.

### Steps to reproduce the behaviour:
1. Go to Login page and click "Forgot Password"
2. Navigate to "Reset password" page
3. Observe "You haven’t setup any email service yet. Please configure your email service to receive a reset link
Configure Email service" is displayed.
4. Enter the email and click on Reset button
5. Observe success message is displayed but email is not received.

Environment : Release

<img width="585" alt="Screenshot 2021-05-07 at 12 54 47 PM" src="https://user-images.githubusercontent.com/83569920/117423698-a110d480-af3e-11eb-8363-89cf2fbd509f.png">

**Comment by nayan-rafiq** [comment] 2021-08-17 10:47
@sharat87 This is a configuration related issue. Seems the `APPSMITH_MAIL_ENABLED` field value is not properly set.

**Comment by sharat87** [comment] 2021-08-17 11:51
This is because of missing SMTP configuration on the release environment back in May (when the issue was created). We still don't have _real-world_ SMTP configuration on this environment, but we do have a dev configuration. This message doesn't appear today, and the forgot password email does show up in the dev configuration.

Closing as can't reproduce.

**Closed by sharat87** 2021-08-17 11:51 UTC
Labels: Bug, Login / Signup, Needs Triaging, Platform

**Comment by patelbhavinoutlook** [comment] 2022-10-20 15:28
Even i have issue with sending email..

Hello,

I have installed a self-hosted appsmith on ubuntu 20.04 Docket compose.

Installation is don't well. Email SMTP configuration done successfully, also getting test mail. 

But now i am facing problems that:

1. not getting password reset links
2. when register new member than welcome email not recieved.

**Comment by hubjsant** [comment] 2023-12-06 22:01
I have the same problem as  @patelbhavinoutlook .

I click on "reset" password and I don't receive the email.

On the administration screen, the test email works normally.

In the logs I correctly capture the test email, but no log appears when I click on recover password.

**Comment by sharat87** [comment] 2023-12-16 00:47
Hey @patelbhavinoutlook @hubjsant, sorry you're facing trouble here. Can you share the backend logs from when you're trying to send test email and when doing forgot-password please?

Please not that forgot password functionality will respond success, but won't send an email, if the given email doesn't have an account. So if forgot-password isn't sending an email, consider trying signup instead.
