### ISSUE TITLE
[Bug]: Helper text hidden for properties in Property pane

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17297] opened 2022-10-04 09:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The helper text `Type / to access quick commands` is hidden for every last property in the Property pane.

<img width="1920" alt="Screenshot 2022-10-04 at 2 26 05 PM" src="https://user-images.githubusercontent.com/39921438/193778962-22d9cc63-7aca-470a-9db9-87d409ef129d.png">

### Steps To Reproduce

1. Go to the property pane of any widget.
2. Turn on the JS Toggle button and start typing in the field.

### Version

Cloud

**Comment by aswathkk** [comment] 2022-10-04 09:15
Duplicate of #17079

**Closed by aswathkk** 2022-10-04 09:15 UTC
Labels: Bug, UI Improvement, Property Pane, Low, Production, Needs Triaging, UI Builders Pod
