### ISSUE TITLE
[Bug]: JSObject execution is failing after forking the template

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17524] opened 2022-10-12 17:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When template 'Customer Support Dashboard' is forked in git connected app, it throws multiple errors around JSObject 
<img width="1440" alt="Screenshot 2022-10-12 at 10 32 59 PM" src="https://user-images.githubusercontent.com/80334441/195405404-a28a986d-f347-4c8e-bfda-159538d21763.png">
<img width="1440" alt="Screenshot 2022-10-12 at 10 32 49 PM" src="https://user-images.githubusercontent.com/80334441/195405458-01471936-0e51-43b7-85e8-6e5cfab417a6.png">

### Steps To Reproduce

1. Connect an app to git
2. Create new branch, fork template Customer Support Dashboard
3. Observe the error

This is not always reproducible , it is observed in this app https://release.app.appsmith.com/app/testtemplate/page1-6346b9423908a23c5fcff919?branch=master

### Public Sample App

https://release.app.appsmith.com/app/testtemplate/page1-6346b9423908a23c5fcff919?branch=master

### Version

Release

**Comment by AnaghHegde** [comment] 2022-10-13 04:37
@Parthvi12 Looks like the jsObject executed but there was an issue with the data and it failed because of that. If you look at the error in the console it says `Cannot read properties of Undefined`.

**Comment by akash-codemonk** [comment] 2022-10-13 04:58
Unable to repro but it looks like the queries have failed to run for some reason which is what the JSObjects are trying to get data from. Could you post a screenshot for the error in the query `delayedOrders` as we cannot see the same in the deployed app and can be seen in the edit mode of the app clearly? @Parthvi12

**Comment by Parthvi12** [comment] 2022-10-13 05:03
These queries run fine, also I can invite to the org if you want to debug further, let me know your email id for release @akash-codemonk 
<img width="1440" alt="Screenshot 2022-10-13 at 10 32 12 AM" src="https://user-images.githubusercontent.com/80334441/195505983-5013e433-cd6d-4606-8797-4529e319074b.png">

**Comment by AnaghHegde** [comment] 2022-10-13 05:06
If the queries are running fine then this is not related to templates. Can you invite me as well to this app?

**Comment by akash-codemonk** [comment] 2022-10-13 05:25
@Parthvi12 Is it working now? I just added a blank line and removed a blank line in the jsobject file and it is working.

**Comment by Parthvi12** [comment] 2022-10-13 05:28
@akash-codemonk Yes it works now, but can we also please debug why did it reach this state. @AnaghHegde Added you as well to org 'template Test'.

**Comment by akash-codemonk** [comment] 2022-10-13 05:31
Adding medium tag since although it goes into this state. Rediting the jsobject with a space or newline seems to fix the evaluation.

**Comment by rahulbarwal** [comment] 2023-05-31 08:03
@Parthvi12 
I tried replicating this by forking "Customer support dashboard" template and removing the extra line at the end. And then forking the newly created app.
But could not reproduce this, it may have been resolved by an untracked issue. Can you please check if we can close this?

**Closed** 2023-06-02 12:42 UTC
Labels: Bug, Needs Triaging, New Developers Pod, Templates pod, medium
