### ISSUE TITLE
[Bug] Firestore where condition values are always treated as strings

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3733] opened 2021-03-29 06:19 UTC
The "Where condition value" for Firestore actions, when getting multiple documents from a collection, only supports string values. If we set it to filter for `GT 5`, it should be setting the value `5` as a number, instead it does this as the string `"5"`, which results in Firestore not returning any results.

**Comment by arturokunder** [comment] 2021-07-22 16:15
Possible duplicate of #6060 ?

**Comment by mohanarpit** [comment] 2021-07-22 17:32
Thanks @arturokunder , you are right. Closing this in favour of #6060.

**Closed by mohanarpit** 2021-07-22 17:32 UTC
Labels: Bug, Needs Triaging, community, firestore
