### ISSUE TITLE
[Bug]: Input Widget - When grouped "Text" field is resized larger minimizing the "Label" field

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#13554] opened 2022-05-04 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/104895602/166653069-b5c502cc-d322-4276-a2f8-ad647fe9ba3e.mp4

On Grouping two or more Input Widgets, label and test fields are resized.
Label field is minimized, whereas Text field is maximized inside the container.

Expected: Upon grouping Input widgets the sizing of fields inside Widget should be same

Actual: The fields in Input widget are resized when grouped.

### Steps To Reproduce

1. Drag and drop two or more Input Widget
2. Select all the Input widget and click on "Group" or press ctrl + G
3. Notice that the Label field is minimized and the Text field is Maximized

### Version

Production

**Comment by dilippitchika** [comment] 2022-05-05 06:00
Ok this happens for the following reason
1. There's a minimum width of the input widget - which is some Xpx for example
2. Once we create a group, it creates a container, in this container the input has to resize because of the relative width logic we have for containers.
3. Input resizes to min width and the rest of the space is occupied by the label, hence it truncates.

According to me this is not a bug because of the way containers work today. Closing this, please let me know if it needs to be reopened.

**Closed by dilippitchika** 2022-05-05 06:00 UTC
Labels: Bug, Input Widget, App Viewers Pod, Low, Production, UI Building Pod, Needs Triaging
