### ISSUE TITLE
[Bug]: Intermittently Seeing an error when we do a refresh or while opening the git connected app

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24842] opened 2023-06-26 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open the git connected app or do an operation/refresh the page within the app, I see the Error "Cannot read properties of undefined" and "There was an unexpected error" Toasts

### Steps To Reproduce

1. Open the git connected [app](https://ee-1703.dp.appsmith.com/app/release-jun26-2023/arango-64992f579d900254a70f9b52/edit?branch=master) on the promotion DP
2. Note the error toast pops up
<img width="1398" alt="Screenshot 2023-06-26 at 12 56 36 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/f67ae852-6d0e-4532-b9b7-77fc956dfbf2">
3. Sometimes seeing this on Refreshing a page on this app also, 
4. Issue is intermittently reproducible
Noticed while opening the application from the home page, and while refreshing the application from an edit ds page.

### Environment

Release

### Version

Cloud

**Comment by bharath31** [comment] 2023-07-04 11:37
@btsgh does this happen for non-git-connected apps too?

**Comment by btsgh** [comment] 2023-07-06 13:00
@bharath31 - this was particular to that DP we were doing regression on. If I am able to see this issue again, will update with my observations

**Comment by bharath31** [comment] 2023-07-18 05:13
@btsgh closing this since there is no update here. feel free to re-open whenever you're able to reproduce this on production

**Closed by bharath31** 2023-07-18 05:13 UTC
Labels: Bug, Release, Needs Triaging, FE Coders Pod, OnPageLoad, Medium
