### ISSUE TITLE
[Bug]Unable to rename action with a name of widget which has been deleted

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#5655] opened 2021-07-07 07:27 UTC
## Description

If a user tries to rename an action with a name of a widget which is now deleted, we get an error disallowing this saying "X is already being used"

[What happened]

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Drop a widget on the canvas. 
2. Rename the widget to Name1
3. Now delete the widget Name1
4. Add a new API
5. Rename the API to Name1 to observe the error

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by Nikhil-Nandagopal** [comment] 2021-07-07 07:33
@trishaanand will the same happen if the API is deleted?

**Comment by ajinkyakulkarni** [comment] 2021-07-07 07:36
Underlying problem could be similar to this https://github.com/appsmithorg/appsmith/issues/5554

**Comment by arunvjn** [comment] 2021-10-01 06:19
Closing this issue since it is not reproducible with the mentioned steps.

**Closed by arunvjn** 2021-10-01 06:19 UTC
Labels: Bug, Actions Pod, High, community, Needs Triaging, Query Executions
