### ISSUE TITLE
[Bug]: S3 - from 2nd upload filename getting saved as undefined

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#9922] opened 2021-12-21 15:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/459ecb8a7e264f589f3ac2e25ab95204-00001.gif)](https://www.loom.com/share/459ecb8a7e264f589f3ac2e25ab95204)

### Steps To Reproduce

1. Generate a New Page with S3 DataSource
2. Upload a file, Wait until 'File Uploaded' message is displayed
3. Search with File prefix & verify result is showing fine
4. Upload 2nd file, Wait until 'File Uploaded' message is displayed
5. Search with File prefix
6. No Search results are returned
7. Try uploading 3rd file & no search results returned as well
8. The 2nd added file is added with the name as "undefined" instead of original name

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment] 2021-12-22 08:23
@Aishwarya-U-R - just tested in production and found the same issue. OK to remove the "release blocker" tag in that case?

**Comment by Aishwarya-U-R** [comment] 2021-12-22 09:27
@RakshaKShetty - Can you please confirm on Rohan's ask here?

**Comment by Nikhil-Nandagopal** [comment] 2021-12-22 10:29
@rohan-arthur @RakshaKShetty This still seems like a critical issue though. Anyone who had an S3 query will not have this search functionality broken. Breaking users app should always be critical

**Comment by rohan-arthur** [comment] 2021-12-23 00:24
Update: this might be something breaking in the js evaluation of the crud app. Not for back-end coders pod until confirmed.

**Comment by Rishabh-Rathod** [comment] 2021-12-23 22:18
This issue seems to be related to list widget's `getItems` and how that is evaluated.

## DataTree list widget items

#### 1st Upload
<img width="745" alt="Screenshot 2021-12-24 at 3 42 39 AM" src="https://user-images.githubusercontent.com/23132741/147295717-11a0cef4-6aa7-4e84-8cf0-f6461a608407.png">

#### 2nd Upload ( After form submit and reset of all widgets inside form )
<img width="1230" alt="Screenshot 2021-12-24 at 3 38 27 AM" src="https://user-images.githubusercontent.com/23132741/147295703-1d7ca690-75f4-440d-bc55-a11b9e294c63.png">

**Comment by SatishGandham** [comment] 2022-01-03 14:46
This is not search functionality broken. The upload itself is not happening correctly.
When uploading the file, we are reading the file name from input widget in list.

Inputs in list have issues, and this is being picked up this quarter by app viewers.

**Comment by SatishGandham** [comment] 2022-01-04 07:56
Until the list widget issue is resolved, we should read the file names from the file picker and disable the input widget in the list. 
This won't fix the problem for existing apps, but will help with new apps.

**Comment by Rishabh-Rathod** [comment] 2022-01-04 11:48
@SatishGandham Shall I create a new issue for the List widget or avoid closing this issue with 
https://github.com/appsmithorg/appsmith/pull/10146 ?

**Comment by Rishabh-Rathod** [comment] 2022-01-07 19:15
For a temporary fix, I tried removing resetting of `ListWidget` but seems like resetting of FilePicker widget though is evaluated but not shown as expected in ListWidget.

Check here https://www.loom.com/share/1dff9ef19c1b424c8ea78c5d019d3ef3

**Closed** 2022-01-10 22:41 UTC
Labels: Bug, QA, App Viewers Pod, Critical, UI Building Pod, Platform Pod, List Widget, Generate Page, New Developers Pod
