### ISSUE TITLE
[Bug]-[480]:Grouping widgets in a Modal makes the resulting container move to the main canvas

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#10163] opened 2022-01-05 07:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I group multiple widgets which are in a modal, the resulting canvas  automatically moves to the main canvas, rather than staying in place

https://user-images.githubusercontent.com/20532920/148173902-7fa57daf-d300-4a32-bcd5-5de1e2301208.mov

### Steps To Reproduce

1. Create a modal
2. Select the 2 existing buttons (close and confirm)
3. Group them

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment] 2022-03-23 04:34
@riodeuno @rahulramesha is this something we'll be able to cover as part of the `Dynamic Height` or  `Copy Paste Improvements` project?

**Comment by riodeuno** [comment] 2022-03-23 05:07
@vuiets This seems like a bug with grouping. I have seen this in the Form widget as well. We should pick this up as a bug fix. @jsartisan Could you help triage this as this seems related to the grouping feature.

**Comment by vuiets** [comment] 2022-04-25 03:37
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 120 |
| Effort (months)  | 0.5 |

For reach,
People using modals in their apps in the last 6 months: 1223
Expect about 10% of these to group widgets in the modal: 120

Added effort as 2 person-weeks for this but feel free to correct me if wrong here.

**Comment by rahulramesha** [comment] 2022-05-31 13:15
This is a duplicate of https://github.com/appsmithorg/appsmith/issues/12320, Which was fixed in https://github.com/appsmithorg/appsmith/pull/13658. Closing this.
cc: @btsgh

**Closed by rahulramesha** 2022-05-31 13:15 UTC
Labels: Bug, High, UI Building Pod, Needs Triaging, UI Builders Pod, Widget Grouping
