### ISSUE TITLE
[Bug]: Change where condition options for firestore

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#13880] opened 2022-05-16 17:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When working with Firestore API, the where condition filter needs to be updated from "Contains" to "Array Contains" and "Contains Any" to "Array Contains Any". This is required as users may get confused searching items directly instead of searching Arrays.

Since the where condition UI component is generic, it needs to be checked if the implementations affects only firestore Databases related UI.

### Steps To Reproduce

UI Changes required
Change "Contains" to "Array Contains" 
and "Contains Any" to "Array Contains Any". 
key remains the same

### Version

Self hosted

**Comment by Nikhil-Nandagopal** [comment] 2022-05-19 11:17
@leotom2000 the problem isn't very clear here. Can you please add steps to show the error and what the problem is. Array Contains as a text doesn't sound very intuitive. I'm closing this till we get more information

**Closed by Nikhil-Nandagopal** 2022-05-19 11:17 UTC
Labels: Bug, Frontend, Needs Triaging, Firestore, BE Coders Pod, medium, Actions Pod
