### ISSUE TITLE
Appsmith bot for comments

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#4797] opened 2021-05-31 07:10 UTC
- Create new threads: a comment could be pushed to educate/nudge the user
- Handle tags: `@appsmith-support` tag to trigger a support flow

**Comment by areyabhishek** [comment] 2021-05-31 09:53
Why not just @appsmith instead of @appsmith-support? It'll be simpler

**Comment by sharat87** [comment] 2021-05-31 10:41
I think we want to use this comment thread started by this bot for user support as well. Like, the user can reply to that comment that initiates a support conversation. If we name the bot just `@Appsmith`, then we'll need some other way of conveying that this is possible right? Will it be obvious still?

**Comment by rishabhsaxena** [comment] 2021-05-31 13:30
Actually just wanted to convey the functionality here, I guess `@appsmith` should suffice. We could convey the support use-case in the comment text.

**Comment by Nikhil-Nandagopal** [comment] 2021-06-10 09:19
Add separate comments for viewers. @momcilo-appsmith

**Comment by Nikhil-Nandagopal** [comment] 2021-06-10 09:20
👋 Welcome to <App Name>, you can share feedback for this app by tagging @devs

**Comment by nayan-rafiq** [comment] 2021-06-26 10:33
Some points on how this feature may work:

- When an user clicks on the comment mode, an onboarding window will appear (it’s there now)
- When user finishes the onboarding, FE will send a trigger to backend. 
- Backend will generate a new type of comment thread - Bot thread 
  - Position will be a fixed location e.g. top left, top right etc
  - A new type field will be introduced to denote the type of the thread
  - This type of thread will have no sequence number or a fixed number e.g. 0
  - This thread will be visible to the corresponding user only. No other user can view or comment here.
  - The user cannot tag other users in the comments under this thread. Doing so will save the comment in backend but it’ll not notify the tagged user. The front end will show a message saying something like - “This is a conversation with bot, you can create another thread …”
  - User will be able to pin and resolve the thread just like any other thread
- Backend will also generate a notification for the create bot thread event so that user will know about it
- If there is another event e.g. user added a list widget and onboarding is done, it’ll create a new bot thread
  - Position will be related to the newly added widget
- It will be great if we’re able to edit the message template without deployment
- If user tags the appsmith-bot in any comment in any thread, an email will be sent to the support email address.

**Comment by Nikhil-Nandagopal** [comment] 2021-06-28 07:41
@nayan-rafiq 
@rishabhsaxena 
Wanted to add a few points so the entire flow is clear. The onboarding needs a revamp to sit with this flow. Right now we're frontloading too much information in the tour.
Once a user deploys an app, the unread notifications tooltip shows in the view mode. Clicking on it, the following steps start
1. Introducing Live Comments
  - You can now collaborate with your users to build apps faster. Invite your team to comment on your apps, exchange thoughts & ship your ideas.
2. Give Contextual Feedback
  - Drop a comment on a widget to suggest an improvement. Comments are tagged to the widget and move along with it. Update the widget and iterate your way to shipping your ideas!
3. Name / Email screen
  - Update the CTA to "Start Tutorial" here and directly start the tutorial no need for the next screen.
4. Click on the icon to access comments.
5. Click anywhere on the canvas to leave a comment.
6. Say hello to team appsmith
7. The bot replies with
  - Hello! 👋 I'm here to help you with your app! You can get help from team appsmith by tagging @appsmith in your comment. Feel free to say Hi!
  - Resolve this comment when you're done (tooltip on resolve)
8. Once the user resolves it, a new comment pops up
  - Apps get shipped faster when team members are involved early on! Invite a teammate to gather requirements, brainstorm, or get some feedback using the @ symbol followed by their email.

If the user opens an app and has app viewer access only, they get the unread notifications tooltip. Clicking it starts the following steps
1. Introducing Live Comments
  - You can now collaborate with your developers to build apps faster. Exchange thoughts, leave feedback & ship your ideas.
2. Give Contextual Feedback
  - Drop a comment on a widget to suggest an improvement or report an issue. Comments are tagged to the widget, resolve them once the updates are live!
3. Name / Email screen
  - Update the CTA to "Start Tutorial" here and directly start the tutorial no need for the next screen.
4. Click on the icon to access comments.
5. Click anywhere on the canvas to leave a comment.
6. Tag your teammate and leave them some suggestions for the application!

**Comment by RakshaKShetty** [comment] 2021-07-27 08:19
@nayan-rafiq When the developer resolve the bot comment a new comment pops up is not displayed the new comment should be 
"Apps get shipped faster when team members are involved early on! Invite a teammate to gather requirements, brainstorm, or get some feedback using the @ symbol followed by their email."

**Comment by RakshaKShetty** [comment] 2021-07-27 08:38
@nayan-rafiq for the "Administrator role"  When the first bot comment "Hello! 👋 I'm here to help you with your app! You can get help from team appsmith by tagging @AppSmith in your comment. Feel free to say Hi!" is resolved by user, a new bot comment dint pop up

**Comment by nayan-rafiq** [comment] 2021-08-05 10:58
Most probably, this was due to RTS not working in deploy previews.

**Comment by Nikhil-Nandagopal** [comment] 2021-08-05 16:33
@RakshaKShetty can you test on release and close this?

**Comment by RakshaKShetty** [comment] 2021-08-06 12:21
@nayan-rafiq, @nikhil the issue is fixed in the release

**Closed by RakshaKShetty** 2021-08-06 12:21 UTC
Labels: Enhancement, QA, Platform
