### ISSUE TITLE
[Bug] Error icon is not displayed to user near Text Widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4935] opened 2021-06-04 14:35 UTC
Steps to reproduce:
1) Add a Text widget
2) Open the property pane
3) Navigate to Text
4) Add an inappropriate data or error 
and observe the Text name 

Observation:
An error icon must be displayed to the user like other widgets name the name of the widget. however the error is displayed in the property pane and debugger

Expectation:
Icon must be displayed like that of other widgets
![Screenshot 2021-06-04 at 7 38 32 PM](https://user-images.githubusercontent.com/71753653/120818355-2bfde280-c570-11eb-810d-ca4239e9b444.png)

**Comment by Nikhil-Nandagopal** [comment] 2021-07-12 08:48
The text widget should not be in an error state

**Comment by somangshu** [comment] 2021-07-12 09:44
@Nikhil-Nandagopal I think its the default behaviour to show the error in such state as its not valid.

@prapullac I cant reproduce the error any more 
![Screenshot 2021-07-12 at 3 14 09 PM](https://user-images.githubusercontent.com/11089579/125266803-d3b2c100-e323-11eb-9970-0725dac39b1f.png)

**Comment by Nikhil-Nandagopal** [comment] 2021-07-12 09:46
@somangshu I think the problem is that if you send an object to a text, it logs it as an error even though it is not an error as the text widget accepts objects / numbers as well

**Comment by somangshu** [comment] 2021-07-12 11:17
@Nikhil-Nandagopal i think that because of the validation set, Text widget expects `string`. The error which I am sowing is that the autocomplete is left incomplete a `.`, this seems to be a default behaviour

**Comment by Nikhil-Nandagopal** [comment] 2021-07-12 11:47
Oh well that now seems to be working so closing this in that case

**Closed by Nikhil-Nandagopal** 2021-07-12 11:47 UTC
Labels: Bug, Low, Text Widget, UI Building Pod, Widgets, regression, release-frozen
