### ISSUE TITLE
[Bug]The resource not found error is displayed when we duplicated the application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7395] opened 2021-09-14 05:14 UTC
## Description

[What happened]The resource not found error is displayed in the toast bar when the user duplicated the application 

### Steps to reproduce the behaviour:

1. Go to the Home page
2. Click 3 dot on database check application
3. now click on the duplicate option
4. See error in toast bar
![image](https://user-images.githubusercontent.com/45958978/133198690-119bd06d-94fb-414e-8a27-4fa4be82f87d.png)

Note: This issue i am facing for the specific application 

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [ chrome]
- Environment release

**Comment by abhvsn** [comment] 2021-09-14 05:38
@RakshaKShetty please invite me to the application for further debugging

**Comment by RakshaKShetty** [comment] 2021-09-14 12:30
The app name is Database_check you have access for that

**Comment by abhvsn** [comment] 2021-09-21 04:47
@RakshaKShetty can we close this for time being as we are not able to reproduce this error

**Comment by mohanarpit** [comment] 2021-09-22 06:16
Closing as not reproducible

**Closed by mohanarpit** 2021-09-22 06:16 UTC
Labels: Bug, Home Page, Low, Needs Triaging, Platform
