### ISSUE TITLE
 [Bug]: After connecting app to git, jsObject binded widget's data is not visible in deploy mode.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#12756] opened 2022-04-11 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/162682692-4896cb45-167e-413f-860f-91ba18137a6a.mov

### Steps To Reproduce

1. Create an app with Page1 having JSObject binded to widget
2. Clone the page
3. Connect it to git
4. Deploy and observe
5. Page1 data will not be visible
6. Go to edit mode
7. JSObject doesn't show under Queries/JS for Page1

### Version

Release

**Comment by abhvsn** [comment] 2022-04-11 08:43
@Parthvi12 I'm not able to reproduce the issue can you please recheck on your end? We have merged a PR which deals with the clone page issue that we had in last release so not sure if that fixed this one as well

**Comment by abhvsn** [comment] 2022-04-11 09:28
Closing this as this has already been resolved.

cc: @Parthvi12

**Closed by abhvsn** 2022-04-11 09:28 UTC
Labels: Bug, Platform Pod, Git Version Control, Team Managers Pod, Release Blocker
