### ISSUE TITLE
[Bug]: `Blank JS object` appears in the `UI` tab after deleting a JS Object

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30612] opened 2024-01-25 05:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Once we delete a JS object, even though we get a success toast we are still able to see a `Blank JS object` in the `UI` tab of the Entity explorer.
**Note:** Sometimes this `Blank JS Object` disappears after toggling between tabs

### Steps To Reproduce

1. Create a JS Object.
2. Now delete it from either the entity explorer or the JS object menu.

**Expected:** The JS Object should get deleted & user should not see any garbage object.
**Actual:** User gets to see a `Blank JS Object` either in the `UI` tab or the `JS` tab of the entity explorer.

### Environment

Release

### Issue video log

https://www.loom.com/share/3a93256973ea475a93a05a9779f7a7f3

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 10:17
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by hetunandu** [comment] 2024-03-13 08:38
This issue is already fixed in prod

**Comment by shadabbuchh** [comment] 2024-03-13 08:48
@hetunandu I am still able to reproduce it in prod.

https://github.com/appsmithorg/appsmith/assets/39921438/5ee1fade-8efe-48ee-9d95-e94b2e5119cb

**Comment by hetunandu** [comment] 2024-03-13 08:54
@shadabbuchh as discussed earlier in this thread: https://theappsmith.slack.com/archives/C02JT9CSE6L/p1706162733056439  the bug is that selected tab is showing as UI. Showing the Create Blank JS object is expected behaviour.

**Closed** 2024-04-05 12:26 UTC
Labels: Bug, QA, Production, IDE, Needs Triaging, New Developers Pod, IDE Navigation, PR blocker
