### ISSUE TITLE
[Bug]: User can press the reset password multiple times during a pending response from the api.

### ISSUE THREAD

**Issue by danieldare** [appsmithorg/appsmith#10083] opened 2021-12-31 05:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can hit the reset password multiple times when the request is still pending. Hence, a 429 error occurs.
```...```
I expect the reset password link to be disabled when awaiting the response from the backend to avoid multiple calls concurrently.

https://user-images.githubusercontent.com/25982036/147806318-bebc57ba-7d84-41ee-b471-bb5db8528282.mp4

### Steps To Reproduce

1. Go to Edit profile
2. Click on Reset Password
3. press multiple times

### Environment

Production

### Version

Cloud

**Comment by skjameela** [comment] 2024-10-16 07:22
@riteshkew i have reproduce this i didnt get any errors it just redirecting to signin page can you please elaborate this issue clearly

**Comment by skjameela** [comment] 2024-10-17 07:15
@rohan-arthur can you please help me with this

**Comment by skjameela** [comment] 2024-10-18 08:19
@riteshkew if i hit on reset password button it is redirecting to the singin page directly it is not even showing any errors

**Comment by riteshkew** [comment] 2024-10-18 08:54
Thank you @skjameela. I just throttled on my end and couldn't reproduce the issue. Closing this for now.

**Closed by riteshkew** 2024-10-18 08:54 UTC
Labels: Bug, Login / Signup, Production, Needs Triaging, Low effort, Platform Administration Pod, Medium, needs estimate, Inviting Contribution, Identity & Authentication Product
