### ISSUE TITLE
[Bug]: More menu items exceed the canvas

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11684] opened 2022-03-07 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 In menu button widget when new Menu items are added in property pane the bottom border is not visible after the 5th new menu item
 
When more number of menu items are added the items move out of canvas 
![image](https://user-images.githubusercontent.com/92293815/157022420-46bd81ef-4be9-424b-82c5-f87a0ed80c6c.png)

https://loom.com/share/3398a3caca3a4b0d95cc4b07d0f846c3

### Steps To Reproduce

1. Drag and drop Menu button widget
2. In property pane add new buttons

### Environment

Production

### Version

Cloud

**Comment by tauantcamargo** [comment] 2022-10-07 18:28
@sbalaji1192 can i get it?

**Comment by Naveen-Nair** [comment] 2022-10-08 10:00
@sbalaji1192 can i work on this issue?

**Comment by Naveen-Nair** [comment] 2022-10-08 17:39
@sbalaji1192 Can you review my PR? thanks

**Comment by beheradibas** [comment] 2022-10-09 12:17
Hey @sbalaji1192 , I would like to work on this issue.

**Comment by sbalaji1192** [comment] 2022-10-10 04:55
@tauantcamargo Thanks for showing interest. I'm assigning this issue to you. I would appreciate it if you could create a PR within two days. All the best!

@Naveen-Nair & @beheradibas As this is assigned, Please pick a different issue from our [issues](https://github.com/appsmithorg/appsmith/issues) page. If this is your first time contributing to the repo, You can start with a [Good first issue](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+).

**Comment by sbalaji1192** [comment] 2022-10-11 04:50
@tauantcamargo Do you want me to reassign this issue?

**Comment by tauantcamargo** [comment] 2022-10-11 13:45
@sbalaji1192 yeah yeah assign it to @beheradibas

**Comment by sbalaji1192** [comment] 2022-10-12 04:35
@Naveen-Nair Would you be still interested in working on this issue?

**Comment by dilippitchika** [comment] 2022-10-13 10:50
Greetings @Naveen-Nair thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Naveen-Nair** [comment] 2022-10-13 14:03
Hey sorry, i'm a bit busy this weekend, so i don't think i'd be able to work on it

**Comment by secure-crypto** [comment] 2022-10-15 10:27
Hi @dilippitchika, I have reproduced this issue and would like to work on this. Thanks.

**Comment by trishitapingolia** [comment] 2022-10-16 11:24
I am little confused as I tried adding menu buttons but they perfectly working. Can anyone clear me out? 
![Screenshot 2022-10-16 4 53 50 PM](https://user-images.githubusercontent.com/35962310/196032629-490c5448-ae18-44d7-9b22-df1fad288a06.png)

**Comment by dilippitchika** [comment] 2022-10-17 06:34
Hi @trishitapingolia this issue is fixed now. Looks like the only issue pending is a missing scroll on the menu items inside the widget (image 2 in the issue description)

**Comment by dilippitchika** [comment] 2022-10-17 06:34
Greetings @secure-crypto thanks for showing interest 🎉 , This is all yours. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by secure-crypto** [comment] 2022-10-19 16:24
Hi @dilippitchika I investigated this and seems to me there will be a change in this file - https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/MenuButtonWidget/component/index.tsx.
I am quite new to React so trying to understand what changes to make. Will update here on my progress.

**Comment by dilippitchika** [comment] 2022-10-19 16:56
Thanks for checking @secure-crypto, @yaldram can you please help here on where the change needs to be?

**Comment by yaldram** [comment] 2022-10-20 12:46
@secure-crypto For this class `.menu-button-popover, .bp3-minimal.menu-button-popover.bp3-popover2`  disable `overflow-y` property on line 44, I think.

**Comment by secure-crypto** [comment] 2022-10-20 18:26
@yaldram Thank you. I will try what you suggested.

**Comment by Rishabhkaul** [comment] 2022-12-24 05:18
@secure-crypto are you still working on this issue? cc @yaldram

**Comment by MuhammadAakash** [comment] 2023-01-26 15:39
@somangshu @dilippitchika 
is this issue is fixed ?
If not than please assign me I would like to work on this issue.

**Comment by somangshu** [comment] 2023-02-01 09:15
Greetings @MuhammadAakash, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and request for the review here

Apologies for the late response here

**Comment by MuhammadAakash** [comment] 2023-02-01 13:40
@somangshu 
I will start working on this issue in weekend, so maybe it will take more than 2 days.

**Comment by MuhammadAakash** [comment] 2023-02-12 17:44
@somangshu 
Sorry for late, but
Previously I was getting some errors during the setup, but now completed and I am working on it.

**Comment by MuhammadAakash** [comment] 2023-02-12 19:08
@somangshu I have created the PR https://github.com/appsmithorg/appsmith/pull/20579. Please review it

**Closed** 2023-02-27 11:51 UTC
Labels: Bug, Good First Issue, UI Improvement, hacktoberfest, App Viewers Pod, Low, Production, Release, Menu Button Widget
