### ISSUE TITLE
[Bug]: Multiple MySQL functions stopped working after upgrade.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#19962] opened 2023-01-20 22:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiple MySQL functions stopped working after the update. Below are the links of the conversations with the clients and the open bug reports.

`Note: these behaviors were observed since version 1.9.3, it seems that each seems to be for slightly different reasons, but they share the feature that stopped working after the update. 
`

Conversations with clients:
1. https://app.frontapp.com/open/cnv_vvcgczw?key=AOwGUlBkzAQISk_Vicu4S9R8DpKgjxVG
https://app.frontapp.com/open/cnv_vp9zurw?key=sWso8kidLNPcafufX4nQgA8G4qCWGqeV
2. https://app.frontapp.com/open/cnv_vw4q3ik?key=xyAr3IQX1Ckfph9cPvrM8ZnhyjPy5WgB
3. https://app.frontapp.com/open/cnv_vvhhscs?key=fFIjTeKBFSYRpvuZPBmNvQ9z5L3LYWYf
4. https://app.frontapp.com/open/cnv_vl8t0p8?key=7dXh_QCblwG274PPOPWKVta_NxhzCmCa

These are the bug reports opened so far regarding the problems:

1. https://github.com/appsmithorg/appsmith/issues/19812
2. https://github.com/appsmithorg/appsmith/issues/19959
3. https://github.com/appsmithorg/appsmith/issues/20018 
5. https://github.com/appsmithorg/appsmith/issues/19992

### Steps To Reproduce

Enter the bug reports mentioned above

### Version

1.9.3

**Comment by Nikhil-Nandagopal** [comment] 2023-01-23 08:00
@rohan-arthur @sumitsum what's the plan to fix these?

**Comment by sumitsum** [comment] 2023-01-24 09:02
Closing this issue since we are pursuing each issue separately as well (redundancy). Of the issues mentioned above, we have at the moment marked the following issues are critical: 
#19812, #19992

#19959 AFAIK, was not supported before. 
#20018 is not a bug - it was a bug being leveraged as a feature. If we want to support it, we would have to pursue it as a new feature request.

**Closed** 2023-01-24 09:02 UTC
Labels: Bug, Needs Triaging, MySQL, BE Coders Pod, Integrations Pod

**Comment by felix-appsmith** [comment] 2023-01-24 21:13
New problem that could be related to the driver update: https://github.com/appsmithorg/appsmith/issues/20048

**Comment by sumitsum** [comment] 2023-01-25 05:31
@felix-appsmith this issue looks related to MsSQL not MySQL ?
