### ISSUE TITLE
[Feature]: horizontal list

### ISSUE THREAD

**Issue by jauniuseitmantis** [appsmithorg/appsmith#9475] opened 2021-11-30 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

for now list is only vertical, I wish for horizontal list also

### Why should this be worked on?

this would add much more possibilities to create different ui cases. For now it is not possible to make horizontal list of controls when data comes from backend as it is dynamic.

**Comment by areyabhishek** [comment] 2021-11-30 18:44
Thanks @jauniuseitmantis for the request. We'll be working to introduce a grid widget.

**Comment by dilippitchika** [comment] 2021-12-30 06:58
@somangshu is this similar to the scope of #7256 (Grid widget)? Can we link it there and close this?

**Comment by Nikhil-Nandagopal** [comment] 2021-12-30 07:10
@dilippitchika this is slightly different. A grid widget lays tiles out in one axis and scrolls in the opp axis i. lays horizontally but scrolls vertically. A horizontal list simply scrolls horizontally

**Comment by dilippitchika** [comment] 2021-12-30 07:14
@Nikhil-Nandagopal is it like a carousel/slide widget then where you can scroll horizontally based on the content?

**Comment by Nikhil-Nandagopal** [comment] 2021-12-30 07:17
@dilippitchika yes

**Comment by dilippitchika** [comment] 2021-12-30 07:21
Ok, then Duplicate of #9370. Closing this and adding an indication of this request there.

**Closed by dilippitchika** 2021-12-30 07:21 UTC
Labels: Enhancement, App Viewers Pod, UI Building Pod, community, List Widget

**Comment by somangshu** [comment] 2021-12-30 12:02
@dilippitchika these our separate things all together, check out [this](https://getbootstrap.com/docs/5.1/components/carousel/) example of what is mentioned in #9370. Also closer to this would be #7256

**Comment by dilippitchika** [comment] 2021-12-31 05:35
:confused: I thought this was grid widget first, and then thought it was carousel. Now it seems like we have a mix of both, @somangshu is this the expectation?

![image](https://user-images.githubusercontent.com/19730984/147805410-9c721a69-3872-47af-bfc4-55706f42180f.png)

**Comment by somangshu** [comment] 2022-01-05 09:08
@dilippitchika think about this again, Seems like you are in the right direction, Essentially the horizontal list and carousal are the same UX / UI.

On that note, its also essential to have the orientation on the list widget, this is a very common ask.

Another point with the carousal is that the text is usually expected to be available as an overlay on the image in a carousal. This is also a very common behaviour.

**Comment by Akshaya1997** [comment] 2023-06-01 05:54
@Nikhil-Nandagopal does appsmith support horizontal list?
