### ISSUE TITLE
[Feature] Set widget property function

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3523] opened 2021-03-12 12:00 UTC
## Summary
Introduce a setWidgetProperty function to set a widget **meta** property via a trigger

## Motivation
It gives developers more power to set values to the end-users inputs dynamically.

**Comment by Nikhil-Nandagopal** [comment] 2021-03-12 12:02
@hetunandu duplicate of #1897 
can we do this without a function and instead directly as Input1.text = "Hello"
This function is not a good solve

**Closed by Nikhil-Nandagopal** 2021-03-12 12:02 UTC
Labels: Actions Pod, JS

**Comment by hetunandu** [comment] 2021-03-12 12:08
This is a sibling of the `resetWidget` function introduced recently. The idea is to set only the meta properties of a widget and not outwrite reset it. Directly setting this to `Input1.text` would be against the reactive programming paradigm, no?

**Comment by Nikhil-Nandagopal** [comment] 2021-03-12 12:12
@hetunandu yeah only for meta properties but Input1.text = "hello" just makes for a cleaner interface.
Input1.text = "Hello" doesn't go against the reactive paradigm because you cannot configure the text property of the input from the property pane. Properties from the property pane are declarative while those that users can input (meta) are programmatic.

**Comment by hetunandu** [comment] 2021-03-12 12:17
Won't it be confusing to only do this in trigger fields of property panes and that too for certain widget properties? Making it a function makes it look like abstraction as it does not directly set the value. We are creating an effect to make the change in the actual tree.

**Comment by Nikhil-Nandagopal** [comment] 2021-03-12 12:25
@hetunandu I see your point but then should this be a global method or should it be a method of the widget? Because as a global method I'm just guessing as to what is the widget and property but I think a 
Input1.setText("Hello") makes more sense as an SDK

**Comment by hetunandu** [comment] 2021-03-12 12:36
I like this! It is obvious and also concise. The autocomplete can help a lot in this aspect. I'll create a new issue around this

**Comment by hetunandu** [comment] 2021-03-12 18:57
Created #3532 based on this discussion

**Comment by ahmadalibaloch** [comment] 2021-11-20 21:04
Use Case: 
I have a form with many input fields, they represent data of a month selected using date picker. Now when I switch between months, I want to load the data user has entered previously in those input fields. I get the data from Firestore. I would like to do 
```
input1.text = getFireDoc().input1;
input2.text = getFireDoc().input2;
input3.text = getFireDoc().input3;
input4.text = getFireDoc().input4;
input5.text = getFireDoc().input5;
```

I tried to set default value of inputs using {{getFireDoc().input4}} for example for input4 but that only happens at the load time of the app or page. I want to trigger default value field manually or set the input text programmatically to recalculate the correct field value based on the current date (month) selected or date_picker.value.

**Comment by Nikhil-Nandagopal** [comment] 2021-11-22 06:49
@ahmadalibaloch when you set the default value, it will automatically update whenever the data changes, it is only only at the time of page load. So depending on the re-calculation you're making, if you have bound the default text of the input correctly, the input will update. We'll be happy to help you with this if you can describe what you'd like to achieve here

**Comment by ahmadalibaloch** [comment] 2021-11-22 07:27
Here is the scenario and problem.
1. I have a query named `current_month_document` , it fetches the document at path "year/month" from Firestore based on the value of a form input "date_picker" `date_picker.value`. I run the query on page load at start.
2. I have a field with name "current_month_bill", which has default value set as "{{current_month_document.data['Current_month_bill']}}, it works well on page load.
3. When I change the value of  date_picker after load, the default value of field "current_month_bill" doesn't change for new document. Even I rerun the query on date picker change. 

here is the app I have made it public. https://app.appsmith.com/applications/615c1e3b05fc5e1d45b5e7e0/pages/615c1e3b05fc5e1d45b5e7e2

**Comment by ahmadalibaloch** [comment] 2021-11-23 23:57
@Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment] 2021-11-24 07:23
@ahmadalibaloch can you invite nikhil@appsmith.com to your app? I need access to the edit mode to see what is going wrong here

**Comment by Nikhil-Nandagopal** [comment] 2021-11-24 09:28
@ahmadalibaloch I am looking at your response and I don't see a current_month_bill or bill_main in the document. Could you tell me which date should I look for?

**Comment by ahmadalibaloch** [comment] 2021-11-24 09:46
Ok the problem was to create a dynamic db path, the path should be calculated in a method. Thanks @Nikhil-Nandagopal for live support!
