### ISSUE TITLE
[Bug]: No longer able to merge to protected branches

### ISSUE THREAD

**Issue by Akatroj** [appsmithorg/appsmith#31622] opened 2024-03-08 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm not able to merge git branches to `master` through the UI, because it's protected.

Branches listed:
<img width="25%" alt="image" src="https://github.com/appsmithorg/appsmith/assets/46789820/d1fccb75-6f96-46cf-aa21-f0168f1d1a9a">

Master is not visible in the merge tool because it's protected:
<img width="620" alt="image" src="https://github.com/appsmithorg/appsmith/assets/46789820/7978a9f5-9117-42c2-aad5-2b4961f302ee">

master is visible after turning off branch protections
<img width="634" alt="image" src="https://github.com/appsmithorg/appsmith/assets/46789820/6b97a3a7-e88b-40fc-b855-c4050e9cba75">

I am sure this worked before we updated to the latest version.

### Steps To Reproduce

1. Go to any git connected project
2. set up a protected branch
3. create a feature branch and commit some changes
4. try merging the feature branch

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self-hosted Appsmith v1.16

**Comment by brayn003** [comment] 2024-04-19 09:49
Hi @Akatroj,
This behaviour is by design. The idea behind protected branches is to disable any direct changes to that branch (including merge changes) and instead drive it through the PR review process. This would mean, you'll have to raise a PR on Github (or any other service provider you are using) and then merging it via the PR review process and then pulling the changes in your protected branches.
If you are not comfortable with this process, you can always remove branch protection for your current branch using the following steps - 
1. Go to Git Settings (gear icon in the bottom bar) 
2. Click on the branch tab
3. Remove the protected branch from the branch protection section

**Comment by brayn003** [comment] 2024-04-19 09:49
Closing this issue for now. If you are facing any other issue, feel free to open another one

**Closed by brayn003** 2024-04-19 09:49 UTC
Labels: Bug, High, Production, Community Reported, Needs Triaging, Git Version Control
