### ISSUE TITLE
[Bug]: Users get locked out when super admins disconnect SSO

### ISSUE THREAD

**Issue by pranayagarwal96** [appsmithorg/appsmith#27846] opened 2023-10-05 12:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consider a scenario where super user connects to an SSO provider (Google SSO, OIDC, etc.), and logins into the instance. Now, if super user disconnects the SSO there are two issues:
1. Existing sessions do not get invalidated
2. Existing users get locked out of the instance when they try to login again into the instance
<img width="1434" alt="image" src="https://github.com/appsmithorg/appsmith/assets/111730799/b0392c8f-857f-4f7e-b965-c580ff114f50">
  

### Steps To Reproduce

1. Setup a new instance
2. Connect to SSO
3. Re-login the super user via SSO
4. Disconnect SSO
5. Logout the super user from instance
6. Try entering super user email to sign-in again into the instance 

### Environment

Production

### Version

Self Hosted - 1.9.37

**Comment by riteshkew** [comment] 2024-10-04 05:25
Duplicate of #13518

**Closed by riteshkew** 2024-10-04 05:25 UTC
Labels: Bug, High, Production, Needs Triaging, Platform Administration Pod, SSO, Identity & Authentication Product
