### ISSUE TITLE
[Bug]-[62]:RTE error highlight includes the label element

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#14019] opened 2022-05-23 09:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The RTE widget error highlight is on both the component and label. Whereas it should only be on the input component.

While fixing this we need to find the same for any I/O widgets with label. 

<img width="1508" alt="Screenshot 2022-05-20 at 15 34 59" src="https://user-images.githubusercontent.com/11089579/169787523-bbe9245b-6a58-4c69-931f-4dc02f071451.png">

### Steps To Reproduce

1. D&D RTE
2. Set to required
3. check the error highlight; it must be only on the input component

### Version

Cloud - v1.7.0

**Comment by dilippitchika** [comment] 2022-05-24 10:08
Fix - Only show the red border on the editor and not the label

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 62 |
| Effort (months)  | 0.5 |

**Comment by Tooluloope** [comment] 2022-05-26 06:17
@somangshu @dilippitchika 
From the screenshot below, the Date picker doesn't have the red border to signify that it's required.
Should this be fixed in this PR?

Also, the UI for Checkbox Group and Switch Group looks odd, was this intended compared to a single checkbox
<img width="845" alt="Screenshot 2022-05-26 at 07 14 30" src="https://user-images.githubusercontent.com/31691737/170428449-9b2f3d53-ce27-4642-bfc9-2adef43e578a.png">

**Comment by dilippitchika** [comment] 2022-05-26 09:56
Hey Tolu, no i don't think it was intended. We need some design for these.

**Comment by Tooluloope** [comment] 2022-05-26 11:18
@dilippitchika 
This PR would only solve the RTE issue, everything else would be outside this PR

**Comment by dilippitchika** [comment] 2022-05-26 11:29
Hey @Tooluloope yes that is the expectation

**Closed** 2022-06-01 12:11 UTC
Labels: Bug, Rich Text Editor Widget, Input Widget, App Viewers Pod, Low, UI Building Pod, Papercut

**Comment by shadabbuchh** [comment] 2022-06-03 09:08
Issue has been verified in Release and it is working as expected.

<img width="1920" alt="Screenshot 2022-06-03 at 2 36 37 PM" src="https://user-images.githubusercontent.com/39921438/171824749-76500204-8b5e-40cf-a64f-0375d18279f1.png">
