### ISSUE TITLE
[Feature]: I need a function that can focus on the input

### ISSUE THREAD

**Issue by developer-honoru** [appsmithorg/appsmith#16965] opened 2022-09-22 00:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to be able to focus on the input whether it is javascript or an action.

### Why should this be worked on?

I want to go directly to the input window when I press the button, but I can't.

**Comment by bharath31** [comment] 2022-11-29 07:48
duplicate of #4874

**Closed by bharath31** 2022-11-29 07:48 UTC
Labels: Enhancement, FE Coders Pod, New JS Function

**Comment by developer-honoru** [comment] 2022-12-13 03:19
@bharath31 I wonder why they decided not to plan this
https://github.com/appsmithorg/appsmith/pull/17339#event-7706124739
I was waiting for @rimildeyjsr to come up with a new method.
If there is no developer to do this, can I make one?
i need this function
