### ISSUE TITLE
[Bug]:Invite user call is failing while trying to Share Application Intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#23985] opened 2023-06-02 08:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Invite User call is failing while trying to share app by inviting new user

### Steps To Reproduce

Steps:

1.Try inviting another user at app level.
2.Check the status of the call.

Expected:
User should be able to invite user

Actual:
Unable to invite user intermittently as the call itself is failing
<img width="1011" alt="Screenshot 2023-06-02 at 1 02 30 PM" src="https://github.com/appsmithorg/appsmith-ee/assets/67676905/bb1a8512-f212-40a2-8b7d-c6508d2b1850">

Reference runs:
https://cloud.cypress.io/projects/n14p1y/runs/7298/test-results/979b3dfe-f43a-4a9c-8b48-294b73d5bb95?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

https://cloud.cypress.io/projects/n14p1y/runs/7277/test-results/a6decf33-21f1-4316-815b-8281d60d106a?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

### Environment

Release

### Version

Appsmith v1.9.20.5-SNAPSHOT

**Comment by Aishwarya-U-R** [comment] 2023-06-02 12:01
@ankitakinger - Please help check this bug. CI runs failing randomly with - Internal server error while inviting user.

**Comment by Aishwarya-U-R** [comment] 2023-06-02 12:01
cc: @Vijetha-Kaja @Parthvi12

**Comment by ankitakinger** [comment] 2023-06-02 12:18
Also noticed ShareAppTests_spec is passing on the latest runs on EE Cypress dashboard @Aishwarya-U-R @NandanAnantharamu

**Comment by Aishwarya-U-R** [comment] 2023-06-02 12:18
@ankitakinger - Issue is random in CI runs. Hence the test is flaky. We need to identify the root cause for why inviting user might fail randomly - with` Internal server error` as shown in screenshot & fix it.

**Comment by ankitakinger** [comment] 2023-06-06 05:04
@Aishwarya-U-R @NandanAnantharamu is this still happening? I don't see this anymore on CI dashboard.

**Comment by Aishwarya-U-R** [comment] 2023-06-06 06:06
It is intermittent @ankitakinger. Unless we see for an extended period of time on its stability - we cant recommend closing this bug.

**Comment by Vijetha-Kaja** [comment] 2023-07-19 09:44
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/8350/test-results/409a8a6c-dbfd-4e32-8213-2c22d137ceab/screenshots) with above failure

**Comment by NandanAnantharamu** [comment] 2023-08-01 05:56
recent [run](https://cloud.cypress.io/projects/n14p1y/runs/8691/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression%2FClientSide%2FWorkspace%2FShareAppTests_Spec.ts%22%2C%22value%22%3A%22%5B%5C%2253d08b2e-5658-4589-944e-f44bd2d16957%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_campaign=view%20spec&utm_medium=failed&utm_source=slack) with above failure

**Comment by NandanAnantharamu** [comment] 2023-08-01 15:37
recent [run](https://cloud.cypress.io/projects/n14p1y/runs/8724/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression%2FClientSide%2FWorkspace%2FShareAppTests_Spec.ts%22%2C%22value%22%3A%22%5B%5C%22165a00e3-73d8-4745-a847-18fbd6d42b4f%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D) with above failure

**Comment by ankitakinger** [comment] 2023-08-01 20:28
@nsarupr Could you check this one too?

**Comment by Aishwarya-U-R** [comment] 2023-08-04 13:24
@ankitakinger @nsarupr - Failure in latest run [2 hours ago](https://cloud.cypress.io/projects/n14p1y/runs/8891/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression%2FClientSide%2FWorkspace%2FShareAppTests_Spec.ts%22%2C%22value%22%3A%22%5B%5C%22260d452f-914b-4c4c-9670-83727fe2a36c%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_campaign=view%20spec&utm_medium=failed&utm_source=slack)

**Comment by Aishwarya-U-R** [comment] 2023-09-15 15:51
[Latest run failure](https://internal.appsmith.com/app/cypressdashboard/specdetails-64ec3df0c632e24c00764939?branch=master&specID=819218&testsstatus=failed), [Logs](https://github.com/appsmithorg/appsmith/actions/runs/6199518829)

**Comment by ankitakinger** [comment] 2023-09-16 09:25
@nsarupr 
Attaching logs here in case the data gets deleted later as per retention period:
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/12640310/dockerlogs.zip)

**Comment by shubham7saxena7** [comment] 2023-09-20 08:37
@ankitakinger was this happening on release-ee only or other instances as well ?

**Comment by shubham7saxena7** [comment] 2023-09-20 08:37
@ankitakinger was this happening on release-ee only or other instances as well ?

**Comment by Aishwarya-U-R** [comment] 2023-09-20 08:41
@shubham7saxena7 - this is happening anywhere ShareApp spec is run. In CE & EE also.

**Comment by Aishwarya-U-R** [comment] 2023-10-25 13:21
Closing this since we dont see it now, past 2 weeks stats, will re-open if this resurfaces.
cc: @Parthvi12

**Closed by Aishwarya-U-R** 2023-10-25 13:21 UTC
Labels: Bug, High, Release, Needs Triaging, Invite users, Team Managers Pod, CI impacted
