### ISSUE TITLE
[Bug]: Demo user gets redirected to login page while trying to save Snowflake DS for staging config

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31535] opened 2024-03-06 06:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to save Snowflake DS config for staging environment, I get redirected to the login page.

### Steps To Reproduce

This issue is Specific to [nightly](https://nightly-saml-alb-https.appsmith.com/user/login) and to this particular [application](https://nightly-saml-alb-https.appsmith.com/app/oldapp-dstesting1-9-24/oauth20-65b0af0b54733a264591f96b).

https://github.com/appsmithorg/appsmith/assets/101863839/b8825e34-3ccb-4423-b519-68e47338bc4c

### Environment

Production

### Severity

High (Blocker to building)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2024-04-29 07:31
The user didn't seem to have access to editing that datasource. Some issue with the permissions it looks like but it's clear this is not a blocker to building

**Comment by Nikhil-Nandagopal** [comment] 2024-04-29 14:24
@btsgh are you able to reproduce it on prod?

**Comment by NilanshBansal** [comment] 2024-07-11 09:10
@btsgh closing this issue since it is not reproducible on prod. Please reopen if it does 🙏

**Closed by NilanshBansal** 2024-07-11 09:10 UTC
Labels: Bug, Datasources, Low, Production, Low effort, snowflake, BE Coders Pod, Integrations Pod
