### ISSUE TITLE
[Bug]: Welcome Tour - Stuck on Step 2

### ISSUE THREAD

**Issue by silversoul93** [appsmithorg/appsmith#21089] opened 2023-03-01 13:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi guys,
I was trying the welcome tour but I got stuck on step 2.

I cannot click on the **CustomersTable** widget on the left panel, nothing happens.
<img width="1917" alt="Screenshot 2023-03-01 alle 13 55 34" src="https://user-images.githubusercontent.com/28152586/222145946-d25601f6-24c4-435a-89ca-58015d09cf40.png">

Could you please verify?

### Steps To Reproduce

1. Login into AppSmith cloud
2. Click on "Welcome Tour" on the bottom left menu
3. Start the tour
4. On the step 2, try to click on the **CustomersTable** widget

### Environment

Production

### Version

Cloud

**Comment by akash-codemonk** [comment] 2023-03-14 13:46
Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/21048

**Closed** 2023-03-14 13:46 UTC
Labels: Bug, High, Community Reported, Needs Triaging, Onboarding, New Developers Pod
