### ISSUE TITLE
[Bug]: App card buttons do not appear if the user clicks on the 3 dots next to it and then hovers back 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15655] opened 2022-08-03 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Edit` & `Launch` buttons do not appear if the user clicks on the 3 dots next to the app card and hovers back over the app.

https://www.loom.com/share/4fe901ff96374d899fe432597ece1a03

### Steps To Reproduce

1. Go to the homepage.
2. Hover over any app card and you'll get to see the `Edit` & `Launch` buttons.
3. Now click on the 3 dots next to the card.
4. Hover back on the app card.

**Expected:** The `Edit` & `Launch` buttons should appear on hovering like they did in the first place.

### Version

Cloud

**Comment by pranavkanade** [comment] 2022-08-08 07:19
@shadabbuchh is this a bug though? @Debsourabh can you please validate, please close the issue if not a bug.

**Comment by shadabbuchh** [comment] 2022-08-08 07:32
> @shadabbuchh is this a bug though?

@pranavkanade it is a little irritating for the user to bring the focus out of the app card and then focus on it again for the button to reappear.

**Comment by shadabbuchh** [comment] 2022-08-10 05:53
Duplicate of https://github.com/appsmithorg/appsmith/issues/6784

**Closed** 2022-08-10 05:52 UTC
Labels: Bug, UX Improvement, Home Page, Production, Needs Triaging, Team Managers Pod, medium
