### ISSUE TITLE
[Feature] Allow removing time input from the date picker

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2971] opened 2021-02-10 11:23 UTC
## Summary
Allow remove time input from the date picker

## Motivation
Currently, there isn't an option to hide the time input which might be confusing to end users

**Comment by Nikhil-Nandagopal** [comment] 2021-02-10 12:20
Duplicate of #1579

**Closed by Nikhil-Nandagopal** 2021-02-10 12:20 UTC
Labels: Date Picker Widget, Enhancement, UI Building Pod, Widgets, community

**Comment by areyabhishek** [comment] 2021-02-10 15:08
@Nikhil-Nandagopal How do you remember duplicates?! Pretty impressive memory for issues!

**Comment by Nikhil-Nandagopal** [comment] 2021-02-11 06:28
I usually just think if I'm surprised by the issue then it's probably something we haven't filed. If I'm not then I do a quick search using the keywords to find the related issue :)
