### ISSUE TITLE
[Bug]: Error messages in templates

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#28967] opened 2023-11-20 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Errors seen across templates
Customer Support Dashboard - Shows 404 error. And upon clicking on `Add selected pages` throws error
![image](https://github.com/appsmithorg/appsmith/assets/92293815/002aa3ed-acb9-4298-8c4d-a7043bf17b46)
![image](https://github.com/appsmithorg/appsmith/assets/92293815/65e9bb95-eff2-4dd0-9630-6e71d5bc8361)

Marketing Dashboard
![image](https://github.com/appsmithorg/appsmith/assets/92293815/a897a5f0-d41d-4a5a-b6a3-d8737da6d29e)

Discord Bot for GitHub Updates
![image](https://github.com/appsmithorg/appsmith/assets/92293815/674e9234-996d-4724-9ad7-b7d517804b57)

Meeting Scheduler
![image](https://github.com/appsmithorg/appsmith/assets/92293815/8163ec62-27f5-434b-ba83-32e549a64f60)

Fund Raising CRM
![image](https://github.com/appsmithorg/appsmith/assets/92293815/10716176-aa8b-4324-b97e-6c57a846df1c)

### Steps To Reproduce

1. Open any application
2. Click on `Add page from Template`
3. Add the above mentioned templates

### Environment

Release

### Version

Cloud

**Comment by jacquesikot** [comment] 2023-11-20 12:38
A duplicate of the prod version has been created on release and the appUrl has been updated. The template has also been updated in prod and a new JSON file has been uploaded. This fixes all the issues on release and prod.

**Closed by jacquesikot** 2023-11-20 12:38 UTC
Labels: Bug, High, Regressed, Needs Triaging, Templates pod, Templates
