### ISSUE TITLE
[Bug]: Queries do not get exported in a git connected app, by using partial export. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29917] opened 2023-12-28 08:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I partially export a git connected app's page, containing a query, a database, and a couple of widgets, the query does not get exported. 

### Steps To Reproduce

Partially export a page which has a query and a database, from a git connected app's master branch. Note that the query does not get exported.

https://github.com/appsmithorg/appsmith/assets/101863839/8fa3d273-e363-4623-83cd-c6350ed51309

This works in a non-git connected app. 

### Environment

Release

### Version

Cloud

**Comment by rahulbarwal** [comment] 2023-12-28 09:13
@AnaghHegde Please take a look at this git connected app issue.

**Comment by AnaghHegde** [comment] 2024-01-01 07:13
@btsgh Is this happening on a specific app or you can reproduce this in any application? I just tried the above steps and i. am unable to reproduce the issue. 
https://www.loom.com/share/a425a89f41ed439f9d5d3b360ff5d50b

**Comment by btsgh** [comment] 2024-01-02 05:46
@AnaghHegde  - [here](https://release.app.appsmith.com/app/dec14repo/oauth20-658a5b7de054ed68d37c8b13?branch=master) is the application where I am seeing the issue. have given you admin rights

**Comment by btsgh** [comment] 2024-01-02 06:50
@AnaghHegde - tried it on a few other existing git connected apps, and the issue is not occurring there. It seems specific to the above app that I have shared in the issue.

**Comment by AnaghHegde** [comment] 2024-01-02 12:49
Removed the priority since its specific to one application.

**Comment by AnaghHegde** [comment] 2024-01-03 04:56
Closing the issue as its not reproducible

**Comment by laveena-en** [comment] 2024-01-16 07:41
@AnaghHegde Re-opening the issue since the bug is seen consistently on prod. It isn't specific to a certain app or DS

App 1:
Loom: https://www.loom.com/share/9135cac4570440f096493ac852157473
[App](https://app.appsmith.com/app/jan15-test/page1-65a6185a445d0e41e26397ab?branch=test)

App 2:
https://www.loom.com/share/7a48670a641b4432b8e20b8207cdd7ef?sid=8675d01a-5499-48d9-a8d6-4d859c2196a4
[App](https://app.appsmith.com/app/regression-jan15-app/gsheet-65a4baba79e028469badc9d6?branch=laveena)

**Closed** 2024-01-17 15:39 UTC
Labels: Bug, High, Production, Needs Triaging, Templates pod, Partial-import-export
