### ISSUE TITLE
[Bug]: Delete UI issue  in Datasources (Workspace)

### ISSUE THREAD

**Issue by raza001** [appsmithorg/appsmith#33540] opened 2024-05-17 06:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below attach video
<img width="1680" alt="Screenshot 2024-05-17 at 11 46 59" src="https://github.com/appsmithorg/appsmith/assets/48116868/4ab616f0-7794-4f90-b493-8c2a6874a41b">

### Steps To Reproduce

1 Go editor 
2 and Select data icon on left side after that 
3 and create two Datasources 
4 Delete one of them

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/bd1376da04ef4594ad71b36392f66c1b

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment] 2024-05-21 07:51
This is a duplicate of #33182

**Closed by Nikhil-Nandagopal** 2024-05-21 07:51 UTC
Labels: Bug, Production, Community Reported, Needs Triaging, Medium
