### ISSUE TITLE
[Feature] Need more alignment options for button widget

### ISSUE THREAD

**Issue by vnodecg** [appsmithorg/appsmith#7913] opened 2021-09-29 04:32 UTC
## Description

Current button widget has text aligned to extreme right when we have an icon. Its better if we provide the user option to align the text and icon in the way they desire

<img width="348" alt="Screenshot 2021-09-29 at 09 53 49" src="https://user-images.githubusercontent.com/4994565/135203593-e069cf2b-b43e-496d-a684-1ba704bab72c.png">

This should change for the menu button widget as well

### Requirement
- An option to provide alignment of the icon and label, centered or space-between

**Comment by somangshu** [comment] 2021-09-29 05:55
Probably needs a new control or use a dropdown

**Comment by Cool-Runningz** [comment] 2021-10-01 16:03
Are there still design decisions needed on this before it can be worked on? If so, I am interested in working on this when and if it is still available.

**Comment by ieshreya** [comment] 2021-10-02 05:17
If the issue is still not sorted, I'm interested in taking this issue.

**Comment by pawankm21** [comment] 2021-10-02 10:45
A Range slider will be great.

**Comment by Cool-Runningz** [comment] 2021-10-03 06:53
I know I was the first to comment on this but feel free to assign this to another contributor since I am interested in working on a different issue. Thank you :)

**Comment by MitAbhay** [comment] 2021-10-04 04:19
Assign it to me... @vnodecg

**Comment by Nikhil-Nandagopal** [comment] 2021-10-04 10:12
@ieshreya this issue is yours if you're interested. The solution is to add a style property for the entire button called Justify Content as a dropdown with options
Start
End
Center
Space between
Space evenly

**Comment by momcilo-appsmith** [comment] 2021-10-04 11:10
@nikhil I think it should only be centered, have not really seen many buttons that have different alignment with the icon.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-04 11:30
@momcilo-appsmith great point, we can just have center, space between and space evenly

**Comment by Nikhil-Nandagopal** [comment] 2021-10-04 11:43
@ieshreya this issue needs a little more consideration in terms of UX so we're removing this issue from our contribution list. Please do find another good first issue

**Comment by somangshu** [comment] 2021-11-02 13:52
@vasanth-appsmith some design updates are still pending, once that is done we will take it up for implementation

**Comment by momcilo-appsmith** [comment] 2021-11-29 06:44
@somangshu @vasanth-appsmith Is the design here done?

**Comment by vasanth-appsmith** [comment] 2021-11-29 07:49
@momcilo-appsmith Yes, this is done?
[Link](https://www.figma.com/file/tVBQrt0G0XI89eS9m8cT5H/Menu-Widget?node-id=0%3A1)

**Closed** 2021-12-08 13:11 UTC
Labels: Enhancement, Frontend, Needs Design, App Viewers Pod, Button Widget, UI Building Pod
