### ISSUE TITLE
[Bug]: Not able to delete the datasource for the app created out of template

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#17273] opened 2022-10-03 11:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Created app with template - Customer support dashboard,
2. Added new page 
3. Deleted Pages created by template
4. delete the datasource created out of template

Actual - Error is displayed that can not delete the Datasource as action is attached to it
Expected - After deleting all the pages attached to datasource it should allow to delete the datasource

![image](https://user-images.githubusercontent.com/80756091/193563993-f977252b-d099-4718-b58d-d530e7693447.png)

### Steps To Reproduce

1. Create a new app with template - customer dashboard (google sheet)
2. Create new page and delete all pages attached to customer dashboard
3. delete all action attached to datasource and delete the datasource

It throws error that datasource can not be deleted as actions are attached to it

### Public Sample App

https://release.app.appsmith.com/applications/633ac19b38ab615cde3ab5ba/pages/633ac1d138ab615cde3ab5c0/edit/datasource/633ac36becf6173a15c33fd1

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-10-03 11:27
Duplicate of #10358

**Closed by Nikhil-Nandagopal** 2022-10-03 11:27 UTC
Labels: Bug, Datasources, Release, Needs Triaging, Templates, medium
