### ISSUE TITLE
Heroku deployment errors

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#14062] opened 2022-05-24 11:31 UTC
"It was looking that everything works but I am not able to get into the ""settings"" part as an admin. I have a lot of errors in the log some related to the amount of memory and some related to missing files. Any ideas ? Error R14 (Memory quota exceeded) - this is one of the errors."

**Comment by jnikhila** [comment] 2022-09-14 09:46
duplicate of #16039

**Closed by jnikhila** 2022-09-14 09:46 UTC
Labels: Documentation, Needs More Info, User Education Pod, A-Force, Doc Rehaul
