### ISSUE TITLE
[Feature] Support generic OAuth2

### ISSUE THREAD

**Issue by abagshaw** [appsmithorg/appsmith#2573] opened 2021-01-13 21:56 UTC
## Summary

Would be great if appsmith supported OAuth2 for any provider, not only Google and Github.

## Motivation

Lots of other useful providers like Okta, Cloudflare Access, etc.

**Comment by Nikhil-Nandagopal** [comment] 2021-01-14 06:28
@abagshaw thank you for the feature request! There are a few challenges with integrating login for any OAuth provider so we simply picked the ones developers would be most familiar with. We'll certainly keep an eye on this and integrate more in the future :)

**Comment by Nikhil-Nandagopal** [comment] 2021-03-01 16:09
Closing as duplicate of #2840 since it has more information

**Closed by Nikhil-Nandagopal** 2021-03-01 16:09 UTC
Labels: Login / Signup, Platform, advanced, community
