### ISSUE TITLE
[Bug]: The user is not able to navigate to Datasource page when user has app level Developer access

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22027] opened 2023-04-03 10:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is not able to navigate to Data source page when user has app level Developer access
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/229487953-b543ef5d-70dd-4790-9f44-56241ee61f33.png">

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now deploy the app
4. share the app with app developer access/ its app level with user 1
5. login as user 1
6.click on edit app
7. in the datasource section the + icon is missing

### Environment

Deploy Preview

### Version

deploy preview

**Comment by ankitakinger** [comment] 2023-04-03 14:42
Since the user has only app-level access, and not workspace-level access, they should not be allowed to create new datasources. Hence, the + icon is missing. I think this is not an issue.

**Comment by infinitetrooper** [comment] 2023-04-03 14:48
Yes @RakshaKShetty  - I checked again and this is expected. Datasources are at a workspace level, when a user is given developer access to an app, they can create/edit queries on that app for a datasource but, they cannot create/delete a datasource. Closing this as it is expected behaviour.

**Comment by RakshaKShetty** [comment] 2023-04-04 05:23
@infinitetrooper, @ankitakinger okay i got the point. i have a question here how does Generate Page works here because through this i can navigate to datasource page

**Comment by nsarupr** [comment] 2023-04-04 08:30
That's a good point @RakshaKShetty . Can you check the same behaviour by creating a custom role and not giving create datasource permission to it.
@ankitakinger a better way would be for us to add permission level CTA to the `+ Connect New Datasource` and use the create datasource permission in order to show it.

**Comment by infinitetrooper** [comment] 2023-04-04 08:40
@RakshaKShetty  - The ideal flow should be to only show the datasources the user has access to in the below dropdown and connect new datasource button should not be shown. If that is not happening then it's a bug.

Also, did the `generate page with the data` feature come before or after GAC?

![image](https://user-images.githubusercontent.com/16632903/229736924-d1527a2d-a44e-4390-9097-cb1567c7ed57.png)

**Closed** 2023-04-05 11:52 UTC
Labels: Bug, Needs Triaging, Deploy Preview, Team Managers Pod, RBAC
