### ISSUE TITLE
[Bug]-[1646]:App is deploying even when Git commit fails

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#15176] opened 2022-07-13 10:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even when a branch is marked as protected and committing fails, the view mode still has the new app. This is a blocker for deployments

### Steps To Reproduce

1. Connect an app to git
2. Mark the master branch as protected
3. Commit changes and see a failure
4. Open the view mode, the changes are there
Alternatively, if you add a pre-commit hook to the local docker image to fail the commit, this still works
```
#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi
```

### Version

Cloud

**Comment by vuiets** [comment] 2022-07-13 11:09
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 823 |
| Effort (months)  | 1 |

@AnaghHegde roughly estimating the effort for this to as 2 weeks, please feel free to correct me if you think different.

**Comment by IAmAnubhavSaini** [comment] 2022-07-13 11:43
We publish even before attempting to commit.

https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java#L440

**Comment by vuiets** [comment] 2022-07-19 05:14
@AnaghHegde could you review this on priority if a fix is in?

**Comment by AnaghHegde** [comment] 2022-07-19 05:51
@vuiets Changes look good to me. There is a test failure which @vishnu-gp is actively working on. Once the tests pass we are good to go.

**Comment by RakshaKShetty** [comment] 2022-09-19 14:04
Reopening the issue because we are still facing the issue with Discard functionality
https://www.loom.com/share/9030d7f9a5bd423eb303221c89041dcf

**Comment by hiteshjoshi** [comment] 2022-12-09 06:52
@RakshaKShetty to create a new issue for the discard functionality.

**Closed** 2022-12-09 06:51 UTC
Labels: Bug, QA, High, community, Needs Triaging, Git Version Control, Team Managers Pod

**Comment by RakshaKShetty** [comment] 2022-12-15 17:16
@hiteshjoshi This issue is no more reproducible
