### ISSUE TITLE
[Bug]: Switching to a branch without the current page shows no page found screen

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17234] opened 2022-09-30 11:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/67054171/193258812-fc3e06ac-1ec1-40ff-8dd1-cc6e2d31a6a6.mov

### Steps To Reproduce

1. Create an application.
2. Connect to git.
3. Create a new branch say `release`. 
3. Create a new page say `Page2`. So now this page isn't on master.
4. Switch branch to master. It shows the page not available screen.

It seems like a frontend issue where we switch the branch but the page remains the same. Seems similar to https://github.com/appsmithorg/appsmith/issues/11889 . In that issue the branch seems to disappear.

### Version

Cloud - Release - 1.8.5

**Comment by mohanarpit** [comment] 2022-09-30 12:15
Technically, Appsmith is behaving correctly. Since a page is not available on a particular branch, there’s a 404 error. In order to give users a better experience, we need to differentiate between scenarios where a user is switching the branch from inside the application to a user who shouldn't have any information about this application/page accessing the URL. In the former case, we can redirect the user back to the default home page. In the latter, Appsmith should just show a plain 404.

**Comment by Richarex** [comment] 2022-10-14 11:00
This issue is still reproducible. Please refer to the attached video:- https://www.loom.com/share/5ab72c0268a04dca8c2293f520de83c9

**Comment by AnaghHegde** [comment] 2023-03-28 15:33
@infinitetrooper This is a duplicate of the issue https://github.com/appsmithorg/appsmith/issues/20883.

**Closed** 2023-04-04 04:59 UTC
Labels: Bug, Needs Triaging, Git Version Control, medium, Git Pod
