### ISSUE TITLE
[Bug]: Number type input widget clears an entry when there's a decimal followed by a zero

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11449] opened 2022-02-25 07:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Input widget clears an entry when there's a decimal followed by a zero. Typing consecutive periods and then hitting 0 clears all input from the widget.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/49d05b2ea0b64b43a1b4113e22bb5fc6-00001.gif)](https://www.loom.com/share/49d05b2ea0b64b43a1b4113e22bb5fc6)

1. Change Input widget type to Number and try to enter `1.06` and observe the value revert to `1`
2. Try to type `1..0` and observe field values getting cleared

### Environment

Production

### Version

Cloud

**Comment by Himanxu1** [comment] 2022-02-25 14:25
Hey , I would like to contribute to this project .
I just want to know what technologies you are using to build this ?
If anyone can explain the bug then i will definetity work on this.

**Comment by sbalaji1192** [comment] 2022-02-28 10:07
@Himanxu1 Thanks for showing interest.
This issue is a little nuanced and requires a considerable amount of change.
You can find a `good first issue` to work on over here - https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22. If you're not able to understand the issue, please post your doubt and one of our team members will help you.

**Comment by chandannkumar** [comment] 2022-03-04 04:57
Due to failed DP link in PR, moving to In Progress again

**Comment by sbalaji1192** [comment] 2022-03-17 01:50
Reopening this issue as we have reverted the changes to fix an issue caused by placing the input widget inside a list widget.
refer:
issue - https://github.com/appsmithorg/appsmith/issues/11833
revert PR - https://github.com/appsmithorg/appsmith/pull/11888

**Closed** 2022-03-18 16:48 UTC
Labels: Bug, Input Widget, App Viewers Pod, Critical, Production, UI Building Pod
