### ISSUE TITLE
[Bug]: Airtable : Suggested list of widget are not appropriately displayed 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#15972] opened 2022-08-12 08:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the Query is RUN with an array of objects using Airtable the suggested widget list displayed is only Text However other Datasources display a list of widgets

### Steps To Reproduce

1) Create Airtable Datasource 
2) Create a Query 
3) Run the Query and 
observe the suggested widgets 
![Screenshot 2022-08-11 at 10 57 48 AM](https://user-images.githubusercontent.com/71753653/184314812-87dc0a67-62ec-4124-aa44-207436cf9d82.png)

### Version

Release

**Comment by sumitsum** [comment] 2023-05-05 10:04
IMO, this should automatically fix if the returned response is not enclosed within the `records` key.

**Comment by sumitsum** [comment] 2023-06-16 08:31
Closing it as this is not a bug.

**Closed by sumitsum** 2023-06-16 08:31 UTC
Labels: Bug, Low, Release, BE Coders Pod, Airtable, Data Platform Pod, Integrations Pod, Suggested Widgets
