### ISSUE TITLE
[Bug]: Unpredictable movements of the dates in the date picker included in the table widget; are decreased by 1 day.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#25081] opened 2023-07-04 19:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, in a table widget, if we try to add a new row and one of the fields is a date picker, it will decrease the selected date by one day. For example, if I select `2023-07-09`, it will select `2023-07-08`. The strange thing about this bug is that it only occurs in a European time zone; it doesn't happen in another time zone.

### Steps To Reproduce

I tried to replicate the issue unsuccessfully. However, the user shared the  [application](https://app.appsmith.com/app/test-bug-date/commandes-extra-649eeac36f8d8c15e6a0c56e) where the problem can be seen. Make sure you are in a European time zone.

For more context and videos, you can see the conversation with the user: https://app.frontapp.com/open/cnv_11b2uw5o?key=6Ow9FD3H6U0PYcJY6lBMKc7w2XqkaAaq

### Public Sample App

https://app.appsmith.com/app/bug-date-simple/page1-64a7d393af033d5dcc48b2e6

### Environment

Production

### Issue video log

https://www.loom.com/share/405cc2a2c6aa416ea7245721dc33dc76?sid=398a0130-dc0e-4bea-8be4-44fc7b0c83e8
### Version

Cloud: Appsmith v1.9.25-SNAPSHOT

**Comment by somangshu** [comment] 2023-07-05 09:17
My understanding here is that the timezone that is stored in the DB and selected on client side are different. 
Usually this kinda issue happens when the timezone stated in the date object is different from the one you are in. This will show unpredictable results with default date objects. This is specially visible because the user is only viewing `dd-mm-yy`. If we can see the full date before and after, it will be easier for us to help them out. 

![Screenshot 2023-07-05 at 2 41 31 PM](https://github.com/appsmithorg/appsmith/assets/11089579/dbad18e7-0181-4266-b192-4b07a5db7fef)

**Comment by benjamindonze** [comment] 2023-07-05 16:25
This is not unpredictable this is always happening when:
 - you have a table widget with a date column with format YYYY-MM-DD
 - you add a new row
 - you are in european time zone

The problem here is that I set my date widget to use format date format (and display format) YYYY-MM-DD. Apparently when updating the row I can see by printing with in logs that "currentRow" does correctly hold a date in the format YYYY-MM-DD that match the one you select in the widget.

But when adding a row the value hold by "newRow" is in format 2023-07-19T22:00:00.000Z. So probably if you select 2023-07-20 in that widget it actually select 2023-07-20T00:00 in my local time zone and then transform it to UTC time zone. While it should work only with date (with no time)

Well anyway the problem happens in the widget as I can see this happens before the query to the DB. Moreover the issue only happen with new row, row update seems to work.

**Comment by benjamindonze** [comment] 2023-07-07 11:08
Looking at the code for [DateCell widget](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/TableWidgetV2/component/cellComponents/DateCell.tsx#L215) I can see that when selecting the date while updating a date, the date is formated with 
`const formattedDate = date ? moment(date).format(inputFormat) : "";`
But this is not done when it is a new row.

Thus this probably lead to keeping the date with time when beeing in newRow mode and so applying some timezoning but correctly handinling the updates.

See below the whole code block:

```
const onDateSelected = (date: string) => {
    if (isNewRow) {
      updateNewRowValues(alias, date, date);
      return;
    }

    if (isRequired && !date) {
      setIsValid(false);
      setShowRequiredError(true);
      return;
    }
    setIsValid(true);
    setShowRequiredError(false);
    setHasFocus(false);

    const formattedDate = date ? moment(date).format(inputFormat) : "";
    onDateSave(rowIndex, alias, formattedDate, onDateSelectedString);
  };
```

**Comment by amareshvarma** [comment] 2023-07-10 16:36
Is there a way I can contribute to this, any steps to reproduce

**Comment by imatpro** [comment] 2023-07-11 08:11
Hello, i have a same problem. when i select date in datepicker (without time precision)  the datepicker.selectedDate is at J-1
<img width="490" alt="Capture d’écran 2023-07-11 à 10 10 23" src="https://github.com/appsmithorg/appsmith/assets/7237663/d4de9697-fbbc-45b8-a72d-6642351eb4ee">

Thanks for helping

**Comment by benjamindonze** [comment] 2023-07-11 18:25
> Hello, i have a same problem. when I select date in datepicker (without time precision) the datepicker.selectedDate is at J-1

Well check the 1st post it includes a link to a sample app that shows the issue.

**Comment by benjamindonze** [comment] 2023-07-11 18:26
> Is there a way I can contribute to this, any steps to reproduce

Well check the 1st post it includes a link to a sample app that shows the issue.

**Comment by somangshu** [comment] 2023-07-12 11:25
Thanks for the detailed analysis @benjamindonze. This will help us debug and triage the issue better. 
We will take this up internally and prioritise it. 

@amareshvarma LMK if you are interested in contributing. This issue might be involved, so my suggestion is to start with other `good first issues`

cc @keyurparalkar

**Comment by amareshvarma** [comment] 2023-07-12 11:41
@benjamindonze 
![image](https://github.com/appsmithorg/appsmith/assets/31888121/e8ff751d-b147-4fca-bba5-018f17987656)
It says 404 error either it is not there or I do not have access

**Comment by benjamindonze** [comment] 2023-07-12 18:53
I have invited support@appsmith.com and made that app public so you should now have access otherwise I don't know how I can give you access

**Comment by benjamindonze** [comment] 2023-07-17 10:19
Well I have added support@appsmith.com in the workspace and made the app public so it should be working now

**Comment by somangshu** [comment] 2023-07-20 08:57
@amareshvarma the app might not be accessible to you. You will have to repro this on your own end.

**Comment by dilippitchika** [comment] 2023-07-20 12:56
Hello can you please use - `{{moment.utc(DatePicker1.formattedDate)}}` instead of using ` {{Datepicker1.selectedDate}}` for now?

@somangshu you are right, this confusion is coming quite often because selectedDate is taking the user's selection and internally using the locale to convert to UTC time. 

Our options are 
1. Add a new property in the datepicker which is a toggle to remove selectedDate UTC formatting
2. Add a new reference property called {{Datepicker1.localDate}} which will just give the selected date without any utc logic applied to it.


Please suggest if there are other options.

**Comment by benjamindonze** [comment] 2023-07-20 14:01
> @amareshvarma the app might not be accessible to you. You will have to repro this on your own end.

I can also add you to the app if you want

**Comment by PaulMcF1987** [comment] 2023-08-17 08:55
@somangshu @keyurparalkar @dilippitchika 

I have been faced with this issue and was pointed here form the discord support channel

I think I have since found a solution although it is early days

I was finding that, no matter what I tried, when using `moment` that the utc time was always applied, adding 1hour onto the time.
The issue only occurred with the Date/Time input, when viewing in a text widget, the date/time was able to be formatted correctly

I have since added the `https://cdn.jsdelivr.net/npm/date-and-time@3.0.2/date-and-time.min.js` library and am using `{{date.parse(appsmith.store.group.datetime, 'YYYY-MM-DD HH:mm:ss [GMT]' )}}`

This seems to have sorted the issue but time will tell

**Comment by benjamindonze** [comment] 2023-11-20 10:19
Any news on fixing this issue?

**Comment by Nikhil-Nandagopal** [comment] 2023-11-20 13:58
@benjamindonze we haven't picked this up yet and this could be an issue with moment. Try using the solution that Paul has mentioned above and let us know if it works!

**Comment by lrytz** [comment] 2024-05-14 12:39
To reproduce in a JS function (I assume it's the same underlying issue):

<img width="951" alt="image" src="https://github.com/appsmithorg/appsmith/assets/119636/7d66a49a-647b-4d29-91f5-10a10cbe5128">

**Comment by Harshithazemoso** [comment] 2024-05-21 09:32
I have picked up the issue and  I have tried tchanging the timezone to  europe and connected to datasource but  I couldnt reproduce the issue ,are there any steps how to reproduce this or is it resolved ?

**Comment by benjamindonze** [comment] 2024-05-22 11:17
Have you tried the public sample app link in the first post : https://app.appsmith.com/app/bug-date-simple/page1-64a7d393af033d5dcc48b2e6

It is very easy to see that the problem is still there. If you simply click "Add new row" and the select a date the save. Then you can see on the left pane "Changed row" that the date is not correct.
For exemple I select date "2024-05-22" and I see after saving in Changed row : {
  "date": "2024-05-21T22:00:00.000Z"
}

**Comment by Harshithazemoso** [comment] 2024-05-26 10:52
Thanks for the response @benjamindonze ,will look into that

**Comment by Harshithazemoso** [comment] 2024-06-06 04:13
hello @benjamindonze I have raised a pr for this issue,can you please look into it

**Comment by benjamindonze** [comment] 2024-06-10 08:23
I did put a comment and approved the PR

**Comment by rahulbarwal** [comment] 2024-10-04 09:20
This is fixed with: https://github.com/appsmithorg/appsmith/pull/36455

**Closed by rahulbarwal** 2024-10-04 09:20 UTC
Labels: Bug, Date Picker Widget, Widgets Product, Production, Community Reported, Needs Triaging, Medium, Table Widget V2, Table Inline Edit, Widgets & Accelerators Pod
