### ISSUE TITLE
[Bug]: Alignment of selected and unselected stars in rate widget is not same

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9336] opened 2021-11-24 09:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="338" alt="Screenshot 2021-11-24 at 2 56 21 PM" src="https://user-images.githubusercontent.com/83569920/143211234-5bbf4193-72a1-492a-ac92-ecce6c81bf6d.png">

<img width="895" alt="Screenshot 2021-11-24 at 3 02 36 PM" src="https://user-images.githubusercontent.com/83569920/143212207-6fecc2a5-b75c-43a2-a7b0-4efff5fe7176.png">

### Steps To Reproduce

1. Drag and drop a Rating widget
2. Change the size to small
3. Observe that the alignment of selected and unselected starts are not same

### Environment

Release

### Version

Cloud

**Comment by souma-ghosh** [comment] 2022-06-22 08:41
@somangshu Unable to reproduce this issue. Moving this to needs info.
@vivekverma2312 Could you check if this issue still persists?

**Comment by somangshu** [comment] 2022-06-22 09:47
same here, Closing for now

**Closed by somangshu** 2022-06-22 09:47 UTC
Labels: Bug, App Viewers Pod, Release, UI Building Pod, regression, Rating Widget, Papercut, medium
