### ISSUE TITLE
[Bug]Dragging and Dropping table widget 'The value at selected-row is invalid' error occurs in the debugger 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4731] opened 2021-05-27 12:01 UTC
## Description
Release Environment - Table Widget - It is observed that by dragging and dropping Table widget 'The Value at the selected row is invalid' error occurs in the debugger

**Expected Result:**
Error should not occur by Dragging and Dropping any widgets

**Actual Result:**
Dragging and Dropping table widget error 'The value at selected row is invalid' occurs in the debugger

### Steps to reproduce the behaviour:
1.Launch Appsmith app in the release Environment 
2.Expand Widgets
3.Drag and Drop table widget and observe

**Video Link:**
https://www.loom.com/share/e741880350784267bd70b6e07121d22d

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS Big sur 11.3]
- Browser [Safari]
- Environment [Release]

**Comment by somangshu** [comment] 2021-05-27 12:06
@YogeshJayaseelan was this seen in release before merge?

**Comment by YogeshJayaseelan** [comment] 2021-05-27 13:30
@somangshu  @prapullac  No we havent noticed earlier. Today i tried to test bug #822 and noticed this issue. 
In Safari i could see the entire message - selectedRowIndices.map is not a function. (In 'selectedRowIndices.map( (ind) => filteredTableData[ind], )', 'selectedRowIndices.map' is undefined)

In chrome i could see partial error message - selectedRowIndices.map is not a function

**Comment by somangshu** [comment] 2021-05-28 06:42
@ApekshaBhosale is this connected to #822, Kindly verify!

**Comment by somangshu** [comment] 2021-06-03 05:55
@SatishGandham can you look into this?

**Comment by vibhandikyash** [comment] 2021-06-03 08:53
@somangshu It seems like it has nothing to do with the changes I've made. I checked the same in the release branch it's there too... Maybe you can create a new issue and assign it to me... I've got the root cause for the same.

**Closed** 2021-06-21 09:09 UTC
Labels: Bug, High, Release, Table Widget, UI Building Pod, Verified, Widgets
