### ISSUE TITLE
[Bug]Text widget disappears when the user clicks anywhere on the canvas when there is an error in the text widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4934] opened 2021-06-04 14:20 UTC
## Description
Release Frozen - Text Widget - Drag and drop text widget and make some error and click anywhere on canvas and observed that the text widget disappears with property pane and we have to expand the entity explorer and click on the text widget from entity explorer and then the text widget re-appears

**Expected Result:**
If the user clicks anywhere on the canvas when there is error in the text widget the text widget should remain in the canvas until the error is resolved by user or user deletes text widget manually.

**Actual Result:**
Text widget disappears when the user clicks anywhere on the canvas when there is an error in the text widget

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the release frozen environment
2. Drag and drop text widget 
3. In the text field pass the following invalid value {{label}}
4. click anywhere in canvas and observe 

**Videolink:**
https://www.loom.com/share/4470e670d31c433ab04ead5484bb19ee

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by somangshu** [comment] 2021-06-07 05:17
@YogeshJayaseelan this is not a bug, Hovering on the text widget area brings out the widget border.

https://user-images.githubusercontent.com/11089579/120962577-a2236480-c77d-11eb-9230-ca414dc82b54.mov

Closing this!

**Closed by somangshu** 2021-06-07 05:17 UTC
Labels: Bug, Low, Needs Triaging, Text Widget, UI Building Pod, Widgets, regression, release-frozen
