### ISSUE TITLE
[Bug]: Save and authorize GSheets data source from a branch in a git connected app is throwing an error

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28478] opened 2023-10-30 12:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Save and authorize GSheets data source from a branch in a git connected app is throwing an error

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/68fd5de7-3f40-4352-9cbe-cb3925064cb8

### Environment

Deploy Preview

### Version

Cloud

**Comment by riteshkew** [comment] 2024-04-12 07:42
Couldn't reproduce in production with v1.18. Closing this hence.

**Closed by riteshkew** 2024-04-12 07:42 UTC
Labels: Bug, High, Needs Triaging, Deploy Preview, BE Coders Pod, Data Platform Pod, Custom environments
