### ISSUE TITLE
[Bug] Where condition is not functional for value "NA"

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7805] opened 2021-09-24 09:42 UTC
Description:
If the page contains NA in any column the data can not be fetched and gives an error and throws an error for any other true statement.  

Steps to reproduce:
1) Create an API of Gsheet
2) Add to fetch rows
3) Add required fields
4) Add "where "condition (sl no == NA)
ensure the sheet contains NA 

Observation:
It is observed that an error is displayed to the user

Expectation:
Result must be displayed to user 

Video
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/fa68665f9e7f45748ced6df2ea76dfee-00001.gif)](https://www.loom.com/share/fa68665f9e7f45748ced6df2ea76dfee)

**Comment by trishaanand** [comment] 2021-09-24 10:29
This is happening because slno has number values for the top few rows and NA is a string value. If a column has been tagged as a number value, string "NA" has failed to be parsed as a number.

**Comment by trishaanand** [comment] 2021-09-24 10:41
Duplicate of #7794

**Comment by Nikhil-Nandagopal** [comment] 2021-12-09 05:42
closing since its duplicate

**Closed by Nikhil-Nandagopal** 2021-12-09 05:42 UTC
Labels: Bug, Actions Pod, High, Release, regression, Needs Triaging, Google Sheets, BE Coders Pod
