### ISSUE TITLE
[Bug]: The search filter disappears when the user searches any country with invalid spelling

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9597] opened 2021-12-06 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user searches any country name with invalid spelling the search filter dropdown disappears. 

Expected result:
For any invalid search the filter should open and will not display any search result or valid message can be displayed 'No results found'

https://loom.com/share/2069b3111ef9480b883f36f9e86c03c7

### Steps To Reproduce

1.Launch appsmith app in release/Prod environment
2.Drag and drop input widget 
3.Change the input type to phone number
4.click on the country drop down on the widget 
5.Try to search any country with invalid spelling or any invalid characters and observe 

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-01-17 06:46
@sbalaji1192 is this fixed in the new input widgets for currency and country? If yes, can you please close this?

**Comment by sbalaji1192** [comment] 2022-01-17 09:33
@dilippitchika No. There was another issue with the dropdown. Will fix this separately along with that.

**Comment by somangshu** [comment] 2022-01-18 06:28
@sbalaji1192 if this needs to be tracked separately please add it back to the HPI epic, since we want to close the input widget issues epic, we need only related issues there.

**Comment by sbalaji1192** [comment] 2022-01-20 06:32
@somangshu This is the only outstanding issue in the input widget v2 epic. will close this week and then we can close the input widget v2 epic.

**Comment by YogeshJayaseelan** [comment] 2022-01-20 06:39
@sbalaji1192 Also observed by enabling allow currency or country code and on searching country and clicking on space the search filter disappears 

https://www.loom.com/share/b70ba522ee084e468c386bfbc35c0b97

Suggestion : To search country/Currency using keyword - For example : Typing 'America' or 'US/us' can show United states/Canda 

https://www.loom.com/share/889288d97c9341149cb18d57163abf4a

**Comment by sbalaji1192** [comment] 2022-01-20 07:15
@somangshu Just now debugged the issue. The issue is not related to the input widget. We're using ADS dropdown, so does the property pane dropdowns. Can observe this issue in both places. So removing this from the Input widget v2 epic. Lets add this to high priority issues.

**Comment by somangshu** [comment] 2022-01-24 09:17
@vicky-primathon please consult before beginning

**Closed** 2022-02-09 07:02 UTC
Labels: Bug, Input Widget, App Viewers Pod, Low, Production, UI Building Pod
