### ISSUE TITLE
[Bug]: User is stuck on deployment screen when using git-sync

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#20478] opened 2023-02-08 07:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="643" alt="Screenshot 2023-02-08 at 1 22 11 PM" src="https://user-images.githubusercontent.com/13262095/217468098-f6a2c664-a86d-4c01-9aa7-226dd245f1a2.png">

A user complained that they were stuck at the above screen. It turns out deployment fails without an error if the app is being edited from two different instances with different versions

### Steps To Reproduce

app is being edited from two different instances with different versions

### Version

v1.9.5

**Comment by AnaghHegde** [comment] 2023-02-10 10:14
@ginilpg This is also an issue from the FE. Frontend does not show the error message even though the server is responding with proper error message. 
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/12005551/218065529-ed6ac1ab-5173-4085-b8c4-2752b0c7fd51.png">

**Comment by akash-codemonk** [comment] 2023-03-09 10:32
Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/21100

**Closed by akash-codemonk** 2023-03-09 10:32 UTC
Labels: Bug, Frontend, Needs Triaging, Git Version Control, Git Pod
