### ISSUE TITLE
[Feature] Allow URL in table to have text that is different from the link

### ISSUE THREAD

**Issue by zdb999** [appsmithorg/appsmith#4145] opened 2021-04-26 06:26 UTC
I am trying to create links to files in an S3 bucket as an item in a table. This works well, but it showed the entire URL, which is very long, taking up a lot of space that could be better used for other things. It also does not really explain to the user what they are about to click on. It would be great if the URL text could be optionally entered in a separate field from the text, allowing them to be specified / templated separately.

I believe this change will generally make the table URL option much more useful.

**Comment by Nikhil-Nandagopal** [comment] 2021-04-26 06:40
@zdb999 you can use the button option here. So instead of the URL, you can show a button with a readable name and onClick assign the navigateTo the URL. 

```
{{navigateTo(currentRow.url)}}
```

**Comment by zdb999** [comment] 2021-04-26 09:26
That makes a lot of sense. Not perfect, but definitely gets the job done. I've got it working now. Thanks for your help.

**Comment by somangshu** [comment] 2021-04-30 10:00
Closing as duplicate of #4135

**Closed by somangshu** 2021-04-30 10:00 UTC
Labels: Enhancement, Table Widget, UI Building Pod, Widgets
