### ISSUE TITLE
[Bug]: Size of last column in table unpredictable especially when right alignment used for text column

### ISSUE THREAD

**Issue by nzidol** [appsmithorg/appsmith#16453] opened 2022-09-02 03:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using right alignment on last text column data can disappear beyond table border, I would expect that I can adjust the column widths to appear within the frame. For the last column the rendered size is unpredictable even when the actual size is set while column in different position in the table..

### Steps To Reproduce

On an empty page add a table.
Move "step" column to end of table.
![image](https://user-images.githubusercontent.com/13618973/188036120-9ee20fd2-ec4a-4245-9858-9cac595aa3a6.png)
Go to "step" column properties and select right alignment: data disappears outside table frame.
![image](https://user-images.githubusercontent.com/13618973/188036186-d772f5a1-f51a-4dce-a87b-b228dd46e2d8.png)
Stretch table frame  small step to the right to show the data: data disappears further right
![image](https://user-images.githubusercontent.com/13618973/188036231-6a92b768-f8c7-4231-b8cd-4070d40c68ac.png)

Essentially you can adjust column width for all columns except the last.
For instance when column "task" stretched, the table can be adjusted to show last column:
![image](https://user-images.githubusercontent.com/13618973/188035603-35e678ef-1396-41ff-a6d1-d6c63798fb4d.png)
Slight increase of table width and last column disappears again:
![image](https://user-images.githubusercontent.com/13618973/188035779-82b7a9c0-5231-4490-b6f9-bb22ca2dba77.png)
Move "task" column to last position to see configured width of "step" column
![image](https://user-images.githubusercontent.com/13618973/188036000-5440d09f-c40d-47d5-845a-00627c630c93.png)

### Version

Self Hosted 1.7.13

**Comment by dilippitchika** [comment] 2022-09-06 16:49
Duplicate of #15483, @nzidol we are currently working on this. Please track #15483 to know when this gets closed.

**Closed by dilippitchika** 2022-09-06 16:49 UTC
Labels: Bug, Table Widget, App Viewers Pod, Low, Needs Triaging
