### ISSUE TITLE
[Docs]: Modification required for the reCaptcha documentation under the "Validation Example" section

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#15654] opened 2022-08-03 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/button/google-recaptcha

### Describe the problem

In the reCaptcha document under the "Validation Example" section it shows to paste the generated secret key values in the 'header' 
![chrome_tuBrjTl0Qj](https://user-images.githubusercontent.com/93259714/182572190-73ae7949-2b79-4676-9f4e-e9bbd4935d74.png)

### Describe the improvement

In the reCaptcha document under the "Validation Example" section it shows to paste the generated secret key values  need to be sent in the body as post params i.e form-data and not in the headers.

![chrome_20fu83fQNe](https://user-images.githubusercontent.com/93259714/182571878-e6d12fd4-865f-404a-bd45-6b699d90c7be.png)

**Comment by jnikhila** [comment] 2022-08-10 07:11
Duplicate of #15863.

**Closed** 2022-08-10 09:35 UTC
Labels: Documentation, App Viewers Pod, Button Widget, User Education Pod
