### ISSUE TITLE
[Docs] Create documentation for storeValue function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#853] opened 2020-10-01 10:25 UTC
## Describe the problem

We do not have documentation for our storeValue action today. The action can be triggered by the action selector of a widget such as the onClick of a button

**Comment by hetunandu** [comment] 2020-10-01 13:46
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo. Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

The signature of the function is mentioned [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/utils/autocomplete/EntityDefinitions.ts#L244)

I'm here if you need any help fixing this so feel free to tag me on this thread 😄

**Comment by kichloo** [comment] 2020-10-02 08:11
I want to take uo this issue

**Comment by Nikhil-Nandagopal** [comment] 2020-10-02 08:19
@kichloo go for it!

**Comment by pooja1198** [comment] 2020-10-04 07:39
@Nikhil-Nandagopal , I see the issue is still open. Can you assign it to me ?

**Comment by hetunandu** [comment] 2020-10-05 07:32
@pooja1198 Assigning this to you. Please make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting and raise a PR in 2 days 🙂

**Comment by deepakchethan** [comment] 2020-10-10 07:33
@Nikhil-Nandagopal, @hetunandu Can I take this up as well as we need this page for sharing data across pages PR?

**Comment by hetunandu** [comment] 2020-10-10 07:38
Go for it @deepakchethan

**Closed** 2020-10-11 08:54 UTC
Labels: Documentation, Good First Issue, hacktoberfest
