### ISSUE TITLE
[Bug]: Cursor position on JS editor moves to home position when user switches to another tab

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9441] opened 2021-11-29 15:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cursor position on JS editor moves to home position when user switches to another tab

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ec73f4354c12464c8045191fdf94e3dc-00001.gif)](https://www.loom.com/share/ec73f4354c12464c8045191fdf94e3dc)

### Steps To Reproduce

1. Go to JS editor and type out something
2. Now tab to a different window and then back to the application
3. Observe cursor position has moved to start of code position

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2022-08-03 14:14
Duplicate of #8940

**Closed by Nikhil-Nandagopal** 2022-08-03 14:14 UTC
Labels: Bug, UX Improvement, Low, Release, JS Editor, FE Coders Pod, JS Usability
