### ISSUE TITLE
[Bug]-[2000]:Cyclic dependency error occurs when enabling JS in the checkbox group options field

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10332] opened 2022-01-12 07:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that in the checkbox group widget by passing the below name and option value and clicking on JS throws cyclic dependency error 

Name - Y Value - {{Y}} and 
Name - N Value - {{N}}

https://loom.com/share/19f6cadf21a046c08095d6d4432a82fe

### Steps To Reproduce

1.Launch appsmith app in release/Prod environment 
2.Drag and drop checkbox group widget 
3. Remove the existing options 
4. Add the following options 

 Name - Y Value - {{Y}} and 
Name - N Value - {{N}}

5.Click on JS and observe

### Environment

Production

### Version

Cloud

**Comment by YogeshJayaseelan** [comment] 2022-01-12 07:48
@somangshu The switch group widget crashes with the following message in console "TypeError: Cannot read properties of undefined (reading 'includes')" due to the above issue 

https://www.loom.com/share/0dc51f7534024b14be84b0389934950f

**Comment by somangshu** [comment] 2022-03-23 07:25
The CheckboxGroupWidget should ideally show an undefined variable linting error and not a cyclic dependency error. I've shared this with the team members, let's see what the root cause here is.

cc @ajinkyakulkarni @eco-monk

**Comment by rohan-arthur** [comment] 2022-05-03 07:33
6m usage of checkbox group, and subsequent encountering of cyclic dependency error: 500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | <<number>> |

**Comment by ohansFavour** [comment] 2022-06-14 07:17
After investigation, the root cause of this issue is the improper handling/update of the dynamicBindingPathlist for the `checkboxgroup` widget.

After toggling to JS, the options field becomes a string (previously an array), but the dynamicBindingPathlist doesn't get updated to reflect this change.

See [loom recording](https://www.loom.com/share/5df7dd0d1a5e4f32bd8c824b967edc3b)

**Comment by dilippitchika** [comment] 2022-06-16 05:03
@ashit-rath while we can remove the options non JS property, but based on the data more than 50% of users don't convert options to JS here. 

My first preference would be solution 2 and if we are unable to figure out a clean way then move to solution 1 or 3. Can you expand more on what de-risking few things means?

**Comment by ashit-rath** [comment] 2022-06-16 05:28
@dilippitchika To make the solution 2 we would have to ensure few things
1. When the JS mode is toggled we update the DSL in the appropriate time frame to avoid any possible race condition.
2. We also have to make sure that the conversion is lossless. 
Eg: 
a. If in JS mode the options structure is incorrect and the user disabled the JS mode, we won't be able to convert it correctly as the structure itself is incorrect and the user might lose the whole options.
b. In JS mode if I have a binding with some code, how do we convert it to a an array when the JS mode is disabled? If we try to use the evaluated value to fill in the boxes of the non-JS mode then if we toggle the JS mode back we lose the initial binding written by the user.

**Comment by dilippitchika** [comment] 2022-06-26 06:47
@somangshu why is this assigned to FE coders? The next steps are on us to move this forward by implementing what ashit suggested.

> Solution 2
> While toggling the JS mode, we updated the options value between array <-> string and update the dynamicBindingPathList accordingly. We would have to de-risk a few things to make sure this solution works.

We can go this way and now that JS mode is disabled when there is a binding in the widget, the conversion is lossless

**Comment by riodeuno** [comment] 2022-06-28 11:49
There are two steps to resolve this problem:
1. We need to now add a function which purges non-existent paths and updates the `dynamicBindingPathList` with the correct paths so that this can be evaluated correctly. This function will run when we toggle from JS to UI and vice-versa on property controls. @appsmithorg/ui-building-pod @somangshu
2. We need to make sure that the options control doesn't allow switching back to UI when it has been modified. This can be tricky @aswathkk 

Finally, the way this control works is prone to errors. The ideal solution here is to change the control so that in UI mode, bindings aren't allowed and they are allowed only in JS mode. This will ensure integrity. The caveat being that when we make this change to the control, we will have to upgrade the widgets which use this control to a newer version.

cc @rohitagarwal88 @somangshu @dilippitchika

**Comment by aswathkk** [comment] 2022-06-28 12:54
> We need to make sure that the options control doesn't allow switching back to UI when it has been modified.

@riodeuno Why do we need to do this?
 Currently what happens is that, if _there are bindings_ or if _the value can't be represented in UI_, we don't allow switching back to UI mode. Wouldn’t this be sufficient?

**Comment by riodeuno** [comment] 2022-06-28 14:04
> if the value can't be represented in UI

@aswathkk Yes, if we're achieving the above correctly, we're fine. We don't need to work on this aspect.

**Comment by ohansFavour** [comment] 2022-11-24 12:20
@dilippitchika This issue is fixed here already https://github.com/appsmithorg/appsmith/pull/14668. Can we close this?

**Closed** 2022-11-24 16:18 UTC
Labels: Bug, Property Pane, High, Production, UI Builders Pod
