### ISSUE TITLE
[Bug]: [Aforce]  Issue with OAuth2 authenticated API authentication error in Appsmith.

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#34923] opened 2024-07-15 06:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[slack link](https://theappsmith.slack.com/archives/C0341RERY4R/p1720666042466659)

The user is not able to connect to their API using Oauth2. It works in Postman but fails in Appsmith. When the query fails the user can see in the logs that there isn't an Authentication header. They can get it to work but need to configure two different requests in Appsmith. They need to do the same in Postman, but got the impression that the datasource was supposed to handle this for them. Screenshots in the slack link.

### Steps To Reproduce

look at the user's application (link in the slack conversation)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by NilanshBansal** [comment] 2024-07-16 06:29
The issue is due to the user's API provider not compliant with RFC specifications. The token request accepts a JSON response but the API returned the "chunked" response falling to `application/octet-stream` not supported issue.

Informed the user about the same, they will contact their provider and continue the next steps. 
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1721051208928829?thread_ts=1720666042.466659&cid=C0341RERY4R

Closing this issue for now, since there are no actionable items at our end.

**Closed by NilanshBansal** 2024-07-16 06:29 UTC
Labels: Bug, Production, Needs Triaging, REST API plugin, Medium, Integrations Pod
