### ISSUE TITLE
[Bug]: Widgets shows data of old page when navigating

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#17134] opened 2022-09-28 07:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we are navigating to a different page and when the widgets names in the old and new page (the page we are navigating to ) are the same, the widget shows data from the old page for a few seconds

Team discussion : https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1664347337043479

### Steps To Reproduce

https://user-images.githubusercontent.com/6636360/192713305-447281e4-ed50-400c-8d7d-f5668076af42.mov

### Version

1.8.2

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5400c)

**Comment by bharath31** [comment] 2022-10-12 06:50
Duplicate of #17097

**Closed by bharath31** 2022-10-12 06:50 UTC
Labels: Bug, JS Evaluation, Needs Triaging, FE Coders Pod
