### ISSUE TITLE
[Bug]: Spaces are not recognized on text display of widgets

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9658] opened 2021-12-08 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spaces are not recognized on any widget that has a text display field. For example, label field or text on the text widget. Any spaces added on property pane is reflected on evaluated value but not on the actual text/label.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/df42fbe28e8949cb9f9a92d843174db5-00001.gif)](https://www.loom.com/share/df42fbe28e8949cb9f9a92d843174db5)

### Steps To Reproduce

1. Try to use tab or spaces on a label field of any widget and observe the evaluated value show the space but not reflect on actual text present on the canvas.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2021-12-08 14:14
@ramsaptami looks like a Duplicate of #9626

**Closed by Nikhil-Nandagopal** 2021-12-08 14:14 UTC
Labels: Bug, UX Improvement, App Viewers Pod, Low, UI Building Pod, Needs Triaging, Widget Property
