### ISSUE TITLE
[Bug]Clicking API or Query shows the properties, which doesn't happen for other entitites

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#957] opened 2020-10-05 14:41 UTC
(https://www.notion.so/Clicking-API-or-Query-shows-the-properties-which-doesn-t-happen-for-other-entitites-7fa6bd46a978443986b20b13b364eca6)

**Comment by Nikhil-Nandagopal** [comment] 2021-01-04 11:21
duplicate of #956

**Closed by Nikhil-Nandagopal** 2021-01-04 11:21 UTC
Labels: Bug, Entity Explorer, Low, Platform, Release
