### ISSUE TITLE
[Bug] Safari -By default Min and Max Date field are highlighted in red with Invalid date message when Datepicker widget is dragged and dropped

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4945] opened 2021-06-07 04:53 UTC
## Description
Release Frozen - Its is observed that by dragging and dropping datepicker widget the min and max field shows invalid and highlighted in red.

**Expected Result:**
Dragging and dropping Date-picker should not throw any error

**Actual Result:**
Dragging and Dropping Date Picker the min and max date field shows invalid and highlighted in red.

### Steps to reproduce the behaviour:
1.Launch Appmsith app in release frozen environment in Safari
2. Drag and Drop DatePicker widget and observe 

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
<img width="1280" alt="Screenshot 2021-06-07 at 9 45 33 AM" src="https://user-images.githubusercontent.com/35128442/120960780-2bd13300-c77a-11eb-953a-037ebca42c1f.png">

- Environment [Release Frozen]

**Comment by somangshu** [comment] 2021-06-07 07:12
@YogeshJayaseelan please test if you can find the bug [here](https://github.com/appsmithorg/appsmith/pull/4372)

**Comment by techbhavin** [comment] 2021-06-08 05:25
@somangshu 

> From reading the current code I can see that version 2 of date picker control expects ISO_DATE_FORMAT. But still, placeholder and default date ( from WidgetConfigResponce.TSX ) give a date in "YYYY-MM-DD HH: mm" format.

This is causing a problem in Safari ( Invalid date ) were as works for Chrome.

![image](https://user-images.githubusercontent.com/58818598/121127277-27268080-c847-11eb-8f0c-c803719a1b1e.png)

>If I enforce ISO_DATE_FORMAT for all controls with version 2 then we have another problem at hand it is 

ISO dates will also consider TimeZones. So UTC max date "2041-12-31 23:59"  changes for IST ( +5:30 GMT ) and 1st date of next year, Out of Range for a max date. This will cause problems for different time zones. It will be better to not use ISO dates for min/max dates and default dates even in version 2.

**Comment by YogeshJayaseelan** [comment] 2021-07-16 06:18
@somangshu  This is still reproducible on Release Frozen in Safari only

**Comment by somangshu** [comment] 2021-07-16 06:29
@YogeshJayaseelan the issue is still open and not yet merged

**Closed** 2021-07-16 07:04 UTC
Labels: Bug, Date Picker Widget, Low, UI Building Pod, Widgets, regression, release-frozen, safari
