### ISSUE TITLE
[Bug]-[6]:Default value on Phone Input type field is not same as Phone Input widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14061] opened 2022-05-24 11:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Expected: The fixes done on Individual widget should have a fix for JSON form field type as well to provide consistency.

Current behavior: The default value of Phone Input type field in JSON form is **John Doe**
refer #13618

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/866865cec6d442f4a3c1061fed0a6b6e-00001.gif)](https://www.loom.com/share/866865cec6d442f4a3c1061fed0a6b6e)

### Steps To Reproduce

1. Add Json form onto canvas
2. Add new field and change it to Phone Input Type
3. Observe the default value shows **John Doe** instead of (000) 000-0000

### Version

Cloud/ Release

**Comment by dilippitchika** [comment] 2022-05-24 11:53
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3 |
| Effort (months)  | 0.25 |

**Comment by tauantcamargo** [comment] 2022-10-07 18:29
can i get it ? @dilippitchika

**Comment by dilippitchika** [comment] 2022-10-10 05:41
Greetings @tauantcamargo thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by utkarshkumarawasthi98** [comment] 2022-12-27 21:08
Hello, can you please assign this issue to me.

**Comment by somangshu** [comment] 2022-12-28 06:40
Greetings @utkarshkumarawasthi98, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and let us know here for a review request

**Comment by iSatVeerSingh** [comment] 2023-04-04 14:20
Can't reproduce it.

**Comment by somangshu** [comment] 2023-04-06 10:26
The issue still exists @iSatVeerSingh, checkout the default value in the property pane
![Screenshot 2023-04-06 at 3 55 52 PM](https://user-images.githubusercontent.com/11089579/230350528-8fcf9a37-9835-4eec-9c4f-0c231a30124f.png)

**Comment by iSatVeerSingh** [comment] 2023-04-06 15:44
Also on `Currency input`, `email input`, and `number input` default value is text.

**Comment by Lovakush** [comment] 2023-04-20 22:04
@chandannkumar I want to contribute on this issue can you assign me ?

**Comment by dilippitchika** [comment] 2023-04-21 04:57
Hey folks just to clarify the change
1. JSON Form widget has a field type called phone input
2. The phone input field has a property called default value
3. The placeholder for the default value property is currently "John Doe"
4. We would like to get this changed to "(000) 000-0000"

**Comment by dilippitchika** [comment] 2023-04-26 07:00
Hey @Lovakush are you interested in working on this issue?

**Comment by Lovakush** [comment] 2023-04-27 04:21
@dilippitchika yes, I am interested

**Comment by dilippitchika** [comment] 2023-04-27 04:22
Thanks @Lovakush  for showing interest 🎉 , This is all yours. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Lovakush** [comment] 2023-04-27 04:27
@dilippitchika Thanks for assigned me this issue sure I will open PR within the next 2 days

**Comment by jaikanthjay46** [comment] 2023-05-26 18:48
@dilippitchika -- I have a pretty good idea of how to fix this. Can it be assigned to me ?

**Comment by dilippitchika** [comment] 2023-05-29 06:11
@jaikanthjay46 sure, assigning this to you

**Comment by jaikanthjay46** [comment] 2023-05-29 13:03
@dilippitchika -- Please review PR #23837

**Comment by dilippitchika** [comment] 2023-05-29 13:23
Thanks @jaikanthjay46, @somangshu fyi can we move this forward?

**Comment by ashit-rath** [comment] 2023-06-01 05:37
@somangshu @dilippitchika There seems to be 2 aspects of this change to align it to the PhoneNumber widget
1. The modification of default value placeholder
2. The formatted text that is shown in the PhoneNumber widget when we enter the following in `default value`
 a. (000) 000-0000
 b. 0000000000

Is the scope of this issue just to fix pt. 1 or both?

**Comment by dilippitchika** [comment] 2023-06-02 05:41
Discussed with ashit the problem is the following
1. Phone input widget can format phone numbers on it's own
2. JSON form's phone input field cannot do the same

So the phone input widget can have any number in default value, either in this format `2025550130` or in this `202-555-0130` and it will format it to `202-555-0130` and show

JSON form only shows the format it receives in default value. 

I have created a new issue to resolve the same - https://github.com/appsmithorg/appsmith/issues/23970
Since it's a bigger change let's pick it later.

**Closed as completed** 2023-06-06 08:03 UTC
Labels: Bug, Good First Issue, Widgets Product, Low, Release, JSON Form, Test Plan Approved, Community Contributor, Widgets & Accelerators Pod
