### ISSUE TITLE
[Bug]: Cannot delete datasource after deleting installed template application

### ISSUE THREAD

**Issue by mtllr** [appsmithorg/appsmith#20843] opened 2023-02-21 13:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After I install the postgreql admin panel template application, I realised that I was not interested in keeping the application. 

I deleted the pgAdmin default page and the related actions for the pgAdmin page disappeared from the list of available actions and the  automatically created Mock Database (1) stayed available.

When I try to delete the Mock Database (1) datasource, I receive an error message saying I have 26 actions using Mock Database (1) so I cannot delete the datasource. 

### Steps To Reproduce

1. add a new page
2. in the choice popup, select "new page from template"
3. choose the postgresql admin panel template and install template
4. refresh browser
5. in the pages drop down of the left side bar, click on the settings button of the pgAdmin page
6. select delete page and confirm deletion
7. notice that all the database queries related to the installation of the postgresql admin template have disappeared from the Queries/JS dropdown
8. click on the settings button of the Mock Database (1) datasource
9. select delete datasource and confirm deletion
10. notice error message

### Version

Cloud / Self-hosted 1.9.7

**Comment by rohan-arthur** [comment] 2023-08-15 06:05
still reproducible as on 15 Aug 2023

**Comment by Nikhil-Nandagopal** [comment] 2024-03-07 09:14
Duplicate of #16866

**Closed by Nikhil-Nandagopal** 2024-03-07 09:14 UTC
Labels: Bug, Backend, Datasources, Low, Production, Community Reported, BE Coders Pod, Integrations Pod
