### ISSUE TITLE
[Bug]: User Application crash with `out of memory error`

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14642] opened 2022-06-17 10:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A discord user is facing out of memory error when opening Appsmith application in edit mode. Everything works fine in view mode.

Video where user is showing RAM consumption and crash issue - https://monosnap.com/file/za6wp0F6fIjrGh7kGO6UOFhQDGzfi9

Discord link - https://discord.com/channels/725602949748752515/985986271073693697/986691121205882982

### Steps To Reproduce

Not yet clear, @Rishabh-Rathod can help with application where this issue is reproducible.

### Version

1.7.2

**Comment by Rishabh-Rathod** [comment] 2022-06-18 15:32
As user application is huge here and has lot of table and JSONForm widgets which increases the propertyPaths.

When we try to `logSuccessfulBindings` for user application initial evaluation has 3549 propertyPaths paths.

We are trying to log these 3549 events to segment after 1st evaluation has completed, this causes `out of memory error`  

<img width="1419" alt="Screenshot 2022-06-18 at 8 41 15 PM" src="https://user-images.githubusercontent.com/23132741/174444902-d5045e5e-4f64-4935-87fa-79da01fead3f.png">

https://user-images.githubusercontent.com/23132741/174445106-f337d466-8239-41c6-af8f-81963aa72ab4.mp4

<img width="468" alt="Screenshot 2022-06-18 at 8 53 12 PM" src="https://user-images.githubusercontent.com/23132741/174445202-987a7216-fe19-45df-bfbd-27e0e5681c25.png">

**Comment by somangshu** [comment] 2022-06-20 08:42
Marking as high since this can be a potential blocker for a user

cc @rohitagarwal88 @riodeuno @SatishGandham

**Closed** 2022-06-24 11:59 UTC
Labels: Bug, Performance, Needs More Info, App Viewers Pod, High, UI Building Pod, UI Builders Pod, FE Coders Pod

**Comment by ramsaptami** [comment] 2022-08-01 05:21
User confirmed this is working on the same discord thread mentioned in the issue description
