### ISSUE TITLE
[Bug]:  The dynamic token in the headers of the Authenticate API is not working after the update.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#24221] opened 2023-06-08 00:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the update, the dynamic tokens in the headers of the authenticated APIs stopped working.

![1](https://github.com/appsmithorg/appsmith/assets/114161539/6cc6db5d-6728-4399-9fb1-5849e612860e)

### Steps To Reproduce

1. Connect to your authentication-required API through the Ahutenticate API.
2. Pass the token in the headers of the Ahutenticate API data source using the following format: `{{appsmith.store.authToken}}`.
3. Save it and execute your query to observe the resulting failure.

### Environment

Production

### Version

Cloud

**Comment by shawn-ward** [comment] 2023-06-18 01:05
I am also experiencing this bug. It seems to only happen when editing. Running the deployed app authenticated apis work as expected.

**Comment by fernando-at-skribble** [comment] 2023-06-20 17:31
> I am also experiencing this bug. It seems to only happen when editing. Running the deployed app authenticated apis work as expected.

This is not my case unfortunately. The API call fails even with the deployed version

**Comment by shawn-ward** [comment] 2023-06-20 21:58
I'm running 1.9.22. Upon some additional testing, if we deploy new versions of the app under 1.9.22 the problem does happen on deployed version of an app. So far, our already deployed apps are working fine on 1.9.22.

**Comment by shawn-ward** [comment] 2023-06-21 18:18
I did some more testing and it seems like if I create the Authorization header that retrieves the value from {{ appsmith.store.* }} and the header is set in the datasource the problem occurs. I cannot reproduce the problem if the header is moved from the datasource to each individual api.

**Comment by fernando-at-skribble** [comment] 2023-06-21 18:59
> I did some more testing and it seems like if I create the Authorization header that retrieves the value from {{ appsmith.store.* }} and the header is set in the datasource the problem occurs. I cannot reproduce the problem if the header is moved from the datasource to each individual api.

I had to temporarily create REST API queries (not authenticated) and hardcode the URL and put the Authorization header in each API call to get it to work.
It works but it is unmaintainable

**Comment by fernando-at-skribble** [comment] 2023-06-21 19:07
I did some debug and seems Appsmith stopped parsing the store variables anymore when it is put in the Authenticated API datasource.
I took a look at the headers of the sent request and it is sending literally `Authorization: Bearer {{appsmith.store.token}}' in the payload.

**Comment by Gabriel-Azevedo** [comment] 2023-10-17 21:28
It's an incredibly frustrating bug.
My team upgraded Appsmith's version and it took us 3 days to realize this was the problem. It's incredibly hard to manually change every single request to have the Authorization there instead of the data source.
Appsmith team: Any time estimate for this bug to be fixed? Do you see this as a bug? Are you looking into offering a better solution for auth token on headers?

**Comment by riteshkew** [comment] 2023-11-14 06:56
First and foremost, thank you for your patience and for bringing this issue to our attention. We understand how frustrating and inconvenient this bug has been for everyone. Your experience and satisfaction are of utmost importance to us.

I want to assure you that our team is actively working on a more robust solution to resolve this issue. While these things can take some time, we are committed to delivering a fix that not only addresses the bug but also enhances the overall user experience.

We will keep you updated on our progress and notify you as soon as the updated solution is available. If you have any further concerns or questions, please don't hesitate to reach out. Your input and support are greatly appreciated.

**Comment by riteshkew** [comment] 2023-12-11 08:10
I'm pleased to inform you that this issue has been resolved. The root cause was an oversight during a recent infrastructure change on our end, and we have taken steps to rectify it.

We understand how frustrating and disruptive such issues can be, and we sincerely apologize for any inconvenience this may have caused. Rest assured, the fix will be included in our next release. Please reach out to us in case of any assistance. Your patience and understanding are greatly appreciated, and we are committed to ensuring a smoother experience moving forward.

**Comment by riteshkew** [comment] 2023-12-11 08:10
Resolved as part of #25537

**Closed by riteshkew** 2023-12-11 08:10 UTC
Labels: Bug, Needs Triaging, Core Query Execution, BE Coders Pod, Data Platform Pod
