### ISSUE TITLE
[Bug]: On clicking on the `unprotect branch` option, all protected branches get unprotected instead of just the current branch.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#34005] opened 2024-06-06 03:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clicking on the `unprotect branch` option, all protected branches get unprotected instead of just the current branch.

### Steps To Reproduce

1. Create a git connected app
2. Create several branches within it (ex: test, test_1, test_2)
3. Protect more than one branch say `test` and `test_1`
4. While being on branch `test`, click on the `unprotect branch` option
5. Notice that both `test` and `test_1` get unprotected

Expected behaviour: Only `test` branch should've been protected

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/0abf8229e45b4b99b3c5da32e5734ff6

### Version

v1.26

**Comment by Nikhil-Nandagopal** [comment] 2024-06-11 07:57
Duplicate of #33310

**Closed by Nikhil-Nandagopal** 2024-06-11 07:57 UTC
Labels: Bug, High, Production, Needs Triaging, Git Version Control, Git Pod, Branch protection
