### ISSUE TITLE
[Bug]Add widget from from Query and then bind to a input widget

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#1378] opened 2020-10-23 17:13 UTC
Steps:
1.Create a query and addwidget.
2.Now make sure you have an input widget, try to bind this with input widget.

Expected:
Based on the binding the data should be seen in input widget.

Actual:
Input widget is not displaying the data based on the binding done.

**Comment by Nikhil-Nandagopal** [comment] 2020-10-27 12:37
Closing this as duplicate of #1366

**Closed by Nikhil-Nandagopal** 2020-10-27 12:37 UTC
Labels: Bug, High
