### ISSUE TITLE
[Bug] Non non-ascii character in column names don't show up correctly in the Table widget

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5445] opened 2021-06-28 09:05 UTC
## Description

A user reported that non-ascii characters such as Från (which means From in Swedish) don't show up correctly in Table column headers.

### Steps to reproduce the behaviour:

1. Create a Google sheet with non-ascii characters data
2. Connect it to a Table widget
3.  You will see word Från shown as Fr_n

<img width="1964" alt="gsheet_error" src="https://user-images.githubusercontent.com/800578/123610149-f4f0b900-d81d-11eb-9ce3-3b5e1519c1c4.png">

### Important Details

- Version: Cloud 
- Browser: Chrome
- Environment: Release

**Comment by ajinkyakulkarni** [comment] 2021-07-09 07:40
The user also [reported](https://discord.com/channels/725602949748752515/760761686549463060/862948702724030495) that if two columns names differ by only one non-ASCII character (eg. Frö and Frä), they both show as {{currentRow.Fr_}} overwriting one of the columns (means making it inaccessible inside the widget).

I feel we should also address this use case when resolving this issue.

**Comment by zzgvh** [comment] 2021-07-10 06:00
Hi, I'm the one that reported this through Discord. I have now also noted that the data from the API gets "mangled" too, when stared in the Table data object, making it hard to use, for instance when doing a post back to the API.

I'm populating a table, `SupplierSeeds`, with the following data:
```
{
  "Leverantör":"De Bolster",
  "Frö":"Basilika - Thai 'Siam Queen'",
  "rowIndex":"0"
},
{
  "Leverantör":"De Bolster",
  "Frö":"Sallad - Oakleaf 'Salad Bowl'",
  "rowIndex":"1"
},
{
  "Leverantör":"De Bolster",
  "Frö":"Sallad - Oakleaf 'Red Salad Bowl'",
  "rowIndex":"2"
},
...
```
fetched using the Google spreadsheets adapter.

When I access `SupplierSeeds.selectedRow` it looks like this:
```
{
  "Leverant_r":"De Bolster",
  "Fr_":"Basilika - Thai 'Siam Queen'",
  "rowIndex":"0",
  "__originalIndex__":0
}
```
So it's not only the header of the table that has issues, but also the stored data. Maybe this is obvious to you when viewing the code for this, but if not, a small heads up!

**Comment by somangshu** [comment] 2021-07-12 10:58
@zzgvh thanks for bringing this up here. Will be of much help!

**Comment by YogeshJayaseelan** [comment] 2021-07-23 10:23
@ajinkyakulkarni Verified this fix and now ascii characters are showing up correctly

<img width="1680" alt="Screenshot 2021-07-23 at 3 52 29 PM" src="https://user-images.githubusercontent.com/35128442/126769378-cf6dcbce-30cc-4c43-b983-855fc321f67a.png">

**Comment by rahulramesha** [comment] 2021-08-10 08:03
@somangshu Re-opening the issue as the [fix](https://github.com/appsmithorg/appsmith/pull/6041) was [reverted](https://github.com/appsmithorg/appsmith/pull/6429), since the special characters were making its way into PropertyPath which was causing cyclic dependency [issue](https://github.com/appsmithorg/appsmith/issues/6375).

**Comment by nickanti** [comment] 2021-12-19 04:29
I guess this is still open?

**Comment by nickanti** [comment] 2021-12-21 12:26
The issue is even worse with Greek chars. Data columns are skipped, underscores are added, widget is basically useless. I guess one method would be to just rename the columns on the data source.

**Comment by Tooluloope** [comment] 2021-12-21 12:29
Hi @nickanti 
This issue would be worked on soon

**Comment by somangshu** [comment] 2021-12-22 09:32
Hey @nickanti, Thanks for reporting the additional context here, We are taking this as part of a bigger effort around table widget #9135, Do check it out and leave any additional feedback in the comments if required, It would be really helpful to have a fresh pair of eyes from the community on the table V2 widget. 😄

**Comment by shadabbuchh** [comment] 2022-05-20 03:59
@sbalaji1192 Reference to a column containing a Non-ASCII character or a space in the beginning throws an error. Please advice should I track it with this issue (and move it into `In Progress`) or create a new one. https://www.loom.com/share/1c446e2163134a16b42134540919e405

**Comment by shadabbuchh** [comment] 2022-05-20 06:38
@sbalaji1192 also noticed that for custom columns, if there is a space in the beginning of the column header then while referencing that column the space vanishes automatically. However this does not happen for regular columns. https://www.loom.com/share/4a1d7794aeee4b0d949fc6ab200ae835

**Comment by sbalaji1192** [comment] 2022-05-20 07:10
@shadabbuchh 
Regarding #1, Expected behaviour, This is not an issue with the Table widget. This is expected behavior with javascript. You're using a character that is not allowed to be part of the identifier. please use square bracket to access the variable that has non-ASCII characters.
Regarding #2, space in column header as in column property name?

**Comment by shadabbuchh** [comment] 2022-05-20 09:03
@sbalaji1192 for `#2` I tried with space in both Property name & in the regular column name.

**Comment by sbalaji1192** [comment] 2022-05-20 11:18
@shadabbuchh #1 is not related to the Table widget. it's a general behavior in the application. We need to improve the autocomplete system to switch to square brackets when the identifier has invalid characters. please create a separate issue if we don't have one.
#2, It's also expected. we trim the space because identifiers cannot have space.

**Comment by shadabbuchh** [comment] 2022-05-24 05:32
This issue has been resolved and is working fine. Tested the below in DP:

1. Non-ASCII characters in column names.
2. Non ASCII characters inside cells.
3. Column names staring with a space or a Non-ASCII character
4. Data in cells starting with Non-ASCII characters and numbers
5. Data in cells starting with a space.

Moving it to `Done`.

**Closed** 2022-07-14 07:02 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, community
