### ISSUE TITLE
[Bug]: Move to Postgres - GCP URI->Unable create roles

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36283] opened 2024-09-12 11:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Move to Postgres - GCP URI->Unable create roles
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/42dc2fed-ca9b-4c9a-8bcf-5545bd1212bc">

### Steps To Reproduce

1. Pull pg locally
2. Add GCP URI
3. Login with a admin user
4. go to admin setting
5. go to roles tab
6. try to create a new role
7. The error message is displayed as in the screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by AnaghHegde** [comment] 2024-09-12 16:31
@RakshaKShetty Unable to reproduce this error - https://www.loom.com/share/60683069954b4561995964dff2a79f35

**Comment by AnaghHegde** [comment] 2024-09-12 17:49
@RakshaKShetty Unable to reproduce this error after multiple retries. Could you share the exact steps reproduce the error if there are any?

**Comment by AnaghHegde** [comment] 2024-09-13 08:40
@RakshaKShetty This due to the padding issue in encryption. Since all the QA members are using the same external db and same database. But all of you are running the docker locally and hence the Salt used for encryption is different that was causing this failure. Hence closing the issue.

**Closed by AnaghHegde** 2024-09-13 08:40 UTC
Labels: Bug, Critical, High, Needs Triaging, Deploy Preview, Move to Postgres, DB Infrastructure Pod
