### ISSUE TITLE
[Bug]: App crashes on adding new datasource/api 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#16940] opened 2022-09-21 06:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding new datasource/api in app is crashing the app, also this is happening for other apps in the same workspace.
<img width="1440" alt="Screenshot 2022-09-21 at 12 15 52 PM" src="https://user-images.githubusercontent.com/80334441/191435508-2ddcd83e-286b-47f8-97b3-785bd53da87d.png">

### Steps To Reproduce

1. Go to this app https://release.app.appsmith.com/app/themeissue/page1-632aab433ab1cc26f7d203c2
2. Create new datasource
3. Observe the app crashes

### Public Sample App

https://release.app.appsmith.com/app/themeissue/page1-632aab433ab1cc26f7d203c2

### Version

Release

**Comment by Parthvi12** [comment] 2022-09-21 07:20
This is not specific to themes, happening on all the apps in that workspace.

**Comment by sumitsum** [comment] 2023-06-16 08:38
Closing it because this issue not reproducible on the shared app anymore.

**Closed by sumitsum** 2023-06-16 08:38 UTC
Labels: Bug, Datasources, Low, BE Coders Pod, Integrations Pod
