### ISSUE TITLE
[BUG] Error: Please enter a valid parameter name

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#816] opened 2020-09-30 11:05 UTC
## Description

When creating a new application, if the user enters just spaces, the error "Please enter a valid parameter name" shows up instead of asking the user to simply enter the name of the application. The same field returns Bad Request: Validation Failure when nothing is submitted. 

### Steps to reproduce the behavior:
Screencast: https://recordit.co/RYHwOMMXl4

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment] 2020-10-01 06:04
Duplicate of #807

**Closed by Nikhil-Nandagopal** 2020-10-01 06:04 UTC
Labels: Bug
