### ISSUE TITLE
[Bug]: Importing app via JSON fails when connecting Datasources

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#16980] opened 2022-09-22 11:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using json option to import apps fails and crashes Appsmith. This happens after connecting to datasource modal is shown

### Steps To Reproduce

1. Import App with datasources via json
2. See crash

### Version

Release

**Comment by hiteshjoshi** [comment] 2022-09-30 07:49
@hetunandu can you post a video or a screenshot or how you reached that state?

**Comment by vuiets** [comment] 2022-10-28 06:59
This looks like it's related to and is a duplicate of https://github.com/appsmithorg/appsmith/issues/17787

**Closed** 2022-10-28 07:19 UTC
Labels: Bug, High, Needs Triaging, Import-Export-App, Team Managers Pod
