### ISSUE TITLE
[Bug]: Select widget not working if same table binding is used for two widget.

### ISSUE THREAD

**Issue by HajaAsmath** [appsmithorg/appsmith#26703] opened 2023-08-28 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select widget not working if same table binding is used for two widget.

### Steps To Reproduce

1. D&D a select widget
2. Choose a table binding for it
3. D&D second select widget and choose the same table binding for it
4. Delete the first select widget 
5. Reload the page and observe the drop down. There will be no data

### Public Sample App

https://release.app.appsmith.com/

### Environment

Release

### Issue video log

https://drive.google.com/file/d/1ZM-Pg9jrWj-RO4iee0Shd34lNPtinCbV/view?usp=sharing

### Version

v1.9.34

**Comment by Nikhil-Nandagopal** [comment] 2024-02-02 05:55
Not able to reproduce this anymore and the video is not available so I'm closing this

**Closed by Nikhil-Nandagopal** 2024-02-02 05:55 UTC
Labels: Bug, Select Widget, App Viewers Pod, High, Release, Community Reported, Needs Triaging
