### ISSUE TITLE
[Feature]: allow setting a custom label on the `Sign in with OIDC SSO` button

### ISSUE THREAD

**Issue by SamWoolerton** [appsmithorg/appsmith#28173] opened 2023-10-17 21:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Apparently this button can't be removed (would also be helpful for my client), but would be great to be able to update this text to e.g. `Sign in with SSO Okta` for a more polished user experience

### Why should this be worked on?

Doesn't sound super hard to implement, and adds more polish for business & enterprise use

**Comment by infinitetrooper** [comment] 2023-10-18 18:12
Duplicate of https://github.com/appsmithorg/appsmith/issues/25660, closing this ticket in favour of the earlier one.

**Closed by infinitetrooper** 2023-10-18 18:12 UTC
Labels: Enhancement, Community Reported, Team Managers Pod, SSO
