### ISSUE TITLE
[Bug]: Cannot change default admin email

### ISSUE THREAD

**Issue by antonxo** [appsmithorg/appsmith#21230] opened 2023-03-07 11:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to change the default appsmith@example.com email to some other email I get an error popup saying: 'Removing own email from Admin Email is not allowed'.
I expected the change to go through.
![image](https://user-images.githubusercontent.com/45237444/223404788-80ed1465-865d-403e-adb1-a29975ff400b.png)

### Steps To Reproduce

1. Go to Admin Settings
2. General tab
3. Try to change Admin Email
4. Click Save & Restart

### Environment

Release

### Version

Self host 1.9.9

**Comment by infinitetrooper** [comment] 2023-03-15 11:53
@trishaanand @sharat87  - Do you know a scenario when this error might occur?

**Comment by Nikhil-Nandagopal** [comment] 2023-03-18 08:58
@antonxo I think you cannot remove your own email if you were the admin that set it up, you can add another email to the admin emails using a comma separated value. Could you please try that?

**Comment by sharat87** [comment] 2023-05-30 11:28
This shows up when a user tries to remove their own email from this list. If you want to remove this email, please add another email (your own, perhaps), signup/login with that, and remove this email from there.

Closing since this is expected behaviour. Please let me know if that didn't work, and we can reopen. Thanks!

**Closed by sharat87** 2023-05-30 11:28 UTC
Labels: Bug, High, Community Reported, Needs Triaging, Super Admin, DevOps Pod
