### ISSUE TITLE
[Bug]: Changing the update mode reset the property of Save/Discard

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#15271] opened 2022-07-18 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/425c58aaacdc4f3ea7339066b466be6b

### Steps To Reproduce

1. Drag and drop a Table widget
2. Click on editable
3. Check that Update mode is Row level
4. Now set some action on Save/Discard
5. Change the Update mode to custom and again change back to Row level
6. Observe that the actions get reset

Note: This is also observed will all the properties of save/discard column

### Version

Cloud

**Comment by sbalaji1192** [comment] 2022-07-18 11:23
This is expected behavior. We're deleting the `Save / Discard` column when the user switches between the update mode. we made the decision to delete the column because keeping the column and hiding it in UI and bindings would not be feasible. And also we assumed that the user won't be switching between the update mode often. Hence closing the issue.

**Closed by sbalaji1192** 2022-07-18 11:23 UTC
Labels: Bug, Table Widget, App Viewers Pod, Release, Needs Triaging, Release Blocker
