### ISSUE TITLE
[Feature]: Allow syncing multiple apps in a single git repo

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11371] opened 2022-02-23 06:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Creating this feature from a user request from intercom. User is trying to merge 2 different applications on the remote and then trying to pull the change.
Allow users to connect multiple apps in single git repo.

### Why should this be worked on?

Allow users to connect multiple apps in single git repo.

**Comment by Nikhil-Nandagopal** [comment] 2022-02-23 06:15
Duplicate of #11120

**Closed by Nikhil-Nandagopal** 2022-02-23 06:15 UTC
Labels: Enhancement, Platform Pod, Git Version Control, Team Managers Pod
