### ISSUE TITLE
[Bug]: Importing app from git/ Existing apps give missing deploy key error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#27692] opened 2023-09-28 10:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we import an app from git and create new branch say 'test', it creates the branch but on opening git modal it throws following error, this happens only for the first branch that we create, although this is not always reproducible.
<img width="1440" alt="Screenshot 2023-09-28 at 3 50 16 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/7ecc33c8-e20f-4596-a52d-395c11c40dda">

### Steps To Reproduce

1. Create an app with queries, jsObject and theme. Coonect it to git
2. Import that app and create new branch say 'test'
3. Switch to that branch and open git modal
4. Observe SSH key error is thrown 

### Environment

Release

### Version

Release

**Comment by rhuanbarreto** [comment] 2023-10-20 14:23
I'm getting the same issue. Shared logs with appsmith support.

**Comment by brayn003** [comment] 2023-12-11 08:43
This issue usually occurs when an Appsmith app is connected to a repo, which is now deleted

**Comment by flavienbert** [comment] 2024-01-03 16:08
I have this issue but the remote repository exists and the key is still there too...

**Comment by brayn003** [comment] 2024-04-23 14:17
Tried triaging, unable to reproduce it

**Comment by nidhi-nair** [comment] 2024-05-09 06:00
Closing as irreproducible. @flavienbert if you continue to face this issue, please provide the following details and we'll follow up on this again.

1. Appsmith deployment information
2. FS used with Appsmith deployment
3. Whether the directory mentioned in the error message is present in your FS
4. Git provider for this repository
5. Appsmith version that you are working with

**Closed by nidhi-nair** 2024-05-09 06:00 UTC
Labels: Bug, High, Production, Needs Triaging, Git Version Control, Git Pod
