### ISSUE TITLE
[Bug][Fixed layout] Context switching doesnt seem to work while switching pages

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22097] opened 2023-04-04 15:20 UTC
https://www.loom.com/share/075cf6e1fd4e4172ab1e81d9eaf16541

**Comment by aswathkk** [comment] 2023-04-05 09:51
@kamakshibhat-appsmith I'm unable to reproduce this issue in latest DP.
Moving it to Needs QA for now.

**Closed** 2023-04-10 04:57 UTC
Labels: Mobile Pod, Responsive Canvas
