### ISSUE TITLE
[Bug] Widget Meta is replicated for widgets with the same name across pages

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1534] opened 2020-11-03 11:42 UTC
## Description
For multipage applications, if an widget with the same name exists, when page is switched, the values of the widgets in the earlier page is shown on the new page

### Steps to reproduce the behaviour:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/14529ca51810407abd0b46f3d9e51f1d-00001.gif)](https://www.loom.com/share/14529ca51810407abd0b46f3d9e51f1d)

**Comment by trishaanand** [comment] 2021-09-29 09:14
@hetunandu : Unable to reproduce this. Can you confirm if you still see this? Thanks!

**Comment by eco-monk** [comment] 2021-11-22 12:20
Closing. Since this is not reproducible.
Although, values evaluate to undefined when switching pages. (#9096)
https://www.loom.com/share/9fe5e306176e41c18b5f048d6a8302f9

**Closed by eco-monk** 2021-11-22 12:20 UTC
Labels: Bug, Frontend, Actions Pod, JS, Low, FE Coders Pod, Project
