### ISSUE TITLE
[Bug]: [currency input widget] Default value validation should throw error for boolean values

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#24930] opened 2023-06-29 13:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currency widget default value validation is coercing boolean values to numbers. We need to throw errors
<img width="643" alt="Screenshot 2023-06-29 at 6 51 55 PM" src="https://github.com/appsmithorg/appsmith/assets/5328605/e6de7f1d-18c1-4b97-a401-e4b35c848e0a">
 in such cases instead of coercion.

### Steps To Reproduce

1. Add a currency widget
2. add `{{false}}` as default value.
3. observe that evaluated value is coming as 0.

### Environment

Production

### Version

cloud

**Comment by tanvircr7** [comment] 2023-06-30 01:42
I have reproduced the issue
![image](https://github.com/appsmithorg/appsmith/assets/34983412/b56bf6a9-8181-4649-b14e-92de63606b9e)
and I can see that it asks for a number yet I am giving a boolean and it is converting it to 0
![image](https://github.com/appsmithorg/appsmith/assets/34983412/65f6e83d-3098-4fc5-a743-b3693aedc77f)
Can I contribute to it?

**Comment by onefastcat** [comment] 2023-07-01 14:59
I was able to reproduce the bug and fix it. This would be my first ever contribution. Can you assign it to me?

**Comment by pheonix-18** [comment] 2023-07-05 22:29
I can take this issue if no one is in line.

**Comment by tanvircr7** [comment] 2023-07-06 16:14
I am opting out on this one, If you want it then please go ahead

**Comment by pheonix-18** [comment] 2023-07-07 13:44
Started working on it

**Comment by pheonix-18** [comment] 2023-07-09 16:00
This bug was fixed. Not able to reproduce. 
<img width="965" alt="Screenshot 2023-07-09 at 11 59 48 AM" src="https://github.com/appsmithorg/appsmith/assets/94332524/4418e9a8-1367-41db-a64b-2b13fd72e765">

**Comment by abhisheksharma886** [comment] 2023-07-13 08:50
Hello, I would like to work on this, can it be assigned to me

**Comment by Anish7575** [comment] 2023-08-07 19:18
Hi, This issue seems to be fixed. I am not able to reproduce this. Why is this still open ? Is there something else that needs to be done ?

**Closed** 2023-09-20 08:46 UTC
Labels: Bug, Good First Issue, App Viewers Pod, Needs Triaging, Widget Validation, Currency Input Widget
