### ISSUE TITLE
[Bug] Autocomplete doesn't work with mouse

### ISSUE THREAD

**Issue by zdb999** [appsmithorg/appsmith#4144] opened 2021-04-26 06:17 UTC
## Description

The autocomplete in the code editor is very helpful. However, it only works with the keyboard, by hitting the down arrow and then pressing enter or tab. If you try to click on one of the options, it exits the popover and does not autocomplete as expected.

### Steps to reproduce the behavior:

1. Open Appsmith project and go to a JS data entry or action field.
2. Start entering in a reference to a query, and wait for the autocomplete box to pop up.
3. Try to click on your preferred option.

### Important Details
 - Version: latest Self-Hosted
 - Browser: Brave (Chromium-based)

**Comment by Nikhil-Nandagopal** [comment] 2021-04-26 06:25
@zdb999 thanks for informing us of this! 
@ApekshaBhosale @mohanarpit can you guys have a look?

**Comment by zdb999** [comment] 2021-04-27 03:40
I'm no longer having this issue today, and I've struggled to reproduce it. I will try to figure out the circumstances where this bug shows up, but right now I'm pretty confused.

**Comment by Nikhil-Nandagopal** [comment] 2021-04-27 07:25
@zdb999 yeah not able to reproduce it myself either! Might be an edge condition somewhere. I'm closing this till we see it again

**Closed by Nikhil-Nandagopal** 2021-04-27 07:25 UTC
Labels: Actions Pod, Autocomplete, Bug, High, JS
