### ISSUE TITLE
[Bug]: The auto commit gets enabled while importing the Auto commit disabled app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33945] opened 2024-06-04 06:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto commit gets enabled while importing the Auto commit disabled app
<img width="1237" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/601c87f7-e5d3-4397-916c-802c63464bac">
<img width="1350" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/3897b65d-5043-4f44-ac1e-f89d9091f2a3">

### Steps To Reproduce

1. Create a auto commit disabled ap from release-ee instance
2. Now go to https://ee-4305.dp.appsmith.com/
3. import the app through git which has diabled auto commit
4.After importing the the app the auto commit is triggered and also when we check in the modal the auto commit button seems to be in enabled state

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

DP

**Comment by SunnyTitus** [comment] 2024-06-20 08:40
Hey @RakshaKShetty, found this mock solution, please advise if this helps:

**Technical Solutions with Code Examples: (ChatGPT)**

**Frontend Code (React):**
_Check Auto Commit State on Import:_

Modify the import logic to check the auto commit state of the application being imported and set the state accordingly.// ImportComponent.jsx

import React, { useEffect, useState } from 'react';import { importApp, getAppSettings } from '../api'; // Assume these API methods exist

const ImportComponent = () => {  const [autoCommitEnabled, setAutoCommitEnabled] = useState(false);

  const handleImport = async () => {    try {      const appSettings = await getAppSettings(importedAppId); // Fetch settings of the imported app      setAutoCommitEnabled(appSettings.autoCommit);

  await importApp(importedAppId); // Import the app
  console.log('App imported successfully');
} catch (error) {
  console.error('Error importing app:', error);
}

  };

  useEffect(() => {    // Ensure UI reflects the correct auto commit state    document.getElementById('autoCommitButton').checked = autoCommitEnabled;  }, [autoCommitEnabled]);

  return (    <div>      <button onClick={handleImport}>Import App</button>      <input type="checkbox" id="autoCommitButton" disabled />    </div>  );};

export default ImportComponent;

Backend Code (Spring Boot):

Preserve Auto Commit State:

Ensure the auto commit setting is correctly transferred during the import process.// AppImportService.java

@Servicepublic class AppImportService {

  @Autowired  private AppSettingsRepository appSettingsRepository; // Assume this repository exists

  public void importApp(String importedAppId) {    AppSettings appSettings = appSettingsRepository.findByAppId(importedAppId);

if (appSettings != null && !appSettings.isAutoCommit()) {
  // Disable auto commit for the imported app
  appSettings.setAutoCommit(false);
  appSettingsRepository.save(appSettings);
}

// Proceed with the import logic...

  }}

API to Fetch App Settings:

Create an API endpoint to fetch the settings of the app being imported.// AppSettingsController.java

@RestController@RequestMapping("/api")public class AppSettingsController {

  @Autowired  private AppSettingsRepository appSettingsRepository; // Assume this repository exists

  @GetMapping("/app-settings/{appId}")  public ResponseEntity<AppSettings> getAppSettings(@PathVariable String appId) {    AppSettings appSettings = appSettingsRepository.findByAppId(appId);    if (appSettings != null) {      return ResponseEntity.ok(appSettings);    } else {      return ResponseEntity.notFound().build();    }  }}

**Comment by btsgh** [comment] 2024-06-21 08:01
@sondermanish  - this is still reproducible. What is decided about this issue?

**Comment by sondermanish** [comment] 2024-06-21 12:58
Although this is undesirable, however this is by design, we are in process of making changes to persist these settings with the app itself that a newly imported app from git works in the same manner as it works in other apps of same repository.

**Comment by btsgh** [comment] 2024-06-21 12:59
Moving this out of auto-commit since the issue exists on prod as well. Keeping it open for git version control

**Comment by infinitetrooper** [comment] 2024-07-22 10:34
@btsgh @manish535  - This is expected, Auto-commit is an app-level setting and not a Git setting, it's not supposed to be propagated across different instances through a repo.

**Closed by infinitetrooper** 2024-07-22 10:34 UTC
Labels: Bug, High, Production, Needs Triaging, Git Version Control, Git Pod
