### ISSUE TITLE
[Bug]: custom number column - cannot reduce column width

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#17042] opened 2022-09-26 05:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a custom column, column type `Number`. It is ridiculously wide at first, but when I try to reduce the width, I cannot see the column header and column values anymore. 
At some widths, I can see the column header but not the values, and at some, I can see neither - this is despite the fact that the chosen width should comfortably accommodate the contents.

### Steps To Reproduce

https://user-images.githubusercontent.com/94514895/192199889-cf916809-7e71-4d39-a1e9-d7d3ece309a0.mov

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-09-26 05:53
Duplicate of https://github.com/appsmithorg/appsmith/issues/15843 , should be fixed in the next release

**Closed by dilippitchika** 2022-09-26 05:53 UTC
Labels: Bug, Table Widget, App Viewers Pod, Needs Triaging
