### ISSUE TITLE
[Bug]: Properties pane is not opening for modal popup intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#9002] opened 2021-11-03 17:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Modal popup properties should come every time when it's selected. In this case, it appears sometimes and inconsistent.

### Steps To Reproduce

1. For a Button widget, select on click action and choose "Open Modal"
2. Modal popup appears but intermittently the properties pane associated with popup doesn't come up.

<img width="904" alt="Screenshot 2021-11-03 at 10 54 07 PM" src="https://user-images.githubusercontent.com/67676905/140157211-963862d6-34ea-4571-9573-986fc3000dd3.png">

### Environment

Release

### Version

Cloud

**Comment by yatinappsmith** [comment] 2021-11-11 06:43
Marking this as high, as it is causing multiple tests to fail intermittently

**Comment by somangshu** [comment] 2021-11-11 10:09
Looks like this issue is not reproducible manually, I found out that there is a slight delay in opening the property pane, Can we check if that fixes the problem, Also can we evaluate if this is really required in the test.

**Comment by NandanAnantharamu** [comment] 2021-11-11 10:37
All the failing tests are related to the Modal popup in different widgets, so when the modal popup comes up the property pane used to come up along with it. So since its a modal popup related test, we can't leave out the test

**Comment by rahulramesha** [comment] 2021-11-11 13:14
This does not seem to be reproducible manually. I ran `Dropdown_onOptionChange_spec.js` and `Button_onClickAction_spec.js` locally, 3 times each and the modal test in both of them is passing consistently. Not sure why this is happening intermittently in CI.

**Comment by NandanAnantharamu** [comment] 2021-11-11 13:47
Correct we havent seen this issue in local only in CI we are facing this issue

**Comment by Nikhil-Nandagopal** [comment] 2021-12-16 09:59
@NandanAnantharamu this should be solved with the docked property pane

**Closed by Nikhil-Nandagopal** 2021-12-16 09:59 UTC
Labels: Needs More Info, Modal Widget, App Viewers Pod, Low, UI Building Pod, Automation
