### ISSUE TITLE
[Bug] App crashed when writing JS in a table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2017] opened 2020-12-03 12:06 UTC
Not able to reproduce it but I have the logs
<img width="1680" alt="Screenshot 2020-12-03 at 5 32 02 PM" src="https://user-images.githubusercontent.com/3897254/101015825-f90d6e80-358d-11eb-8fbd-2b96d5aa6c4a.png">

**Comment by Nikhil-Nandagopal** [comment] 2020-12-10 07:19
@riodeuno @vicky-primathon please look into this

**Comment by vicky-primathon** [comment] 2021-01-14 07:57
Fixed in [PR 2297 ](https://github.com/appsmithorg/appsmith/pull/2297/files)

**Closed** 2021-01-14 08:29 UTC
Labels: Bug, High, QA, Table Widget, UI Building Pod, Widgets

**Comment by prapullac** [comment] 2021-01-15 03:08
Closing the issue as I a, unable to reproduce the same
