### ISSUE TITLE
[Enhancement]: Table doesn't retain the selected value

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10529] opened 2022-01-20 17:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

On updating data for a selected row, when the table re-renders I want to keep the same row selected.

### Why should this be worked on?

A user in our community recognised that the default selected value get's reset everytime on data update.

https://community.appsmith.com/t/master-details-table-update-and-selected-row-reset/514

**Comment by Nikhil-Nandagopal** [comment] 2022-01-24 11:22
@dilippitchika one way to do this is to store the last selectedrow and set it as the default selected row. We undid this experience by default because IIRC it was leading to an unexpected outcome of the next row being shown to a user when a row is deleted

**Comment by somangshu** [comment] 2022-01-24 11:27
@dilippitchika we have a property called primary key for this which will help you retain the selected row, even after update! Of-course if the data is deleted I dont think we have anything selected then. Am I getting the problem statement right?

**Comment by arminus** [comment] 2022-01-26 11:28
@somangshu Actually, the problem is that a secondary table (**whose query depends on the selectedRow.id of the first table**) does not get properly loaded. 

At this time, in my App, it never loads the 2nd table on page load, only when I actually click/select a row in the first table. I guess there's a timing problem somewhere.

(both tables have their PK set to the respective PK in the database)

**Comment by dilippitchika** [comment] 2022-01-27 05:31
Hey @arminus Somangshu is right, we can use the primary key field to help you retain the selected row even after update. Please see the loom video attached below.

https://www.loom.com/share/da9e1b08816a4c83abe469a070b0cd0a

Note, this will only work if the primary key is not being edited. If it is being edited, then the default selected row is reset. This should resolve the query you had. If not, can you please share a screen recording?

**Comment by arminus** [comment] 2022-01-27 08:56
Hey @dilippitchika - all I can say at this time is that unless I store master's table Table1.selectedRowIndex into appsmith.store and use that as Default Selected Row on Table1, the row selection is not retained after a page **reload**.

But (and that is my actual problem): In a small example, the 2nd table, which in its query depends on Table1.selectedRowIndex.id loads ok (after page load). However, in my main app, it doesn't - and this smells like a timing issue, i.e. the query for the 2nd table is run before Table1.selectedRowIndex.id is actually set and thus retrieves nothing.

I can sort of confirm that by having changed the 2nd table's Table Date function from an SQL query to a JS function like so:

```
	get: () => {
		console.log("current order ID: "+Table1.selectedRow.id)
		return SQLgetComments.data // that is the query for the 2nd table
                // SELECT * from comments where order_id = {{Table1.selectedRow.id}} order by date
	}
```

Obviously, it that get function gets called a couple of times with an undefined Table1.selectedRowIndex.id, during the 4th and 5th call, Table1.selectedRowIndex.id is finally set but apparently has no effect on the table at that point, i.e. the table remains empty.

**Comment by arminus** [comment] 2022-01-27 10:17
Ok, so here's the stripped down app which shows the problem, I'm also attaching the exported JSON with xxxxxx'ed out DB host and password for the datasource, but I can share the app if needed - just need an email address for that...

https://user-images.githubusercontent.com/683680/151338549-fc35611a-6253-4486-b5de-41b590b96ba2.mp4

[OrderTracker Test.zip](https://github.com/appsmithorg/appsmith/files/7949523/OrderTracker.Test.zip)

**Comment by dilippitchika** [comment] 2022-01-27 11:03
After viewing the video, i understood that the problem is the **onSelectedRow** action is not being triggered when there is a default selected row value. 

I don't think we can enable this directly as this may break other apps unintentionally. Let me check internally before i can answer.

CC @somangshu

**Comment by somangshu** [comment] 2022-01-28 09:17
You are right @dilippitchika, we do not want to set onRowSelected when it is on the page load with the help of default selected row. We tried going this way, but as you predicted, it breaks old apps and makes it an unexpected change

**Comment by arminus** [comment] 2022-01-28 09:46
Understood, never mind.

**Comment by somangshu** [comment] 2022-01-28 12:24
Should we close this @dilippitchika @arminus ?

**Comment by Nikhil-Nandagopal** [comment] 2022-01-28 12:27
@somangshu the filters and sort should not get reset on query change though right?

**Closed** 2022-04-13 11:04 UTC
Labels: Enhancement, Table Widget, App Viewers Pod, Low, UI Building Pod

**Comment by huylocit14054** [comment] 2024-09-11 04:04
I have the same issue, in my case, I want to select the default value using the query param in the URL. For example appsmith.com?selectedIndex=1. 
I wrote a custom function to get the param value and assign it to the default value field. However, the onSelectedRow action was not called. 

As I read through this issue I understand that it is intentional so my question is:
- Is there any other solution you can suggest? 
- Or is there a way to run a code after the widget loaded with data so I can run code here and `setSelectedRowIndex` which I think will trigger the onSelectedRow?

**Comment by Nikhil-Nandagopal** [comment] 2024-09-12 16:21
@huylocit14054 what you can do is create a JSObject with an async function. Mark it to run on page load. In that function, read the selectedIndex query parameter and based on that, trigger the query you want to run.

**Comment by huylocit14054** [comment] 2024-09-13 02:28
Thank you. I was not aware of that config. I managed to do it just like you said. ❤️
