### ISSUE TITLE
[Bug] Canvas Widgets have rounded borders and shadows

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1563] opened 2020-11-04 12:30 UTC
## Description
Canvas widgets, by design, are not supposed to have styles like rounded borders and shadows.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add a tabs widget
2. The default tabs generated have rounded borders in the Canvas Widgets

### Important Details
 - Version: All
 - OS: Any
 - Browser Any

**Comment by hetunandu** [comment] 2020-11-04 12:40
Duplicate of #990

**Closed** 2020-11-04 13:28 UTC
Labels: Bug, High
