### ISSUE TITLE
[Enhancement] :  "reset form on success" field when switched on also resets if there's an error in the API.

### ISSUE THREAD

**Issue by techbhavin** [appsmithorg/appsmith#15713] opened 2022-08-04 11:58 UTC
There's one issue which we may need to fix when we are taking this up. 

Link to video - https://www.loom.com/share/56cc7ae651e34f8b88db0d730805e0b3

Today our "reset form on success" field when switched on also resets if there's an error in the API which is incorrect, i believe this could be fixed here

_Originally posted by @dilippitchika in https://github.com/appsmithorg/appsmith/issues/3613#issuecomment-1138453150_

**Comment by somangshu** [comment] 2022-08-26 09:42
@dilippitchika is this being worked on?

@techbhavin can you give an update?

**Comment by dilippitchika** [comment] 2022-08-26 09:44
Not that i am aware of @somangshu

**Comment by dilippitchika** [comment] 2022-08-26 09:44
It was supposed to be done after form button migration, hence it was in sprint backlog

**Comment by somangshu** [comment] 2022-08-31 07:52
@dilippitchika thanks, Can you link the issue to it?

**Comment by dilippitchika** [comment] 2022-09-28 07:08
Linked to #3613

**Comment by dilippitchika** [comment] 2023-02-16 05:21
Cannot reproduce, when api fails. Bumping this down and moving to icebox.

**Closed by dilippitchika** 2023-02-16 05:21 UTC
Labels: Enhancement, App Viewers Pod, High, Form Widget
