### ISSUE TITLE
[Feature]: Allow users to access current page name with global `appsmith` object.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#10381] opened 2022-01-13 08:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Expose the name of the current working page with the global `appsmith` object. User should be able to access it as  - `{{ appsmith.currentPageName }}`

### Why should this be worked on?

User request on intercom

**Comment by lublak** [comment] 2022-04-13 07:16
it would be useful to use do navigateTo with the same page to adjust the parameters. Or if a text on the page should contain the page name.
If you then rename or copy the page you don't have to edit it everywhere by hand. Especially for templates this is a good thing.

**Comment by rfenaux** [comment] 2022-06-14 09:19
Dynamically accessing the page Title would be great for navigation and building a dynamic menu with dynamic styling (current active page).
I'm currently using a hidden text field but it's not the most elegant solution

**Comment by vyeruva2** [comment] 2022-07-07 07:16
It would be helpful if we have this feature, currently we need to store value(hard code data), with respect to maintainability its will be very helpful

**Comment by kamal-wareo** [comment] 2023-09-10 08:44
+1

**Comment by justinzyw** [comment] 2024-05-06 08:08
+1

**Comment by sanederchik** [comment] 2024-05-22 10:54
+1

**Comment by Heming9** [comment] 2024-08-30 14:49
+1

**Comment by linkoffate** [comment] 2024-10-13 08:28
+1

**Comment by eedwardsSGS** [comment] 2024-10-16 16:38
Would be useful for code reusability

**Comment by Nikhil-Nandagopal** [comment] 2024-11-19 05:57
Closing this as a duplicate of #10381

**Closed by Nikhil-Nandagopal** 2024-11-19 05:57 UTC
Labels: Enhancement, Javascript Product, Query & JS Pod, New JS Function
