### ISSUE TITLE
[Feature] Supress Appsmith error messages for viewer mode

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3705] opened 2021-03-25 18:18 UTC
1. Today we show error messages for the user in view mode. Some of these error messages aren't necessary for the end-user.
2. Can we allow the developer to suppress error messages for the end viewer and be able to see a timeline of error messages in their console?
3. This will allow the developer to debug but not burden the end-user with messages that don't matter to them and might even be confusing.

These error messages are especially bad for public mode apps, so we should definitely suppress them there.

**Comment by Nikhil-Nandagopal** [comment] 2021-03-26 06:07
@areyabhishek this looks like a duplicate of #2465
@hetunandu when are we picking this up?

**Comment by hetunandu** [comment] 2021-03-26 06:55
@Nikhil-Nandagopal we had decided that we will keep this till the debugger is created since the error will then be shown in the debugger when needed

**Comment by Nikhil-Nandagopal** [comment] 2021-03-26 10:22
@hetunandu debugger will be out next week so you can actually do this

**Comment by Nikhil-Nandagopal** [comment] 2021-05-25 10:04
Closing in favor of #4669

**Closed by Nikhil-Nandagopal** 2021-05-25 10:04 UTC
Labels: Actions, Actions Pod, Enhancement, Needs Design, error, view-mode
