### ISSUE TITLE
[Bug]: Api config throwing cyclic dependency 

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#14068] opened 2022-05-24 15:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Api config throwing cyclic dependency - there are 2 problems:
 
i. Api depends on config & run rather than config & data. 
ii. pluginSpecifiedTemplates is not part of all paths hence it depends on its parent which is config resulting in a cyclic dependency 

The question is why pluginSpecifiedTemplates is missing? what is that case?
```
category_update_api: [
category_update_api.config, 
category_update_api.run
], 
category_update_api.config: [
category_update_api.config.path, 
category_update_api.config, 
category_update_api.config.body
],
```

### Steps To Reproduce

https://www.notion.so/appsmith/Cyclic-Dependency-Errors-830aad407e194d27804a764caa92e05c

https://sentry.io/organizations/appsmith/issues/3187138220/events/7c07fdd944c24dd289e8c8e063ffcbaa/?project=1546547&statsPeriod=14d

### Version

Cloud

**Comment by ChandanBalajiBP** [comment] 2023-02-13 09:13
@Rishabh-Rathod @riteshkew @subrata71 can anyone help me with the steps to reproduce?

**Comment by subrata71** [comment] 2023-02-13 17:46
@ChandanBalajiBP 
The description of the issue is not clear to me. The Sentry link is not valid anymore. Moreover, the issue was reported long ago when there was no such implementation of AST in the backend. 

My assumption is that It may not be valid anymore.

**Comment by Rishabh-Rathod** [comment] 2023-02-14 06:34
@ChandanBalajiBP we don't have clear steps to reproduce here and I am not sure if this would happen for the new API. 

We noticed back then that for an API like `category_update_api` in the config object, a few paths were missing that led to `category_update_api.config` depending on itself and hence cyclic dependency issue was observed

```
category_update_api: [
category_update_api.config, 
category_update_api.run
], 
category_update_api.config: [
category_update_api.config.path, 
category_update_api.config, 
category_update_api.config.body
],
```
 https://www.notion.so/appsmith/Cyclic-Dependency-Errors-830aad407e194d27804a764caa92e05c?pvs=4#a5d07c7a49d945c0befa618858b97df4

@subrata71 Could we please check this sentry issue:- https://appsmith.sentry.io/issues/3839650974/?query=is%3Aunresolved+cyclic+dependency&referrer=issue-stream&statsPeriod=14d

**Comment by ChandanBalajiBP** [comment] 2023-03-20 05:26
I did check a few issues on the Sentry and the following is my observations

1. Most of the errors in the sentry are duplicates. 

| Sentry Link | Occurrence  | Analysis | Time to resolve |
| ------- | --- | --- |
| [Sentry 1](https://appsmith.sentry.io/discover/appsmith:f43a61eb2d3b47e9974333fdce244555/?end=2023-02-10T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-02-10T00%3A00%3A00.000&yAxis=count%28%29) | 2 | This is the exact issue reported here, but we are not able to reproduce this issue locally  | 1 |
| [Sentry 2](https://appsmith.sentry.io/discover/appsmith:74ee81d712dc40e98482e9367f8e8284/?end=2023-02-10T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-02-10T00%3A00%3A00.000&yAxis=count%28%29) | 15 | This is the exact issue reported here, but we are not able to reproduce this issue locally | 1 |
| [Sentry 3](https://appsmith.sentry.io/discover/appsmith:afc4fe4c3437419ba7503920d362f6a7/?end=2023-02-10T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-02-10T00%3A00%3A00.000&yAxis=count%28%29) | 5 | This is a valid case of cyclic dependency caused due to user configurations | 1 |
| [Sentry 4](https://appsmith.sentry.io/discover/appsmith:149a9196710d4dbd9bfe22397b9ae568/?end=2023-02-10T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-02-10T00%3A00%3A00.000&yAxis=count%28%29) | 10 | This is a valid case of cyclic dependency caused due to user configurations | 1 |
| [Sentry 5](https://appsmith.sentry.io/discover/appsmith:d863cd942417479abc3f123e578a0a5d/?end=2023-02-10T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-02-10T00%3A00%3A00.000&yAxis=count%28%29) | 5 | This is the exact issue reported here, but we are not able to reproduce this issue locally | 1 |
| [Sentry 6](https://appsmith.sentry.io/discover/appsmith:8ae51628389641ec89ed1c89ca0fff9c/?end=2023-03-09T23%3A29%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+Cyclic+dependency+found+while+evaluating.&project=1546547&query=issue%3AAPPSMITH-5P0&sort=-timestamp&start=2023-03-09T00%3A00%3A00.000&yAxis=count%28%29) | 1932 | This is a valid case of cyclic dependency caused due to user configurations | 1 |

Summary: 
1. All these errors are resolved with a good tat. And most of the errors entry is duplicate of the same error. (This duplication is because we are logging the same error every time the page refreshes and the user tends to refresh at regular intervals on cyclic dependency.)
2. The valid cyclic dependencies cases were introduced by the user, but there are a few cases which are not the case of cyclic dependency. This needs to handle both in the server and client.

**Comment by Rishabh-Rathod** [comment] 2023-04-17 10:43
We have a sentry issue related to this https://appsmith.sentry.io/issues/3839650974/?project=1546547&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=3 

cc: @riteshkew @rohan-arthur

**Comment by riteshkew** [comment] 2024-04-11 15:28
Closing this as we have not seen any user report this recently and neither on Sentry. Will re-open if we see it reoccurring again.

**Closed by riteshkew** 2024-04-11 15:28 UTC
Labels: Bug, High, Production, Needs Triaging, Core Query Execution, BE Coders Pod, Entity Refactor, Data Platform Pod
