### ISSUE TITLE
[Bug]: Any widget with Events onChange property - shows up blank in the following scenario

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14328] opened 2022-06-06 15:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Drop any widget which has Events onChange property (e.g. Rating widget) and enable JS once, then disable JS. Choose onChange property to show some message of type Info/Warning/Error/Success (Or any other action like copy to clipboard etc), and give details. Now on enabling JS, if we click on the field we see that the evaluated value still shows up blank.

If we go to another page, and come back to this page, it then brings up the evaluated value as undefined. 

### Steps To Reproduce

1. Drop any widget which has Events onChange property (e.g. Rating widget). 
2. Click to enable JS for No Action. It shows up blank, which is the right behaviour. 
3. Now click to disable JS. 
4. Choose onChange property to show some message of type Info/Warning/Error/Success (Or any other action like copy to clipboard etc), and give details. 
5. Now enable JS. Click on the field to see that the evaluated value still shows up blank. 

<img width="766" alt="Rating_EventsJS_Production" src="https://user-images.githubusercontent.com/101863839/172200279-afb31567-131c-40ca-a605-a24a3786e3ca.png">

### Version

Production

**Comment by dilippitchika** [comment] 2022-06-07 06:19
Looks like a property pane issue, @aswathkk can you confirm?

**Comment by Nikhil-Nandagopal** [comment] 2022-06-07 06:30
This is a duplicate of #12736

**Closed by Nikhil-Nandagopal** 2022-06-07 06:30 UTC
Labels: Bug, App Viewers Pod, Low, UI Building Pod, Needs Triaging, All Widgets
