### ISSUE TITLE
[Bug]: When only Staging access is given, it is seen that both Production and Staging are visible in Edit and Deploy mode

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27614] opened 2023-09-26 06:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When only Staging access is given, it is seen that both Production and Staging are visible in Edit and Deploy mode

### Steps To Reproduce

1. Create an application from an instance admin user and create any datasource and configure it on both prod and staging and a few queries on this application. [DP - https://ee-2306.dp.appsmith.com/user/login]
2. Now create a role, giving all required access, and only Staging access for this application [Don't check Production, check only staging]
3. Create a new group, Assign this role to a group and add a user say user1, to the group
4. Check by logging into appsmith with the user1 on say a different browser, and ensure only Staging data is visible for the app in both edit and deploy mode.
5. Now from instance admin login, add another user - user2 - to the above group and save the changes
6. Refresh the page for user1, and now note that though for the role, we have given access to only Staging env, both the environments are visible and can be toggled in the dropdown.

https://github.com/appsmithorg/appsmith/assets/101863839/832edd5e-2fcd-4b30-a480-7b2b32830bb5

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment] 2023-10-24 13:47
@btsgh I am not able to reproduce this issue. Here is my recording of the same process. Can we get on a call and close this? 
https://drive.google.com/file/d/1AUk6MV-R7Ra1uGn5RKPu0RgLqbM1WD2p/view?usp=sharing

**Comment by btsgh** [comment] 2023-10-26 07:38
@ayushpahwa - this is not reproducible on release or Custom env. I had logged the issue on one of the DPs that Chandan was working on. Let me try to get hold of it

**Comment by btsgh** [comment] 2023-10-26 07:45
https://github.com/appsmithorg/appsmith/pull/27043#issuecomment-1717495254

Here is the PR while testing which I found the issue on that particular DP- @ayushpahwa

**Closed** 2023-11-24 08:14 UTC
Labels: Bug, High, Needs Triaging, Deploy Preview, BE Coders Pod, Data Platform Pod, Datasource Environments
