### ISSUE TITLE
[Feature] Support multipart/form-data for uploading files

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2427] opened 2021-01-04 08:53 UTC
## Summary
If we want to upload binary files, we need multipart/form-data support for the Api pane.  

## Motivation
Allow for non alphanumeric file types to be uploaded in parts

## Additional Context
#2425

**Comment by Nikhil-Nandagopal** [comment] 2021-01-04 10:26
@hetunandu this is a duplicate of #1586

**Closed by Nikhil-Nandagopal** 2021-01-04 10:26 UTC
