### ISSUE TITLE
[Bug]: Intermittent Internal Server Error when deploying a workflow

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33168] opened 2024-05-03 12:44 UTC
This appears sometimes but, workflow deploys when we click on deploy again.

**Comment by nsarupr** [comment] 2024-05-22 22:37
Not able to reproduce this issue on my Local. 
Also, the logs related to the previous error aren't present on Mezmo anymore.
[Slack thread](https://theappsmith.slack.com/archives/C05QG0J87UL/p1715840992984679)

**Comment by nsarupr** [comment] 2024-05-22 22:39
For the moment, closing the ticket.
Will re-open it if this issue is resurfaced.

**Closed by nsarupr** 2024-05-22 22:39 UTC
Labels: Bug, Needs Triaging, Medium, Workflows Pod, Workflows
