### ISSUE TITLE
[Bug]: [Deploy Preview]Uncommitted error is displayed even when all the changes are committed in the branch 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13631] opened 2022-05-06 05:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Uncommitted error is displayed even when all the changes are committed in the branch 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/167073245-e9203174-b02d-4b5a-8c73-89f5c43bed65.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/167073275-e6dba259-e2a6-4ad8-b86f-572025788a69.png">

### Steps To Reproduce

1. Connect Application to git 
2. Add a page add some changes commit and push (dont merge)
3. Now Add some changes
4. Do a discard changes
5. Now try to merge the chnages to master 
6. The uncommitted error will be displayed in the merge tab

### Version

deploy preview

**Comment by abhvsn** [comment] 2022-05-16 05:54
@RakshaKShetty can you please try this on release if this is still happening.

**Comment by IAmAnubhavSaini** [comment] 2022-05-24 04:11
@RakshaKShetty is this reproducible?

**Comment by IAmAnubhavSaini** [comment] 2022-05-24 05:17
Not able to reproduce it. Confirmed with @RakshaKShetty. Closing it.

**Closed by IAmAnubhavSaini** 2022-05-24 05:17 UTC
Labels: Bug, High, Needs Triaging, Git Version Control, Deploy Preview, Team Managers Pod, Platform Pod
