### ISSUE TITLE
[Bug]: Select widget's default value field throws error 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15701] opened 2022-08-04 08:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For select widget, the error is displayed in default value field "Default value is missing in options. Please update the value.". Even though the value is provided and correct in the options. 

Note: This is observed in existing apps

<img width="1440" alt="Screenshot 2022-08-04 at 1 08 37 PM" src="https://user-images.githubusercontent.com/80334441/182791337-19cec9be-aaf5-47e7-871d-d443b1e86b07.png">

### Steps To Reproduce

1. Open any existing app which has select widget
2. Observe the error is shown

### Version

Release

**Comment by danciaclara** [comment] 2022-08-08 05:21
A user reached out with this issue as well - https://discord.com/channels/725602949748752515/760761686549463060/1005116722296127488

**Comment by dilippitchika** [comment] 2022-08-08 06:39
@Tooluloope will need you to immediately check this issue, why is this happening as this is a release blocker

**Comment by Tooluloope** [comment] 2022-08-08 07:03
Just checked this, @Parthvi12 can i get a recording on how this happened, couldn't reproduce it on my end
https://user-images.githubusercontent.com/31691737/183358400-5d9df123-060d-4555-a0a7-b5637b7484fc.mov

**Comment by Parthvi12** [comment] 2022-08-08 08:40
@Tooluloope This issue persists on existing apps for me, also when I tried following these steps I could reproduce the issue once and not always

1. Drag and drop a select widget
2. Change the default value to something random
3. Go back to homepage, and open app again
4. Correct the default value and refresh, the error would go away
5. Go back to homepage, and open app again, it will throw error

**Comment by dilippitchika** [comment] 2022-08-08 11:45
Will be fixed in the long term here by the team- https://github.com/appsmithorg/appsmith/issues/15303

**Closed** 2022-08-11 04:32 UTC
Labels: Bug, Select Widget, App Viewers Pod, Critical, High, Production, Old App Issues
