### ISSUE TITLE
[Bug]: Missing data in the menu button source causes page to crash

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#19106] opened 2022-12-21 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- App failed while editing it shows message: something went wrong
- App had template of customer dashboard api and treeselect and menu
- Issue is not reproducible other places

https://release.app.appsmith.com/app/failingapp/page1-63a2eb2b2c7c941b53359bd9/edit
<img width="1440" alt="Screenshot 2022-12-21 at 4 47 21 PM" src="https://user-images.githubusercontent.com/80756091/208896407-e6b105ce-868b-43bc-b6c3-cdc8232249a6.png">

### Steps To Reproduce

Use the app and edit it

### Public Sample App

https://release.app.appsmith.com/app/failingapp/page1-63a2eb2b2c7c941b53359bd9/edit

### Version

cloud

**Comment by pranavkanade** [comment] 2022-12-22 08:43
@AnandiKulkarni, the app is not accessible. Can you please record a loom video and explain the issue & how to reproduce it?

**Comment by AnandiKulkarni** [comment] 2022-12-22 11:16
@pranavkanade app is shared [pranav@appsmith.com] - 
Just click on edit and it shows something went wrong Recording is attached

https://user-images.githubusercontent.com/80756091/209122822-15ed41a4-d688-4235-912f-a19512d18520.mov

**Comment by kamakshibhat-appsmith** [comment] 2022-12-26 08:40
@AnandiKulkarni Can you share the app with me ?

**Comment by kamakshibhat-appsmith** [comment] 2022-12-26 08:41
@AnandiKulkarni Can you share the app with kamakshi@appsmith.com ?

**Comment by kamakshibhat-appsmith** [comment] 2022-12-26 09:03
Issue identified : 
The app is breaking because of the binding in the dynamic Menu items when the values are evaluating to NULL. 
https://www.loom.com/share/508cede6d1c847c09fc60c481d5208a4

@dilippitchika @dhruvikn please check

**Comment by dilippitchika** [comment] 2022-12-26 09:18
Thanks for finding this out, looks like the page goes to a bad state immediately. Refreshing the page shows the menu button but doesn't open the menu anymore, this is desirable behavior which we should implement here.

**Comment by dilippitchika** [comment] 2022-12-26 09:20
@dhruvikn can you check if you can fix this in the current table dynamic menu items issue or we should move it to next sprint?

**Comment by dhruvikn** [comment] 2022-12-27 07:11
Possible to share the app with me as well? @AnandiKulkarni @kamakshibhat-appsmith

**Comment by kamakshibhat-appsmith** [comment] 2022-12-27 07:13
done , Pls check [here](https://release.app.appsmith.com/app/failingapp/page1-63a2eb2b2c7c941b53359bd9/edit)
@dhruvikn

**Comment by somangshu** [comment] 2023-01-17 06:00
@dhruvikn what happened here? Are you waiting on any information, what is the next set of action here?

**Comment by dhruvikn** [comment] 2023-01-17 08:01
I'm not able to reproduce it on the latest release. 
Can you folks also check once? @kamakshibhat-appsmith @AnandiKulkarni

**Comment by kamakshibhat-appsmith** [comment] 2023-01-17 09:03
@dhruvikn I can't reproduce the exact same scenario either, However, on clicking ITEM CONFIGURATION, the app is breaking

**Comment by somangshu** [comment] 2023-01-17 09:13
we need this problem triaged to get to the backlog, we will actually pick it up later, @dhruvikn please take a call on when this can be done, LMK if you need a discussion!

**Comment by dhruvikn** [comment] 2023-01-30 10:37
I have triaged this. This can be resolved with a minor fix. Dev work is small I can raise a PR, but QA and CI will be needed to push the fix. Can we pick it up this week? @kamakshibhat-appsmith @somangshu

**Comment by kamakshibhat-appsmith** [comment] 2023-01-30 15:10
@dhruvikn yes we can pick up

**Comment by dhruvikn** [comment] 2023-01-31 05:46
A fix is [ready here](https://github.com/appsmithorg/appsmith/pull/20243).

Have moved the issue to Needs QA and is parallelly awaiting review from @jsartisan.

cc: @laveena-en @chandannkumar @somangshu @kamakshibhat-appsmith

**Comment by dhruvikn** [comment] 2023-02-01 08:19
Hey folks, any idea who is picking this up for QA?
@laveena-en @ChandanBalajiBP @kamakshibhat-appsmith

**Comment by kamakshibhat-appsmith** [comment] 2023-02-01 10:19
hey @dhruvikn  , @chandannkumar will help us with this tomorrow .

**Comment by kamakshibhat-appsmith** [comment] 2023-02-01 13:52
@riodeuno Point and point 8 are still not fixed

**Closed** 2023-02-02 18:59 UTC
Labels: Bug, App Viewers Pod, High, Menu Button Widget
