### ISSUE TITLE
🛠️[Feature]: User can save filter & column format on  Table widget

### ISSUE THREAD

**Issue by DuaneDuan** [appsmithorg/appsmith#11727] opened 2022-03-09 07:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Table widget can add those feature:
1. User can save filter for switch, also can set default format like this: 
![1646812967(1)](https://user-images.githubusercontent.com/24667276/157398302-f434c21c-cbc9-43f4-868e-f58ea01265f9.png)

2. User can format the grid format and save it for switch,also can set default format like this：
![1646811833(1)](https://user-images.githubusercontent.com/24667276/157395419-528db498-1cf2-4c82-88b3-af33473bc6bb.png)

### Why should this be worked on?

Those features can improve user experience.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-10 06:22
Hi @DuaneDuan Thank you for raising this feature request. This feature is already on our roadmap and you can upvote it here #9577
I'm closing this as a duplicate of that one

**Closed by Nikhil-Nandagopal** 2022-03-10 06:22 UTC
Labels: Enhancement

**Comment by DuaneDuan** [comment] 2022-03-10 07:53
Thanks @Nikhil-Nandagopal  the issue https://github.com/appsmithorg/appsmith/issues/9577 only for filter save,  no requests for save grid format.

**Comment by Nikhil-Nandagopal** [comment] 2022-03-10 08:09
@DuaneDuan can you explain the feature for formatting grid? I would like to understand what you are trying to achieve

**Comment by DuaneDuan** [comment] 2022-03-10 08:36
@Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment] 2022-03-10 09:00
@DuaneDuan Ah I see, I think your requirement is similar to an excel / google sheet like widget that we have tracked here
#1392 please upvote this issue with the requirements

**Comment by DuaneDuan** [comment] 2022-03-10 09:10
@Nikhil-Nandagopal thanks aggain,  awosome feature .
