### ISSUE TITLE
[BUG] Unrelated errors upon deleting an application

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#796] opened 2020-09-29 13:27 UTC
## Description

Invited a second account to access the organization and the apps. Worked pretty well until I deleted one of the the primary user's application. 

### Steps to reproduce the behavior:
1. Invite a user to the organization
2. Delete one application
3. See error

![image](https://user-images.githubusercontent.com/4999463/94564328-7dd5c680-0285-11eb-8f08-5986bf3dcf14.png)

Screencast: https://recordit.co/SCInMI871M

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Brave and Microsoft Edge

**Comment by hetunandu** [comment] 2020-09-30 04:45
@satbir121 Seems like we are trying to update the application name after delete request is complete. Not related to example apps or invite user flow since it is happening to all applications.

**Comment by avats-dev** [comment] 2020-10-03 19:19
@hetunandu I want to work on this. Can you help me out a bit in resolving this? Thanks.

**Comment by satbir121** [comment] 2020-10-05 17:24
@avats-dev Application card has a menu in which you can update an application's properties. We need the application's properties to update on Menu's blur. The problem is that when onBlur is called after the application gets deleted. We need to set a deleting state for an application id and check if the application is deleting. We also need to check if the application exists before it gets deleted.

Deleting state per application needs to be added in `applicationsReducer`.
Use it in `ApplicationCard` menu onBlur.

**Comment by satbir121** [comment] 2020-10-06 07:06
@avats-dev Have you made progress on this? This issue is a little more involved. If you are not able to resolve this, please have a look at [other issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22).

**Comment by avats-dev** [comment] 2020-10-06 23:09
ok @satbir121 :+1:

**Comment by Nikhil-Nandagopal** [comment] 2020-10-08 10:28
@avats-dev apologies but this issue was resolved by someone internally. If you haven't started on this, I recommend you pick up another issue

**Closed by Nikhil-Nandagopal** 2020-10-08 10:28 UTC
Labels: Bug, Frontend, Home Page, Low, above-them
