### ISSUE TITLE
[Bug]: Timer increases in speed each time Start button on this app is clicked

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9244] opened 2021-11-18 14:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App shared by Keyur ([link](https://app.appsmith.com/applications/61924b9443aaaf0225a80095/pages/61924b9443aaaf0225a80097)) has a timer that skips a beat each time the start button is re-clicked.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9b6fb72028f6468080f47dff9c3ac6dd-00001.gif)](https://www.loom.com/share/9b6fb72028f6468080f47dff9c3ac6dd)

### Steps To Reproduce

1. Go to [link](https://app.appsmith.com/applications/61924b9443aaaf0225a80095/pages/61924b9443aaaf0225a80097)
2. Press start once and then observe the timer
3. Press start once more and observe the timer skip a beat and race faster with each consecutive click.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment] 2021-11-19 08:29
@keyurparalkar can you show the code used, Seems like the issue is local

**Comment by keyurparalkar** [comment] 2022-02-07 08:19
Apologies for the late reply!!

The issue is internal to the app's logic. I am maintaining the setInterval's reference value in `appsmtih.store`. Whenever we click on the start button this value is store in the `refId` variable. I forgot to apply a condition that will limit the spawning of setIntervals. I have added this condition now and it is working as expected.

By apply condition like before the setInterval:
```JS
if(refId===undefined || refId===null){
	setInterval(()=>{
```
The setInterval will execute only once.

Since this is resolved therefore closing this issue.

**Closed by keyurparalkar** 2022-02-07 08:19 UTC
Labels: Bug, Actions Pod, JS, Needs Triaging, FE Coders Pod
