### ISSUE TITLE
[Bug] Git Connection issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8653] opened 2021-10-20 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Connecting to Git
- [x]  The deploy key text should say "Paste this deploy key in your repository settings and give it write access. Learn more". This can be slightly more prominent, maybe place it above the deploy key instead of below?-->UI
- [ ] When the user pastes the Wrong URL then paste the right one and click on generate SSH key the button doesn't work
- [x] there is a slight delay in the performance of the activity when the user add new widgets and click on deploy button under deploy tab it takes some time to enable the Commit and push button
- [x]  As the deploy key is displayed at the first instance now when there is an error in the SSh key the error feels like overlapped on the Deploy key section

Others
- [x] #8655

Commit and Push
- [x]  We need to indicate when a branch has unpush commits ( git status API dependency ) [Out of scope as commit and push is an atomic operation]
- [x] The Commit and push functionality is broken when the user deletes the pages and try to commit and push 
@abhvsn 

### Steps To Reproduce

```markdown
New feature
```

### Environment

Deploy Preview

### Version

Cloud

**Comment by Rishabh-Rathod** [comment] 2021-10-20 11:12
> The Commit and push functionality is broken when the user deletes the pages and try to commit and push

@abhvsn  updated the issue here, can you reply here

**Comment by AnaghHegde** [comment] 2021-10-20 12:25
> * [x]  [When there is no write access given when a user added a deploy key add a Related toast error for it @AnaghHegde (when ssh key is added without write access when tried connecting a relevant error should show up) still pending #8655](https://github.com/appsmithorg/appsmith/issues/8655)

This is not possible because the connect CTA requires read only permission.

**Comment by Rishabh-Rathod** [comment] 2021-11-07 20:07
Unable to reproduce this
> When the user pastes the Wrong URL then paste the right one and click on generate SSH key the button doesn't work

**Comment by Rishabh-Rathod** [comment] 2021-11-07 20:09
Closing this issue as mentioned issues are either resolved or aren't valid anymore due to new design changes.

**Closed by Rishabh-Rathod** 2021-11-07 20:09 UTC
Labels: Bug, Needs Triaging, Platform Pod, Git Version Control, Team Managers Pod
