### ISSUE TITLE
[Bug] Fields in the Header and Params section of API pane keeps increasing 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3054] opened 2021-02-16 05:10 UTC
Steps to reproduce:
1) Navigate to API pane 
2) Add an API 
3) Run the API
4) Bind the API to table 
5) Navigate back to API pane and run the API 
and observe

Observation:
It is observed that the Fields in the Header and Params section of API pane keeps increasing 

Expectation:
It is expected to display only default fields to be displayed to user

Video:
https://www.loom.com/share/1707ea5e96c24a4aa5cafef6e0773efa

**Comment by nidhi-nair** [comment] 2021-02-16 05:26
Similar to #3002

**Comment by hetunandu** [comment] 2021-02-18 12:30
Duplicate of #3002

**Closed by hetunandu** 2021-02-18 12:30 UTC
Labels: API pane, Actions Pod, Bug, Low, Needs Triaging, Project
