### ISSUE TITLE
[Bug]: "Unsupported operation" error toast is displayed when user tries to share the workspace 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27632] opened 2023-09-26 11:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"Unsupported operation" error toast is displayed when user tries to share the workspace 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/6965e05c-b7cc-423e-802d-3137d4e9800d">

### Steps To Reproduce

1. login to https://ee-2453.dp.appsmith.com/
2. login with demo@appsmith.com/ demo@appsmith.com
3. now try to click on any share button that is present on the home page 
4. The unsupported operation error is displayed

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by Harshask93** [comment] 2023-09-26 12:25
The observation is also made on trying to share a app from edit page and Deploy page.

**Comment by btsgh** [comment] 2023-09-26 14:55
Another area where the issue is seen - From the Home Page - > Click on the Kebab menu [...], choose Settings, and navigate to Members page - Unsupported Operation and Unexpected error pops up

https://github.com/appsmithorg/appsmith/assets/101863839/1b73b60f-0dac-471a-a221-d62145dda9ed

**Comment by btsgh** [comment] 2023-10-06 04:49
This has been fixed. Tested on downgrade to CE as well as upgrade to Enterprise.

**Comment by dipyamanbiswas07** [comment] 2023-10-06 05:03
Thanks. Closing this.

**Closed by dipyamanbiswas07** 2023-10-06 05:03 UTC
Labels: Bug, High, Needs Triaging, Deploy Preview, Billing & Usage Pod, 1-click upgrade
