### ISSUE TITLE
[Enhancement] From the entity explorer the user must be lead to respective Tab/Widget inside the Tab

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4748] opened 2021-05-27 19:34 UTC
Steps to reproduce:
1) Add a Tabs Widget
2) Add multiple Tab inside the widget
3) add different widget inside the Tab
4) Navigate to Entity explorer
5) Click on Tab/widget inside the tab 
and observe

Observation:
User can identify only the Tabs widget from the entity explorer however when the user clicks on a particular widget inside the Tab the user is not navigated to the respective widget.
Considering if the Tab is open the widget gets highlighted.

Expectation:
Clicking on the Widget name from the entity explorer the user must be navigated to the respective widget inside the tab or at least to the tab to display the widget

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2e665011ecc04fe7aee2362c82c5bca7-00001.gif)](https://www.loom.com/share/2e665011ecc04fe7aee2362c82c5bca7)

**Comment by dilippitchika** [comment] 2022-01-12 10:01
@somangshu can we get this estimated? Looks high effort/low priority when i check this.

**Comment by somangshu** [comment] 2022-01-12 10:22
given that this functionality has an alternate and the end user is not directly effected, we should think about this only later.

@dilippitchika i agree with you

**Comment by hetunandu** [comment] 2023-01-13 10:45
Duplicate of #1282

**Closed by hetunandu** 2023-01-13 10:45 UTC
Labels: Bug, Tab Widget, App Viewers Pod, Low, High effort, New Developers Pod, IDE Navigation
