### ISSUE TITLE
[Bug]: Cant't edit Array type values in JSON Form

### ISSUE THREAD

**Issue by thebadking** [appsmithorg/appsmith#30078] opened 2024-01-06 11:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't edit values on Array type

### Steps To Reproduce

<img width="371" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/7b81bf53-bff5-4220-989d-0d807fec1f92">

### Environment

Production

### Version

Cloud

**Comment by animeshMondal-crypto** [comment] 2024-01-06 15:15
can i work on this issue ??

**Comment by pranavkanade** [comment] 2024-01-08 05:36
@thebadking can you please share a recording of the bug in action or a sample app that shows this issue?

**Comment by thebadking** [comment] 2024-01-08 11:57
[screen-capture.webm](https://github.com/appsmithorg/appsmith/assets/53491595/e1fae672-427d-4ba1-b290-dc27500bbc6c)

**Comment by Nikhil-Nandagopal** [comment] 2024-01-11 08:38
@thebadking we're not able to see the video. Could you attach a list of steps or a public forkable app?

**Comment by thebadking** [comment] 2024-01-11 14:38
the video plays on the github platform on chrome for sure here is a screenshot you see when i hover over the input field i get only a "draggable" hand

<img width="985" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/d7b32f9f-2f8d-4be0-b6eb-e5f149ea002b">

**Comment by thebadking** [comment] 2024-01-11 14:40
The steps are very simple just add an Array type to a form and try to edit the fields

**Comment by Nikhil-Nandagopal** [comment] 2024-01-17 07:46
@thebadking able to see the video now. 
- The values from the postgres response aren't in an array format, they are in a csv format because that's how postgres stores and returns arrays. You need to convert them to an array
I'm not able to reproduce the issue with the adding of a new item in the array. Could you share the default source JSON of the json form that you are using? Just a sample will do or even a public app that can reproduce this issue so we can fork and inspect it

**Comment by thebadking** [comment] 2024-01-19 17:52
![image](https://github.com/appsmithorg/appsmith/assets/53491595/5c38f0a2-3ebf-4013-ac15-68850c8ce7ca)

[Untitled application 1.json](https://github.com/appsmithorg/appsmith/files/13992559/Untitled.application.1.json)

with some more digging I relised the bug happens on the auto generated form fields when you change them to array type, if you create a custom field it works, so it definitely looks like a bug

**Comment by thebadking** [comment] 2024-01-19 17:53
I attached the app.json but it is a new project using the default users data mockup

**Comment by jacquesikot** [comment] 2024-10-11 11:21
@thebadking I have been able to replicate the error from the app json you provided. 

The issue is in the Field configuration property of the gender array column. From the image below, you can see that field configuration has - No fields configured

<img width="307" alt="Screenshot 2024-10-11 at 12 16 26 PM" src="https://github.com/user-attachments/assets/968538d6-6191-4c04-80b6-3a6bd165654b">


On the custom field, it works because there are field configs for the column as seen below
<img width="301" alt="Screenshot 2024-10-11 at 12 16 08 PM" src="https://github.com/user-attachments/assets/b5bcf3e9-2958-4d53-be5a-645793db22c8">

Updating the field configuration from the Gender property pane will solve the problem.

**Comment by jacquesikot** [comment] 2024-12-04 09:58
@thebadking based off my last comment, we will be closing this issue. If you still experience this problem or something similar, please create a new issue.

**Closed by jacquesikot** 2024-12-04 09:58 UTC
Labels: Bug, Needs More Info, Widgets Product, High, Production, Community Reported, JSON Form, Widgets & Accelerators Pod
