### ISSUE TITLE
[Task]: Create a DP for user testing where onboarding flow is visible for all users

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#29540] opened 2023-12-12 08:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The task is to create a DP for user testing where start with data onboarding flow is visible for all users. This DP has been requested by @carinanfonseca so that she can carry out the user testing of this feature seamlessly

**Comment by sneha122** [comment] 2023-12-12 09:51
Moving it to blocked as no active work is required on this issue, it's only open because DP is required for user testing

**Comment by rohan-arthur** [comment] 2024-01-22 07:15
@sneha122 I'll close this because Carina has confirmed that the testing is finished.

**Closed by rohan-arthur** 2024-01-22 07:15 UTC
Labels: Task, Integrations Pod, Integrations Pod General
