### ISSUE TITLE
[Bug]: Date picker gets overlapped on the modal and property pane  in edit mode

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8767] opened 2021-10-25 09:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user adds a modal for action on the date picker it is observed that the  date picker overlaps on the modal and property pane of the modal
![Screenshot 2021-10-25 at 2 54 10 PM](https://user-images.githubusercontent.com/71753653/138672089-9af5666d-182a-4d05-8059-31a19bec8bd6.png)

### Steps To Reproduce

1) Add a date picker 
2) Click on the add a modal 
3) now change the date 
and observe

### Environment

Release

### Version

Self-Hosted

**Comment by somangshu** [comment] 2022-04-14 06:48
Though the property pane is not docked, the popover still overlaps the modal, If this is a real world scenario it will stop the user from completing their workflow. 

The problem is with the zindex, We need a cleanup around this. 

@dilippitchika kindly set impact and priority. Moving to icebox for now

**Comment by dilippitchika** [comment] 2023-03-02 12:23
Duplicate of #18620

**Closed by dilippitchika** 2023-03-02 12:23 UTC
Labels: Bug, Date Picker Widget, App Viewers Pod, Low, Deploy Preview
