### ISSUE TITLE
[Bug]: Unable to generate a crud app from a Google Sheets data source.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#18138] opened 2022-11-09 19:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attempting to generate a crud app from a Google Sheets data source but failing with the following error

![image](https://user-images.githubusercontent.com/114161539/200924027-8cd5ea87-a542-4b11-90be-f5b50be96e28.png)

### Steps To Reproduce

1. Connect a Google Sheets data source to your app

2. try to generate a crud app from your Google Sheets data source and see the error

### Version

Cloud Appsmith v1.8.7-SNAPSHOT

**Comment by sumitsum** [comment] 2022-11-13 04:22
Closing since it is a duplicate of https://github.com/appsmithorg/appsmith/issues/18102

**Closed by sumitsum** 2022-11-13 04:22 UTC
Labels: Bug, Critical, Needs Triaging, Google Sheets, Integrations Pod
