### ISSUE TITLE
[Bug]: App counter must start from 1 even for imported apps

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11219] opened 2022-02-16 17:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When importing an app, app counter does not start from 1 as is the case with duplicating or new app creation but rather picks off from the previous counter. So over time app name is appended with a number that does not correlate to any data present on the current org page. 

More info: Usually duplicated apps show Copy, Copy1, etc; new apps also start from 1, 2, and so on if there aren't other apps with the same name. Fork app follows the same naming convention. Only import functionality behaves differently to this.

![image](https://user-images.githubusercontent.com/79509062/154323875-aa999594-e1d4-4ff5-9393-e09a6cd185cb.png)

### Steps To Reproduce

1. On the org page, duplicate, fork, import and create new orgs and observe the naming convention when this step is repeated a couple of times.
2. Now delete all/most apps and try to repeat the above step and observe the naming convention being different for improted apps

### Environment

Production

### Version

Cloud

**Comment by hiteshjoshi** [comment] 2022-03-19 08:53
I tried replicating this and got another bug. The error message says “Resource not found” on fork and duplicate of app.

**Closed** 2022-06-03 05:07 UTC
Labels: Bug, Home Page, Low, Production, Import-Export-App, Team Managers Pod, Platform Pod
