### ISSUE TITLE
[Bug] Search in filter of tables only works if I'm on the same page as the item being searched

### ISSUE THREAD

**Issue by Rishabhkaul** [appsmithorg/appsmith#4636] opened 2021-05-23 13:28 UTC
While searching through a table, I am only able to filter for data on the page that I am on. So with pagination this becomes an issue. 

### Steps to reproduce the behaviour:
I've used the Applicant Tracker App to show case this issue, but this is a larger issue with Tables (since the same thing has happened on other apps as well).

https://www.loom.com/share/5bfea0ccb3514dfe9864fd59ed60383e

### Important Details
- Version: Cloud
- OS: MacOSX Catalina
- Browser: Chrome
-

**Comment by areyabhishek** [comment] 2021-05-23 13:57
@somangshu does the table search work as intended? Is Rishabh supposed to connect the table search field property to a search query?

**Comment by somangshu** [comment] 2021-05-23 15:11
@areyabhishek we had this issue with the table widget when the client-side search would apply on the server-side search, This was resolved [here](https://github.com/appsmithorg/appsmith/issues/4039) and is in release right now. 

Yes, the table widget search in case of the server-side pagination needs to be connected to a `Query/API` to get correct search results. 
@Rishabhkaul could you provide more info on the reproducible steps.

**Comment by Rishabhkaul** [comment] 2021-05-23 15:34
@somangshu I just forked the template from the Appsmith site (https://www.appsmith.com/templates) and continued using it (with the mock DB). And then I went a searched in the table.

**Comment by somangshu** [comment] 2021-05-24 13:32
@Rishabhkaul @areyabhishek I have replicated this on the [release environment](https://release.app.appsmith.com/applications/60aba4455123fa30d6c393f7/pages/60aba4455123fa30d6c393f9) and it seems to be working fine. However I can see some lag in the table widget in the Edit mode. Ill dig more into that. Let me know if you think the issue is resolved here. 

If it is, then I would say we should update the template on the prod as the search query is not written properly and can lead to this or other errors.

**Comment by Nikhil-Nandagopal** [comment] 2021-05-25 06:21
seems to be working on prod. @Rishabhkaul can you share the link to the app where it's not working and invite us to it?

**Comment by somangshu** [comment] 2021-05-26 05:11
@Rishabhkaul After the release promotion yesterday this is working just fine. However the query written in the template is not correct and will result in wrong data population. Closing this.

**Closed by somangshu** 2021-05-26 05:11 UTC
Labels: Bug, Table Widget, UI Building Pod, Widgets

**Comment by Rishabhkaul** [comment] 2021-05-26 05:22
Ok that makes sense, thanks @somangshu! cc @vihar maybe have a look at the query at some point since its in the template.
