### ISSUE TITLE
[Bug]: Map pin does not center when location is changed and centering option is turned on

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9844] opened 2021-12-17 07:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pinned location should move when location changes on the map when `Map & marker centering` is turned on. Currently, the pin moves as location changes but manual intervention is needed to center or even bring the pin into view since it does not auto-adjust.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/034a71830c514ca4919330cb6d925a8d-00001.gif)](https://www.loom.com/share/034a71830c514ca4919330cb6d925a8d)

### Steps To Reproduce

1. Open up map widget with map & marker centering turned on and bind location using `watchPosition()` on a button trigger as seen in the video
2. Change user location using sensor
3. Observe the pin position move but map view remain the same - this needs to dynamically change as per setting

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment] 2021-12-17 09:20
The functionality is actually to center the pointer on click. We have to think about another way to achieve this

@wmdev0808 @jsartisan any solution in mind?

**Comment by wmdev0808** [comment] 2021-12-17 12:53
@somangshu , 
I've reviewed the issue and gave it a try.
Please assign this issue to me so I can make the commit on my solution

**Comment by ramsaptami** [comment] 2022-06-22 17:21
This isn't working again

**Comment by somangshu** [comment] 2022-06-24 06:13
The only change made here Approx 2 months ago was with #9714 (App theming) and #12962 (map centring issue).

Seems like the change in #12962 could be causing this. @techbhavin kindly verify this and do make sure that you add test case this time to avoid regression.

**Comment by techbhavin** [comment] 2022-07-01 08:10
@ramsaptami  @somangshu  

As per my testing, I am not able to reproduce my issue. I attached the Below video for reference. 
Let me know if I am following the wrong step.

Application Link: https://release.app.appsmith.com/app/common-testing-application/page-62be8b496d836615ef8a90ac

https://user-images.githubusercontent.com/58818598/176852274-83f0c697-d267-4095-a3c0-5bec670730da.mov

**Comment by ramsaptami** [comment] 2022-07-04 08:32
Seems like the issue appears when accessing lat and long values from stored value. Directly accessing it from the geolocation function works as expected

**Comment by techbhavin** [comment] 2022-07-07 11:31
@somangshu  
any update for me on this issue?

**Comment by ramsaptami** [comment] 2022-07-13 09:13
Bind lat and long from Appsmith store values - something like `{{appsmith.store.lat}}` `{{appsmith.store.long}}`
Observe that the value is read as a string and not number
![image](https://user-images.githubusercontent.com/79509062/178697233-56afcc70-2afb-40df-8e86-c5b34c89da5a.png)

**Closed** 2022-07-20 13:16 UTC
Labels: Bug, Map Widget, App Viewers Pod, High, Release, regression, Reopen
