### ISSUE TITLE
[Bug]slash command issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5826] opened 2021-07-13 08:07 UTC
1.When the menu is open, the blue tooltip behind it should not show
2.The headers of the menu should look the same as the headers of the autocomplete
3.New Datasource does not have an icon
4.Pressing enter on new binding does not open the autocomplete but clicking it does
5.As soon as you focus on the field with slash commands, if you click an option it does not work only enter works
6.Bind data in the query does not populate the field as well. This should work exactly like the best match feature
7.Slash menu does not work in the keys of the API pane and the tooltip for the key field is different from the value field in the headers

### Important Details

- Version: [Cloud ]
- OS: mac
- Browser chrome
- Environment [release]

**Comment by arunvjn** [comment] 2021-07-14 06:10
Duplicate of #5825

**Closed by arunvjn** 2021-07-14 06:10 UTC
Labels: Bug, Needs Triaging
