### ISSUE TITLE
[Bug]: No debugger error is shown when JS Function run on page load fails

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#16128] opened 2022-08-18 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unlike Apis, no debugger error is shown when JS Function run on page load fails

### Steps To Reproduce

1. Create a JS Function
2. Set the function to run on page load
3. Set the function to confirm before execution
4. Reload the page and prevent execution of the function by rejecting confirmation
5. No error is shown in the debugger

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 09:38
Duplicate of #6339

**Closed by Nikhil-Nandagopal** 2024-03-06 09:38 UTC
Labels: Bug, Production, Needs Triaging, Medium
