### ISSUE TITLE
[BUG] User is removed from his own organization

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#632] opened 2020-09-20 19:01 UTC
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login with User A and From User A invite User B (give User B administrator access)
2. Login with User B
3. Go to manage user under User A's personal organization
4. Click on 'delete' against User A
5. Log in with User A and User A's personal organization disappeared from User A's account.

Expected Result: No other administrator should be able to remove an administrator from his/her own account.

**Comment by Nikhil-Nandagopal** [comment] 2020-09-21 07:23
@trishaanand seems like an error with ACL

**Comment by trishaanand** [comment] 2020-09-21 07:34
@Nikhil-Nandagopal : This is the designed behaviour. Every administrator of the organization has the right to remove users. There is no special permission given to the creator of an organization. All the administrators have the same permissions.

**Comment by mohanarpit** [comment] 2020-09-23 09:17
Closing this issue as this is expected behaviour and not a bug.

**Closed by mohanarpit** 2020-09-23 09:17 UTC
Labels: ACL, above-them, bug
