### ISSUE TITLE
[Bug]: Impossible to select time on a 'Date' column in the Table component

### ISSUE THREAD

**Issue by marchellodev** [appsmithorg/appsmith#31198] opened 2024-02-19 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever I have a 'Date' column, make it editable, and then I try to edit it - I can only specify the date, but not the time:

<img width="271" alt="image" src="https://github.com/appsmithorg/appsmith/assets/61112084/b49ca2a4-af9c-480e-a07a-c85d90519404">

### Steps To Reproduce

1. Create a table with a 'Date' column
2. Make this column editable
3. Try to edit it - you will not be able to set the time, only the date

### Environment

Production

### Version

Self hosted - 1.13

**Comment by Nikhil-Nandagopal** [comment] 2024-02-28 08:33
@marchellodev thanks for reporting this. This is a duplicate of #19549

**Closed by Nikhil-Nandagopal** 2024-02-28 08:33 UTC
Labels: Bug, Community Reported, Needs Triaging
