### ISSUE TITLE
[Bug]: [List widget] clicking on child widget (button etc) should not trigger `onListItemClick`.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11452] opened 2022-02-25 09:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When there is a button widget inside a list, clicking on the button triggers `onClick` of the button and it also triggers `onListItemClick` of the List Widget

### Steps To Reproduce

here is the sample app (please fork it)- https://app.appsmith.com/applications/62189b47445a8d746a05f768/pages/62189b47445a8d746a05f76b

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-03-07 05:39
Will triage this with list issues, @somangshu can you check if this can be picked up independent of list issues though?

**Comment by st-trade** [comment] 2022-03-17 12:35
Had this issue

**Comment by Nikhil-Nandagopal** [comment] 2022-03-17 13:03
@st-trade sorry, you faced this issue. We'll be solving this soon

**Comment by Tooluloope** [comment] 2022-05-29 17:30
Closing, duplicate of https://github.com/appsmithorg/appsmith/issues/9568

**Comment by Tooluloope** [comment] 2022-05-29 17:30
Closing, duplicate of https://github.com/appsmithorg/appsmith/issues/9568

**Closed by Tooluloope** 2022-05-29 17:30 UTC
Labels: Bug, App Viewers Pod, High, UI Building Pod, community, List Widget, AutomationGap
