### ISSUE TITLE
[Bug]: server isn't verifying page unique names

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#11192] opened 2022-02-16 05:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2022-02-14 at 19 39 04](https://user-images.githubusercontent.com/31691737/154201816-aa47541f-da0e-4479-ba6f-8816d6e86073.png)

### Steps To Reproduce

Open the same application in two tabs, click add page in both the tabs, refresh

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 07:52
Duplicate of #14286

**Closed by Nikhil-Nandagopal** 2024-03-06 07:52 UTC
Labels: Bug, Pages, Production, Needs Triaging, Medium, IDE Pod
