### ISSUE TITLE
[Task]: graphql Action test cases

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12388] opened 2022-03-30 12:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_As an engineer, I should ensure the quality and sanity of the code flows by providing automated test cases on the server side_

@Sumit Kumar placeholder to list the test cases here

1. Test for successfull graphQL query with content type json.
2. Test for successfull graphQL query with content type graphql.
3. Add test for successful graphQL query with query variables.
4. Test for successfull graphQL query with smart substitution in query variables.
5. Test for successfull graphQL query with smart substitution in query body.
6. Test for successfull graphQL query with both get and post type of requests.
7. Add test to catch syntax error in query body. 
8. Add test to catch syntax error in query variables. 
9. (Manual ?) test with Oauth

**Comment by sumitsum** [comment] 2022-09-02 06:50
@prapullac moving it directly to closed state since the issue is about adding JUnit TCs only.

**Closed by sumitsum** 2022-09-02 06:50 UTC
Labels: Backend, Task, BE Coders Pod, GraphQL Plugin
