### ISSUE TITLE
[Bug]: Not able to create new datasource , when user has create datasource permissions

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18591] opened 2022-12-01 04:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When logged in as user with create permission for application and datasource, not able to create new datasource from datasource editor as the save button for it is disabled.
<img width="1434" alt="Screenshot 2022-12-01 at 9 37 38 AM" src="https://user-images.githubusercontent.com/80334441/204964125-9370ade7-6539-460e-9172-671d9dd86b76.png">

### Steps To Reproduce

1. Login as Admin and create new role with Create permission for application and datasource
2. Assign the permission to user1
3. Login as user1 and create new datasource
4. Observe save is disabled.

### Version

http://65.0.99.89/

**Comment by trishaanand** [comment] 2022-12-02 05:56
Duplicate of https://github.com/appsmithorg/appsmith/issues/18600

**Closed by trishaanand** 2022-12-02 05:56 UTC
Labels: Bug, Needs Triaging, Deploy Preview, Team Managers Pod, RBAC
