### ISSUE TITLE
[Bug]: Image (jpg/png) corrupts when uploading with file picker 

### ISSUE THREAD

**Issue by lahiruelectrily** [appsmithorg/appsmith#9212] opened 2021-11-17 11:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we upload a jpg or png file using file picker (size < 10 mb) the file get corrupted. 

The file upload file size is different to actual file.

file picker properties ;
![Screenshot 2021-11-17 at 16 52 11](https://user-images.githubusercontent.com/90342635/142192249-7137c64a-f476-42ac-a89c-9beba3661289.png)

![Screenshot 2021-11-17 at 16 56 07](https://user-images.githubusercontent.com/90342635/142192128-47f0d775-d59f-4ed7-b21f-8130ccf8ff2b.png)

 

### Steps To Reproduce

1. add file picker
2. upload any jpg or png file

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment] 2021-11-17 11:52
@lahiruelectrily are you trying to upload multiple files at the same time? Because if it is a single file then instead of {{Filepicker1.files}} your binding should be {{Filepicker1.files[0]}}

**Comment by mohanarpit** [comment] 2021-11-17 11:54
@Nikhil-Nandagopal We've recently improved the UX here. As a user, I just need to bind `{{ FilePicker1.files }} ` to the API. Appsmith is smart enough to understand if there are multiple files being uploaded or a single file. 

@nidhi-nair Can you please confirm this?

**Comment by lahiruelectrily** [comment] 2021-11-17 12:20
@Nikhil-Nandagopal , yes we need to upload multiple files and the `{{ FilePicker1.files }}` was working several days ago.

**Comment by nidhi-nair** [comment] 2021-11-17 15:58
@mohanarpit that's correct, the array reference supports any number of files for uploads. 

@lahiruelectrily I'm trying to reproduce this issue at my end but unable to do so. Is there any particular file that you can share with me to test this?

**Comment by lahiruelectrily** [comment] 2021-11-18 04:17
@nidhi-nair I used a randomly download image from the internet. Attached the image.
![pexels-free-jpg-639024](https://user-images.githubusercontent.com/90342635/142350765-4ecdc39a-a46a-4bfe-a8fb-d177cedc546e.jpg)

```curl --location --request POST 'https://<API_HOST>/ownerconsentimages' \
--header 'Authorization: Bearer xxxx' \
--form 'ownerConsentId="68"' \
--form 'image=@"/Users/lahiru/Downloads/pexels-free-jpg-639024.jpg"'```

**Comment by nidhi-nair** [comment] 2021-11-18 04:36
@lahiruelectrily I'm guessing that this might be a discrepancy in the expectation in that case. The image that is sent across as a multipart value in the request is actually a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs). In the screenshot below, I've tried sending this image to an [httpbin endpoint](https://httpbin.org/post) to test whether the data URL is getting corrupted. The response does translate to the correct image. I've attached the file that contains the response from this endpoint [here](https://file.io/8Gr6iqme9Nbc).

<img width="1279" alt="Screenshot 2021-11-18 at 10 00 59 AM" src="https://user-images.githubusercontent.com/5298848/142352088-7f3170b0-59fc-45b5-8806-ea6b32d57077.png">


Since you mention that this was working for you earlier, could you share what has changed in the request for you since?

**Comment by lahiruelectrily** [comment] 2021-11-18 06:21
@nidhi-nair below is the response I got after trying same you did
![Screenshot 2021-11-18 at 11 49 13](https://user-images.githubusercontent.com/90342635/142363004-ae5b05a9-a627-49d2-8c8e-ca802b5e463d.png)

**Comment by nidhi-nair** [comment] 2021-11-18 06:27
@lahiruelectrily , could you please confirm if the file format selected on the file picker widget is "Base 64"?

**Comment by lahiruelectrily** [comment] 2021-11-18 12:16
@nidhi-nair, The format was Binary. I change it to base64 and now I can see the res.files as a Data URL. Data URL object is what getting stored the the image. Is this behaviour expected? Do I need to decode file before store?

I tried to show the uploaded Data URL image in an image Widget. But the image widget does not process the Data URL.
![Screenshot 2021-11-18 at 17 36 36](https://user-images.githubusercontent.com/90342635/142413698-e2708845-f5ed-4ece-91f9-a9223be68406.png)

**Comment by nidhi-nair** [comment] 2021-11-18 15:19
@lahiruelectrily Could you please explain your use case to me? I'd need to get an understanding of what your endpoint is doing to be able to recommend the best way to use the filepicker.

For the second part, we'd need to copy the evaluated value over to a validator to check if the data got corrupted while retrieving it. You could use something like [this tool](https://onlinebase64tools.com/validate-base64) for that, or if you're comfortable sharing the data with me, we can connect on Discord (hawk3y3#2925).

**Comment by lahiruelectrily** [comment] 2021-11-18 15:46
Hi @nidhi-nair , My usecase is to store images from one screen and display them on separate screen. When I store a file throughout the middleware (sailsjs skipper) the file is stored as jpeg but when open the jpeg from text editor I can see it is a Data URL. I suspect it is not corrupted. 

When I try to show the same file stored through image widget it doesn't render the image.

**Comment by nidhi-nair** [comment] 2021-11-18 15:48
Got it, that's the retrieval API we'll have to take a look at then. Is the Data URL you receive from the API the same as the one that you see when you open the file in a text editor @lahiruelectrily ?

**Comment by lahiruelectrily** [comment] 2021-11-18 15:55
Yes it is the same.see the last post with image I shared.

**Comment by nidhi-nair** [comment] 2021-11-18 15:58
Could you please try creating an image widget on the same page as the FilePicker, and display the FilePicker data instead? This would be bound as `{{FilePicker1.files[0].data}}`

**Comment by lahiruelectrily** [comment] 2021-11-18 16:22
<img width="772" alt="Screenshot 2021-11-18 at 21 49 24" src="https://user-images.githubusercontent.com/90342635/142454453-555a1893-0373-44dc-a3ab-3b307fc19a3b.png">

```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIWFhUSFBQXGiEcFxgfGRQUHScdHyIjJSUlFhwpLCgkKyEkJST/2wBDAQYGBgkICREJCREkGBQYJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCT/wAARCACpASwDASIAAhEBAxEB/8QAHAABAAIDAQEBAAAAAAAAAAAAAAEGAgUHAwQI/8QAOxAAAQMDAgMEBggFBQAAAAAAAAECAwQFEQaBEiExQVFhcQcTIpGhwRQVIzJDUrHRJEJicvBTkqKy8f/EABsBAQACAwEBAAAAAAAAAAAAAAADBgIEBQcB/8QAMxEAAQQBAQUFBgYDAAAAAAAAAAECAwQRBRIhMUFRBhNxgdEyM2GRocEUIrHh8PEjQkP/2gAMAwEAAhEDEQA/AP1SAAAAAAAAAAAAAAAAAAAPeAAAAAAAAPeAAAAAAAAAAAAAAAAAAAAAAAAAAAABuNwNgAAAAAAAAAAAABuNwABuNwABuNwABuNwABuNwAANwa6XUFugknZJUNRIET1j+xFX+XxXryQyaxzvZTJHJKyNMvVE8TYjcrdPrKOurEipaZUp2r9pUTvRjWN7/wBuZs4NQ2qpqW00NbE+Vy4aiZ5r59CV9aVnFprxahXk9l6dOmfDPHyNiACA3BuAABuAAANwAANwAAAABuNwAAAAAAAAAAAAAAAAABsVXXq1EFLSVlPJJEsUitVzHKiplPDyJoIu9kRmcZNa5Z/DQumxnBagc7tuvbhS4ZVsZVs719l/vTl8C1WzVtqueGtn9RKv4c3srsvRSeehNFvVMp8DTqa1Us7muwvRd37G6AGxpHVAAAAGxqdS3ptktrpm49e/2IkXv7/JDOON0jkY3ipFPMyGNZHruQ0+sNTrS8Vuon4lVPtZG/yJ3J4/oUZXKqYVVwnPBD5XSPc97lc5y5VV6qpjxFurVWwM2W+Z5jqGoSXJVkfw5J0Q2dBb4azh+k3SmpW9jXZVU26fEumntN2mkc2qp6ltbK3pIjkVrV8ET5nOOI9IKqalkSWCV8T06OYqopHZqyStVGvwT0NQhrvRz4kcqc8rn0OzApWn9dcTm011VEzybUImP9yfMujXI5EVqoqLzRUKzYrSQO2XoegUr8Ntm3EvinNCQAQG4AAAAAAAAAAAAAAANwNhsAANhsABuNgAAAANxuAANz5blQRXShmpJvuSNxn8q9i7KfUNj61ytXKcTF7GvarXJlFOOXO3VFprH0tSzhe3ovY5OxU8D5OIvOotT6euMbqWop6qZ7FVGvYxGqxfBVX5FFlWNJHeqVyszyVyYXHiXKpK+RmZGqinlmpVooJVSB6Ob9U8Tb2vVFztKo2GdXxJ+FL7Tdu7YuVp13b67hjq/wCDlXtcuWLv2bnNOIcRhY0+GbeqYXqhLS1u1V3NdlvRd/8AR3BrmvajmuRzVTKKi5RSdzkNo1JcLK5Po0yrFnnC/mxduzY6Jp/VFHfo+Fn2VS1MuhcvPzTvQr9vTZIPzcW9fUuum67BcXY9l/Refgputzlur7z9a3d6MdmCnzHH3L3ruv6IXvVV1+qbLPM1cSvT1cf9y9uyZXY5LxG9o1fOZl8E+5yO1V7CNqtXjvX7evyM+IcRhxDiO/gpeTPiHEYcQ4hgZM+Iueh9SuZKy1Vb8sdygcq/dX8vl3FJ4iWyOY5HNVWuauUVOqKQWazZ41Y43KN59SZJWefxTodwBrdPXRLvaKeqXHrFThk8HJyX99zZFLexWOVruKHq0UrZWJIzgqZAAMSQAAAAAAAAADcDYAAAAAAADcAAbjcAAbjcAAbgbDYA5hrixvttzfVxsX6NUuVyOTo169UX9f8AwrWTt1VSwVsD6eoibLE9MOa5OSlA1FoanoMz0txp4WLzSKqejV8kd2ll0/U2OakUvFPqULW9AkY91ivvau9U6fsVDIyRI1YnqxVaqp2tcip70McncRMlSXduUzyZwVElNMyaGR0cjFy1zVwqKeORkK3O5QjlRcobu/anqL9BSRztRqwNXiVvR7l7cdnL5mnyYZGTCOFsbdliYQlnsSTvWSVcqZ5GTDIyZ4IcmeRkwyMjAyZ5GTDIyMDJc9Cajo7VFUUtdP6lj3o+NVRVTOML06dELk3UtmcmUulJjxlRDjkbVle1jVaiuXGXORqe9eRZLZoSuuOHrV0TI16qyRJF/wCPL4nFvUK6vWWR+zktekaxdSNK8EaPRP51wXtuqbTJUR00FUlRNI7hayFFdnfobY01g0tQ2BqviRZahyYdM/rjuROxDclenSJHYizj4l2qLYVm1ZwjuicvVQACE2gAAAAAAAABuNxsNgBuNxsAANwABuAABuNwABuNwADF6KrHI13C5Uwi4zg4xf4bhTXWeO5vfJUIvN7l++nYqeB2k115sNBfYEirIsq37kjVw9nkvyOjp11Kz1VyZRfmcTXNKdfiRGOw5vDovj9lOLZGS6V/oxnh45Ka4weqaiqqzorOFPFUyU2qhZTTOiZURVCN5cceeFfLKIWuC1FP7tcnnNzT7FT37ceaGORk88jJsYNLJ6ZGTzyMjAyemRk88jIwMnpkZPPIyMDJ6ZGTzyMjAyfRDDNUOVsMT5FTmqMaqr8DY0emr3VvT1FuqW9zntVie9cFw9GVtWG3VFe9uFqH8DM/lb2+9V9xdTgXNYdFI6NjUXHMuOl9mWWIGTyvVM78J9N5T9P6GfSubUXapWoe3m2BrlViL49/l08y4YAOBPYfM7aepcqdKGqzYiTH6qAAQm2AAAAAAABsAAAAAAAAAAAAAAeU9THTcCzO4Gvdwo5eiKvRF7s/52Hqfccz4ioq4AAPh9AA2AKv6RlqU02/6PxcHrW+ux+Tn8M8JyfJ357GSscx7EexyYVrkyip3FB1bpzS1nidUSrUQTPysdPBIntr5Ki4TxLBpF9sbe4Vq5Vd2CmdpdHkmf8Ai2vRERN+Vx8vQ5/kZMVcmVxyQZLRgoJlkZMcjIwDLIyY5GRgGWRkxyMjAMsn0W6imuddDR06ZkmcjU8PHyTqfLk6f6PdMOt1N9Z1bMVM7cRtVOcbP3X9DSvWm1olevHl4nT0nTn3rCRp7Kb1Xon78i12+iittFDRwpiOFiMTx8T6ACiqqquVPXGtRqI1vBAAD4ZAAAAAAAAAAAbADcbkEgAAAAAAAAAHnPBFUwvhmY2SORFa5rkyiopS7hdLvoadrZWuuNoeuInPX7SL+lXfpnr4F4PKppoayB9PURNlikThcxyZRUNmvOka4em01eKenRTSu1XTN2onbL04L9lTmho7bruxXFqJ9MSmkXqyoTgxv0+JvYaiGobxQzRyN72ORU+ByzVmgKm0K+rtzX1FH1Vqc3xefenj7+8qCOVq5RVRfA7bNHr2W95Xk3fP0KrL2kuUn91chRV6ouM/HmfoVXI1Mq5ETvU1ldqazW5FWpuNO1U/la7id7kypw50r3/ee53mpjkkZ2eai/nf8k/shl7ZvVP8cSIvxXP2Q6Je/SjlrorPTqi9PXzJ08m/v7ih1dZUV076iqmfNK9cue9cqp8+Rk7NalDXTEaefMrN7VLN12Z3ZTpy+RnkZMMjJtYOeZ5GTDIyMAzyMmGRkYBnkZMqammrJ2QU8T5ZXrhrGJlVOkaU9HbKJWVt3Rks6c2U/VrF/q71+Hmadu7FWbl67+nM6WnaXPefsxJu5ryT+dD4NDaIdUOjulzixCntQwuT7/c5U7u5O3y69J3IBSrdt9l+2/yToeo6dp0VGLuovNeaqTuNyAap0CdxuQACdxuQACdxuQACdxuQACdxuQACQAAAAAAAAAAAAAACq6i9H1uvKunpv4KqXmrmN9h6+LfmnxLUCaGeSF23GuFNa1UhtM7uZuUOIXnSF4saudUUrpIU/Gi9pm/dvg0uT9E7GluWj7HdVV1Rb42yL+JF7DvPl13LBX7Qcp2+aehT7nY/ftVX+S+qehxDIydMrPRNRvVVo7jPD4SsR/6YNTN6J7q1fsa2jkT+vib8lOozV6j/APfHjk4MvZzUI193nwVFKTkZLcvouvyLydRr5Sr+xnH6Kr25fbqKFif3uVf+pKupVU/6IQJol9d3dKU7IydBpvRJIqotVdGtTtSKLPxVfkbyg9GlhpFR0zJ6tyf6r8J7m4NaTW6rOCqvgnrg3YOy9+T2mo3xX0ycnpqaeslSGmhkmkXoyNquVdkLhZPRjca1Wy3KRKKHrwJ7Ui/JP85HTKOgpLfH6qkpoqdn5Y2I1F9x9ByLOvSv3Qps/VSxUuyMEa7Vh20vTgnr+hrbNp63WGH1dDToxyph0jub3+a/LobIA4T3ueu05cqWuKJkTUZGmETkgABiSAAAAAAAAAAAAAAAAAAEEjmMgAAAAAAAAAADmACATkZAIBORkAgE5GQCATkZAIBORkAAAAEEgAAAAAAAgkAAAAAEEgAAAAAAAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgAgEgA//Z
```

**Comment by nidhi-nair** [comment] 2021-11-19 08:24
Triaged this issue to be caused by #9258, closing this issue in its favour.

**Closed by nidhi-nair** 2021-11-19 08:24 UTC
Labels: Bug, Actions Pod, Critical, Query Execution, BE Coders Pod
