### ISSUE TITLE
[BUG] Delete user doesn't work

### ISSUE THREAD

**Issue by gogetter22** [appsmithorg/appsmith#653] opened 2020-09-21 13:46 UTC
Steps to replicate: Login  --> Go to table tutorial --> edit --> usersTable --> onRowSelected --> Execute a DB query --> Delete query --> select --> Run DELETE FROM users where id = '8';

Result: Getting an error

Browser Details: Firefox 68.12.0esr (64-bit)
Device Details: macOS 
Note: Tried on cloud.

<img width="1789" alt="delete user" src="https://user-images.githubusercontent.com/71608910/93774383-d8947000-fc3e-11ea-8a6f-79fa803f8d1d.png">

**Comment by mohanarpit** [comment] 2020-09-21 14:14
@gogetter22 Thanks for pointing this out. 

This is expected. Since we host the mock database for all users, we don't want them to delete data in the DB as this affects the template applications. If you connect your own PostgreSQL DB, you can execute the delete query successfully.

I'm closing this issue as "Not a bug".

**Closed by mohanarpit** 2020-09-21 14:14 UTC
Labels: bug
