### ISSUE TITLE
[BUG] Distorted view on toggling the state in setting of RadioGroup Widget.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#665] opened 2020-09-22 08:25 UTC
## Description
On toggling of state for Keys (`Required`, `Visible` & `Disabled`), the widget setting box is flashing out and in of the screen.

### Steps to reproduce the behaviour:
1. Add Radio Group Widget.
2. Add onSelectionChange to show static text with `showMessage`.
3. Toggle state for any key `Required`, `Visible` or `Disabled`.
4. The widget would flashes out/in to the screen.

[Video In Action](https://streamable.com/ruqnpa)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by visibleajay** [comment] 2020-09-23 04:39
Same is happening with charts.

**Comment by Nikhil-Nandagopal** [comment] 2020-09-24 07:16
@visibleajay unable to reproduce and the video is not available anymore. Please update the video here. Re-assigning to you for more information

**Comment by visibleajay** [comment] 2020-09-24 08:12
@Nikhil-Nandagopal [Action Video In Drive](https://drive.google.com/file/d/1u5gS6w7B3h18JGxpFV_L-jQwlpqQkHlD/view?usp=sharing). Kindly let me know if anymore info is needed.

**Closed** 2020-11-03 07:09 UTC
Labels: Bug, Cannot Reproduce, Property Pane, Radio Widget, above-them
