### ISSUE TITLE
[Bug]: On creating  a page from a template in a git connected app- no Page link on the left side - though the canvas with the widgets are seen

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17268] opened 2022-10-03 09:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create  a page from a template in a git connected app, there is no Page link on the left side - though the canvas with the widgets are seen

### Steps To Reproduce

1. Connect an app to git. Create your own branch
2. Switch to this child branch
3. Click on the Plus sign next to pages and choose Add Page From Template
4. Choose Bugs and Issue manager from the template list to create template
5. Now we see that the canvas is created with the template, but there is no corresponding Page id linked to this Canvas.
<img width="1114" alt="Screenshot 2022-10-03 at 2 56 13 PM" src="https://user-images.githubusercontent.com/101863839/193548394-9a254003-d4a1-4815-9c17-6fc1e891cf8a.png">

### Version

Release

**Comment by akash-codemonk** [comment] 2022-10-03 09:48
@btsgh Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/17262

**Comment by btsgh** [comment] 2022-10-03 09:53
I don't understand why its duplicate, this seems to be a new issue. The page link is not seen on the left side. The other issue is different in the sense its a page not found error.

**Comment by akash-codemonk** [comment] 2022-10-03 09:56
That issue starts with performing the steps in this issue, but yeah we can keep this and close it when it is fixed.

**Closed** 2022-10-07 11:41 UTC
Labels: Bug, Needs Triaging, Git Version Control, Team Managers Pod, Release Blocker, New Developers Pod, Templates

**Comment by btsgh** [comment] 2022-10-10 05:16
Verified and found to be fixed in Release.
