### ISSUE TITLE
[Bug]Query execution takes more time to render result [ Automation issue]

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#5226] opened 2021-06-17 11:01 UTC
Steps:

1.create a Postgres data source and create a query.
2.later the query data is binding to a table.

Actual:
After query creation, when we execute the query it takes a lot of time to show the result.
Sometimes the result is not displayed.

**Comment by Nikhil-Nandagopal** [comment] 2021-06-18 07:19
@NandanAnantharamu can you give more steps and please add the correct tags for this issue

**Comment by NandanAnantharamu** [comment] 2021-06-21 12:29
Steps:
After creating query we are executing query.
After the execution the query is successful, we have been adding the data to a table widget.
But the table is blank.

The same is observed when we bind Query to table as well.

**Comment by ajinkyakulkarni** [comment] 2021-07-27 18:14
@NandanAnantharamu can you send a Loom video? I am not able to reproduce it.

**Comment by NandanAnantharamu** [comment] 2021-07-28 04:37
@ajinkyakulkarni<img width="1054" alt="Screenshot 2021-07-27 at 2 14 28 PM" src="https://user-images.githubusercontent.com/67676905/127264479-7ecd0585-8089-4efc-8087-5d0a01ee42c3.png">this doesn't happen in the local run, I will be in the loop and see if it's reproducible. Here is the attachment from CI where it's happening for almost all PR.

**Comment by sumitsum** [comment] 2021-07-30 06:36
Closing it post confirmation from @yatinappsmith that this issue has been resolved by the QA team.

**Closed by sumitsum** 2021-07-30 06:36 UTC
Labels: Actions, Actions Pod, Bug, High
