### ISSUE TITLE
[Feature] Slider Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3349] opened 2021-03-03 12:31 UTC
## Summary

Users need a slider widget to select between a min/max range
https://ant.design/components/slider/#header

**Comment by gaa23** [comment] 2022-06-06 22:23
Just wanted to submit my support for this feature, and also worth mentioning that it is not a duplicate of the cascader widget.

**Comment by dilippitchika** [comment] 2022-08-10 07:25
# High level PRD

PR - https://github.com/appsmithorg/appsmith/pull/15712
DP link - [https://appsmith-git-feat-slider-widget-get-appsmith.vercel.app/applications](https://appsmith-git-feat-slider-widget-get-appsmith.vercel.app/applications)

1. Allow users to select the type of slider - either categorical or numerical
    1. Depending on the type selected show the following options
    2. Categorical - 
        1. Options (Similar to radio group)
            1. Allow JS
            2. Values can be strings on numbers
            3. You need at least 2 options
        2. Default value (similar to radio group)
        3. Show marks
            1. Boolean to show marks based on data added
    3. Numerical
        1. Minimum value
            1. Input field
        2. Maximum value
            1. Input type field
        3. Step size
        4. Marks 
            1. Array where the users can provide marks
            2. Validation
                1. Max 20 marks allowed
                2. No other validation for now
2. Other parity properties
    1. Label and label styles group
    2. Visible, Disabled and Animate loading
    3. Required (Design only)
3. Style properties
    1. Fill color - Should automatically inherit theme value
    2. Size - 3 sizes suggested Small, medium and large
4. Other properties
    1. Label always on switch
    2. Show label on hover switch

## Design tasks

1. Design the property pane for a slider widget
2. Suggest the missing states 
    1. Disabled
    2. Size
3. Add all the properties in the properties library - [](https://www.notion.so/853275adc3524c0390f7599b66f74859) 
4. Discuss with Dilip on the re-orgranisation of properties

## Dev tasks

1. Start working on the logic for categorical slider
2. Implement parity properties
3. By then design should be ready

**Comment by dilippitchika** [comment] 2022-08-12 06:13
We need to add
1. isDirty property
2. Support reset widget functionality

**Comment by andrewdietekoki** [comment] 2022-08-23 04:24
Design: https://www.figma.com/file/1aTQ6vksqqAMtgB243PtHm/UI-%7C-Widget-Style-Updates-0.1?node-id=5458%3A86979

Property Pane Design: https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=6723%3A124386

**Comment by somangshu** [comment] 2022-08-31 07:43
What is the progress here @andrewdietekoki @yaldram @dilippitchika ? Are we going to close this widget in the sprint?

**Comment by dilippitchika** [comment] 2022-08-31 10:55
We are going to give it to QA, we are done from our side. Arsalan will now work on testcases and documentation.

**Closed** 2022-09-22 15:56 UTC
Labels: Enhancement, Needs Design, QA, App Viewers Pod, High, New Widget
