### ISSUE TITLE
[Bug]: Discard Changes does not Discard Changes

### ISSUE THREAD

**Issue by andrew-fraction** [appsmithorg/appsmith#23704] opened 2023-05-25 02:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I attempt to discard changes. I go through the discard process. But the commits remain after the process is completed.

### Steps To Reproduce

1. Go to `Commit Changes`
2. Go to `Deploy` tab
3. Click `Discard Changes`
4. Click `Are You Sure`
5. Progress bar will display and go to 100%
6. The process will complete
7. Popup will say `Discarding Changes was Successful`
8. Commits will still remain in the bottom tool bar.

### Environment

Release

### Version

Appsmith Community v1.9.18

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b61fw)

**Comment by driek** [comment] 2023-05-29 04:41
Sorry to "piggy-back" on this issue, but we encounter this similar issue. 
Not sure if it helps troubleshooting, but we suspect this is caused by autogenerated changes after reset. 
Creating a new branch right after discarding changes and creating PR from said new branch to `master` / `main` shows these autogenerated changes. However, since pulling latest from tracking branch is disabled, even merging the auto-generated changes back to the default branch will not resolve this issue unfortunately as we are unable to update the "local" defaul/`master`/`main` branch. 
Currently the only workaround we have is deleting the app and re-importing from GH after merging said autogenerated changes.
Perhaps ideally we should be able to discard the changes, which then pull latest from tracking branch, and from that point do any auto-generation if required.

Please let me know if there is anything I can do to help or more info is required. 
Thank you.

**Comment by pranavkanade** [comment] 2023-06-08 06:04
@andrew-fraction could you please clarify - if the discard changes did not work after appsmith version upgrade? If so, then most likely those are system changes that you have to commit. In such situations, we recommend that you create new temp branch and commit these changes. See if your functionality is intact and if everything looks fine then merge to your dev/master branch.

**Comment by infinitetrooper** [comment] 2023-06-08 11:41
@andrew-fraction @driek  - We're releasing a fix to `Discard and Pull` changes from the remote repository, this will allow you to ignore system changes and pull your latest commits from the remote repository. 

The system changes can be safely committed as well, you can follow @pranavkanade's flow to commit them.

**Comment by AnaghHegde** [comment] 2023-06-09 10:40
https://github.com/appsmithorg/appsmith/pull/23988

**Closed by AnaghHegde** 2023-06-09 10:40 UTC
Labels: Bug, Release, Community Reported, Needs Triaging, Git Version Control, Git Pod
