### ISSUE TITLE
[Bug]: JSON Form: Unable to bind value when changing a field to select with pre-set options

### ISSUE THREAD

**Issue by jacktanxd** [appsmithorg/appsmith#36048] opened 2024-09-02 10:06 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When modifying a field type from input to select in a JSON Form, and setting the options for the select element, the value binding fails to work as expected. The select field displays the correct options, but the value does not bind correctly, resulting in an empty or incorrect value being submitted.

### Steps To Reproduce

	1.	Create a JSON Form with an input field.
	2.	Change the field type to select.
	3.	Define a list of options for the select field.
	4.	Attempt to bind a value to the select field.

Expected Behavior:
The select field should correctly bind the value based on the selected option.

Actual Behavior:
The value is either not bound correctly or is missing from the submitted data.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Appsmith Community v1.37

**Comment by rahulbarwal** [comment] 2024-10-10 09:56
@jacktanxd Can you please clarify this step
> Attempt to bind a value to the select field.

We attempted your steps and tried changing value in select manually, it always evaluated correctly.
If you can also share a video, that would be great.

**Comment by jacquesikot** [comment] 2024-12-06 08:34
@jacktanxd I am also not able to reproduce this issue, so I will be closing it for now. Please create a new issue if you are still experiencing this, preferably with a video attached. Thanks

**Closed by jacquesikot** 2024-12-06 08:34 UTC
Labels: Bug, Needs More Info, Widgets Product, High, Needs Triaging, JSON Form, Widgets & Accelerators Pod
