### ISSUE TITLE
[Bug]: Tab name panel does not spatially accommodate letters like 'g' and 'p' in the name

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#22491] opened 2023-04-17 17:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I name tabs with names like 'Log' or 'Report', the tab name pane does not adjust the height to accommodate the 'g' and 'p' of the words respectively. 
![image](https://user-images.githubusercontent.com/55969597/232566247-a29e90b8-5f06-49d8-bd8d-b4f29182ceac.png)
![image](https://user-images.githubusercontent.com/55969597/232566296-c6ad78ea-e9d2-49c3-934b-419ae82624aa.png)
![image](https://user-images.githubusercontent.com/55969597/232566348-4e23a42e-2501-40c4-8ef7-44fd3ca5f7b5.png)

### Steps To Reproduce

1. Open an app
2. Add the tab widget
3. Rename the tabs to 'Log' and 'Report'

### Environment

Production

### Version

Cloud - v1.9.15

**Comment by somangshu** [comment] 2023-04-18 05:33
Duplicate of #21606. We already have a PR raised by an external contributor. We are reviewing their code!

@Vidushi-Gupta please keep a track of the PR, Test if possible, check to see if your problem is resolved

**Closed by somangshu** 2023-04-18 05:33 UTC
Labels: Bug, Tab Widget, Needs Triaging
