### ISSUE TITLE
[Bug]: Template Phase 2 issues

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15879] opened 2022-08-10 04:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Following are the issues found in DP https://appsmith-git-feature-templates-phase-2-get-appsmith.vercel.app : 

- [ ] #15920
- [x] On selecting filters in template modal, closing it and again opening the modal, shows count of the filters although no filters are selected
<img width="257" alt="Screenshot 2022-08-10 at 9 25 31 AM" src="https://user-images.githubusercontent.com/80334441/183809584-a7074172-2404-45e4-82bc-5776a03b27b7.png">

- [x] On adding new page Page2, the start from template and generate crud card disappears from Page1, ideally until any page level action is performed we should show the cards
- [ ] #15921
- [x] In filters list we use `Widgets` and in templates description page it's `Widgets Used`,we should make them consistent
- [x] Icon size for Create a blank page seems little smaller then the other two
<img width="507" alt="Screenshot 2022-08-10 at 9 33 01 AM" src="https://user-images.githubusercontent.com/80334441/183810602-57fa1440-5296-42c3-818f-61cfb9284298.png">

### Steps To Reproduce

1. Go to https://appsmith-git-feature-templates-phase-2-get-appsmith.vercel.app/
2. Create new app

### Version

https://appsmith-git-feature-templates-phase-2-get-appsmith.vercel.app/

**Comment by Richarex** [comment] 2022-09-26 05:10
1. On selecting filters in template modal, closing it and again opening the modal, shows count of the filters although no filters are selected this is working fine verified it on release.
2. On adding new page Page2, the start from template and generate crud card disappears from Page1, ideally until any page level action is performed we should show the cards this is fixed verified it on release.
3. In filters list we use Widgets and in templates description page it's Widgets Used, we should make them consistent this is also fixed verified it on release.
4. Icon size for Create a blank page seems little smaller then the other two fixed verified it on release.

**Comment by Richarex** [comment] 2022-09-30 10:05
@akash-codemonk 

- [ ] On switching to child branch and forking any template it is throwing error. Please refer to the attached video :- 
https://user-images.githubusercontent.com/93259714/193246764-b70a620c-4587-438e-8621-c921517b5410.mov

**Comment by ginilpg** [comment] 2022-09-30 10:19
> @akash-codemonk can you please look into this issue:
> 
> * [ ]  On switching to child branch and forking any template it is throwing error. Please refer to the attached video :-
>   https://user-images.githubusercontent.com/93259714/193246764-b70a620c-4587-438e-8621-c921517b5410.mov

@Richarex Is this happening with all templates?

**Comment by akash-codemonk** [comment] 2022-09-30 10:55
> @akash-codemonk can you please look into this issue:
> 
> * [ ]  On switching to child branch and forking any template it is throwing error. Please refer to the attached video :-
>   https://user-images.githubusercontent.com/93259714/193246764-b70a620c-4587-438e-8621-c921517b5410.mov


First one seems like an issue with errors template actions of multiple pages which are just piled up. This happens on release as well. The number of toasts depends on the number of failing actions on page load. If you have fewer actions failing in the templates you have fewer errors.
Not considering this as a bug it's more of an issue with the templates themselves. 

> * On switching from child branch to Master the data is not getting displayed and the user sees "Page Not Found" error. Please refer to the SS attached.

The second issue is a bug I can repro on release. Will create an issue for this. 
Not considering as a bug since it isn't related to templates and can be replicated on release.

**Closed** 2022-09-30 13:41 UTC
Labels: Bug, High, Needs Triaging, Deploy Preview, New Developers Pod, Templates

**Comment by Richarex** [comment] 2022-10-14 10:58
@akash-codemonk this issue is still reproducible
- [ ] On switching from child branch to Master the data is not getting displayed and the user sees "Page Not Found" error. Please refer to the attached video:- https://www.loom.com/share/5ab72c0268a04dca8c2293f520de83c9

**Comment by akash-codemonk** [comment] 2022-10-14 11:12
> > * On switching from child branch to Master the data is not getting displayed and the user sees "Page Not Found" error. Please refer to the SS attached.
> 
> The second issue is a bug related to git without templates I can repro on release. Will create an issue for this. Not considering as a bug since it isn't related to templates and can be replicated on release. Created an issue for this at #17234

As mentioned in https://github.com/appsmithorg/appsmith/issues/15879#issuecomment-1263426095 is not an issue with templates. So we will not be taking it up as part of template fixes.
@Richarex
