### ISSUE TITLE
[Bug]: Unexpected enabling of "Run API on Page Load" when api response is mapped to some widget

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12476] opened 2022-03-31 21:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/161149433-027d6720-246b-4239-8f35-c68a556b2e8b.mov

### Steps To Reproduce

1. Create an api - observe 'Run API On Page Load' is not checked in Settings' tab of API
2. Map the api  results to an widget for display
3. Observe : 'Api will be executed automatically on PageLoad' toast
4. **Observe: Now again check the 'Run API On Page Load' of Api settings page - its enabled**
5. **Expected: Api should not be executed onPageLoad unless asked by user**
6. Observe : Because of this setting, the Deploy/View mode of app gives a 'The action 'Api' has failed' every time app is refreshed/loaded which is a bad experience especially when api needs an outside parameter to be passed

### Version

Prod/Release v1.6.17

**Comment by rohan-arthur** [comment] 2022-04-01 02:18
@Aishwarya-U-R this is expected behaviour, added for convenience - when the api data is mapped on the canvas, it is automatically marked to run on page load, because we read the users intent is to show data. 
In your video, the intent appears to be to show data when the button is clicked, and this is not possible to determine programmatically.
If you don't want to run the api on page load, you can also manually turn it off.

**Comment by Aishwarya-U-R** [comment] 2022-04-01 02:25
@rohan-arthur - No, when my api expects a parameter & I as a user to intend to pass it later during one of my interactions with the page - why would I want to see the api failed error in 1st place? 
And what about a POST api - which runs the same way during a OnPageLoad when no data is supplied at start? It's just causing confusion on the validity of my api.

**Comment by Aishwarya-U-R** [comment] 2022-04-01 02:26
And personally I won’t prefer to manually disabled “Run on PageLoad” when I didn’t even enabled it!

**Comment by Rishabh-Rathod** [comment] 2022-04-01 05:36
@rohan-arthur I agree with @Aishwarya-U-R  here, In the case of post API calls in most cases, a user would not want to run API on page load, for example, every form submission, file upload happens when the user clicks on the submit button.

In such cases, enabling "run API on page load" just because they are using a response of that API somewhere else is not an expected experience, and manually disabling "run API on page load" for such cases where we automatically enable it for them is an extra work we add to their plate IMO.

**Comment by Nikhil-Nandagopal** [comment] 2022-04-01 07:19
@Aishwarya-U-R @Rishabh-Rathod we debated this a lot internally as well and all of these concerns were raised but to date we've never had a problem or a question about this from a user. However, when we didn't do this, users would frequently ask us why the API data is not showing in their table and it would be because they forgot to turn it on.

The reason we haven't gone with the approach of excluding post APIs is because GraphQL APIs are all post even to fetch data and in SQL queries, we cannot detect this yet. 
Generally, it doesn't make sense to bind a post API response to a widget since it's nontrivial to merge the response from the POST API to the original fetched data (this is why we get users to re-fetch the data)

So I'm inclined to close this unless we start seeing a lot of issues from a users experience of building an app

**Closed by Nikhil-Nandagopal** 2022-04-01 07:19 UTC
Labels: Bug, API pane, Actions Pod, Needs Triaging, BE Coders Pod

**Comment by Rishabh-Rathod** [comment] 2022-04-01 08:08
@Nikhil-Nandagopal 
It makes sense in most of the cases as you mentioned and I strongly agree with the case GraphQL APIs this way makes more sense.

But for cases mentioned above where users don't want to run API on page Load, What if we give users a "CANCEL" CTA in the toast where we inform them "API1 will now run on page Load"?

**Comment by Nikhil-Nandagopal** [comment] 2022-04-01 12:17
@Rishabh-Rathod that sounds like a clean solve to me. Can you raise a feature request for this?

**Comment by kamal0808** [comment] 2022-07-02 21:50
Is the checkbox "Run on API Load" is of no use then if the data is mapped to some widget? It calls the API even the checkbox says it won't

**Comment by Rishabh-Rathod** [comment] 2022-07-03 07:17
@kamal0808  the checkbox `"Run on Page Load"` does disable/enable running API on page load. ( works as expected )

Above discussion were mainly on user experience. When user types `{{Api.data}}` Appsmith automatically enable the Api to run on page load. But in few cases, user would like to disable it.

For such case, instead of going to Api editor settings to disable, we discussed on a `cancel` CTA when Appsmith automatically enables the Api to run on page load.
