### ISSUE TITLE
[Bug] `\n` inside bindings get an unexpected token error

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5345] opened 2021-06-23 05:56 UTC
## Description
line breaks and other characters need to be escaped or else they give a JS error

### Steps to reproduce the behaviour:
1. Drop two text widgets
2. In the first text widget add the following binding
```{{ Text2.text.split('\n') }}```
3. You see a JS error for this valid JS expression

**Comment by Nikhil-Nandagopal** [comment] 2021-07-16 06:27
Duplicate of #2862

**Closed by Nikhil-Nandagopal** 2021-07-16 06:27 UTC
Labels: Actions Pod, Bug, High, JS, community
