### ISSUE TITLE
[BUG] DB Issue : Create query doesn't work in the 1st attempt, works in 2nd one

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#638] opened 2020-09-21 10:11 UTC
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login 
2. Go to table tutorial --> edit --> usersTable --> onRowSelected --> Execute a DB query --> Create query --> select 
3. Run SELECT * FROM users ; - It succeeds and fetches the correct result
4. Pick any column name now (say name, gender) and run SELECT name FROM users ; OR SELECT gender FROM users ;

Expected result: Query should fetch the correct result everytime it runs.
Actual Result: Query doesn't fetch the result for the 1st time, when it runs for the 2nd time, it works.

Attachment: https://drive.google.com/drive/folders/1qtlCY_HsxmHEN5hCnTUH89KDe0TmDeng?usp=sharing

**Comment by Nikhil-Nandagopal** [comment] 2020-09-24 08:03
@Saket2 not able to reproduce this, are you able to see this consistently?

**Comment by Saket2** [comment] 2020-09-24 08:48
@Nikhil-Nandagopal It was happening 10 out of 10 times that day. Unable to replicate it now.

**Comment by Nikhil-Nandagopal** [comment] 2020-09-30 09:12
Closing this till we're able to reproduce

**Closed by Nikhil-Nandagopal** 2020-09-30 09:12 UTC
Labels: Bug, Needs More Info
