### ISSUE TITLE
Read More link broken in Edit data source page

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#3709] opened 2021-03-26 07:45 UTC
## Description

On clicking "Read More" user should be redirected [here](https://docs.appsmith.com/core-concepts/connecting-to-data-sources) instead of [this](http://docs.appsmith.com/core-concepts/connecting-to-databases)
![appsmith_link_broken](https://user-images.githubusercontent.com/23132741/112598566-c6d19680-8e34-11eb-996b-9e13fd292764.png)

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to Dashboard
2. Click on your DB file
3. Click on **Read more**

**Comment by Rishabh-Rathod** [comment] 2021-03-26 07:57
This is a small change. I believe i can send a PR to fix if that is fine.

**Comment by hetunandu** [comment] 2021-03-26 08:10
Hey @Rishabh-Rathod, we have an issue already open for this: #3666, and there is a PR already opened to fix this. Thanks for your interest in improving this project, though. If you are interested, we have many "low" and "Good first issues" on this project which you can pick up. Just mention me on any issue you are interested in, and I will assign it to you.

**Comment by hetunandu** [comment] 2021-03-26 08:12
Duplicate of #3666 and fixed by #3679

**Closed by hetunandu** 2021-03-26 08:12 UTC
Labels: Bug, Needs Triaging

**Comment by hetunandu** [comment] 2021-03-26 08:14
Ohh I see you already created a PR! You are super fast 😄.
Please make sure you read our [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/c9cee45f51773a6deaea6bf0cc4a6bc4ad1cfe4a/CONTRIBUTING.md) before to avoid any wasted effort

**Comment by Rishabh-Rathod** [comment] 2021-03-26 09:53
> Ohh I see you already created a PR! You are super fast 😄.
> Please make sure you read our [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/c9cee45f51773a6deaea6bf0cc4a6bc4ad1cfe4a/CONTRIBUTING.md) before to avoid any wasted effort

Oh i tried searching this issue couldn't find it. Great that it is already been resolved. 😄 
Will surely invest more going through already open issues.
