### ISSUE TITLE
[Bug] Table column configuration resets when a necessary query param is missing

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3499] opened 2021-03-11 15:19 UTC
If the table data is dependent on a query parameter in the URL, and the parameter is missing when I go to the page in Edit Mode, the tables hidden column and updated column names configurations get reset.

**Comment by naveennazimudeen** [comment] 2021-03-11 15:27
Steps to reproduce:
1. Create two pages Page 1 and Page 2
2. On page 1 add a button widget that on click navigates to Page 2 with a query parameter
3. On page 2 add a table that loads data from DB that uses the query parameter
4. Modify the table columns - hide a column and rename another
5. In Edit Mode, go to click on button on Page 1 - the table on page 2 loads as expected
6. Go back to page 1, now go to Page 2, by clicking on the Page 2 in the left side navigation, the table will be empty as there is no query parameter
7. Now do step 5 again. The Page 2 will load with hidden column shown and renamed column reset

**Comment by naveennazimudeen** [comment] 2021-03-24 21:12
Is there any progress being made on this issue?

**Comment by riodeuno** [comment] 2021-03-25 09:39
Hi @naveennazimudeen Can you confirm if this is still an issue? I tried re-creating this scenario, using the steps you mentioned, but it seems to be working fine for me.

https://user-images.githubusercontent.com/103687/112451920-07210e00-8d7c-11eb-8d1b-c367b35e8beb.mov

**Comment by Nikhil-Nandagopal** [comment] 2021-03-26 08:36
@prapullac can you please verify this issue is working?

**Comment by naveennazimudeen** [comment] 2021-03-26 11:24
@riodeuno @Nikhil-Nandagopal The changes seemed to have fixed the problem. It looked fine when I tested yesterday, but want to run more scenarios, and will have another update in 24 hours to confirm.

**Comment by naveennazimudeen** [comment] 2021-03-27 03:58
It looks fine. I didn't see the issue today. Thanks for fixing it!

**Comment by Nikhil-Nandagopal** [comment] 2021-03-29 05:50
Awesome! I'm closing this issue

**Closed by Nikhil-Nandagopal** 2021-03-29 05:50 UTC
Labels: Bug, High, Table Widget, UI Building Pod, Widgets, community
