### ISSUE TITLE
[Bug]: Audit Logs - Workspace details not available in description tag of user.invited event

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#18848] opened 2022-12-10 11:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Audit Log event `user.invited` the workspace details is not available in the description which is present in the API response. This is only applicable after the new UI is released from EE PR `#811`

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/9128194/206853423-629b36aa-ee44-488a-a5ac-53cc31faf5e7.png">

### Steps To Reproduce

1. Invite a user to any workspace
2. Check the Audit Log entry of that
3. The workspace details will be missing in the subtitle description

### Version

release

**Comment by nsarupr** [comment] 2023-04-28 07:08
Closing this one. 
If the issue is seen again, please reopen the ticket.

**Closed by nsarupr** 2023-04-28 07:08 UTC
Labels: Bug, Needs Triaging, Team Managers Pod, Audit Logs
