### ISSUE TITLE
[BUG] Error 401 on URLs (Forms and API end points)

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#805] opened 2020-09-30 07:14 UTC
## Description

Tried accessing form submission URLs in the browser using GET and the following URLs return a 401 instead of disabling the request and redirecting back to the homepage/login page or a 404 page appropriately. 

**URLs with issues:**

[https://app.appsmith.com/api/v1/users](https://app.appsmith.com/api/v1/users)
[https://app.appsmith.com/api/v1/](https://app.appsmith.com/api/v1/)
[https://app.appsmith.com/api/](https://app.appsmith.com/api/)

Error: [http://prntscr.com/uonvcd](http://prntscr.com/uonvcd)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Brave (Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit))

**Comment by Nikhil-Nandagopal** [comment] 2020-09-30 10:04
@mohanarpit can you verify this

**Comment by pc9795** [comment] 2020-10-13 21:52
According to the current configuration in `SecurityConfig`, this is the expected behaviour. I checked by running locally.

**Comment by mohanarpit** [comment] 2020-10-23 04:18
Closing issue because this is expected behaviour. The API server returns only JSON API responses. Hence returning HTTP responses with appropriate status codes is expected behaviour.

**Closed by mohanarpit** 2020-10-23 04:18 UTC
Labels: Backend, Bug, Low
