### ISSUE TITLE
[Bug]: The irrelevant  linting error is displayed in  the s3 Update button property pane 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9738] opened 2021-12-13 12:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The irrelevant  linting error is displayed in  the s3 Update button property pane 
![image](https://user-images.githubusercontent.com/45958978/145816578-79110e20-8633-4f10-804a-93973e5b286b.png)

### Steps To Reproduce

1. Generate S3 crud page
2. click on the edit icon
3. click on the update button
4. inside the property pane 
5. Under onclick action "the update file and Listfile shows up the lining error "

### Environment

Release

### Version

Cloud

**Comment by eco-monk** [comment] 2022-03-21 07:06
Duplicate of #11943.

**Closed** 2022-07-02 17:53 UTC
Labels: Bug, High, Verified, Release, JS Linting & Errors, FE Coders Pod
