### ISSUE TITLE
[Bug] Widget gets placed at the bottom of the page when copied or created from the query page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1286] opened 2020-10-19 12:51 UTC
Steps to Reproduce:
Scenario 1:
1) Add widget
2) Copy the widget 
3) Paste the widget 
and observe

Scenario2:
1) Create a query
2) Click on Add widget 
3) User is navigated to Edit mode 
and observe 

Observation :
It is observed that the widget gets placed completely at the bottom of the page which makes to difficult to navigate the position of the widgets and also not user friendly.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/02cfa33a37de444d95bd5dd946ebc2ac-00001.gif)](https://www.loom.com/share/02cfa33a37de444d95bd5dd946ebc2ac)

**Comment by sumitsum** [comment] 2021-02-19 14:09
This issue also came up during smart look session on 19 Feb 2021

**Comment by rohitagarwal88** [comment] 2022-05-31 04:38
The issue is related to old UI, irrelevant now.
Closing after discussion with @vuiets.

**Closed by rohitagarwal88** 2022-05-31 04:38 UTC
Labels: Bug, Release, UI Building Pod, regression, UI Builders Pod, Copy Paste
