### ISSUE TITLE
[Bug]: Git Sync generates invalid SSH Key 

### ISSUE THREAD

**Issue by MLNW** [appsmithorg/appsmith#11941] opened 2022-03-17 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to link an existing app to a Git repository an SSH key is generated.
When I copy this key and paste it into GitLab as a deploy key I get the following error message:

> Key must be at least 521 bits, Deploy keys projects deploy key key must be at least 521 bits

The key that was generated:

> ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAVCmhE3uqy7jRN9ATPofOJlaYPqAWDBvj+yhkGAkOojBEMji97LRcFyfUQyGvhhYKLHwSbLxxctHD9Kkb8Inr8= appsmith

### Steps To Reproduce

1. Go to `Connect to git repository`
2. Enter a GitLab URL
3. Copy the generated SSH key
4. Go to the GitLab repo
5. Add the copied key as a deploy key

### Version

Self Hosted - 1.6.15

**Comment by Nikhil-Nandagopal** [comment] 2022-03-18 10:48
@MLNW thank you for reporting this issue. 

@abhvsn @AnaghHegde can we have a look at what went wrong here?

**Comment by AnaghHegde** [comment] 2022-03-18 13:04
@MLNW Can you confirm if you have copied the keys correctly? I just tried connecting an app to gtilab repo from appsmith cloud. It works perfectly fine. Here is the recording of the video - https://www.loom.com/share/ea942969ba744d4480be3f677aa77334

**Comment by MLNW** [comment] 2022-03-18 13:11
@AnaghHegde Yes, I am 100% sure I copied the key correctly. To be sure I just tried again and it still does not work. I posted a copied key in the original post.

I tried regenerating the key but it does not seem to change.

**Comment by AnaghHegde** [comment] 2022-03-18 13:17
Can you share a screen recording? Because I am not able to reproduce the issue.

**Comment by hiteshjoshi** [comment] 2022-03-19 07:00
Hi @MLNW are you on self hosted GitLab or cloud version? We are unable to reproduce this on cloud.

**Comment by MLNW** [comment] 2022-03-23 20:33
> Hi @MLNW are you on self hosted GitLab or cloud version? We are unable to reproduce this on cloud.

As stated in the original post I am on a self hosted instance.

**Comment by AnaghHegde** [comment] 2022-03-25 09:49
@MLNW We generate key of size `256` bits. Can you check the gitlab settings if your organisation has a different settings. We can discuss this over a call if you are having any issues.

**Comment by AnaghHegde** [comment] 2022-04-08 04:56
@MLNW Can you please let us know if you are still facing the issue? We can schedule a call to debug the issue further.

**Comment by Nikhil-Nandagopal** [comment] 2022-04-11 06:02
@MLNW please write to support@appsmith.com so we can schedule a call to debug your issue if you're still facing this. We're closing this issue in the meanwhile

**Closed by Nikhil-Nandagopal** 2022-04-11 06:02 UTC
Labels: Bug, Needs More Info, High, Cannot Reproduce Issue, Platform Pod, Git Version Control, Team Managers Pod

**Comment by pabloogc** [comment] 2022-04-12 23:09
Same issue with github, given error is:

```Key is invalid. You must supply a key in OpenSSH public key format```
