### ISSUE TITLE
[Bug] Enhancement : On adding Email id the role field must get activated 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1269] opened 2020-10-19 05:55 UTC
Steps to reproduce:
1) Navigate to homepage
2) Click on the Share option 
3) Select the role , Ensure the email ID is not added 
and observe 

Observation:
1) The role does not get selected until the Email Id is been added 
2) No error message is displayed to user stating on reason for role not being selected 

Expectation:
1) On adding Email id the role field must get activated 
OR
2) Add an error message stating "Please add an email ID to select the Role"

**Comment by Nikhil-Nandagopal** [comment] 2020-10-19 08:59
@prapullac duplicate of #1239

**Closed by Nikhil-Nandagopal** 2020-10-19 08:59 UTC
Labels: Bug, Low, Release
