### ISSUE TITLE
[Bug]: Evaluated value scrolls horizontally 

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#20840] opened 2023-02-21 12:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On some error tabs, we can observe that error tab is being scrolled horizontally as well.

### Steps To Reproduce

1. Drag & Drop a filepicker widget
2. Drag & Drop a Text widget
3. Bind filepicker widget with Text widget as shown in video
4. Observe that Error tab can be scrolled horizontally

### Public Sample App

https://release.app.appsmith.com/app/untitled-application-2/page1-63f4bc4d9e6fd93ee3ecbcf7

### Issue video log

https://bthrujcsw8.vmaker.com/record/Q2FFOkMf0RjHz4Vo

### Version

Cloud/ Release

**Comment by rohan-arthur** [comment] 2024-05-22 09:48
https://github.com/appsmithorg/appsmith/assets/94514895/1c000925-89c8-4064-84d5-da69c1177877

cannot reproduce, closing this issue

**Closed by rohan-arthur** 2024-05-22 09:48 UTC
Labels: Bug, Low, Production, Cannot Reproduce Issue, FE Coders Pod, Evaluated Value, Integrations Pod, Integrations Pod General
