### ISSUE TITLE
Pop up still remains when Modal widget is selected

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#20767] opened 2023-02-20 05:45 UTC

**Comment by rimildeyjsr** [comment] 2023-03-01 05:36
@AnandiKulkarni @ramsaptami - Unable to reproduce this issue. It might have got solved by another solution we had for a similar problem. Moving this to needs QA
cc @ravikp7 @satbir121 @bharath31

**Comment by shwetha-ramesh** [comment] 2023-03-01 11:06
@rimildeyjsr able to reproduce this on new dp
https://www.loom.com/share/f302d23403334c6bae66a616e0e23eb5

**Comment by arunvjn** [comment] 2023-03-24 05:10
The behaviour now would be to close the action selector popup when a new modal is created to keep it consistent with new API/JSObject creation. We'll might have to revisit this in the future.

**Comment by shwetha-ramesh** [comment] 2023-03-29 13:20
@arunvjn please refer the video below
https://www.loom.com/share/5fad450d85fd455e9f3d62acfe0ff075

**Comment by ravikp7** [comment] 2023-04-05 11:19
@shwetha-ramesh This looks fixed to me. I'm not able to understand what's the issue. After selecting new modal, the popup is getting closed.

**Comment by shwetha-ramesh** [comment] 2023-04-05 13:31
Tested, works as expected. Moving to Done

**Closed** 2023-04-10 10:35 UTC
Labels: Deploy Preview, FE Coders Pod, AST-frontend, Action Selector
