### ISSUE TITLE
[Bug]: Duplicating an application does not duplicates a JS Object

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#9611] opened 2021-12-06 18:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I duplicate an Application which have a JS Object, that JSObject is not present in the duplicated application.

### Steps To Reproduce

1. Add a JS object to an application
2. Go to home page and duplicate the application
3. Open the duplicated application
4. Check that JSObject is not there

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment] 2021-12-07 05:11
can confirm this happens with "duplicate" action. Might be relevant: "fork" doesn't have this problem.

**Comment by nidhi-nair** [comment] 2021-12-07 05:41
Closing as duplicate of #9372.

**Closed by nidhi-nair** 2021-12-07 05:41 UTC
Labels: Bug, Duplicate, Actions Pod, High, Needs Triaging, JS Editor, FE Coders Pod
