### ISSUE TITLE
[Bug] Appsmith fails on Page Load action when it is fetching Dropdown items from a MySQL DB

### ISSUE THREAD

**Issue by naqushab** [appsmithorg/appsmith#2508] opened 2021-01-10 18:01 UTC
## Description

The OnPageLoad dropdowns doesn't get populated and hangs

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to the Page without going to Editor page
2. Click on any page
3. See Dropdowns
4. The On page load action gets timeout and never gets populated

https://user-images.githubusercontent.com/6817118/104131374-f1ff2a80-539b-11eb-86f8-9855e9e40c2f.mov

### Important Details
 - Version: On-Premise Docker Installation of Appsmith, Database - MySQL
 - OS: Linux - Ubuntu
 - Browser Chrome

**Comment by mohanarpit** [comment] 2021-01-11 08:03
@naqushab Thanks for raising this issue. Would love to get more details on this issue so that we can reproduce this problem. 
I have a few simple questions to eliminate any basic issues:
1. Was the "Run on page load" toggle enabled in the DB Query settings?
2. How many DB queries are running on page load? Is it 1 or multiple?
3. If there are multiple DB queries being executed, are they all hitting the same database or different ones?

If you'd be more comfortable sharing information on a private channel, can I drop you an email on the one listed on your Github profile? If you'd prefer an alternative communication channel, please let me know.

**Comment by naqushab** [comment] 2021-01-11 08:30
Hey @mohanarpit, I am following up with Nikhil on this over discord. And we have a call for it to discuss the problem. But to answer your question, here it is-
1. Yes, it is toggled on with increased timeout for DQ query.
2. If you consider each tab as a seperate page, then only one query runs at page load and the next drop down is dependent on the first result. If you consider all the tabs as a single page, then 3 queries run at page load.
Only 1 query is running and a quite simple one.
3. As said, 1 query is being executed and it is all in one single database which is also an on-premise installation.

I can share the info as it is a pet project over here as well.

**Comment by sumitsum** [comment] 2021-01-13 07:13
Hi @naqushab, can you please share the following info:
1. What happens when you go to your MySQL query page in edit mode and click on "Run" ? What is the query timeout set to ?
2. Repeat step 1 after you go to your datasource credentials page in edit mode, click "Test", click "Save".

**Comment by sumitsum** [comment] 2021-01-20 11:35
cc: @Nikhil-Nandagopal @mohanarpit 
Updates:
(1) We have a work around - toggling the button "make app public" resolves the issue. Should we markdown the issue to "high priority" from "critical" because a work around is available ?
(2) Root cause - when a datasource is created after marking the app as public, then the datasource does not inherit execute permissions for anonymous user. I am working to get a fix.

**Comment by sumitsum** [comment] 2021-01-21 06:15
cc: @Nikhil-Nandagopal @mohanarpit 
Changing label to "high priority" from "critical" because:
(a) The fix for this problem will only apply to new applications / datasources. 
(b) Occurrence frequency of this problem is low. 
(c) An easy work around is available to fix the issue.

**Comment by naqushab** [comment] 2021-01-21 11:07
Hey, sorry had a family emergency. I'll try to provide all the info and also try out the workaround. 
Does the workaround fixes the problem permanently or does it need to be done every time the issue occurs? Is there an automated way to trigger that action, so that I can maybe setup a cron job to do that? I am happy to de-escalate issue if it is fixable via a small workaround.

**Comment by sumitsum** [comment] 2021-01-21 13:35
@naqushab The workaround is to toggle off and on the "make app public" button that is available when you click on the share application button. Can you please check and confirm ?

**Comment by naqushab** [comment] 2021-01-21 13:41
Okay. Now I got it. I'll check and update here.

**Comment by naqushab** [comment] 2021-01-21 21:09
The workaround worked. Thank you for identifying this tricky workaround. @sumitsum

**Comment by sumitsum** [comment] 2021-02-16 19:09
@trishaanand assigning to you as per today's discussion.

**Closed** 2021-02-18 12:35 UTC
Labels: Actions, Actions Pod, Bug, High
