### ISSUE TITLE
[Bug]: [aforce] Issue with downloading large .wav files from S3 bucket

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#34341] opened 2024-06-19 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This user is facing an issue with downloading large .wav files from an S3 bucket. While files of smaller size (810kb) download successfully, larger ones (4726kb) fail to do so. They get an Unexpected error when trying to fetch the larger file.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1718226840833629

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Cloud

**Comment by NilanshBansal** [comment] 2024-06-26 10:21
Since the user has not replied back for the last 4 days, we are closing this issue for now.
cc: @rishabhrathod01 @rohan-arthur

**Comment by rishabhrathod01** [comment] 2024-06-27 10:20
Reopening this issue as the user has responded with the logs.

**Comment by rishabhrathod01** [comment] 2024-07-03 13:30
Moving it back to the spring backlog as we decide to prioritize this after completing https://github.com/appsmithorg/appsmith/issues/34684

**Comment by rishabhrathod01** [comment] 2024-07-04 14:19
We had a call with the user and realized the root cause of the issue was that the query was timing out. Problem was fixed after increasing the timeout time for the query.

**Closed by rishabhrathod01** 2024-07-04 14:19 UTC
Labels: Bug, High, Production, Cannot Reproduce Issue, Needs Triaging, S3, BE Coders Pod, Integrations Pod
