### ISSUE TITLE
[Bug] Widget name gets hidden behind other elements

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#997] opened 2020-10-05 15:47 UTC
https://www.notion.so/Widget-name-gets-hidden-behind-other-elements-e97e10357332460995a6cc750b9c6291

**Comment by jsartisan** [comment] 2020-12-04 09:43
@Nikhil-Nandagopal Is this still happening? I am not able to reproduce this. 
Can you share the steps if you can reproduce this on your end?

**Comment by Nikhil-Nandagopal** [comment] 2020-12-04 10:50
@jsartisan doesn't seem to be happening anymore. closing it

**Closed by Nikhil-Nandagopal** 2020-12-04 10:50 UTC
Labels: Bug, Frontend, Low, Release, UI Building, Widgets
