### ISSUE TITLE
[Bug]: The widget gets reset and displays the hidden series chart as well on clicking on chart datapoints

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#25783] opened 2023-07-27 10:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue seen after updating charts from fusion to ECharts

### Steps To Reproduce

1. Drag & Drop a Chart widget
2. Add multi series chart data
3. Click some legends to hide the series data graph
4. Click on the datapoints visible on chart
5. Observe that the hidden chart graphs are visible now

### Environment

Production

### Issue video log

https://www.loom.com/share/d0545e25480e4fcc8c1fbdbc4bb5c8d5?sid=64fcbf2b-05a1-4044-8906-33c05933a854

### Version

Cloud/Release

**Comment by rajatagrawal** [comment] 2023-07-27 12:08
This is happening because the chart widget gets rerendered when a user clicks on a datapoint. The fix would be to stop rerendering of the chart for this scenario. This bug is not coming from ECharts library, but it is coming from our codebase. So the unknown factor about the cause of this issue isn't there anymore now.

**Comment by dilippitchika** [comment] 2023-07-31 05:37
@rajatagrawal can we close this then?

**Comment by rajatagrawal** [comment] 2023-08-01 10:45
@chandannkumar I have also updated the UI of Chart Error Message as part of the fix for this issue. Please refer to [this slack thread](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1690444629395199?thread_ts=1690174913.925549&cid=C02JV8G1MP0) for expected Chart Widget Error UI.

**Closed** 2023-08-03 05:58 UTC
Labels: Bug, Chart Widget, App Viewers Pod, Needs Triaging, Medium
