### ISSUE TITLE
[Bug]: Cron Expression for Automated Backups Not Working

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31090] opened 2024-02-13 08:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user has set up this environment variable: `APPSMITH_BACKUP_CRON_EXPRESSION="0 12 * * SAT"` . However, the backup is running every day and not as expected only on Saturdays. Appsmith backup starts every day at 0 midnight.
Even when trying to change it to `APPSMITH_BACKUP_CRON_EXPRESSION="0 22 * * 1` (1 for Monday), the behavior is the same. 

### Steps To Reproduce

1. Set the environment variable `APPSMITH_BACKUP_CRON_EXPRESSION="0 12 * * SAT"` in the `docker.env` file.
2. Restart Appsmith.
3. Note that the backup starts every day at midnight.

### Environment

Production

### Version

self-hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5ks03w)

**Comment by pratapaprasanna** [comment] 2024-04-03 18:23
possible duplicate of [31393](https://github.com/appsmithorg/appsmith/issues/31393)

**Closed by pratapaprasanna** 2024-04-03 18:23 UTC
Labels: Bug, Production, Needs Triaging, DevOps Pod, Medium, Backup & Restore
