### ISSUE TITLE
[Bug]: App crashes when exploring a tab widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20615] opened 2023-02-14 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes when trying to explore/add widgets to a tab widget on a specific tab of an app.
Unable to repro the exact scenario since I don't know how the app ended up in this state. 

### Steps To Reproduce

1. Navigate to the app [here](https://release.app.appsmith.com/app/og/page1-63d79e49a527647debc839d6/edit#o4e3yzwxmm)  and try to add widgets to the tab widget or use the entity explorer to look at child widgets and observe the app crash

Linking app JSON to repro on prod
[crash.zip](https://github.com/appsmithorg/appsmith/files/10731323/crash.zip)

### Issue video log

https://www.loom.com/share/b66b6e98a0314010800d8ce09499637e

### Version

Cloud

**Comment by somangshu** [comment] 2023-02-14 11:50
@dhruvikn can you find why is this happening?

**Comment by dhruvikn** [comment] 2023-02-14 11:51
On it.

**Comment by kamakshibhat-appsmith** [comment] 2023-02-14 12:11
There seems to be Listv2 inside the Tab widget. @ramsaptami You might have used this Application to test Listv2 , since the widget is not available in release,hence the unexpected behaviour

cc: @dilippitchika @somangshu @dhruvikn

**Comment by kamakshibhat-appsmith** [comment] 2023-02-14 12:12
@dilippitchika We can close this

**Closed** 2023-02-14 12:39 UTC
Labels: Bug, Tab Widget, App Viewers Pod, High, Production, Needs Triaging

**Comment by ramsaptami** [comment] 2023-02-14 12:47
@kamakshibhat-appsmith you're right, I did use this app during our bug bash, my bad!
