### ISSUE TITLE
PR Template is missing!

### ISSUE THREAD

**Issue by Hard-Coder05** [appsmithorg/appsmith#894] opened 2020-10-03 07:29 UTC
## Summary

I have noticed that the PR template iss missing for https://github.com/appsmithorg/appsmith-docs .

## Motivation

This should be completed as early as possible because there are numerous PR's made everyday but in an irregular way!

**Comment by Hard-Coder05** [comment] 2020-10-03 07:29
@Nikhil-Nandagopal @mohanarpit I hope this is a good issue for Hacktoberfest and I would like to work on it!

**Comment by hetunandu** [comment] 2020-10-03 08:39
Hey @Hard-Coder05! Welcome to Appsmith 🎉 Love your enthusiasm to improve our repo during Hacktoberfest. Unfortunately this issue is already raised and someone is already working on it. I welcome you to go through our [Good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) or create a new one by testing the application at [app.appsmith.com](https://app.appsmith.com) 
Looking forward to your contributions to our repo 😄

**Comment by hetunandu** [comment] 2020-10-03 08:39
Duplicate of #826

**Closed by hetunandu** 2020-10-03 08:39 UTC
