### ISSUE TITLE
[Feature]: Increase proxy_read_timeout Or Configure It From the UI

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#17068] opened 2022-09-26 13:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For APIs running more than 10 seconds, the execution fails. The fix for this is to increase the  proxy_read_timeout in the /api location in the sites-enabled/default file.
However, users need a solution where they do not have to override the entire Nginx config because the setting will not persist if they have to recreate the container. 
More info in [this Intercom thread](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100168637#part_id=initial-part-164629100168637-1444263488).

### Why should this be worked on?

A permanent fix for this issue would improve the user experience.

**Comment by Nikhil-Nandagopal** [comment] 2023-03-21 14:01
@sharat87 reading the intercom conversation it seems their query takes 2 minutes to execute and they expect that to happen. They want a way to handle this so that if they configure 120seconds in the UI, it should work. Thus however is a limit at the nginx level I think

**Comment by sharat87** [comment] 2023-03-23 04:03
Understood. Then this is indeed a feature request. We'll need to test to verify if NGINX will allow us to set longer timeouts, and if it does, look into making it configurable. I'll keep this open and see if we can prioritize. Thanks.

**Comment by sharat87** [comment] 2023-06-02 11:42
Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/14535.

**Closed by sharat87** 2023-06-02 11:42 UTC
Labels: Enhancement, Super Admin, DevOps Pod
