### ISSUE TITLE
[Bug]: Datasource reconnect modal throws `not found` error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21740] opened 2023-03-23 15:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1421" alt="Screenshot 2023-03-23 at 8 26 02 PM" src="https://user-images.githubusercontent.com/80334441/227244529-a7f3ac48-594c-4fd7-bc88-368fd5bb8815.png">

### Steps To Reproduce

1. Import a json file which has datasources
2. Datasource reconnect modal is shown , add some datasource click save & observe an error 'Not found' error is thrown.

### Environment

Release

### Version

Release

**Comment by AnaghHegde** [comment] 2023-03-25 16:49
@Parthvi12 The API that is failing is `https://release.app.appsmith.com/api/v1/environments/workspaces/`

**Comment by Parthvi12** [comment] 2023-03-27 04:19
Treating it as release blocker as we have regressed here and its a poor UX.

**Comment by sondermanish** [comment] 2023-03-27 08:54
Tested with user email ids with domain outside appsmith.com and moolya.com, not reproducible. 
The error is contained within the feature flag only

**Comment by trishaanand** [comment] 2023-04-05 05:51
@Parthvi12 @manish535 : Since this is happening wrt multiple environments (which itself is behind a feature flag), can we not track this under release blocker? This wouldnt impact any of our customers.

**Comment by ayushpahwa** [comment] 2023-05-22 08:18
Marking this as closed since environments collections have been reintroduced and the API is not failing anymore

**Closed by ayushpahwa** 2023-05-22 08:18 UTC
Labels: Bug, Low, Release, Regressed, BE Coders Pod, Data Platform Pod, Datasource Environments
