### ISSUE TITLE
[Bug]  Nested API or datasource breaks the widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6370] opened 2021-08-03 16:35 UTC
Steps to reproduce:
1) Add an API 
2) Run the API 
3) Select list from the widget list
and observe the widget on the canvas

Observation:
It is observed that when the nested API is binded to the widget breaks 

Expectation:
As we are looking into providing good experience to the user we need to dynamically read and understand the API before binding them. 
![Screenshot 2021-08-03 at 10 03 26 PM](https://user-images.githubusercontent.com/71753653/128052678-e64b87c3-9104-4814-9c78-188937beff36.png)

**Comment by akash-codemonk** [comment] 2021-08-04 04:34
Closing as duplicate of #6268

**Closed** 2021-08-04 17:04 UTC
Labels: API pane, Actions Pod, Bug, High, Needs Triaging, regression, release-frozen
