### ISSUE TITLE
[Bug]: FilePicker selector counter does not reset when unmounted

### ISSUE THREAD

**Issue by noe-charmet** [appsmithorg/appsmith#10887] opened 2022-02-04 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a FilePicker is included in a modal, the `X files selected` text on the button is not reset with the modal open/close cycle.
Moreover, each time a new file is selected, the counter increases continously.

### Steps To Reproduce

1. Create a Modal widget with a FilePicker inside of it
2. Open the modal and select a file with the FilePicker. The FilePicker button will now read "1 file selected"
3. Close the modal, and repeat step 2. the FilePicker button will now read "2 files selected"

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment] 2022-02-04 09:49
Hello, this seems like a duplicate of #6492

**Closed by Nikhil-Nandagopal** 2022-02-04 09:49 UTC
Labels: Bug, Needs Triaging
