### ISSUE TITLE
[Bug]: On page load queries fail when they use one of the sample databases

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#20865] opened 2023-02-22 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An error toast is thrown on page load when a query using a sample database is set to run on page load. 

Related issues  https://github.com/appsmithorg/appsmith/issues/20852

### Steps To Reproduce

1. Create a new app
2. Create a new mongo query using the mongo sample database. 
3. Run the query succesfully.
4. Add a table widget and bind the query to the same.
5. Refresh the page.
6. An error toast is visible. The query when run from the query pane runs successfully. 

https://user-images.githubusercontent.com/67054171/220573694-bd71bd32-4b7a-4096-a964-0f8e9f427856.mov

### Version

Cloud /  v1.9.8-SNAPSHOT

**Comment by satbir121** [comment] 2023-03-16 08:01
@ramsaptami This issue is not reproducible. Can you please check once?

**Comment by ramsaptami** [comment] 2023-03-16 09:31
Unable to reproduce this hence closing the issue

**Closed by ramsaptami** 2023-03-16 09:31 UTC
Labels: Bug, High, Needs Triaging, FE Coders Pod, OnPageLoad
