### ISSUE TITLE
[Bug]: Unable to disconnect SAML SSO in https://release-ee-https.appsmith.com instance

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22273] opened 2023-04-11 11:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to disconnect SAML SSO in https://release-ee-https.appsmith.com/ instance
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/231140212-6437bab7-4ae8-479e-959c-4ad6439a0831.png">

### Steps To Reproduce

1. go to https://release-ee-https.appsmith.com/
2. Login with  username: demo@appsmith.com password: demo@appsmith.com
3. go to admin setting
4. got o authentication
5. click on edit on saml SSO
6. now click on disconnect 
7. The error is displayed instead of disconnecting

### Environment

Release

### Version

release

**Comment by trishaanand** [comment] 2023-04-12 08:03
This issue is happening on this instance because the server is unable to connect to keycloak using the credentials present in docker.env file. This looks like a case of manual intervention which has caused this bad state.

**Comment by trishaanand** [comment] 2023-07-07 06:42
This issue was caused by manual intervention and the state has been reversed. Closing this since its not a product issue.

**Closed by trishaanand** 2023-07-07 06:42 UTC
Labels: Bug, High, Needs Triaging, Team Managers Pod, SSO
