### ISSUE TITLE
[Feature]: Add toggle to SHARE modal for user to enable app forking

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#20569] opened 2023-02-10 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This request is for a new toggle to be added to the UI of the SHARE modal, to allow users to enable forking of their applications. The toggle should be off by default.

Not all users are familiar with the term forking, so we should be careful with the labeling of this feature, and ensure we clearly communicate to the user that others will be able to copy their app once enabled. 

Mockup
![image](https://user-images.githubusercontent.com/24459976/218078576-be7820f2-321a-4322-9fb0-a34bb04d7da7.png)

### Why should this be worked on?

This will allow users to share a copy of their app, rather than give users direct access to the source app itself. 

### Deploy preview
https://appsmith-ck33fvwhx-get-appsmith.vercel.app/

**Comment by GreenFlux** [comment] 2023-03-02 16:59
@kocharrahul7 @ginilpg , could we get an update on this feature please?
cc @Nikhil-Nandagopal

**Comment by akash-codemonk** [comment] 2023-03-08 05:27
So by marking it as forkable we want to see the fork button on the deployed version of the app.
<img width="630" alt="fork button" src="https://user-images.githubusercontent.com/67054171/223625569-9ab4bd57-b10c-4d3b-a42e-da5c4775dd0f.png">

For e.g https://app.appsmith.com/applications/623cca594d9aea1b062b33c6/pages/623cca594d9aea1b062b33cd is a sample app which is forkable. 

Currently the fork button shows up only when the application is public. Do we need this to show up when the app is shared to a user and not public? FYI implementation isn't hard just needs testing for the new scenarios.  @GreenFlux @kocharrahul7

**Comment by GreenFlux** [comment] 2023-03-09 00:02
thanks @akash-codemonk. Yes, this feature should be independent of the `public` setting. We should allow for all combinations of public (true/false) and forkable (true/false). 
cc @rlnorthcutt @jacquesikot

**Comment by kocharrahul7** [comment] 2023-03-09 02:59
@GreenFlux hey, If the app isn't public how can the user fork it? for a non-public app, any non-invited user will see this:

In what scenario would it be helpful to make an app forkable and not public?
For users who are invited, they can also fork the application from the home page or within the edit page of the app.

@akash-codemonk We should also speak to TM about GAC. I'll start a thread with them

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20532920/223904672-c5977e5d-b623-403e-a347-077ae1dfc55d.png">

**Comment by akash-codemonk** [comment] 2023-03-09 05:00
> In what scenario would it be helpful to make an app forkable and not public? For users who are invited, they can also fork the application from the home page or within the edit page of the app.

For users who are invited as `App Viewer` the menu won't be visible in the home page, so in this case they will see a fork button in the deployed page. 

Anyways after thinking about a few scenarios I have some concerns about enabling forking for private apps. One of the use cases we discussed was for support, the user can share view access to the support team and mark the app as forkable. The support team will be able to debug the application having an editable version of the app without being able to edit the original app. Here if the app is shared with 10 users with view access, one of them being the appsmith support team, marking the app as forkable today will make the app forkable for all 10 users which might not be the intention of the user. 

So I think the surface area of impact is more and needs more work too look at the different possibilities if the app is forkable for private apps. For now to have minimal change we should allow apps to be forkable only if they are public. For private apps we should consider creating a separate issue.

Eitherways things to be looked at before shipping
- should create a seperate permission for forking similar to what we have for marking application as public.
- Updating the forking field should reflect in audit logs as well.

**Comment by rlnorthcutt** [comment] 2023-03-10 13:45
I don't think we should conflate these two things. Making an app forkable is a very explicit action to take, so the user should have an awareness of that. Plus, the data connections will not be carried over at this time, which is additional security protection.

Some use cases:
1. DevRel is working on a new template and want to test it without making it public yet.
2. A customer team wants to make their own private templates available for users without opening them up to the world
3. Customer wants support or a consultant to be able to work on an app _without_ being able to alter or modify the original
4. Freelancer is building a customer's app in their own workspace and wants the customer to be able to fork it into their separate workspace.

We can create a separate issue to look into this, but then it is a question of *undoing* work, which is not ideal. My suggestion is to add the forkable switch now, and open up another ticket to investigate if the switch should also force the public app (which would be an additive change).

**Comment by rlnorthcutt** [comment] 2023-03-10 13:45
+1 to Permission for forking and forking switch being in the audit log at

**Comment by kocharrahul7** [comment] 2023-03-13 05:23
Adding in comments after discussing it with @GreenFlux 

1. This setting will go in the app settings under the share and embed settings, not in the share modal. Since we feel like it will not be a very utilised feature, putting it in the share modal seems unwise.
2. When a user tries to toggle this on, they will have to be served with a double confirmation modal. This modal should have the following text:
`Enabling forking of this app means anyone who has access to this app can copy it into their own workspace. When copied, the user will also get access to any connected datasources. Are you sure you would like to enable forking?`
3. This will retain the same permissions as forking on the home page. No new permissions need to be added

**Comment by aakashDesign** [comment] 2023-03-17 10:56
Hey folks :wave:,
here is a prototype for how app fork settings can work - [https://www.figma.com/proto/aUq991dKP4aW7yepxxFete/App-fork-settings?page-id=0%3A1&[…]7%2C338%2C0.65&scaling=contain&starting-point-node-id=1%3A7912](https://www.figma.com/proto/aUq991dKP4aW7yepxxFete/App-fork-settings?page-id=0%3A1&node-id=1-7912&viewport=287%2C338%2C0.65&scaling=contain&starting-point-node-id=1%3A7912)
Github issue - https://github.com/appsmithorg/appsmith/issues/20569
Please check it out and share feedback.

**Comment by rlnorthcutt** [comment] 2023-03-21 20:25
1) This should actually go in *both* places (share and settings). This matches the expected behavior we see in other tools like Notion. It also makes sense - sharing the app, making it public, and making it reusable are all related. I think this will actually be more useful than you may think, especially when we build the community library of templates.

2) Double confirmation is great, but I think the note about connected datasources is incorrect. The forked app will *not* have the connected datasources unless they are in the same workspace, right? And even then, they are not connected by default on a forked template. There is a separate flag for cloning the data source that will not be set. @GreenFlux to confirm.

Prototype looks good for the settings page. Here are the mockups we have in our internal notes:

![image](https://user-images.githubusercontent.com/673633/226732192-970a165c-2640-4864-b80a-14435d93a4c6.png)


![image](https://user-images.githubusercontent.com/673633/226732254-ce2aee5f-87b0-4bfe-b689-729a6d97ed29.png)

**Comment by GreenFlux** [comment] 2023-03-22 09:59
@rlnorthcutt it should not share the credentials for the new datasource copy unless `exportWithConfiguration=true`. However, there's a bug with Authenticated REST API datasources that is ignoring this flag, and including the credentials regardless of the setting. I've just submitted an issue for it. 
https://github.com/appsmithorg/appsmith/issues/21691

This issue should probably be prioritized before exposing the forking option on the UI.

**Comment by aakashDesign** [comment] 2023-03-23 12:04
@rlnorthcutt I see your point, for why the fork toggle should be added to the Invite modal but I'd recommend we plan it as a phase 2 of the feature for the following reasons -
1. Keeping the invite modal clutter free is paramount. Any action added to the invite modal should affect 100% of the users. Let's get more data on the feature's adoption before we decide.
2. The current architecture of the modal is not flexible enough to add new actions. We'd have to expand the scope of the project to make any design changes, and they'll require cross-pod collaboration.

@kocharrahul7 As @GreenFlux pointed out, credentials for the datasource are not shared outside of the workspace, so in that case we should remove the double confirmation in my opinion.

**Comment by rlnorthcutt** [comment] 2023-03-25 18:52
Understood on the invite modal. That is important, but not urgent. I think it makes sense to minimize difficulties and take our time with changes to the modal. Thank you for the detailed explanation!

I think we should get this ready, but block release until issue #21691 is fixed. Are there other related issues we should consider?

**Comment by akash-codemonk** [comment] 2023-03-29 13:15
https://appsmith-m46itso6q-get-appsmith.vercel.app/ deploy preview. 

The forked app will have the connected datasources as per how it works today on prod(for e.g sample apps). So essentially whoever forks the app, they will be able to query the datasources without adding their own credentials.

**Comment by Richarex** [comment] 2023-04-05 11:05
- [ ] **Make application forkable** toggle switch is not getting displayed for old apps is this expected? Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/7EY6dXhR4xDgLK7i

**Comment by rlnorthcutt** [comment] 2023-04-07 14:32
On item 1 - I would expect to see the toggle switch for all apps, old and new. 

On item 2 - when a user has edit access to an app, then they would see the edit button, not the fork button. My guess is that the forking button is shown by default, and then removed when edit access is asserted.

**Comment by akash-codemonk** [comment] 2023-04-07 15:44
> * [ ]  **Make application forkable** toggle switch is not getting displayed for old apps is this expected? Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/7EY6dXhR4xDgLK7i

We checked this on call, it wasn't an issue with old apps. The user just didn't have the permission to mark an app as forkable, so the section was hidden. 

> * [ ]  Glitch is observed when the user deploys the app **Fork App** button is seen for few secs and then goes off is it expected? Please refer the video:- https://jiju8jbmwa.vmaker.com/record/qYaTWXTblzrweSIb

Yup as @rlnorthcutt mentioned it defaults to fork(only if the app is forkable), once we know the user has edit access it replaces with the edit button. Will fix this by waiting to receive all information then show the right button once. Will post the new DP once fixed

@Richarex

**Comment by rlnorthcutt** [comment] 2023-04-10 21:37
Looking good! Just want to check again on the tooltip: the expectation is that when the app is forked, the datasource connection is made, but the credentials are NOT shared. So, you have to reset or reconnect to the datasource: https://github.com/appsmithorg/appsmith/issues/21691

@aakashDesign @GreenFlux @jacquesikot @rahulbarwal

**Comment by akash-codemonk** [comment] 2023-05-09 04:26
The PR for this is on hold. There are is a prerequisite issue https://github.com/appsmithorg/appsmith/issues/21691 which needs to be closed first.
We are targeting to get this on release by end of this month.

**Closed** 2023-05-23 11:09 UTC
Labels: Enhancement, Fork App, New Developers Pod, Templates pod, Test Plan Approved
