### ISSUE TITLE
[Bug] Filepicker widget: does not clear selected files

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3836] opened 2021-04-01 17:44 UTC
## Description
After removing the file from the uploaded list, it still remains internally at the original index so multiple calls using `filepicker.files[0].data` uploads the same file even though we remove a file and add a new file in the widget.

### Steps to reproduce the behaviour:

1. Select a file in filepicker
2. Create an S3 create query which uploads the first file selected using `FilePicker1.files[0].data`
3. Click on the filepicker to execute the create query
4. Remove the file from the filepicker's list and add another file
5. FilePicker shows 2 files selected, when it should only have one <--- Bug 1
6. Click on the filepicker to execute the create query
7. The query succeeds but uploads the same file which was deleted earlier. <--- Bug 2

### Important Details
 Release 1.4.6

**Comment by RakshaKShetty** [comment] 2022-02-07 13:13
reopening the issue facing similar issue in s3 https://www.loom.com/share/758c90e448494370b3549833daf18a99

**Comment by vibhandikyash** [comment] 2022-02-10 10:13
This issue is duplicate of #6492. Can be tracked there further.

**Closed** 2022-02-10 10:13 UTC
Labels: Bug, File Picker Widget, App Viewers Pod, High, UI Building Pod, community
