### ISSUE TITLE
[Bug]: Authenticate API does not read bearer token and shows errors

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#19645] opened 2023-01-09 21:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This problem seems to be with a specific token. The token is obtained through an API to get the token and then authenticate the API.
For this, we have Oauth2 the token we get it correctly but nevertheless this token breaks Appsmith

I did another test which was to directly pass the token I got the token and put it normally in the auth API using bearer token and this gives me problems it shows me these two errors.

This does work when used in postman, however in Appsmith it does not work.

Below I attach screenshots and a video

Mistake 1:

```js
Unexpected state: Duplicate key error. Message: Write operation error on server appsmith-prod-shard-00-02.swrsq.mongodb.net:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: appsmith.datasource index: workspace_datasource_deleted_compound_index dup key: { workspaceId: "6266bb1300cba01cd0301018", name: "Untitled Datasource 1", deletedAt: null }', details={}}.. Please reach out to Appsmith customer support to report this
```

Mistake 2:

```js
{"Message":"User is not authorized to access this resource with an explicit deny"}

```

Video:

https://user-images.githubusercontent.com/114161539/211413464-ad1232b8-43a9-462f-88e6-b45fad61b6c1.mp4

### Steps To Reproduce

1. Use support@appsmith.com account.
2. Enter this [application](https://app.appsmith.com/app/fmtc-chit-replacer-copy/page1-63b5a4b9f276cd0745e979ad
).
3. Run the query called Get Error.
4. Look at the error.
5. Copy the bearer token and try to eject the query from a new data source, but it will be authenticated with the bearer token.
6. look at the error.
7. You can test that this works in postman.

### Public Sample App

https://app.appsmith.com/app/fmtc-chit-replacer-copy/page1-63b5a4b9f276cd0745e979ad

### Version

Appsmith v1.8.16-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6skcs)

**Comment by felix-appsmith** [comment] 2023-01-20 15:10
Another user affected by this problem. 
conversation link: https://app.frontapp.com/open/cnv_vwd6xak?key=KmR8o4SJPDQvda2f9QpF73M0WEEk3wfD

**Comment by felix-appsmith** [comment] 2023-01-30 15:19
Another user affected by this problem.
Conversation link:  https://app.frontapp.com/open/cnv_w5zq4b0?key=avFnQzBpZ80BPlG155OyloisDu0O3uQ9

**Comment by felix-appsmith** [comment] 2023-01-30 15:20
Note: the users do not show the same error code, however the main problem for the 3 users if the token is not being passed correctly.

**Comment by rohan-arthur** [comment] 2024-07-09 05:36
Since this is specific issue that is not otherwise reproducible, and:
- we don't have edit access to the sample app
- the sentry also hasn't recurred in a long time
...I am closing this issue

**Closed** 2024-07-09 05:36 UTC
Labels: Bug, Backend, High, Production, Cannot Reproduce Issue, Community Reported, BE Coders Pod, REST API plugin, Integrations Pod
