### ISSUE TITLE
[Bug]: UUID function not working as expected

### ISSUE THREAD

**Issue by sri-repareo** [appsmithorg/appsmith#35025] opened 2024-07-18 12:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The UUID function doesn't seem to return anything for a hexstring as a result the mongoquery search seems to break and return all the documents.

### Steps To Reproduce

1. pass a hexstring to the UUID function in mongoquery , the evaluated value says empty.
![image](https://github.com/user-attachments/assets/cd5ac8ea-cdb2-40ca-93c9-2c4f94bf32ba)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/1eb6709207e54fc3a558b5d86bf4060d

### Version

Self hosted

**Comment by rishabhrathod01** [comment] 2024-07-26 11:13
@sri-repareo which UUID library is being used here? If it is the recommended library from appsmith then UUID.generate() is the method to be used here.  Refer the docs here  https://github.com/LiosK/UUID.js/#uuidjs---rfc-compliant-uuid-generator-for-javascript 

I believe this is being confused with the popular UUID library with a different syntax. https://github.com/uuidjs/uuid 

I will be closing this issue for now. Please reopen this issue if the error still is not resolved.

**Comment by sri-repareo** [comment] 2024-07-26 11:22
I am using the recommended library from appsmith. UUID.generate() is used to generate  a new uuid. What I want is to convert the uuid stored as text to uuid that can be used to filter mongo data.
for example : 
{{
{
  "location_id": UUID(4b9e4acf-66ee-4e8f-92ac-5b150f6564cd)
}
}}

**Comment by Nikhil-Nandagopal** [comment] 2024-07-29 10:12
@sri-repareo can you give us the link to the custom javascript library you installed?

**Comment by sri-repareo** [comment] 2024-07-29 10:16
@Nikhil-Nandagopal I think its this one : 
https://github.com/LiosK/UUID.js/#uuidjs---rfc-compliant-uuid-generator-for-javascript
This comes pre-installed with appsmith I guess.

**Comment by Nikhil-Nandagopal** [comment] 2024-07-29 10:18
@sri-repareo which version of Appsmith are you on? 
Can you try UUID. parse() instead of UUID() that seems to be the right method

**Comment by sri-repareo** [comment] 2024-07-29 10:39
I am using Appsmith Community v1.32.
I tried this : 
{{
{
  "location_id": UUID.parse(GarageSearchSelect.selectedOptionValue),
  "service._id": UUID.parse(ServiceSearchSelect.selectedOptionValue) 
}
}}
This returns null as well.
Although I see output in the evaluated value window ![image](https://github.com/user-attachments/assets/8b6fe4ef-fb1f-41ca-8687-9dda68050d5c)
When I run a blank query to see the records in my mongo db this is how I see it in the output: 
![image](https://github.com/user-attachments/assets/253615b1-f11d-42e7-8836-d1fa30697bf2)

**Comment by Nikhil-Nandagopal** [comment] 2024-07-29 16:39
@sri-repareo so maybe the query itself is incorrect. Are you trying to fetch a collection by the ID? have you tried constructing an ObjectId('id') value? (You need to turn off smart substitution to do this)

**Comment by Nikhil-Nandagopal** [comment] 2024-07-29 16:43
@sri-repareo can you confirm that hardcoding the string 
```{
  "location_id": "4b9e4acf-66ee-4e8f-92ac-5b150f6564cd"
}```
Works for the query? If that doesn't work then the problem is with the query construction

**Comment by sri-repareo** [comment] 2024-07-30 14:22
The same query works in the mongoshell and other apps without any issue: 
{
  "location_id": UUID(GarageSearchSelect.selectedOptionValue),
	"service._id": UUID(ServiceSearchSelect.selectedOptionValue) 
}

**Comment by sri-repareo** [comment] 2024-07-30 14:30
@Nikhil-Nandagopal This query returns data in mongoshell but not in appsmith : 
{
  "location_id": "4b9e4acf-66ee-4e8f-92ac-5b150f6564cd"
}

**Comment by Nikhil-Nandagopal** [comment] 2024-07-30 14:54
@sri-repareo can you try if this works
{
"location_id": ObjectId("4b9e4acf-66ee-4e8f-92ac-5b150f6564cd")
}

**Comment by sri-repareo** [comment] 2024-07-30 14:55
![image](https://github.com/user-attachments/assets/938d7d3a-2c2d-4fb9-9492-985918266c9c)
I get error.

**Comment by Nikhil-Nandagopal** [comment] 2024-07-30 15:03
@sri-repareo from what I've read it seems you should use
{
"location_id": BinData(subType,base64)
}

Can you try this?

**Comment by sri-repareo** [comment] 2024-07-30 15:04
how do I pass : 4b9e4acf-66ee-4e8f-92ac-5b150f6564cd?

**Comment by Nikhil-Nandagopal** [comment] 2024-07-30 15:05
{
"location_id": BinData("04", "4b9e4acf-66ee-4e8f-92ac-5b150f6564cd")
}

**Comment by sri-repareo** [comment] 2024-07-30 15:07
![image](https://github.com/user-attachments/assets/4c4137c7-ee01-44cc-b1ef-d46517f2ac51)
Error

**Comment by Nikhil-Nandagopal** [comment] 2024-07-30 15:11
@sri-repareo remove the quotes from 04 and just make it 4

**Comment by sri-repareo** [comment] 2024-07-30 15:16
![image](https://github.com/user-attachments/assets/73932129-6a28-4830-a0fb-6a0aeb0be57a)
unfortunately still error.

**Comment by sri-repareo** [comment] 2024-07-31 11:20
@Nikhil-Nandagopal How do you mean? I am getting the result for the same location id an same query in other applications/ mongo shell. 
![image](https://github.com/user-attachments/assets/1b9035bd-b6bf-4e3a-82ba-3a3e638dbb81)

**Comment by rishabhrathod01** [comment] 2024-08-01 06:03
@sri-repareo My bad, earlier i believed you are trying to use JS UUID method but according to your latest messages i believe you need to use mongoDB UUID method. Could you please try below query. 

```
{
"location_id": UUID('{{GarageSearchSelect.selectedOptionValue}}')
}
``` 

NOTE: If you want to use the mongoDB method, that should be outside of double curly braces ( `{{ }}` ) else appsmith will consider it as javascript.

**Comment by sri-repareo** [comment] 2024-08-01 06:21
I get error: 
![image](https://github.com/user-attachments/assets/d827f6dc-0713-4747-b0b7-c882c759debf)
![image](https://github.com/user-attachments/assets/3b7ee8cd-8df2-45dd-bbae-5041f31a2eb7)

**Comment by rishabhrathod01** [comment] 2024-08-01 06:44
@sri-repareo Could you please it with removing all the comments added above?  Also, if it fails again are you available to connect on a sync call to resolve this ?

**Comment by Nikhil-Nandagopal** [comment] 2024-08-16 08:19
@sri-repareo closing this since we haven't heard back from you in a while

**Closed by Nikhil-Nandagopal** 2024-08-16 08:19 UTC
Labels: Bug, Needs More Info, Production, Cannot Reproduce Issue, Community Reported, Needs Triaging, Mongo, Query & JS Pod, Integrations Product
