### ISSUE TITLE
[Bug] Remove labels from the Chart Widget 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1621] opened 2020-11-06 12:44 UTC
Steps to reproduce:
1) Add chart widget 
and observe that labels are displayed to user

Please refer to the screenshot below 

![Screenshot 2020-11-06 at 6 09 32 PM](https://user-images.githubusercontent.com/71753653/98367275-5bd91c00-205b-11eb-924e-f268a48f4681.png)

**Comment by areyabhishek** [comment] 2020-11-08 13:42
@prapullac this is not what I meant by chart labels. Chart labels are the index of items displayed in the chart. This is also a duplicate of an already filed issue #1520 Closing this issue.

**Closed by areyabhishek** 2020-11-08 13:42 UTC
Labels: Bug, Low, Release
