### ISSUE TITLE
[Bug]: Apps not getting shared even though public

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#11010] opened 2022-02-08 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Summary of the discussion/understanding from the session with the user:
(1)The user have created around 10 applications and made the app access as public.
(2)They use the sharing url to embed Appsmith application into their custom application using iframe.
(3) They provide necessary accessToken and session details as iframe src parameters required to access the appsmith application.. 
(4)Their custom application is used by several users
(5) The issue is in their custom application, one embedded appsmith application which is not complex (just a grid and 2 Api's defined) is visible for one user and another user  is not able to access.
(6) In developer tools->Network, one failed url says "Unable to find application 61f3d38991652b7c444bf668. Either the asset doesnt exist or you dont have required permissions"

As a policy they cannot share the application and denied recording the session which we accepted.
Now we have to create a scenario to simulate the issue.

### Steps To Reproduce

Based on discussion with user
(1) Create Appsmith application
(2) Embed those application in another application using iFrame
(3) Try to view the other application in different system.

Here is the iFrame syntax used
<iframe src = {r.iframe + '?embed=true' + '&brandId=' + brandId + '&accessToken=' +accessToken+ '&session=' + session + '&email=' + email} height="950" width="100%"></iframe>

### Environment

Production

### Version

Cloud

**Comment by leotom2000** [comment] 2022-02-08 18:41
A workaround like creating a new application from scratch similar to the failing application was suggested and it works, so the user is not blocked at this point. 

Suspect it could be anything related to session or tokenId getting blocked for few of their users.
Let us wait until we hear from the user again to prioritise this issue, since the scenario is currently vague.

**Comment by Nikhil-Nandagopal** [comment] 2022-02-14 06:18
Closing since it's hard for us to reproduce

**Closed by Nikhil-Nandagopal** 2022-02-14 06:18 UTC
Labels: Bug, App Viewers Pod, UI Building Pod, Needs Triaging, Platform Pod, Team Managers Pod, Embedding Apps
