### ISSUE TITLE
[Bug]-[837]:Turning off column sorting option on Table widget doesn't stop user from sorting column on client side.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#16796] opened 2022-09-15 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It's a little confusing for our users. As I understand it, the option is used similarly to serverside pagination (it doesn't stop client-side pagination).

https://discord.com/channels/725602949748752515/1019883948270157845

### Steps To Reproduce

1. turn off the column sorting
2. click on the sortable column header

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-12-21 04:38
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 837 |
| Effort (months)  | 0.5 |

Needs triaging if sortable key is being used only for server side sorting

**Comment by dilippitchika** [comment] 2022-12-21 05:23
Closing as duplicate of #15184

**Closed by dilippitchika** 2022-12-21 05:23 UTC
Labels: Bug, Table Widget, App Viewers Pod, Needs Triaging, medium
