### ISSUE TITLE
[Task]: Show changed pages and query details in commit popup

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#24059] opened 2023-06-06 03:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, the commit popup just displays the overall number of changes. There is no way for a user to understand which changes are included in the commit. As a first step toward improved communication, we can begin displaying changed page names, queries, and API along with their count, in the commit popup.

**Comment by infinitetrooper** [comment] 2023-11-24 11:30
Duplicate of #20931

**Closed by infinitetrooper** 2023-11-24 11:30 UTC
Labels: Git Version Control, Task, Git Pod
