### ISSUE TITLE
[Bug]-[450]:Table widget is not center aligned according to setting and alignment changes when page/table is refreshed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13336] opened 2022-04-26 16:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When table column values are center aligned and either page or table is refreshed then some of the values default to left-alignment. A page refresh reverts column back to user-defined center alignment though.

### Steps To Reproduce

1. Center align table data on any app with multiple pages or go to app at [this](https://release.app.appsmith.com/app/earworm/spotify-and-youtube-61ea4a44361846772cfb1180) location
2. Navigate between pages of the table widget as seen in the video and observe some column entries not center alinged as per user setting
3. Change selection from dropdown widget and observe that table refresh corrects the alignment as seen in the video
4. Observe that a page refresh also corrects alignment as per settings

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bb5ecc680be94b7cbd8799964fff2b4b-00001.gif)](https://www.loom.com/share/bb5ecc680be94b7cbd8799964fff2b4b)

Note: Steps to populate data on the table on this app incase you don't see any values:
Go to the [home page](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e) and click on the Spotify logo to go through the authorization.

### Public Sample App

https://release.app.appsmith.com/app/earworm/spotify-and-youtube-61ea4a44361846772cfb1180

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-04-28 05:21
Is reproducible on tables when I resize the columns, probably there are some issues which are cropping up due to style settings Saptami has done. Anyone triaging this please use the app above to fully understand the scenario

Adding a tentative rice score - Reach based on all the users who have set the alignment to center or right
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 450 |
| Effort (months)  | 0.5 |

**Comment by techbhavin** [comment] 2022-05-13 05:54
@dilippitchika Not able to reproduce this issue in other Application. 

we need exact step to reproduce this issue

https://images.zenhubusercontent.com/275993885/2c772dd6-c3da-4862-a2cf-2e62589d3fcc/screen_recording_2022_05_12_at_8_25_19_pm.mov

**Comment by dilippitchika** [comment] 2022-05-16 05:18
@ramsaptami can you help bhavin reproduce this on a call?

**Comment by sbalaji1192** [comment] 2022-05-25 08:10
@techbhavin I have pushed a fix https://github.com/appsmithorg/appsmith/pull/14095. please do the needful.

**Closed** 2022-06-09 04:59 UTC
Labels: Bug, Table Widget, UX Improvement, App Viewers Pod, Release, UI Building Pod, medium
