### ISSUE TITLE
[Bug] Table column names and order gets reset sporadically

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#7540] opened 2021-09-16 12:36 UTC
## Description
A user has been seeing their table columns names and order that is custom gets reset and all the changes need to be added again. This happens when the underlying data / datasource has changed

**Comment by Nikhil-Nandagopal** [comment] 2021-09-18 09:16
Related to #4984. Can we please fix this on priority? Many users are facing this

**Comment by Nikhil-Nandagopal** [comment] 2021-09-22 07:04
Duplicate of #4984

**Closed by Nikhil-Nandagopal** 2021-09-22 07:04 UTC
Labels: Bug, Table Widget, Widgets, Critical, UI Building Pod, Needs Triaging
