### ISSUE TITLE
[Feature]: Make SSO Session Timeout Configurable

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#30807] opened 2024-01-31 16:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When using SSO to log in to Appsmith, a login session for a user is 30 days. 
Some users may want to be able to change this default session timeout to 1 or 2 days, for example. ([ZD ticket](https://appsmith3239.zendesk.com/agent/tickets/1413)).

### Why should this be worked on?

This feature would give Enterprise users the ability to configure and control the SSO session timeout.

**Comment by Nikhil-Nandagopal** [comment] 2024-02-02 06:42
This is a duplicate of #24455 so i'm closing it in favor of that

**Closed by Nikhil-Nandagopal** 2024-02-02 06:42 UTC
Labels: Enhancement, Team Managers Pod, SSO
