### ISSUE TITLE
[Bug]: Editable checkbox is not aligned with rest of the column checkboxes in Table widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15384] opened 2022-07-22 11:04 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When we D&D a Table widget to the canvas and bind it with a query, the checkbox next to the `Editable` property does not align with the checkboxes of other columns.

https://www.loom.com/share/d467f54dd72048e5b7f53055a5d7cb70

### Steps To Reproduce

1. D&D a Table widget.
2. Bind it with a query.

**Expected:** The checkboxes for the editable property should all be properly aligned.
**Actual:** Initially on binding the Table widget with a query for the first time, the checkbox next to the `Editable` keyword is misaligned. Once we refresh the page, the checkbox gets aligned automatically. 

### Version

Cloud

**Comment by utkarshkumarawasthi98** [comment] 2022-12-27 21:05
Hello, can you please assign this issue to me.

**Comment by somangshu** [comment] 2022-12-28 06:43
Hey @utkarshkumarawasthi98, I already assigned you another issue, If you can raise a PR there and then request to assign this, Ill do it

**Comment by utkarshkumarawasthi98** [comment] 2022-12-28 17:17
Can you please share the path of the files so that I can look into it, thanks.

**Comment by piyushpradhan** [comment] 2022-12-29 07:00
@somangshu if no one else is working on this issue, can you assign this to me ?

**Comment by somangshu** [comment] 2022-12-30 10:39
Greetings @piyushpradhan, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and request for a review here.

**Comment by piyushpradhan** [comment] 2022-12-30 10:41
Got it

**Comment by shadabbuchh** [comment] 2023-03-17 15:41
This is still reproducible from my end @rajatagrawal. Please have a look at the LOOM below:
https://www.loom.com/share/af704e6f180b45e5a9120937d206940c

**Note:** This issue only happens the first time you bind the Table widget with a datasource.

**Comment by siddheshJungade** [comment] 2023-03-26 02:50
Hey @somangshu if now is working on this can you please assigne to me ?

**Comment by somangshu** [comment] 2023-03-27 10:29
Greetings @siddheshJungade, thanks for showing interest 🎉, This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and let me know here!

**Comment by siddheshJungade** [comment] 2023-03-30 14:32
I have tried to setup codebase not able to setup mongo5 is not supporting on ubuntu 22.04 thats why appsmith container giving unhalthy response once setup if this issue still opens then you can assign to me.

**Comment by somangshu** [comment] 2023-03-31 08:30
@siddheshJungade this bug is related to the client side. You can ideally [use our release server](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server) for the backend instead of setting up your own server. Hope that resolves your problem

**Comment by iSatVeerSingh** [comment] 2023-03-31 14:18
can I work on it if this needs to be resolve?

**Comment by somangshu** [comment] 2023-04-06 09:46
Hey @iSatVeerSingh is you are still available, I am assigning this to you, I somehow missed the notification on your comments. 

@Souvik-223 apologies, Ill have to give @iSatVeerSingh at-least 24hrs before I can get back to you. Please checkout other issue that you might want to solve

**Comment by iSatVeerSingh** [comment] 2023-04-06 09:59
@somangshu Thanks for assigning me. But somehow I can't reproduce this anymore. Let me do some debugging if this issue bug is still present. I will let you know.

**Comment by somangshu** [comment] 2023-05-29 13:50
Hey @utkarsh-shrivastav77, Apologies missed the notification on this one
This issue is all yours, assigning it to you now. 
please raise the PR in the next 48hrs and let me know here so that I can take it forward.

**Comment by Vishrut19** [comment] 2023-06-13 06:18
Hey @utkarsh-shrivastav77! Are you working on it and do you need any help?

**Comment by utkarsh-shrivastav77** [comment] 2023-06-13 09:45
There is one problem i searched many files but could not figure it out how to change the editable the solution is change the particular css of editable.

**Comment by dilippitchika** [comment] 2023-06-13 11:39
@utkarsh-shrivastav77 feel free to pick some other issue if you are unable to fix this.

**Comment by Vishrut19** [comment] 2023-06-13 11:43
I can take up if it is okay ?

**Comment by dilippitchika** [comment] 2023-06-13 11:44
Sure @Vishrut19

**Comment by cookiejar2104** [comment] 2023-12-31 06:38
may i work on this issue? @somangshu

**Comment by somangshu** [comment] 2024-01-05 10:30
Greetings @dibyajyoti-mandal, thanks for showing interest 🎉, This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and let us know here.

**Closed** 2024-01-30 07:56 UTC
Labels: Bug, Good First Issue, Table Widget, App Viewers Pod, Low, Production, Table Widget V2
