### ISSUE TITLE
[Bug]: icon is not loaded in template also count mismatch with release and prod

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#25331] opened 2023-07-12 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. icon is not loaded properly in template information pane
2. Also template count is not same with release and prod

- icon not loaded - customer dashboard/marketing dashbord
<img width="1408" alt="Screenshot 2023-07-12 at 4 54 48 PM" src="https://github.com/appsmithorg/appsmith/assets/80756091/00592d0f-c2dd-4c8d-a76a-993302bc69db">
Relase count
<img width="984" alt="Screenshot 2023-07-12 at 5 01 11 PM" src="https://github.com/appsmithorg/appsmith/assets/80756091/6bb79a16-2fca-42a6-b0f4-db261dfab50f">
Prod count
<img width="984" alt="Screenshot 2023-07-12 at 5 01 32 PM" src="https://github.com/appsmithorg/appsmith/assets/80756091/39b733c9-b4f4-4000-baed-5e4e95e620e4">

### Steps To Reproduce

Click on template > and verify template information

### Environment

Release

### Version

cloud

**Comment by rahulbarwal** [comment] 2023-07-18 04:38
We have separate templates(databases) for release and prod. Hence the count is different.
Regarding icon not loaded. 
* Root cause: **The templates are using older widgets which stand deprecated, hence removed from codebase.**
* Solution: Replace the widgets with newer versions. 

We faced the same in prod and updated all the templates. This can be fixed in release as well, but it is a tedious task, and would stand low in priority for the team. 
Since this is not really a problem per se, we can ignore the icons on release. If you notice this on prod please notify us, we will fix that asap.
I am closing this for now. Let me know if you have any concerns.

**Closed by rahulbarwal** 2023-07-18 04:38 UTC
Labels: Bug, Low, Release, Needs Triaging, Templates pod
