### ISSUE TITLE
[Feature]: Keycloak OAuth2 Support

### ISSUE THREAD

**Issue by iocampomx** [appsmithorg/appsmith#8440] opened 2021-10-12 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a developer/system admin,
I want to integrate Keycloak OAuth2 for SSO
So that I can implement an enterprise grade authentication mechanism with appsmith

### Why should this be worked on?

"Keycloak is an open source identity and access management solution" very popular in the market.

It seems that several appsmith users would like to have this feature as mentioned in https://github.com/appsmithorg/appsmith/issues/2840.

**Comment by mohanarpit** [comment] 2021-10-12 12:09
I'm closing this as a duplicate of #2840

**Closed as completed by mohanarpit** 2021-10-12 12:09 UTC
Labels: Enhancement
