### ISSUE TITLE
[Bug]: Error message is observed when the user transfers the google sheet data in the table widget

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#15927] opened 2022-08-11 07:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When table widget is connect to the canvas this error is displayed "The value at primaryColumns.action.buttonColor is invalid
This value does not evaluate to type ^(?![<|{{]).+
{
"primaryColumns.action.buttonColor":"{{Table1.processedTableData.map((currentRow, currentIndex) => ( appsmith.theme.colors.primaryColor))}}"
}" on the screen and once the page is refreshed it goes off.

https://user-images.githubusercontent.com/93259714/184080743-a3c204c7-01f9-406b-a4ae-0faa20e33c76.mp4

![chrome_VCg5Q4NCoO](https://user-images.githubusercontent.com/93259714/184081024-3260d967-4c85-45e8-9a2c-f25e5eaeff42.png)
![chrome_UPEyW4Xa9O](https://user-images.githubusercontent.com/93259714/184081158-4f6e41fd-b853-41fc-8f0d-914195c2f3ed.png)

### Steps To Reproduce

1. Go to url:- https://release.app.appsmith.com/
2. Click on '+' icon on QUERIES/JS and select 'Sheets Query'
3. Select the Google sheets showed in the dropdown and fill other fields.
4. Click on the 'Run' button and execute the query
5. Now from right hand 'Connect Widget' menu select 'Table' widget 
6. Navigate back to canvas and observe the error 

**Note:- The error disappears once the user refreshes the page.**

### Version

Cloud - 1.7.13

**Comment by dilippitchika** [comment] 2022-10-25 10:39
Duplicate of #14527

**Closed by dilippitchika** 2022-10-25 10:39 UTC
Labels: Bug, Table Widget, App Viewers Pod, Needs Triaging, App Theming, medium
