### ISSUE TITLE
[Feature] Only Date option

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3516] opened 2021-03-12 09:08 UTC
## Summary

We need a way to allow users to enter only the date in the datepicker.

## Motivation
Today, the Datepicker allows users to enter the date and time. This becomes inconvenient in use-cases where only the date is needed. We need an option to disable time from the datepicker

## Additional Context
- The DatePicker property pane should have a toggle to enable time in the datepicker (disabled by default)
- The format options should show formats with time (when time is enabled), and without time (when time is disabled)
- Migrate existing widgets to have this property enabled.

**Comment by somangshu** [comment] 2021-04-12 11:20
#3345 date range picker & #3346 time picker widget are related to this.

**Comment by somangshu** [comment] 2021-05-25 06:02
@wmdev0808 
Note:

- The datepicker property pane will have a new option `Enable time : boolean`.
- The property `Enable time` is `true` by default.
- When `Enable time` is `false`
    - The Default date format changes to `YYYY-MM-DD`
    - The datepicker popover (on widget and property pane) hides the time option
    - In the date format dropdown, remove all time format options
    - The `min date` & `max date` properties also need to have the same behaviour  
- When `Enable time` is `true`
    - The Default date format changes to `YYYY-MM-DD HH:mm`
    - The datepicker popover (on widget and property pane) shows the time option
    - In the date format dropdown, show all time format options
    - The `min date` & `max date` properties also need to have the same behaviour

**Comment by somangshu** [comment] 2021-05-28 05:16
Since the date string by default is ISO string which consists of the timezone, the date might erratically change for +/- GMT. The solution around this needs to the thought of properly.

**Comment by somangshu** [comment] 2022-01-05 09:03
@dilippitchika It was pointed out to me by @wmdev0808 that these changes are conflicting to what @techbhavin implemented in #9423, I checked the implementation and he is right, Now that we have the time precision control for the dev, the problem is solved for the end user and the onus is on the dev to set the correct format required in the api/query. 

We dont need the changes planned here anymore. I am closing this.

**Closed by somangshu** 2022-01-05 09:03 UTC
Labels: Enhancement, Date Picker Widget, App Viewers Pod, UI Building Pod, community
