### ISSUE TITLE
[Bug] "Reset Form on Success" field - resets even on Error

### ISSUE THREAD

**Issue by pric-appsmith** [appsmithorg/appsmith#1888] opened 2020-11-24 10:49 UTC
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add a new page
2. Add a form on the page
3. Add some input fields on the form
4. Set the submit button's `Reset Form on Success` field to true by toggling to Green
5. Connect the submit button to a DB Query that will always fail
6. Deploy the app
7. View App
8. Fill the form
9. Click Submit
10. You'll see error pop-ups and YET the form gets reset

 
![chrome-capture (1)](https://user-images.githubusercontent.com/72548460/100084357-adadde80-2e70-11eb-80d2-b6a93f636633.gif)

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

**Comment by Nikhil-Nandagopal** [comment] 2020-11-24 11:07
duplicate of #820

**Closed by Nikhil-Nandagopal** 2020-11-24 11:07 UTC
Labels: Bug
