### ISSUE TITLE
[Bug]: Auto complete text displays outside of the Mustache binding on DB/Sheet Queries

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#16087] opened 2022-08-17 07:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While adding a mustache binding into DB queries of Google sheet queries, the auto complete text displays outside of mustache in a weird way

https://www.loom.com/share/316ad3fe1cea46e3b7d74069731adcb3

<img width="932" alt="Screenshot 2022-08-17 at 12 33 13 PM" src="https://user-images.githubusercontent.com/95341241/185056440-4bcf8292-82e6-4a9c-98c3-91971bcdc30a.png">

### Steps To Reproduce

1. Create a Google Sheet/DB query
2. use mustache binding on query page. Like {{Table1.triggeredRows}}
3. Instead of typing it all, use auto-complete to see the issue
4. Observe that text you selected from suggestion list displays outside of bracket

### Version

Cloud / Release

**Comment by Nikhil-Nandagopal** [comment] 2022-08-19 08:33
Seems to be a duplicate of #16141

**Closed by Nikhil-Nandagopal** 2022-08-19 08:33 UTC
Labels: Bug, High, Release, Autocomplete, regression, Needs Triaging, MySQL, Google Sheets, FE Coders Pod, BE Coders Pod, Postgres
