### ISSUE TITLE
[BUG] Redirect start-https.sh script to local Java servers instead of staging servers.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#818] opened 2020-09-30 11:12 UTC
## Description
On registering new `email` and `password` with no `smtp` credentials at `dev.appsmith.com`, the user is receiving an email from `hello@appsmith.com`.

<a href="https://ibb.co/7yJQ8Hw"><img src="https://i.ibb.co/Yj7XY6z/SignUp.png" alt="SignUp" border="0"></a>

<a href="https://ibb.co/sVkDtwG"><img src="https://i.ibb.co/Tgpnr8S/temp-email.png" alt="temp-email" border="0"></a>

<a href="https://ibb.co/ngD67mL"><img src="https://i.ibb.co/TvHY42g/temp-email-content.png" alt="temp-email-content" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment] 2020-10-01 06:55
@mohanarpit not so sure about this. What stops a user from creating fake emails on prod and causing the same problem? Changing the server URL won't help this

**Comment by mohanarpit** [comment] 2020-10-01 06:59
@Nikhil-Nandagopal That's a different problem. During dev time, we almost always end up using a dummy email ID for testing. It's a lot more prevalent in dev scenarios than in production. 

Also, getting the dev setup to be completely independent of any hosted service is the ideal goal. As a developer, I should be able to get up & running with the Appsmith codebase independently on my machine and not rely on an internet connection to develop.

**Comment by Nikhil-Nandagopal** [comment] 2020-10-01 07:46
Then it seems like different problems to solve. Frontend devs will value a hosting server and we can assume goodwill there. If we want to protect our email reputation let's solve that correctly.

**Comment by ps-19** [comment] 2021-10-04 04:38
@mohanarpit @Nikhil-Nandagopal Can you specify the procedure to recreate issue in little more detail?
Thanks

**Comment by mohanarpit** [comment] 2021-10-04 04:42
@ps-19 Apologies. This issue is a duplicate of #1231 and has already been resolved.

**Closed by mohanarpit** 2021-10-04 04:42 UTC
Labels: Bug, Low

**Comment by ps-19** [comment] 2021-10-04 05:26
@mohanarpit can you suggest me some very beginner friendly issue to work on.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-04 07:08
@ps-19 please have a look at our (Contribution Guide)[https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md]
