### ISSUE TITLE
[Bug]: Git Import Issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10950] opened 2022-02-08 05:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- [x] The invalid author name error is displayed when a user tries to import the file from git
- [ ] If the User import the app from instance 1 to instance 2 then the warning or error message should be displayed
- [x] When the user imports the application there should not be any uncommitted changes displayed on the commit icon-->fixed
- [x] Instead of showing available and missing data sources as a 2 section show it as one -->fixed
- [x] Inside the reconnect flow pop up The dropdown seems to be very big and the dropdown which opens up is very small-->Fixed
- [x] The text “Port” alignment is broken -->not Fixed
- [x] When the user enters the details and without clicking on save if we change the page the details will be erased-->Fixed
- [x] The reconnect application button is missing in the data source tab when the user skips filling the data source details-->fixed
- [x] Even the data source is available in the org still the data source details are asked to fill when user import the app
- [x] There should not be a scroll when the reconnect datasource modal opens for the first time->Fixed
- [x] When the user import the app the reconnect datasource modal is not displayed the user is directly taken to the application->Fixed
- [x] When the user click on authenticated API " OOPS something went wrong" page is displayed-->Fixed
- [x] When the user has deleted the old app from org and now the org is empty and try to import the application the old datasources will be displayed which is very confusing-->Fixed
- [x] Once we authorize the gsheet the user will be navigated to application instead of authorizing the other datasources
- [x] when user addthe Database detailes and click on save the user should be navigated to next datasource page instead of showing API (same page remaining now @haojin111 )
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/153386986-8a737813-68b6-4e4b-a94f-cf2b3f29f7cb.png">

- [x] When the user adds the credentials and try to test it the plugin failed error is displayed 
![image](https://user-images.githubusercontent.com/45958978/153387997-1a45cf60-0102-4e1a-ada0-54923ae2f9bb.png)

- [x] The redirection fails when we authorize the google sheet datasource
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b265f2cbecb1431f83bbc35bb9c5d275-00001.gif)](https://www.loom.com/share/b265f2cbecb1431f83bbc35bb9c5d275)

- [x] The save button is not enabled even when all the data fields are filled
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d5b4494c25d943b0bb6dbf7bed43433e-00001.gif)](https://www.loom.com/share/d5b4494c25d943b0bb6dbf7bed43433e)

- [x] If we add the 3 database detailed out of 4 from reconnect database modal and skip to application the remaining datasource doesnt display the reconnect button
- [x] The s3 details displayed in the reconnect datasource pop up is wrong
- [x] when user hover on the skip application button the tooltip message should change as per new changes

### Steps To Reproduce

New feature issues

### Environment

Deploy Preview

### Version

Cloud

**Comment by RakshaKShetty** [comment] 2022-02-16 17:32
Ux related issues

- [ ] The look and feel of the import modal is not same as figma
- [ ] The hand icon should not be displayed when there is no hover in the import modal
- [ ] The reconnect datasource pop up should be displayed without a scroll
- [ ] The Left pane and the header section should be sticky and  only the datasource details should be scrollable
- [ ] The connection text should be Parallel to the first data source name

**Comment by RakshaKShetty** [comment] 2022-02-22 09:54
1.The Import from file icon is broken in import application modal
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/155093018-b83091ee-b29f-4b23-99d1-6618725330e4.png">
2.when user import json application the reconnect application button is displayed
3.If there are 2 datasource that needs to be authenticated and if the user authenticated one datasource the other datasource is marked as authenticated in the reconnect datasource Modal

**Comment by AnaghHegde** [comment] 2022-02-23 07:06
> * [x]  The Import from file icon is broken in import application modal
 This is fixed.
> * [ ]  when user import json application the reconnect application button is displayed
 We are following the same design and hence we should show the reconnect modal right?
> * [ ]  If there are 2 datasource that needs to be authenticated and if the user authenticated one datasource the other datasource is marked as authenticated in the reconnect datasource Modal
I am not able to replicate this.

**Comment by RakshaKShetty** [comment] 2022-02-23 11:08
when user import json application the reconnect application button is displayed
We are following the same design and hence we should show the reconnect modal right?->but anagh the the query runs without reconnecting this gives a wrong impression rite

**Comment by AnaghHegde** [comment] 2022-02-23 12:54
@RakshaKShetty The appJson file you have imported does it have datasource config already present? Because in the new flow we are not exporting the credentials for file export. Could that be the reason you are observing this ?

**Comment by AnaghHegde** [comment] 2022-02-28 04:47
Ignore the newly introduced fields as part of git import while committing to git repo @AnaghHegde

**Comment by haojin111** [comment] 2022-03-01 08:02
- [ ] 1.The delete button should be removed from reconnect database modal ->Must Fix
- [ ] 2.when user click on save button the user should be navigated to next database ->Must Fix
- [ ] 3.when user add all the detailes the user should be navigated to application page ->Must Fix
- [ ] 4. The reconnect datasource pop up should be displayed without a scroll->Low
- [ ] 5.The look and feel of the import modal is not same as figma->Low
- [ ] 6.The connection text in recoonect database modal should be Parallel to the first data source name->low
- [ ] 7.when user import json application the reconnect application button is displayed- insid ethe application under action tab>Must Fix
- [ ] 8.If there are 2 datasource that needs to be authenticated and if the user authenticated one datasource the other datasource is marked as authenticated in the reconnect datasource Modal->Must Fix
- [ ] 9. The text “Port” alignment is broken->Low
- [ ] 10.The invalid author name error is displayed when a user tries to import the file from git->Issue exits only sometime
Changes asked by nikhil last time :
- [ ] 1.After entering credentials and clicking save next unConfigured datasource should be selected and if none show a toast and redirect->Must Fix
- [ ] 2.Design : DB Name should be at top->Must Fix
- [ ] 3.when user enter the db detailes and navigate to next datasource if he comes back to edit the same datasource again teh edit page should be kept as it is instead of showing "These datasources were imported successfully!” Message->Must Fix

**Comment by RakshaKShetty** [comment] 2022-03-03 09:27
- [ ] In the reconnect datasource pop up  when the user click on Airtable for authentication the application breaks
- [ ] When user clicks on test button it should just check the config is correct or not instead it navigate user to the next data source connection section

**Comment by hiteshjoshi** [comment] 2022-03-04 08:42
@AnaghHegde to raise PR for last three items above comment.

**Comment by AnaghHegde** [comment] 2022-03-05 07:12
Closing this as all the issues listed are fixed. We can track the issue found in regression in a different ticket as this is getting bulky.

**Closed by AnaghHegde** 2022-03-05 07:12 UTC
Labels: Bug, QA, Needs Triaging, Platform Pod, Git Version Control, Team Managers Pod
