### ISSUE TITLE
[Bug]: Promises don't work unless returned from a function body

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9782] opened 2021-12-15 06:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Use `showAlert()` inside a `.then` or `.catch` and observe that the trigger does not take place unless another `showAlert()` is present outside the promises structure.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/de5143ea6db9487ca4f0c607201f1c96-00001.gif)](https://www.loom.com/share/de5143ea6db9487ca4f0c607201f1c96)

### Environment

Deploy Preview

### Version

Cloud

**Comment by Rishabh-Rathod** [comment] 2022-01-11 17:58
This seems to be working for me, can you help re-producing this or share an app link where this can be reproduced. @ramsaptami

**Comment by ramsaptami** [comment] 2022-01-12 06:08
Related to issue #10150 where `return` keyword needs to be used for promises to work.

**Comment by ramsaptami** [comment] 2022-01-12 06:13
Repro steps -->
https://www.loom.com/share/cbdc803c0ff2470b8e8458fa713e4fca

**Comment by Nikhil-Nandagopal** [comment] 2022-02-02 10:08
We discussed 2 approaches to this problem
- Extend the promise class and overwrite the then method so that we know the chain of promises to wait for
- Add a custom Lint rule to inform users that they must return the promises in an async function

**Comment by hetunandu** [comment] 2022-02-22 10:44
This issue is to do with the confusion regarding returning of promises. Hence renaming it.

**Comment by Rishabh-Rathod** [comment] 2022-04-05 13:47
As we have already added docs for promises mentioning about returning of promise is needed in Appsmith here - https://docs.appsmith.com/core-concepts/writing-code/javascript-promises#promise-methods

Can we close this issue @hetunandu

**Comment by Nikhil-Nandagopal** [comment] 2022-04-06 18:04
We also need to solve this without docs

**Comment by Rishabh-Rathod** [comment] 2022-04-16 09:01
Moving this issue from `Needs Doc` to `product backlog` as we already have documentation and aim to fix the core issue.

**Comment by ramsaptami** [comment] 2022-04-18 05:51
Needs a lint rule implemented around the usage of `return` keyword

**Comment by Nikhil-Nandagopal** [comment] 2022-04-20 06:25
More than lint, can we just solve this properly so we don't need a return statement?

**Comment by Rishabh-Rathod** [comment] 2022-04-20 06:50
> More than lint, can we just solve this properly so we don't need a return statement?

We might need a discussion around this. 

#### Why do we need to return promises?
 
To explain the need for returning promises, let me take an example of `ButtonWidget`. 

In ButtonWidget, we need to know when did the onClick JS execution completed to stop the internal `isLoading` state of the button. 

For this, we rely on promise resolution, when we receive a promise from JS execution.

- Case 1: The button shows loading until Api1 is executed.
```js
onClick = {{Api1.run(() => { Api2.run() })}}
```

- Case 2: The Button shows loading until Api1 & Api2 are executed.
```js
onClick = {{Api1.run(() => { return Api2.run() })}}
```

- Case 3: The Button shows loading for a small time. ( No relation with API execution )
```js
onClick = {{
function(){ 
Api1.run(() => { return Api2.run() })
}()
}}
```

If we have a Button widget `IsLoading` property where users explicitly mention when they want button in loading state.
We could remove the dependency of the `IsLoading` state with promise resolution and the user can skip the `return`.

**Comment by bharath31** [comment] 2022-08-19 09:53
While we continue to work on a long-term fix for this issue, a linter warning would prevent users from running into long debugging loops. 

@ApekshaBhosale here's a linter warning message we can show when a callback syntax is detected: 
```
Expected 'return' for callback to succeed
```

**Closed** 2022-10-31 04:34 UTC
Labels: Bug, High, Production, FE Coders Pod, JS Promises
