### ISSUE TITLE
[Bug]The red dot is displayed on the comment icon even when there are no new comments

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7788] opened 2021-09-24 06:20 UTC
## Description 

The red dot is displayed on the comment icon even when there are no new comments

### Steps to reproduce the behaviour:

1. log in as a user 1 
2. create an app1 add a comment tagging user 2
3. Create one more app under the same org don't add any comment
4. now login as a user2 
5. launch the app2 where there is no comment added
6. Now you can see a red dot on the comment icon
7. click on the comment icon 
8. There are no comments added
![image](https://user-images.githubusercontent.com/45958978/134627358-d928ac6a-02c4-4429-abaf-5f4dbb5052a9.png)

### Important Details

- Version: [Cloud]
- OS: MacOS
- Browser chrome
- Environment production

**Comment by rishabhsaxena** [comment] 2021-09-24 09:06
Closing this for now, since it was caused after logging out and logging back in, which we're not solving currently.
@RakshaKShetty if you get a chance please try we can reproduce this in any other way just to be sure

**Closed by rishabhsaxena** 2021-09-24 09:06 UTC
Labels: Bug, Production, Needs Triaging, Platform, Collaboration
