### ISSUE TITLE
[Bug]: Mustache brackets don't show up in bold when used on a new line

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9015] opened 2021-11-05 10:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mustache brackets do not show up in bold if closing brackets are on a new line

![image](https://user-images.githubusercontent.com/79509062/140497452-19eb45e1-b1da-4f81-ae7a-6cd3baf3b68b.png)

![image](https://user-images.githubusercontent.com/79509062/140497743-f81c2d31-c4cd-42b6-bdaf-a1cc220112ca.png)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/aaf60d6595024a3b865b6f8dbf4a2c3a-00001.gif)](https://www.loom.com/share/aaf60d6595024a3b865b6f8dbf4a2c3a)

### Steps To Reproduce

1. Go to widget property pane and type in mustache brackets with code and move the closing brackets to a new line. Repeat this by deleting the closing braces and causing an error within the code to observe this.

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment] 2021-11-05 12:06
Mismatched brackets on trigger field
![image](https://user-images.githubusercontent.com/79509062/140507825-6163ac16-e089-44da-9baf-e004c1d882e2.png)

**Comment by Nikhil-Nandagopal** [comment] 2021-11-10 12:38
Duplicate of #7113

**Closed by Nikhil-Nandagopal** 2021-11-10 12:38 UTC
Labels: Bug, Actions Pod, JS, Low, Release, FE Coders Pod
