### ISSUE TITLE
[Bug]: Cannot connect to Google Sheets because authorization fails `Internal server error while processing request `

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#18211] opened 2022-11-16 19:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The attempt to create a new data source from Google Sheets fails when trying to authorize access this happens only in the self-hosted version

[Performance Logs](https://www.udrop.com/7ymE/GoogleSheets.json)

https://user-images.githubusercontent.com/114161539/202267282-15bb7c7a-2f7e-4d2e-9c40-5b3e7f2a432d.mp4

### Steps To Reproduce
To reproduce the Google sheets error, follow these steps

1. If you previously had an instance of appsmith, cleared its cache, you have to create a new instance

`Warning everything you have in your self-hosted will be deleted.`

```console
docker ps -a
docker stop <<AppsmithContainerID>>
docker rm <<AppsmithContainerID>>
ls
sudo rm -rf stacks
docker-compose up -d
```

https://user-images.githubusercontent.com/114161539/204024361-ae33b098-7bc1-440d-9db5-c0f55c15bca9.mp4

2. Once you have re-run self-hosted create a new application.
3. Try adding a Google Sheets data source.
4. Try to authenticate the Google sheets data source, and you will see the error.

### Version

Self hosted: Appsmith Community v1.8.8 
Self hosted: Appsmith Community v1.8.6

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5upl8)

**Comment by felix-appsmith** [comment] 2022-11-25 16:22
Update the steps to follow to reproduce this issue

**Comment by sumitsum** [comment] 2022-11-28 21:40
Investigated this issue and found that the issue occurred because the self hosted instance was not able to register itself with the cloud services. This issue has been already addressed by [this PR](https://github.com/appsmithorg/appsmith/pull/18440/files) raised by @nidhi-nair . Moving this issue to QA for verification. 

Steps shared by @felix-appsmith and tested by me to reproduce the issue on my local setup: 
- docker system prune -a
- docker rmi $(docker images | grep 'appsmith')
- curl -L https://bit.ly/3AQzII6 -o $PWD/docker-compose.yml 
- docker-compose up -d

**Comment by prapullac** [comment] 2022-11-30 09:25
Closing the issue after testing it on the release as I was unable to repro the issue

**Closed by prapullac** 2022-11-30 09:25 UTC
Labels: Bug, Critical, High, Needs Triaging, Google Sheets, BE Coders Pod, Integrations Pod
