### ISSUE TITLE
[Bug]: Hiding rows in the table widget is not working properly.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#24765] opened 2023-06-22 17:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click the hide button on a row in the table widget, it appears to be hidden. However, if I scroll to the left, the hidden row is still visible. Additionally, if I collapse and expand the widget again, other users can see the previously hidden rows.

![image](https://github.com/appsmithorg/appsmith/assets/114161539/2ab9f491-a0de-4555-bbd9-f02f5abb62c7)
![image](https://github.com/appsmithorg/appsmith/assets/114161539/1d7526c1-82e3-46f4-a037-af9d2fa0ac31)

### Steps To Reproduce

1. Create a table.
2. Hide a row in the table.
3. When you hide a row, scroll to the left.
4. You will see the hidden row if you click on `deploy` (presumably referring to expanding or refreshing the view). The hidden row will also be visible in that state.

In this thread on Frontapp, the user shared a video demonstrating the behavior: https://app.frontapp.com/open/cnv_118pl0gc?key=FxvAklMRJ5GwjQLEagVhcktQGKfEFUvD

### Environment

Production

### Version

Cloud/ Self-Hosted Appsmith Community v1.9.22

**Comment by dilippitchika** [comment] 2023-06-23 03:17
Happens only in the preview or edit mode. Duplicate of https://github.com/appsmithorg/appsmith/issues/15639

**Closed by dilippitchika** 2023-06-23 03:17 UTC
Labels: Bug, Tab Widget, App Viewers Pod, Needs Triaging
