### ISSUE TITLE
[Bug]: No horizontal scroll for the Settings tab of a JS Object

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31584] opened 2024-03-07 09:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We do not see the complete content inside the Settings tab of a JS Object in the split mode. And hence a horizontal scroll is required which os currently missing blocking the user from seeing the whole content.
<img width="652" alt="Screenshot 2024-03-06 at 10 14 17 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/48a2c205-cc40-486c-abdf-10f2c63c2337">

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. Create a JS Object inside an app.
3. Go to the settings tab.

**Expected:** A horizontal scroll should be present that enables the users to see the whole content.
**Actual:** Horizontal scroll is not present.

### Environment

Release

### Severity

High (Blocker to building)

### Version

Cloud

**Comment by hetunandu** [comment] 2024-03-13 11:31
Duplicate of #31716

**Closed by hetunandu** 2024-03-13 11:31 UTC
Labels: Bug, High, Release, Needs Triaging, New Developers Pod, IDE Navigation, PR blocker
