### ISSUE TITLE
[BUG] Login POST URL throws "Whitelabel Error Page"

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#804] opened 2020-09-30 07:13 UTC
## Description

When I tried calling the URL directly in the browser, it throws a Whitelabel Error Page instead of invalidating the request itself and redirecting the user back to the login page or the app home page. 

### Steps to reproduce the behaviour:

Request URL (s): [https://app.appsmith.com/api/v1/login](https://app.appsmith.com/api/v1/login), [https://app.appsmith.com/api/v1/logout](https://app.appsmith.com/api/v1/logout)
Request Type: GET
Error: [http://prntscr.com/uonq1e](http://prntscr.com/uonq1e)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Brave (Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit))

**Comment by mohanarpit** [comment] 2020-10-02 08:14
This is not a bug but an enhancement. The error is correct because you're trying to access an API endpoint that doesn't exist. The server should send back a better designed error page with a button to redirect the user to Appsmith's home page.

I'm marking this as an enhancement instead of a bug because the behaviour we are seeing is expected.

**Comment by Nikhil-Nandagopal** [comment] 2020-10-02 08:17
Shouldn't it be 404 if it doesn't exist?

**Comment by mohanarpit** [comment] 2020-10-02 08:19
@Nikhil-Nandagopal The server is returning a 404. The screenshot attached to the issue is the default HTML page that Spring framework returns for any error. If you see closely, the status in the error page is also "404 Not Found"

**Closed** 2020-10-15 12:17 UTC
Labels: Backend, Enhancement, Low

**Comment by prapullac** [comment] 2020-10-22 10:07
Verified the issue and works good for me
