### ISSUE TITLE
[Bug]Navigate to function is not working in Table widget for "On Page Change" 

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#1183] opened 2020-10-14 05:34 UTC
Pre-requisite

Make sure you have 2 pages, in one page make sure you have a table widget.

1. In table widget make sure you have 2-3 page data.
2. Then in Table widget properties "onPageChange" try to Navigate to another page say "Page2".
3. In table click on next page.

## Observation

On click of next in table navigation is not happening to other page

## Expected behaviour

On click of next in table navigation to the page mentioned in the widget should happen

**Comment by Nikhil-Nandagopal** [comment] 2020-10-14 05:55
closing as duplicate of #731

**Closed by Nikhil-Nandagopal** 2020-10-14 05:55 UTC
Labels: Actions, Bug, Frontend, High, Table Widget
