### ISSUE TITLE
MongoDB DS Save internal Server Error

### ISSUE THREAD

**Issue by PiyushPushkar02** [appsmithorg/appsmith#21598] opened 2023-03-20 12:14 UTC
The following issue is observed while saving the MongoDB data source.

Steps to recreate:
1. Configure a MongoDB data source.
2. Set the default database name as some value.
3. Set the database name under the authentication section as empty.
4. while saving the data source an internal server error is observed. 

![Screenshot 2023-03-20 at 5.43.42 PM.png](https://images.zenhubusercontent.com/637b06255553bbc156f20882/9f8a2d4c-7eae-4451-ae04-3a918b17c707)

![Screenshot 2023-03-20 at 5.43.34 PM.png](https://images.zenhubusercontent.com/637b06255553bbc156f20882/5f79891f-0d20-4d15-8885-fbdf475f3cc3)

**Comment by sumitsum** [comment] 2023-03-21 06:52
Closing it as the issue is not reproducible on release or local setup.

**Closed by sumitsum** 2023-03-21 06:52 UTC
