### ISSUE TITLE
[Bug]: Currency widget inside Form is not seen as part of the .data object

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#33930] opened 2024-06-03 11:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you add a currency widget inside a Form, its value is not accessible inside the `Form1.data`.
All other input widgets are accessible via Form1.data, except for the Currency widget.

### Steps To Reproduce

1. Add a Form widget onto the canvas
2. Drag and drop a currency widget inside it.
3. Enter some value inside the currency widget.
4. Now introduce a text widget, and bind the `{{Form1.data}}` to it.

You will see that the Form1.data is empty and there is no parameter itself with the Currency widget name and its value.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud / Self Hosted 1.26

**Comment by rahulbarwal** [comment] 2024-07-12 09:13
@tomjose92 We tried this on app.appsmith.com and were unable to reproduce. Can you share a recording of this? I want to make sure we are not missing anything.

**Comment by Nikhil-Nandagopal** [comment] 2024-07-12 11:08
Yeah not able to reproduce this either. Let's close it

**Closed by Nikhil-Nandagopal** 2024-07-12 11:08 UTC
Labels: Bug, App Viewers Pod, Low, Production, Form Widget, Cannot Reproduce Issue, Needs Triaging, Currency Input Widget, Widgets & Blocks Pod, Inviting Contribution
