### ISSUE TITLE
[Bug]-[31]:Cursor should be on the input once user selects country code on phone widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11506] opened 2022-02-28 13:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cursor should be on the input when user selects country code instead of an additional step of clicking inside the search bar

### Steps To Reproduce

1. Drag and drop a phone widget on to the canvas and change the country code
2. Observe that an additional step of clicking on the input is necessary to search for a country code

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-03-03 17:55
Also for currency input widget

**Comment by somangshu** [comment] 2022-04-19 13:47
## Stats 
| Stat | Values | 
| ------------- | ------------- | 
| Reach | 31 | 
| Effort (months) | 0.5 |

**Comment by YuriDevAT** [comment] 2022-10-05 17:03
Hi. I would like to work on this issue.

**Comment by AkkiBond** [comment] 2022-10-12 10:40
Hi, Can I work on it?

**Comment by dilippitchika** [comment] 2022-10-12 11:29
Hi @YuriDevAT @AkkiBond thanks for showing interest. 
Assigning this to both of you for now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by MuhammadAakash** [comment] 2023-01-26 15:44
@dilippitchika 
if this issue is also not completed, I would like to work on this too.

**Comment by ramsaptami** [comment] 2023-01-27 10:28
Since there's been no activity on this, I'll assign this to you @MuhammadAakash Please feel free to pick this up

**Comment by MuhammadAakash** [comment] 2023-01-27 11:27
Thanks @ramsaptami 
I will look into this issue after setting up the project.
One more thing can you please share the details that what are the steps to set up the project on Ubuntu(Linux).
Thanks.

**Comment by MuhammadAakash** [comment] 2023-01-28 10:41
Thank you @ramsaptami

**Comment by ramsaptami** [comment] 2023-02-14 04:29
@MuhammadAakash please take it up

**Comment by iSatVeerSingh** [comment] 2023-04-04 14:35
Can't reproduce this issue.

**Comment by somangshu** [comment] 2023-04-06 09:45
Thanks @iSatVeerSingh 🙏

**Closed by somangshu** 2023-04-06 09:45 UTC
Labels: Bug, Good First Issue, UX Improvement, hacktoberfest, App Viewers Pod, Low, Release, Papercut, Currency Input Widget, Phone Input Widget
