### ISSUE TITLE
[Bug]: When we bind widgets to itself App crashes - Only error in prod

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#17091] opened 2022-09-27 10:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to bind the widgets with itself, we are observing an App crash, and in prod we are seeing only an error as below.

![image](https://user-images.githubusercontent.com/104895602/192495109-dbceb03c-9c2e-45ee-9cb5-d9beabc710cb.png)

### Steps To Reproduce

1. D&D any widgets like checkbox, radio, switch etc.,
2. In any JS toggle of any property of that widget, Hard code widget's name as for example Checkbox1 
3. Observe app crash

Expected: Cyclic dependency error to be displayed.

### Version

Release

**Comment by bharath31** [comment] 2023-03-16 12:06
Closing this since this is not reproducible

**Closed by bharath31** 2023-03-16 12:06 UTC
Labels: Bug, JS Evaluation, Release, Regressed, Cannot Reproduce Issue, FE Coders Pod
