### ISSUE TITLE
[Feature]: Ability to freeze columns in table widget

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11657] opened 2022-03-07 03:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A way to lock/freeze columns so that when you scroll horizontally through the rest of the table the locked columns stay put on the screen.

### Why should this be worked on?

It'd be very useful when there are many columns in the table and you need some columns to be always visible on the screen. Like pinning columns on ag-grid - https://www.ag-grid.com/javascript-data-grid/column-pinning/

Asked by discord user - https://discord.com/channels/725602949748752515/760761686549463060/950217151627808799

**Comment by dilippitchika** [comment] 2022-03-07 04:56
Duplicate of https://github.com/appsmithorg/appsmith/issues/3265

**Closed by dilippitchika** 2022-03-07 04:56 UTC
Labels: Enhancement
