### ISSUE TITLE
[Feature]: navigateTo action needs autocompletion to pages

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#8558] opened 2021-10-15 13:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

`navigateTo` action needs autocompletion where it suggests the pages existing in the application. We do a similar thing in the case of `showModal` or `closeModal`

### Why should this be worked on?

Most common use case for `navigateTo` is to navigate between application pages. Bringing in autocompletion makes this process easier.
[Here](https://discord.com/channels/725602949748752515/760761686549463060/898554522526449735)'s a place where one of our users was expecting this.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-17 09:11
Duplicate of #1033

**Closed by Nikhil-Nandagopal** 2021-10-17 09:11 UTC
Labels: Enhancement, Actions Pod, App Viewers Pod, UI Building Pod, FE Coders Pod, App Navigation
