### ISSUE TITLE
[Bug]: Table widget on sorting columns throws error when onSort event is configured

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#13726] opened 2022-05-10 13:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7e3ac6389fd8484eb0f82934e8845a60-00001.gif)](https://www.loom.com/share/7e3ac6389fd8484eb0f82934e8845a60)

### Steps To Reproduce

1. Add table widget onto canvas
2. Use onSort Event to display sorting order from property pane. eg: {{showAlert(Table1.sortOrder.order)}}
3. click on the table columns header to start sorting
4. click for 3 time and observe the error message

### Version

Cloud/ Production

**Comment by dilippitchika** [comment] 2022-05-12 05:45
Hey Chandan, the 3rd click removes sorting that is the reason why it sends null as the order and doesn't send ascending or descending. Closing this as this is expected behavior.

**Closed by dilippitchika** 2022-05-12 05:45 UTC
Labels: Bug, Table Widget, App Viewers Pod, Production, UI Building Pod, Needs Triaging, medium
