### ISSUE TITLE
[Bug]: Multiselect doesn't work in Table V2

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15306] opened 2022-07-19 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiselect doesn't work in Table V2
https://www.loom.com/share/9e3fba45c8644e0cb172de4e168607fe

### Steps To Reproduce

1. Drag and drop the table
2. bind it with a data
3. now make all row as editable
4. now bind the event for save button
5. enable multiple select from property pane
6. check multiple row
7. now edit the any row and click on save
8. The multi-select is disabled by default

### Public Sample App

https://release.app.appsmith.com/app/tablev2/table-62d515c1600c9c6f0b73b23f/edit?branch=master#pr3etjol9t

### Version

release

**Comment by dilippitchika** [comment] 2022-08-16 06:41
Hey Raksha, apologies for the delayed response, both selection and editing solve 2 different problems here. 
If you refresh the table data row selection will get cleared. I think onSave success is refreshing the table data.

**Comment by dilippitchika** [comment] 2022-08-24 07:18
@RakshaKShetty can you confirm if this happens when primary key is added? Because i wasn't able to reproduce this with primary key set.

**Comment by dilippitchika** [comment] 2022-09-01 10:43
Closing this

**Closed by dilippitchika** 2022-09-01 10:43 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, Release, Needs Triaging
