### ISSUE TITLE
[Bug]:  APPSMITH_INSTANCE_NAME is not escaped when being stored in docker.env. Can result in entrypoint.sh failure.

### ISSUE THREAD

**Issue by paulcoates** [appsmithorg/appsmith#14659] opened 2022-06-18 04:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I changed the name of my appsmith instance in the web interface to something with a space in it. For example "XYZ Group".  When starting the container, the entrypoint.sh bash script is fails due to space in the string with the following error.
```
Initialize .env file
Load environment configuration
/appsmith-stacks/configuration/docker.env: line 92: Group: command not found
```
Expected behaviour is that container is able to start without error.

Resolution was to edit docker.env

### Steps To Reproduce

1.  Deploy appsmith
2. Login as supervisor and go to admin settings.
3. Change instance name to "XYZ Group".
4. Press "save and restart". 
6. After restart, stop the docker container.  `docker stop appsmith`
7. Start container `docker start appsmith`

### Version

Self-Hosted ee - 1.7.4

**Comment by tomharvey** [comment] 2022-06-21 09:49
This seems like a duplicate of https://github.com/appsmithorg/appsmith/issues/14659 - or at least a specific example of the wider problem with spaces in the .env file.

**Comment by tomharvey** [comment] 2022-06-21 09:51
This seems like a duplicate of https://github.com/appsmithorg/appsmith/issues/13335 - or at least a specific example of the wider problem with spaces in the .env file.

**Comment by Nikhil-Nandagopal** [comment] 2022-06-22 09:21
@tomharvey thanks for pointing this out! I'll close this in favor of #13335

**Closed by Nikhil-Nandagopal** 2022-06-22 09:21 UTC
Labels: Bug, Needs Triaging
