### ISSUE TITLE
[Bug] ipify's api6.ipify.org url

### ISSUE THREAD

**Issue by sabbatum** [appsmithorg/appsmith#889] opened 2020-10-02 21:26 UTC
## Description

Does the ipify url need to be changed to `api64.ipify.org` url? `api6.ipify.org` is now only for IPv6 requests. I can make PR if so.

Message from [ipify.org](https://www.ipify.org/)
> Oct 1, 2020 the A record for api6.ipify.org will be removed to make the subdomain only for IPv6 requests. For universal access please use api64.ipify.org.

https://github.com/appsmithorg/appsmith/blob/8c388eb1539627fcf1f2d6b63e7cf40e8ef66a80/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PingScheduledTask.java#L29

**Comment by mohanarpit** [comment] 2020-10-03 03:56
Closing as duplicate of #886

**Closed by mohanarpit** 2020-10-03 03:56 UTC
Labels: Bug, High
