### ISSUE TITLE
[Bug]: Input widget does not allow user entry for Currency data type

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#10367] opened 2022-01-13 04:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the Currency data type, the input widget is not accepting values entered by the user. 

### Steps To Reproduce

1. Drag and drop an input widget on the canvas.
2. Change the data type to Currency
3. Enter values in the input widget. 
4. It does not record any typed values and the widget stays empty

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment] 2022-01-13 07:36
@danciaclara I'm not able to repro this. Could you share the app where it is happening? 
https://www.loom.com/share/875205e23c4a4eb1b31e9cf140584dc3

**Comment by sbalaji1192** [comment] 2022-01-13 10:42
@vibhandikyash 
Note: 
Issue is caused by the L401 from `/app/client/src/widgets/InputWidget/component/index.tsx`. need to handle when `focus-visible` is not present.

**Comment by vibhandikyash** [comment] 2022-01-18 12:07
@sbalaji1192 This issue has already been fixed with the new Currency widget and is working in latest Release.
cc: @vivekverma2312 @sbalaji1192 Pl. verify and close the same.

**Comment by Nikhil-Nandagopal** [comment] 2022-01-18 12:30
seems fixed on release

**Closed by Nikhil-Nandagopal** 2022-01-18 12:30 UTC
Labels: Bug, Input Widget, App Viewers Pod, Critical, UI Building Pod, regression
