### ISSUE TITLE
[Bug]: Spacebar on iFrame does not pause audio content

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10170] opened 2022-01-05 07:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hitting `spacebar` on iFrame widget with audio content does not pause media. Play icon animates between pause and play but does not stop playing. Albeit, it does resume playing by hitting the `spacebar` if media has been paused. 

This works on video (example, embeded **YouTube** link) but does not work for audio only (**Spotify**)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b90ccc4c99e44c4aab5ca7ff58103f38-00001.gif)](https://www.loom.com/share/b90ccc4c99e44c4aab5ca7ff58103f38)

### Steps To Reproduce

1. Embed Spotify link on iFrame and use `spacebar` to control player and observe behaviour

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-01-12 17:36
Hi @ramsaptami, I am unable to reproduce this in release. can you check this app - https://release.app.appsmith.com/applications/61b735d35440164c77e9f956/pages/61df10e015bb3b596c504f22  Page 2 in this app. Want to know if this is a browser issue.

**Comment by ramsaptami** [comment] 2022-01-19 13:41
hey @dilippitchika I'm not able to access that link. Can you repost please?

**Comment by dilippitchika** [comment] 2022-02-25 05:19
Forgot about this, sorry @ramsaptami can you access using demo@appsmith.com?

**Comment by ramsaptami** [comment] 2022-02-25 06:21
Yep, I'm not able to repro this on release anymore. I'll have another look and close this since it seems to be working now

**Comment by dilippitchika** [comment] 2022-03-31 18:43
Closing this for now @ramsaptami, let me know if you want to reopen

**Closed by dilippitchika** 2022-03-31 18:43 UTC
Labels: Bug, UX Improvement, App Viewers Pod, Low, Release, UI Building Pod, keyboard shortcut, iFrame
