### ISSUE TITLE
[Bug]: Base64 of .docx and/or .xlsx not working with Document Viewer

### ISSUE THREAD

**Issue by SvV-CWinJS** [appsmithorg/appsmith#19427] opened 2023-01-02 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I put a data URL of a docx or xlsx file as source for the document viewer, the document is not shown. "Oops, Something went wrong." is shown instead.

### Steps To Reproduce

1. Create a xlsx (or docx) file or use the attached test files.
2. Encode the file as base64.
3. Set under "Document link" of a Document Viewer the following: data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,_your base64_
[test.docx](https://github.com/appsmithorg/appsmith/files/10331112/test.docx)
[test.xlsx](https://github.com/appsmithorg/appsmith/files/10331113/test.xlsx)

### Version

Self Hosted - 1.8.15

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6z9xo)

**Comment by somangshu** [comment] 2023-01-02 12:41
@SvV-CWinJS thanks for reporting the issue

@vsvamsi1 lets triage this issue, this ideally should be working

**Comment by ame-appsmith** [comment] 2023-01-24 12:54
[Another user](https://app.frontapp.com/open/msg_1lo0p8p8?key=VfHXFpp12D2a_VVRls29hUTTCo_bfdGM) reported this error.

**Comment by chandannkumar** [comment] 2023-02-03 05:18
#20342

**Comment by dilippitchika** [comment] 2023-02-03 06:51
Scope change, so i would assume it's a new issue. But need @vsvamsi1 to check if this can also be fixed in the same pr in a short notice, if not then we should skip.

**Comment by vsvamsi1** [comment] 2023-02-03 06:57
Hi @dilippitchika I need to analyse for other document types, they are not currently working in our current release. 
I think we can move ahead with this fix for now, we should enable our users to use doc and xlsx document types. Can we mark this as done @dilippitchika ?

**Comment by dilippitchika** [comment] 2023-02-03 06:59
Sure @vsvamsi1 let's proceed

**Comment by dilippitchika** [comment] 2023-02-03 07:01
But how do we bring this foresight upfront to ensure the issue is resolved in the best possible way, @somangshu @vsvamsi1. If we would have scoped this before to also include Chandan's findings before being picked up for development, we could have built a holistic solution.

**Comment by vsvamsi1** [comment] 2023-02-03 07:36
Hi @dilippitchika 
I assumed that doc types specified in ticket are the only ones broken, I wasn't aware of failures of other doc types.
I think the main issue was there weren't adequate test cases for document viewer widget, i believe it was broken some time back and regression test cases would have brought it up.
It surprised me that many features of it are not working and it hasn't been noticed, my hunch is that our users were not using this component too much.

**Comment by SvV-CWinJS** [comment] 2023-02-03 07:44
Hi all
I can tell you that data URL's of pdf's are shown by the Document Viewer in my current version (v.1.9.5) (when formatted as data:application/pdf;base64,_data_.)

**Closed** 2023-02-08 09:52 UTC
Labels: Bug, App Viewers Pod, High, Needs Triaging, Document Viewer Widget
