### ISSUE TITLE
[Bug]: On saving and authorizing auth api, from a branch in a git connected app, user is thrown out of application

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28475] opened 2023-10-30 11:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On saving and authorizing an authenticated api, from a branch in a git connected app, user is thrown out of application

### Steps To Reproduce

1. Create a git conected app
2. Create  a branch, and from the branch, create an Auth API. 
3. Save and authorize this. 
4. Note that user is taken to the home page, instead of retaining the user on the Review page.
Note: If the above steps are done from the Master branch, it works fine. 
**Note: Incase of release or prod, user is taken to a 404 page.**

### Environment

Deploy Preview

### Version

Cloud

**Comment by btsgh** [comment] 2023-11-06 05:32
As per discussions on the slack [thread](https://theappsmith.slack.com/archives/C03QHS03RDK/p1699247920881549?thread_ts=1698389608.824789&cid=C03QHS03RDK), this is an issue seen on Release as well, in a particular case where the Page ID's don't match. Removing PR Blocker tag and assigning adding this to Prod .. cc: @ayushpahwa

**Comment by rohan-arthur** [comment] 2023-12-08 06:38
changing tags to platform pod [because](https://theappsmith.slack.com/archives/C03QHS03RDK/p1699247920881549?thread_ts=1698389608.824789&cid=C03QHS03RDK)

**Comment by riteshkew** [comment] 2024-04-12 07:44
Not able to reproduce this on Production v1.18, hence closing this as of now.

**Closed by riteshkew** 2024-04-12 07:44 UTC
Labels: Bug, High, Production, Needs Triaging, Data Platform Pod, Datasource Environments
