### ISSUE TITLE
[Bug]: The workspace settings/options pop up does not close when we scroll through the page.

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15659] opened 2022-08-03 09:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we open the workspace settings/options pop up by clicking the 3 dots, it does not close when we scroll through the page.

https://www.loom.com/share/ea29dabf3d03458ab871669be8dd7fa3

### Steps To Reproduce

1. Go to the homepage.
2. For any workspace click on the 3 dots next to the `+ New` button.
3. Now scroll through the page.

**Expected:** The settings pop up should automatically close when we scroll through the homepage.

### Version

Cloud

**Comment by deepika-appsmith** [comment] 2024-04-01 08:16
With the recent revamp of the homepage, the issue is no longer relevant as multiple workspaces are no longer displayed one below the other. Therefore, closing the ticket.

**Closed by deepika-appsmith** 2024-04-01 08:16 UTC
Labels: Bug, UI Improvement, UX Improvement, Home Page, Production, Needs Triaging, Medium, Billing & Usage Pod
