### ISSUE TITLE
[Feature]: Set pageNo on table

### ISSUE THREAD

**Issue by spamoom** [appsmithorg/appsmith#32077] opened 2024-03-26 14:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When using a table with multiple pages, I navigate to another page, click a button in a table row to view an item on a different page.

When I go back, the table is reset and I have to navigate back to where I was on the table pagination

### Why should this be worked on?

It's a quick win, but allows for advanced functionality

**Comment by Nikhil-Nandagopal** [comment] 2024-03-26 18:29
@spamoom if you have configured your table with server side pagination, what you can do is store the value of the page number using `storeValue` and then when you come back you can by default fetch data from your query with that pageNumber to ensure that you are right where you left off

**Comment by Nikhil-Nandagopal** [comment] 2024-04-29 09:02
I believe this is a duplicate of #24973

**Closed by Nikhil-Nandagopal** 2024-04-29 09:02 UTC
Labels: Enhancement, Table Widget, App Viewers Pod, Community Reported
