### ISSUE TITLE
[Feature] Ability to watch a remote branch: auto deploy when the remote branch has new commits

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5791] opened 2021-07-12 08:41 UTC

**Comment by abhvsn** [comment] 2022-03-21 09:47
@hiteshjoshi this can be a potential duplicate of https://github.com/appsmithorg/appsmith/issues/11522, should we close this as more context is present in the other ticket?

**Comment by abhvsn** [comment] 2022-05-16 12:16
Closing this as possible duplicate of https://github.com/appsmithorg/appsmith/issues/11522

**Closed by abhvsn** 2022-05-16 12:16 UTC
Labels: Git Version Control, Task, Team Managers Pod, Platform Pod
