### ISSUE TITLE
[Feature] Need a option to disable/hide time picker in the datepicker widget.

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#7706] opened 2021-09-22 05:19 UTC
## Summary
Need a option to disable/hide time picker in the date picker widget.

## Motivation
More often than not, users want to have date pickers in their forms and not be concerned about time. An option to remove the time picker or even disable it, would be a great addition.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-22 06:27
Duplicate of #3516

**Closed by Nikhil-Nandagopal** 2021-09-22 06:27 UTC
Labels: Enhancement
