### ISSUE TITLE
[Bug]: Gateway timeout on git connect request

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#12407] opened 2022-03-31 04:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add `git@example.com:username/reponame.git` as remote repo and click connect, service doesn't return valid response. In dev console, I see that a gateway timeout has occurred. Service should return proper response.

### Steps To Reproduce

1. go to app.appsmith.
2. Click git connect
3. Enter `git@example.com:username/reponame.git` and click generate key
4. Open dev console, network tab
5. Click Connect
6. See that service doesn't return proper response, and request times out as gateway timeout.

![Screenshot 2022-03-31 at 9 16 05 AM](https://user-images.githubusercontent.com/1573771/160974428-f106c888-b111-41f4-b87e-50f0d087da95.png)

### Response

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment] 2022-03-31 04:13
There was a [similar issue](https://github.com/appsmithorg/appsmith/issues/12094#issuecomment-1077266144) due to gateway timeout in git fetch branches request.

![gateway timeout in git fetch branches](https://user-images.githubusercontent.com/1573771/159852082-74c15d9a-5a0b-46b0-a43f-ed4dc7af4701.png)

**Comment by jgrgt** [comment] 2022-04-08 09:19
As mentioned on discord, for me the problem is in `GitUtils.isRepoPrivate`.

There are multiple things wrong with that call:
1. It's using *blocking* IO in a WebFlux server. Which is a bad idea. A reactive HTTP client should be used.
2. It assumes the domain of the SSH access and HTTPS access for the server are identical. This is not the case in my environment, different domains are used.. The problem code:
```
    public static String convertSshUrlToBrowserSupportedUrl(String sshUrl) {
        if (StringUtils.isEmptyOrNull(sshUrl)) {
            throw new AppsmithException(AppsmithError.INVALID_PARAMETER, "ssh url");
        }
        return sshUrl
                .replaceFirst(".*git@", "https://")
                .replaceFirst("(\\.[a-z]*):", "$1/")
                .replaceFirst("\\.git$", "");
    }
```

Why is it required to do this `GitUtils.isRepoPrivate` check? In any case, a reactive HTTP client should be use with both connection and response timeouts that are low enough to not break the rest of the flow?

**Comment by abhvsn** [comment] 2022-04-25 07:10
Closing this as a part of https://github.com/appsmithorg/appsmith/pull/12819

**Closed by abhvsn** 2022-04-25 07:10 UTC
Labels: Bug, Needs Triaging, Platform Pod, Git Version Control, Team Managers Pod
