### ISSUE TITLE
[Bug]: Random string shows up as series name on chart widget when data comes from a binding

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#26107] opened 2023-08-08 05:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Series title field cannot be left empty on a chart widget when data is fetched from a binding, a random string shows up as series title.

This is a recent change and causes existing charts to display an error on page load and correct itself after completing evaluations
![image](https://github.com/appsmithorg/appsmith/assets/79509062/702b44d4-dc99-497e-9b65-487670113bca)

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/1c3f9577-2c28-45fc-8546-f9041b20244f)

### Public Sample App

https://app.appsmith.com/app/appsmith-regression-app/feature-list-63845f073e748351b7e6b224?branch=master

### Environment

Production

### Version

Cloud

**Comment by rajatagrawal** [comment] 2023-09-01 12:36
@ramsaptami 

The random string bug has been addressed in one the earlier bugs fixes and isn't happening anymore.

For the error flicker, the root cause has been triaged to a user coding error instead of a bug in the chart widget. We have experienced similar issues in other apps and has been happening in the standup app in the team stats section as well.

For the particular case of the standup app team stats section, 

We have the following query :
```
{{velocity_trend.data.data.workspace.sprints.nodes.map((v,i) => {
  return {x: v.name, y:v.totalPoints, data: v}
})}}
```

The error that we get in flicker is ```Cannot read properties of undefined (reading data)```. This is an expected error and it can be fixed by a code snippet like this

```
const apiData = velocity_trend ?? {}

if (Object.keys(apiData).length > 0) {
  return apiData.data.data.workspace.sprints.nodes.map((v,i) => {
    return {x: v.name, y:v.totalPoints, data: v}
   })
} else {
  return apiData
}
```

I have verified that a simllar snippet in a demo app worked and the error went away.

Thus it can be confirmed that it is not a bug rather a configuration error from  the user’s persepctive.

**Closed** 2023-09-06 07:49 UTC
Labels: Bug, Chart Widget, App Viewers Pod, Production, Regressed, Needs Triaging, Medium
