### ISSUE TITLE
[Bug]-[1320]:'Ends With' operator in Table filters not working in certain cases

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#13334] opened 2022-04-26 14:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It appears to not work when filtering the entire word in a column

Appears to work fine when filtering letters from the last word in the following situations. Note that I searched for 'son' and 'Benson' in the FullName column. Gives correct results

<img width="922" alt="Screenshot 2022-04-26 at 7 57 09 PM" src="https://user-images.githubusercontent.com/32227135/165323212-2390a687-abe2-425b-a02a-fdeeb77c7f34.png">

<img width="917" alt="Screenshot 2022-04-26 at 7 56 58 PM" src="https://user-images.githubusercontent.com/32227135/165323188-9b8ea057-dbd7-44cd-b047-ca4a7e2f3bb5.png">

Search for 'son' in the LastName column yields correct results.
<img width="852" alt="Screenshot 2022-04-26 at 8 07 00 PM" src="https://user-images.githubusercontent.com/32227135/165325192-292661f0-d902-4912-83a2-002c03f8dbda.png">

Now when I search for the whole word 'Benson' on the LastName column, it gives incorrect results. My guess is it is not returning correct results for anything more than 3 letters in a column with a single word (Eg: LastName column) and also if you search for the entire word in a column (Eg: Catherine Benson in FullName column)
<img width="847" alt="Screenshot 2022-04-26 at 7 57 24 PM" src="https://user-images.githubusercontent.com/32227135/165323555-ad96d449-9da6-4a17-bb67-dcde12707ddf.png">

### Steps To Reproduce

Detailed above with screenshots. Shared sample app below

### Public Sample App

https://app.appsmith.com/app/table-filters-ends-with-operator/page1-6268050000cba01cd0305d2d

### Version

Cloud/Self-Hosted - v1.6.20

**Comment by dilippitchika** [comment] 2022-04-28 05:57
Needs a bit more detailed investigation to identify what are other similar cases which may fail. @somangshu should we assign this to someone in the QA team to do a bit more thorough investigation on filters or should this be looked at by a dev for triaging. 

Also predicting Reach is tricky because we don't have filters on how many people are clicking on table buttons.
Approximating this to 5% of users who have configured a table for now
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 330 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment] 2022-04-28 06:31
Lets follow a test driven approach this time since this has happened multiple times

@Aishwarya-U-R can you check out the test cases and tell us what is missing, we will list them here and then implement the change and also right the corresponding test cases. This was we should regress again. 

Please consider any use case from the past you have experienced

**Comment by somangshu** [comment] 2022-04-28 06:32
setting this to high since this issue blocks the user, Though there is an alternative to resolve the problem

**Comment by Aishwarya-U-R** [comment] 2022-05-12 07:15
Hi @dilippitchika - I have added a script for validating this bug & is right now commented, once this is fixed can add that also to the regression suite. And adding @vivekverma2312 if incase he has any more scenarios he may have for TableFilters!

**Comment by Aishwarya-U-R** [comment] 2022-05-12 07:17
And from script point of view - yet a many table filter scenarios are to be covered & the coverage seems less/basic Text column filters at this point of time!

**Comment by dilippitchika** [comment] 2022-09-28 07:18
@somangshu can you spend time on identifying next steps here?

**Comment by somangshu** [comment] 2022-09-28 10:15
Ok, Here is what I think
- We triage the problem basis above test cases that are written
- We identify the fix and implement it
- Add the test cases and ship

cc @keyurparalkar

**Comment by souma-ghosh** [comment] 2022-10-12 11:04
@somangshu @Aishwarya-U-R
This is an edge case with the logic behind the endsWith operation. Whenever the search term length is greater than the cell value length by exactly 1 it will satisfy the ends with condition irrespective of what the search term or the cell value is.
Should be a simple fix

**Closed** 2022-10-14 05:39 UTC
Labels: Bug, Table Widget, App Viewers Pod, High
