### ISSUE TITLE
[Epic]: Performance infra V2

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#23787] opened 2023-05-28 05:12 UTC
### Objective

Make performance infra robust to help improve developer adoption.

- Option to re-run failed tests.
- Automatic re-running of tests.
- Identify problem area based on problem failures by tagging tests with the areas covered.
- Run perf tests in parallel.
- Ability to mark perf tests as flaky.

### Success Metrics

| Metric         |
| -------------- |
| Bring the false positives under 20%  |
| Bring the time taken by perf tests under 30 minutes       |

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   | @SatishGandham , @sarojsarab                |
| Accountable   |     @SatishGandham           |
| Consulted     | @SatishGandham |
| Informed      |     @somangshu           |

**Comment by somangshu** [comment] 2023-06-28 12:44
@SatishGandham I feel we should divide this in 2 parts
- the enhancements that we need (increased coverage etc)
- the stability we need

Because of the current scenario as pointed out [here](https://theappsmith.slack.com/archives/C024GUDM0LT/p1686913371737549), I feel if we wait for too long, the infra will keep becoming a blocker in many places to a point it gets obsolete. 
Lets make it stable so that most test are passing, and the once that dont are actually a regression.

**Comment by rajatagrawal** [comment] 2024-03-02 07:45
Since we have deprioritized running local perf tests, closing this epic that tracks tasks for it.

**Closed by rajatagrawal** 2024-03-02 07:45 UTC
Labels: Performance Pod, Epic, Performance infra, Performance
