### ISSUE TITLE
[Bug]: Capitalized file extensions cause an error in the Document Viewer

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#27828] opened 2023-10-04 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to read a pdf file ending in .PDF with the document viewer I get the error `Current file type is not supported`. The PDF is valid. This does not happen for PDFs with lowercase extensions.

I expect the document to be read and displayed.

### Steps To Reproduce

1. D&D a Document viewer widget.
2. Provide a URL to a PDF that ends with a non-lowercase extension (PDF, pDf, etc.)
3. Observe that the the error `Current file type is not supported` is displayed instead of the provided document.

### Environment

Production

### Version

1.9.37.1

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1yni18)

**Comment by raushan3737** [comment] 2024-07-10 08:04
Hi @Nikhil-Nandagopal , @LagunaElectric ,  I would like to work on this issue. 

Approach: We have to make sure that file extension should be in lowercase(as all file extension should be in lowercase in standard form) while doing validation and rendering the corresponding viewer.

**Comment by Nikhil-Nandagopal** [comment] 2024-07-10 08:59
@raushan3737 the validation already works, the ask here is to make the file render even if it is in upper case.

**Comment by raushan3737** [comment] 2024-07-10 09:44
Hi @Nikhil-Nandagopal , 

**In order to fix the issue:** 
 1. We have to make sure that if the user enters url having some uppercase url at place of document link, internally we should first validate the extension from allowed extension list by converting the extension to lowercase as may user can enter url containing uppercase char.
 2. We have to make sure that, when browser will make the request to that url it should be correct so, that api response will be success as to render in any of the viewer.


**Observation:** 
![Screenshot from 2024-07-10 14-56-38](https://github.com/appsmithorg/appsmith/assets/124759155/72de8199-35e2-467f-8d95-60825bdee531)
![Screenshot from 2024-07-10 14-57-31](https://github.com/appsmithorg/appsmith/assets/124759155/ab1219ed-4b8c-4d93-8069-8ddc6c3a96e9)

**Code Snapshot(Refering the FE Code):** 
![Screenshot from 2024-07-10 15-00-46](https://github.com/appsmithorg/appsmith/assets/124759155/fbeffc5c-15f7-4fed-8690-410728b1fc6b)
![Screenshot from 2024-07-10 15-01-18](https://github.com/appsmithorg/appsmith/assets/124759155/4a5f3151-a8e6-498d-a52a-b4382d3eab77)

**Comment by Nikhil-Nandagopal** [comment] 2024-07-10 10:02
@raushan3737 sure but my thinking is that the browser should accept and open a URL that has the extension in uppercase. Maybe you can validate that once with a file in uppercase?

**Comment by raushan3737** [comment] 2024-07-10 10:12
> @raushan3737 sure but my thinking is that the browser should accept and open a URL that has the extension in uppercase. Maybe you can validate that once with a file in uppercase?

Yes @Nikhil-Nandagopal , i have checked this behaviour, when we are directly copy-pasting the document url containing uppercase extension, browser was able to convert that in lowercase and served the response. But, in case of our application it is not transforming the extension to lowercase that is why are getting 404(Not Found)  in network tab for our application. 

**Try to open this [Sample Docs Url](https://www.learningcontainer.com/wp-content/uploads/2019/09/sample-pdf-file.Pdf) and observe browser is changing the extension to lowercase, but not in the appsmith application.** 

Snapshot: 
In Browser: 
![image](https://github.com/appsmithorg/appsmith/assets/124759155/17f574f0-9fe8-4b1e-95f3-4723c59d8ede)
In Appsmith app: 
![image](https://github.com/appsmithorg/appsmith/assets/124759155/3944194f-54a4-4037-bd62-e700ee538b93)

**Comment by Nikhil-Nandagopal** [comment] 2024-07-12 11:17
@raushan3737 in this case the PDF itself is not on that route and the issue is not with the document viewer but with the actual PDF URL. In the users case they are saying the PDF url is valid and opening in the browser but not in the document viewer

**Comment by raushan3737** [comment] 2024-07-12 11:30
> @raushan3737 in this case the PDF itself is not on that route and the issue is not with the document viewer but with the actual PDF URL. In the users case they are saying the PDF url is valid and opening in the browser but not in the document viewer

Yes @Nikhil-Nandagopal ,  it was opening in the browser but with lowercase, Please try to open this url & observe this behaviour:
 Sample doc with uppercase extension: https://www.learningcontainer.com/wp-content/uploads/2019/09/sample-pdf-file.Pdf 

By changing to lowercase i am able to render the document in the viewer.

Should i proceed with the approach.

Output(See the url in the right side, used url with uppercase extension):
![image](https://github.com/user-attachments/assets/21a1a929-f351-45d6-8005-f55b9ee86252)

**Comment by Nikhil-Nandagopal** [comment] 2024-07-12 12:28
@raushan3737 my point is that that is not the issue. The issue is when a doc opens in the browser with uppercase but does not open in the document viewer. If it doesn't open in the browser, it's not expected to open in the document viewer

**Comment by raushan3737** [comment] 2024-07-12 12:54
> @raushan3737 my point is that that is not the issue. The issue is when a doc opens in the browser with uppercase but does not open in the document viewer. If it doesn't open in the browser, it's not expected to open in the document viewer

Hi @Nikhil-Nandagopal :
- If you try to click on the link and open it in the browser directly, then the extension is not getting converted to lowercase because of which it won't open.
- If you copy paste the link, then the browser automatically converts it into lowercase and then the document gets rendered.

- The above mentioned works only if the extension of those docs are not in correct format specifically if it is capitalize (example:  .PDF,  .Pdf)
- If the issue is at any other part of url then, it won't open in the brower as well as app. 

- If you are on the same line as me, then we either have to convert the extension of the url to lowercase or else, we can show that error unsupported type as the response.

**Comment by Nikhil-Nandagopal** [comment] 2024-07-12 14:18
@raushan3737 copy pasting it in the browser does not make it lowercase. If it's just about making it lowercase frankly the user can just do {{url.toLowerCase()}} and solve their problem. So this is not really the issue.

Unless we are able to make a valid URL that opens with https://url.PDF work on the platform because it's also working on the browser, we should just close this issue and not bother about it

**Comment by Nikhil-Nandagopal** [comment] 2024-07-12 14:20
In light of this, I'm going to close this issue

**Closed by Nikhil-Nandagopal** 2024-07-12 14:20 UTC
Labels: Bug, App Viewers Pod, Production, Community Reported, Needs Triaging, Document Viewer Widget, Medium
