### ISSUE TITLE
[Feature] Show last saved, last deployed info

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4939] opened 2021-06-05 23:55 UTC
## Summary
It'll be helpful for users to know the last time their app was auto-saved and deployed.

## Motivation
1. Users hover on the green tick and don't understand what it means
2. Users don't know if they've deployed the latest changes

Solution:
1. Show last saved on hover on tick
2. Show a timestamp for last deployed in the drop-down which displays the deployed URL

**Comment by Nikhil-Nandagopal** [comment] 2021-06-07 06:38
Duplicate of #2483 closing as we have more info there

**Closed by Nikhil-Nandagopal** 2021-06-07 06:38 UTC
Labels: Enhancement, Platform, Quick effort
