### ISSUE TITLE
[Bug] Collab->When the user add a comment the user should be able to drag and drop the comment pin in required area

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5220] opened 2021-06-17 09:27 UTC
## Description

[What happened]Collab->When the user add a comment the user should be able to drag and drop the comment pin in required area

### Steps to reproduce the behaviour:

1. Create an App
2. Click on comment Icon
3. drop a comment pin and add a comment
4. now try to drag the comment pin

Expected result: The user should be able to Drag and drop the comment pin in the required position

Actual Result: Now the user is not allowed to drag and drop the comment pin
![image](https://user-images.githubusercontent.com/45958978/122369863-352d7d00-cf7c-11eb-8b20-a8803a67cab2.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production,]

**Comment by rishabhsaxena** [comment] 2021-07-19 11:14
Duplicate of #5608

**Closed by rishabhsaxena** 2021-07-19 11:14 UTC
Labels: Bug, Collaboration, Low, Needs Triaging, Platform, Release
