### ISSUE TITLE
[Bug]: Vertical scroller is coming in view mode when changed from fluid to any view while editing

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10352] opened 2022-01-12 12:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Refer to comments below for loom!

### Steps To Reproduce

1. Open an app in edit mode
2. Change the view to any from fluid
3. Deploy the app
4. Observe the vertical scroller is displayed on the screen.

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-01-12 17:05
Hey @vivekverma2312 can you add the video or screenshot? Looks like the link is broken.

**Comment by vivekverma2312** [comment] 2022-02-25 05:40
@dilippitchika Now the observation is slightly changed. Previously the horizontal scroll bar use to persist after deployment but now it shows for a sec and then disappears.
https://www.loom.com/share/e8c9ce460f194069863c370b90a1526a

**Comment by vivekverma2312** [comment] 2022-03-03 08:23
@dilippitchika I am able to repro this issue on release again. Can you please check. Let me know if you need more help in repro.
https://www.loom.com/share/2430f36041dd458da7935ce2d3a259d1

**Comment by dilippitchika** [comment] 2022-03-03 08:58
@somangshu looks like an issue in ui builders pod, this is high priority though it's happening in release

**Comment by somangshu** [comment] 2022-03-03 09:41
Our code is the same on release and prod right now, Our promotion is already completed last night. 

In case its only on release, it means its a recent commit that is causing this? We can check that

**Comment by somangshu** [comment] 2022-03-03 10:50
As pointed out internally this was caused because of the change [here](https://github.com/appsmithorg/appsmith/pull/11461). @techbhavin lets find the solution soon and ship it on priority

cc @vivekverma2312 @rahulramesha

**Comment by somangshu** [comment] 2022-03-03 10:51
regression from #9858

**Comment by techbhavin** [comment] 2022-03-08 04:16
@somangshu  can we close this issue. Here we revert the change of #9858 so the related issue is fixed

**Closed** 2022-03-08 07:24 UTC
Labels: Bug, App Viewers Pod, High, Release, UI Building Pod, regression, View Mode, Release Blocker, Embedding Apps
