### ISSUE TITLE
[Bug]: Unable to download excel sheet successfully as it says `file corrupted` when trying to open the doc

### ISSUE THREAD

**Issue by Druthi** [appsmithorg/appsmith#22206] opened 2023-04-10 06:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Link to slack conversation: https://theappsmith.slack.com/archives/C0341RERY4R/p1678954237147369

### Steps To Reproduce

1. Go to this app https://app.appsmith.com/app/download-jsreport-document/page1-6424543cdc009637d664ba3c
2. Click on Download button
3. Try to open the downloaded file
4. Get an error while trying to open.

### Public Sample App

https://app.appsmith.com/app/download-jsreport-document/page1-6424543cdc009637d664ba3c

### Environment

Production

### Version

Cloud - v1.9.15

**Comment by sanchoo85** [comment] 2023-06-06 08:21
I have object:
`export default {

	downloadXLS: async (name, guid, from, to) => {

		let data = await DownloadXls.run({
			"guid": guid,
			"from": from,
			"to": to
		})

		await download(data, name+"-"+from+"--"+to+".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	}
}`
And I call from table, button on click:
`{{
DownloadObject.downloadXLS(
 Table1.triggeredRow.name, Table1.triggeredRow.guid,
 from.inputText,
  to.inputText
)}}`

It works

**Comment by davd-edia** [comment] 2024-02-16 15:59
We find that when using the Table's builtin download button, any table that has a numeric column, will produce an excel file that when opened in Excel produces an error message regarding recovery of the file. 

If we change the column type in the Table's column's properties to Plain Text, the file is created correctly. But this then breaks sorting of numeric columns (and maybe filtering?).

This is a basic functionality that is built into the table widget but does not work. Telling users to just "ignore the error" is not a good look. We are forced to disable this functionality and build another download button somewhere on the canvas, taking screen space unnecessarily.

**Comment by ssciacco** [comment] 2024-03-09 10:05
> We find that when using the Table's builtin download button, any table that has a numeric column, will produce an excel file that when opened in Excel produces an error message regarding recovery of the file.

I confirm a similar issue. Numeric columns miss the column title. When changing the type to plain text everything is fine.

**Comment by bl1nkker** [comment] 2024-09-11 09:40
Are there any updates on this issue? I encountered this problem using FilePicker

In my project I use the Appsmith + FastAPI. When I upload a file that is larger than 100kb, appsmith saves it to my file system. However, when opening the file, it seems to be corrupted. After researching more, I uploaded the file manually using swagger and noticed a difference in file sizes (the difference is on average 40kb). It’s interesting that files smaller than 100kb are uploaded correctly

**Comment by bl1nkker** [comment] 2024-09-11 09:41
I suspect that the file might be truncated or modified during the Appsmith upload, causing this error for specific .xlsx files

**Comment by Nikhil-Nandagopal** [comment] 2024-09-16 14:55
@bl1nkker this seems to be a very different issue you are facing. Can you please open a new issue with a sample app and file that we can use to test?
I'm closing this issue because it's not possible to reproduce the original issue

**Closed by Nikhil-Nandagopal** 2024-09-16 14:55 UTC
Labels: Bug, High, Production, Needs Triaging, Low effort, Javascript Product, Query & JS Pod, Framework Functions, Integrations Product, Integrations Pod General
