### ISSUE TITLE
[Bug] In prepared statements, it is impossible to use numeric values with leading zero as strings

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4056] opened 2021-04-19 13:29 UTC
Consider a Postgres query with following SQL, where column `col` is of type `text`:

```sql
update x set col = {{"0123"}}
```

This sets the value of the column to `0123` when **not** using stored procedures and `123` when using stored procedure. The reason seems to be that we are identifying this value as an _integer_, because `Integer.parseInt` succeeds, however, in doing so, we lose the leading zero. The leading zero here is important which is why the column was defined as `text` type instead of a numerical type.

From the code, it looks like this problem will be present for other numerical Java types like `Long`, `Float` and `Double`.

**Comment by sharat87** [comment] 2021-04-19 13:30
Not marking this critical **only** because the prepared statements have a `[Beta]` tag in the UI.

**Comment by hetunandu** [comment] 2021-04-19 13:33
Is this a proper use case for Prepared statements only? By default, the browser will always throw an error for any numbers with a leading 0 because this is not allowed in the "strict" mode of JS. This is reproducible in any binding.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#converting_mistakes_into_errors

**Comment by sharat87** [comment] 2021-04-19 13:39
The problem is we don't want to treat it as a number. We want to treat it as a string. Consider the following SQL:

```sql
update x set col = '01234'
```

Here, we're not dealing with a zero-prefixed number, we are dealing with a string whose first character is zero. JS doesn't have a problem with (would be absurd to 😉).

Our backend, noticing that this is parseable as an integer, converts into the integer `123`, thereby losing the leading `0`.

**Comment by hetunandu** [comment] 2021-04-19 13:52
That is correct but when the value is coming via a binding, it would be parsed and treated like a number since each binding is evaluated separately and then substituted in the place with $1 etc.
```
update x set col = '{{ 01234 }}'
```
and evaluating that number will fail before we can substitute it.

**Comment by sharat87** [comment] 2021-04-19 14:18
Even in the binding Javascript, it's a string. It's nowhere represented as a number:

```sql
update x set col = '{{ "01234" }}'
```

**Comment by trishaanand** [comment] 2021-04-20 08:38
This is a valid bug. To avoid extra configuration by the user when using Prepared Statements, today the data type is implied from the value. The fix for this would be to overrule the server set data type by using something like the following :
```select * from users where id = {{Input1.text}}::text```
The above needs to be implemented on the server side where the user wants to override the default server data type implication.

**Closed** 2021-07-15 14:03 UTC
Labels: Actions, Actions Pod, Bug, High, Needs Triaging, community
