### ISSUE TITLE
[Feature]: Users can view / discard changes done to an application managed using github before deploying it.

### ISSUE THREAD

**Issue by Rhitottam** [appsmithorg/appsmith#19042] opened 2022-12-19 14:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Managing our Appsmith application using github is a great feature. But sometimes there are certain changes that are shown while deploying which do not map well with the changes done by the user. So it might make the user doubtful about confirming these changes before deployment. This problem will get solved if users can view the changes made to their application in a detailed human-readable format and correct any mistakes they might have done before they commit their changes. This feature requests attempts to solve this problem and will greatly improve Appsmith's user experience

### Why should this be worked on?

Problem Scenario :
- User makes changes to a JS query or an SQL query
- While deploying the user notices that their changes include UI changes as well
- User is not confident about deploying these changes since they don't remember doing any changes to the UI.
- User discards all the changes made and redoes everything.

**Comment by AnaghHegde** [comment] 2023-08-17 11:42
Closing this as duplicate of #14411

**Closed by AnaghHegde** 2023-08-17 11:42 UTC
Labels: Enhancement, Git Version Control, Git Pod
