### ISSUE TITLE
[Bug] File upload is not putting picker in loading state

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1026] opened 2020-10-06 12:09 UTC
https://www.notion.so/File-upload-is-not-putting-picker-in-loading-state-6d129e0564ec4b8eba0db59f3103afbf

**Comment by Nikhil-Nandagopal** [comment] 2020-10-06 14:06
duplicate of #949

**Closed by Nikhil-Nandagopal** 2020-10-06 14:06 UTC
Labels: Bug, Low, Release

**Comment by prapullac** [comment] 2020-10-08 06:58
Closing the issue after verifying
