### ISSUE TITLE
[Bug]: rm: cannot remove '/etc/letsencrypt': Directory not empty

### ISSUE THREAD

**Issue by liliang8858** [appsmithorg/appsmith#13651] opened 2022-05-07 01:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
Initialize .env file


Load environment configuration


Checking environment configuration


Checking APPSMITH_MONGODB_URI


Detected local MongoDB


Initializing local database


Checking initialized database


Mounting Let's encrypt directory


rm: cannot remove '/etc/letsencrypt': Directory not empty
```

![image](https://user-images.githubusercontent.com/38367404/167231697-ce0b1041-ebfd-4ff1-a868-a5c63d0bc0fc.png)

### Steps To Reproduce

curl -L https://bit.ly/32jBNin -o $PWD/docker-compose.yml
docker-compose up -d
docker logs -f appsmith

### Version

appsmith 1.3

**Comment by liliang8858** [comment] 2022-05-07 01:21
logs   
```
about to fork child process, waiting until server is ready for connections.,
forked process: 79,
child process started successfully, parent exiting,
Waiting 10s for MongoDB to start with Replica Set,
MongoDB shell version v4.4.13,
connecting to: mongodb://localhost:27017/appsmith?compressors=disabled&gssapiServiceName=mongodb,
Implicit session: session { "id" : UUID("f0539772-9c25-44ed-bac0-846bcc2a7a5d") },
MongoDB server version: 4.4.13,
{,
	"info2" : "no configuration specified. Using a default configuration for the set",,
	"me" : "localhost:27017",,,
1,
},
{"t":{"$date":"2022-05-07T00:50:16.594+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"},
{"t":{"$date":"2022-05-07T00:50:16.598+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"},
{"t":{"$date":"2022-05-07T00:50:16.599+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."},
killing process with pid: 79,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
Initialize .env file,
Load environment configuration,
Checking environment configuration,
Checking APPSMITH_MONGODB_URI,
Detected local MongoDB,
Initializing local database,
Checking initialized database,
Mounting Let's encrypt directory,
rm: cannot remove '/etc/letsencrypt': Directory not empty,
```

**Comment by sharat87** [comment] 2022-05-09 01:47
Hey @liliang8858, sorry you are facing trouble with this. Can you share what OS you are running on? Do you have an existing `stacks` folder in the current folder? If yes, does it have a non-empty folder called `letsencrypt`?

**Comment by liliang8858** [comment] 2022-05-09 03:51
> Hey @liliang8858, sorry you are facing trouble with this. Can you share what OS you are running on? Do you have an existing `stacks` folder in the current folder? If yes, does it have a non-empty folder called `letsencrypt`?

![image](https://user-images.githubusercontent.com/38367404/167337639-6ede7667-533e-4180-881d-4e27c2c82ed2.png)

**Comment by liliang8858** [comment] 2022-05-09 03:54
linux 
```
Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Mon Oct 24 16:09:20 UTC 2016
```

 docker version
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by sharat87** [comment] 2022-05-16 10:47
Hey @liliang8858, I see that your version of Docker is quite old. Docker `1.13.1` was released in early 2017, and there's been over two dozen versions released. I suspect this is part of the reason we aren't able to reproduce the problem. Can you upgrade your Docker version to `20` or higher please? Preferably, `20.10`. Please let us know if you see the same problem there as well. Thanks.

**Closed** 2022-05-16 11:49 UTC
Labels: Bug, Needs Triaging, Docker, DevOps Pod
