### ISSUE TITLE
Task: add source event for all ways templates can be forked on the platfrom.

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#31038] opened 2024-02-11 01:44 UTC
Based on the conversation [here](https://www.notion.so/appsmith/Test-party-Create-apps-from-template-in-homepage-ff8c518c28b549b2b29528ae951082e1?pvs=4#f55dc094e42749679d9be86c8b621abd)

We need to differentiate source of template forking events.
1. We need to update the backend api to accept this.
2. update all places in UI where we call this API - we have to be thorough about this.

**Comment by rahulbarwal** [comment] 2024-02-11 01:46
also, I think there is a larger problem of saving name during fork template event in the backend. 

See if it makes sense to send the template name from the UI and save in the fork event. @AnaghHegde

**Comment by AnaghHegde** [comment] 2024-04-03 14:31
Duplicate of #32018

**Closed by AnaghHegde** 2024-04-03 14:31 UTC
Labels: Task, Templates Pod, Templates
