### ISSUE TITLE
[Bug]-[300]:Default value is displayed on widget even when it is not available in drop-down options

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12225] opened 2022-03-24 11:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Uploading Screenshot 2022-03-24 at 2.28.19 PM.png…]()

https://watch.screencastify.com/v/rTmvAKEDYT6lAqffXIXq

### Steps To Reproduce

1. Drag and drop a Select/multi-select/TreeSelect/Multi tree select
2. Add any random value in Default Value
3. Observe that it is shown in widget even when the default value is not present in drop-down options

### Version

Cloud

**Comment by Tooluloope** [comment] 2022-03-30 09:34
@dilippitchika Should we close this issue.
Since this was intended

**Comment by dilippitchika** [comment] 2022-03-30 09:42
@Tooluloope i think we should be smarter about this because it's causing frequent confusion.

Here's my suggestion on how to fix this -
1. When user provides only value and not {label, value} in default, we check if the option exists. If it doesn't then we don't show this in default. 
2. When user provides {label, value} for default, we check if the option exists. If it doesn't then we NOW show this in default. This is the only scenario for a user to add default when they have configured the server side filtering in the widget. 
This is applicable both for select and multi-select widgets.

Let me know your thoughts

**Comment by Tooluloope** [comment] 2022-03-30 10:30
So Conclusion here was to enable this defaultValue caching only when Serverside Filtering is enabled. But once Serverside filtering is false, we do a strict check to know if the default value is in the list of options, and Only the default values in options would be displayed.

CC @dilippitchika @somangshu

**Comment by dilippitchika** [comment] 2022-04-07 05:15
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 150 |
| Effort (months)  | 1 |

**Comment by techbhavin** [comment] 2022-04-20 06:37
this issue is covered in PR[#13079](https://github.com/appsmithorg/appsmith/pull/13079)

**Comment by Tooluloope** [comment] 2022-04-26 09:30
# QA Note

The following should be tested in the PR

- For all the Select Family, The value must be strictly checked against the options except if serverside filtering is enabled, i.e all selectedValues/DefaultValues must exist in the options for it to be reflected in `selectOptionValue`
- Connecting the defaultValue from a Table or external source, should reflect the expected value in `selectOptionValue`
- Getting the expected value in a Form.
- For Treeselect widgets, The Display Mode should reflect the right value

cc @ashit-rath @wmdev0808 @somangshu @dilippitchika

**Comment by dilippitchika** [comment] 2022-04-27 04:28
Adding my notes here for default value for testing- @Tooluloope @wmdev0808 @ashit-rath

## Default value with server side filtering OFF- Select widget
1. Supported formats - value, {label,value}
2. When value is not present in the list of options 
     - No default should be shown in the select widget
     - The default value field in property pane should show an error
3. When label is not present in the list of options but value is present
    - The label is shown from the list of options and NOT from the label added in the default field
       - The selectedOptionLabel and selectedOptionValue should populate data of value from default and label from options  

## Default value with server side filtering ON - Select widget
1. Supported formats - value, {label, value}
2. When value is present in list of options
    - Similar to server side filtering OFF; We show the default from the list of options
    - If label is not same between options and default {label, value}; We show the default from the list of options
       - The selectedOptionLabel and selectedOptionValue should populate data of value from default and label from options 
4. When value is not present in list of options
    - If the format is <value> and not {label,value} 
        - No default should be shown in the select widget
        - The default value field in property pane should show an error 
    - If the format is {label, value} 
       - The default will be shown in the list of options using the label field from {label, value}
       - There should be no error in the default field
       - The selectedOptionLabel and selectedOptionValue should populate data from {label, value}

**Comment by ashit-rath** [comment] 2022-05-02 07:05
@dilippitchika Just double-checking, this is also true for multi-select?

**Comment by dilippitchika** [comment] 2022-05-04 05:41
@ashit-rath almost, but this is only for select. For multiselect, i will add more notes.

**Comment by ashit-rath** [comment] 2022-05-04 05:49
@dilippitchika Please do consider all the Select family widgets just for the sake of future reference.

**Comment by dilippitchika** [comment] 2022-05-04 06:02
@ashit-rath the challenge i see is with the CSV behavior in multiselect. I need some clarity there on what we are supporting currently in default values - @Tooluloope can you let me know?

**Comment by dilippitchika** [comment] 2022-05-04 06:36
Adding my notes here for the part i am confident of for Multi select widget

## Default value with server side filtering OFF- MultiSelect widget
1. Supported formats - `[values]`, `[{label,value}]`
2. When any value from default is not present in the list of options
   - The value will not be shown by default in the multiselect widget, if all values are missing no default should be multiselect widget
   - The default value field in property pane should show an error
      - Error message - "Some or all default values are missing from options. Please update the values."
3. When the label is different from the one configured in the default and the options
    - The default label(s) will be shown from the options and not from the data in the default values field.
       -  The selectedOptionLabels and selectedOptionValues should populate data of value from default and label from options

## Default value with server side filtering ON- MultiSelect widget
1. Supported formats -`[values]`, `[{label,value}]`
2. When value is not present in list of options
    - Format is `[values]`, then we throw an error message 
       - Default value is missing in options. Please use `[{label : <string | num>, value : < string | num>}]` format to show default for server side data
    - Format is `[{label,value}]` then we show the these as the default labels and values in the multi-select widget
3. When value is present in list of options
    - Similar to server side filtering OFF; We show the default from the list of options
    - If the label is different between default and the option then, the default label(s) will be shown from the options and not from the data in the default values field 
       -  The `selectedOptionLabels` and `selectedOptionValues` should populate data of value from default and label from options

Not considering CSV here, need discussion on that.

**Comment by dilippitchika** [comment] 2022-08-08 05:53
@Tooluloope @vivekverma2312 I think this issue is linked to select default changes, please verify this and and link the PR here as well.

**Comment by Tooluloope** [comment] 2022-08-08 10:25
fixed in #15133

**Closed** 2022-08-08 10:25 UTC
Labels: Bug, Select Widget, App Viewers Pod, High, Production, MultiSelect Widget, MultiTree Select Widget, TreeSelect
