### ISSUE TITLE
[Bug]-[80]:Inaccessible git branch when the pages in the branch differ from the ones on master

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#11889] opened 2022-03-16 06:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Lost access to branch, when I deleted the pages that were on master, in the branch.

### Steps To Reproduce

1. Create a new application.
2. Check out a new branch.
3. Create a new page(Page2) in the branch and set it as homepage.
4. Delete the other page (Page1).
5. Now switching back to master will give a 404.
6. Go to applications dashboard and launch the application in edit mode. Lands on master branch.
7. Try checking out the branch created earlier. -> 404.

The branch is lost forever. (Workaround is the remove "/pages/:pageId" info from URL)

### Version

Cloud

**Comment by vuiets** [comment] 2022-03-18 12:35
Thanks for reporting this @arunvjn. Was able to reproduce the former issue but not the latter one, ie,
> 7. Try checking out the branch created earlier. -> 404

Checking out the branch created earlier redirected me to the branch with Page 2 as home page.

**Comment by abhvsn** [comment] 2022-03-21 09:08
I think this is a common scenario to get `Resource not found` exception after we have launched the git. In above case it goes beyond the recovery state, but the root cause is the same that user have deleted the resource in the sub-branch. I propose following solution for these cases:
> We should have a redirect CTA to go back to the applications default page instead of the home page that we have today.

![Screenshot 2022-03-21 at 2 37 18 PM](https://user-images.githubusercontent.com/41686026/159231622-aa22b1d5-6dba-4950-b6e6-cea8fb94edfb.png)

**Comment by arunvjn** [comment] 2022-03-21 09:24
I like the CTA to take the user to the default page in their branch but if that is the only CTA, can we not make it the default behaviour ? 
Or should we show a list of available pages instead ?

**Comment by abhvsn** [comment] 2022-03-21 09:36
I'm more inclined to the CTA option as this will give you the clear idea that you should not expect the same resource in other branch and this can happen to any resource like JSObject, action etc But @vuiets would love to have your opinion as well

**Comment by arunvjn** [comment] 2022-03-21 13:27
@vuiets Sorry I missed your previous comment. You are right about the 2nd point. I am unable to reproduce it any more. Must be a recent change I guess. 

Can you verify if you are actually getting the home page of the branch ? For me it loads the home page of master itself when I switch branch after I follow the replication steps.

**Comment by vuiets** [comment] 2022-04-18 21:13
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10 |
| Effort (months)  | 0.25 |

People who have created branches: 50
About 20% to delete existing pages on different branches: 10

**Comment by AnaghHegde** [comment] 2022-04-26 03:12
@abhvsn Is this bug still valid?

**Comment by abhvsn** [comment] 2022-04-26 10:09
Yes this is still valid, try to follow the specs provided in the description but currently we really don't have any solution on this

**Comment by hiteshjoshi** [comment] 2022-11-25 07:40
@RakshaKShetty can you verify this? We are not sure if this happens right now too. Closing this, but if you find this happens, please reopen and let us know.

**Closed by hiteshjoshi** 2022-11-25 07:40 UTC
Labels: Bug, High, Needs Triaging, Git Version Control, Team Managers Pod
