### ISSUE TITLE
[Bug]: Template's image and icon is broken.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#23303] opened 2023-05-13 08:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/109572422/95012e6d-549e-49e3-b24f-3caf0efb23ca)

<img width="609" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/a1891c83-ae4b-473e-9173-dcf8bfe28720">

### Steps To Reproduce

Navigate to the Maintenance order Management template and notice the broken image and icon

### Environment

Release

### Version

Cloud

**Comment by ezioishan** [comment] 2023-05-13 18:07
Hey, I'm new here and was trying to replicate this issue in my local setup but was unable to do so. In Templates >> Maintenance Order Management, checked on different device widths, all seems fine to me. Am I missing something?

**Comment by harshitpandey0426** [comment] 2023-05-13 19:15
@ezioishan I am able to reproduce this. Pull in the recent changes and search for Maintenance Order Management template under template section

**Comment by jacquesikot** [comment] 2023-05-15 10:07
@laveena-en I am not able to reproduce this. All template images and icons work fine. Is this still an issue?

**Comment by rahulbarwal** [comment] 2023-05-24 05:23
Hey @harshitpandey0426, @laveena-en  we were not able to reproduce this neither in local nor on app.appsmith.com. 

Can you please check this once after taking latest changes from release.

**Comment by harshitpandey0426** [comment] 2023-05-24 08:03
@rahulbarwal I could still see the broken image icon
<img width="1470" alt="image" src="https://github.com/appsmithorg/appsmith/assets/54776298/63d9f501-c4c1-4e61-918a-aa5641655036">

**Comment by rahulbarwal** [comment] 2023-05-24 08:10
@harshitpandey0426 Please put your observations for these 2:
1. Can you try hard refreshing the page?
         a. If this still does not work, can you inspect the image url for the broken image and pass it?
2. Please check for same in app.appsmith.com

**Comment by harshitpandey0426** [comment] 2023-05-24 08:32
@rahulbarwal 
1. I have done hard refresh and manually disabled cache for browser, but still I see this issue.
2. I don't see this in production.
PS:
I will try passing broken image url and let you know.
 I wonder why others are not able to reproduce this.

**Comment by harshitpandey0426** [comment] 2023-05-24 08:58
@rahulbarwal 
Any help from which file these images are getting loaded? I don't see any local reference
![image](https://github.com/appsmithorg/appsmith/assets/54776298/12b812ec-0715-42a8-b458-182e09c87bb7)

**Comment by harshitpandey0426** [comment] 2023-05-24 10:08
@rahulbarwal Yeah it works fine now. If possible please let me know the fix you made or the PR you merged.
Thanks

**Closed** 2023-05-24 10:15 UTC
Labels: Bug, Release, Needs Triaging, Templates pod

**Comment by rahulbarwal** [comment] 2023-05-24 10:43
No PR as such, just updated the correct data.
