### ISSUE TITLE
[Bug]: Gsheet : The user see forbiden error on upgraded instance 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#26409] opened 2023-08-17 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to Gsheet DS it is observed that the user is authorised but observes an error being displayed to the user 

### Steps To Reproduce

1) Navigate to the Edit of App
2) Click on any Auth Gsheet 
and observe the error being displayed 
<img width="1792" alt="Screenshot 2023-08-17 at 1 25 46 PM" src="https://github.com/appsmithorg/appsmith-ee/assets/132243297/992822f8-4bab-48b4-8f2b-06f92d82c5b7">

### Public Sample App

https://ee-2077.dp.appsmith.com/

### Environment

Release

### Version

Rgression DP

**Comment by sneha122** [comment] 2023-08-23 10:21
This issue is reproducible on instance https://release-ee-https.appsmith.com/. The issue occurs because this instance is not correctly configured to point to cloud-services correctly, hence trigger API used to fetch data about spreadsheets and sheets fail and throw 403 forbidden error. If we tried to create google sheet datasource on the instance, it leads to error like below:
<img width="821" alt="Screenshot 2023-08-23 at 3 44 50 PM" src="https://github.com/appsmithorg/appsmith/assets/30018882/3c4ce8cd-b976-45a7-b389-9ed850751875">

@prapullc will be checking with @RakshaKShetty on how this instance gets set up, we can close this issue as it looks like an issue with setup

Cc: @rohan-arthur

**Closed by sneha122** 2023-08-23 10:21 UTC
Labels: Bug, High, Needs Triaging, Google Sheets, BE Coders Pod, Integrations Pod
