### ISSUE TITLE
[Bug]: Select widget with filtering on has weird width issue for options

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#9375] opened 2021-11-25 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/6636360/143428200-f4c59171-2611-498d-a6cf-b8673fbe64cf.png)

### Steps To Reproduce

1. Drop a select widget
2. Enable filtering option
3. Reduce the width of the select widget
4. Notice the width of options

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-05-11 05:29
Unable to reproduce now, closing this


<img width="216" alt="Screenshot 2022-05-11 at 10 58 57 AM" src="https://user-images.githubusercontent.com/19730984/167775479-740927a5-343d-4435-a311-10f5800f8548.png">

**Closed by dilippitchika** 2022-05-11 05:29 UTC
Labels: Bug, Select Widget, App Viewers Pod, UI Building Pod, Needs Triaging
