### ISSUE TITLE
Communication between embedded Appsmith dashboard iframe and parent applications

### ISSUE THREAD

**Issue by nishantag9** [appsmithorg/appsmith#7241] opened 2021-09-08 09:20 UTC
I was trying to create a hybrid dashboard with part custom react code and part Appsmith dashboards embedded as iframe in the main application. I am facing an issue of maintaining communication between the Appsmith iframe and parent application. 
Possible ways of communication currently limited to passing data via query params in the iframe url. 

It would be helpful if the embed iframe supported post messages/ and can listen to posted messages so that we can maintain communication between the parent and the iframe. 

This feature might be helpful in instances were Appsmith page is being used as a listing table and on click of a row we need to perform some action on the parent page (like routing, etc.) 

Also if Communication and listeners on messages is possible it will be possible to trigger data resources in the embedded Appsmith dashboard from the parent itself.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-08 10:34
@nishantag9 thank you for the feature request! 
@somangshu @jsartisan can we add an option for onMessageReceived in the page settings?

**Comment by somangshu** [comment] 2021-09-08 10:47
@Nikhil-Nandagopal I think having JS or actions executing on the page setting is a platform challenge right now and we do not have it prioritised. Also what @nishantag9 requested for is more like using postMessage in the Appsmith application to receive that in the parent application, that the other way round.

This ideally should also be possible in the JS editor as well given that we allow the window object as postMessage API in a part of it.

**Comment by Nikhil-Nandagopal** [comment] 2021-09-08 10:50
@somangshu I think both are needed to be able to post message as an action and to be able to list to posted messages in the page. Lets discuss the implementation challenge

**Comment by somangshu** [comment] 2021-09-08 10:55
Whats the use case for posted messages in the page? If i want to exec JS  on a certain action on the appsmith page, Ill need to postMessage to the parent!

**Comment by Nikhil-Nandagopal** [comment] 2021-09-08 11:20
@somangshu an event in the outer page may want to trigger an action in the embedded appsmith page

**Comment by nishantag9** [comment] 2021-09-13 09:18
@Nikhil-Nandagopal That sounds about correct. By implementing the post message feature in iframe we can have two way communication between the parent web-app and embedded appsmith iframe.

**Comment by Nikhil-Nandagopal** [comment] 2021-12-06 11:41
another request to pass data from the embedded appsmith app to the parent application

**Comment by unknown1337** [comment] 2022-03-12 12:48
@jsartisan  
@somangshu
@Nikhil-Nandagopal 

Do I interpret (given the "test" label added on the 5th of Jan) correctly that you're working on a mechanism for bi?? directional communication between the appsmith parent application and a child js application executed from within the Iframe? Thanks:)

**Comment by somangshu** [comment] 2022-03-14 10:24
Hey @unknown1337, this is not yet prioritised, Ill try and collect more information on what is required here to proceed!

**Comment by billyrudi** [comment] 2022-03-16 18:59
Hi, I do you have news?

**Comment by unknown1337** [comment] 2022-03-30 11:50
@rohan-arthur , do you have an update on the timeline? :) thanks!

**Comment by rohan-arthur** [comment] 2022-03-30 12:13
@unknown1337 Ah sorry about the delay, was focusing on other things. Please allow me a couple of days to get back to you on this.

**Comment by ajinkyakulkarni** [comment] 2022-04-01 05:56
duplicate of https://github.com/appsmithorg/appsmith/issues/2268

**Comment by rimildeyjsr** [comment] 2022-04-01 06:14
I will remove that and track development here

**Comment by unknown1337** [comment] 2022-04-01 07:51
Thanks @rohan-arthur , great to hear! Can you give me some rought idea when it will be released to 'your cloud hosted appsmith instance'? is this e.g. 2 weeks, 2 months or 6 months? Thanks!

**Comment by rimildeyjsr** [comment] 2022-04-15 08:58
Splitting this issue into 2 - this ticket contains adding post message as a global function and 
[this ticket has the adding of event listener part ](https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/12953)

**Comment by dncpax** [comment] 2022-06-24 08:51
hey. Does this implementation also allow for an iframe widget in appsmith to receive postmessages?

**Comment by somangshu** [comment] 2022-06-24 09:02
@dncpax I think that is already implemented from before, the iframe can receive a postMessage, you will find an internal property `message` which will give you the object and also another property `onMessageRecived` that will allow you to trigger events when you receive a message from the parent app / web page

[Docs here](https://docs.appsmith.com/widget-reference/iframe)

**Comment by dncpax** [comment] 2022-06-24 09:44
That's the other way around... I'm referring to appsmith sending messages to the iframe.

**Comment by somangshu** [comment] 2022-06-28 12:21
@dncpax My bad on understanding this incorrectly, I got to understand you use case now, This issue particularity will resolve sending messages to a website / app where an appsmith app is embedded in an iFrame. 

You asked for sending the message to an iframe embed in appsmith, that will be taken care as part of #5390, We are figuring out the best way to achieve this right now, please give any suggestions you might have.

**Comment by wemod123** [comment] 2022-08-10 10:25
🎉🎉🎉 Is there any estimated release time? 
Really nice if appsmith can postMessage to parent frame

**Comment by rimildeyjsr** [comment] 2022-08-11 08:42
@wemod123 - We decided to revert our PR and add a few more additions to this feature. It will take around 2-3 weeks for us to implement, test and then deploy the feature. Thank you for your patience while we implement this feature!

**Closed** 2022-10-20 09:29 UTC
Labels: Enhancement, JS Evaluation, UI Builders Pod, Medium effort, FE Coders Pod
