### ISSUE TITLE
[Task]: [Tech Debt] Refactor export / import flow on API server into smaller functions

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#18588] opened 2022-11-30 17:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Currently, the export / import code flow on API server has turned into giant monolithic function. Need to refactor the code flow for better understanding and readability.

**Comment by trishaanand** [comment] 2022-12-23 07:14
Duplicate of 18501

**Closed by trishaanand** 2022-12-23 07:14 UTC
Labels: Backend, Task, Import-Export-App, Team Managers Pod, Tech Debt
