### ISSUE TITLE
[Feature]: Support multi-select widget inside the table

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16026] opened 2022-08-16 06:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For editable cells we need a way to display and support multiselect widget in the table

### Why should this be worked on?

This enables users to edit array values in the table

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_56ato)

**Comment by Nikhil-Nandagopal** [comment] 2024-02-02 06:57
Duplicate of #20076

**Closed by Nikhil-Nandagopal** 2024-02-02 06:57 UTC
Labels: Enhancement, Table Widget, App Viewers Pod, potential-duplicate, MultiSelect Widget
