### ISSUE TITLE
[Feature] Cron jobs

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1951] opened 2020-11-27 11:27 UTC
## Summary

As a user, I want to be able to run & manage cron jobs on Appsmith. I would like to define a cron schedule on which an action/workflow will get executed.

## Motivation

A lot of tools require actions such as importing of data, executing workflows on a regular basis. Cron jobs are integral to powering such flows on a predictable basis.

**Comment by Nikhil-Nandagopal** [comment] 2021-02-01 16:26
Closing as it's a duplicate of #738

**Closed by Nikhil-Nandagopal** 2021-02-01 16:26 UTC
Labels: Enhancement, advanced, community
