### ISSUE TITLE
[Bug]-[508]:Camera widget bugs

### ISSUE THREAD

**Issue by osloma** [appsmithorg/appsmith#14069] opened 2022-05-24 21:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We can see that when Appsmith is run on an Android, pictures are not having all the quality than the camera on the phone can capture. Also, using iPhone, pictures taken are only a completely black image where nothing can be seen

### Why should this be worked on?

The use case for this is to capture pictures of documentation (like bills, receipts, etc.) that should be in a resolution that can be read easily. 
In our case, we are storing the pictures in Cloudinary but pictures have reduced size (around 350x350 pixels) that make them very hard to read their content (letters cannot be read easily). We have tried to change the resolution of the camera on the phones with no result

So far we are finding:
* On Android, it works but we get low resolution pictures
* On iPhone, pictures are completely black

The goal will be to be able to select the resolution required on the picture before it's taken. It could be done either from the widget (more preferred way) or from the running camera on the application.

Thank you so much!

**Comment by Nikhil-Nandagopal** [comment] 2022-05-25 13:21
@osloma thank you for the information. We'll debug this and let you know what is going wrong

**Comment by dilippitchika** [comment] 2022-05-26 12:18
@vivekverma2312 can you ask someone to test on an android phone? 

It is broken in iphone for sure.

**Comment by dilippitchika** [comment] 2022-05-30 09:03
Found a set of issues
Apple devices - 
1. [Blocker] Iphone safari and chrome unable to capture image in camera in iOS 14.4
2. [Blocker] In Ipad the camera goes black after capturing the image
https://www.loom.com/share/7747e01f5ba24560b35dee884af79e79

Android devices - 
1. [Blocker] The back camera feed seems to be mirrored.
6. [Blocker] When I tap the full screen, the tooltip stays open and I am unable to see any other button
8. [Blocker] When I turn on/off the video, the icon jumps a few pixel to the top right and back.
9. [Blocker] In full screen mode I’m not able to switch the camera (the dropdown doesn’t open)
10. [Blocker] Weird noise after taking a picture
11. [Blocker] Low resolution of the image leading to hazy images for app developers 

Enhancements 
1. [Enhancement] Switching between back and front camera is a bit inconvenient. My general reflex is flip with one press but here I have to click a dropdown and then select the camera
2. [Enhancement] When I take a photo, a check and a dismiss icon appears, which was fine but the reset of the actions were still visible like the turn on/off video, switch camera which IMO is not relevant when I try to save/discard the photo.
3. [Enhancement]  I feel like the controls should not be a part of the camera view port. As the controls are white in color, if I point at a light background; it’s really hard to locate the controls. This seems to be fine in the full screen mode.
4. [Enhancement] All the buttons are very closed together, it always felt like I’m gonna press something else
5. [Enhancement] The button to take a picture should be a bit bigger  so that the press area is more prominent

Slack discussion thread - https://theappsmith.slack.com/archives/C02JV8G1MP0/p1653567793725609
Library issue - 
https://github.com/mozmorris/react-webcam/issues/57

**Comment by dilippitchika** [comment] 2022-05-30 09:05
@techbhavin please start triaging all the blockers mentioned first and leave a comment on if all these blockers can be fixed or not. If you need any help with devices, do reach out to me or @vivekverma2312 

Here's the sample app - https://app.appsmith.com/app/untitled-application-5/page1-628f70677901344ba8d2e7cb

**Comment by techbhavin** [comment] 2022-06-03 13:05
@dilippitchika  Plz refers below mention blocker we can fixed.

Apple Devices 
1 . We can Fix 
2. Not Sure 

Android Device : 

1. it is working as expected. we have the property for turning on the mirror
2. can we change the tooltip position to the right? or do we have any approach?
3. We can Fix  
4. We can Fix 
5. Not able to reproduce. (Look like it is the device-specific issue)
6.  Not able to test in Device

**Comment by dilippitchika** [comment] 2022-06-14 05:14
Regarding

> Android Device :
> can we change the tooltip position to the right? or do we have any approach?
Why is the tooltip staying open, is there a reason for it? Tooltip should only open when we have clicked on it right?

Low resolution of the image leading to hazy images for app developers -- Please talk to ashit once, he can show this to you

**Comment by dilippitchika** [comment] 2022-06-14 05:15
Scope:

1. Fix all the items which are marked as "we can fix" by Bhavin
2. Check the rest of the blockers with QA team's help if they are reoccurring 

@techbhavin @vivekverma2312

**Comment by techbhavin** [comment] 2022-06-16 05:33
> Why is the tooltip staying open, is there a reason for it? The tooltip should only open when we have clicked on it right?

here is the library issue tooltip working fine with a click but there is an issue while touching.
@dilippitchika

**Comment by dilippitchika** [comment] 2022-06-24 07:02
@techbhavin what is the suggestion regarding tooltip and fullscreen library? I thought there was a discussion around it.

**Comment by techbhavin** [comment] 2022-06-24 08:58
@dilippitchika  
> about the tooltip and fullscreen

- For the tooltip,it is standard behavior with a Mobile Device. here tooltip is visible with long touch and when we touch again on anywhere on the screen it will hide again. At the moment we don’t have any alternative solutions for this.  
  
- In full-screen mode, we can’t switch the camera because the popover is not visible.  so instead of adding a popover to change the camera can we add a standard round icon for the swap camera? like below-attached image

<img width="285" alt="image" src="https://user-images.githubusercontent.com/58818598/175493302-23890476-3a14-4c9e-85b8-9001857c95d6.png">

**Comment by techbhavin** [comment] 2022-06-24 12:03
@dilippitchika  
Yes, we can remove fullscreen but instead of  can we do the similar like  [webcamera](https://webcamera.io/) 

and Currently, we have a tooltip on capture and a fullscreen icon so can we remove this tooltip?

**Comment by dilippitchika** [comment] 2022-06-26 06:51
> but can we do a similar like [webcamera](https://webcamera.io/) to show list of available camera

Are you referring to how it shows the settings? If so, then we can proceed from a product standpoint, but i thought there is a tech limitation.

> and Currently, we have a tooltip on capture and a fullscreen icon so can we remove this tooltip?
Yes we can remove this for now

**Comment by dilippitchika** [comment] 2022-06-26 06:52
@vivekverma2312 @chandannkumar let's discuss this issue once on a call, i believe this needs a small discussion to align and decide if we need more issues created from this issue.

**Comment by vivekverma2312** [comment] 2022-06-28 06:18
@techbhavin On ios it's almost impossible to use camera widget
1. Controls are not visible on the widget
2. Image click makes the widget black
3. Changing from camera to video also makes the widget black

ios:15.5

https://user-images.githubusercontent.com/83569920/176106817-9b9453d5-7fdb-4635-b62f-b7a716d785bb.MP4

**Comment by chandannkumar** [comment] 2022-06-28 07:26
Moving this issue to in progress due to blockers and callouts. There is also a merge conflict in this PR

**Comment by techbhavin** [comment] 2022-07-07 05:22
As per our discussion, 

- I have to put the camera rotate icon instead of the camera menu (list of the camera). but there is one more functionality that is camera turns off. so when we will put the camera rotate icon then how to manage camera turn-off functionality. 
- Now one more dought is what should we do for the audio menu that is shown in video mode of the camera widget and also the same issue will happen with audio mute functionality like as camera turn-off.

![image](https://user-images.githubusercontent.com/58818598/177697036-ea878b6c-61c2-42f5-86ae-dad36f233c57.png)


@dilippitchika

**Comment by techbhavin** [comment] 2022-07-07 10:24
- Fixed the camera unable to capture images on ios devices.
- Fixed the camera goes black after capturing the image in ios devices.
- Fixed the changing from camera to video and also makes the widget black in ios devices.
- Removed the tooltip so it can not cause tooltip-related issues.
- Give the mirror functionality in the camera widget.
- Fixed the getting weird noise after taking the picture.
- Improved the picture quality of the camera.
- Fixed the camera widget break when we switch the camera or take pictures after switching the camera.

@chandannkumar @vivekverma2312

**Comment by techbhavin** [comment] 2022-07-10 12:21
- Fixed the show video/audio input menus in full-screen mode.
- Fixed to show the control panel in the full-screen mode of the safari browser.

@chandannkumar @vivekverma2312

**Comment by chandannkumar** [comment] 2022-07-26 11:24
Observation:
While recording a video from from front camera as soon as i switch camera to rear, the video stops recording and saves automatically but the recording timer is still continues on camera widget. 

https://images.zenhubusercontent.com/275993885/276d845f-802b-4325-b048-1cd48faa2122/screenrecorder_2022_07_26_16_33_41_679_0_.mp4

@techbhavin Not sure about the video recording stops automatically on switching camera is a bug or an expected behavior

**Comment by techbhavin** [comment] 2022-07-26 13:41
- Fix the camera switching issue when recording video

@chandannkumar

**Comment by vivekverma2312** [comment] 2022-07-27 06:38
@techbhavin On ios when my mic is disabled and I record a video the sound is getting recorded.

**Comment by techbhavin** [comment] 2022-07-29 07:16
For now, we are removing the video/audio mute buttons for ios devices because of an issue with the Safari browser. whenever we get the solution for that at that time we fix that.

@chandannkumar @vivekverma2312 

cc: @dilippitchika @somangshu

**Closed** 2022-08-03 06:02 UTC
Labels: Enhancement, App Viewers Pod, High, community, Camera Widget
