### ISSUE TITLE
[Bug]: MongoDB when views are present in DB, structure is not fetched

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#33829] opened 2024-05-29 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have views in my mongoDB database along with collections, the `getStructure` API fails, this the collection dropdown in mongo query is empty and so in one click binding. This prevents me from using appsmith functionalities of one click binding and query.

### Steps To Reproduce

1. Create a mongoDB database with views and collections
2. In appsmith create mongoDB datasource with config from above DB
3. Create a new query, observe the collection dropdown

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud - 1.26.0

**Comment by raushan3737** [comment] 2024-08-13 05:52
Hi @sneha122 , @Nikhil-Nandagopal , I have reproducing the issue but it is working fine for the view as well.
Issue is not re-producable, It is working fine.

**Comment by Nikhil-Nandagopal** [comment] 2024-08-13 07:13
We can close this since we're removing the one click binding feature

**Closed by Nikhil-Nandagopal** 2024-08-13 07:13 UTC
Labels: Bug, Production, Needs Triaging, Mongo, Query & JS Pod, Medium, Integrations Product

**Comment by SplendidFarzad** [comment] 2024-10-23 14:27
Hi @Nikhil-Nandagopal  @raushan3737  I originally created the issue linked in the thread. The issue is very persistent and has not been resolved. I initially showed the problem once to @sneha122 , I can show you again the error. I am a devops engineer andh ave tested this on multiple different instances of mongo, it is persistent. Would love to give a quick demo.
