### ISSUE TITLE
[Bug]: Auto Height for container widget is not working as expected

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#22411] opened 2023-04-14 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The container fails to expand in preview mode when hidden table is visible.

### Steps To Reproduce

1. Create a container
2. Add a button to facilitate the visibility toggle using storeValue
3. Add a table and set its visibility based on the above toggle
4. Go to preview mode observer how container doesn't expand even if the table is in visible state.

Caveat - I couldn't reproduce this issue on a brand-new app. Although, I produced this in an old app by creating a new page

### Environment

Production

### Issue video log

https://www.loom.com/share/93781c74dd914e5e82cee26d8e78b58b

### Version

v1.9.15

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9cymk)

**Comment by thanhloc1993** [comment] 2023-05-17 09:26
same issue!

**Comment by thanhloc1993** [comment] 2023-05-17 12:21
Steps To Reproduce
1. Create a container
2. Add list widget
3. Add image below list widget
4. set visible list = false
Go to preview mode and see the image still in bottom of container
![2023-05-17_19-20](https://github.com/appsmithorg/appsmith/assets/91037551/9c2a7ab3-f5f6-4353-9f65-0b760ea7d296)

**Comment by thanhloc1993** [comment] 2023-05-18 04:16
I think the reason is old app misses config collapseInvisibleWidgets.
https://github.com/appsmithorg/appsmith/pull/20118/files#diff-5213fb244bf59ac26b2b2310ac284bc69b4c811b39b8fe1557b04bfc7adf9374R30

**Comment by ramsaptami** [comment] 2024-07-16 11:03
this is a non-issue on anvil layout system hence closing it

**Closed by ramsaptami** 2024-07-16 11:03 UTC
Labels: Bug, Production, Needs Triaging, UI Builders Pod, Medium, Auto Height
