### ISSUE TITLE
[Bug]API Status code overlaps with the text log in the minimized mode

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4926] opened 2021-06-04 09:04 UTC
## Description
Release Environment - API - It is observed that when the API query is executed in the minimized mode the status code and the Log text overlaps

**Expected Result:**
Text should not overlap and should be clearly visible 

**Actual Result:**
Status code text overlaps with log text when api query is executed in minimized mode

### Steps to reproduce the behaviour:

1.Launch Appmsmith app in the release environment
2.Expand API and click on new api
3.Minimise the screen to 60-70%
4.Pass the following valid API header - https://dev-bprlwumm.us.auth0.com/api/v2/client-grants
5.Click save as Datasource
6.Choose the authentication type as - Oauth2.0
7.Pass the following valid authentication code - https://dev-bprlwumm.us.auth0.com/oauth/token
8.Pass the following client id - zxA3X7pNdK1S8Q6TNgIy0IeX8uTF2RDv
9.Pass the following valid client secret - PSzJHUZ-0slfHms8FjKWaABy4UURvFK2VLQp8KcZ_nmoROHOao765R4zwFLlQtrR
10.Pass the following valid audience - https://dev-bprlwumm.us.auth0.com/api/v2/
11.Click on save
12.Execute the API and observe the status code

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release
<img width="1280" alt="Screenshot 2021-06-04 at 2 27 22 PM" src="https://user-images.githubusercontent.com/35128442/120776473-ea564300-c541-11eb-8b84-8fb0ba0c9024.png">
]

**Comment by ApekshaBhosale** [comment] 2021-09-29 10:04
Needs CSS style update. File -  [ApiResponseView.tsx](https://github.com/appsmithorgappsmith/app/client/src/components/editorComponents/ApiResponseView.tsx)

**Comment by Nikhil-Nandagopal** [comment] 2021-10-06 09:41
Duplicate of #6862

**Closed by Nikhil-Nandagopal** 2021-10-06 09:41 UTC
Labels: Bug, Good First Issue, API pane, Actions Pod, Low, BE Coders Pod
