### ISSUE TITLE
[Bug] Improper renaming/refactoring of strings that match with names of widgets

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5657] opened 2021-07-07 08:18 UTC
## Description

I was helping a user debug a cyclic dependency problem. As soon as I added "atm" key in a widget binding (which is returned from the API), the error showed up. After a lot of time, I figured out that the user also has the switch widget called "atm" which is referring to the widget. **When I tried to rename the switch from "atm" to "atm_switch, the keys in my JSON object were also renamed.**

For more information, please refer to this internal thread https://theappsmith.slack.com/archives/C01HXJPFWBC/p1625498880378500

### Steps to reproduce the behaviour:

1. Create a widget called "atm"
2. Create another widget that is in JS bindings use the "atm" key 
3. Also when you rename the widget called "atm", you will notice the string keys called "atm" are also replaced

 
### Important Details

- Version: Cloud
- Browser: Chrome
- Environment: Production

**Comment by Nikhil-Nandagopal** [comment] 2021-07-16 06:39
Duplicate of #2098

**Closed by Nikhil-Nandagopal** 2021-07-16 06:39 UTC
Labels: Actions, Actions Pod, Bug, High, Needs Triaging
