### ISSUE TITLE
GSheet Scope Drop Down Bug

### ISSUE THREAD

**Issue by PiyushPushkar02** [appsmithorg/appsmith#22576] opened 2023-04-20 04:19 UTC
Steps to reproduce:
1. Create a new google sheet data source 
2. Select Read/write all google sheets scope from drop-down menu
3. Now edit the data source name 
4. After changing the data source name click on whitespace anywhere.
5. Issue it will change the user selected scope to default one.

**Comment by sneha122** [comment] 2023-04-24 12:10
This issue exists in **production**. I investigated the issue a little bit and it does not seem straightforward and seems like a tech debt. Since this is a **legacy** issue, it would make sense to de priortise the issue, not take it up as part of gsheets project at this point and we can take it up as ad hoc issue later on CC: @rohan-arthur @sbalaji1192

**Comment by sbalaji1192** [comment] 2023-04-25 06:34
@sribalajig Please check the above comment.

**Comment by prapullc** [comment] 2023-05-02 09:49
@Ade : 
1) I observe that the scope of other DB changes when I click on white spaces. Refer the video for more clarity
https://www.loom.com/share/74adfac867754616afdfaef4d4edd05f

**Comment by Irongade** [comment] 2023-05-04 20:46
Hey @prapullc Thanks for this. This video actually shows that the issue has been resolved. Also, the authorization failing is a separate issue. It maybe possible that the service responsible for authorization was not working at the time or you tested this locally (dev.appsmith.com). Please add appropriate label to the PR.

**Comment by prapullc** [comment] 2023-05-05 02:48
Hey @Irongade 
That is right the basic issue is solved but also please observe that when user changes the name of the DB the scope of other DB also change and navigate to the default scope.

**Comment by Irongade** [comment] 2023-05-05 03:03
@prapullc Hi prapulla, that is expected behaviour because you haven't saved and authorized the new configuration you made. Unlike queries and Apis, Datasources don't autosave. so if you do not save them explicitly, they wont work. This behaviour is also consistent with release.

Hence, I'll be moving this back to needs QA. Please add appropriate label.

**Comment by AmanAgarwal041** [comment] 2023-05-09 14:38
Reopening this issue. The PR merged for this issue was creating authorization issues. The code is reverted in the [PR](https://github.com/appsmithorg/appsmith/pull/23113).

**Comment by Irongade** [comment] 2023-05-31 18:41
I tried to fix this issue but it didn't get resolved. I'll try again tomorrow. I'm bumping up the complexity estimation for this issue. 

cc: @rohan-arthur @sumitsum

**Closed** 2023-06-02 11:15 UTC
Labels: Google Sheets, BE Coders Pod, medium, Integrations Pod
