### ISSUE TITLE
[Bug]: Snowflake: There is not data on generating a page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#22041] opened 2023-04-03 12:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On generating a page with data, there is no data to be seen.

Refer to the video.

### Steps To Reproduce

1. Create a valid snowflake datasource
2. Check if the select query works and gives some data
3. Generate a page with data

Observe - The page has no data.

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/FaIOuiJ92TBhhS1j

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment] 2023-04-08 10:35
Duplicate of #7493

**Closed** 2023-04-08 10:35 UTC
Labels: Bug, High, Generate Page, New Developers Pod
