### ISSUE TITLE
[Bug]: submitting password reset fails

### ISSUE THREAD

**Issue by marijasiol** [appsmithorg/appsmith#18086] opened 2022-11-03 16:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a self-hosted instance, when a user tries to reset their password an email is sent and the link in the email navigates to a password reset page. When submitting a new password an `Internal server error` message appears. 

### Steps To Reproduce

1. go to `<host>/user/forgotPassword`
2. type in registered email and click reset
3. click on Reset Password link in email 
4. on reset password page (`<host>/user/resetPassword?token=<token>`), type in new password and click Reset 
5. password reset fails

backend.log stack:
`
[2022-11-03 15:58:04,196]  - Error clearing user sessions
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding 
serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 61707073
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:84)
        at org.springframework.data.redis.serializer.DefaultRedisElementReader.read(DefaultRedisElementReader.java:49)
        at org.springframework.data.redis.serializer.RedisSerializationContext$SerializationPair.read(RedisSerializationContext.java:272)
        at org.springframework.data.redis.core.DefaultReactiveHashOperations.readHashValue(DefaultReactiveHashOperations.java:353)
        at org.springframework.data.redis.core.DefaultReactiveHashOperations.deserializeHashEntry(DefaultReactiveHashOperations.java:357)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:886)
        at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291)
        at io.lettuce.core.output.StreamingOutput$Subscriber.onNext(StreamingOutput.java:64)
        at io.lettuce.core.output.KeyValueListOutput.set(KeyValueListOutput.java:72)
        at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:810)
        at io.lettuce.core.protocol.RedisStateMachine.handleBytes(RedisStateMachine.java:572)
        at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206)
        at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334)
        at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:841)
        at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:792)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:766)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:658)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 61707073
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36)
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:82)
        ... 39 common frames omitted
Caused by: java.io.StreamCorruptedException: invalid stream header: 61707073
        at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:935)
        at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:374)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:65)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:51)
        at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73)
        ... 41 common frames omitted`

### Version

Self Hosted 1.8.6

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5v6oc)

**Comment by Nikhil-Nandagopal** [comment] 2022-11-04 08:20
@kocharrahul7 I'm able to reproduce this as well. Can we please get someone to fix this?

**Comment by sharat87** [comment] 2022-11-04 11:44
@marijasiol, thank you for reporting this. I'm currently working to fix this.

From what I could see, when we submit the reset password form with the new password, we see an error message. However, if you open Appsmith in a new tab, and attempt to login with your new password, you should go through. The password reset is _actually_ happening. What seems to be failing is communicating that back to the user.

I'm still working to resolve this. But, can you confirm if the above is true for your case as well please? Thanks!

**Comment by sharat87** [comment] 2022-11-04 12:44
Partially fixed in https://github.com/appsmithorg/appsmith/pull/18108.

**Comment by juandl** [comment] 2022-11-19 18:21
not yet fixed #18149

**Comment by Nikhil-Nandagopal** [comment] 2022-11-21 10:20
@juandl it will be available in the next release

**Closed** 2022-11-22 12:31 UTC
Labels: Bug, Design System Pod, Login / Signup, High, Needs Triaging, New Developers Pod

**Comment by shadabbuchh** [comment] 2022-12-02 04:35
Verified this bug on Release. Working fine.
