### ISSUE TITLE
[Bug] Page hangs while binding Text Widget's Text property to a Table object

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7339] opened 2021-09-10 12:26 UTC
## Description

While binding Text Field of Text widget to a table object, the whole page hangs.
### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add a Table with a large data set e.g. for 500 records
2. Add a text widget'
3. Bind Text property of Text widget to the Table object
4. The whole page hangs.

Other scenario:

1. Add a table with a query that selects fewer records e.g. 10 records using limit in the query
2. Perform Step 2 and Step 3 from the above scenario, this time text in the widget will change and fill with the json object of Table record
3. Now change the query binded to the table by removing the limit and thus returning all the records or increase the limit to 500
4. Go back to the page and let the table reload with the new query.
5. Now again the page will hang, but this time closing the browser and relaunching the app will not fix the problem and your app will hang as soon as you launch it

### Important Details

- Version: Cloud
- Browser: chrome, safari
- Environment: production

**Comment by SatishGandham** [comment] 2021-09-14 15:14
Can't reproduce. I tried on a table with 5k records and 5 columns.
@kundansonu, How many columns does your source have.

This could be because the diff calculation was moved from worker to the main thread, for large data sets this can take time.

**Comment by Nikhil-Nandagopal** [comment] 2021-10-06 11:23
Closing this as we need more information

**Closed by Nikhil-Nandagopal** 2021-10-06 11:23 UTC
Labels: Bug, Table Widget, Performance, Widgets Pod, UI Building Pod, Text Widget, Needs Triaging, UI Builders Pod
