### ISSUE TITLE
[Bug]: System unresponsive while fetching large dataset from Gsheets

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#9902] opened 2021-12-21 08:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while fetching Datasets of around 10k rows with multiple columns from Google sheets, Appsmith app stuck and become unresponsive

Attaching video link:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/db3f850574324191bea3213ac5ce77d2-00001.gif)](https://www.loom.com/share/db3f850574324191bea3213ac5ce77d2)

### Steps To Reproduce

1. Create a gsheets api to fetch sheets rows
2. Paste the gsheets url which have large data entries
3. Set row limit to >1000
4. Hit run

Note: This test has  been run on Windows laptop

### Environment

Production

### Version

Cloud

**Comment by zzgvh** [comment] 2021-12-21 09:25
I can confirm this is an issue on a more powerful machine too. I'm developing on a stationary PC based around an AMD Ryzen 7 3700 CPU and lots of memory, so not ultra powerful, but good enough. It still takes fetching 1500 rows from a Google sheet about... forever! At least it feels like it; on Chrome it takes around 50 seconds, using Firefox it takes about twice that time! (V8 showing its prowess here I guess).

It seems it's the rendering of the dataset that takes so long. And this is one of the few places where Appsmith has chosen form over function, since the rendered data isn't even useful, you can't copy-paste it and use it as a list of JS objects which would be super handy!

Please fix this it is an almost daily annoyance. I have resorted to developing using mock data in the Google sheet, but sometimes you need to work with the real data and it's a pain. It would be fine if only the first and last 10 objects were rendered, since you can't use the data anyway. Of course it'd be even better with a fast, usable rendering of the whole dataset :wink: 

Oh, and when scrolling the data in Firefox just now I realise it hasn't even rendered the full dataset, so when scrolling you quickly come to a blank area and you get the in-browser notification that a script is taking a long time. And after a long wait you get to see a few more records...

**Comment by nidhi-nair** [comment] 2021-12-21 10:04
@Irongade would your changes to minimize all objects in the response array beyond the first n items solve this issue?

**Comment by Irongade** [comment] 2021-12-21 10:09
With my changes, it will take less time, However, 1000+ records is a lot, Delay would be noticeable by the user. Without my changes, I doubt it would even be possible. @nidhi-nair

**Comment by nidhi-nair** [comment] 2022-01-11 06:44
@zzgvh I'm a little curious about your use case here. We generally recommend implementing pagination for requests that work with large datasets. Is there any particular reason you'd want to pull in 1500 rows in one go?

**Comment by zzgvh** [comment] 2022-01-11 11:38
Hello @nidhi-nair! Yes I'm kind of abusing Google sheets. We run an indoor aquaponic farm and use Appsmith to register everything we plant. It's been an awesome tool, I've been able to build customized views for all events involved, from seed to harvest of our plants, along with supporting views to enter data listings like seeds, and data digests of various kinds.

That I'm using Google sheets as a database is an experiment. The idea is that it makes it easier for "non techies" to use the data. And it's been successful at that. I have a recurring job that exports copies of the sheets that my users have access to, and they use them for off-line stuff from time to time. It is also very convenient, as I can edit any data very, very easily. (Yes it's a little dangerous, but we're in startup mode and convenience beats safety still. This will surely change down the line.)

The largest sheet holds the data about every event in the farm, and is around 1900 lines at the moment, growing by about 200 per week. Currently I pull the full dataset and then apply some JS map-reduce to present the relevant data in our views. I could apply a filter on the datasource level, but even then I would pull over 1000 records as they are all "current" and are needed for the views.

Hope this gives a little insight into why someone would be stupid enough to use Google sheets as a database! (And yes, I have considered moving to Postgres... 😉)

To refer to the issue at hand, I see no performance issues with actually pulling and using the data in my apps. It's the interface to the datasources in the Appsmith editor that sucks 😛  as it is dog slow and not even useful as I've written above. And please take this comment with a glint in the eye. I love what you're doing and I think that's what makes the data source views so frustrating; they are comparatively bad to most of the rest of the framework!

**Comment by nidhi-nair** [comment] 2022-01-12 04:45
That sounds like a really nice app you've built. It'd be awesome if you could share glimpses of how you've designed the app! :)

Since you mention that the performance degradation is something you only notice on the query page, I think the changes that @Irongade is working on might help you. Ade, could you share the PR for your change here so @zzgvh could keep track?

**Comment by zzgvh** [comment] 2022-01-12 21:40
@nidhi-nair , I'd be happy to demo the app if you like! I find Appsmith a tool that appeals to me a lot, where many of the core ideas to make it easy to get something up and running that _actually gets the job done_, like how building a view is made so smooth and "incremental", really works for me. Thus I can more than live with the bugs and the quirks 😉 And you're also such an awesome team, the support discord is so friendly and helpful!

**Comment by leotom2000** [comment] 2022-02-08 17:34
Seems we need to prioritise this issue,  one more user reported this issue. In fact they are using columns upto 'CP' and around 1500 rows. That is leading to continuous unresponsive alerts.

**Comment by GreenFlux** [comment] 2022-02-09 12:52
I'm also affected by this with a dataset of only 400 rows. I tested in a new/empty app and only added this one API. The editor starts lagging as soon as the API gets back a response.

**Comment by nidhi-nair** [comment] 2022-02-14 08:29
PR to handle this on the query editor: https://github.com/appsmithorg/appsmith/pull/9629

**Closed** 2022-03-31 22:30 UTC
Labels: Bug, Actions Pod, Needs Triaging, BE Coders Pod
