### ISSUE TITLE
[Bug]: User Is unable to add the new mongo URI from the advanced tab

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#34333] opened 2024-06-19 08:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User Is unable to add the new mongo URI from the advanced tab
![image](https://github.com/appsmithorg/appsmith/assets/45958978/de65b80f-b634-47e2-ba59-2876a9ee643a)

### Steps To Reproduce

1. Pull the latest image
2. Open localhost
3. Go to admin setting
4. Go to advanced tab
5. Add the Mongo URI
6. click on dave and restart button
7. Bad request error toast is displayed

Note: when we add same the same URI from env it works

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

v1.28

**Comment by Nikhil-Nandagopal** [comment] 2024-07-22 04:30
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by Shivam-z** [comment] 2024-08-12 11:21
@Nikhil-Nandagopal @abhvsn @RakshaKShetty
The root cause of the issue was identified as the incorrect naming of the environment variable APPSMITH_MONGODB_URI, which should be APPSMITH_DB_URL. This misconfiguration has been corrected in https://github.com/appsmithorg/appsmith/pull/35526, which effectively resolves this bug too.

**Comment by abhvsn** [comment] 2024-08-12 23:53
@Shivam-z thanks for bringing this to the attention. As you rightly suggested this was indeed the problem with misconfiguration at the env level and above mentioned PR fixed this issue. Closing this now 👍🏽

**Closed by abhvsn** 2024-08-12 23:53 UTC
Labels: Bug, Admin Settings Product, High, Production, Needs Triaging, Platform Administration Pod

**Comment by Shivam-z** [comment] 2024-08-13 01:13
@abhvsn Thank you for closing this issue. Additionally, could you please review the [comment](https://github.com/appsmithorg/appsmith/issues/34332) addressing a similar issue?
