### ISSUE TITLE
[Bug]: Scroll issue when Date widget is open

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#14740] opened 2022-06-22 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the Date widget is open, the page scroll intermittently gets blocked below the open Date widget, and not able to scroll further down.

https://user-images.githubusercontent.com/11089579/175484289-bdc89157-f2b9-40c7-a919-9768bea69d3f.mov

### Steps To Reproduce

1. Have a page with multiple widgets, so that page requires scroll.
2. Have a Date widget in the middle.
3. Whenever Date widget is open, the page is not scrolling as intended.

### Version

Cloud

**Comment by dilippitchika** [comment] 2022-06-24 10:32
@techbhavin can you check this and let me know? I was unable to reproduce it clearly

**Comment by techbhavin** [comment] 2022-06-27 11:22
@dilippitchika  this issue is not reproduce from my side

**Comment by dilippitchika** [comment] 2022-07-05 06:30
@tomjose92 can you add the app here where we can check this out?

**Comment by ashit-rath** [comment] 2023-03-30 07:30
This issue doesn't seem to be reproducible. I'm closing this for now, feel free to open this if this still persists.

**Closed by ashit-rath** 2023-03-30 07:30 UTC
Labels: Bug, Needs More Info, Date Picker Widget, App Viewers Pod, medium
