### ISSUE TITLE
[Bug]: Extra field got added in JSON form when data binded with Table widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#27535] opened 2023-09-21 05:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On binding JSON Form with Table widget, we can observe that there is a new field added automatically while we type incomplete binding i.e {{Table1. }}

### Steps To Reproduce

1. Drag & Drop a Table widget
2. Drag & Drop a JSON Form
3. Try to Bind the Json form with Table widget using {{Table1. }}
4. Observe that extra field got added in JSON Form automatically which shows all properties of Table widget

### Environment

Production

### Issue video log

https://www.loom.com/share/c47f7ea78e4a4420a03ba319e41d2cb8?sid=3fce77ed-4e44-4e5f-8d07-eead6ceaf74e

### Version

Cloud/Production

**Comment by carinanfonseca** [comment] 2024-08-26 12:24
Closing this issue because it is not reproducible in production.

**Closed by carinanfonseca** 2024-08-26 12:24 UTC
Labels: Bug, Table Widget, Widgets Product, Production, Regressed, Needs Triaging, JSON Form, Medium, Widgets & Accelerators Pod
