### ISSUE TITLE
[Bug]: Barcode scanner widget not able to scan barcodes accurately and consistently

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#20935] opened 2023-02-24 06:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Barcode scanner widget is not able to read barcodes consistently. The 

### Steps To Reproduce

Drop a barcode scanner widget and try to scan some barcodes, randomly fails on a few attempts.

Front conversation: https://app.frontapp.com/open/cnv_wxhfymk?key=uyxJ7gAGodTLwL0V_HtRhgkZDK1_B0ni

### Version

1.9.8

**Comment by Nikhil-Nandagopal** [comment] 2024-03-06 09:44
Duplicate of #27131

**Closed by Nikhil-Nandagopal** 2024-03-06 09:44 UTC
Labels: Bug, Production, Needs Triaging, Medium
