### ISSUE TITLE
[Bug]: MongoDB: user gets "missing endpoint" error on doing test configuration after configuring another environment

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20262] opened 2023-01-31 12:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user configures a value for a different environment through manage env, and then if he clicks on "test configuration" for any of the environment, there is an error "missing endpoint".

### Steps To Reproduce

Steps:

1. add a mongo datasource
2. edit and do manage env
3. configure a different value for another env
4. bind the value
5. perform test configuration
observe -  missing endpoint error

### Version

1.9.5

**Comment by AnandShahs123** [comment] 2023-02-14 09:31
still hapenning @sondermanish

**Comment by sondermanish** [comment] 2023-02-20 06:03
not reproducible

**Comment by btsgh** [comment] 2023-02-20 08:41
As per discussion with @sribalajig  and @sondermanish - closing this as its not an issue.

**Comment by AnandShahs123** [comment] 2023-02-21 04:29
@sondermanish - attaching video. this remains opened as per discussion with @sondermanish and @btsgh 

https://knynrq7fk9.vmaker.com/record/Tn66wIzKUahKL2jO

**Comment by sondermanish** [comment] 2023-02-21 08:41
@ayushpahwa  @ChandanBalajiBP this happens due to client side not sending the id along with the datasourceConfig.

**Comment by sondermanish** [comment] 2023-03-02 09:26
Server side has to improve the error messages.

**Closed** 2023-03-10 08:38 UTC
Labels: Bug, High, Needs Triaging, Data Platform Pod, Datasource Environments
