### ISSUE TITLE
[Feature]: Allow pdf file navigation from local machine using navigateTo

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17607] opened 2022-10-17 07:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

<img width="861" alt="Screenshot 2022-10-17 at 12 39 33 PM" src="https://user-images.githubusercontent.com/13262095/196111442-199b72a7-89a7-4f82-878a-949270d29f71.png">

A user should be able to hyperlink to pdf file in their local disk

### Why should this be worked on?

Feature requested by EE user

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5bdcc)

**Comment by bharath31** [comment] 2022-10-19 08:18
Duplicate of #4878

**Closed by bharath31** 2022-10-19 08:18 UTC
Labels: Enhancement, Low, FE Coders Pod, Framework Functions
