### ISSUE TITLE
[BUG] Bad Request: Validation Failure

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#808] opened 2020-09-30 07:20 UTC
## Description

Submitted the "Create Organization" form without filling up anything in the "Name" field and got "Bad Request: Validation Failure" instead of a "Please enter a valid name" which is more user friendly. Also, saw two notifications on top right in the place of one. 

### Steps to reproduce the behavior:
Screencast: https://recordit.co/fJcyrtFBik

Submitted the "Create Application" form without filling a name in the field and got "Bad Request: Validation Failure" instead of a "Please enter a valid name" which is more user friendly. 

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment] 2020-09-30 10:01
duplicate of #604

**Closed by Nikhil-Nandagopal** 2020-09-30 10:01 UTC
Labels: Bug
