### ISSUE TITLE
[Bug]: Copy pasting Auth API credentials, sometimes adds leading whitespaces, server side should validate this and remove unnecessary whitespaces

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#19955] opened 2023-01-20 13:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In order to create Authenticated API DS, we are supposed to enter details like URL, Client ID and Client Secret. When we copy paste above values in the input field, it introduces leading whitespaces. So in case of URL and client ID, user can notice this manually but in case client secret, since this is a password field, user cannot notice the leading whitespaces. Thus authenticating such datasource leads to failure as whitespaces are considered as part of input data. 

Ideally server side should validate these fields and remove the unnecessary whitespaces that are getting added.

### Steps To Reproduce

1. Create Auth API DS
2. Fill in details like URL, client ID and client secret by copy pasting them from someplace else
3. Notice the whitespace introduced in client ID, URL

### Version

v1.9.3

**Comment by sribalajig** [comment] 2023-02-14 05:03
Duplicate of #19954

**Closed by sribalajig** 2023-02-14 05:03 UTC
Labels: Bug, Backend, High, BE Coders Pod, REST API plugin, Integrations Pod
