### ISSUE TITLE
[Bug]-[240]:Grouping widget causes newly formed container to shift to the bottom of the page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9646] opened 2021-12-08 08:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Grouping widget causes newly formed container to shift to the bottom of the page

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0f12a17c2cf7427a85811c1220302b18-00001.gif)](https://www.loom.com/share/0f12a17c2cf7427a85811c1220302b18)

### Steps To Reproduce

1. Drag and drop multiple widgets to the canvas and stretch them to the entire width of the canvas.
2. Select a couple of widgets as seen in the video and group them, observe the contained move to the bottom of the canvas when done so

### Environment

Release

### Version

Cloud

**Comment by marks0351** [comment] 2021-12-09 06:07
this is not a bug but a limitation which wud be full filled by reflow project since we will have an algorithm to move widgets around programmatically. will be tackling this as part of the Copy paste experience enhancement project. #5150

**Comment by IAmAnubhavSaini** [comment] 2022-01-30 06:47
This has a jarring effect.

https://user-images.githubusercontent.com/1573771/151689496-2ec7451d-d70e-4a5c-a3ae-a72ed7e20d50.mp4

And it is inconsistent too, notice in video below that first grouping keeps the components in same place, but later groupings throw new container way down. 

https://user-images.githubusercontent.com/1573771/151689566-e6d1f73f-499b-4e50-a8a8-c9f37f6f5e4a.mp4

The inconsistencies come from which component was selected first. If I select top component first (a), the new group jumps down, if I select bottom component first (b), the new group stays at same place. I guess (b) happens when there is no other component below the selected one.


https://user-images.githubusercontent.com/1573771/151689687-b6de1f28-cc6c-4681-9f80-2c2307b24824.mp4

**Comment by vuiets** [comment] 2022-04-25 04:07
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 60 |
| Effort (months)  | 0.5 |

For reach,
People grouping widgets in the last 6 months: 300
Assuming that about 20% of them are affected by this issue: 60

**Comment by Sripriya93** [comment] 2022-05-18 13:13
Verified, Moving to done

https://images.zenhubusercontent.com/275993885/4fa3c018-f081-46b2-b1bd-6f9b21f8e2e4/grouping___editor___appsmith___18_may_2022__1_.mp4

**Closed** 2022-05-20 13:57 UTC
Labels: Bug, UX Improvement, App Viewers Pod, High, Release, UI Building Pod, Container Widget, UI Builders Pod
