### ISSUE TITLE
[Bug] `ctrl+c` copy behaviour

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2175] opened 2020-12-12 15:06 UTC
## Description

When a user tries to copy content in the property pane, as the widget is selected and the user isn't focused in an input field, `ctrl+c` defaults to copying the widget. 

### Steps to reproduce the behaviour:
https://media.discordapp.net/attachments/760761686549463060/787297223263387688/copypasteIssueKeystrokes.gif

**Comment by mohanarpit** [comment] 2020-12-21 09:08
Closing as duplicate of #2261

**Closed by mohanarpit** 2020-12-21 09:08 UTC
Labels: Bug, Editor, Low, UI Building, community
