### ISSUE TITLE
[Bug] Change the visible property for list widget to "false: still the widget is visible

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5593] opened 2021-07-05 08:28 UTC
Observation: For visible property on list widget it's only invisible when the field is left blank

### Steps to reproduce the behaviour:

1. Drag and drop a list widget
2. Open the property pane
3. Click JS for visible property
4. Type any letter in the field "false" or "d"
5. Observe that list widget is still visible

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/39e189fd222c4f61a0d0c0cf8726c6bf

**Comment by jsartisan** [comment] 2021-07-27 12:01
Closing this as this is a duplicate of #5805

**Closed by jsartisan** 2021-07-27 12:01 UTC
Labels: Bug, List Widget, Needs Triaging, UI Building Pod, Widgets
