### ISSUE TITLE
[Bug]: Templates' app link redirects to sign in page for non signed in users

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15795] opened 2022-08-08 06:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For templates which are by default public, when accessed by user who has not signed in, redirects to sign in page instead of opening template in view mode.

### Steps To Reproduce

1. Fork a template
2. Publish and copy the app link
3. Sign out of the user
4. Paste the app link in new tab and observe
 

### Public Sample App

https://app.appsmith.com/app/applicant-tracker-3/1-track-applications-62f09b6cb2f8027edfbf84cc

### Version

Production

**Comment by kocharrahul7** [comment] 2022-08-08 06:43
Hey, @Parthvi12 is this the same as [this issue ](https://github.com/appsmithorg/appsmith/issues/12659)

**Comment by akash-codemonk** [comment] 2022-08-08 06:50
Closing as duplicate of https://github.com/appsmithorg/appsmith/issues/12659

**Closed by akash-codemonk** 2022-08-08 06:50 UTC
Labels: Bug, Production, New Developers Pod, Templates, medium
