### ISSUE TITLE
[Bug] "Invalid data" is displayed in  default date of date picker  

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#980] opened 2020-10-05 15:16 UTC
https://www.notion.so/Invalid-data-is-displayed-in-default-date-of-date-picker-8360811b8d76426e9c25d5f6cd6cc1b3

**Comment by Nikhil-Nandagopal** [comment] 2020-10-24 05:09
Duplicate of #752

**Closed by Nikhil-Nandagopal** 2020-10-24 05:09 UTC
Labels: Bug, Date Picker Widget, Frontend, Low, Release
