### ISSUE TITLE
[Bug]-[800]:Query fails with the error "mapper returned a null value"

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#5004] opened 2021-06-10 03:42 UTC
The dropdown widgets reports the error "Error: mapper returned a null value" occasionally on page load, although the binding given to the widget does resolve to the correct data. When this error comes up, the dropdown widget is empty.

When we refresh the page, the error is gone and the widget functions normally.

As reported in a Discord message:

> When I visit an app I've built with AppSmith, sometimes I get a message that says "Error: mapper returned a null value" (or something close to that) for one or more of the queries that run when I load the page and one of my drop downs that populate from the database won't have any values in it.  If I refresh the page everything loads correctly.  It seems to be a problem the first time I visit the page/app that day.  It doesn't appear to be a timeout issue since the page is loading in just a second or two and the queries should be quite fast.  I know it also happens to other people who are loading this app as well so it's not just me.  Is this a known issue and is there a solution to it?

Details of the binding behind such a dropdown widget:

> Sure.  Here's the screenshot.  This is the query: "SELECT id, name FROM attack_direction ORDER BY id" and it returns 5 records, always:
> 1, Front
> 2, Side
> 3, Rear
> 4, Top
> 5, Bottom

![](https://cdn.discordapp.com/attachments/760761686549463060/852372311976968192/Untitled2.png)

**Comment by bigwheels16** [comment] 2021-06-10 04:03
Some additional information, it is not specific to just this drop down.  Sometimes it happens on different drop downs or multiple drop downs at once.  I am not sure that is it limited to just drop downs and it may happen with other components as well.

**Comment by somangshu** [comment] 2021-06-10 04:37
The underlying problem might be the same as #4988

**Comment by bigwheels16** [comment] 2021-06-11 01:19
I just had it happen again.  I have three separate drop downs that are all populated with the same DB query called "version_list".  When the error happened, none of those three drop downs were populated and the exact error message that I got is this:

```
The action "version_list" has failed.
Error: "The mapper returned a
null value."
```

So based on this, it seems like it's more of an issue with the code that queries the database.  If I was to guess, I'd say maybe the database connection is going stale and that explains why it only happens after the app hasn't been used for a while.

**Comment by bigwheels16** [comment] 2021-06-11 01:26
I pulled the logs from the backend server this time.  Not sure why I didn't think to do that before, but I see several of these errors:

```
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
 - Connection has been closed by peer
 - Operator called default onErrorDropped
dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection unexpectedly closed
	at dev.miku.r2dbc.mysql.client.ClientExceptions.unexpectedClosed(ClientExceptions.java:32)
	at dev.miku.r2dbc.mysql.client.ReactorNettyClient.handleClose(ReactorNettyClient.java:260)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:257)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1871)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:359)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:268)
	at reactor.core.publisher.EmitterProcessor.checkTerminated(EmitterProcessor.java:489)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:350)
	at reactor.core.publisher.EmitterProcessor.onComplete(EmitterProcessor.java:293)
	at dev.miku.r2dbc.mysql.client.ReactorNettyClient.resumeError(ReactorNettyClient.java:215)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:424)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:210)
	at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:412)
	at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:437)
	at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:129)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
 - An exception 'reactor.core.Exceptions$BubblingException: dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection unexpectedly closed' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

**Comment by bigwheels16** [comment] 2021-06-11 01:28
There aren't dates in that log file so I can't correlate them to what happened.  There was also this error which was the most recent error:

```
java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1871)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onComplete(ObservableToPublisher.java:76)
	at com.mongodb.async.client.AbstractSubscription.onComplete(AbstractSubscription.java:154)
	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:225)
	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:172)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:105)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:89)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:174)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:118)
	at com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:89)
	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:227)
	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:172)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:105)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:89)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:169)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:118)
	at com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:89)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:53)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:46)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.OperationExecutorImpl$1$1$1.onResult(OperationExecutorImpl.java:94)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:827)
	at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:412)
	at com.mongodb.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:481)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:245)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:85)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:467)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:111)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:399)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:233)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:619)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:233)
	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:263)
	at com.mongodb.connection.netty.NettyStream.access$800(NettyStream.java:69)
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:322)
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:319)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by somangshu** [comment] 2021-06-11 05:38
Wow 👏, Thank you so much @bigwheels16 for such a detailed analysis and for bringing out the information here. This will help us a long way.

@ajinkyakulkarni please look into this.

**Comment by somangshu** [comment] 2021-07-01 09:50
@ajinkyakulkarni any update here?

**Comment by ajinkyakulkarni** [comment] 2021-10-06 10:20
@bigwheels16 is this still happening with you? Are there steps to reproduce it or it is still occurring sporadically?

**Comment by bigwheels16** [comment] 2021-10-22 01:06
Yes it's still happening.  It happens if the app hasn't been accessed for a while, perhaps a day or two.  My suspicion is that the database connection is timing out, and needs an extra refresh in order to re-establish the connection.  Take a look at the exception stack traces I pulled from the logs.

**Comment by Nikhil-Nandagopal** [comment] 2021-11-22 09:37
@sumitsum do we know the root cause and how to reproduce / fix it?

**Comment by rohan-arthur** [comment] 2022-04-17 05:03
6m incidence: 200

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment] 2022-12-08 07:05
Closing this since we haven't had a report of this in a while

**Closed by Nikhil-Nandagopal** 2022-12-08 07:05 UTC
Labels: Bug, Backend, Needs More Info, High, community, Core Query Execution, BE Coders Pod, Up for grabs, Data Platform Pod
