### ISSUE TITLE
[Docs] Add documentation on how to use the MS-SQL integration

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1316] opened 2020-10-20 09:32 UTC
## Documentation Link 

Need to add a section in our documentation that informs the user about Ms SQL server integration.

## Describe the problem

We've added Microsoft SQL Server as an integration to Appsmith. We need to have a page (similar to the [Postgres documentation](https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres)

## Describe the improvement

Please refer to the [contribution doc](https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md) to check out how to create documentation pages.

**Comment by Nikhil-Nandagopal** [comment] 2020-10-20 09:33
@mohanarpit duplicate of #1259

**Comment by alex-jitbit** [comment] 2020-12-14 20:44
How **MY**SQL is a duplicate of **!MS!** SQL? ;)

**Comment by Nikhil-Nandagopal** [comment] 2020-12-15 05:43
@alex-jitbit whoops my mistake must've misread the issue. Thanks for pointing this out 😅

**Comment by Aditya-Ramachandran** [comment] 2021-02-07 14:30
Hi, I would like to work on this issue, can you suggest me ways get started?

**Comment by Nikhil-Nandagopal** [comment] 2021-02-08 06:01
Hi Aditya,

The best place to get started would be to read our contribution guide :)
https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md

**Closed** 2021-02-10 05:13 UTC
Labels: Documentation, Enhancement, Good First Issue, hacktoberfest
