### ISSUE TITLE
[Bug]: JSON parse fail for execute API due to special characters in string.

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9992] opened 2021-12-24 12:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
<img width="1438" alt="Screenshot 2022-01-04 at 6 27 16 PM" src="https://user-images.githubusercontent.com/23132741/148062570-ab34d1f8-bb4c-406f-823d-f25a8ae1da3b.png">

When the user has an input widget added for multi-line input and the value entered has a newline character (because the user pressed enter and went to the next line in the input widget).

for eg - input is
```
first line
second line
third line
```

In this case, then sent this data in API call using run, the execute API fails as in backend JSON.parse fails. 

Solution:-
Will need to escape all special chars before running JSON.parse everywhere in the platform.

### Steps To Reproduce

1. Add input Widget to canvas
2. Create an API and bind input widget value to the request body
3. Enter below string in Input widget
```
first line
second line
third line
```
4. Add a button to submit API and hit Submit button.

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment] 2022-01-27 06:30
When sending multiple values via checkbox group widget, JSON fails to parse multiple values (array). 
![image](https://user-images.githubusercontent.com/79509062/151304088-309ece9a-0106-49af-8e9e-bafba7f7be9e.png)

**Comment by nidhi-nair** [comment] 2022-01-29 06:23
@Rishabh-Rathod is there a repro for this that you could help me with? I've tried using the newline in REST and Google sheets and both seem to work okay.

@ramsaptami same with the array. The array would work as is in a REST API where the body was a JSON because an array is a valid JSON input. But in Google Sheets all the values are expected to be a string.

**Comment by nidhi-nair** [comment] 2022-02-23 07:15
Closing as a non-issue. Please feel free to re-open in case any scenarios have been missed.

**Comment by Rishabh-Rathod** [comment] 2022-04-01 10:03
This is again reproducible in a discord user's application. @nidhi-nair 

Error response of execute API call
```
{"responseMeta":{"status":200,"success":true},"data":{"statusCode":"5006","title":"Invalid JSON found","errorType":"INTERNAL_ERROR","body":"Plugin failed to parse JSON \"{\n\t  \"rowIndex\": \"0\", \n\t\t\"first_name\": \"rishabh\",\n\t\t\"last_name\": \"dfgfg\",\n\t\t\"start_date\": \"dfgfg\", \t\n\t\t\"end_date\": \"dfggd\", \n\t\t\"training_block\": \"dfgfggdfg\", \n\t\t\"injury_flag\": \"\",\n\t\t\"teambuildr\": \"\",\n\t\t\"pt\": \"\",\n\t\t\"ep\": \"\",\n\t\t\"sc\": \"sdgfdsfgdsfg\r\nwefwef\r\nwefqwef\r\n\r\nweffwef\",\n\t\t\"dt\": \"\",\n\t\t\"pt_test\": \"\",\n\t\t\"ep_test\": \"\",\n\t\t\"sc_test\": \"\",\n\t\t\"dt_test\": \"\",\n\t\t\"athlete_manager\": \"drtgg\"\n}\" with error: Unable to parse request body. Expected a row object.","isExecutionSuccess":false,"dataTypes":[{"dataType":"RAW"}],"suggestedWidgets":[{"type":"TEXT_WIDGET","bindingQuery":"data"}]}}
```

**Comment by ramsaptami** [comment] 2022-05-05 08:16
If this is an expected response from Google Sheets then we should nudge the user about the expected behaviour so they can typecast. Helps enhance user experience on the platform

**Comment by Rishabh-Rathod** [comment] 2022-05-05 10:19
https://github.com/appsmithorg/appsmith/issues/9992#issuecomment-1085704441

We noticed for above user application, configuring smart substitution resolved the issue. @ramsaptami

**Closed** 2022-06-13 04:37 UTC
Labels: Bug, UX Improvement, Needs More Info, Needs Triaging, Query Execution, BE Coders Pod, Actions Pod, Datatype issue
