### ISSUE TITLE
[Bug]: Multiple Save/Discard columns are being created on changing the Update Mode.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#16913] opened 2022-09-20 11:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On changing the Update Mode several times, multiple Save/Discard columns are being created.

https://user-images.githubusercontent.com/109572422/191249722-f68cb96f-76ae-4ab9-a2b6-7f31acb87a15.mov

### Steps To Reproduce

1. D&D a Table widget.
2. Update all columns to be editable.
3. Change the Update mode by selecting Row level multiple times
4. Notice that several Save/Discard columns are getting created.

### Version

Production

**Comment by dilippitchika** [comment] 2022-09-21 04:32
Closing as duplicate of #15602

**Closed by dilippitchika** 2022-09-21 04:32 UTC
Labels: Bug, Table Widget, App Viewers Pod, High, Production, Needs Triaging
