### ISSUE TITLE
[Bug]: Total List items of List widget gets decreased by 1 and hence page numbers increases after doing widget reset

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#19754] opened 2023-01-12 08:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On doing widget reset action on list widget, it is observed that total `Listitems` are getting decreased by 1 and hence total number of pages get increased in List widget

### Steps To Reproduce

1. D&D List widget
2. Observe that no pagination is seen at first on List widget
3. D&D Button widget
4. Configure onClick event of Button widget: "{{resetWidget("List1",true)}}"
5. Click on Button to reset List widget
6. Observe that pagination appears and one List items been shifted to next page of List widget

### Issue video log

https://bthrujcsw8.vmaker.com/record/5FgqxIH7vorD2QbB

### Version

Cloud/ Production

**Comment by ashit-rath** [comment] 2023-01-12 08:53
@chandannkumar Can you verify if the issue is present in v2
DP -> https://appsmith-git-feat-list-widget-v2-get-appsmith.vercel.app/

**Comment by chandannkumar** [comment] 2023-01-12 09:07
> @chandannkumar Can you verify if the issue is present in v2? DP -> https://appsmith-git-feat-list-widget-v2-get-appsmith.vercel.app/

@ashit-rath  Works fine in Listv2

**Comment by Tooluloope** [comment] 2023-02-20 10:57
Fixed in https://github.com/appsmithorg/appsmith/pull/15839

**Closed by Tooluloope** 2023-02-20 10:57 UTC
Labels: Bug, App Viewers Pod, Production, List Widget, medium
