### ISSUE TITLE
[Enhancement]: To have back button in the property doc pane when multiple widgets are selected in canvas

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9227] opened 2021-11-18 07:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Suggestion to have back button in the property section

**Current behaviour:**
when the user selects multiple widget and chooses any of the widget property pane and selection on the canvas goes off and user needs to again select multiple widget 

**Expected result:**
If we have back button so user can can choose any of the widgets property pane by clicking on back button and the selection will also remains until user clicks anywhere on the canvas

https://loom.com/share/b3d9450e9b844ba48029941db8adfb0f

### Steps To Reproduce

1.Launch Appmsith app in release environment 
2.Drag and drop few widgets
3.Draw and select few widgets 
4.Try to select any of the widget property from the property doc pane and try to select any other an dobserve

### Environment

Deploy Preview

### Version

Cloud

**Comment by somangshu** [comment] 2022-02-21 10:27
We can see that the grouping goes away as soon as a widget is selected, This seems like it was intended.

**Comment by somangshu** [comment] 2022-02-21 10:28
@rahulramesha can you tell me if that is the case, Please close the issue in that case?

**Comment by rahulramesha** [comment] 2022-02-23 07:06
There seems to be a regression here, clicking on the widget button from the list of grouped widgets does not seem to open properties pane of that widget anymore. Opened a bug regarding [this](https://github.com/appsmithorg/appsmith/issues/11378).
cc: @YogeshJayaseelan
https://user-images.githubusercontent.com/71900764/155273045-29a5207b-de61-4433-8678-87bb2bbef266.mp4

**Comment by rahulramesha** [comment] 2022-05-16 10:32
Closing this, since in multi widget propertyPane, when one widget is selected other widgets get deselected.

**Closed by rahulramesha** 2022-05-16 10:32 UTC
Labels: Enhancement, Property Pane, Low, UI Building Pod, Needs Triaging, UI Builders Pod, Widget Grouping
