### ISSUE TITLE
[Bug] Number input field set to 0 is not valid until "wiggled"

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#7899] opened 2021-09-28 11:36 UTC
## Description

In the attached app, the form will not validate unless the Input widgets set to 0 are changed to 1 and then back to 0.

### Steps to reproduce the behaviour:

Run the app and follow the text by the inputs :smiley: 

### Important Details

[Validation bug.txt](https://github.com/appsmithorg/appsmith/files/7243557/Validation.bug.txt) Change the extension to .json!

- Version: Cloud
- OS: Linux mint 19
- Browser Firefox
- Environment production

**Comment by Nikhil-Nandagopal** [comment] 2021-09-30 10:48
@zzgvh I'm not able to reproduce this and get the form to validate in any case. Can you share a video?

**Comment by zzgvh** [comment] 2021-09-30 16:14
I'm sorry, maybe my instructions weren't the clearest. Anyways, here's a video that shows the problem. Note the hidden input, Validator, that has the default text "Submit". It has a regex that emits "Submit" if the sum of the four number inputs is between 0 and 32, inclusive, otherwise it emits "Invalid". That way I have a "central" form widget that controls if the total is permissible. But as you see in the video, the Submit button is still disabled when the sum is 32. Until I jiggle the two fields with 0!

I did some more messing around today with inputs with the Number data type and the result is issue #8012. I'm pretty sure the issues I posted here and the ones in 8012 are related and very likely manifestations of the same underlying issue.

https://user-images.githubusercontent.com/142613/135492493-2764e8cb-b0e0-47d1-a290-622dad461f31.mp4

**Comment by Nikhil-Nandagopal** [comment] 2021-11-09 07:11
I'm able to reproduce this when the input is marked as required
@aswathkk @somangshu

**Comment by zzgvh** [comment] 2021-11-09 07:16
It seems likely this bug is closely related to #8012.

**Comment by Nikhil-Nandagopal** [comment] 2021-11-10 08:28
https://user-images.githubusercontent.com/3897254/140878496-f760263c-612f-4742-b776-d26444e3383d.mov

**Closed** 2022-01-20 05:25 UTC
Labels: Bug, Input Widget, App Viewers Pod, High, UI Building Pod, community, Needs Triaging, Widget Validation
