### ISSUE TITLE
[Bug] Refactoring a widget name, renamed a non-reference in the api url

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2098] opened 2020-12-09 07:25 UTC
## Description
When refactoring a name, we should only refactor references inside a binding

### Steps to reproduce the behaviour:
1. Name a widget class
2. Have an api with the following url `https://domain/v1/api/class`
3. Rename with widget name to something else
4. Issue: The url also updated

**Comment by hetunandu** [comment] 2020-12-09 07:25
@srijanshetty Please add more info here if necessary

**Comment by Nikhil-Nandagopal** [comment] 2020-12-09 13:47
@hetunandu are you able to reproduce this?

**Comment by srijanshetty** [comment] 2020-12-10 16:42
@Nikhil-Nandagopal and @hetunandu, realized that this bug is hit on a very strange edge case. Steps to reproduce:

1. Create an API called `getTrials` which is a `POST` request to an endpoint `https://something/api/v1/trials`.
2. Add a payload of the form:

`
{
    "trials": "{{trials}}"
}
`
3. Now create a widget with a name `trials`.
4. Now renaming the name of the widget from `trials` to `trialz` will rename the endpoint, payload and widget.

Things to note:

1. This works with a POST request if and only if it has a payload which has a key called `trials`, the lack of such a key does not cause the bug to be reproduced. So probably it's linked to refactoring the payload.

**Comment by trishaanand** [comment] 2020-12-10 17:59
This is actually because of the way refactor has been implemented. Currently we are doing a string replace across the entire object leading to incorrect refactoring. The correct way to do this would be to only do string replace inside the dynamic bindings.

**Comment by Nikhil-Nandagopal** [comment] 2021-07-28 10:09
@trishaanand @ajinkyakulkarni another user reported this

**Comment by ajinkyakulkarni** [comment] 2021-07-28 17:27
@hetunandu were you planning to solve this by implementing parsing and creating AST (https://github.com/appsmithorg/appsmith/issues/2435) to identify types correctly?

**Comment by Nikhil-Nandagopal** [comment] 2021-07-29 05:45
@hetunandu Can we not simply run the replacement only inside bindings for now?

**Comment by hetunandu** [comment] 2021-07-29 05:59
@Nikhil-Nandagopal @ajinkyakulkarni a simpler solution would be to use the already extracted bindings and running refactor on them but that would still have issues as there could be strings defined in the bindings which match the entity we want to refactor. A more complete solution would need AST inside bindings

**Comment by Nikhil-Nandagopal** [comment] 2021-07-29 08:17
@hetunandu agreed with this solution for now if it's simple to implement

**Comment by ChandanBalajiBP** [comment] 2023-02-14 10:36
This issue is resolved in this [EPIC](https://github.com/appsmithorg/appsmith/issues/17047)

**Closed by ChandanBalajiBP** 2023-02-14 10:36 UTC
Labels: Bug, Backend, Low, community, BE Coders Pod, Entity Refactor, Data Platform Pod
