### ISSUE TITLE
[Bug]: Min Date property of Date widget is by default in error state

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10385] opened 2022-01-13 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Date picker widget that's added to the canvas shows an error for Min Date property by default

![image](https://user-images.githubusercontent.com/79509062/149300048-6998a0d2-7caf-4890-897b-eaa57999d802.png)

### Steps To Reproduce

1. Add a date widget to the canvas and observe the `Min Date` field in error state. It clears when the field is clicked on and if user clicks away on the canvas and returns back to the widget, `Min Date` shows up in error state again

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment] 2022-01-13 10:47
duplicate of #10187

**Closed by somangshu** 2022-01-13 10:47 UTC
Labels: Bug, Date Picker Widget, App Viewers Pod, Low, Release, UI Building Pod
