### ISSUE TITLE
[Enhancement] Custom CSS + Option to pass custom class to widgets

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3184] opened 2021-02-24 07:34 UTC
Users familiar with CSS would want to overwrite the styling of widgets. A place to write custom CSS and an option to pass the custom class to widgets would be great.

**Comment by somangshu** [comment] 2021-04-14 06:33
@jsartisan should this instead be achieved through the themification option we are thinking about?

**Comment by sbalaji1192** [comment] 2021-11-16 11:20
Closing this as it is a duplicate of https://github.com/appsmithorg/appsmith/issues/3095 (moving this issue's description to the other issue.)

**Closed by sbalaji1192** 2021-11-16 11:20 UTC
Labels: Enhancement, App Viewers Pod, UI Building Pod, community

**Comment by ichik** [comment] 2024-01-09 11:08
@nikosgpet Hi. We've been working on a revamp of our layout and theming engines that should facilitate faster, more predictable, and more consistent styling of the widgets. While that is still work-in-progress the team wants to properly evaluate a common request for custom CSS, that has been asked by the community.
To that end I'd be interested in talking with you, to see what kind of ideas you have.
You can schedule [a call with me](https://www.getclockwise.com/c/vadim-appsmith-com/quick-meeting) if you're willing to talk or [drop me an email](mailto:vadim@appsmith.com).
